### ISSUE TITLE
InvalidMediaFileType error when sending videos

### ISSUE THREAD

**Issue by tcortega** [open-wa/wa-automate-nodejs#1000]
**Describe the bug**
When I try to send videos, such as videos from twitter, I get an error of 
Something went wrong Error: Evaluation failed: Error: InvalidMediaFileType: ExtendableError

**Steps to Reproduce**
Just try to send a video, I'll give the code down there:

**create() code**
This is the code you use to create the client. e.g
```javascript
await client.sendFileFromUrl(from, "https://video.twimg.com/ext_tw_video/1322318527609462784/pu/vid/320x384/MNazoaPGn4RMWizD.mp4", 'video.mp4', `teste`, null, null, true)
.catch((err) => console.error(err))
```

**Expected behavior**
It'll give you an error. Same error I told you before.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
WA_VERSION: '2.2043.8',
PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
WA_AUTOMATE_VERSION: '3.0.6',
BROWSER_VERSION: 'HeadlessChrome/87.0.4272.0'                 
}
```

**Screenshots**
No need

**Host (please complete the following information):**
 - OS: Android

**Comment by smashah** [comment]
@tcortega can you provide some more details of the OS that you're running the code on (not your mobile os). Also, can you confirm that the get request for the URL is working by trying it in curl

**Comment by tcortega** [comment]
> @tcortega can you provide some more details of the OS that you're running the code on (not your mobile os).

I'm using Windows 10 Pro v2004. OS Compilation versin is 1904.572.

The link you can see in the code is the download link I'm attempting, and seems to be working just fine with CURL
![image](https://user-images.githubusercontent.com/60912483/97786620-8c1c4880-1b8b-11eb-83c2-dae2b2cd5fb9.png)

**Comment by tcortega** [comment]
Fixex, I was missing useChrome parameter on config object.

**Comment by aidilaryanto** [comment]
> Fixed, I was missing useChrome parameter on config object.

How to fix?

**Comment by aidilaryanto** [comment]
![Screenshot_20201102-180030528](https://user-images.githubusercontent.com/57789597/97855216-692d9800-1d35-11eb-8d4d-3799c15df911.jpg)

**Comment by smashah** [comment]
@aidilaryanto make sure you have installed chrome on your machine.

**Comment by aidilaryanto** [comment]
> @aidilaryanto make sure you have installed chrome on your machine.

Already installed

**Comment by Kry9toN** [comment]
> @aidilaryanto make sure you have installed chrome on your machine.

which version you install chrome

**Comment by aidilaryanto** [comment]
> > @aidilaryanto make sure you have installed chrome on your machine.
> 
> which version you install chrome

Latest

**Comment by smashah** [comment]
@aidilaryanto please fill in the issue tempalte. And if you're using code from another repo then make the issue there instead.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
