### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by umeshnaga** [open-wa/wa-automate-nodejs#1001]
hi
   today I have buy license for me. it got following error 

License issue: Expected 8844 but this account is 1728

Please Help Me

**Comment by smashah** [comment]
@umeshnaga you've entered the incorrect number at checkout. Please follow these instructions to change to the corect number

https://open-wa.github.io/wa-automate-nodejs/pages/The%20Client/licensed-features.html#switching-your-host-account

**Comment by umeshnaga** [comment]
Hi
   i have enter for my personal number for buying licence but I have required another number please change this

   Current no -   +919950448844
    Correct Number -   +919829271728




Umesh Naga
