### ISSUE TITLE
Feature: Callbacks should consume Webhook URL and optionally a request config

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#1002]
This will be super useful to easily manage webhooks via the existing CLI.

- [x] First param can be POST webhook URL

- [x] Second param optionally can be request config (for simple webhook authentication)

- [x] New method to get all current webhooks: `client.getWebhooks()`

- [x] New method to remove a specific webhook from a listener: `client.removeWebhook(listener, webhook)`

**Comment by smashah** [comment]
related #963

**Comment by joedutra** [comment]
I come to apologize and say that we have nothing against this, only that they accuse us of copying and we never copied anything, if someone copied it was when someone changed our lib, I apologize and the intention was not to be slandered anymore of copying something we worked on every day. just like you, we will not do that anymore.

**Comment by smashah** [comment]
Extension of #1175 which was implemented in the latest version:

https://github.com/open-wa/wa-automate-nodejs/releases/tag/3.1.9

Documentation:

https://docs.openwa.dev/classes/client.html#registerwebhook
