### ISSUE TITLE
Feature Proposal: `client.sendVideoAsSticker`

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#1003]
You're not able to respond to gifs with a sticker of that gif because gifs in WA are actually mp4s. The ability to easily convert mp4s to stickers may be a fun feature to have for short videos.

If there is enough demand for this feature I'll implement it as part of the library in the next version.

If you'd like this issue then comment with +1.

**Comment by tcortega** [comment]
+1

**Comment by Storm3r** [comment]
+1

**Comment by Waxaranai** [comment]
+1

**Comment by smashah** [comment]
@Waxaranai @Storm3r 

https://twitter.com/smashah/status/1323047255486717954

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
https://open-wa.github.io/wa-automate-nodejs/classes/client.html#sendmp4assticker

This will only work with mp4s

**Comment by tcortega** [comment]
> https://open-wa.github.io/wa-automate-nodejs/classes/client.html#sendmp4assticker
> 
> This will only work with mp4s
> 
> please provide feedback

Seems to be working perfectly!

**Comment by Waxaranai** [comment]
> https://open-wa.github.io/wa-automate-nodejs/classes/client.html#sendmp4assticker
> 
> This will only work with mp4s
> 
> please provide feedback

Are we need to install ffmpeg and libwebp first to our machine?

**Comment by smashah** [comment]
@Waxaranai yes, latest versions of ffmpegs should have libwebp built in but if you see errors then it's maybe because you're missing libwebp

**Comment by Waxaranai** [comment]
> @Waxaranai yes, latest versions of ffmpegs should have libwebp built in but if you see errors then it's maybe because you're missing libwebp

Alright, i'll try then
