### ISSUE TITLE
client.sendPtt and client.sendAudio doing nothing

### ISSUE THREAD

**Issue by tcortega** [open-wa/wa-automate-nodejs#1015]
**Describe the bug**
I was testing both client.sendPtt and client.sendAudio, and they don't seem to work, or maybe my usage is just wrong?

**Steps to Reproduce**
```javascript
const pttResult = await client.sendPtt(from, 'http://95.217.115.50/xf/r8/eEVJjA_JMwhCSWd7_ELNeA,1604321640/yt:FrkKWJjvWaI-1/Teru%20vs%20Shimazaki%20%20Mob%20Psycho%20100%20II.mp3', id)
console.log(pttResult)
const audioResult = await client.sendAudio(from, 'http://95.217.115.50/xf/r8/eEVJjA_JMwhCSWd7_ELNeA,1604321640/yt:FrkKWJjvWaI-1/Teru%20vs%20Shimazaki%20%20Mob%20Psycho%20100%20II.mp3', id)
console.log(audioResult)
```

**create() code**
This is the code you use to create the client. e.g
```javascript
const headless = true;
create({
        licenseKey: '######################',
        headless: headless,
        qrRefreshS: 20,
        qrTimeout: 0,
        authTimeout: 0,
        autoRefresh: true,
        restartOnCrash: start,
        cacheEnabled: false,
        logConsole: true,
        useChrome: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false
    }).then((client) => start(client))
    .catch((err) => new Error(err))
```

**Expected behavior**
It'll log into console 2 messages, but it will do nothing in the chat.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2043.21',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.0.8',
  BROWSER_VERSION: 'HeadlessChrome/86.0.4240.111'
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/60912483/97866810-6dcd5e80-1ceb-11eb-831c-0c0b9e59f31c.png)

**Host (please complete the following information):**
 - OS: Windows 10 Pro v2004. OS Compilation version is 1904.572

**Additional context**
Console logged constants:
true_55#########5@c.us_3EB0D4########684B3B
true_55#########5@c.us_3EB082########43B6EF

**Comment by smashah** [comment]
if it logged the message IDs then it should be working. What is happening that you think it is not working? Your screenshot is unclear as to when you expect the audio to be sent (what's meant to be triggering it?).

Also, I checked that URL and for 403 forbidden.

Can you check using the URL in the demo as that is working consistently:

https://github.com/open-wa/wa-automate-nodejs/blob/54334d9089ac2c084c87ec52ebaba9f126dba751/demo/index.ts#L119

You seem to be having a lot of issues. I would suggest using a mac or ubuntu machine instead of windows

**Comment by tcortega** [comment]
I'm too used to windows xD.
But it's working just fine, it's probably something to do with the audio link I was trying.

And sorry for opening that many issues, but I'm adventuring myself through the lib xD
