### ISSUE TITLE
addComplated_deleted error Error: Protocol error (Target.closeTarget): Target closed.

### ISSUE THREAD

**Issue by realunreals** [open-wa/wa-automate-nodejs#1023]
**Describe the bug**
I have restart the my project today and I have received error "**addComplated_deleted error Error: Protocol error (Target.closeTarget): Target closed.**". I have tested on version 2.1.6 and 3.0.9. I have restarted 20 times and I have received 5 times same error ( I have received this error 20% of restart). Please check screenshots.

**Edit**: I'm receiving this error on **WA_VERSION '2.2045.11'**,   no error on WA_VERSION '2.2043.21'  

**create() code**
const weboptions = {
		sessionId:'test',
		useChrome: true,
		headless:true,
		throwErrorOnTosBlock:false,
		qrTimeout:40,
		authTimeout:40,
		killProcessOnBrowserClose: false,
		autoRefresh:true, //default to true
		qrRefreshS:15, 
	};

**Screenshots**

**### Version 3.0.9**
<img width="1355" alt="Screen Shot 2020-11-03 at 18 55 58" src="https://user-images.githubusercontent.com/13606459/98014013-27bbec00-1e0c-11eb-846c-7c0c0a2594fd.png">

**### Version 2.1.6**
<img width="1375" alt="Screen Shot 2020-11-03 at 19 29 32" src="https://user-images.githubusercontent.com/13606459/98014069-3a362580-1e0c-11eb-98da-5f93d0b16864.png">

**Comment by smashah** [comment]
@realunreals thanks for filling the template. can you try with 

https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#skipbrokenmethodscheck


Set to true on your config please

**Comment by realunreals** [comment]
Thanks, I will try now

**Comment by realunreals** [comment]
Same error on WA_VERSION '2.2045.11'

**Comment by smashah** [comment]
@realunreals Can you report back the frequency of this error now, please.

There are some weird issues right now where people can restart their session and get either one of these versions.

 - 2.2043.21
 - 2.2045.11
 - 2.2045.12
 - 2.2045.13

**Comment by realunreals** [comment]
I have restarted the application 40 times now. Please check below.

38 X **2.2043.21** -> No Error
1 X **2.2045.11** -> Same Error
1 X **2.2045.13** -> Same Error

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.0.11](https://github.com/open-wa/wa-automate-nodejs/compare/3.0.10...3.0.11) (2020-11-04)

- Release 3.0.11 [`7328a32`](https://github.com/open-wa/wa-automate-nodejs/commit/7328a326f0b1745a882ff2d13933acbcffa72e98)
- Check page exists before calling close(), added error logging on auth #1023 [`9a2d50c`](https://github.com/open-wa/wa-automate-nodejs/commit/9a2d50c7dce95eb13b4ac52c79bcf4fc38dcc75c)

**Comment by smashah** [comment]
@realunreals latest update should prevent the Target Closed error and make it easier to understand what's going wrong

**Comment by realunreals** [comment]
I will try now.

**Comment by realunreals** [comment]
@smashah  please check below screenshot.

<img width="1335" alt="Screen Shot 2020-11-04 at 14 51 45" src="https://user-images.githubusercontent.com/13606459/98108762-92713400-1ead-11eb-8bb6-248de004d4c9.png">

**Comment by smashah** [comment]
@realunreals are you running multiple clients in one process?

**Comment by realunreals** [comment]
No only one

**Comment by realunreals** [comment]
But chrome also creating 2-3 more process in the background. It was always like this.

**Comment by smashah** [comment]
Yeah sorry @realunreals but there's a lot of context that is still missing here. If you want this error fixed you'll need to share your code, and a screen capture video of what's going on with `headless: false`.

I'm going to close this, can you please fill in the issue template with all information and the requested evidence. Please reference this issue in the new one.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️

**Comment by smashah** [comment]
Continued in #1028
