### ISSUE TITLE
decryptMedia throws error on trying to decrypt MP4 / Video

### ISSUE THREAD

**Issue by D3DDLOCK** [open-wa/wa-automate-nodejs#1027]
Using the following code on an embedded gif (mp4 video) throws an error.

### Code:
const mediaData = await decryptMedia(message, uaOverride)
const mp4_as_sticker = await client.sendMp4AsSticker(message.from, mediaData);

### Error:
`[ERROR] Error: message is missing critical data needed to download the file.`

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
