### ISSUE TITLE
Broken methods detected. Attempting repair

### ISSUE THREAD

**Issue by can1871** [open-wa/wa-automate-nodejs#1035]
#1029 

----------
EV Checking client integrity customer-support STARTUP
----------

----------
EV Broken methods detected. Attempting repair. customer-support STARTUP
----------
�  Broken methods detected. Attempting repair.
----------
EV Unable to repair. Reporting broken methods. customer-support STARTUP
----------
× Unable to repair broken methods. Sometimes this happens the first time after a new WA version, please try again. An issue has been created, add more detail if required: https://github.com/open-wa/wa-automate-nodejs/issues/1029

----------
EV Unable to repair broken methods. Sometimes this happens the first time after a new WA version, please try again. An issue has been created, add more detail if required: https://github.com/open-wa/wa-automate-nodejs/issues/1029 customer-support STARTUP
----------

----------
EV {
  WA_VERSION: '2.2045.15',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '2.0.25',
  BROWSER_VERSION: 'Chrome/86.0.4240.111',
  LAUNCH_TIME_MS: 15523
} customer-support DebugInfo
----------

----------
EV  customer-support STARTUP
----------
√ Client loaded in 15.523s

----------
EV Client loaded in 15.523s customer-support STARTUP
----------

----------
EV  customer-support STARTUP
----------

----------
EV Installing patches customer-support STARTUP
----------
√ Patches Installed

----------
EV Patches Installed customer-support STARTUP
----------

----------
EV Checking License customer-support STARTUP
----------
�  Checking License
----------
EV Evaluation failed: ReferenceError: STOP is not defined
    at eval (eval at <anonymous> (:1:27), <anonymous>:1:1)
    at __puppeteer_evaluation_script__:1:27 customer-support STARTUP
----------
Shutting Down

**Comment by can1871** [comment]
@BenSchZA @smashah

**Comment by smashah** [comment]
You're using an ancient version of the library. Make sure to keep it up to date

**Comment by can1871** [comment]
> Kütüphanenin eski bir versiyonunu kullanıyorsunuz. Güncel tuttuğunuzdan emin olun

what is the last version

**Comment by smashah** [comment]
@can1871 3.0.12

```
npm i --save @open-wa/wa-automate@latest
```

**Comment by can1871** [comment]
> npm i --save @open-wa/wa-automate@latest

npm i @open-wa/wa-automate@1.9.103

When I installed this it was fixed

**Comment by smashah** [comment]
@can1871 please update your library version. Don't use such old versions of the library as it will just cause more problems.

If you don't want to update and don't want to see this error then please set 

```skipBrokenMethodsCheck: true```
