### ISSUE TITLE
Feature: Message Collector (wait for reply)

### ISSUE THREAD

**Issue by tcortega** [open-wa/wa-automate-nodejs#1042]
A feature similar to discord's message collector, that can collect the message based on conditions and for a specified time, that way you can keep a dialog alive with certain users, expecting for issues.

Discord documentation about MessageCollector for reference: 
https://discord.js.org/#/docs/main/stable/class/MessageCollector

**Comment by joedutra** [comment]
<img src="https://media.giphy.com/media/sNZddQMtrqpS0HEEMC/giphy.gif"></img>
Man, you know it sucks, how we copy your repo, if we have functions that you don’t even have, all for free, we perform almost every day, I came from Sulla and you too, but if you look at following the week, we redid it all lib again, now you will no longer be able to copy us, you copy and keep saying that we copy, nor compete with you ours and for free and your payment

**Comment by tcortega** [comment]
> ![](https://camo.githubusercontent.com/630e8919e368dd2f0865e9e3b8ae6c24c9bd6d0e9ea0457b21b6e8a1afce8327/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f734e5a6464514d7472717053304845454d432f67697068792e676966)
> Man, you know it sucks, how we copy your repo, if we have functions that you don’t even have, all for free, we perform almost every day, I came from Sulla and you too, but if you look at following the week, we redid it all lib again, now you will no longer be able to copy us, you copy and keep saying that we copy, nor compete with you ours and for free and your payment

?????????????????????????????????????????????

**Comment by joedutra** [comment]
I come to apologize and say that we have nothing against this, only that they accuse us of copying and we never copied anything, if someone copied it was when someone changed our lib, I apologize and the intention was not to be slandered anymore of copying something we worked on every day. just like you, we will not do that anymore.

**Comment by Dargon-dev** [comment]
any example in code form?

**Comment by smashah** [comment]
TODO:

- [ ] Config property to bundle all client listeners in an event emitter.

**Comment by Urbaeexyz** [comment]
> TODO:
> 
> * [x]  Config property to bundle all client listeners in an event emitter.

![image](https://user-images.githubusercontent.com/75126993/107320896-32a1af00-6ad4-11eb-9909-86e01f8cd955.png)

```
case 'sticker':
        case 'stiker':
        case 'stc':
            if ((isMedia || isQuotedImage) && args.length === 0) {
                const encryptMedia = isQuotedImage ? quotedMsg : message
                const _mimetype = isQuotedImage ? quotedMsg.mimetype : mimetype
                const mediaData = await decryptMedia(encryptMedia, uaOverride)
                const imageBase64 = `data:${_mimetype};base64,${mediaData.toString('base64')}`
                aruga.sendImageAsSticker(from, imageBase64, {keepScale: true})
                .then(() => {
                    aruga.reply(from, 'Here\'s your sticker')
                    console.log(`Sticker Processed for ${processTime(t, moment())} Second`)
                })
                } else {
                      await aruga.reply(from, 'Format pesan salah...', id)
                     }
                break

**Comment by smashah** [comment]
@Urbaeexyz if you keep spamming unrelated issues then I'm going to have to block you from this repo. Do not do this again. If you have a quick question, use the discord.

You need to use this to decrypt sticker messages: https://docs.openwa.dev/classes/client.html#getstickerdecryptable

**Comment by Urbaeexyz** [comment]
> @Urbaeexyz if you keep spamming unrelated issues then I'm going to have to block you from this repo. Do not do this again. If you have a quick question, use the discord.
> 
> You need to use this to decrypt sticker messages: https://docs.openwa.dev/classes/client.html#getstickerdecryptable

oh

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.9.13](https://github.com/open-wa/wa-automate-nodejs/compare/3.9.12...3.9.13) (2021-03-21)

- 📝 collector docs #1042 [`02ddbf6`](https://github.com/open-wa/wa-automate-nodejs/commit/02ddbf62eac0b0dfb41058acbce549c634b1feaa)
- ✨ implemented `client.createMessageCollector` #1042 [`bed4c4b`](https://github.com/open-wa/wa-automate-nodejs/commit/bed4c4b100bf67410af8bf607a1df84188617ed9)
- Release 3.9.13 [`6178f8c`](https://github.com/open-wa/wa-automate-nodejs/commit/6178f8c600bab8c5ae68d64383742b8fadaa7344)
- ✨ feat: implemented `onChatDeleted` #1504 [`8b05581`](https://github.com/open-wa/wa-automate-nodejs/commit/8b055813774848d78a05ccffb7f510b05d56e7d0)
- 📝  added docs for `getChatsByLabel` [`606df4e`](https://github.com/open-wa/wa-automate-nodejs/commit/606df4e7f484745b50e3cd96464e6ae9efc3c508)
- 🥚  labels patch [`3c66c15`](https://github.com/open-wa/wa-automate-nodejs/commit/3c66c153de9dec69d4804b6419f7b1bf5910270c)
- 🥚 patch update [`0a8254a`](https://github.com/open-wa/wa-automate-nodejs/commit/0a8254a707d13f8674b05ddf9cb56c2e09501b37)
- 🚸 added `GROUP_FULL` error status code [`272d81a`](https://github.com/open-wa/wa-automate-nodejs/commit/272d81a39356d6bbfbeec1e99c3dcd89fde20f81)

**Comment by smashah** [comment]
@tcortega @Dargon-dev @shubham0804 @lxndr-rl you can now use `client.createaMessageCollector` to make a discord-like message collector

Example 1: I want maximum 2 images over the next 15 seconds with at least 1 every 5 seconds.

```javascript
const collector = client.createMessageCollector(message, (m: Message) => m.type === MessageTypes.IMAGE, {
    /**
     * Only collect for 15 seconds.
     */
    time: 15000,
    /**
     * If 2 messages are collected then end the collector
     */
    max: 2,
    /**
     * If 5000ms goes by without an answer then end the collector
     */
    idle: 5000
});

collector.on('collect', async message => {
    await client.sendText(message.from, `Got a message ${i++}, ${message.type}`)
})

collector.on('end', async (collected, reason) => {
    console.log(`Collected ${collected.size} items`);
    await client.sendText(message.from, `Collected ${collected.size} items ${reason}`)
})
```

Example 2: Give me the next 5 replies over the next 30 seconds


```javascript
const questionId = await client.send('Reply to this with your name. First 5 win.');
const collector = client.createMessageCollector(message, (m: Message) => m?.quotedMsgId === questionId, {
    /**
     * Only collect for 30 seconds.
     */
    time: 30000,
    /**
     * If 5 messages are collected then end the collector
     */
    max: 5,
});

collector.on('collect', async message => {
    await client.sendText(message.from, `Hello ${message.body}`)
})

collector.on('end', async (collected, reason) => {
	if(reason == 'time') {
		await client.sendText(message.from, 'timeout. Here are the winners ....');
	}
	if(reason == 'limit') {
		await client.sendText(message.from, 'Got 5, the winners are...');
	}
})
```


You can learn more about the inspiration (read, source) of this feature here: https://discordjs.guide/popular-topics/collectors.html#basic-message-collector

Here are the docs:

https://docs.openwa.dev/classes/structures_messagecollector.messagecollector.html


Since this issue only refers to the implementation of this feature I will be closing the issue.

If you have problems with the message collector or need implementation help then please use the discord.

Thanks for your patience.

**Comment by smashah** [comment]
I FORGOT TO MENTION THAT YOU NEED TO MAKE SURE EVENTMODE IS ON.

in your configs:

`eventMode: true`
