### ISSUE TITLE
InvalidMediaFileType send video after update

### ISSUE THREAD

**Issue by MRHRTZ** [open-wa/wa-automate-nodejs#1046]
**Describe the bug**
Like as usual i use this library from version 2.1.6 its working fine sending the videos, and after upgrading to 3.0.13 i've catch error for sending videos (InvalidMediaFileType) and if i downgrade to 2.1.6 again its working

**Steps to Reproduce**
1. Do a command for getting video (wa-automate v2.1.6)
![image](https://user-images.githubusercontent.com/52845610/98431069-db5efd80-20e4-11eb-9449-873814fc9916.png)

Its working fine
2. Upgrade to version 3.0.13
![image](https://user-images.githubusercontent.com/52845610/98431129-7526aa80-20e5-11eb-8044-0fa43cec3b01.png)

3. Do that command again (wa-automate v3.0.13)
![image](https://user-images.githubusercontent.com/52845610/98431221-f716d380-20e5-11eb-893f-8b2ba0d821c4.png)

4. Go to the console log and see the error 
![image](https://user-images.githubusercontent.com/52845610/98431251-3513f780-20e6-11eb-833a-bd5c7844f2b0.png)

**create() code**
This is the code you use to create the client. e.g
```javascript
create({
        headless: true,
        qrRefreshS: 20,
        qrTimeout: 0,
        authTimeout: 0,
        autoRefresh: true,
        restartOnCrash: start,
        cacheEnabled: false,
        useChrome: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false
    }).then((client) => start(client))
    .catch((err) => new Error(err)))
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
WA_VERSION : 2.2045.15
PAGE_UA : WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
WA_AUTOMATE_VERSION : 3.0.13 UPDATE AVAILABLE: 3.0.13
BROWSER_VERSION : HeadlessChrome/87.0.4272.0
}
```

**Screenshots**
No need for now

**Host (please complete the following information):**
 - OS: Window Server 2019 x64

**Additional context**
I can't solving this bug from previous issue like : <a href=https://github.com/open-wa/wa-automate-nodejs/issues/1000#issuecomment-719971092>#1000 Comment</a>

![image](https://user-images.githubusercontent.com/52845610/98431432-cdf74280-20e7-11eb-9338-26dabccba7a0.png)

I try changing my browser application Google Chrome Application and also chromium still get that error.

**Comment by smashah** [comment]
@MRHRTZ

I used your same config and am unable to replicate the issue on my machine with the latest verison.

Can you bump the version until you find one that it doesn't work so we can narrow down which version is resulting in the error, please

**Comment by joedutra** [comment]
<img src="https://media.giphy.com/media/sNZddQMtrqpS0HEEMC/giphy.gif"></img>
Man, you know it sucks, how we copy your repo, if we have functions that you don’t even have, all for free, we perform almost every day, I came from Sulla and you too, but if you look at following the week, we redid it all lib again, now you will no longer be able to copy us, you copy and keep saying that we copy, nor compete with you ours and for free and your payment

**Comment by joedutra** [comment]
> @MRHRTZ
> 
> I used your same config and am unable to replicate the issue on my machine with the latest version.
> 
> Can you bump the version until you find one that it doesn't work so we can narrow down which version is resulting in the error, please


I come to apologize and say that we have nothing against this, only that they accuse us of copying and we never copied anything, if someone copied it was when someone changed our lib, I apologize and the intention was not to be slandered anymore of copying something we worked on every day. just like you, we will not do that anymore.

**Comment by MRHRTZ** [comment]
> @MRHRTZ
> 
> I used your same config and am unable to replicate the issue on my machine with the latest version.
> 
> Can you bump the version until you find one that it doesn't work so we can narrow down which version is resulting in the error, please

Okay i'll do that on process..

**Comment by MRHRTZ** [comment]
@smashah I think i'm know the issue i made a custom create like this 👍 

```create('MRHRTZ', options()) 
.then(start => start(client))
.catch(e => console.log(e)) 
```

Thats create is can broke the code? And i change to :

```create(options()) 
.then(start => start(client))
.catch(e => console.log(e)) 
```

And all the function is working no more error sending videos.

**Comment by smashah** [comment]
@MRHRTZ 

I'm going to make the library throw an error if it detects a string as the first parameter as many people are not using typescript with the library
