### ISSUE TITLE
License not working

### ISSUE THREAD

**Issue by lbertoncello** [open-wa/wa-automate-nodejs#1050]
**Describe the bug**

I've just bought the license to send message to non contacts (Restricted License Key), but I'm still receiving the error message "Not a contact".

**Steps to Reproduce**

npx @open-wa/wa-automate --license "..."

**DEBUG INFO**

```
Debug Info {S
  WA_VERSION: '2.2045.15' ,
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.0.14',
  BROWSER_VERSION: 'HeadlessChrome/87.0.4272.0'
}
```

**Host (please complete the following information):**
 - OS: Windows 10

**Comment by smashah** [comment]
@lbertoncello emailed
