### ISSUE TITLE
Reply breaks getAllMessagesInChat and loadAndGetAllMessagesInChat just for the chatId of the reply

### ISSUE THREAD

**Issue by dgphp** [open-wa/wa-automate-nodejs#1051]
**Describe the bug**
After using the **reply** function, **even if with success**, getAllMessagesInChat and loadAndGetAllMessagesInChat returns **undefined** when retrieving the messages for the **SAME** chatId used to Reply! It continue working in other chats!

I think the same problem reported in issue #376 (closed)

**Steps to Reproduce**

1. Send a normal message ( in order for reply to work properly - as docs)
2. Send a reply
3. Try to getAllMessagesInChat or loadAndGetAllMessagesInChat
4. The promises is **resolved** but returns undefined

**create() code**
```
const wa = require('@open-wa/wa-automate');

const launchConfig = {
    headless: false,
    qrTimeout: 0
};

wa.create( launchConfig ).then(client => startClient(client));
```

**Expected behavior**
getAllMessagesInChat and loadAndGetAllMessagesInChat continues working after a reply

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2045.15',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.0.14',
  BROWSER_VERSION: 'Chrome/87.0.4272.0'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Windows

**Additional context**

Function that makes the reply:

```
dg.waClient.reply(data.chatId, data.content, data.replyTo, true).then( ( ret ) => {

    console.log('on sendMessageText: REPLY => THEN', ret);
    
    if(ret){

        console.log('on sendMessageText: REPLY SUCCESS');

        loadMessages(socket, { chatId: data.chatId }).then( (chatData) => {

            socket.emit('chatMessages', {

                chatId: data.chatId,
                messages: messagesPrepareToSend(chatData)
            });

        }).catch( (err) => {

            console.log('Error load messages:', err);

        });

    }else{

        console.log('on sendMessageText: REPLY FAILURE');
    }

}).catch( (err) => {

    console.log('dg.waClient.reply ERROR', err);

});
```

Function that load the messages (dg.waClient stores the client)

```
function loadMessages(socket, data) {
    
    return new Promise( (resolve, reject) => {

        console.log('on loadMessages: init => ', data);

        if(!data.chatId){ 

            console.log('Error: on loadMessages => no chatId', data);

            reject('Error: on loadMessages => no chatId');
        
        }else{

            console.log('on loadMessages: chatId ok => ' + data.chatId);

            dg.waClient.getAllMessagesInChat(
                data.chatId,
                true, // include me
                false // include notifications
            ).then( chatData => {

                console.log('getAllMessagesInChat: then => chatData:\n', chatData , '\n*****************');
                // chatData returning undefined <<<< PROBLEM HERE

                //console.log('getAllMessagesInChat: then =>', chatData.length);
          
                getAllMessagesMedias(chatData).then( (chatDataWithMedia) => {

                    //console.log('chatDataWithMedia', chatDataWithMedia);
                    
                    resolve(chatDataWithMedia);            

                }).catch( (err) => {

                    reject('chatDataWithMedia ERROR', err);
                });

            }).catch( (err) => {

                console.log(err);

                reject(err);
            });
            
        }

    });

};
```
**First of all, congrats for the package, it´s amazing!!!**

I am doing some tests with a multiple attendants system! I intend to buy a License Key when in production, but it was a bit necessaire that reply works fine!

Please, let´s solve it!

Sorry, my poor english! Best regards!

**Comment by smashah** [comment]
@dgphp thanks for detail. Can you set `logConsole: true` and see if it results in any errors

**Comment by dgphp** [comment]
@smashah thanks for the quick attention!

`logConsole: true` (In create object, correct?) did not log any message!

Today something different happened!

The REPLY function was returning **FALSE**, but the reply was **SENT**!

My Logs:
```
on sendMessageText: REPLY => THEN false
on sendMessageText: REPLY FAILURE
```
Screen:
![image](https://user-images.githubusercontent.com/49364808/98757377-2dd14000-23ab-11eb-9b8d-afe6d401650a.png)

AND NOW a so much strange thing!

When I tried a **SECOND REPLY in the SAME CHAT**!

 **The FIRST REPLY becames an AUDIO MESSAGE!**

![image](https://user-images.githubusercontent.com/49364808/98757639-bfd94880-23ab-11eb-9564-21d29dfe3932.png)

**The change was just seen in headless: false**, in the phone it was yet a normal reply! And the Second reply works!

![image](https://user-images.githubusercontent.com/49364808/98758502-bcdf5780-23ad-11eb-8493-57f8e1ccc29c.png)

This message was logged when sent the second reply (i think because it did not locate the "fake" audio):

```
ConsoleMessage {
  _type: 'error',
  _text: 'Failed to load resource: the server responded with a status of 410 ()',
  _args: [],
  _stackTraceLocations: [
    {
      url: 'https://mmg.whatsapp.net/v/t62.7117-24/30572649_356606552059320_266204942482646216_n.enc?oh=f1d2dc26bbbafcf05774490c86c4f2c5&oe=5FAE4191&auth=[REMOVED-BY-ME]&hash=[REMOVED-BY-ME]&mms-type=ptt&__wa-mms=',
      lineNumber: undefined
    }
  ]
}
```

**Comment by smashah** [comment]
@dgphp what is happening in the web instance doesn't always show what's happening on the host/recipient devices. As long as the recipient gets the message intended then any glitches in the web instance can be ignored.

**Comment by dgphp** [comment]
@smashah ok, i now understand! I just reported because it was related!

Do you think it´s possible to be related with the OS (Windows)?

If there is something else i can do to help, please let me know!

**Comment by smashah** [comment]
@dgphp should be patched now. Can you restart your session, try again and report back if the issue is fixed, please.

**Comment by dgphp** [comment]
@smashah thanks!
getAllMessagesInChat -> **WORKING**
loadAndGetAllMessagesInChat -> **STILL FAILS**

**I don´t use loadAndGetAllMessagesInChat, but maybe for anothers users might be useful, and its good everything working fine**

What i did:
- npm i @open-wa/wa-automate
- I had some problems with the update of socket.io to 3.x (cors origins)! Updated front-end version and back-end config!

**Tests made in the same session!**

Test 1 - Chat **A**:
1 - Send a normal message -> OK
2 - Send a reply message ->OK
**3 - Use getAllMessagesInChat -> OK!!**
4 - Send another reply message -> OK
**3 - Use getAllMessagesInChat -> OK**

![image](https://user-images.githubusercontent.com/49364808/99133766-0cb25e80-25fa-11eb-9995-38a44dffcd80.png)

Test 2 - Chat **B**:
1 - Send a reply (without sending a normal message in the session) -> **WORKS!!**
**2 - Use getAllMessagesInChat -> OK**
3 - Send another reply message -> OK
**4 - Use getAllMessagesInChat -> OK**

**Is it not necessaire to send a normal message before a reply anymore??**

![image](https://user-images.githubusercontent.com/49364808/99133797-2eabe100-25fa-11eb-9e45-4212ff53a63f.png)

Teste 3 - Chat **A**:
After Test 1 and 2
1 - Use loadAndGetAllMessagesInChat -> **STILL FAILS** returns undefined

![image](https://user-images.githubusercontent.com/49364808/99133870-729ee600-25fa-11eb-86d7-bdbeae17ade1.png)

**Comment by smashah** [comment]
@dgphp thanks for your patience and detail. This latest patch should fix it for `loadAndGetAllMessagesInChat`

Please run your test again and let me know if it is working for you

**Comment by dgphp** [comment]
@smashah fixed `getAllMessagesInChat` and  `loadAndGetAllMessagesInChat`! **Thanks**!

I have just seen that `reply` also breaks `loadEarlierMessages` and `loadAllEarlierMessages`!

Is it better to open a new Issue or keep in this??

**Comment by smashah** [comment]
@dgphp `loadAllEarlierMessages` is only supposed to respond with `true` once all messages are loaded. I'll look into `loadEarlierMessages`

**Comment by smashah** [comment]
@dgphp try now

**Comment by dgphp** [comment]
@smashah `loadEarlierMessages` working! **Thanks**!
