### ISSUE TITLE
onGlobalParticipantsChanged getting triggered multiple times

### ISSUE THREAD

**Issue by AlenSaito1** [open-wa/wa-automate-nodejs#1055]
**Describe the bug**

`onGlobalParicipantsChanged` is getting triggered multiple times on a singe event

**Steps to Reproduce**
1. Create a client
2. add the listener and make link it to the function below

```javascript 

client.onGlobalParicipantsChanged((event) => {
      welcome(client, event)
     })
module.exports = welcome = async (client, event) => {

  	try {
  		if (event.action == 'add') {
  			const det = await client.getChatById(event.chat)
  			const person = await client.getContact(event.who)
  			await client.sendTextWithMentions(event.chat, `Welcome to *${det.contact.formattedName}!* \n\n@${event.who.replace('@c.us', '')} \n\nHave fun with us✨ \n\n *Group Description* ❇️ \n\n ${det.groupMetadata.desc}`)
  		} 
	} catch(err) {
		console.log(err)
	}
}
```
**create() code**
This is the code you use to create the client. e.g
```javascript
const serverOpt = {
    headless: true,
    cacheEnabled: false,
    useChrome: true,
    chromiumArgs: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--aggressive-cache-discard',
        '--disable-cache',
        '--disable-application-cache',
        '--disable-offline-load-stale-cache',
        '--disk-cache-size=0'
    ]
}
const startServer = async (client) => {
client.onGlobalParicipantsChanged((event) => {
      welcome(client, event)
     })
}

create('session', serverOpt)
    .then(async (client) => startServer(client))
    .catch((error) => console.log(error))
```

**Expected behavior**
It supposed to send the welcome text once 

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION:  '2.2045.15' ,
  PAGE_UA:  'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.0.14' ,
  BROWSER_VERSION: 'HeadlessChrome/87.0.4272.0'
}
```

**Screenshots**
![IMG_20201110_185741](https://user-images.githubusercontent.com/66544823/98679929-b5588800-2386-11eb-9581-fa5de3687b7f.jpg)

**Host (please complete the following information):**
 - OS: Android for whatsapp and Ubuntu 18.04 LTS for hosting

**Additional context**
This happened after updating to 3.0.13

**Comment by Kry9toN** [comment]
I'm also having the same problem

**Comment by smashah** [comment]
@Kry9toN @AlenSaito1 can you restart your sessions and try again, please. You should only receive one instance of the event now. Please report back if the issue is resolved.

**Comment by Kry9toN** [comment]
@smashah 
Bug fixed

Screenshot:
![Screenshot_20201112-071726~2](https://user-images.githubusercontent.com/44697929/98879275-b6d59d80-24b7-11eb-91f9-66818c822b93.jpg)

**Comment by AlenSaito1** [comment]
Works fine now, Thanks @smashah

**Comment by smashah** [comment]
> No, for me i have the same issue.. but it only comes SOMETIMES! sometimes i start the session.. all looks good.. but sometimes i start the session.. and it keep spamming into the group for no reason..
> 
> this bug is definitely not fixed in the latest build

Lots of parameters changed since then. Please fill a new issue template

**Comment by Kuroosh** [comment]
> > No, for me i have the same issue.. but it only comes SOMETIMES! sometimes i start the session.. all looks good.. but sometimes i start the session.. and it keep spamming into the group for no reason..
> > this bug is definitely not fixed in the latest build
> 
> Lots of parameters changed since then. Please fill a new issue template

Done #2533
