### ISSUE TITLE
getMessageReaders does not work anymore

### ISSUE THREAD

**Issue by Gimenz** [open-wa/wa-automate-nodejs#1057]
**Describe the bug**
I don't know what to write, but I want to let you know that `getMessageReaders` isn't working.
As shown in screenshot.

Thank you!

**Steps to Reproduce**

1. if it worked, it should be like this :
 ![2020-10-07 19_15_31-Window](https://user-images.githubusercontent.com/23699593/98697756-d8476400-23a7-11eb-8cbf-c16e9896aacb.png)

2. but, now it does not work anymore
![2020-11-10 22_51_04-Window](https://user-images.githubusercontent.com/23699593/98697920-0a58c600-23a8-11eb-8e22-d2d1cc2bd43e.png)

**create() code**
This is the code you use to create the client. e.g
```javascript
const reader = await client.getMessageReaders(quotedMsgObj.id)
console.log(reader)
let list = ''
for (let pembaca of reader) {
list += `- @${pembaca.id.replace(/@c.us/g, '')}\n` 
}
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2045.15',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.0.14',
  BROWSER_VERSION: 'HeadlessChrome/86.0.4240.183'
}
```

**Screenshots**
![2020-11-10 22_17_03-Window](https://user-images.githubusercontent.com/23699593/98696398-5145bc00-23a6-11eb-86c7-772cb73042c1.png)

**Host (please complete the following information):**
 - OS: Android 10 for WhatsApp and Windows Server 2016 

**Additional context**
This package is very amazing and also useful

Please, let´s solve it!
Sorry, my bad english! Best regards!

**Comment by smashah** [comment]
@Gimenz thanks so much for filling out the issue template perfectly. You have no idea how much easier and quicker it makes resolving issues. 

I have issued a patch that should fix this error. Please try again in 5 minutes and report back if this issue is resolved. 

Thanks!

**Comment by Gimenz** [comment]
Wow, its worked. Thank you so much
![2020-11-13 05_51_05-Window](https://user-images.githubusercontent.com/23699593/99005929-42146900-2574-11eb-9049-1437cc06f0f3.png)
