### ISSUE TITLE
Not send Image, audio, doc ou video After upgrade

### ISSUE THREAD

**Issue by danielct59** [open-wa/wa-automate-nodejs#1058]
after the latest version i can no longer send video or image please give me a suggestion

I already entered this information more unsuccessfully

waAutomate.create ({
        headless: true,
        qrRefreshS: 20,
        qrTimeout: 0,
        authTimeout: 0,
        autoRefresh: true,
        restartOnCrash: start,
        cacheEnabled: false,
        useChrome: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false
    }). then ((client) => start (client))
    .catch ((err) => new Error (err))

const mime = require('mime-types');
const fs = require('fs');

**Comment by smashah** [comment]
@danielct59 if this is happening then it's a huge problem. In order to fix it I'll need you to fill in the issue template with as much detail as possible. I will be working through issues tomorrow

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
