### ISSUE TITLE
sendLinkWithAutoPreview API is not working

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-nodejs#1062]
sendLinkWithAutoPreview API is posting message but it is getting timeout issue. 

Can you please help me to fix it?

**Comment by smashah** [comment]
@manojsitapara I have just tested it. Seems to be working ok with this link:

https://www.instagram.com/p/CGSaIrqJv2F/

I will need you to fill out an issue template

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
