### ISSUE TITLE
Get connection state

### ISSUE THREAD

**Issue by shubham0804** [open-wa/wa-automate-nodejs#1072]
I'm using the easyApi to interact with the library and I wanted to periodically check if the session is online i.e there's no issue with the host phone or the server on which the library is running.

I tried to test it by turning off internet on the host phone and hitting the /getConnectionState, /getMe or similar endpoints of the easyApi but I'm still getting a successful response. The /getSnapshot endpoint also shows that WA Web is running normally. 

The only workaround I could find was hitting the /refresh endpoint, after which /getConnectionState returns an offline status. Is there an alternative?

**Comment by smashah** [comment]
Looks like it will only update connection state when you try to do something that requires contacting the host account device. If anything I'll have to trick it into pinging the device every time you call `getConnectionState`

**Comment by smashah** [comment]
@shubham0804 please restart your session and try again. Although `getConnectionState()` now takes about 4 seconds to resolve, it will be much more reliable and up to date.

If you ever want to 'wake up' the connection between the session and the host device just call `getConnectionState()`

Please report back if it working for you.

**Comment by smashah** [comment]
changing `getConnectionState` caused issues so now I've implemented `client.forceUpdateConnectionState()` instead.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.0.16](https://github.com/open-wa/wa-automate-nodejs/compare/3.0.15...3.0.16) (2020-11-15)

- build(deps): bump socket.io from 3.0.0 to 3.0.1 [`#1052`](https://github.com/open-wa/wa-automate-nodejs/pull/1052)
- build(deps): bump ts-json-schema-generator from 0.77.0 to 0.78.0 [`#1061`](https://github.com/open-wa/wa-automate-nodejs/pull/1061)
- Release 3.0.16 [`afd46ca`](https://github.com/open-wa/wa-automate-nodejs/commit/afd46ca2dfa5dfab5e700a75dd2d255b9b99ff32)
- added `401` information to docs #1070 [`8d6f554`](https://github.com/open-wa/wa-automate-nodejs/commit/8d6f554259632b1997f528e9c4b9ef967b90139a)
- Feature: Implemented `forceUpdateConnectionState()` #1072 [`3b03950`](https://github.com/open-wa/wa-automate-nodejs/commit/3b0395027a6c546a45f099044d9ee6fdd2d341ea)
- CLI: new flag `--headful` to launch browser window [`c2cfbac`](https://github.com/open-wa/wa-automate-nodejs/commit/c2cfbacbfcc3f2f47c96c4a1e79bdf719a981f0a)
- ignore `needsToScan` error on `kill` #1063 [`96e4979`](https://github.com/open-wa/wa-automate-nodejs/commit/96e49792d6f2dcf55b0ee68a53c064a06e7a91aa)
- patched: #1072 #1069 [`1ca07fb`](https://github.com/open-wa/wa-automate-nodejs/commit/1ca07fb57e15265e37a8c93e8def7fb57b5a028a)
- prevent `client.kill()` from being called twice. [`7a04599`](https://github.com/open-wa/wa-automate-nodejs/commit/7a045996d52a33ca737464ae08abbba58d2b33e5)
- bump popup socket io version [`5d1167b`](https://github.com/open-wa/wa-automate-nodejs/commit/5d1167b7c971d5e5dc401ca8c9649e12c6ea5fa3)
- patched `loadAndGetAllMessagesInChat` #1051 [`6477105`](https://github.com/open-wa/wa-automate-nodejs/commit/64771051393213adfaac4fcc1d855399c7554692)
- patch: #1051 [`4d48454`](https://github.com/open-wa/wa-automate-nodejs/commit/4d48454ffacab59b41436743d074bf08b9a92d11)

**Comment by shubham0804** [comment]
client.forceUpdateConnectionState() has solved the issue! Would it be possible to call it through the easyApi?

**Comment by shubham0804** [comment]
Never mind. It's working through the easyApi after updating. Thanks!
