### ISSUE TITLE
isChatOnline ALWAYS returns false

### ISSUE THREAD

**Issue by foerderlabor** [open-wa/wa-automate-nodejs#1073]
Hi there

I have installed the latest version of open-wa and ran into the following issue. When checking for a contacts status (available, unavailable), it always returns false. Even when I'm checking the status once a second the response doesn't change. I'm testing the following code with 2 seperate phones. One ist the host and the other one is the phone which status should be "available" but isn't.

Any help is appreciated!
Cheers

```
// import { create, Client } from '@open-wa/wa-automate';
const wa = require("@open-wa/wa-automate");

wa.create().then((client) => start(client));

function start(client) {
  client.onMessage(async (message) => {
    if (message.body === "Hi") {
      await client.sendText(message.from, "👋 Hello!");
    }
  });
  (() => {
    setInterval(async () => {
      let res = await client.isChatOnline("XXXXXXXXX@c.us");
      console.log(res);
    }, 1000);
  })();
}
```

**Comment by smashah** [comment]
there is a lag between the recipient device showing up online and the session seeing it. How many times is it showing false?

**Comment by foerderlabor** [comment]
Hi and thanks for your reply

As I mentioned before it's always returning false - even when testing it for several minutes.

**Comment by smashah** [comment]
Improved docs and error response:

73e53eb689797e56a9c6f069cfa6fb7a108ca012
