### ISSUE TITLE
Generate an image of a QR so that it can be used anywhere instead of just terminal

### ISSUE THREAD

**Issue by pysaquib** [open-wa/wa-automate-nodejs#1076]
Not sure if this functionality already exists, but providing a method for printing the QR would be really flexible for the developers

**Comment by smashah** [comment]
https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#popup

And

https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrpopuponly

**Comment by smashah** [comment]
Also:

https://github.com/open-wa/wa-automate-nodejs/blob/73e53eb689797e56a9c6f069cfa6fb7a108ca012/demo/index.ts#L27
