### ISSUE TITLE
EasyAPIsession stops working when an error occurs

### ISSUE THREAD

**Issue by shubham0804** [open-wa/wa-automate-nodejs#1082]
**Describe the bug**
Easy Api session stops working when an error occurs

**Steps to Reproduce**
Run the easyAPI 

**create() code**
Easy API

**Expected behavior**
While running the easyAPI, if an error occurs, as shown in the screenshot, the session stops responding. I'm not sure if this is by design but I don't think the session should stop for an error such as an evaluation error.

**DEBUG INFO**
{
  WA_VERSION: '2.2045.19'
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_1      5_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36'
  WA_AUTOMATE_VERSION: .3.0.16
  BROWSER_VERSION: 'HeadlessChrome/87.0.4272.0'
}

**Screenshots**
![wa-automate error](https://user-images.githubusercontent.com/52071475/99499732-58209000-299f-11eb-9d00-e21a98ab3a9c.PNG)

**Host (please complete the following information):**
 - Android

**Additional context**
-

**Comment by smashah** [comment]
@shubham0804 can you provide some more context to this issue? I'm trying to instigate a frozen session after an error caused by an unknown group id via `getGroupInviteLink` but am unable to replicate

**Comment by shubham0804** [comment]
@smashah I'm not sure what exactly led to the session freezing. I restarted the session and tried to replicate what might have led to it. I'm still getting logs of the error on the console but the session isn't freezing. Maybe I'll reopen this issue if the session freezes again & I can let you know how to replicate it.

**Comment by smashah** [comment]
ok thanks i'll close this for now then

**Comment by shubham0804** [comment]
2 of the sessions that I was running through the EasyApi have frozen again. 
The logs of the 1st sessions are:
![session-12 freeze logs (24 11)](https://user-images.githubusercontent.com/52071475/100061619-54d04d00-2e54-11eb-9130-0469511ce2b7.PNG)
I was running a cron job on this session using the following sequence:
1) Create a dummy group (not adding anyone to it other than host no.) using /createGroup 
2) Wait 8 seconds
3) Get the invite link of the created group using /getGroupInviteLink
4) Archive the group using /archiveChat
The cron job had run successfully for quite a while but the session froze sometime yesterday.

The logs of the 2nd session are:
![session-14 freeze logs](https://user-images.githubusercontent.com/52071475/100062085-112a1300-2e55-11eb-8a32-2d3f0655659e.PNG)
I wasn't running the above cron job on this & I'm not sure when it froze. Also calling /forceUpdateConnectionState using the Swagger UI doens't result in any response (no TIMEOUT) and the response of /getSnapshot is:
{
  "success": false,
  "error": {
    "message": "Protocol error (Page.captureScreenshot): Internal error"
  }
}

I was also running a cron job every 1min on the sessions calling /forceUpdateConnectionState in order to determine if the session is online but I stopped running that yesterday. That could be the cause of the 2nd session crashing, but I'm not sure.

**Comment by smashah** [comment]
@shubham0804 will need to inspect your code for better context (DM it to me on discord) because I think something else is causing this session to freeze up. For now, I will issue a patch that returns 'GROUP_DOES_NOT_EXIST' in order to prevent this error path.

It may be that the session still freezes but at least we can eliminate the `getGroupInviteLink` as a cause.

**Comment by smashah** [comment]
@shubham0804 I've issued a patch that will result in `GROUP_DOES_NOT_EXIST` being returned if the chat doesn't exist. Can you please run your test again and see if it still freezes after a while. Also, check the PM2 dashboard to see memory consumption over time as that may be a cause also.

**Comment by shubham0804** [comment]
> @shubham0804 I've issued a patch that will result in `GROUP_DOES_NOT_EXIST` being returned if the chat doesn't exist. Can you please run your test again and see if it still freezes after a while. Also, check the PM2 dashboard to see memory consumption over time as that may be a cause also.

Thanks, I'll get back to you if it happens again.
