### ISSUE TITLE
Proxy recommendation

### ISSUE THREAD

**Issue by pkhadson** [open-wa/wa-automate-nodejs#1083]
I want to start using this library, but in addition to asking the customer to save my contact. It is necessary to use a proxy to hide the ip. Which are the best? And how to install?

**Comment by smashah** [comment]
I don't think it's necessary to use a proxy but you can do it using `proxyServerCredentials`

Here's an example:
https://github.com/open-wa/wa-automate-nodejs/issues/670#issue-664269911


I highly suggest using [luminati](https://luminati.io/?affiliate=ref_5f1b9ae8c7669177abfd9fb8)

**Comment by smashah** [comment]
Here's the new proxy docs

https://docs.openwa.dev/pages/How%20to/use-a-proxy.html
