### ISSUE TITLE
sendText doesn't return properly

### ISSUE THREAD

**Issue by dantenol** [open-wa/wa-automate-nodejs#1088]
**Describe the bug**
When I send a message through the API and get the response for the function, it returns the messageId of the previous message on the cat, not the id of the one I just sent

**Steps to Reproduce**
```
const myMsg = await sendText("553799131393@c.us", "Hi there")
console.log(myMsg)
> false_...
```

**create() code**
This is the code you use to create the client. e.g
```javascript
wa.create({
        killProcessOnBrowserClose: false,
        restartOnCrash: start,
        licenseKey: '***',
        disableSpins: true,
        hostNotificationLang: 'pt-br',
        // cacheEnabled: false,
        sessionDataPath: './session',
        logQR: true,
        autoRefresh: true,
        qrTimeout: 90,
        authTimeout: 90,
      })
```

**Expected behavior**
return the id of the message that was just sent

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
{
  WA_VERSION: '2.2047.10',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.0.16',
  BROWSER_VERSION: 'Chrome/86.0.4240.198',
}
```

**Host (please complete the following information):**
 - OS: Ubuntu/android

**Additional context**
Issue has been running for the last 15 days. Doesn't work with and without license key.

**Comment by smashah** [comment]
@dantenol thanks for filling in the issue template. I've issued a patch and it should now be working as expected, you just need to restart your sessions. Please report back if the patch is working for you.

thanks

**Comment by dantenol** [comment]
Thanks, works great Just as expected.
