### ISSUE TITLE
Is EasyAPI working?

### ISSUE THREAD

**Issue by lbertoncello** [open-wa/wa-automate-nodejs#1096]
Today my servers running EasyAPI has stopped working. I'm getting HTTP 504 when I try to run a request. I've tried to run EasyAPI in my local machine, but it's not working as well, it's freezing in the following screen:

 ![screenshot](https://user-images.githubusercontent.com/30178254/99805915-f46fa180-2b1b-11eb-955c-2dd4c2776532.png)

The API is working or it's an error on my side?

```
Debug Info {
  WA_VERSION: 2.2047.10,
  PAGE_UA: WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36,
  WA_AUTOMATE_VERSION: 3.0.16,
  BROWSER_VERSION: HeadlessChrome/87.0.4272.0
}
```
 - OS: Ubuntu and Windows 10

**Comment by smashah** [comment]
can you paste the command you use here please @lbertoncello

**Comment by lbertoncello** [comment]
> can you paste the command you use here please @lbertoncello

I've ran the following command in my local machine:

`
npx @open-wa/wa-automate -p 3000 -k '...' -w "..." --qr-timeout 0 --qr-log-skip --disable-spins --popup -l '...'
`

In my server I've ran the following command:

`
npx @open-wa/wa-automate --in-docker --api-host "..." -p 3000 -k '...' -w "..." --qr-timeout 0 --qr-log-skip --disable-spins --popup -l '...'
`

My API monitor indicates that server requests stopped working after 5 am (utc).

**Comment by smashah** [comment]
@lbertoncello can you try without any flags and see if it works please

**Comment by lbertoncello** [comment]
> @lbertoncello can you try without any flags and see if it works please

It works without flags.

**Comment by smashah** [comment]
@lbertoncello can you try to eliminate each flag one by one to determine which one is causing this issue, please. I suspect it may be `--popup`.

**Comment by smashah** [comment]
@lbertoncello if it is `--popup` this may be due to the fact that socket io dependency has been updated. Try to ensure that you have the latest version of socket io dependency in your npx cache

**Comment by smashah** [comment]
@lbertoncello This issue should be resolved in the latest version: 

https://github.com/open-wa/wa-automate-nodejs/releases/tag/3.1.1

Please try it with


`npx @open-wa/wa-automate@3.1.1 -p 3000 ...`

**Comment by lbertoncello** [comment]
> @lbertoncello This issue should be resolved in the latest version:
> 
> https://github.com/open-wa/wa-automate-nodejs/releases/tag/3.1.1
> 
> Please try it with
> 
> `npx @open-wa/wa-automate@3.1.1 -p 3000 ...`

It's working now! Thanks!
