### ISSUE TITLE
Feature [CLI]: Communicate with session via socket.io

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#1100]
This is related to #894 although there can be a basic implementation for now.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.6.5](https://github.com/open-wa/wa-automate-nodejs/compare/3.6.4...3.6.5) (2021-02-23)

- Release 3.6.5 [`adba301`](https://github.com/open-wa/wa-automate-nodejs/commit/adba3015e8cc0e72dccaaaca7dcee47e4825f96e)
- 🔥  Removed redundant code, improves CLI collection generation performance [`a1a5477`](https://github.com/open-wa/wa-automate-nodejs/commit/a1a5477c75746a070d5431e445a0efa36255906e)
- ➖  removed `typescript-parser` dep [`eac61d7`](https://github.com/open-wa/wa-automate-nodejs/commit/eac61d760fede2c32876ad3095ac61cac7495ec8)
- 🍱  update release image [`a356558`](https://github.com/open-wa/wa-automate-nodejs/commit/a356558f3ca7e0409dcdb0af9f55c032280897a9)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.9.9](https://github.com/open-wa/wa-automate-nodejs/compare/3.9.8...3.9.9) (2021-03-21)

- Release 3.9.9 [`c58eedb`](https://github.com/open-wa/wa-automate-nodejs/commit/c58eedbfa4ee3b3c7ad2ad92dc448c896dcfdab8)
- ✏️  fix typos and broken links [`b9c1be5`](https://github.com/open-wa/wa-automate-nodejs/commit/b9c1be5032cdfa4a356d6d5c450c5be310c95d7d)
- ⬆️ package lock fix [`a3b1069`](https://github.com/open-wa/wa-automate-nodejs/commit/a3b10695fadd117e5cbf562d60259640d4af92bc)
- fix npm lib version [`65f8846`](https://github.com/open-wa/wa-automate-nodejs/commit/65f8846bef88d9598dc51ffd0baf2073b730e45a)

**Comment by Urbaeexyz** [comment]
> # Changelog
> ##  Release [3.9.9](https://github.com/open-wa/wa-automate-nodejs/compare/3.9.8...3.9.9) (2021-03-21)
> * Release 3.9.9 [`c58eedb`](https://github.com/open-wa/wa-automate-nodejs/commit/c58eedbfa4ee3b3c7ad2ad92dc448c896dcfdab8)
> * pencil2  fix typos and broken links [`b9c1be5`](https://github.com/open-wa/wa-automate-nodejs/commit/b9c1be5032cdfa4a356d6d5c450c5be310c95d7d)
> * arrow_up package lock fix [`a3b1069`](https://github.com/open-wa/wa-automate-nodejs/commit/a3b10695fadd117e5cbf562d60259640d4af92bc)
> * fix npm lib version [`65f8846`](https://github.com/open-wa/wa-automate-nodejs/commit/65f8846bef88d9598dc51ffd0baf2073b730e45a)

how to set timeout puppeteer?

**Comment by smashah** [comment]
Todo:

- [ ] Refactor /bin/index.js to within to /src so it can be compiled and rebuilt in typescript
- [ ] Add a socket middleware within the CLI
- [ ] Refactor post create promises to resolve before the instance is finished being created

**Comment by smashah** [comment]
https://docs.openwa.dev/classes/connect_socket.socketclient.html
