### ISSUE TITLE
onGlobalParicipantsChanged doesn't fire

### ISSUE THREAD

**Issue by shubham0804** [open-wa/wa-automate-nodejs#1113]
**Describe the bug**
I'm using the easyAPI with webhook and the onGlobalParicipantsChanged event doesn't fire when a group is created using the host phone (not wa-automate) and another phone tries enter the group using the invite link. If the group has been created using wa-automate, the onGlobalParicipantsChanged  is received on the webhook if another phone enters the group using the invite link.

**Steps to Reproduce**
1. Create a group using the physical host phone
2. Have another phone enter the group using the invite link

**create() code**
This is the code you use to create the client. e.g
easyAPI and webhook

**Expected behavior**
onGlobalParicipantsChanged should be recieved on the webhook every time when someone is added or removed from the group.

**DEBUG INFO**
```
Debug Info {
  WA_VERSION: '2.2047.11'
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36'
  WA_AUTOMATE_VERSION: 3.0.16 
  BROWSER_VERSION:' HeadlessChrome/87.0.4272.0' 
}
```

**Screenshots**
NA

**Host (please complete the following information):**
 - OS: Android

**Additional context**
onAnyMessage event is received when someone is added to the group or removed regardless of how the group was created. If onAnyMessage is more reliable compared to onGlobalParicipantsChanged, let me know & I'll that in my code accordingly.

It's also possible that onGlobalParicipantsChanged is not recieved when the group has recently been created. The groups that I had created using wa-automate were done a while back.

**Comment by smashah** [comment]
@shubham0804 can you try with the latest version please:

https://github.com/open-wa/wa-automate-nodejs/releases/tag/3.1.1

**Comment by shubham0804** [comment]
@smashah onGlobalParicipantsChanged is still not received after updating to 3.1.2 for recently created groups from the host phone, but restarting the session after creating the group solves the issue.  This is fine for my use case and you might not want to spend more time on this. Just wanted to point this issue when I came across it.

**Comment by smashah** [comment]
@shubham0804 it's definitely an edge case but it is fixable. Just working on some other issues right now so will leave this open till it's fixed. thanks

**Comment by smashah** [comment]
@shubham0804 this is resolved now thanks
