### ISSUE TITLE
setMyName doesn't work for WhatsApp Business accounts

### ISSUE THREAD

**Issue by mikhail-idris** [open-wa/wa-automate-nodejs#1115]
If the account that is being used for wa-automate is a WhatsApp Business account, setMyName does not work.

Thank you.

**Comment by smashah** [comment]
@mikhail-idris that's due to the fact that a business account requires some sort of approval for changing details and the same methods as a personal account cannot be used. Last time I checked this was impossible but I'll take another crack at it and report back. Thanks

**Comment by mikhail-idris** [comment]
@smashah 
Yes, I think you are right with the assumption that it cannot be done.

I misconstrued the ability to do so directly from the app to that with the web variant.

I have checked and it is indeed not possible to change the business name directly from the web, only from the app itself.
