### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by contatodct** [open-wa/wa-automate-nodejs#1116]
^Croot@supernetzap:/var/www/bot/admin# ts-node app.ts
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                   ┃
┃   @open-wa/wa-automate                                                                            ┃
┃    💬 🤖 The most reliable NodeJS whatsapp library for chatbots with advanced features.           ┃
┃   Version: 3.1.0                                                                                  ┃
┃   Check out the latest changes: https://github.com/open-wa/wa-automate-nodejs#latest-changes      ┃
┃                                                                                                   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
- Initializing WA
- Browser Launched
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│       (index)       │                                                                    Values                                                                    │
├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│     WA_VERSION      │                                                                  undefined                                                                   │
│       PAGE_UA       │ 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '3.1.0'                                                                    │
│   BROWSER_VERSION   │                                                         'HeadlessChrome/83.0.4103.0'                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
- Injecting api
- WAPI injected
- Authenticating
- Authenticate to continue
set -> e Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined
    at window.<computed>.window.<computed> (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/lib/launch.js:1:31435)
    at __puppeteer_evaluation_script__:3:89
    at ExecutionContext._evaluateInternal (/var/www/bot/admin/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ExecutionContext.evaluate (/var/www/bot/admin/node_modules/puppeteer/lib/ExecutionContext.js:33:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/var/www/bot/admin/node_modules/puppeteer/lib/helper.js:94:19)
    at DOMWorld.evaluate (/var/www/bot/admin/node_modules/puppeteer/lib/DOMWorld.js:89:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (/var/www/bot/admin/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.evaluate (/var/www/bot/admin/node_modules/puppeteer/lib/Page.js:612:14)
    at Page.<anonymous> (/var/www/bot/admin/node_modules/puppeteer/lib/helper.js:95:27)
    at set (/var/www/bot/admin/node_modules/@open-wa/wa-automate/dist/controllers/auth.js:165:75)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by smashah** [comment]
@contatodct this only happened once?

**Comment by contatodct** [comment]
@smashah 
and so.......
let's assume I'm going to register the qrcode the first time .... it appears the qrcode normally and I can scan, but if I miss the scan, it gives this problem, so I need to wait a while to be able to scan, this error keeps showing up, so I wait about 2 hours and try again, here it goes

**Comment by contatodct** [comment]
![image](https://user-images.githubusercontent.com/66734743/100526764-c983ee00-31aa-11eb-992e-36daa6ec01ec.png)

**Comment by rahulserver** [comment]
I am facing the same issue on windows (10 64 bit). Seems working fine on MAC(Bug Sur/Catalina both).
It seems that once the app is run for the first time, then somewhere a cache is created. So subsequent qr scans do not lead to any further authentication.

**Comment by contatodct** [comment]
@rahulserver 
and exactly what happens ..... the first time goes normally, I use Debian 8.7 64Bits and it always worked normal, and now I face this problem

**Comment by rahulserver** [comment]
My initial run was on 3.0.8. Now even after i fix the package json version to "3.0.8" I still get this error on windows. 
Maybe someone might confirm this by running on another windows machine if my assumption is correct(that this app is broken on windows). @contatodct

**Comment by contatodct** [comment]
just tested on debian 64Bits and windows .... both have the same problem @rahulserver

**Comment by smashah** [comment]
@rahulserver @contatodct can you run with `headless: false` and then enter `Debug.VERSION` in the console to get the version number, please.

and/or take a screenshot of the browser window.

Also, try with `useChrome: true`

**Comment by rahulserver** [comment]
@smashah I have run with useChrome: true and headless: false same result. 
I am not near windows machine. I'll send the screenshot of the error once I get there. In short its the same error what @contatodct sent.

**Comment by smashah** [comment]
There's too much context missing from the original issue. I'm going to need you to fill in the issue template. In the meantime, I will test it on a windows machine.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️

**Comment by contatodct** [comment]
@smashah 
I'm using Debian, 8.7 64Bits and the Open-wa Example so I don't have an error, the first time it logs normally ..... it looks more like it loads a cache somewhere than when removing Session and trying again to register from another number it happens this ...

![100526843-8413f080-31ab-11eb-97f7-288c5518ce43](https://user-images.githubusercontent.com/66734743/100543035-9124f400-322c-11eb-8c5d-1d0f503ea426.png)

**Comment by edneijunior** [comment]
I believe it is related
https://github.com/visionmedia/debug/issues/797

**Comment by Qix-** [comment]
@edneijunior There's nothing to indicate this is a problem with `debug`.
