### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by contatodct** [open-wa/wa-automate-nodejs#1117]
I am using Debian, 8.7 64Bits and the Open-wa Example, the first time it registers normally ..... it seems more that it loads a cache somewhere that when removing the Session and trying again to register another number it it happens...

TEMPLATE:
```javascript
const wa = require('@open-wa/wa-automate');

wa.create({
  sessionId: "COVID_HELPER",
  authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
  blockCrashLogs: true,
  disableSpins: true,
  headless: true,
  hostNotificationLang: 'PT_BR',
  logConsole: false,
  popup: true,
  qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
}).then(client => start(client));

function start(client) {
  client.onMessage(async message => {
    if (message.body === 'Hi') {
      await client.sendText(message.from, '👋 Hello!');
    }
  });
}
```

![100526843-8413f080-31ab-11eb-97f7-288c5518ce43](https://user-images.githubusercontent.com/66734743/100543187-72732d00-322d-11eb-8ddb-b20157adb05d.png)

**Comment by smashah** [comment]
related: #1116

**Comment by smashah** [comment]
@contatodct when did this issue start and please add a screenshot of the browser here please

**Comment by contatodct** [comment]
@smashah  started about 5 days ago, I disabled the Browser with Use_chrome false

I am registering only through the terminal because I use Debian in text mode

**Comment by rahulserver** [comment]
I remember that this issue happened only after I tried registering from another number. Haven't tested this scenario on MAC though.

**Comment by contatodct** [comment]
@rahulserver that's right, whatever, it happens on any operating system!

and it only happens when I try to register another number

**Comment by smashah** [comment]
@rahulserver @contatodct if this happens on every operating system can you kindly take a screen recording of the process or a screenshot of the browser window when this happens please.

**Comment by contatodct** [comment]
@smashah as I said, I don't use a browser, I use it directly on my DEBIAN 8.7 64Bits terminal

[WhatsApp Video 2020-12-02 at 22.57.35.zip](https://github.com/open-wa/wa-automate-nodejs/files/5633176/WhatsApp.Video.2020-12-02.at.22.57.35.zip)

**Comment by edneijunior** [comment]
this happens with me too

**Comment by smashah** [comment]
@contatodct I have a sneaking suspicion that you're getting tos-blocked and then the system forces it to untosblock itself (which wow cool). I just need confirmation of this with a screenshot of the web page. OR! A screenshot of the folder structure from your process working directory. When this happens next, please run `ls` and take a screenshot. There may be a lingering folder there which is acting as the 'cache' leading to this error. @rahulserver @edneijunior 

So:

1. Run the program
2. If the error happens again, ctrl+c
3. `ls` (it may also be in the directory of the code)
4. Send me the screenshot here.

If that directory is there then simply deleting it before every run should fix this issue.

Another thing that may help is installing real chrome on your machines and running with `useChrome: true`.

Lastly, you really should NOT be running any puppeteer based program as root. Please make a new user and make that user run the program.

**Comment by Qix-** [comment]
@edneijunior This doesn't appear to have anything to do with `debug`. Please let me know if otherwise, but we have an upwards of 80 million weekly downloads with no reported issues thus far.

**Comment by smashah** [comment]
I also think this has nothing to do with `debug`

**Comment by smashah** [comment]
@rahulserver @contatodct I was not able to replicate the issue.

in https://github.com/open-wa/wa-automate-nodejs/releases/tag/3.1.4 it will take a screenshot if the error occurs again and add it into a `logs` folder. Please add this screenshot here next time.

This new version also tries to predict the error and attempts to "wait" for a valid session which may stop this problem from happening altogether.

**Comment by smashah** [comment]
@rahulserver @contatodct this new version may have fixed the issue. It may have been a case of Debian being too fast for the code. Adding a 2 second cool off before continuing to get the QR code looks like it fixed it.
