### ISSUE TITLE
sendLinkWithAutoPreview never resolves

### ISSUE THREAD

**Issue by mrodal** [open-wa/wa-automate-nodejs#1118]
The async function sendLinkWithAutoPreview never resolves:
![image](https://user-images.githubusercontent.com/20667544/100546538-a3109200-3240-11eb-95a5-db65f51db96e.png)

this breaks the python code, since WAPI.pyFunc expects the functions to resolve.

Cant debug code because its obfuscated:
![image](https://user-images.githubusercontent.com/20667544/100546561-c9cec880-3240-11eb-9001-32d30ae36fea.png)

**Comment by smashah** [comment]
@mrodal are you sure this never resolves? I'm unable to recreate the issue

**Comment by smashah** [comment]
@mrodal please restart and try again.

**Comment by mrodal** [comment]
looks like its fixed! thanks!
