### ISSUE TITLE
Freezing  in  Authenticating or time out

### ISSUE THREAD

**Issue by ruevers** [open-wa/wa-automate-nodejs#1124]
**Describe the bug**
Time out in authethication or freeze when is doing this

**Steps to Reproduce**
npx @open-wa/wa-automate
✓ Browser Launched
┌─────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                    Values                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2047.11'                                                                  │
│       PAGE_UA       │ 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '3.1.0'                                                                    │
│   BROWSER_VERSION   │                                                         'HeadlessChrome/88.0.4298.0'                                                         │
└─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
🌔  Authenticating

Error Navigation timeout of 30000 ms exceeded TimeoutError: Navigation timeout of 30000 ms exceeded
    at /home/ruevers/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
Last version installed using 
npm i --save @open-wa/wa-automate@latest
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS:UBUNTU 20

**Additional context**
Is working last week, today I try use and stay in autheticating or guive time out.

**Comment by smashah** [comment]
@ruevers does this only happen once?

**Comment by ruevers** [comment]
@smashah no, I tried multiple times im my vm, restore point, update again to last version, other ubuntu version 19, same issue, now I am installing a ubuntu 20 desktop to try see if this change, but for now same issue in diferente versions, old one and last one of this repository

**Comment by ruevers** [comment]
O done a fresh install of ubuntu 20.04.1 desktop, update and upgrade, instal version 14.15.1 npm  6.14.8 install as described 
npm i --save @open-wa/wa-automate@latest  and now when run the comand npx @open-wa/wa-automate -p 9000 freeze in 
"injecting API" after a lot of minuts I cancel and the time out messagem come again.

**Comment by smashah** [comment]
@ruevers Can you try with the latest version please https://github.com/open-wa/wa-automate-nodejs/releases/tag/3.1.1

`npx @open-wa/wa-automate@3.1.1 -p 9000`

then try this to see what's going on:

`npx @open-wa/wa-automate@3.1.1 -p 9000 --headful`

**Comment by ruevers** [comment]
I remove all software and reinstall, same issue, freeze in Authenticating 

![waerror4](https://user-images.githubusercontent.com/7357820/100677806-8fe9e900-334a-11eb-99cc-0b49fe95a0ab.jpg)
![waerror5](https://user-images.githubusercontent.com/7357820/100677815-94160680-334a-11eb-91b3-460370ed0e1b.jpg)

**Comment by smashah** [comment]
@ruevers the fact that you're getting an undefined WA_VERSION is very concerning, please run with `-headful` and then share a screenshot of the browser window.

**Comment by ruevers** [comment]
@smashah  I have a good news and a very bad news.
The good news I install in windows and work fine, is showin qr code and cofiguring fine, also using popup and headful parameter, in windows working fine, follow the screens and versions of nodejs e npm I installed in windows ( the problem is I prefer use a linux server for this)
![wawin1](https://user-images.githubusercontent.com/7357820/100689002-5e7d1780-3362-11eb-81a5-8f01f32e1427.jpg)
![wawin2](https://user-images.githubusercontent.com/7357820/100689029-676de900-3362-11eb-9f34-efbe8d245154.jpg)

I linux desktop or server the issues is the same, using --headful , after open the browser, he guive a time out in seconds and not show the page.
![wa3 1 1error-headful1](https://user-images.githubusercontent.com/7357820/100689158-b0be3880-3362-11eb-93e5-bd34654130ff.jpg)
![wa3 1 1error-headful2](https://user-images.githubusercontent.com/7357820/100689157-b0be3880-3362-11eb-881a-ffa77dea887d.jpg)
![wa3 1 1error-headful3](https://user-images.githubusercontent.com/7357820/100689167-b3b92900-3362-11eb-94f7-ca31a59f6e76.jpg)
The parameter headful in linux open the watsaup web windows and guive error, if I refresh the program close with the error in print screen below.
![wa3 1 1error-headful4](https://user-images.githubusercontent.com/7357820/100689582-7e610b00-3363-11eb-8962-dbcab16a99f0.jpg)


Using windows 10 I can use any of this parameters and the windows of the browsers open and everthing works. Hope I help to solve this, because of my tests, none linux, server or desktop are working anymore with this program, just windows.

**Comment by smashah** [comment]
@ruevers thanks so much for the screenshot of the browser. There may be a clue there, you're getting a SIGILL error in the browser. Are you able to open any other sites on another tab. Also what version of node are you using on that machine? Also, can you confirm that you are not running as root user

**Comment by smashah** [comment]
@ruevers you're running this in a vm? what's the host machine?

**Comment by smashah** [comment]
https://openradar.appspot.com/FB8922558#ag9zfm9wZW5yYWRhci1ocmRyFAsSB0NvbW1lbnQYgICAqv3V8AgM

**Comment by smashah** [comment]
@ruevers have you tried this? 

https://askubuntu.com/questions/821834/chrome-on-virtualbox-shows-blank-pages

**Comment by ruevers** [comment]
> @ruevers have you tried this?
> 
> https://askubuntu.com/questions/821834/chrome-on-virtualbox-shows-blank-pages

I had tried disable this, but avery time I start again npx the option is enable.
My linux version is 20.04.01, but I try in 19 server wich as wroking fine last week and have same issue.
I try put more ram to video 128, is the maximum of virtuabox, same issue with the browser
I try enable 3d accelaration in virtuabox, because is disable by default same issue in crhomin
I try webpage of whatsup in firefox and works fine, diferent of the crhomiun in the time of generate qrcode stop
I will try this linux in a desktop, not a vm, but I think will not work, because the problem can be betwen puppeter and chromiun

**Comment by ruevers** [comment]
A for wrost, I discoverer today my number was banned, I don´t know if is because of the number of attemps, so I am think not if is not bether use a api and enterprise account if this software can cause a ban in your account, very concerning this.

**Comment by smashah** [comment]
@ruevers I suggest hopping into discord to discuss/revert the ban. I'll add some documentation mentioning to not run this in a virtualbox VM. Closing for now thanks

**Comment by ruevers** [comment]
> @ruevers I suggest hopping into discord to discuss/revert the ban. I'll add some documentation mentioning to not run this in a virtualbox VM. Closing for now thanks

The odd think is, was working pretty good in vm one week ago.

**Comment by smashah** [comment]
@ruevers it may be due to a chrome issue. Please hop into the discord (click the discord badge in the readme) so we can resolve this issue quickly.

**Comment by ruevers** [comment]
> @ruevers have you tried this?
> 
> https://askubuntu.com/questions/821834/chrome-on-virtualbox-shows-blank-pages



> @ruevers it may be due to a chrome issue. Please hop into the discord (click the discord badge in the readme) so we can resolve this issue quickly.

And for last I don´t think is very clever send message yourself by app, saying your watsaup are conrtolled by a remote resource and if it is not you to logout of all web resource, for 2 reasons, is not comun and not possible send mensagem to yourself in normal watsaup and the container of the message, whit this the robots of whatsup can fast find this behavear and block everyone with do the same.
I send email and my whatsup was unbluck, but at list remove this automatic message, because I think this cause my block.

**Comment by ruevers** [comment]
> @ruevers I suggest hopping into discord to discuss/revert the ban. I'll add some documentation mentioning to not run this in a virtualbox VM. Closing for now thanks

I think is not related with VM, I try in other linux in a laptop and have a same issue, headful browser window guive a statu_access_violation

**Comment by smashah** [comment]
@ruevers do you have chrome installed?

**Comment by ruevers** [comment]
> @ruevers do you have chrome installed?

Yes, I have chrome installed and I think I solved problem, because work 1 one windows desktop and another not, so I start to investgate just the chromiun in win 10 wich not working, the whatsup page not open too, same issue, so I find it in direcotry and try work stand alone, same issue, chromium crash in whatsup page, so I find a workaround, download the last version(833255) of chromium in page. https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/ and copy the content of foder chrome-win to  node_modules\pupepetter\.local_chromim\win64-818858\chrome-win and start work wint parameter hearful or not. working normal, now I will try this same workaround in my linux vm, SO, the problem is not vm, is just some issue of the old verssion of chromium with web whatsup page.

**Comment by ruevers** [comment]
> > @ruevers do you have chrome installed?
> 
> Yes, I have chrome installed and I think I solved problem, because work 1 one windows desktop and another not, so I start to investgate just the chromiun in win 10 wich not working, the whatsup page not open too, same issue, so I find it in direcotry and try work stand alone, same issue, chromium crash in whatsup page, so I find a workaround, download the last version(833255) of chromium in page. https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/ and copy the content of foder chrome-win to node_modules\pupepetter.local_chromim\win64-818858\chrome-win and start work wint parameter hearful or not. working normal, now I will try this same workaround in my linux vm, SO, the problem is not vm, is just some issue of the old verssion of chromium with web whatsup page.
I think is good you guys open a issue or bug in puppeter, how you have more influence in github they will listen more carefull and correct the problem more fast.

**Comment by ruevers** [comment]
> > > @ruevers do you have chrome installed?
> > 
> > 
> > Yes, I have chrome installed and I think I solved problem, because work 1 one windows desktop and another not, so I start to investgate just the chromiun in win 10 wich not working, the whatsup page not open too, same issue, so I find it in direcotry and try work stand alone, same issue, chromium crash in whatsup page, so I find a workaround, download the last version(833255) of chromium in page. https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/ and copy the content of foder chrome-win to node_modules\pupepetter.local_chromim\win64-818858\chrome-win and start work wint parameter hearful or not. working normal, now I will try this same workaround in my linux vm, SO, the problem is not vm, is just some issue of the old verssion of chromium with web whatsup page.
> > I think is good you guys open a issue or bug in puppeter, how you have more influence in github they will listen more carefull and correct the problem more fast.
And please take out this message of this program "Your account is currently being controlled by a automation service. If you have not autorized this then please logout from all devices in whats wap web" because after be unblocked by google they guive a little of understand wich this cause of thing can block the accounts, because is very uncomun person send messages by yourself and all times same messagem, the bots of faceboook are not dummy and will cath very soon who are using this program and will bock all forever.

**Comment by smashah** [comment]
Awesome, just FYI, setting

https://docs.openwa.dev/interfaces/configobject.html#browserrevision

does the same as you said

So 

`browserRevision: "833255"` 

At the moment this config is blocked from the CLI. But I will allow it in the CLI so in future versions you will be able to set it like so:

 `--browser-revision "833255"

Also, if you have the normal chrome (not chromium) installed on your machine, you can just use `--use-chrome` flag to bypass chromium builds all together

**Comment by ruevers** [comment]
> Awesome, just FYI, setting
> 
> https://docs.openwa.dev/interfaces/configobject.html#browserrevision
> 
> does the same as you said
> 
> So
> 
> `browserRevision: "833255"`
> 
> At the moment this config is blocked from the CLI. But I will allow it in the CLI so in future versions you will be able to set it like so:
> 
> `--browser-revision "833255"`
> 
> Also, if you have the normal chrome (not chromium) installed on your machine, you can just use `--use-chrome` flag to bypass chromium builds all toge

When I use --use-chrome he enter and after secondes crash ang guive me error
Shutting Down
Error Cannot read property 'user' of undefined TypeError: Cannot read property 'user' of undefined
    at C:\Users\asus\AppData\Roaming\npm-cache\_npx\364\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:402:86
    at step (C:\Users\asus\AppData\Roaming\npm-cache\_npx\364\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:63:23)
    at Object.next (C:\Users\asus\AppData\Roaming\npm-cache\_npx\364\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:44:53)
    at fulfilled (C:\Users\asus\AppData\Roaming\npm-cache\_npx\364\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
internal/fs/utils.js:308
    throw err;
    ^

Error: EPERM: operation not permitted, unlink 'C:\Users\asus\AppData\Roaming\npm-cache\_npx\364\node_modules\@open-wa\wa-automate\node_modules\sharp\build\Release\libglib-2.0-0.dll'
    at Object.unlinkSync (fs.js:1210:3)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:219:13)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:350:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:349:26)
    at rmdirSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:342:7)
    at fixWinEPERMSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:217:5)
    at rimrafSync (C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\rimraf\rimraf.js:350:5 {
  errno: -4048,
  syscall: 'unlink',
  code: 'EPERM',
  path: 'C:\\Users\\asus\\AppData\\Roaming\\npm-cache\\_npx\\364\\node_modules\\@open-wa\\wa-automate\\node_modules\\sharp\\build\\Release\\libglib-2.0-0.dll'



, for now, the most estable work around is change the chromium in puppeter to last version.

**Comment by smashah** [comment]
@ruevers can you please share all of the logs from the `--use-chrome` run. Actually, give me all of the logs using `--use-chrome --headful`.

**Comment by ruevers** [comment]
> @ruevers can you please share all of the logs from the `--use-chrome` run. Actually, give me all of the logs using `--use-chrome --headful`.

Solved, if anyone need use a linux vm server withoth xserver just need install version 3.0.16 of opewnawa

install this packages.

sudo apt-get install -y libpango-1.0-0
sudo apt-get install -y libpangocairo-1.0-0
sudo apt-get install -y libstdc++6
sudo apt-get install -y libx11-6
sudo apt-get install -y libx11-xcb1
sudo apt-get install -y libxcb1
sudo apt-get install -y libxcomposite1
sudo apt-get install -y libxcursor1
sudo apt-get install -y libxdamage1
sudo apt-get install -y libxext6
sudo apt-get install -y libxfixes3
sudo apt-get install -y libxi6
sudo apt-get install -y libxrandr2
sudo apt-get install -y libxrender1
sudo apt-get install -y libxss1
sudo apt-get install -y libxtst6
sudo apt-get install -y lsb-release
sudo apt-get install -y wget
sudo apt-get install -y xdg-utils
sudo apt-get install -y libcups2
sudo apt-get install -y libxss1
sudo apt-get install -y libnss3-tools
 sudo apt-get install -y freetype2-demos
 sudo apt-get install -y libfreetype-dev
 sudo apt-get install -y libharfbuzz-dev
sudo apt-get install -y ttf-freefont
sudo apt-get install -y ca-certificates
sudo apt-get install -y fonts-liberation
sudo apt-get install -y libappindicator3-1
sudo apt-get install -y libasound2
sudo apt-get install -y libatk-bridge2.0-0
sudo apt-get install -y libatk1.0-0
sudo apt-get install -y libc6
sudo apt-get install -y libcairo2
sudo apt-get install -y libcups2
sudo apt-get install -y libdbus-1-3
sudo apt-get install -y libexpat1
sudo apt-get install -y libfontconfig1
sudo apt-get install -y libgbm1
sudo apt-get install -y libgcc1
sudo apt-get install -y libglib2.0-0
sudo apt-get install -y libgtk-3-0
sudo apt-get install -y libnspr4
sudo apt-get install -y libnss3
sudo apt-get install -y libpango-1.0-0
sudo apt-get install -y libpangocairo-1.0-0
sudo apt-get install -y libstdc++6
sudo apt-get install -y libx11-6
sudo apt-get install -y libx11-xcb1
sudo apt-get install -y libxcb1
sudo apt-get install -y libxcomposite1
sudo apt-get install -y libxcursor1
sudo apt-get install -y libxdamage1
sudo apt-get install -y libxext6
sudo apt-get install -y libxfixes3
sudo apt-get install -y libxi6
sudo apt-get install -y libxrandr2
sudo apt-get install -y libxrender1
sudo apt-get install -y libxss1
sudo apt-get install -y libxtst6
sudo apt-get install -y lsb-release
sudo apt-get install -y wget
sudo apt-get install -y xdg-utils
sudo apt install -y libnss3


and after install in directory /home/ruevers/wa/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux

unpack and copy this files to this directory from 
https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F833368%2Fchrome-linux.zip?generation=1607021483151856&alt=media
