### ISSUE TITLE
Audio not received

### ISSUE THREAD

**Issue by aidilaryanto** [open-wa/wa-automate-nodejs#1126]
![Screenshot_20201201-134425871](https://user-images.githubusercontent.com/57789597/100701871-6fb63a80-33db-11eb-8818-dacd61357904.jpg)
![Screenshot_20201201-134439427](https://user-images.githubusercontent.com/57789597/100701879-72b12b00-33db-11eb-8717-fb1a5b7354b5.jpg)

**Comment by smashah** [comment]
@aidilaryanto can you please fill in the issue template with some CC examples, please. I don't want this project to get youtube-dl'ed

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
