### ISSUE TITLE
Is it possible to terminate the Create function conditionally?

### ISSUE THREAD

**Issue by LUN7** [open-wa/wa-automate-nodejs#1128]

**Comment by smashah** [comment]
@LUN7 will need more details. In general, it's not possible to terminate a promise, you either have to wait for it to catch or resolve. You can limit how long you're waiting for a `create` to resolve by setting authTimeout/qrTimeout.

**Comment by LUN7** [comment]
I would like to terminate the promise while a client terminate the restful api call unexpectedly.

**Comment by smashah** [comment]
According to:

You need to implement bluebird with cancellable promises.

1. Install bluebird
	
		> npm i bluebird

then 

```javascript
	import {Promise} from "bluebird";
```

2. Enable cancellation to the promise config:

```javascript
Promise.config({
    cancellation: true,
});
```

3. Create a 'cancellable' promise out of `create` which you can reference:

```javascript
// set the reference to the promise, do not await it straight away.
		this.cancellableCreate = new Promise((resolve,reject)=>create(...).then(resolve).catch(reject));

	const client = await this.cancellableCreate;
```

4. Then use that reference to cancel it somewhere else

```javascript
	app.post('/cancel', (req,resp)=>{
		this.cancellableCreate.cancel()
	})
```

Let me know if this works for you thanks, I may implement this in v4.

**Comment by LUN7** [comment]
it helps. Thanks!
