### ISSUE TITLE
Message type of sticker

### ISSUE THREAD

**Issue by aidilaryanto** [open-wa/wa-automate-nodejs#1129]
What is message type of stiker? 'image'?

**Comment by zalviandyr** [comment]
you can use function sendImageAsSticker

**Comment by aidilaryanto** [comment]
> you can use function sendImageAsSticker

No. I want detect sticker on message

**Comment by zalviandyr** [comment]
you can check message type 

```javascript
if (message.type === 'sticker'){
// do something
}
```

theres a list available message types [https://open-wa.github.io/wa-automate-nodejs/enums/messagetypes.html](https://open-wa.github.io/wa-automate-nodejs/enums/messagetypes.html)

**Comment by smashah** [comment]
thanks @zalviandyr
