### ISSUE TITLE
getMentionList is not defined

### ISSUE THREAD

**Issue by sycletz** [open-wa/wa-automate-nodejs#1132]
Music Error : Error: Evaluation failed: ReferenceError: getMentionsList is not defined
    at Object.window.<computed>.<computed> [as sendImage] (__puppeteer_evaluation_script__:1:102710)
    at __puppeteer_evaluation_script__:3:45

**Comment by aidilaryanto** [comment]
Same here. Error when fetch

**Comment by SlavyanDesu** [comment]
Same here, I thought my code was wrong

**Comment by smashah** [comment]
@SlavyanDesu @aidilaryanto @sycletz should be fixed now please restart your sessions in about 5 minutes

**Comment by aidilaryanto** [comment]
> @SlavyanDesu @aidilaryanto @sycletz should be fixed now please restart your sessions in about 5 minutes

Restart session means rescan QR?

**Comment by smashah** [comment]
@aidilaryanto no, just ctrl+c and then run again.

**Comment by SlavyanDesu** [comment]
> @SlavyanDesu @aidilaryanto @sycletz should be fixed now please restart your sessions in about 5 minutes

![Screenshot_20201203-022229](https://user-images.githubusercontent.com/28254882/100920997-87421000-350e-11eb-83e4-bef4060e6fa2.jpg)

It worked, thank you!
