### ISSUE TITLE
Authentication issues ..

### ISSUE THREAD

**Issue by cosmo83** [open-wa/wa-automate-nodejs#1134]
Iam not able to Authenticate from a last few hours .. I even tried --headful, and though web.whatsapp.com is logged in, the program is not able to detect that its authenticated.

**Comment by ruevers** [comment]
I had a similar issue, maybe help you my workaround https://github.com/open-wa/wa-automate-nodejs/issues/1134#issue-755766831

**Comment by edneijunior** [comment]
i'm too

**Comment by smashah** [comment]
I'm unable to replicate the issue with the instructions given. Please fill in the issue template @cosmo83

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️

**Comment by ruevers** [comment]
> @github-actions run
> 
> Template!

what´s the discord link? I not able to find.

**Comment by smashah** [comment]
@ruevers click on the discord badge in the readme

**Comment by cosmo83** [comment]
Never mind .. Looks like an issue with chrome browser. Pointed to a headless browser and works fine .

**Comment by smashah** [comment]
@cosmo83 in the latest version you can set a custom browser revision using `--browser-revision`

e.g:

`--browser-revision 123123`

see this for browser revision documentation: https://docs.openwa.dev/interfaces/configobject.html#browserrevision

also, best thing to do is always use the latest version of chrome with `--use-chrome`
