### ISSUE TITLE
Please take out the message when you auteticate

### ISSUE THREAD

**Issue by ruevers** [open-wa/wa-automate-nodejs#1137]
Please take out the message when you auteticate "Your account is currently being controlled by a automation service. If you have not autorized this then please logout from all devices in whats wap web" because after be unblocked by google they guive a little of understand wich this cause of thing can block the accounts, because is very incomun person send messages ti yourself and all times same messagem, the bots of faceboook are not dummy and will cath very soon who are using this program and will bock all forever. After you do this 2 or 3 times the bot of whats are blocking your acounts.

**Comment by smashah** [comment]
Your concerns are noted. This will not be removed any time soon. Might update the message though:

https://github.com/open-wa/wa-automate-nodejs/issues/709

**Comment by ruevers** [comment]
> Your concerns are noted. This will not be removed any time soon. Might update the message though. Please see:
> 
> #709

I understand the message is good to avoid unautorazed access, but the problem is is causing block of the whatsup plataform, because they think is a hacker atempt, is best had no message or a parameter to send or not.

**Comment by smashah** [comment]
@ruevers Please join the discord so you can talk more about bans. No ban talk on public issues.
