### ISSUE TITLE
sendText route from EasyAPI returning success: false

### ISSUE THREAD

**Issue by lbertoncello** [open-wa/wa-automate-nodejs#1143]
sendText route from EasyAPI is returning { success: false, error: {} } sometimes, even when the message was successfully sent (I'm checking in WA Business). I can't tell what triggers this bug, most of the time the response is correct. I think it's not related to specific WhatsApp numbers, because I've tried to send message to those numbers again and the response was correct.

These numbers are not contacts in my phone, but I do have a lincese key of wa-automate.

**DEBUG INFO**
```
Debug Info {
  WA_VERSION: '2.2047.12',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.1.1',
  BROWSER_VERSION: 'HeadlessChrome/88.0.4298.0'
}
```

**Comment by smashah** [comment]
@lbertoncello Please can you send me the chat ids that this happens with

**Comment by smashah** [comment]
Closing for now. Please report back if this keeps happening. Thanks
