### ISSUE TITLE
Only work locally, broken in deployment, especially heroku

### ISSUE THREAD

**Issue by LouisAldorio** [open-wa/wa-automate-nodejs#1146]
**Describe the bug**

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
Will need more detail

**Comment by smashah** [comment]
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-heroku

**Comment by smashah** [comment]
@LouisAldorio 
![image](https://user-images.githubusercontent.com/5903821/101294713-464d4280-3811-11eb-932c-2655769bfb84.png)

**Comment by smashah** [comment]
#296
