### ISSUE TITLE
Can't upload .wav files from external URL.

### ISSUE THREAD

**Issue by jamborghini** [open-wa/wa-automate-nodejs#1150]
**Describe the bug**
Whenever I try to upload a `.wav` file from an external URL rather than my local, It fails.

**Steps to Reproduce**
1. Execute code 
```js
client.onAnyMessage(async (msg) => {
    
    if (msg.body.startsWith('aan')) {      //or any other .wav file.
      await client.sendAudio(msg.chatId, 'https://www2.cs.uic.edu/~i101/SoundFiles/StarWars3.wav', msg.id);

    }
```

2. Send a message starting with `aan` or your prefered word to any chat.
3. See the file trying to upload.
4. See it'll just try to upload and won't resolve the request.

**create() code**
This is the code you use to create the client. e.g
```javascript
create({
  useChrome: true,
  restartOnCrash: start,
  headless: false,
  throwErrorOnTosBlock: true,
  qrTimeout: 0,
  authTimeout: 0,
  killProcessOnBrowserClose: true,
  autoRefresh: true,
  safeMode: false,
  disableSpins: false,
  hostNotificationLang: NotificationLanguage.PTBR,
  popup: 3012,
  defaultViewport: null,
}).then(async (client) => await start(client));
```

**Expected behavior**
To successfully upload the .wav audio file right after I send the message `aan`.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2047.12',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.1.5',
  BROWSER_VERSION: 'Chrome/85.0.4183.121'
}
```

**Screenshots**
<img src="https://i.imgur.com/Hb6dCNQ.png">

**Host (please complete the following information):**
 - OS: Linux 5.6 (Solus)

**Additional context**
There is no problem with uploading mp3 files or any other but can't seem to be uploading `.wav` files.

**Comment by smashah** [comment]
@jamborghini thanks for filling out the template properly. Unfortunately not every audio format is supported by WA and this project can obviously not create automatic converters for every single file type. I highly suggest using some sort of audio conversion API before using this library. Or check if ffmpeg-fluent can convert this file for you. Or of course just use MP3 files from the beginning

**Comment by jamborghini** [comment]
> @jamborghini thanks for filling out the template properly. Unfortunately not every audio format is supported by WA and this project can obviously not create automatic converters for every single file type. I highly suggest using some sort of audio conversion API before using this library. Or check if ffmpeg-fluent can convert this file for you. Or of course just use MP3 files from the beginning

Thanks for the reply, yeah I was thinking the same thing, convertin from an API before uploading it, I'll check them out. Thank again, have a good day.

**Comment by smashah** [comment]
Thanks for understanding @jamborghini `fluent-ffmpeg` is a dependency of thks project so you might as well use it to convert the file (if that's even possible via ffmpeg)
