### ISSUE TITLE
external connection

### ISSUE THREAD

**Issue by orinocodev** [open-wa/wa-automate-nodejs#1160]
Hi, I have an application made in laravel and nuxt and I want to connect it to wa-automate-nodejs and thus have access to all the functions externally

**Comment by smashah** [comment]
@orinocodev try out the heroku deployment (button in readme). It will give you an instance of open wa with a secure api layer with api docs also.


Soon there will be generated SDKs also to Support most languages.

https://github.com/open-wa/wa-automate-deploy-heroku

**Comment by orinocodev** [comment]
@smashah thanks for the info.

**Comment by smashah** [comment]
Np. Closing for now.
