### ISSUE TITLE
QR Code not authenticating.

### ISSUE THREAD

**Issue by randracar** [open-wa/wa-automate-nodejs#1167]
I recently started to use the API, and I always get this error:

Before the QR code, the following error appear at the console:

Screenshot taken. path: ./logs/Imperial/1607635507566
Screenshot taken. path: ./logs/Imperial/1607635507566
qr -> e Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined
    at window.<computed>.window.<computed> (/home/random-guy/Documents/imageToSticker/node_modules/@open-wa/wa-automate/dist/lib/launch.js:1:36887)
    at __puppeteer_evaluation_script__:3:85
    at ExecutionContext._evaluateInternal (/home/random-guy/Documents/imageToSticker/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

After that, the QR code does appear, but, it does not authenticate.
![Captura de tela de 2020-12-10 18-25-38](https://user-images.githubusercontent.com/63797127/101832204-cd523180-3b15-11eb-8f0b-a633334a5c04.png)

**Comment by smashah** [comment]
@randracar please fill in the issue template

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
