### ISSUE TITLE
sendMp4AsSticker without crop?

### ISSUE THREAD

**Issue by aidilaryanto** [open-wa/wa-automate-nodejs#1188]
How to sendMp4AsSticker without crop?

**Comment by smashah** [comment]
@aidilaryanto can you show me an example of the issue you're having with the crop? I set it so the crop results in a centered square

**Comment by aidilaryanto** [comment]
> @aidilaryanto can you show me an example of the issue you're having with the crop? I set it so the crop results in a centered square

Can you add setting for no crop too?

**Comment by aidilaryanto** [comment]
Sometimes I need to no cropping to fit all content

**Comment by smashah** [comment]
Ok

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.1.11](https://github.com/open-wa/wa-automate-nodejs/compare/3.1.10...3.1.11) (2020-12-22)

- build(deps-dev): bump @types/node from 14.14.13 to 14.14.14 [`#1182`](https://github.com/open-wa/wa-automate-nodejs/pull/1182)
- build(deps-dev): bump @grupoboticario/news-fragments from 1.8.0 to 1.9.0 [`#1183`](https://github.com/open-wa/wa-automate-nodejs/pull/1183)
- build(deps-dev): bump marked from 1.2.6 to 1.2.7 [`#1185`](https://github.com/open-wa/wa-automate-nodejs/pull/1185)
- build(deps): bump tcp-port-used from 1.0.1 to 1.0.2 [`#1184`](https://github.com/open-wa/wa-automate-nodejs/pull/1184)
- build(deps): bump ts-json-schema-generator from 0.80.0 to 0.81.0 [`#1190`](https://github.com/open-wa/wa-automate-nodejs/pull/1190)
- build(deps): bump axios from 0.21.0 to 0.21.1 [`#1191`](https://github.com/open-wa/wa-automate-nodejs/pull/1191)
- Release 3.1.11 [`faf1931`](https://github.com/open-wa/wa-automate-nodejs/commit/faf1931a6bdacc91c8e46ee05d9ccf8fe052aad7)
- Feature: `eventMode`. Receive all callbacks on `ev` event emitter!! #1042 [`2be34c5`](https://github.com/open-wa/wa-automate-nodejs/commit/2be34c5560cce62422a4ae18ff82463c8c048d32)
- Updated documentation for group participant changes [`707ee87`](https://github.com/open-wa/wa-automate-nodejs/commit/707ee87d8311b2a9de88455ffe64266fdf7a31c7)
- Feature: Bypass sticker video crop #1188 [`7eaced6`](https://github.com/open-wa/wa-automate-nodejs/commit/7eaced618e164f92901316a623f112af594b77d2)
- Update heroku button and support WA version [`5a32ffd`](https://github.com/open-wa/wa-automate-nodejs/commit/5a32ffd649fe4568f05e8be51146bf5885b16d77)
- patch update [`149b29f`](https://github.com/open-wa/wa-automate-nodejs/commit/149b29fb236bdeb71c487877cfc0c462cb2a79d5)
- CLI: forward user to api-docs if they go to root path [`1df0e44`](https://github.com/open-wa/wa-automate-nodejs/commit/1df0e44856c0f1b57e162ac711203ad021d53566)
- patches update [`7d3744c`](https://github.com/open-wa/wa-automate-nodejs/commit/7d3744c61011acdc9626b73c9940bc91890c80a8)
- added `--incognito` flag by default [`9f27c67`](https://github.com/open-wa/wa-automate-nodejs/commit/9f27c679a773ad7b3dc2032c0d3a26a1dc97d227)

**Comment by smashah** [comment]
@aidilaryanto It missed the documentation in the latest version however it is implemented.

You can now set `crop: false` [default: `true`] in the third parameter (processOptions) of [sendMp4AsSticker](https://docs.openwa.dev/classes/client.html#sendmp4assticker)

e.g:

```javascript
	await client.sendMp4AsSticker('...chatid','...file',{crop:false});
```

Please try it out and report back if it is working as expected in the latest version.

Thanks

**Comment by aidilaryanto** [comment]
Thankyou so much
