### ISSUE TITLE
How to Make Custom Reply ?

### ISSUE THREAD

**Issue by albertstyles312** [open-wa/wa-automate-nodejs#1198]
like we replied to him but he didn't type anything

**Comment by albertstyles312** [comment]
like we replied to him but he didn't type anything

**Comment by smashah** [comment]
@albertstyles312 can you be a little more specific with screenshots please

**Comment by SlavyanDesu** [comment]
> @albertstyles312 can you be a little more specific with screenshots please

![received_440143903817109](https://user-images.githubusercontent.com/28254882/103754139-88e78200-503e-11eb-8e13-cfa5b4458384.jpeg)
Let me help.
As you can see, the mentioned user (Anda/me) wasn't sent a single message but the bot replied my message that never exist. This is literally generating a fake message id.

**Comment by smashah** [comment]
@SlavyanDesu can you share the code you are using that results in this behaviour, please.

Also, sometimes what you see on the host account is not what the recipients/group participants see. Can you confirm using another phone that the resultant message is also showing this issue?

**Comment by smashah** [comment]
Closing for now. Please reply with more information if you want this issue reopened.

Thanks

**Comment by smashah** [comment]
If I understand this correctly, you want to be able to generate a completely fake quoted message?

**Comment by SlavyanDesu** [comment]
Yeah, perhaps.
