### ISSUE TITLE
Help to do a simple Interface 

### ISSUE THREAD

**Issue by marlon33** [open-wa/wa-automate-nodejs#1200]
Hello, I'm new here and I would like to know if it is possible to create an html interface using socket.io, I work with real estate sales, and I think I can send messages easier, if possible can someone say how or post a tutorial? I came from php css html C # python, but nodejs is new to me

**Comment by smashah** [comment]
@marlon33 Soon there will be a UI library for platform-agnostic (vue/angular/react) web components. I suggest signing up to the discord for updates as to when that gets released (maybe in the next few months).

At the same time, keep an eye on #1100 for when you will be able to interact with the sessions fully using socket.io

Closing for now.

Thanks
