### ISSUE TITLE
getAllChats doesn't bring profile pic depending on viewport size

### ISSUE THREAD

**Issue by JulioLongo** [open-wa/wa-automate-nodejs#1207]
When I change viewport height size on startup, it brings more profiles pics

pic of chat item that has this problem

![image](https://user-images.githubusercontent.com/33060329/103387666-c8b0e580-4ae3-11eb-8506-15794ed4ff1b.png)

**Comment by smashah** [comment]
@JulioLongo use this to get the missing pics:

https://docs.openwa.dev/classes/client.html#getprofilepicfromserver

**Comment by smashah** [comment]
Closing for now. Thanks
