### ISSUE TITLE
EasyAPI Send Video

### ISSUE THREAD

**Issue by axixu** [open-wa/wa-automate-nodejs#1213]
Hi, is there tutorial to send video (MP4) from EasyAPI? thx. 

I've tried use sendFile, sendFileFromURL but the sent video come as file. my OS is Debian 10 on AWS.

this is my getConfig EasyAPI:
{
  "success": true,
  "response": {
    "autoRefresh": true,
    "useChrome": true,
    "port": 8002,
    "ev": false,
    "allowSessionDataWebhook": false,
    "host": "localhost",
    "noApi": false,
    "generateApiDocs": true,
    "sessionDataOnly": false,
    "inDocker": false,
    "skipSavePostmanCollection": false,
    "popup": false,
    "headful": false,
    "preAuthDocs": false,
    "headless": true,
    "executablePath": "/usr/bin/google-chrome-stable"
  }
}

**Comment by smashah** [comment]
@axixu you need to use chrome but also make sure ffmpeg is installed on your machine

**Comment by axixu** [comment]
Oke thx I will try it...
