### ISSUE TITLE
Get user pushname from sender.id

### ISSUE THREAD

**Issue by SlavyanDesu** [open-wa/wa-automate-nodejs#1227]
Hello. Is there a way to get pushname from sender.id? Thanks in advance.

**Comment by AlenSaito1** [comment]
You can get the pushname of the user from `message.sender.pushname` [message.sender](https://docs.openwa.dev/interfaces/message.html#sender)
or use `getContact(sender.id)` [contact](https://docs.openwa.dev/interfaces/contact.html#pushname)

**Comment by SlavyanDesu** [comment]
> You can get the pushname of the user from [`message.sender.pushname`](https://docs.openwa.dev/interfaces/message.html#sender)
> or use [`getContact(sender.id)`](https://docs.openwa.dev/interfaces/contact.html#pushname)

Thank you for replying! `getContact(sender.id)` is what I've looking for.
