### ISSUE TITLE
Add subject in groupMetadata

### ISSUE THREAD

**Issue by Kry9toN** [open-wa/wa-automate-nodejs#1230]
Please add subject on groupMetadata for group name return

**Comment by smashah** [comment]
@Kry9toN can you be more specific? Which method is missing the group subject?

**Comment by Kry9toN** [comment]
> @Kry9toN can you be more specific? Which method is missing the group subject?

How i get the name group on groupMetadata?

**Comment by smashah** [comment]
@Kry9toN in order to answer this question i need to know how you are getting to the group metadata. Maybe I'll just make a new `client` method called `getGroupInfo` with the title and subject. Would that resolve this for you or are you looking for more information?

**Comment by Kry9toN** [comment]
> @Kry9toN in order to answer this question i need to know how you are getting to the group metadata. Maybe I'll just make a new `client` method called `getGroupInfo` with the title and subject. Would that resolve this for you or are you looking for more information?

Yes, create a method like that, it will resolve👍

**Comment by smashah** [comment]
@Kry9toN In v3.1.13 can now use `client.getGroupInfo('123123123-1231231232@c.us)` to get the title and description [(docs)](https://docs.openwa.dev/classes/client.html#getgroupinfo)


```javascript
	const groupInfo = await client.getGroupInfo('123123123-1231231232@c.us)
	/**
	 * {
	 *  title: 'Cool Group',
	 *  description: 'Cool description'
	 * }
	 */
```

**Comment by Kry9toN** [comment]
> @Kry9toN In v3.1.13 can now use `client.getGroupInfo('123123123-1231231232@c.us)` to get the title and description [(docs)](https://docs.openwa.dev/classes/client.html#getgroupinfo)
> 
> ```js
> 	const groupInfo = await client.getGroupInfo('123123123-1231231232@c.us)
> 	/**
> 	 * {
> 	 *  title: 'Cool Group',
> 	 *  description: 'Cool description'
> 	 * }
> 	 */
> ```

Thanks you so much

**Comment by Kry9toN** [comment]
> @Kry9toN In v3.1.13 can now use `client.getGroupInfo('123123123-1231231232@c.us)` to get the title and description [(docs)](https://docs.openwa.dev/classes/client.html#getgroupinfo)
> 
> ```js
> 	const groupInfo = await client.getGroupInfo('123123123-1231231232@c.us)
> 	/**
> 	 * {
> 	 *  title: 'Cool Group',
> 	 *  description: 'Cool description'
> 	 * }
> 	 */
> ```

Can you also create a method `getUserInfo` then return pushname, photo profile, etc

**Comment by smashah** [comment]
@Kry9toN sure just open a new issue
