### ISSUE TITLE
Add new metod getUserInfo

### ISSUE THREAD

**Issue by Kry9toN** [open-wa/wa-automate-nodejs#1232]
@smashah Please add metod `getUserInfo('13244564333@c.us')` with return pushname, photo profile, and etc

**Comment by smashah** [comment]
@Kry9toN have you tried [`client.getContact()`](https://docs.openwa.dev/classes/client.html#getcontact)?

**Comment by Kry9toN** [comment]
> @Kry9toN have you tried [`client.getContact()`](https://docs.openwa.dev/classes/client.html#getcontact)?

No. I just found out about that method, maybe I'll try to use it
