### ISSUE TITLE
send sticker with about

### ISSUE THREAD

**Issue by Jonas33235** [open-wa/wa-automate-nodejs#1233]
option to change the description of the sticker by pressing it

**Comment by smashah** [comment]
@Jonas33235 can you provide some screenshots please

**Comment by SlavyanDesu** [comment]
@Jonas33235 
![Screenshot_20210115-024057](https://user-images.githubusercontent.com/28254882/104640508-28f67880-56db-11eb-994f-80d5e64b4c90.jpg)
Like this perhaps?

**Comment by smashah** [comment]
@Jonas33235 ah ok. This is a duplicate of #682 

Please keep track of that issue. It is currently on the to-do list.

Thanks

**Comment by Jonas33235** [comment]
> @Jonas33235
> ![Screenshot_20210115-024057_1](https://user-images.githubusercontent.com/28254882/104640716-6f4bd780-56db-11eb-9d2f-82e154ece6f9.jpg)
> 
> Like this perhaps?

send this group link
?

**Comment by Jonas33235** [comment]
> @Jonas33235 ah ok. This is a duplicate of #682
> 
> Please keep track of that issue. It is currently on the to-do list.
> 
> Thanks

error, 
![image](https://user-images.githubusercontent.com/56744848/104681008-11fe5900-56d0-11eb-9902-a2ae8cc6317d.png)

**Comment by SlavyanDesu** [comment]
If you want to create sticker metadata so badly, you need to make an EXIF file that contains your metadata. And then add it to your raw webp sticker. Of course, you need a [libwebp](https://developers.google.com/speed/webp/download) lib.
