### ISSUE TITLE
How to visualize emojis ?

### ISSUE THREAD

**Issue by jpramirezp** [open-wa/wa-automate-nodejs#1245]
Hi, this libray is awesome, I want to know if is possible retrieve the emojis or emoticons from the messages, I only can see the ? sign  �

**Comment by smashah** [comment]
@jpramirezp Thanks, can you provide some screenshots of the issue please?

**Comment by gnadelwartz** [comment]
if you see this for almost all emjois than you display the characters in an evironment without UFT-8, this is alo the case if language specific charaters are shown as <?>  e.g. `ä,δ, Δ,ν,πش`  

Can you pls provide OS, LANG setting etc.


If you are on Linux / Unix LANG should be something like xx_XX-utf-8
```bash 
echo $LANG

C.UTF-8
en_US.UTF-8
de_DE.UTF-8
```

**Comment by smashah** [comment]
Closing thanks. Feel free to add more info @jpramirezp
