### ISSUE TITLE
`promoteParticipany` never works for me

### ISSUE THREAD

**Issue by Aminadav** [open-wa/wa-automate-nodejs#1249]
**Describe the bug**
I'm calling promoteParticipany but it doesn't do anything.
I'm trying to give someone from the group the admin permission.
I'm using the EasyAPI. if it's working for others, I will give all the other details. (version, etc')

**Comment by smashah** [comment]
@Aminadav You will have to provide more context, as it is working fine here. Are you sure that account is in that group chat?
