### ISSUE TITLE
Decrypting Media on quotedMsgBody

### ISSUE THREAD

**Issue by edneijunior** [open-wa/wa-automate-nodejs#1253]
Does anyone know how to get the media in a replied message.
```javascript
   CLIENT.onMessage(message => {
    //CRECKING IF MESSAGE HAVE ANY MEDIA TYPE EMBED
     if (message['quotedMsgBody'].mimetype) {
          const mediaData = openWA.decryptMedia(message,uaOverride).then(function(DECRYPTED_DATA){
        var filename = `${message.t}.${mime.extension(message['quotedMsgBody'].mimetype)}`;
        fs.writeFile('/var/www/ejj/public/cdn/'+filename, Buffer.from(DECRYPTED_DATA, 'base64'), 'base64',function(err) {
          if(err){
            console.log("#Error on saving file");
            message['body'] = `data:${message['quotedMsgBody'].mimetype};base64,${message['quotedMsgBody']['body']}`;
            that.PROCESS_MESSAGE(message);
          } else {
            message['body'] = `data:${message['quotedMsgBody'].mimetype};base64,${base64Encode('/var/www/ejj/public/cdn/'+filename)}`;
            message['filelink'] = '/var/www/ejj/public/cdn/'+filename;
            that.PROCESS_MESSAGE(message);
          }
        });
      });
    } else {
      that.PROCESS_MESSAGE(message);
    }
  });
```

Forgiveness for the translator and for not knowing to follow the stardards. I1m a library contributor and would like help.

**Comment by smashah** [comment]
Hello @edneijunior I got your email also, but we'll continue this here.

When you say it's not working, what do you mean? Does it throw an error? Is the file empty? Whay file are you expecting? Etc.

Also, please, next time use the issue template

**Comment by edneijunior** [comment]
The truth is, I don't know how to do that. I wonder if there is any Doc or tutorial. Sorry for not using the template.
I will wait for the consultation by email. Thanks so much

**Comment by smashah** [comment]
@edneijunior 


```javascript

   CLIENT.onMessage(message => {
     if (message.quotedMsgObj && m.quotedMsgObj.mimetype) {
        let m = message.quotedMsgObj;
          const mediaData = openWA.decryptMedia(message,uaOverride).then(function(DECRYPTED_DATA){
        var filename = `${message.t}.${mime.extension(m.mimetype)}`;
        fs.writeFile('/var/www/ejj/public/cdn/'+filename, Buffer.from(DECRYPTED_DATA, 'base64'), 'base64',function(err) {
          if(err){
            console.log("#Error on saving file");
            message['body'] = `data:${m.mimetype};base64,${m['body']}`;
            that.PROCESS_MESSAGE(message);
          } else {
            message['body'] = `data:${m.mimetype};base64,${base64Encode('/var/www/ejj/public/cdn/'+filename)}`;
            message['filelink'] = '/var/www/ejj/public/cdn/'+filename;
            that.PROCESS_MESSAGE(message);
          }
        });
      });
    } else {
      that.PROCESS_MESSAGE(message);
    }
  });
```

**Comment by edneijunior** [comment]
i will try, thank you.

**Comment by edneijunior** [comment]
CLIENT.onMessage(message => {
     if (message.quotedMsgObj && m.quotedMsgObj.mimetype) {
        let m = message.quotedMsgObj;
          //const mediaData = openWA.decryptMedia(message,uaOverride).then(function(DECRYPTED_DATA){
        const mediaData = openWA.decryptMedia(m,uaOverride).then(function(DECRYPTED_DATA){
        var filename = `${message.t}.${mime.extension(m.mimetype)}`;
        fs.writeFile('/var/www/ejj/public/cdn/'+filename, Buffer.from(DECRYPTED_DATA, 'base64'), 'base64',function(err) {
          if(err){
            console.log("#Error on saving file");
            message['body'] = `data:${m.mimetype};base64,${m['body']}`;
            that.PROCESS_MESSAGE(message);
          } else {
            message['body'] = `data:${m.mimetype};base64,${base64Encode('/var/www/ejj/public/cdn/'+filename)}`;
            message['filelink'] = '/var/www/ejj/public/cdn/'+filename;
            that.PROCESS_MESSAGE(message);
          }
        });
      });
    } else {
      that.PROCESS_MESSAGE(message);
    }
  });


This worked, thank you very much my friend.
I'll leave it here in case anyone else has this doubt.

**Comment by smashah** [comment]
Great!
