### ISSUE TITLE
Chat - profilePicThumbObj empty since 3.1.13

### ISSUE THREAD

**Issue by Victorsouza02** [open-wa/wa-automate-nodejs#1258]
I'm trying to get the group photo with "chat.contact.profilePicThumbObj.eurl" to display it with the description, but since version 3.1.13 it's returning me undefined/empty.
![image](https://user-images.githubusercontent.com/4674786/105102958-7f263b80-5a8e-11eb-9b29-d7d8abf4cbb9.png)

**Comment by smashah** [comment]
@Victorsouza02 restart your sessions and try again. If it keeps happening then use:

https://docs.openwa.dev/classes/client.html#getprofilepicfromserver
