### ISSUE TITLE
it does not work decryptMedia and getStickerDecryptable

### ISSUE THREAD

**Issue by maurihn** [open-wa/wa-automate-nodejs#1268]
When receiving a sticker it cannot be decrypted, it shows "false" as a result

**Comment by smashah** [comment]
@maurihn if you've got a valid license key and it is still returning `false` then it is either because the message cannot be found or it is not a sticker. Either way, this problem requires a lot more context.

**Comment by maurihn** [comment]
If I have a key, and before it worked super well with decryptMedia, but now I don't know why it doesn't work, I'm doing the following.
const mediaDecry = await client.decryptMedia (messages);

**Comment by smashah** [comment]
@maurihn 

`getStickerDecryptable` returns a sticker message that can be decrypted. It requires the message id as the first and only parameter. After you get the return of `getStickerDecryptable` you send that message to `decryptMedia`. Please check the example below.

```javascript
	client.onMessage(async message = > {
      let mediaData;
      if( message.type==='sticker') {
        //getStickerDecryptable is an insiders feature! 
        let stickerDecryptable = await client.getStickerDecryptable(message.id);
        if(stickerDecryptable) mediaData = await decryptMedia(stickerDecryptable);
      } else {
        mediaData = await decryptMedia(message, uaOverride);
      }
		...
	});	
```

**Comment by maurihn** [comment]
I have received a sticker and it always returns a **false**, actually the message does contain the sticker, but it always returns a **false**

**Comment by smashah** [comment]
@maurihn I think this only affects `OW` keys. I have issued a fix, can you try again, please. Thanks

**Comment by maurihn** [comment]
Thank you @smashah , I already tried and everything is fine.
