### ISSUE TITLE
Expected type of "sticker-server-endpoint" to be one of ["string", "boolean", "number", "array", "string-array", "boolean-array", "number-array"], got ["string", "boolean"]

### ISSUE THREAD

**Issue by Skowt** [open-wa/wa-automate-nodejs#1274]
**Describe the bug**
Unable to get session data due to an error with dependencies.

**Steps to Reproduce**
1. Run: `npx @open-wa/wa-automate -o`

**create() code**
This is the code you use to create the client. e.g
```javascript
npx @open-wa/wa-automate -o
```

**Expected behavior**
No bug.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
npx @open-wa/wa-automate -o
(node:63959) ExperimentalWarning: The fs.promises API is experimental
Downloading Chromium r818858 - 132.4 Mb [====================] 100% 0.0s
info sharp Using cached /Users/skowt/.npm/_libvips/libvips-8.10.5-darwin-x64.tar.gz
Expected type of "sticker-server-endpoint" to be one of ["string", "boolean", "number", "array", "string-array", "boolean-array", "number-array"], got ["string", "boolean"]
(node:63923) ExperimentalWarning: The fs.promises API is experimental
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4960236/105898259-e3fb0c00-6021-11eb-95e7-b2f53390ab0f.png)

**Host (please complete the following information):**
 - OS: macOS Big Sur

**Additional context**
Just trying to get the session data to run the API on Heroku.

**Comment by smashah** [comment]
@Skowt thanks for bringing this up.

For now please use this

```
npx @open-wa/wa-automate@3.1.16 -o
```

**Comment by Skowt** [comment]
Thanks! Working 💪🏼

**Comment by laruche** [comment]
Too bad ! Tee API sounds amazing !! Impatient to test it !

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.2.1](https://github.com/open-wa/wa-automate-nodejs/compare/3.2.0...3.2.1) (2021-01-31)

- build(deps-dev): bump typedoc from 0.19.2 to 0.20.19 [`#1272`](https://github.com/open-wa/wa-automate-nodejs/pull/1272)
- build(deps): bump puppeteer-extra-plugin-stealth from 2.6.6 to 2.6.7 [`#1273`](https://github.com/open-wa/wa-automate-nodejs/pull/1273)
- build(deps-dev): bump marked from 1.2.7 to 1.2.8 [`#1275`](https://github.com/open-wa/wa-automate-nodejs/pull/1275)
- build(deps): bump sharp from 0.27.0 to 0.27.1 [`#1277`](https://github.com/open-wa/wa-automate-nodejs/pull/1277)
- build(deps): bump swagger-ui-dist from 3.40.0 to 3.41.1 [`#1279`](https://github.com/open-wa/wa-automate-nodejs/pull/1279)
- Release 3.2.1 [`4adc3e5`](https://github.com/open-wa/wa-automate-nodejs/commit/4adc3e577ec878efb189d6b231bf7a927c49402d)
- package lock fix [`f8e6da9`](https://github.com/open-wa/wa-automate-nodejs/commit/f8e6da93ed7e051ee093f531ff2cd0de964bbaa1)
- Feature: Now able to set viewport in CLI [`f3d254a`](https://github.com/open-wa/wa-automate-nodejs/commit/f3d254a58aa1e58d36234ef6f61aa83166729a83)
- Improved sticker documentation [`64c303c`](https://github.com/open-wa/wa-automate-nodejs/commit/64c303c7abaf1d4a7632febbdc89cb69d5d5534a)
- Feature: [Config] Implemented `resizable` to make headful browser resizable. CLI: `--resizable` [`9429c55`](https://github.com/open-wa/wa-automate-nodejs/commit/9429c559c9da30f89dc6052d2d47635627236fef)
- revert typedoc [`9fa5e30`](https://github.com/open-wa/wa-automate-nodejs/commit/9fa5e3037728e90e4233cc0fbe0cb988f41b0b22)
- fix: #1274 [`df5b5d1`](https://github.com/open-wa/wa-automate-nodejs/commit/df5b5d1f4420fb10c808d59ba6f7e3c168470963)

**Comment by smashah** [comment]
@laruche @Skowt this should be fixed now. thanks

**Comment by laruche** [comment]
Works like a charm :)
