### ISSUE TITLE
How can I send a list of contacts without separating them?

### ISSUE THREAD

**Issue by DaviZMelo** [open-wa/wa-automate-nodejs#1276]
when i use client.sendContact and pass an array of contacts, instead of being sent a list with several contacts, separate contacts are sent

what happens

![image](https://user-images.githubusercontent.com/49699162/106067438-6dbbdf80-60dd-11eb-9d5d-087e6081401f.png)

what i want

![image](https://user-images.githubusercontent.com/49699162/106067493-8926ea80-60dd-11eb-8d42-c6db8c45f2b7.png)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.2.3](https://github.com/open-wa/wa-automate-nodejs/compare/3.2.2...3.2.3) (2021-02-01)

- Release 3.2.3 [`5c6a7fd`](https://github.com/open-wa/wa-automate-nodejs/commit/5c6a7fdbcae0c1b20647a5610550fdd4fe221033)
- feat: (Insiders) `sendMultipleContacts` in a single message #1276 [`11f8bfb`](https://github.com/open-wa/wa-automate-nodejs/commit/11f8bfb1952f94efae6382d1dd645514f65aa2a3)

**Comment by smashah** [comment]
@DaviZMelo please dm or email me for instructions on how to get your insiders key. Thanks
