### ISSUE TITLE
Mute chat notifications

### ISSUE THREAD

**Issue by VideFrelan** [open-wa/wa-automate-nodejs#1281]
Is it possible to add features that can mute chat notifications, including group chats?
I thought it would be great if we didn't have to manually mute chat notifications

**Comment by AlvioAdjiJanuar** [comment]
ada yang bisa saya bantuu ?

> Is it possible to add features that can mute chat notifications, including group chats?
> I thought it would be great if we didn't have to manually mute chat notifications

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.2.2](https://github.com/open-wa/wa-automate-nodejs/compare/3.2.1...3.2.2) (2021-02-01)

- Release 3.2.2 [`0b8210a`](https://github.com/open-wa/wa-automate-nodejs/commit/0b8210a626709725df8104a3d4e9712056a158a0)
- Improved type aliases [`4a20176`](https://github.com/open-wa/wa-automate-nodejs/commit/4a20176ab99e270986b29cab1edc8b22fddd961a)
- feat: (Insiders) `muteChat` & `unmuteChat` #1281 [`f8eaf18`](https://github.com/open-wa/wa-automate-nodejs/commit/f8eaf182274cefae58ec1f27cec5bb076ece8a4e)
- upgrade to typescript beta for literal types [`8945c22`](https://github.com/open-wa/wa-automate-nodejs/commit/8945c226c159a94fe678e8a4e802d7a39dd2ecb6)
- fix bad sticker URL #1282 [`38614c4`](https://github.com/open-wa/wa-automate-nodejs/commit/38614c48d9ed63629b5721752003260bc538c046)

**Comment by smashah** [comment]
@VideFrelan please DM me on discord or email me for your insiders key. thanks

**Comment by VideFrelan** [comment]
Hello Mohammed Shah, i'm VideFrelan, what do you mean "please DM me on
discord or email me for your insiders key. thanks"

This is my email, what can I get?

Thank you.

Pada tanggal Sen, 1 Feb 2021 pukul 13.29 Mohammed Shah <
notifications@github.com> menulis:
