### ISSUE TITLE
sticker nobg

### ISSUE THREAD

**Issue by Jonas33235** [open-wa/wa-automate-nodejs#1292]
how to send sticker no background whitout no api?

**Comment by lxndr-rl** [comment]
this is not a issue

**Comment by smashah** [comment]
@Jonas33235 You'll need to provide a raw webp file with a transparent background then use https://docs.openwa.dev/classes/client.html#sendrawwebpassticker

**Comment by smashah** [comment]
@Jonas33235 in the stickerMetadata parameter, set `removebg: true`

docs.openwa.dev/globals.html#stickermetadata

Just fyi, this requires a **paid** license key
