### ISSUE TITLE
getAllChatIds and getAllChats only return a few entries

### ISSUE THREAD

**Issue by SSchaaf** [open-wa/wa-automate-nodejs#1299]
**Describe the bug**
Working with a whatsapp that has about 1,5 mil chats getAllChatIds and getAllChats only return a few entries. getAllChatsIds is returning 37 entries.

**Steps to Reproduce**
1. Run : npx @open-wa/wa-automate

**create() code**
This is the code you use to create the client. e.g
```npx @open-wa/wa-automate```

**Expected behavior**
Return all entries from whatsapp

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2102.9',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.2.5',
  BROWSER_VERSION: 'HeadlessChrome/88.0.4298.0'
}
```

**Host (please complete the following information):**
 - OS: Windows 10

**Comment by smashah** [comment]
@SSchaaf these methods return whatever is in memory, and it seems as though it's for the best as returning an array of 1.5million(!?!?!?!?!??!) chat ids will probably crash your server and your device. I'll look into it though but don't say I didn't warn you

**Comment by SSchaaf** [comment]
Sorry @smashah ! 1,5 thousand chats.

I understand wat you mean. It is the same problem when we need to get all messages form a chat. I am using loadEarlierMessages and faced that is best aproach. Reanding 50 step by step  messages untuil the end.

But ..... How can I do the same with chats ?

My code is working with getAllChatIds. Once I have the array of Ids I sart reading the chats one by one. Works like a charm. I think that something changed in WA and now we don't have all Ids with  one step. Only scrolling the app but it is not what we want :) !

My code is changing frequently. And I use a account with few chats. Now I am testing again with a larger one. I am not 100% sure but I susppect that I have runed this code ( with getAllChatIds ) with 1,5 thousand chats and worked fine.

**Comment by smashah** [comment]
@SSchaaf ah ok 1.5k doesn't sound too bad. The only way for this issue to be resolved is if you DM me on discord so I can fix this using your session as I don't have access to any accounts with this many chats.

**Comment by SSchaaf** [comment]
Ok, we can see about discord later. I am not a discord user.
In this meantime I tried with my WA account ( about 215 chats ). 
No problem. I got all chatIds.

Give me a time to do another test wiht de account that has 1,5 thousand.

**Comment by SSchaaf** [comment]
Hi @smashah

Sorry about this issue. The account that we are testing had a problem. Lost the contacts. 
I tried with another acoount ( about 1,7 thousands chats ) and worked perfectly.

Sorry again by my fault.

Maybe better delete this issue.  I don't know it it is posible. 
Just not to pollute the issues knowledge base.

Your project is awsone. Congrats.

**Comment by smashah** [comment]
Thanks for the kind words. I'll keep the issue as is for reference. Thanks
