### ISSUE TITLE
Feature: resize image while preserving scale

### ISSUE THREAD

**Issue by Mikael-R** [open-wa/wa-automate-nodejs#1309]
**Describe**
The image was resized to the resolution of the stickers, but it loses its scale, let's say it has a height greater than the width, it is simply cut off

**Comment by smashah** [comment]
@Mikael-R can you be more specific with some examples and code please.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.3.1](https://github.com/open-wa/wa-automate-nodejs/compare/3.3.0...3.3.1) (2021-02-05)

- build(deps): bump swagger-ui-dist from 3.41.1 to 3.42.0 [`#1314`](https://github.com/open-wa/wa-automate-nodejs/pull/1314)
- build(deps-dev): bump @types/line-reader from 0.0.32 to 0.0.33 [`#1315`](https://github.com/open-wa/wa-automate-nodejs/pull/1315)
- build(deps-dev): bump @types/node from 14.14.24 to 14.14.25 [`#1317`](https://github.com/open-wa/wa-automate-nodejs/pull/1317)
- Release 3.3.1 [`64aefde`](https://github.com/open-wa/wa-automate-nodejs/commit/64aefde276b424e39e71d8f5bb20622773b599c6)
- added `removebg` and `keepScale` in stickermetadata #1292 #1309 [`c621f02`](https://github.com/open-wa/wa-automate-nodejs/commit/c621f02513f6abc02701fc26aa632a244e58d99c)
- added `ChatMuteDuration` documentation [`215cdba`](https://github.com/open-wa/wa-automate-nodejs/commit/215cdbae1ac768a028f301b84faf4d9257aeba95)
- patch: #1263 [`a08266d`](https://github.com/open-wa/wa-automate-nodejs/commit/a08266d8c1e183f2c2a3450fcd4ebda27aca6983)

**Comment by Urbaeexyz** [comment]
![image](https://user-images.githubusercontent.com/75126993/107110664-5cf92f80-687c-11eb-934c-6c108e972683.png)

function ```sendImageAsSticker``` that image from result base 64 in rest api has error
request failed with status code

**Comment by smashah** [comment]
@Urbaeexyz please open a new issue and show your code. These screenshots are useless to fix your issue.

**Comment by smashah** [comment]
@Mikael-R in stickerMetadata, set `keepScale: true`

https://docs.openwa.dev/globals.html#stickermetadata
