### ISSUE TITLE
Bug and error

### ISSUE THREAD

**Issue by Urbaeexyz** [open-wa/wa-automate-nodejs#1313]
![image](https://user-images.githubusercontent.com/75126993/106971353-589c1c00-6781-11eb-8249-8c8e7c8a96fa.png)

sticker in version 3.2.0 or newer has error and the new version 3.3.0 have bug command not working
it is bug?

**Comment by smashah** [comment]
500 errors are usually due to memory issues on the sticker server. I've fixed some memory leaks so it should be a bit better now.
