### ISSUE TITLE
Questions about onMessageDeleted

### ISSUE THREAD

**Issue by VideFrelan** [open-wa/wa-automate-nodejs#1318]
Hello smashah! Thanks for your hardworks to make a such amazing library.
I have a several questions about ```onMessageDeleted```. I noticed that type and isMedia properties is returned as undefined instead of the type of the message and boolean (for isMedia), is it normal? If it is, then this issue will most likely a feature request. It would be nice if we can use those property because I have a feature that the bot I made returning a message that has been deleted by users. So I need to seperate them whether the message is an image, text, video, or any others media. Thanks in advance.

**Comment by smashah** [comment]
@VideFrelan you can detect media by checking the `mimetype` property

```javascript
  client.onMessageDeleted(message=>{
    if(message.mimetype) {
      //it is media
    }
  });
```
