### ISSUE TITLE
Middleware Error in PostMan

### ISSUE THREAD

**Issue by sakthimj** [open-wa/wa-automate-nodejs#1319]
When i try to post api using Postman Error has been received,

"{"success":false,"error":{}}" 
![image](https://user-images.githubusercontent.com/18246843/107112170-84033180-687b-11eb-9822-27e4e743c688.png)

**Comment by smashah** [comment]
You're not meant to copy paste the node code into the request body.

Please see the middleware documentation it will show you how the request body should look. Also, on the future please use the issue template

**Comment by smashah** [comment]
Please use the CLI, it literally outputs a postman collection JSON file with API explorer by default

https://docs.openwa.dev/pages/Getting%20Started/quick-run.html
