### ISSUE TITLE
remove bg

### ISSUE THREAD

**Issue by Urbaeexyz** [open-wa/wa-automate-nodejs#1320]
sticker metadata of remove bg not work

**Comment by Urbaeexyz** [comment]
![image](https://user-images.githubusercontent.com/75126993/107118550-4a9ae800-68b4-11eb-8971-3c4e4843be56.png)

**Comment by Urbaeexyz** [comment]
![image](https://user-images.githubusercontent.com/75126993/107118576-6605f300-68b4-11eb-8902-a9e4a2f4ad23.png)

**Comment by smashah** [comment]
Why are you setting `id` as the fourth parameter?

There are only three parameters on that method. Remove the `id` at the end.

https://docs.openwa.dev/classes/client.html#sendimageassticker

**Comment by smashah** [comment]
Also, please use the issue template.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️

**Comment by Urbaeexyz** [comment]
it's same, the background not changes

**Comment by Urbaeexyz** [comment]
i have deleted id but it's still same
at 2 pm it's still work, but idk now it's not work

**Comment by smashah** [comment]
@Urbaeexyz also, `removebg` will not work forever just FYI due to API limits.
