### ISSUE TITLE
State Changed:Conflict

### ISSUE THREAD

**Issue by NitinNR** [open-wa/wa-automate-nodejs#1321]
**Describe the bug**

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

we have self host the whatsapp api and after 5 to 6 conversation the api stop working with state change conflict

**Comment by smashah** [comment]
@NitinNR there's no point using the template if you're not going to fill it in. `CONFLICT` state refers to when a host account click "use here" somewhere else (maybe on their own WhatsApp web instance on their laptop).

Please see:

https://docs.openwa.dev/pages/How%20to/detect-logout.html

**Comment by NitinNR** [comment]
"there's no point using the template if you're not going to fill it in" can
you explain the quoted statement in detail.
