### ISSUE TITLE
whatsapp-web freezes after being idle

### ISSUE THREAD

**Issue by Schwartzblat** [open-wa/wa-automate-nodejs#1322]
**Describe the bug**

When WhatsApp Web is inactive or it does not receive messages for a few minutes, it freezes and does not update. If I do not use headless I can see that on the phone I get messages and on WhatsApp Web no.

**Steps to Reproduce**
1. Just being idle or not getting any messages for few minutes.

**create() code**
This is the code you use to create the client. e.g
```javascript
create({
    useChrome: false,
    autoRefresh: true,
    headless: true})...
```

**Expected behavior**
I want whatsappWeb will not freeze or when it freezes it will refresh.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2102.9,
  PAGE_UA: WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36,
  WA_AUTOMATE_VERSION: 3.3.1,
  BROWSER_VERSION: HeadlessChrome/90.0.4403.0
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Windows 10 Pro (updated to the last version)

**Additional context**

**Comment by smashah** [comment]
@Schwartzblat best course of actions is to make sure there is no battery optimization happening on the phone and keep the app open with the screen on.

**Comment by Schwartzblat** [comment]
> @Schwartzblat best course of actions is to make sure there is no battery optimization happening on the phone and keep the app open with the screen on.

Is there any other way? I have no batttery saver and I don't want to keep my phone like that.

**Comment by smashah** [comment]
You don't have to do all three depending on your device. Try each solution and see if it works for you. Also, best solution is to get another phone and leave it an optimal state.

Speaking of state, keep an eye on it using [`onStateChanged`](https://docs.openwa.dev/classes/client.html#onstatechanged) or try [forceUpdateConnectionState](https://docs.openwa.dev/classes/client.html#forceupdateconnectionstate) once in a while.

There are many reasons why what's happening to you is happening. A lot of it is not in the control of the library, unfortunately.

**Comment by Schwartzblat** [comment]
Ok, I will try it. thanks you!

**Comment by Urbaeexyz** [comment]
> You don't have to do all three depending on your device. Try each solution and see if it works for you. Also, best solution is to get another phone and leave it an optimal state.
> 
> Speaking of state, keep an eye on it using [`onStateChanged`](https://docs.openwa.dev/classes/client.html#onstatechanged) or try [`forceUpdateConnectionState`](https://docs.openwa.dev/classes/client.html#forceupdateconnectionstate) once in a while.
> 
> There are many reasons why what's happening to you is happening. A lot of it is not in the control of the library, unfortunately.

how to send sticker as reply?

i have try function ```sendImageAsStickerAsReply``` but the sticker it's not sending

```
aruga.sendImageAsStickerAsReply(from, imageBase64, {keepScale: true})

**Comment by smashah** [comment]
@Urbaeexyz [`sendImageAsStickerAsReply `](https://docs.openwa.dev/classes/client.html#sendimageasstickerasreply) is an Insider's feature.

@Schwartzblat closing for now. If there are any updates, please add it here and I will reopen. thanks
