### ISSUE TITLE
clientUrl = null

### ISSUE THREAD

**Issue by IanosJunior** [open-wa/wa-automate-nodejs#1329]
the clientUrl property of the messages is gone.

**Comment by smashah** [comment]
@IanosJunior this was fixed with the latest patch. Please restart your sessions and try again

**Comment by smashah** [comment]
report back if this is still happening. closing for now thanks

**Comment by IanosJunior** [comment]
can you give me the  fix ID ou link?

**Comment by smashah** [comment]
@IanosJunior there is no fix I'd. You just need to restart your session.
