### ISSUE TITLE
sendSeen() not working

### ISSUE THREAD

**Issue by WaxArsatia** [open-wa/wa-automate-nodejs#1340]
**Describe the bug**
when im execute `client.seenSeen(message.id)` nothing is happen and not send read to target message.id

**Steps to Reproduce**
Nothing error on console but you can reproduce by just run `client.sendSeen(message.id)`

**create() code**
This is the code you use to create the client. e.g
```javascript
const start = async (client = new Client()) => {

	client.onMessage((message) => {
                client.seenSend(message.id);
		msgHandler(client, message);
	});

};
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2104.9,
  PAGE_UA: WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36,
  WA_AUTOMATE_VERSION: 3.4.0,
  BROWSER_VERSION: HeadlessChrome/88.0.4324.150
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Android

**Additional context**

**Comment by smashah** [comment]
Not able to recreate this issue @WaxArsatia . Is it still happening? Got any other ideas as to how I can replicate this?

**Comment by WaxArsatia** [comment]
My bad, it should `client.sendSeen(message.chatId)` but im type `client.sendSeen(message.id)`
