### ISSUE TITLE
Cannot find module 'sharp'

### ISSUE THREAD

**Issue by Skowt** [open-wa/wa-automate-nodejs#1348]
**Describe the bug**
Unable to get session dump when using the latest release. 

**Steps to Reproduce**
1. Run  npx @open-wa/wa-automate -o`

**create() code**
This is the code you use to create the client. e.g
N/A

**Expected behavior**
No error.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
N/A

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: MacOS

**Additional context**
Running an older version works without an issue:

```
> npx @open-wa/wa-automate -o
(node:13350) ExperimentalWarning: The fs.promises API is experimental
Downloading Chromium r848005 - 110.5 Mb [====================] 100% 0.0s
Cannot find module 'sharp'

>npx @open-wa/wa-automate@3.1.16 -o
(node:14549) ExperimentalWarning: The fs.promises API is experimental
Downloading Chromium r818858 - 132.4 Mb [====================] 100% 0.0s
info sharp Using cached /Users/danielpietersen/.npm/_libvips/libvips-8.10.5-darwin-x64.tar.gz
(node:14456) ExperimentalWarning: The fs.promises API is experimental
fresh run
...
```

**Comment by smashah** [comment]
@Skowt This will be fixed in an upcoming version but for now run this before using the CLI:

```bash
> npm i -g sharp fluent-ffmpeg
```

**Comment by smashah** [comment]
This should no longer happen if you do not use local sticker processing on the latest version (3.5.0)
