### ISSUE TITLE
How 

### ISSUE THREAD

**Issue by MFarelS** [open-wa/wa-automate-nodejs#1355]
How To Custom Thumbnail Link Preview

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.5.1](https://github.com/open-wa/wa-automate-nodejs/compare/3.5.0...3.5.1) (2021-02-18)

- build(deps): bump puppeteer-extra-plugin-stealth from 2.7.4 to 2.7.5 [`#1356`](https://github.com/open-wa/wa-automate-nodejs/pull/1356)
- build(deps): bump puppeteer-extra-plugin-devtools from 2.2.15 to 2.2.16 [`#1357`](https://github.com/open-wa/wa-automate-nodejs/pull/1357)
- build(deps): bump puppeteer-extra from 3.1.16 to 3.1.17 [`#1358`](https://github.com/open-wa/wa-automate-nodejs/pull/1358)
- build(deps): bump open from 7.4.1 to 7.4.2 [`#1360`](https://github.com/open-wa/wa-automate-nodejs/pull/1360)
- build(deps): bump ts-json-schema-generator from 0.84.0 to 0.86.1 [`#1368`](https://github.com/open-wa/wa-automate-nodejs/pull/1368)
- Release 3.5.1 [`3067075`](https://github.com/open-wa/wa-automate-nodejs/commit/3067075fc516fe0ba27567c3e04c77f2bf1f1a2e)
- improved message and chat typings [`70abe09`](https://github.com/open-wa/wa-automate-nodejs/commit/70abe098e1f6092b420dec665562f48c8f2290b6)
- feature: `sendLinkWithAutoPreview` now accepts custom thumbnail #1355 [`81a719f`](https://github.com/open-wa/wa-automate-nodejs/commit/81a719fb3c5a78047bf3ed05c237f34684b217e6)
- fix: untrimmed messages no longer result in stuck promises [`1a25bb7`](https://github.com/open-wa/wa-automate-nodejs/commit/1a25bb70d814fc6341cc909933f3aabe6ad3d81d)
- fix: wapi module typo fixed [`22be7c5`](https://github.com/open-wa/wa-automate-nodejs/commit/22be7c543281ffb54ec3e39e727c5550b6de81a6)

**Comment by smashah** [comment]
@MFarelS 

[`sendLinkWithAutoPreview`](https://docs.openwa.dev/classes/client.html#sendlinkwithautopreview) now can take a fourth optional parameter where you should submit the base64 (not data URL) of the thumbnail you want to use.

**Comment by MFarelS** [comment]
> @MFarelS
> 
> [`sendLinkWithAutoPreview`](https://docs.openwa.dev/classes/client.html#sendlinkwithautopreview) now can take a fourth optional parameter where you should submit the base64 (not data URL) of the thumbnail you want to use.

THX 🙏
