### ISSUE TITLE
Proper Error Handling On SendText()

### ISSUE THREAD

**Issue by Sp0derDev** [open-wa/wa-automate-nodejs#1359]
Upon sending a message to a number that is not on WhatsApp, the method sendText() doesn't throw an error. Instead, it simply logs 'Error: Number not linked to WhatsApp Account' 

It would be better if it threw an error instead of just logging it to the console.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.6.3](https://github.com/open-wa/wa-automate-nodejs/compare/3.6.2...3.6.3) (2021-02-21)

- 📝 added improved error handling to documentation [`e42bf07`](https://github.com/open-wa/wa-automate-nodejs/commit/e42bf07a43321c594140f3473ee87734e0fd01d5)
- Release 3.6.3 [`9646673`](https://github.com/open-wa/wa-automate-nodejs/commit/9646673dd8c2cb0b24992672e4bf39b8fc521a05)
- 💥 : `sendText` now throws error when unable to send a text #1359 [`f300e44`](https://github.com/open-wa/wa-automate-nodejs/commit/f300e445a9c456acbd143c5cf0695f15ef28c534)

**Comment by smashah** [comment]
@Sp0derDev it should now throw the error with a corresponding [error name](https://docs.openwa.dev/enums/error_name.html)

```javascript
try {
    await client.sendText(wrong_number, 'Hello')
} catch (error) {
    switch (error.name) {
        case ERROR_NAME.SENDTEXT_FAILURE:
        	//this has to be checked separately because the message is different for every number
            if (error.message.includes('Not a contact')) {

            } else {
                switch (error.message) {
                    case 'Error: Number not linked to WhatsApp Account':
                        ...
                        break;
                    case 'ERROR: Please make sure you have at least one chat':
						...
						break;

                }
            }
            break;
        default:
            // code block
    }
}
```
