### ISSUE TITLE
Decrypt function doesn't work on quoted videos/gifs

### ISSUE THREAD

**Issue by Sp0derDev** [open-wa/wa-automate-nodejs#1361]
**Describe the bug**
Upon receiving the quoted video/gif, the decrypt function fails to decrypt and throws this error:  message is missing critical data needed to download the file.

**create() code**
This is the code you use to create the client. e.g
```javascript
await wa.create({
            sessionId: "InstagramBot",
            authTimeout: 60,
            blockCrashLogs: true,
            disableSpins: true,
            headless: true,
            hostNotificationLang: 'PT_BR',
            logConsole: false,
            popup: true,
            qrTimeout: 0,
            useChrome: true,
            callTimeout: 70 * 1000,
            licenseKey: 'xxxxxxxxxx'
        })
```

**Expected behavior**
It should behave the same as when quoting ( replying ) to an image. 

Edit: 

┌─────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                    Values                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2104.10'                                                                  │
│       PAGE_UA       │ 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '3.5.0'                                                                    │
│   BROWSER_VERSION   │                                                        'HeadlessChrome/88.0.4324.182'                                                        │
│         OS          │                                                               'macOS Big Sur'                                                                │
│      START_TS       │                                                                1613647313626                                                                 │
└─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by smashah** [comment]
@Sp0derDev you haven't filled in the template entirely. What version of the library are you running?

Also, run this and try again:

```bash
> npm i @open-wa/wa-decrypt@latest
```

**Comment by Sp0derDev** [comment]
I am running the latest version of both the library and @open-wa/wa-decrypt

This is the deprecatedMms3Url:
https://mmg.whatsapp.net/d/f/AtTW85WXOGpTBs_q43YGu3sm1SruXLuquBgz_3NIhBqh.enc

**Comment by Sp0derDev** [comment]
I am running the latest version of both the library and @open-wa/wa-decrypt

This is the deprecatedMms3Url:
https://mmg.whatsapp.net/d/f/AtTW85WXOGpTBs_q43YGu3sm1SruXLuquBgz_3NIhBqh.enc

Edit:

And this is my code:

```nodejs
 const encryptMedia = isQuotedVideo ? quotedMsg : message
                            console.log(encryptMedia)
                            if (_mimetype === 'video/mp4' || _mimetype === 'image/gif') {

                                var mediaData = await decryptMedia(message, uaOverride)
```

It Logs This:

```json
{
  type: 'video',
  deprecatedMms3Url: 'https://mmg.whatsapp.net/d/f/AtTW85WXOGpTBs_q43YGu3sm1SruXLuquBgz_3NIhBqh.enc',
  directPath: '/v/t62.7161-24/35734477_338272470771439_6014232314182822151_n.enc?oh=ab909740d2324259895fc751a4fb05e5&oe=60562A64',
  mimetype: 'video/mp4',
  filehash: 'ZXMUJ4dTBoFrm/oEgvVs5qNQ9a6ohdGl4fnNbTB+nns=',
  encFilehash: 'PP0e4AcQb9C/JkTIbxR1zEeAz6A4ub1NDOi8UReeVnA=',
  size: 324045,
  height: 368,
  width: 368,
  duration: '4',
  mediaKey: 'XYNjVkud7JcTCoXNt+r8J+4rMbU263Na/+o7BXgLtvg=',
  mediaKeyTimestamp: 1613557301,
  caption: '!sticker',
  body: '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABsSFBcUERsXFhceHBsgKEIrKCUlKFE6PTBCYFVlZF9VXVtqeJmBanGQc1tdhbWGkJ6jq62rZ4C8ybqmx5moq6T/2wBDARweHigjKE4rK06kbl1upKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKT/wgARCABIAEgDASIAAhEBAxEB/8QAGgABAAMBAQEAAAAAAAAAAAAAAAECAwUEBv/EABcBAQEBAQAAAAAAAAAAAAAAAAABAgP/2gAMAwEAAhADEAAAAIzljEa5q9Hj9E1xtPfSKJHe4n0vJmueqxi18lvv35Ou70GLeutn59ee+DGmWOEoEkLZVX0mcc/XXyZGOIkia2tAtQGwk1FyACf/xAAdEQACAgEFAAAAAAAAAAAAAAAAARESAhAgITBR/9oACAECAQE/ALMuS2SSPnRMWXu6ev8A/8QAGhEBAAIDAQAAAAAAAAAAAAAAARARAAIgMP/aAAgBAwEBPwDnYkYTi8WvL//EACwQAAEDAgQEBQUBAAAAAAAAAAEAAhEDBBASITEFE0FhIjJCQ1FSU3GBoZH/2gAIAQEAAT8Afe3v3P8AFU4jevblcXAdkzil2z1EjuEzjVwPNTn9IcdqCc1JXvEqt43K5gAG3ZHODEKi+pSeHAwQq/E7qrTLHvJaVPdT3wDy3oE11J/mbB+UbbNqwgp9Bzd2I0j9P8XJcfT/ABXdpb8rOxgnsn6PIUqVJTKzmHRU7oO8yGVwkQnNPSFTcCIgQuK2fLfzWDwHfCVKmVMbKnXLSqdwDugQwbq9JqWb410w2whbYBxCZTfHicSqry4NpN3KuqZpXD2/BUqVKGLRLdE5oYS89FcP5tZzp3K/KhHRBynA1m0wQTEK+vs4NNmx6qeqKCgIhBSE+q951K0K2K5lA+2VzKI9tF9I+gjTDqjqv//+AAMA/9k=',
  streamingSidecar: {},
  interactiveAnnotations: [],
  isViewOnce: false
}
```

`Error: message is missing critical data needed to download the file.`

**Comment by Sp0derDev** [comment]
This only throws the error when the message is a reply.

**Comment by smashah** [comment]
@Sp0derDev based on your code you are trying to decrypt the main message, not the quotedMsg.

![image](https://user-images.githubusercontent.com/5903821/108351378-5902d100-71dd-11eb-8499-76af3ec1baef.png)


I think you mean to write:

```javascript
const encryptMedia = isQuotedVideo ? quotedMsg : message
	console.log(encryptMedia)
if (_mimetype === 'video/mp4' || _mimetype === 'image/gif') {	
var mediaData = await decryptMedia(encryptMedia, uaOverride)
	...
}

```


If for some reason,`encryptedMedia` is still not working then you can try this:


```javascript
const encryptMedia = isQuotedVideo ? quotedMsg : message
	console.log(encryptMedia)
if (_mimetype === 'video/mp4' || _mimetype === 'image/gif') {
	if(!encryptedMedia.clientUrl && encryptedMedia.deprecatedMms3Url) encryptedMedia.clientUrl = encryptedMedia.deprecatedMms3Url
	var mediaData = await decryptMedia(message, uaOverride)
	...
}

```

**Comment by Sp0derDev** [comment]
oh nooo, I feel so stupid.
Thank you sir. My apologies for wasting your time.
