### ISSUE TITLE
where all data get stored like images and files?

### ISSUE THREAD

**Issue by NitinNR** [open-wa/wa-automate-nodejs#1367]
It is possible to view the base64 string to view the image but not possible with file type  because it only provides the mime type in there body field(json format) so want to know where all these files get stored on api side(means on server)?

**Comment by smashah** [comment]
I'm sorry I do not understand what you mean.

**Comment by NitinNR** [comment]
> I'm sorry I do not understand what you mean.

i mean all media files like images and files which are received by api where all these data get stored?

**Comment by smashah** [comment]
@NitinNR no data is stored anywhere by the library. The files are saved on your device and temporarily uploaded to a wa server. The server link is used to download the encrypted file and then decrypted in `wa-decrypt`.

Closing.

Thanks
