### ISSUE TITLE
Proper Error Handling On sendMp4AsSticker & sendImageAsSticker

### ISSUE THREAD

**Issue by tcortega** [open-wa/wa-automate-nodejs#1370]
Whenever you try to process a sticker that the file size exceeds 1MB, it'll just warn you in the console and then give you an `Evaluation failed: n` exception.

It'd be nice if you could throw an `max sticker file size exceeded` exception instead of console logging the sticker size message, or at least something like that. That way we can handle it better.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.6.2](https://github.com/open-wa/wa-automate-nodejs/compare/3.6.1...3.6.2) (2021-02-21)

- 📝 docs update [`5cf1bce`](https://github.com/open-wa/wa-automate-nodejs/commit/5cf1bce0d390202d697c5609a14a8b8e808bff55)
- Release 3.6.2 [`3df1fa7`](https://github.com/open-wa/wa-automate-nodejs/commit/3df1fa731656aefc869bba77d422159639139783)
- 📝 `ChatMuteDuration` added to docs [`ac8b4d9`](https://github.com/open-wa/wa-automate-nodejs/commit/ac8b4d9506f895808d4ff5ee53944128240c9141)
- 🚸 Improved error handling #1370 [`fe89c84`](https://github.com/open-wa/wa-automate-nodejs/commit/fe89c8480b1635313633f73e265a333ad0fe78d4)
- ✨[Insider's] `hideTags` on mention messages [`8d2bafe`](https://github.com/open-wa/wa-automate-nodejs/commit/8d2bafedb2fc59fcada2f7e3a8e35b64948567b9)
- feat: [CLI] postman and swagger collections are now exposed at the `postman.json` and `swagger.json` paths [`2d9e27e`](https://github.com/open-wa/wa-automate-nodejs/commit/2d9e27e4cac564f2bab8cb25da9c6cffe4d47346)
- 💥: Sticker server issues now throw errors #1370 [`2e99fa9`](https://github.com/open-wa/wa-automate-nodejs/commit/2e99fa9d5c7fed3e04d0bddb17a5af351b9158eb)
- 🔧 [TS] remove trailing comma [`0c22773`](https://github.com/open-wa/wa-automate-nodejs/commit/0c2277313cbcbe83efa71f1ec39f38fa1d3f7388)
- 🐛 [CLI] `unexpected token .` issue fixed [`3dfcc90`](https://github.com/open-wa/wa-automate-nodejs/commit/3dfcc90219f9a4c47f8c14850d6ea3744ba3c77c)

**Comment by smashah** [comment]
@tcortega the library will now throw the 1mb error instead of just logging it.

**Comment by tcortega** [comment]
> @tcortega the library will now throw the 1mb error instead of just logging it.

its still just logging it.
