### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by MFarelS** [open-wa/wa-automate-nodejs#1379]
![Screenshot_2021-02-23-16-15-53-832_com microsoft rdc androidx](https://user-images.githubusercontent.com/58540890/108827669-775f3700-75f8-11eb-905b-0e0fb4a78be5.jpg)

**Comment by smashah** [comment]
Duplicate: #1378

Please stop spamming low effort issues.

If you read the error logs, this is a problem with your powershell set up. Please google:

`powershell is not recognized as an internal or external command operable program or batch file`

This error has nothing to do with this library.
