### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#1381]
Using -l or --license with EasyAPI doesn't load or generate any error for licensing. So I can't send messages to non contacts.

**Comment by smashah** [comment]
@silvaartur which version are you using?

And can you try with `--license-key`

**Comment by silvaartur** [comment]
Hi @smashah. 3.6.5. Works now... using --license-key.

**Comment by silvaartur** [comment]
@smashah, testing I got same error to non contacts:

{
  "success": false,
  "error": {
    "name": "SENDTEXT_FAILURE"
  }
}

**Comment by smashah** [comment]
@silvaartur I will investigate this tonight. In the mean time can you send me your license details pls either or discord or email.

Also, please share your launch logs

**Comment by silvaartur** [comment]
I will send by Discord.

**Comment by smashah** [comment]
@silvaartur is this still happening?

**Comment by smashah** [comment]
Closing for now. Please feel free to bump this issue if this is still happening.

Thanks
