### ISSUE TITLE
Add suport to utf-8 and emoji in stickerMetadata

### ISSUE THREAD

**Issue by Jonas33235** [open-wa/wa-automate-nodejs#1384]

**Comment by aymenitc** [comment]
Yes, please
when I enter sticker metadata in Arabic it returns empty sticker

**Comment by smashah** [comment]
@Jonas33235 @aymenitc can you show an example of a sticker that has Arabic/emojis in the metadata and it shows up properly in the mobile apps? I just investigated this and the metadata encoder successfully writes both Arabic and emojis into the sticker. I think WA itself removes these characters from sticker metadata. Happy to be proven wrong and continue investigating though.

**Comment by aymenitc** [comment]
![٢٠٢١٠٢٢٧_١٥٠٣٣٤](https://user-images.githubusercontent.com/76839622/109386645-18a60000-790d-11eb-8b5b-cca0ad8c75d3.jpg)
This is a sticker made by an app.. and the metadata is written in Arabic. I don't know about emojis.

But when trying to made Arabic metadata using The Bot it returns empty sticker
![٢٠٢١٠٢٢٧_١٥٠٨٣٢](https://user-images.githubusercontent.com/76839622/109386711-b13c8000-790d-11eb-9831-61f6f0a61e22.jpg)

**Comment by smashah** [comment]
thanks @aymenitc can you change your language settings to English in the app and see if the sticker in your first image still shows arabic. I just want to make sure all variables are equal

**Comment by aymenitc** [comment]
![٢٠٢١٠٢٢٧_١٥٤٣٥٧](https://user-images.githubusercontent.com/76839622/109387494-cff14580-7912-11eb-8772-446fc61c52b8.jpg)
I canged whatsapp language to english, and still shows Arabic

**Comment by smashah** [comment]
thanks @aymenitc I will work on this and report back. If you can, please come into the discord and DM me - I want you to send me that sticker in your screenshot

**Comment by aymenitc** [comment]
ok, Also, I hope you add metadata to sendStickerfromUrl function too
I appreciate all your efforts

**Comment by smashah** [comment]
@aymenitc this was implemented yesterday - https://github.com/open-wa/wa-automate-nodejs/issues/1409#issuecomment-786608093

**Comment by Jonas33235** [comment]
> obrigado @aymenitc eu vou trabalhar nisso e reportar de volta. Se puder, por favor, entre na discórdia e me DM- Eu quero que você me envie esse adesivo em sua captura de tela

=)

**Comment by smashah** [comment]
@Jonas33235 @aymenitc emojis and arabic should be working now. I have pushed an update to the sticker server. Please try again in about 4 minutes.

Thanks

**Comment by Jonas33235** [comment]
> @Jonas33235 @aymenitc emojis e árabe devem estar funcionando agora. Eu empurrei uma atualização para o servidor de adesivos. Por favor, tente novamente em cerca de 4 minutos.
> 
> Obrigado

can this update also use utf-8 encoded words?

**Comment by aymenitc** [comment]
> @Jonas33235 @aymenitc emojis and arabic should be working now. I have pushed an update to the sticker server. Please try again in about 4 minutes.
> 
> Thanks
Thanks a lot. It works with Arabic and emojis 
jazak Allah khaeer

**Comment by smashah** [comment]
@Jonas33235 can you give me an example please
