### ISSUE TITLE
getChat returns undefined for existing chats

### ISSUE THREAD

**Issue by blackchineykh** [open-wa/wa-automate-nodejs#1385]
**Describe the bug**
When replying to a chat that had messaged my number a while back, even though the chat is still present, if its not a recent conversation then the getChat(chatId) method returns **undefined**. If I go to the WA web page and search for the number, and then try to send, it works. Is there a way to load the conversation from the history before trying to send in such cases?

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create({
    sessionId: sessionId,
    sessionDataPath: sessionDataPath,
    useChrome: false,
    restartOnCrash: start,
    headless: process.env.CHROME_HEADLESS === "true",
    throwErrorOnTosBlock: true,
    qrTimeout: 0, //set to 0 to wait forever for a qr scan
    authTimeout: 0, //set to 0 to wait forever for connection to phone
    killProcessOnBrowserClose: false, 
    autoRefresh: true,
    safeMode: false,
    disableSpins: false,
    qrRefreshS: 15,
    cacheEnabled: false,
    blockCrashLogs: true,
    useStealth: true,
  })
```

**Expected behavior**
I expect to be able to send message to the persons who have messaged me even though it may be a few weeks ago.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
WA_VERSION      │                                                                 '2.2104.10'
                              │
│       PAGE_UA       │ 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                       '3.1.12 UPDATE AVAILABLE: 3.6.5'
                              │
│   BROWSER_VERSION   │                                                             'Chrome/83.0.4103.0'
                              │
│         OS          │                                                                 'Windows 10'
}
```

**Screenshots**
N/A

**Host (please complete the following information):**
 - OS: see above

**Additional context**

**Comment by smashah** [comment]
@blackchineykh can you expand on "a while back"? Also, try to run with `headless:false` and see if the chat is not `undefined` when you scroll down to it. If that works then I'll be able to figure out how to fix this. Also, how many chats do you have in total?

**Comment by blackchineykh** [comment]
> @blackchineykh can you expand on "a while back"? Also, try to run with `headless:false` and see if the chat is not `undefined` when you scroll down to it. If that works then I'll be able to figure out how to fix this. Also, how many chats do you have in total?

A while back could be 3 weeks ago and I do get a lot of incoming chats started. I have in the order of maybe ~20k conversations. I am running with headless = false and when I scroll to the chat, then it does return successfully using the getChat function. What can I do to force this behavior so that the chat doesn't return as undefined?

**Comment by smashah** [comment]
Thanks for the additional context @blackchineykh 

How many chats does it load on startup?

**Comment by smashah** [comment]
@blackchineykh can you hop onto discord so I can remote into your machine to fix this please. I can't replicate this because I don't have an account with this many chats

**Comment by smashah** [comment]
@blackchineykh With some help from people in the community. I have identified that wa web actually loads at least 10k chat objects on launch. If there was some sort of caching limit, it would be well before that point so I have to assume something else is going wrong.

I have a few ideas how to fix this but cannot do it unless I get access to your session - for which I ask again for you to DM me in discord.

I'll close this issue for now.

Thanks and looking forward to hearing from you so we can resolve this issue.
