### ISSUE TITLE
Message: javascript error: webpackJsonp is not defined

### ISSUE THREAD

**Issue by erickmourasilva** [open-wa/wa-automate-nodejs#1386]
this error started to happen unexpectedly just now.

**Comment by andersonarsilva** [comment]
hello i had the same problem. I used the change below to solve the problem.

if (typeof webpackJsonp === 'function') {
    webpackJsonp([], {'parasite': (x, y, z) => getStore(z)}, ['parasite']);
} else {
    webpackJsonp.push([ ['parasite'], { parasite: function (o, e, t) { getStore(t); } }, [['parasite']] ]);
}

**Comment by erickmourasilva** [comment]
> hello i had the same problem. I used the change below to solve the problem.
> 
> if (typeof webpackJsonp === 'function') {
> webpackJsonp([], {'parasite': (x, y, z) => getStore(z)}, ['parasite']);
> } else {
> webpackJsonp.push([ ['parasite'], { parasite: function (o, e, t) { getStore(t); } }, [['parasite']] ]);
> }

no work, because webpackJsonp not exist anymore
