### ISSUE TITLE
error in scan Qr this  ReferenceError: getQrPng is not defined

### ISSUE THREAD

**Issue by IsanMaulana** [open-wa/wa-automate-nodejs#1387]
**Describe the bug**
This bug is where when you want to scan qr in the command prompt a text appears that says (node: 29088) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getQrPng is not defined

**Steps to Reproduce**

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2106.5
  PAGE_UA: WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
  WA_AUTOMATE_VERSION: 3.4.1 UPDATE AVAILABLE: 3.6.5
  BROWSER_VERSION: HeadlessChrome/88.0.4324.190
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/77374832/109092800-cec0ec80-7749-11eb-9f18-b3d82d8c8dd4.png)

**Host (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by cucabr** [comment]
apparently because of the new version of the web wa , 2.2106.5

**Comment by rvp98** [comment]
Same here, and also got TOS BLOCK on demo

**Comment by aymenitc** [comment]
me to on ubuntu

**Comment by jlsubia404** [comment]
I have the same issue on Mac OS Catalina.

**Comment by ariona** [comment]
@smashah This probably caused by the update of wa-web. the `webpackJsonp` object is no longer exists. there is only `webpackChunkBuild` object

**Comment by smashah** [comment]
#1391
