### ISSUE TITLE
error getQrPng is not defined when starting scan qr

### ISSUE THREAD

**Issue by ikkehman** [open-wa/wa-automate-nodejs#1388]
**Describe the bug**
my session suddenly expired. So i start scaning again and got error  
> UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getQrPng is not defined

when starting. 

**Steps to Reproduce**
1. Just start wa-automate-nodejs
2. You got thats error when Authenticate

**Expected behavior**
Its shows QR code

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2106.5'
  PAGE_UA: WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36,
  WA_AUTOMATE_VERSION: 3.6.5
  BROWSER_VERSION: HeadlessChrome/87.0.4280.66}
```

This full error:
`UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getQrPng is not defined
    at __puppeteer_evaluation_script__:1:1
    at ExecutionContext._evaluateInternal (/root/BocchiBot2/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:172:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Host (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by prayogigit** [comment]
WhatsApp has just released a major change to the WhatsApp Web application that changes the internal module system (possibly upgraded webpack to v5).

**Comment by allanmelo** [comment]
I'm dealing with this same problem now.

Env:
<img width="1174" alt="Captura de Tela 2021-02-25 às 03 01 09" src="https://user-images.githubusercontent.com/16151423/109110351-b800a280-7715-11eb-80e1-6032b1a1bf4f.png">

**Comment by smashah** [comment]
#1391
