### ISSUE TITLE
 MsgKey not defined

### ISSUE THREAD

**Issue by group2tts** [open-wa/wa-automate-nodejs#1389]
`{ id: "MsgKey", conditions: (module) => (module.default&&module.default.toString().includes('MsgKey error: obj is null/undefined')) ? module.default : null },`

error: 

`Uncaught TypeError: module.default.toString is not a function`

**Comment by group2tts** [comment]
#1390

**Comment by cantiir2** [comment]
excusme sir . how to solve this problem
(node:23052) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getQrPng is not defined
    at __puppeteer_evaluation_script__:1:1
    at ExecutionContext._evaluateInternal (D:\Sociality Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:172:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (D:\Sociality Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23052) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
