### ISSUE TITLE
2.2106.5

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#1391]
# UPDATE TO 3.6.10 - IT SHOULD FIX THE MAJORITY OF THE PROBLEMS

- [x] l10n
- [x] QR
- [x] GroupMetadata
- [x] License key holders
- [x] Send Text

Long Term:

- [x] WAPI should no longer be shipped with each version
- [x] Migrate WAPI to moduleraid
- [ ] fallback launch js

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.6.6](https://github.com/open-wa/wa-automate-nodejs/compare/3.6.5...3.6.6) (2021-02-25)

- Update Wapi.js [`#1390`](https://github.com/open-wa/wa-automate-nodejs/pull/1390)
- 🐛  fixes #1389 [`#1389`](https://github.com/open-wa/wa-automate-nodejs/issues/1389)
- Release 3.6.6 [`5faee4b`](https://github.com/open-wa/wa-automate-nodejs/commit/5faee4bcb4f4cc26e795c4fafe6426e1c72c5427)
- 🐛#1391 [`6757818`](https://github.com/open-wa/wa-automate-nodejs/commit/67578180286e95f87d807ac269014086fee92e1b)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.6.7](https://github.com/open-wa/wa-automate-nodejs/compare/3.6.6...3.6.7) (2021-02-25)

- Release 3.6.7 [`242ce8e`](https://github.com/open-wa/wa-automate-nodejs/commit/242ce8e84c62a336f23aa9e4eda08c81d7b62ba7)
- ➕  installed `moduleRaid` #1391 [`207e0bc`](https://github.com/open-wa/wa-automate-nodejs/commit/207e0bc8cb1a088a408a4ca4cd50e70ea16a2ae9)
- 🙈  ignore logs [`e1c43be`](https://github.com/open-wa/wa-automate-nodejs/commit/e1c43beffc3864730ed677df42e9fecd8f11ea23)
- 🥚  patch `l10n` [`7060df4`](https://github.com/open-wa/wa-automate-nodejs/commit/7060df451c8a8538650e2f51f614a9a28e8635af)
- 🥚  patch `GroupMetadata` #1391 [`54f5c7e`](https://github.com/open-wa/wa-automate-nodejs/commit/54f5c7e88450e61972879044e3cb5523b7262d64)
- 🐛  smart qr working #1391 [`8307c99`](https://github.com/open-wa/wa-automate-nodejs/commit/8307c99d1f090b744c51905ab5541eef678990c8)
- 🥚  patch update #1391 [`f069425`](https://github.com/open-wa/wa-automate-nodejs/commit/f069425085bfdbd472bcf6be1e8c280e2a7173ae)

**Comment by smashah** [comment]
@hasamaini @erickmourasilva @ikkehman @prayogigit @allanmello @IsanMaulana @cucabr @rvp98 @aymenitc @jlsubia404 @group2tts @cantiir2

Please update to 3.6.7 and try again. If there are further problems please report back on this issue with context thanks

**Comment by ikkehman** [comment]
i got new issue in 3.6.7.
**Screenshot**
![image](https://user-images.githubusercontent.com/62538390/109138009-78c16880-778c-11eb-9708-763dc74b477a.png)

then i try to fix it by install @pedroslopez  in /@open-wa/wa-automate/node_modules/. But i got an error like before update #1388 
![image](https://user-images.githubusercontent.com/62538390/109138364-deadf000-778c-11eb-9725-d87c7f85384b.png)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by alexanderoskin** [comment]
WA_VERSION: '2.2106.5'
PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36'
WA_AUTOMATE_VERSION: '3.6.7'
BROWSER_VERSION: 'HeadlessChrome/90.0.4403.0'
OS: 'Linux 4.15'
START_TS: 1614247917596

- Browser Launched
- Injecting api
- Initializing WA

And freezing on this step. Nothing else happens.

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.6.8](https://github.com/open-wa/wa-automate-nodejs/compare/3.6.7...3.6.8) (2021-02-25)

- Release 3.6.8 [`122fc2d`](https://github.com/open-wa/wa-automate-nodejs/commit/122fc2d7cbbe015212bfeb01f4f81e24fc038f43)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
@alexanderoskin please show your config

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.6.9](https://github.com/open-wa/wa-automate-nodejs/compare/3.6.8...3.6.9) (2021-02-25)

- Release 3.6.9 [`23e9dca`](https://github.com/open-wa/wa-automate-nodejs/commit/23e9dca9e11bb6b3f317e65fdf6f0287d5997985)
- ➖  removed `moduleraid` dependency due to `git` errors. Still used via patches for backwards compatibility. #1391 [`92b1cd2`](https://github.com/open-wa/wa-automate-nodejs/commit/92b1cd2c3eda82ff8cd5774c5b9b537986b3608c)

**Comment by alexanderoskin** [comment]
@smashah 

```
{
   "licenseKey":"....",
   "sessionData":"....",
   "disableSpins":true,
   "qrLogSkip":true,
   "sessionId":"........",
   "skipSessionSave":true,
   "logConsole":true,
   "logConsoleErrors":true,
   "killProcessOnBrowserClose":true
}
```

**Comment by smashah** [comment]
@alexanderoskin how many times have you restarted your process? also, have you tried the latest version 3.6.9?

**Comment by cantiir2** [comment]
> i got new issue in 3.6.7.
> **Screenshot**
> ![image](https://user-images.githubusercontent.com/62538390/109138009-78c16880-778c-11eb-9708-763dc74b477a.png)
> 
> then i try to fix it by install @pedroslopez in /@open-wa/wa-automate/node_modules/. But i got an error like before update #1388
> ![image](https://user-images.githubusercontent.com/62538390/109138364-deadf000-778c-11eb-9725-d87c7f85384b.png)

@smashah  this same problem

**Comment by smashah** [comment]
@cantiir2 please try 3.6.9

**Comment by ikkehman** [comment]
@smashah still error in 3.6.9 

![image](https://user-images.githubusercontent.com/62538390/109141145-faff5c00-778f-11eb-84a0-1f144f8137a7.png)

**Comment by alexanderoskin** [comment]
With 3.6.9 got - Error: Evaluation failed: ReferenceError: getQrPng is not defined

**Comment by alexanderoskin** [comment]
@smashah logs

<img width="1492" alt="Снимок экрана 2021-02-25 в 13 42 39" src="https://user-images.githubusercontent.com/5063096/109142063-7866a480-776f-11eb-8540-22d3b4d2535f.png">

**Comment by alexanderoskin** [comment]
@smashah Sentry error log [https://sentry.io/share/issue/69a96c88510b4dd08002c1a46a26ced4/](url)

**Comment by smashah** [comment]
@alexanderoskin @ikkehman can you set `throwOnError:true` in your config and try again please

**Comment by smashah** [comment]
@alexanderoskin please contact me on discord so I can investigate from within your machine because I'm unable to replicate

**Comment by king0429** [comment]
and when i updated to 3.6.9, still throw error of `getQrPng is not defined`,and i used puppeteer.js to call in terminal @smashah

**Comment by alexanderoskin** [comment]
@smashah with `throwOnError:true` nothing changed and nothing new in logs

**Comment by ghifar1** [comment]
thanks for hard work, working in 3.6.9

**Comment by cantiir2** [comment]
![image](https://user-images.githubusercontent.com/36468037/109145224-cb068780-7794-11eb-9644-304b5f17ed57.png)
i try with 3.6.9 not working

**Comment by ikkehman** [comment]
@smashah nothing changes

![image](https://user-images.githubusercontent.com/62538390/109145271-dd80c100-7794-11eb-9f3f-489677a62db4.png)

**Comment by HasamiAini** [comment]
@smashah 
**### thank you for the help ... i have been able to solve the problem, have a nice day**

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.6.10](https://github.com/open-wa/wa-automate-nodejs/compare/3.6.9...3.6.10) (2021-02-25)

- Release 3.6.10 [`205e1a7`](https://github.com/open-wa/wa-automate-nodejs/commit/205e1a7d063ae372a18982639eaa4dc7b09c53bc)
- 🥚  `sendText` patch #1391 [`7b20f8e`](https://github.com/open-wa/wa-automate-nodejs/commit/7b20f8e7bf00961dd4b27495e1620b8191a72be4)

**Comment by smashah** [comment]
@ikkehman @cantiir2 @king0429 @alexanderoskin please update to 3.6.10 and try again

**Comment by alexanderoskin** [comment]
With 3.6.10 load successfully 👍

**Comment by caturpamunqkas** [comment]
3.6.10 loaded qr successfully. thanks

**Comment by ikkehman** [comment]
Its works!!! Problem solved. Thanks 😊

**Comment by HasamiAini** [comment]
@smashah 
**### Sorry in advance .. I want to ask, is the current server really a little slow?
not like usual...or is it just me?
**

**Comment by ghifar1** [comment]
@HasamiAini me too, i think its just me

**Comment by smashah** [comment]
@HasamiAini the sticker server?

**Comment by HasamiAini** [comment]
@smashah **### not just stickers. all of them experience slow response**

**Comment by HasamiAini** [comment]
@smashah 
### **for the command when typed, the server appears but it takes a process to send it**

**Comment by HasamiAini** [comment]
not just stickers. all of them experience slow response

**Comment by jlsubia404** [comment]
Working well with 3.6.10 version. Thank you :)

**Comment by pedroslopez** [comment]
Whoop, saw I was tagged here haha- FYI I saw @smashah removed the direct dependency due to git errors, but the package is available on npm if you want to use it https://www.npmjs.com/package/@pedroslopez/moduleraid, which is how my library uses it and we haven't had any issues with it. v5 (latest) is the one that works with the new webpack. Good stuff though!

**Comment by smashah** [comment]
Must've overlooked checking on npm in the chaos. I will add it back thanks for your great work @pedroslopez
