### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getQrPng is not defined     at __puppeteer_evaluation_script__:1:1

### ISSUE THREAD

**Issue by cantiir2** [open-wa/wa-automate-nodejs#1395]
can you solved this pliss

(node:1692) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getQrPng is not defined
    at __puppeteer_evaluation_script__:1:1
    at ExecutionContext._evaluateInternal (D:\HisokaBOT-Whatsapp-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:172:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (D:\HisokaBOT-Whatsapp-Bot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by smashah** [comment]
track this in #1391

**Comment by Botmcz** [comment]
(node:11996) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getQrPng is not defined
    at __puppeteer_evaluation_script__:1:1
    at ExecutionContext._evaluateInternal (C:\xampp\whatsapp-botz\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:171:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\xampp\whatsapp-botz\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

COMO POSSO RESOLVER ESSE ERRO ?

**Comment by smashah** [comment]
@Botmcz please update to the latest version of the library this has been fixed already
