### ISSUE TITLE
Not listening any message

### ISSUE THREAD

**Issue by odhier** [open-wa/wa-automate-nodejs#1396]
![Screen Shot 2021-02-25 at 18 08 28](https://user-images.githubusercontent.com/28082192/109145012-837ffb80-7794-11eb-814c-6135b9056d4b.png)

After update to version 3.6.9, bot not listen/receive any messages.
i have enable `throwOnError` in my config, but there's no error thrown

**Comment by smashah** [comment]
@odhier can you try again with 3.6.10 please

**Comment by odhier** [comment]
@smashah nothing changes

**Comment by odhier** [comment]
its working now, thank you very much for your hard work @smashah
