### ISSUE TITLE
mc.processFiles is not a function

### ISSUE THREAD

**Issue by IanosJunior** [open-wa/wa-automate-nodejs#1398]
![Erro_Comunica](https://user-images.githubusercontent.com/34457222/109147749-23f9ff80-7744-11eb-9180-1365fc45591c.png)

?

**Comment by jeferssonlemes** [comment]
Same problem here

**Comment by lukasportal** [comment]
Same here

**Comment by smashah** [comment]
@IanosJunior I am unable to replicate the issue with the context you've provided. With the latest version 3.6.10, it is working fine for me. Please fill in the issue template.

thanks

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️

**Comment by lukasportal** [comment]
To anyone with this problem, here's what fixed for me:
on wapi.js:

look for the function `WAPI.procFiles` and replace the `await mc.processFiles...`
with:
```
await mc.processAttachments(blobs, chat, 1);
return mc;
```

then later on `sendImage`:
replace the `window.WAPI.procFiles(chat, mediaBlob)` with:

```
window.WAPI.procFiles(chat, [{ file: mediaBlob }])
```

**Comment by jeferssonlemes** [comment]
This solution works for me 😁,  thanks @lukasportal ✌

**Comment by smashah** [comment]
thanks @lukasportal

**Comment by IanosJunior** [comment]
Done! Thanks @lukasportal and @smashah .
Will you put it in the repository @smashah ?

**Comment by smashah** [comment]
@IanosJunior it doesn't seem to be affecting anyone using the latest version of the library so I will leave it out for now. I think this issue only occurs for people using wapi.js on it's own

**Comment by IanosJunior** [comment]
Ok.
Thanks @smashah

**Comment by costafacchini** [comment]
This solution works for me too, thanks @lukasportal
