### ISSUE TITLE
 Doesn't get the first message sent, but if a message is sent then it gets both

### ISSUE THREAD

**Issue by can1871** [open-wa/wa-automate-nodejs#1405]
Doesn't get the first message sent, but if a message is sent then it gets both. Why?

**Comment by smashah** [comment]
@can1871 I need a screenshot.

Is this the same as #1397 ?

**Comment by Urbaeexyz** [comment]
> @can1871 I need a screenshot.
> 
> Is this the same as #1397 ?

can i ask you something?

why my bot is not respond in version 3.3.0 or newer?
my bot just respond command in version older - 3.2.6

i have search what's wrong with the code
but i can't find out wtf is just happen'

**Comment by can1871** [comment]
> @can1871 I need a screenshot.
> 
> Is this the same as #1397 ?


It's not the same as # 1397. There is nothing to see in the screenshot because my problem is that when I start the program, nothing happens when I first send a message, but when I send a second message, it writes the previous and the new message.

**Comment by can1871** [comment]
I realized that this problem was rooted in the method I used to solve problem # 1399. client.sendText (phone_number + "@ c.us", msg_content); it doesn't work that way. But like this client.sendText (905347396479@c.us ", msg_content);
works. Why?
The error I got is the following: Argument of type 'string' is not assignable to parameter of type 'ChatId'.ts (2345)

**Comment by smashah** [comment]
@can1871 I'm not sure what's going on with your set up but for now try this:

```javascript
client.sendText(`905347396479@c.us` as any, msg_content);
```

**Comment by can1871** [comment]
> @can1871 I'm not sure what's going on with your set up but for now try this:
> 
> ```js
> client.sendText(`905347396479@c.us` as any, msg_content);
> ```

This way I solved the sendtex problem, but not receiving the first message. When he sends the second message, he receives the first message and writes it on the screen

**Comment by smashah** [comment]
@can1871 can you share the repo with all of your code please so we can resolve this issue.

**Comment by smashah** [comment]
Closing for now please respond with the specific code that would help in replicating this issue.

Thanks
