### ISSUE TITLE
Error when generating swagger spec

### ISSUE THREAD

**Issue by jlsubia404** [open-wa/wa-automate-nodejs#1406]
I have the next error when I run docker-compose up --build.

`Error File not found: /usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.ts FileNotFoundError: File not found: /usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.ts
app_1      |     at DirectoryCoordinator.addSourceFileAtPath (/usr/src/app/node_modules/ts-morph/dist/ts-morph.js:17851:19)
app_1      |     at Project.addSourceFileAtPath (/usr/src/app/node_modules/ts-morph/dist/ts-morph.js:19289:51)
app_1      |     at /usr/src/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:107:42
app_1      |     at step (/usr/src/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:63:23)
app_1      |     at Object.next (/usr/src/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:44:53)
app_1      |     at fulfilled (/usr/src/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:35:58)`

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.6.12](https://github.com/open-wa/wa-automate-nodejs/compare/3.6.11...3.6.12) (2021-02-26)

- 🐛  [CLI] fix #1406 [`#1406`](https://github.com/open-wa/wa-automate-nodejs/issues/1406)
- Release 3.6.12 [`03d884a`](https://github.com/open-wa/wa-automate-nodejs/commit/03d884aa70233d5621ae90d163cc1d96d56a1338)
- 🐛  [CLI] `--headless false` should work now [`3a96be3`](https://github.com/open-wa/wa-automate-nodejs/commit/3a96be348be8dac5286adbc37423e07f5ea01adb)
- 🥚  fix `clearChat` [`2cf6c07`](https://github.com/open-wa/wa-automate-nodejs/commit/2cf6c073f67be7adfb0bbfd956032dab1a6f493b)

**Comment by smashah** [comment]
@manojsitapara try now with this latest version

**Comment by manojsitapara** [comment]
@smashah now working fine !! Thank you !!
