### ISSUE TITLE
sendLinkWithAutoPreview API is not generating image thumbnail 

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-nodejs#1407]
I am using latest version 3.6.12

/sendLinkWithAutoPreview API is not generating image thumbnail, only title and description shows up on message.

earlier it was working fine but suddenly it stopped working.

current output

![image](https://user-images.githubusercontent.com/12126671/109283024-496e3280-7844-11eb-86b4-62acc220e3d0.png)

Expected output

![image](https://user-images.githubusercontent.com/12126671/109283045-4ffcaa00-7844-11eb-8c82-5b21434eaf1f.png)

I am not passing any value in `thumbnail `parameter in this API

Following parameters I am using to send link with auto preview

`{
  "args": {
    "to": "xxxxxx@c.us",
    "url": "https://www.amazon.in/LG-Inverter-Fully-Automatic-Loading-T7585NDDLGA/dp/B08GNX4PRN",
    "text": "LG Washing Machine"
  }
}`

**Comment by smashah** [comment]
@manojsitapara I've issued a patch for this. please restart your session and let me know if this is fixed thanks

**Comment by manojsitapara** [comment]
@smashah thanks !! it's working now !!
