### ISSUE TITLE
TOSBLOCK error

### ISSUE THREAD

**Issue by can1871** [open-wa/wa-automate-nodejs#1410]
![Capture](https://user-images.githubusercontent.com/53393674/109325189-b2ff3880-7866-11eb-81ae-9112b3bcbc58.PNG)

after that chrome closes and the program ending.

The reason for all the problems I opened before was that I got this error and downloaded the new updated version. If I can fix this error my problems will disappear.

**Comment by smashah** [comment]
2.0.25?! Please only use the latest versions of the library. If you are having ts lint issues then use 

```javascript
//@ts-ignore
```

above those lines.
