### ISSUE TITLE
#OpenSource_The_Open_WA_Library

### ISSUE THREAD

**Issue by SomnathDas** [open-wa/wa-automate-nodejs#1414]
**Dear [ not a corpo ] Admin!** ( ꈍᴗꈍ)

Hi, we've been using this library for a while and recently had to switch to **Baileys** due because it was easy to edit/extend the capabilities of. We tried to fix it, but it was not locking us out. Then **we found out that it won't let edited WAPIs access WA**. The reason I'm making this issue is to know why is this a thing, _it doesn't cause you any harm that if you let edited WAPIs be a thing, if any if we make some remarkable breakthrough or something open a pull request and do the right thing._ _The point of open-source software is giving back to the community and the community will help you in every_. **But is this the right thing? If only that this makes it looks like you're using Github as an advertising platform for this library.**

In the recent updates _we've noticed the codes are not actually there, and it's actually taken from your api endpoint and it uses the JS eval function_. Isn't that an **huge vulnerability**? **Making how can we trust the code gotten from a private endpoint?** **Doesn't this take away the "open" part of "open-wa**"? The recent wa-web update caused this library to break... If this repo was fully open source and didn't restrict edited code, the issue should have been solved more quickly and more efficiently, also it wouldn't have made people without session data and licence key wait (we know this is due the fix involved edited WAPI). This brings me to my next point. Licence key.

**Licence Keys** are a great way to earn money but it's not the way to go with open source. Many people (including us) would love to donate if this was fully open-source. I'm not especially mad about it but.... Why? Why do I need a license key to a 'sticker as reply'? Or 'set the description of a group', we get it about the story/status thing. But this....

Sticker API.. **we still don't get it why you would go an extra mile and create your own sticker endpoint while you could provide a self-hosting solution**. Not gonna say more. It's pretty clear from above what we're trying to say.

Listen fam, **we are developers**, **we are not the fuckin' corporates, eh?**. We are here for **Open Web** & **Open Development** . This project is huge and you're literally ruining it by doing all these things. 

~ Sincerely, God of Culture

**Comment by MFarelS** [comment]
Good, 👍

**Comment by Suryapardana** [comment]
We all feel it

**Comment by MFarelS** [comment]
Shah, recent update you made the bot script corrupted

**Comment by smashah** [comment]
Going to lock this self-rightous convo until I can fully reply.

TLDR: No
