### ISSUE TITLE
adding and removing participants to a group

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#1415]
This issue is to track issues w.r.t adding and removing participants from a group. Apparently there is some delay that needs to be respected between events.

If you are having this issue also, please add your experiences here instead of creating a new issue.

**Comment by Bintang73** [comment]
I don't care about you, I've moved to whatsapp web js. jajajaja

**Comment by smashah** [comment]
Seems to be fixed with recent patches
