### ISSUE TITLE
why are you stuck here?

### ISSUE THREAD

**Issue by restugbk** [open-wa/wa-automate-nodejs#1420]
![image](https://user-images.githubusercontent.com/69737152/109410405-0ee3d180-79cd-11eb-9012-03131f8d1ff6.png)

**Comment by smashah** [comment]
Is this still happening?

**Comment by restugbk** [comment]
has not

**Comment by MFarelS** [comment]
Minta apikey bang :3

> has not

**Comment by restugbk** [comment]
> Minta apikey bang :3
> 
> > has not

anjjer
