### ISSUE TITLE
Incorrect chat data in message object

### ISSUE THREAD

**Issue by adityaag121** [open-wa/wa-automate-nodejs#1430]
**Describe the bug**
The chat data inside the message object which was sent using client.reply() to a group, contains the data of some other chat.

**Steps to Reproduce**
1. Listen to onAnyMessage and log the message object
2. Send a text message as a reply to some message in a group, using client.reply()
3. Check the logged message object of the message sent in step 2.
4. See that the chat object inside it contains data of some other chat.

**create() code**
This is the code you use to create the client. e.g
```javascript
create({
        sessionId: 'BarBar',
        headless: headless,
        qrTimeout: 0,
        authTimeout: 0,
        restartOnCrash: start,
        cacheEnabled: false,
        useChrome: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false,
        chromiumArgs: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--aggressive-cache-discard',
            '--disable-cache',
            '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            '--disk-cache-size=0'
        ]
    })
```

**Expected behavior**
The chat data should be of the group in which the message was sent.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2106.5',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.6.13',
  BROWSER_VERSION: 'HeadlessChrome/88.0.4324.190'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: 'Windows 10'

**Additional context**

**Comment by smashah** [comment]
thanks for filling out the template. I will look into it and report back thanks

**Comment by smashah** [comment]
@adityaag121 can you show the code please

**Comment by smashah** [comment]
This is super odd, I think it is a bug from wa. I will issue a patch for this either way

**Comment by adityaag121** [comment]
> @adityaag121 can you show the code please. Is step 2 in onMessage or onAnyMessage?

It's onAnyMessage. And the chat data is of some account which is not even in the group. Strange ik. Were you able to reproduce it or shall I provide the code?

**Comment by smashah** [comment]
@adityaag121 this should have been addressed with the recent patches. Please restart your session and can you confirm that it is working as expected now please. thanks

**Comment by adityaag121** [comment]
> @adityaag121 this should have been addressed with the recent patches. Please restart your session and can you confirm that it is working as expected now please. thanks

Yes, it's working as expected now. Thanks
