### ISSUE TITLE
target close

### ISSUE THREAD

**Issue by Jonas33235** [open-wa/wa-automate-nodejs#1448]
frequent error
![image](https://user-images.githubusercontent.com/56744848/110229149-1bdd5500-7ee6-11eb-9b2b-e5d57c346ab6.png)

**Comment by smashah** [comment]
@Jonas33235 can you share the video file that was causing the problem

**Comment by Jonas33235** [comment]
I don't have the video at the moment
 =(

> @Jonas33235 can you share the video file that was causing the problem

**Comment by smashah** [comment]
@Jonas33235 do you set custom durations for the stickers?

**Comment by Jonas33235** [comment]
> @Jonas33235 do you set custom durations for the stickers?


                            client.sendMp4AsSticker(chatId, mediaData, { fps: 20}, { pack: authordefault , author: packdefault })

**Comment by smashah** [comment]
@Jonas33235 The default for stickers is already 10fps to avoid hitting the 1MB limit. I suggest trying with the defaults and seeing if the error still occurs. To be honest, without any further context or code I cannot help with this issue.

**Comment by Jonas33235** [comment]
> @Jonas33235 The default for stickers is already 10fps to avoid hitting the 1MB limit. I suggest trying with the defaults and seeing if the error still occurs. To be honest, without any further context or code I cannot help with this issue.

ok, thanks

**Comment by smashah** [comment]
If you are able to replicate this please fill the issue template.

Closing.

thanks
