### ISSUE TITLE
Not able to get reply message after creating it

### ISSUE THREAD

**Issue by guilhermebkel** [open-wa/wa-automate-nodejs#1454]
**Describe the bug**
Hello everyone! At first I would like to thank you all for making this awesome lib!
Some days ago I started using it and came across with the following bug: When I create a message and try to get it by its id after, it works as expected, but when I create a replyMessage and try to get it later, it does not return me a Message but null 🤔
Do you know why this happens?

**Steps to Reproduce**
```typescript
const messageId = await client.sendMessage(ID, 'test message')
const message = await client.getMessageById(messageId) // returns Message

const replyMessageId = await client.reply(ID, 'test message', messageId)
const replyMessage = await client.getMessageById(replyMessageId) // returns null
```

**Expected behavior**
Since a reply message is a message with reply option, I think it was expected to return a message on **getMessageById** 🤔

**Comment by smashah** [comment]
Interesting. I will look into this.

**Comment by smashah** [comment]
@guilhermebkel I've issued a patch to fix this. Please restart your session and try again. Let me know if it worked. Thanks

**Comment by guilhermebkel** [comment]
@smashah It now works like a charm! Thanks for fixing it so fast!
