### ISSUE TITLE
Proxy fails on production

### ISSUE THREAD

**Issue by guilhermebkel** [open-wa/wa-automate-nodejs#1467]
Hello! How you doing?

I've started using proxy with **open-wa** and it works like a charm on development environment, but fails on production (actually when I set up a proxy on production, the message logs stop on "- Initializing WA" and does not go anywhere).

My Dockerfile is:
```Dockerfile
FROM node:current-stretch

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY ./package.json /usr/src/app
COPY ./package-lock.json /usr/src/app

RUN apt-get update

RUN apt-get install -y libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libgconf2-4 libasound2 libatk1.0-0 libgtk-3-0

RUN apt-get install -y libgbm-dev

RUN npm ci

COPY . /usr/src/app

RUN npm run build

ENV NODE_ENV production

ENV PORT 4444

CMD [ "npm", "run", "start" ]
```

Do you have any tips about that?

A huge thanks for this awesome lib :)

**Comment by smashah** [comment]
@guilhermebkel will need to see your config to see what's going wrong

**Comment by guilhermebkel** [comment]
@smashah My config is:
```js
let config = {
    authTimeout: 60,
    blockCrashLogs: true,
    disableSpins: true,
    headless: true,
    hostNotificationLang: 'PT_BR',
    logConsole: true,
    qrLogSkip: false,
    skipSessionSave: true,
    corsFix: true,
    popup: false,
    qrTimeout: 0,
    deleteSessionDataOnLogout: true,
    idCorrection: true,
    killProcessOnBrowserClose: true,
    logConsoleErrors: true,
    chromiumArgs: ["--disable-setuid-sandbox", "--no-sandbox"]
}
```

The correct error that is shown is:

```
Error: net::ERR_FAILED at https://web.whatsapp.com
    at navigate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async FrameManager.navigateFrame (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:416:16)
    at async Page.goto (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:789:16)
```

**Comment by smashah** [comment]
For whatever reason, your proxy is not able to get the web page in your production environment.

Have you tried the proxy in another environment? Maybe your proxy is being blocked by the provider. If you want I can test out the proxy on my machine if you dm me the details in discord

**Comment by guilhermebkel** [comment]
hmmmmm, the other only environment I've tried was my local machine and it worked perfectly, besides, I do not think I could be a provider block since I have made a **CURL** inside the machine that is running the open-wa and the **CURL** works fine as well 🤔 (or maybe the curl does not simulate the chromium behavior)

**Comment by smashah** [comment]
@guilhermebkel can you DM me your config with the proxy details and I will look into this. I can't really help without testing it out myself

**Comment by smashah** [comment]
For reference, this should work:

```Dockerfile
FROM node:current-stretch

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY ./package.json /usr/src/app
COPY ./package-lock.json /usr/src/app

RUN apt-get update

RUN apt-get install -y libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libgconf2-4 libasound2 libatk1.0-0 libgtk-3-0 libasound2-data libatk-bridge2.0-0 libatk1.0-data libdrm2 libxkbcommon0 libgbm1 libxshmfence1

RUN apt-get install -y libgbm-dev

RUN npm ci

COPY . /usr/src/app

RUN npm run build

ENV NODE_ENV production

ENV PORT 4444

CMD [ "npm", "run", "start" ]
```

**Comment by smashah** [comment]
@guilhermebkel did the changes work for you?

**Comment by guilhermebkel** [comment]
Hello @smashah! At first thanks a lot for that support!

I've tried to add these changes on my Dockerfile but I'm still having the same error :/ So I think it is something related to the Docker environment. Tomorrow I'll try to install my application on a VM without Docker in order to try to understand what I'm missing on my Dockerfile to get it to work.

**Comment by smashah** [comment]
@guilhermebkel I have tried to make it work in a docker environment and the following files work when compiled and run on docker on mac and ubuntu.



<details>
<summary>index.js</summary>

```javascript
const {create} = require('@open-wa/wa-automate')

const proxyServerCredentials = {
	...
}

let config = {
    authTimeout: 60,
    blockCrashLogs: true,
    disableSpins: true,
    headless: true,
    hostNotificationLang: 'PT_BR',
    logConsole: true,
    qrLogSkip: false,
    skipSessionSave: true,
    corsFix: true,
    popup: false,
    qrTimeout: 0,
    deleteSessionDataOnLogout: true,
    idCorrection: true,
    killProcessOnBrowserClose: true,
    logConsoleErrors: true,
    chromiumArgs: [
            "--disable-setuid-sandbox",
            "--no-sandbox"
            ],
  proxyServerCredentials
}


create(config)
```

</details>


<details>
<summary>Dockerfile</summary>


```Dockerfile
FROM node:current-stretch

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY ./package.json /usr/src/app

RUN apt-get update &&  apt-get install -y libgbm-dev libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libgconf2-4 libasound2 libatk1.0-0 libgtk-3-0 libasound2-data libatk-bridge2.0-0 libatk1.0-data libdrm2 libxkbcommon0 libgbm1 libxshmfence1

COPY . /usr/src/app

RUN npm i

ENV NODE_ENV production

ENV PORT 4444

CMD [ "npm", "run", "start" ]
```

</details>

<details>
<summary>package.json</summary>


```javascript
{
  "name": "issue-1467",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "@open-wa/wa-automate": "^3.9.5"
  }
}
```


</details>


command:

```bash
> docker build --no-cache -t issue-1467 . && docker run -it issue-1467
```

The only thing I noticed is that it does take quite a while for the logs to go from 

```bash
- Initializing WA
Active proxy: http://1....
```

to

```bash
- Browser Launched
```

in the docker environment. Why is this? Not entirely sure but if you wait long enough it definitely will work.

The delay may be due to the performance of your specific proxy.

Because I'm able to reliably launch the session with the aforementioned set up I will close this issue for now.

Thanks

**Comment by guilhermebkel** [comment]
Hello @smashah, it looks like I had an cache dependency issue. I deleted my package-lock.json that I use for caching during builds, created a new one and it worked like a charm while using the commands you asked me for on Dockerfile in the last comment!

Thanks for all the support!
