### ISSUE TITLE
blur stickers

### ISSUE THREAD

**Issue by richoarbianto** [open-wa/wa-automate-nodejs#1471]
![sticker-blur](https://user-images.githubusercontent.com/74143772/111032812-a66f0880-8440-11eb-8cbf-e730fc024ba7.jpg)

Why does the sticker that I make produce a blurry sticker?

I made a sticker using the following code:

```python
client.sendImageAsSticker(message.from, message.quotedMsgObj.content, {author: authordefault, keepScale: true, pack:  packdefault})
```

Why?

**Comment by smashah** [comment]
@richoarbianto what is the source image?

**Comment by richoarbianto** [comment]
@smashah image file

**Comment by smashah** [comment]
@richoarbianto I mean, can you attach the original file here

**Comment by richoarbianto** [comment]
![textprome_16048aeef5e572](https://user-images.githubusercontent.com/74143772/111036585-7af51980-8452-11eb-987d-787aa7d6a186.jpg)

try using it, how to do it?

**Comment by richoarbianto** [comment]
I have managed to solve this problem by first using the [decryptMedia()](https://docs.openwa.dev/classes/api_client.client.html#decryptmedia) function to generate a buffer.

**Comment by Optimuspime123** [comment]
> I have managed to solve this problem by first using the [decryptMedia()](https://docs.openwa.dev/classes/api_client.client.html#decryptmedia) function to generate a buffer.

Can you please elaborate? (the docs website seems to be down - privacy error) 
I am also getting this issue, I tried also manually resizing the image to 512*512 , no luck.
