### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by edneijunior** [open-wa/wa-automate-nodejs#1472]
I noticed that my instance had a significant increase in the use of cpu for no apparent reason.

**Describe the bug**
I have three instances of OpenWa running for a few months, after upgrading to version 3.7.0 I noticed the high CPU
After reading qrCode after a while, for no apparent reason, the use of cpu goes above 70%

**Steps to reproduce the behavior:**
1. Execute below sample code
2. Scan QR code

**create() code**

```javascript
Array.prototype.find = function (...args)
{
    let index = this.findIndex(...args);
    if (index >= 0)
        return index >= 0 ? this[index] : void 0;
};

global.openWA = require('@open-wa/wa-automate');
const fs = require('fs');
const async = require("async");
const request = require('request');
const moment = require('moment');
const mime = require('mime-types');

global.uaOverride = 'WhatsApp/2.16.352 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15';

    openWA.create({
        sessionId: "/whatsSessions/" + F.config['instance'],
        useChrome: false,
        headless: true,
        throwErrorOnTosBlock: true,
        qrTimeout: 0, //set to 0 to wait forever for a qr scan
        authTimeout: 0, //set to 0 to wait forever for connection to phone
        autoRefresh: true, //default to true
        safeMode: false,
        disableSpins: true
}).then(function (client) {
        if (qrCodeManager) {
            qrCodeManager.send({connected: true});
        }
        WA_CLIENT.SETUP(client, F.config['webhook'], F.config['token']);
    });

});
```

Expected behavior
CPU usage should not constantly be on high

**DEBUG INFO**
```javascript
{
  WA_VERSION: '2.2108.8' ,
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) 
                    Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.9.3', 
  BROWSER_VERSION: 'HeadlessChrome/90.0.4427.0' ,
 OS:''Linux 4.9';
}
```

**Screenshots**
![Sem título2](https://user-images.githubusercontent.com/67341065/111033769-a3006080-83f1-11eb-8100-e0c79924e7ea.png)

**Host (please complete the following information):**
OS: "Debian GNU/Linux 9 (stretch)

**Additional context**
none

**Comment by smashah** [comment]
@edneijunior thanks for filling in the template. Do you have any idea as to when this jump in CPU usage happens (maybe it is triggered by a firing of a specific listener)

What listeners do you using in your code? Is this easily reproducible? Does the problem occur on every instance? Do all instances run the same code?

**Comment by edneijunior** [comment]
hello friend, yes, all instances with the same percentage of disk usage. I did not notice any event that may have triggered the increase in disk usage. The only point in common is that they were consuming a lot of memory, so I restarted them all and scanned qrCode again.

**Comment by marcogaruthix** [comment]
the same occurs here

**Comment by smashah** [comment]
@edneijunior @marcogaruthix

The investigation to the root cause of this issue is more involved than what can be achieved over a github issue. I will need to audit your code and your environments to solve this one. Please join the discord and use the perf channel to discuss this further.
