### ISSUE TITLE
parseUrl is not a function

### ISSUE THREAD

**Issue by lbertoncello** [open-wa/wa-automate-nodejs#1484]
I'm receiving the following error after running `npx @open-wa/wa-automate --in-docker --api-host $API_HOST -p 3000 -k $API_KEY -w $API_WEBHOOK --qr-timeout 0 --qr-log-skip --disable-spins --popup -l $API_LICENSE`

```
Error parseUrl is not a function TypeError: parseUrl is not a function
    at /app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:193:58
    at Array.map (<anonymous>)
    at /app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:162:28
    at step (/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:63:23)
    at Object.next (/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:44:53)
    at fulfilled (/app/node_modules/@open-wa/wa-automate/dist/build/build-postman.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**DEBUG INFO**

```
Debug Info {
  WA_VERSION: '2.2108.8',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.9.5',
  BROWSER_VERSION: 'HeadlessChrome/90.0.4427.0',
  OS: 'Linux 4.4'
}
```

**Comment by smashah** [comment]
what an odd issue. I'm not able to reproduce. What node version is your container/vps running?

**Comment by lbertoncello** [comment]
> what an odd issue. I'm not able to reproduce. What node version is your container/vps running? @lbertoncello

My container is using Node 14.5.0

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.9.6](https://github.com/open-wa/wa-automate-nodejs/compare/3.9.5...3.9.6) (2021-03-16)

- build(deps): bump ts-json-schema-generator from 0.88.0 to 0.89.0 [`#1475`](https://github.com/open-wa/wa-automate-nodejs/pull/1475)
- build(deps-dev): bump eslint from 7.21.0 to 7.22.0 [`#1476`](https://github.com/open-wa/wa-automate-nodejs/pull/1476)
- build(deps): bump puppeteer-extra-plugin-block-resources from 2.2.8 to 2.2.9 [`#1478`](https://github.com/open-wa/wa-automate-nodejs/pull/1478)
- build(deps): bump puppeteer-extra-plugin-stealth from 2.7.5 to 2.7.6 [`#1479`](https://github.com/open-wa/wa-automate-nodejs/pull/1479)
- build(deps-dev): bump @types/node from 14.14.33 to 14.14.34 [`#1481`](https://github.com/open-wa/wa-automate-nodejs/pull/1481)
- build(deps): bump patch-package from 6.4.6 to 6.4.7 [`#1480`](https://github.com/open-wa/wa-automate-nodejs/pull/1480)
- build(deps): bump pino from 6.11.1 to 6.11.2 [`#1477`](https://github.com/open-wa/wa-automate-nodejs/pull/1477)
- build(deps): bump puppeteer-extra from 3.1.17 to 3.1.18 [`#1482`](https://github.com/open-wa/wa-automate-nodejs/pull/1482)
- build(deps-dev): bump typedoc from 0.20.30 to 0.20.32 [`#1483`](https://github.com/open-wa/wa-automate-nodejs/pull/1483)
- Release 3.9.6 [`94e10b6`](https://github.com/open-wa/wa-automate-nodejs/commit/94e10b66d98cbd6f8f8de57c317df913d2ae55d1)
- updated readme links [`729ac1d`](https://github.com/open-wa/wa-automate-nodejs/commit/729ac1d64b598d870eb672d8505e71a0d78a25e6)
- 📝 fix links in docs homepage [`37d05a9`](https://github.com/open-wa/wa-automate-nodejs/commit/37d05a987ea18f92c7333a5847d788ae34d8ea07)
- ⬆️  update wa-decrypt [`1af3bfd`](https://github.com/open-wa/wa-automate-nodejs/commit/1af3bfd1736e216e44a84b4de94548b0321385bc)
- 🐛 possible solution for #1484 [`126100f`](https://github.com/open-wa/wa-automate-nodejs/commit/126100fda974163b608e5f250aad1fe2687219e2)
- 🥚  handle jpeg octet-streams [`c0b20a6`](https://github.com/open-wa/wa-automate-nodejs/commit/c0b20a6d38cd0bde16c194a68e3fa88f45b745fc)
- 🥚  patch update - memory/cpu improvements [`6c709f5`](https://github.com/open-wa/wa-automate-nodejs/commit/6c709f59cce5f81a704a0d397bfee90f9c28e628)

**Comment by smashah** [comment]
@lbertoncello try 3.9.6

**Comment by lbertoncello** [comment]
> @lbertoncello try 3.9.6

It's working now. Thanks!
