### ISSUE TITLE
Run api on web hosting 

### ISSUE THREAD

**Issue by suariana** [open-wa/wa-automate-nodejs#1486]
Hi, i have a problem with running this api on web hosting
the api can't create a qr code images 
i already changes the permission but still can't create the file
is there any solution to solve the problem?
thankyou :)

**Comment by smashah** [comment]
There isn't much info here but if you are using the heroku deployment, you have to authenticate and generate a session.data.json file then set it as an environmental variable because a heroku dyno does not maintain its states.

**Comment by suariana** [comment]
![image](https://user-images.githubusercontent.com/47437771/111400734-e6fda900-8702-11eb-90ec-0d0c9132eb6c.png)

this is my code, i wanna make a png file of the qr code but that doesn't work, when i try to make txt file with fs.writeFile function, it's working properly, i still don't know what's the problem.

it only happens in web hosting, when i try it on my local computer, it's working properly
