### ISSUE TITLE
Function refresh not working

### ISSUE THREAD

**Issue by victorsouzaleal** [open-wa/wa-automate-nodejs#1493]
**Describe the bug**
Problem with client.refresh() , the promise never ends and the bot is stuck only with the message on the console "Refreshing"

**Steps to Reproduce**
1. Try to run client.refresh () from any part of the code

**create() code**
This is the code you use to create the client. e.g
```javascript
module.exports = options = (headless, start) => {
    const options = {
        sessionId: 'session',
        headless: headless,
        qrTimeout: 0,
        authTimeout: 0,
        restartOnCrash: start,
        cacheEnabled: false,
        useChrome: true,
        stickerServerEndpoint: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false,
        chromiumArgs: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--aggressive-cache-discard',
            '--disable-cache',
            '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            '--disk-cache-size=0'
        ]
    }
    return options
}

create(options(false, start))
    .then(client => start(client))
    .catch((error) => console.log(error))

```

**Expected behavior**
The page reload and the bot continue to work.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2108.8
  PAGE_UA: WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
  WA_AUTOMATE_VERSION: 3.9.6
  BROWSER_VERSION: Chrome/89.0.4389.90
  OS: Windows 10
}
```

**Screenshots**
Nothing happens on the Chrome screen

**Host (please complete the following information):**
 - OS: Windows 10

**Comment by smashah** [comment]
`refresh` has been updated and tested to be working in v3.9.7

Please open a new issue if there are any further problems. thanks
