### ISSUE TITLE
version:3.9.6,EASY API: error Error: Protocol error (Runtime.callFunctionOn): Session closed.

### ISSUE THREAD

**Issue by FubinSama** [open-wa/wa-automate-nodejs#1494]
**Describe the bug**
version 3.9.6 EASY API , `middleware -> error Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.`

**Steps to Reproduce**
1. exec `nohup npx @open-wa/wa-automate &`
2. Waiting for some minutes and do nothing.
3. There's a `session close` appears and threads terminal

**The whole console**
```JavaScript
middleware -> error Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (/data/app/whatsApp/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:195:35)
    at ExecutionContext._evaluateInternal (/data/app/whatsApp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:201:50)
    at ExecutionContext.evaluate (/data/app/whatsApp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:27)
    at DOMWorld.evaluate (/data/app/whatsApp/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:91:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
How can I fix this?

Thank u very much!

**Comment by smashah** [comment]
@FubinSama for some reason the browser/page is being closed or is being "disconnected" from the open-wa client . This usually happens when the browser context is 'let go', for example, when your computer goes to sleep or when the client is stringified and referenced later. Because you are using the easy-api I would assume that this is due to the node process being interrupted in some way. Does this happen without `nohup`?

**Comment by FubinSama** [comment]
@smashah I think it doesn't happen without `nohup`. But I can't sure it. 
Howerver, I using `nohup` to run it for 12 hours and the error just occurs one time.(By the way, I ran it on a CentOS7 server and there's alway request to it.)
Thanks for your help.

**Comment by smashah** [comment]
@FubinSama it seems like an extreme edge case. I would suggest not using `nohup` and also restarting the process regularly based on your experience (so in your situation I would restart it every 12 hours).

For now, I will close this issue but please update it with any new details or you can mention this issue in the discord to discuss further. 

Thanks
