### ISSUE TITLE
Sending Image to endpoint maximal  100px only?

### ISSUE THREAD

**Issue by the-jojo-jj** [open-wa/wa-automate-nodejs#1501]
I've got image from endpoint just 100px only. there is the way to setting this up?

thanks.

**Comment by smashah** [comment]
@the-jojo-jj when you receive a media/image message via the API, the body property will represent the blurred thumbnail of the image, not the actual image. You have to decrypt the message using /decryptMedia

**Comment by the-jojo-jj** [comment]
Ok, super thanks!

**Comment by the-jojo-jj** [comment]
@smashah can you give me example message format?

**Comment by the-jojo-jj** [comment]
Messageid = id 

Thanks!
