### ISSUE TITLE
REQ

### ISSUE THREAD

**Issue by perikout** [open-wa/wa-automate-nodejs#1510]
I really want this nice library to have the send raw webp as video / gif feature, is that possible? I beg you to make it possible

**Comment by smashah** [comment]
https://docs.openwa.dev/classes/api_client.client.html#sendrawwebpassticker

**Comment by perikout** [comment]
> https://docs.openwa.dev/classes/api_client.client.html#sendrawwebpassticker

Sorry that didn't answer me, I'd like to be able to convert Webp to video / gif

**Comment by smashah** [comment]
@perikout you can achieve this by reversing the sticker code in client.ts

Webp files work pretty much everywhere why would you want to convert from webp to gif?

**Comment by perikout** [comment]
> @perikout you can achieve this by reversing the sticker code in client.ts
> 
> Webp files work pretty much everywhere why would you want to convert from webp to gif?

Because I want to change animated webp to gif simply

**Comment by smashah** [comment]
@perikout It's not really in the scope of the library to be a converter for media. especially when it's not useful going into any functionality of the library.

That aside, ffmpeg can encode webp but it cannot decode webp.

Also, webp is a better format than gifs.

**Comment by perikout** [comment]
> @perikout It's not really in the scope of the library to be a converter for media. especially when it's not useful going into any functionality of the library.
> 
> That aside, ffmpeg can encode webp but it cannot decode webp.
> 
> Also, webp is a better format than gifs.

So how do I send the animated webp on WhatsApp?

**Comment by smashah** [comment]
@perikout 

https://docs.openwa.dev/classes/api_client.client.html#sendrawwebpassticker

the third parameter (animated) is a boolean, set it to `true` if you are sending an animated webp.

**Comment by perikout** [comment]
Sorry, can you make me an example? @smashah
