### ISSUE TITLE
Is this against Whatsapp's Terms of Service?

### ISSUE THREAD

**Issue by lfilipe09** [open-wa/wa-automate-nodejs#1517]
I am thinking using this library to develop an academic research in my university, I see on internet nowadays a lot of companies that develops whatsapp chatbots using their own API, but they don't have access to Whatsapp API according to the official [list](https://www.facebook.com/business/partner-directory/search?solution_type=messaging&platforms=whatsapp) . I've made some interviews with that companies that develop chatbot for whatsapp without license and they told me that Whatsapp only blocks bulk messaging and abusive behavior.

And in my case this chatbot would bring such good things for the community i am working for, I will not send any bulk messaging and I'll only talk to people that is in my contact list or sent me a text before and they can leave chatbot anytime and the chatbot asks for permission to talking to people in first interaction.

Is this against Whatsapp's Terms of Service? I read this [article](https://faq.whatsapp.com/general/security-and-privacy/unauthorized-use-of-automated-or-bulk-messaging-on-whatsapp/?lang=en) and this [white paper](https://scontent.whatsapp.net/v/t61.22868-34/69510151_652112781951150_6923638360331596993_n.pdf/Stopping-Abuse-white-paper.pdf?ccb=1-3&_nc_sid=2fbf2a&_nc_ohc=L-Xdw3LDI68AX_G5bOt&_nc_ht=scontent.whatsapp.net&oh=971abb195a2cd607f463dfbcadfe65f8&oe=605B6E4F) and I'm very afraid

**Comment by smashah** [comment]
@lfilipe09 I am not a lawyer so cannot advise on what is or isn't within their TOS. That aside, everybody uses this library at their own risk.

Bulk messaging/spam and abusive behaviour are most likely to result in people reporting your account leading to a ban. It is against the license of this library also.

You are actually not able to send bulk messages through this library as it is, specifically to protect users of this library from unwanted attention.

> And in my case this chatbot would bring such good things for the community I am working for

The library is used for many projects to do positive things. For example, one project has built a track & trace system and another has built a project to serve a minority community and keep them safe. I highly encourage you to try out the library and if you're concerned about implication then consider that Zuck and the gang have done nothing to stop Whatsapp from being used to spread fake news which has directly been implicated in hate murders, genocides and the rise of fascism. So I'm sure your use case shouldn't raise any eyebrows.

Thanks. please join the discord (click the discord badge in the readme) to discuss this further.
