### ISSUE TITLE
how to send image  and let receiver get preview instead of download the image?

### ISSUE THREAD

**Issue by the-jojo-jj** [open-wa/wa-automate-nodejs#1518]
confusing with sendimage and sendfile endpoint. 
how to send image and let receiver get image preview instead of downloadind the image?

**Comment by smashah** [comment]
@the-jojo-jj please show the request you're making to the endpoint

**Comment by the-jojo-jj** [comment]
both localpath file and base64 doesn't work.

curl --location --request POST 'https://xxx.xxxxx.xx/v01/wa/jxxxxx/sendImage' \
--header 'api_key: 46xxxxxx1a9bfcbxxxxx' \
--header 'Content-Type: application/json' \
--header 'Cookie: __cfduid=d0c50ae364cc9f288f8e6f02aacc7816e1616313290' \
--data-raw '{
  "args": {
    "to": "62822191xxxxx@c.us",
    "file": "https://labs.xxxxxx.info/media/qris-jagoan-small.jpg",
    "filename": "qris-jagoan-small.jpg",
    "caption": "Hello",
    "quotedMsgId": "false_447123xxxxxx@c.us_xxxxx965EA5C0xxxxx334ABxxxxx7FEB",
    "waitForId": "boolean",
    "ptt": "boolean",
    "withoutPreview": "boolean",
    "hideTags": "boolean"
  }
}'

**Comment by smashah** [comment]
You need to remove the placeholder/example properties in the JSON body

```
    "quotedMsgId": "false_447123xxxxxx@c.us_xxxxx965EA5C0xxxxx334ABxxxxx7FEB",
    "waitForId": "boolean",
    "ptt": "boolean",
    "withoutPreview": "boolean",
    "hideTags": "boolean"
```

when you send `"withoutPreview": "boolean"` it resolves to `"withoutPreview": true` because a non null string resolves to true.

Don't send unnecessary data to the endpoint.

**Comment by the-jojo-jj** [comment]
hi @smashah thanks again for your reply.
but, can i send image more than 100x100 ?
we need it to send qrcode. 

thanks

**Comment by smashah** [comment]
@the-jojo-jj any file you can send via the web client itself should be able to be sent via these endpoints. Please click on the discord badge in the readme and discuss these small issues there thanks
