### ISSUE TITLE
**ERROR** Failed to apply patch for package swagger-stats at path

### ISSUE THREAD

**Issue by sakthimj** [open-wa/wa-automate-nodejs#1524]
Hello,

I try to run "npx @open-wa/wa-automate", But i Have some error,
![screenshot](https://user-images.githubusercontent.com/18246843/112614478-54b67d00-8e47-11eb-8bba-dd2780df639b.png)

Kindly help to resolve this error

**Comment by smashah** [comment]
hi @sakthimj 

I will fix this asap

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.9.16](https://github.com/open-wa/wa-automate-nodejs/compare/3.9.15...3.9.16) (2021-03-26)

- build(deps-dev): bump @types/node from 14.14.35 to 14.14.36 [`#1522`](https://github.com/open-wa/wa-automate-nodejs/pull/1522)
- build(deps): bump @types/sharp from 0.27.1 to 0.27.2 [`#1523`](https://github.com/open-wa/wa-automate-nodejs/pull/1523)
- build(deps-dev): bump typedoc from 0.20.33 to 0.20.34 [`#1521`](https://github.com/open-wa/wa-automate-nodejs/pull/1521)
- Release 3.9.16 [`d0e6683`](https://github.com/open-wa/wa-automate-nodejs/commit/d0e6683e347497f5cb1214326ae91fe7f6b24cf6)
- ⬆️  update swagger-stats patch #1524 [`1bedf83`](https://github.com/open-wa/wa-automate-nodejs/commit/1bedf8326223cc78d73fbd914520bf06b212bd85)
- 🥚  patch update [`f000936`](https://github.com/open-wa/wa-automate-nodejs/commit/f0009362d902436be5a146b62ed94f9b3bb820ba)
- 🥚 patch update [`fe40b0b`](https://github.com/open-wa/wa-automate-nodejs/commit/fe40b0b44d478a04da23585f6eedbfc37fefc0fd)

**Comment by smashah** [comment]
@sakthimj can you try again with:

```bash
> npx @open-wa/wa-automate@latest
```

P.S

You can save a cached version of the CLI by installing it in your working directory. This way it doesn't download everything every time:


```bash
# downloads everything
> npx @open-wa/wa-automate@latest

# downloads everything again
> npx @open-wa/wa-automate@latest
```

vs.

```bash
# install once
> npm i @open-wa/wa-automate@latest

# starts instantly
> npx @open-wa/wa-automate@latest

# starts instantly
> npx @open-wa/wa-automate@latest
```

**Comment by shabbir135** [comment]
> Hello,
> 
> I try to run "npx @open-wa/wa-automate", But i Have some error,
> ![screenshot](https://user-images.githubusercontent.com/18246843/112614478-54b67d00-8e47-11eb-8bba-dd2780df639b.png)
> 
> Kindly help to resolve this error

**Comment by shabbir135** [comment]
@sakthimj bro ran up with the same issue, Put node at version 14.16.0 and npm and ngx version to 7.6.1 fixed the issue. Thanks

**Comment by sakthimj** [comment]
Hi ,

Still I have some error, Kindly guide me,

![screenshot](https://user-images.githubusercontent.com/18246843/112710262-b88f8300-8ee5-11eb-89ad-9841293a1255.png)

**Comment by smashah** [comment]
@sakthimj try this in your directory

```bash
> npm i prom-client
```

Then try to run the npx command again

**Comment by sakthimj** [comment]
@smashah i have try this code many time still i have same error,
![screenshot](https://user-images.githubusercontent.com/18246843/112710864-3eadc880-8eea-11eb-99a4-7705a8aea11c.png)

**Comment by smashah** [comment]
Did you try installing locally then running as laid out in this comment?

https://github.com/open-wa/wa-automate-nodejs/issues/1524#issuecomment-808129783

**Comment by sakthimj** [comment]
When i try to use above code i have received some other error.
![screenshot](https://user-images.githubusercontent.com/18246843/112710960-e3300a80-8eea-11eb-9e7b-f001923026c2.png)

**Comment by smashah** [comment]
@sakthimj you're not able to install a dependency that has the same name as the working directory. Change the name of your directory and try again

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.10.2](https://github.com/open-wa/wa-automate-nodejs/compare/3.10.1...3.10.2) (2021-03-28)

- Release 3.10.2 [`71812d3`](https://github.com/open-wa/wa-automate-nodejs/commit/71812d3fa92cf569e3931ed3321cabe65d839447)
- 🐛  prevent prom-client issue by lazy loading stats #1524 [`4fc0e19`](https://github.com/open-wa/wa-automate-nodejs/commit/4fc0e19c7ab856c9638a022e1fb5ba66278973be)
- ✨ set `circle:true` to `stickerMetadata` for a circluar sticker! #1530 [`aa50990`](https://github.com/open-wa/wa-automate-nodejs/commit/aa509901aaec122310f8a4545fd37f8af86f5175)
