### ISSUE TITLE
deleteSessionDataOnLogout config problem

### ISSUE THREAD

**Issue by suariana** [open-wa/wa-automate-nodejs#1538]
hi, I have set the config deleteSessionDataOnLogout true, but after logging out from device, the session file is still not deleted..

![image](https://user-images.githubusercontent.com/47437771/112930567-1d98e200-914d-11eb-97a3-52a4828dcf38.png)

![image](https://user-images.githubusercontent.com/47437771/112930674-52a53480-914d-11eb-9d26-942473a6baf7.png)

**Comment by smashah** [comment]
- [ ] fix deleteSessionDataOnLogout
- [ ] Implement `config.returnFalseIfLaunchLoggedOut`
- [ ] Implement `config.killClientOnLogOut`
- [ ] Set eventMode to `true` by default

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.10.5](https://github.com/open-wa/wa-automate-nodejs/compare/3.10.4...3.10.5) (2021-03-30)

- Release 3.10.5 [`6b1337c`](https://github.com/open-wa/wa-automate-nodejs/commit/6b1337c0f1956a6bb01ecf1a0c545d8eba867ce1)
- ♻️ refactor session data filepath detection #1538 [`aa01346`](https://github.com/open-wa/wa-automate-nodejs/commit/aa01346098be21c5ff14d3832e613da3e31f5dfd)
- ✨ feat: implemented `client.getLastMsgTimestamps` [`90f697a`](https://github.com/open-wa/wa-automate-nodejs/commit/90f697a471c7d234a9bafd2b8ca5d564cc14def1)
- 🔧 config: Implemented `throwOnExpiredSessionData` #1538 [`7bdc0cc`](https://github.com/open-wa/wa-automate-nodejs/commit/7bdc0cca29a00254cfca5d00684fdb72964152e9)
- 🔧 config: Implemented `killClientOnLogout` and fix `deleteSessionDataOnLogout` #1538 [`cf59db9`](https://github.com/open-wa/wa-automate-nodejs/commit/cf59db9ff4ae5474f07f6b8770ee5209646150b0)
- 🔧 config: Implemented `useNativeProxy` [`1e7e289`](https://github.com/open-wa/wa-automate-nodejs/commit/1e7e289dd55857329178b71883c36bbedc880b9f)
- ✨ feat: `client.onLogout` #1538 [`89a6ce9`](https://github.com/open-wa/wa-automate-nodejs/commit/89a6ce93cf61a46c0b80131b3650326a367321b9)
- 🔊 launch: logs session data file detection info [`8deb131`](https://github.com/open-wa/wa-automate-nodejs/commit/8deb1314f02e3ab97754ad3a44e301d5a84b85a3)
- 🔊 launch: logs when QR code is scanned [`55dcc77`](https://github.com/open-wa/wa-automate-nodejs/commit/55dcc7703cda5b89198a4bb5c8aa7470f32b3b25)
- 📝  added docs for `onLogout` [`23f3fa8`](https://github.com/open-wa/wa-automate-nodejs/commit/23f3fa8d91ff76e7353f6bd4203d154c4ea45054)
- config: `eventMode` is now `true` by default #1538 [`a172858`](https://github.com/open-wa/wa-automate-nodejs/commit/a172858e64e53116384790e05154003f1e3b7243)

**Comment by suariana** [comment]
hi, i wanna ask, when i run my project in vps, i got this error, but working properly in local computer, how can i solve it?
i already use the latest update
thankyou

![image](https://user-images.githubusercontent.com/47437771/113117857-734eb680-9241-11eb-82d1-4c4d6eac20fc.png)

**Comment by smashah** [comment]
@suariana I think you're running an old version of node/npm

Please make sure you're running a recent version of node as indicated in the readme badge:

![image](https://user-images.githubusercontent.com/5903821/113225700-2b05b780-9286-11eb-8d90-a63b44d3036a.png)

**Comment by suariana** [comment]
i already update node version in vps and it's work, thankyou :)
