### ISSUE TITLE
CLI: allow setting of `ev` namespace filter

### ISSUE THREAD

**Issue by dudanogueira** [open-wa/wa-automate-nodejs#1546]
Is it possible to send the qrcode to the webhook? Maybe an cli option.

My usecase is that I have an endpoint to provide as webhook, and when receiving the qrcode it will send it using the chat platform to the corresponding manager to authenticate.

As of right now, I was not able to get the qrcode from the easyapi (has not worked for me) and the webhook receives no indication that the qrcode is available.

Thanks!!

**Comment by smashah** [comment]
@dudanogueira have you tried using the `-e` (or `--ev` both do the same thing) flag?

**Comment by smashah** [comment]
```
npx @open-wa/wa-automate --session-id qrtest -e https://webhook.site/e4f7c0df-e6f4-4c0b-9415-d6b942b091a2
```

will send launch events including the QR code to that URL.

Check out the webhook data here: https://webhook.site/#!/e4f7c0df-e6f4-4c0b-9415-d6b942b091a2/024e7ad1-95a5-452d-a537-e18858f5907d/1

**Comment by dudanogueira** [comment]
Oh! I see!! you need to pass the hook again. It was not clear to me. Thanks!!

The -e flag is too much verbose, it would be nice to be able to filter the outgoing namespaces, something like
-e 'http://myhook.site' -ef 'qr,STARTUP'

or, for me it would be: -ef 'qr'

if not -ef (event filter) by defualt, show all.

But I can work with that for now, thanks!

**Comment by smashah** [comment]
Good idea

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.10.8](https://github.com/open-wa/wa-automate-nodejs/compare/3.10.7...3.10.8) (2021-04-05)

- build(deps-dev): bump typedoc from 0.20.34 to 0.20.35 [`#1557`](https://github.com/open-wa/wa-automate-nodejs/pull/1557)
- build(deps): bump swagger-stats from 0.95.19 to 0.99.1 [`#1558`](https://github.com/open-wa/wa-automate-nodejs/pull/1558)
- build(deps): bump open from 8.0.4 to 8.0.5 [`#1559`](https://github.com/open-wa/wa-automate-nodejs/pull/1559)
- build(deps): bump ts-json-schema-generator from 0.89.1 to 0.89.2 [`#1560`](https://github.com/open-wa/wa-automate-nodejs/pull/1560)
- 🥚  fixes #1555 [`#1555`](https://github.com/open-wa/wa-automate-nodejs/issues/1555)
- Release 3.10.8 [`f3d65a6`](https://github.com/open-wa/wa-automate-nodejs/commit/f3d65a600da058110f560797457e101d263c67c9)
- ✨ [CLI] feat: set namespace filters with `--ef` #1546 [`03e5648`](https://github.com/open-wa/wa-automate-nodejs/commit/03e564874803ff893a39b5cd12d1375a9a4c41b6)
- 🥚 patch fix for #1556 [`5dc44b0`](https://github.com/open-wa/wa-automate-nodejs/commit/5dc44b04f480ccbc2d6fb1b8c05e87a083366040)

**Comment by smashah** [comment]
@dudanogueira you can now set namespace filters like so:

```npx @open-wa/wa-automate --ev EV_WEBHOOK_URL --ef qr --ef STARTUP```

or


```npx @open-wa/wa-automate --ev EV_WEBHOOK_URL --ef qr,STARTUP```

or

```npx @open-wa/wa-automate --ev EV_WEBHOOK_URL --ef qr```

or you can use a `cli.config.json` and set it as an array or string. For example:

```javascript
{
    "headful": true,
    "disableSpins": true,
    "webhook": [{
        "url": "WEBHOOK_ADDRESS_1",
        "events": ["onPlugged", "onAck"]
    },
    {
        "url": "WEBHOOK_ADDRESS_2",
        "events": "onAnyMessage"
    }],
    "ef":[
        "qr",
        "startup"
    ]
	//or
	"ef":"qr,STARTUP"
	//or
	"ef":"qr"
}
```

with this specific `cli.config.json`, the only thing missing is the ev webhook address

so then you run:

```npx @open-wa/wa-automate --ev EV_WEBHOOK_URL```

or, you can set the `EV_WEBHOOK_URL` in the cli.config.json itself:

```javascript
...
	"ev":"EV_WEBHOOK_URL",
...
```

**Comment by dudanogueira** [comment]
That's awesome!!

For the sake of retro compatibility, while providing -ev and not providing -ef should be the same of --ef qr,STARTUP

One really cool feature, and not documented, was this cli.config.json with the filtering possibilities.

Also, I didn't notice it generated a index.js file with all that. 

It's really impressive. This library is amazing. Congratulations. 

I am developing a solution using it, and hopefully and happily  will be able to acquire some licenses when the time comes.

Thanks!

**Comment by smashah** [comment]
> For the sake of retro compatibility, while providing -ev and not providing -ef should be the same of --ef qr,STARTUP

That should already be the case. Let me know if you're experiencing otherwise.

> One really cool feature, and not documented, was this cli.config.json with the filtering possibilities.

I will be concentrating on better documentation after V4 is released.

> Also, I didn't notice it generated a index.js file with all that.

The CLI generates an index.js file for you? It shouldn't be doing that, can you explain further please.

> It's really impressive. This library is amazing. Congratulations.

> I am developing a solution using it, and hopefully and happily will be able to acquire some licenses when the time comes.

Amazing! Thank you!
