### ISSUE TITLE
SimpleListener: onAnyMessage didn't work while eventMode is set to true

### ISSUE THREAD

**Issue by Waxaranai** [open-wa/wa-automate-nodejs#1555]
**Describe the bug**
`onAnyMessage` didn't work while `eventMode` at the `CreateConfig` is set to `true`

**Steps to Reproduce**
1. Update to the latest version
2. Create a `onAnyMessage` event
3. Try logging the event
4. Observe

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**
The event should emitted a message

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: "2.2110.12",
  PAGE_UA: "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  WA_AUTOMATE_VERSION: "3.10.7",
  BROWSER_VERSION: "HeadlessChrome/89.0.4389.114"
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Android

**Additional context**
By disabling the `eventMode` the event is working

**Comment by gnadelwartz** [comment]
may related to my Problem not getting messages with onAnyMessage https://github.com/open-wa/wa-automate-nodejs/issues/1266#issuecomment-812981931 after update to 3.10.7

**Comment by smashah** [comment]
@gnadelwartz @Waxaranai should be working now with patches. This issue is a weird relic from the first setup of onAnyMessage. Basically, the fix was to return `true` when the listener is set in the browser instead of the internal wa web event listener object. Weird error with an easy fix.
