### ISSUE TITLE
EASYAPI -> Generate QR After Logout

### ISSUE THREAD

**Issue by dudanogueira** [open-wa/wa-automate-nodejs#1571]
**Describe the bug**
It would be nice to have the EasyAPI to loop when the user logout from the device. Right Now I receive the onLogout Event, and also the onStateChanged with data OPENING, but that's it. While opening the EasyApi with headful true, I can see the browser comes back to the qr code page at Whatsapp, but the QR is not fired thru webhook.

Is there some options that does it?

**Steps to Reproduce**
1. run the EasyApi: npx @open-wa/wa-automate
2. scan the qr code at terminal
3. logout at device
4. no qr code at terminal

**Expected behavior**
Qr Code should be showing at the terminal and be fired for the webhook

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug info: {
"WA_VERSION": "2.2112.10",
"PAGE_UA": "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
"WA_AUTOMATE_VERSION": "3.10.10",
"BROWSER_VERSION": "Chrome/90.0.4427.0",
"OS": "Linux 5.4",
"START_TS": 1617904867136
}
```

**Host (please complete the following information):**
 - Android

**Comment by smashah** [comment]
hey @dudanogueira sorry for leaving this for a long time.

Automatically getting the QR code and starting from scratch isn't really supported behaviour and I can foresee many issues coming up with this, so I would suggest just restarting the process when you detect a logout event. Or calling `create` manually upon logout.

For example

```javascript
...

const options = {
	...
}

async function start(client) {

	...
	
	client.onLogout(_=>{
		return create({
		...options,
		sessionData: "NUKE" // This explicitly tells the library to get a new QR code instead of waiting for it to automatically detect it. saves some time.
		}).then(start)
	})

}


create(options).then(start)
```

Hope that sorts it out for you.

Thanks

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.11.3](https://github.com/open-wa/wa-automate-nodejs/compare/3.11.2...3.11.3) (2021-04-20)

- Release 3.11.3 [`99a7bb6`](https://github.com/open-wa/wa-automate-nodejs/commit/99a7bb6c390fc645333e07357bfd14f3769043fb)
- 💥 feat/breaking [CLI]: `-c` flag now refers to file (or base64 json string) of ALL cli config, not just session config #1595 [`2806650`](https://github.com/open-wa/wa-automate-nodejs/commit/280665005f32d6f3f5b2946c3b6d36530382af71)
- 🚩 cli-flag: `--no-kill-on-logout` (default `false`) #1571 [`8e2ebe9`](https://github.com/open-wa/wa-automate-nodejs/commit/8e2ebe90bab52472da63893b7951700663e7d9fd)
- 👷 dev: ignore patch updates from changelogs #1597 [`e5c27bf`](https://github.com/open-wa/wa-automate-nodejs/commit/e5c27bfdf76347f05053543be28f4db8d08de2c8)
- 🥚 patches update [`4cbb023`](https://github.com/open-wa/wa-automate-nodejs/commit/4cbb023fa471a7b058e30700008e59150a5d734b)
- 🥚 patches update [`267d3c4`](https://github.com/open-wa/wa-automate-nodejs/commit/267d3c43d7cbc8e0ad048a0838fc17a0cdef5eef)

**Comment by smashah** [comment]
@dudanogueira the CLI now, by default kills the process when the host account logs out from the session.

You can use something like forever, pm2 or nodemon to restart the process to get a new QR code.

I tried implementing the restart within the process itself but it's not feasible due to memory leak concerns.

thanks
