### ISSUE TITLE
Error when replying image message sent by myself

### ISSUE THREAD

**Issue by guilhermebkel** [open-wa/wa-automate-nodejs#1589]
**Describe the bug**
Right after sending a image message and replying it I've got an error. After restarting the session and attempting to reply the image message again, it works like a charm.

**Steps to Reproduce**
```js
const messageId = await client.sendFile(userId, imageBase64, "image.png", null, null, true, false)

const replyMessageId = await client.reply(userId, "image reply", messageId)

console.log(replyMessageId) // ERROR: Something went wrong while trying to send the message: ERROR_UNKNOWN
```

**Expected behavior**
Since right after sending file message (per example: video, text, audio, voice) and replying it, everything works fine, it was expected to be the same with image message.

**DEBUG INFO**
```
Debug Info {
  "WA_VERSION": "2.2112.10",
  "PAGE_UA": "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "3.10.13 UPDATE AVAILABLE: 3.10.15",
  "BROWSER_VERSION": "HeadlessChrome/90.0.4427.0",
  "OS": "Linux 5.4",
  "START_TS": 1618515091968
}
```

**Comment by smashah** [comment]
@guilhermebkel can you add a caption  to the image and try again. That, for some reason, is fixing it for me.

**Comment by smashah** [comment]
@guilhermebkel this is happening because the caption is `null`, if it was `undefined` it would work fine. I will submit a patch that will convert any caption to `undefined` if `null` is provided.

**Comment by smashah** [comment]
This should be patched now. Please restart your sessions and try again, let me know if it keeps happening. thanks

**Comment by guilhermebkel** [comment]
@smashah Got it! I just tested and it worked like a charm, thanks!
