### ISSUE TITLE
addLabel: create new label if doesn't exist

### ISSUE THREAD

**Issue by rickricardo** [open-wa/wa-automate-nodejs#1591]
Hi, when I use the addLabel() function sending a label name that was not created yet, nothing happens.
Is it possible to add a parameter in the function that, if set to True, create the label if it doesn't exist and then label the chat/message/contact?

**Comment by smashah** [comment]
@rickricardo this has been implemented in v3.11.0 as an insider's feature. Please DM me on discord. thanks
