### ISSUE TITLE
AddParticipant return ADD_BLOCKED

### ISSUE THREAD

**Issue by pe77** [open-wa/wa-automate-nodejs#1606]
**Describe the bug**
When I add a participant to a group it returns: ADD_BLOCKED. I not found what this could mean. These users are in the contact list, are not blocked and have no privacy block to add to groups.

The biggest problem is that when I start the service, it can work or not. It looks like it's some problem related to the session, maybe. Because when I start the service, if it works, it will continue to work as long as the session is open. If it doesn't work, it will still not work as long as the session is open.

**Steps to Reproduce**
I cannot consistently reproduce. Sometimes when I restart the service it always works, but eventually, in some other restart this error always happens

**create() code**
```javascript
var addResult = await client.addParticipant(groupId, userId);
```

**Expected behavior**
add participant to a group

**DEBUG INFO**

```
ADD_PARTICIPANTS_ERROR: ADD_BLOCKED
    at Client.<anonymous> (D:\p\services\project\current\node_modules\@open-wa\wa-automate\dist\api\Client.js:2289:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\p\services\project\current\node_modules\@open-wa\wa-automate\dist\api\Client.js:24:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  data: undefined
```

**Comment by smashah** [comment]
@pe77 when you get `ADD_BLOCKED` it means there was an unexpected error while adding the participant. Now, this can be for a number of different reasons. In order to figure out what's going on, I'll forward the error via a patch so we can see what's the error actually is.

**Comment by smashah** [comment]
@pe77 please try again and check what the error is now. it should show some more information

**Comment by pe77** [comment]
okay. I will apply the patch and come back with the answer as soon as it happens again.

Thanks

**Comment by smashah** [comment]
@pe77 do you have more information on the error?

**Comment by smashah** [comment]
Closing.

Thanks
