### ISSUE TITLE
onStateChanged going crazy on block/unblock someone

### ISSUE THREAD

**Issue by victorsouzaleal** [open-wa/wa-automate-nodejs#1610]
After making a block or unblock, onStateChanged starts to switch between TIMEOUT and CONNECTED

```js
client.onStateChanged(state => {
     console.log('[STATE]', state)
})
```

![image](https://user-images.githubusercontent.com/4674786/115977198-2f9f5200-a54c-11eb-8561-061445c181fc.png)

**Comment by smashah** [comment]
hey @victorsouzaleal I've been keeping an eye on this over the past week. It seems like this is a WA issue. If you run the library with `headless: false` then manually block someone, it still causes state to bounce between `TIMEOUT` and `CONNECTED`.

I notice this state-bounce during the development of new features. It occurs when socket payloads between the web instance and mobile app are 'broken' in some way. The problem always occurs when I am working on some sort of custom payload but this is the first time I'm witnessing it through interaction with the native web interface itself, so I have to assume this is a bug from WA.

I'll close this for now but I will check up on this over the next few weeks.

thanks
