### ISSUE TITLE
.iAmAdmin returning an array of null

### ISSUE THREAD

**Issue by DaviZMelo** [open-wa/wa-automate-nodejs#1624]
**Describe the bug**
The .iAmAdmin () function is returning an array of nulls

**Steps to Reproduce**
1 - Use the .iAmAdmin Client function.

**create() code**
This is the code you use to create the client. e.g
```javascript
    const createdInstance = await create({
      logConsole: false,
      disableSpins: true,
      blockCrashLogs: true,
      useChrome: true,
      callTimeout: 0,
      headless: false,
    });
```

**Expected behavior**
I hope it returns an ids array

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: "2.2114.9",
  PAGE_UA: "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"",
  WA_AUTOMATE_VERSION: "3.11.6",
  BROWSER_VERSION: "Chrome/90.0.4430.93",
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots
![image](https://user-images.githubusercontent.com/49699162/116624231-f71dc080-a91d-11eb-81c7-6c59b7624ff6.png)

**Host (please complete the following information):**
 - OS: Android 10

**Additional context**
x

**Comment by smashah** [comment]
@DaviZMelo thanks for filling out the issue template. should be fixed now
