### ISSUE TITLE
sendVideoAsGif and sendGiphy don't work as they should

### ISSUE THREAD

**Issue by oMrRexD** [open-wa/wa-automate-nodejs#1628]
**Describe the bug**
I'm trying to send a video as a gif using "sendVideoAsGif", but it still sends the file as a video, not a gif. I tried to use the "sendGiphy" example that is in the documentation, but it also returned a video.

**Steps to Reproduce**
```javascript
  const from = "xyz@c.us"
  const randomVideo = "https://cdn.discordapp.com/attachments/685501923314368513/837698000565960704/WhatsApp_Video_2021-04-19_at_15.23.35.mp4"

  await client.sendVideoAsGif(from, randomVideo, 'random.mp4')
  await client.sendGiphy('xyz@c.us','https://media.giphy.com/media/oYtVHSxngR3lC/giphy.gif', `Hello this is the caption`);
```
**Screenshots**
<img src="https://cdn.discordapp.com/attachments/685501923314368513/837710568122875964/unknown.png" width="250px">

**create() code**
```javascript
const settings = {
  sessionId: 'Skye',
  headless: true,
  qrTimeout: 0,
  authTimeout: 0,
  cacheEnabled: false,
  useChrome: true,
  killProcessOnBrowserClose: true,
  throwErrorOnTosBlock: false,
  chromiumArgs: [
    '--no-sandbox',
    '--disable-setuid-sandbox',
    '--aggressive-cache-discard',
    '--disable-cache',
    '--disable-application-cache',
    '--disable-offline-load-stale-cache',
    '--disk-cache-size=0'
  ]
}
create(settings).then((client) => start(client))
```

**Expected behavior**
Well, I expected the bot to send the file as a gif on WhatsApp, like this screenshot here:
<img src="https://cdn.discordapp.com/attachments/685501923314368513/837715825200726033/unknown.png" width="250px">
**DEBUG INFO**
```
Debug Info {
  WA_VERSION: '2.2114.9'
  PAGE_UA: 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
  WA_AUTOMATE_VERSION: '3.11.6'
  BROWSER_VERSION: 'HeadlessChrome/90.0.4430.93'
}
```

**Host (please complete the following information):**
 - OS: Windows 10

**Comment by smashah** [comment]
@oMrRexD thanks for filling out the issue template perfectly.

This should be fixed in the latest patch update.

thanks
