### ISSUE TITLE
I am trying to send sticker from image and it does not upload on phone since a while.

### ISSUE THREAD

**Issue by ParthThakkar08** [open-wa/wa-automate-nodejs#1631]
I am trying to send sticker from image and it does not upload on phone since a while, Also If I have received the same image in sticker before it works properly but 
not for new stickers.

![Capture](https://user-images.githubusercontent.com/75181936/116786766-181d1780-aabe-11eb-9105-d76a124122d1.PNG)

**Comment by smashah** [comment]
hey @ParthThakkar08 can you please fill in the issue template so we can get this resolved asap. thanks

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
