### ISSUE TITLE
Navigation Timeout

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#1636]
As elusive as this issue is, there should at least be some diagnostics/retries when a navigation timeout is anticipated.

This can be inferred from intercepting network requests and receiving no response within a certain time frame.

**Comment by guilhermebkel** [comment]
Hey @smashah, I just randomly got able to reproduce that error locally, being honest I don't know how I did it, but there are some infos I can show:

**My shell:**
```
- Starting
- Version: 3.12.0
- Initializing WA
- Launching Browser
- Setting Up Browser
- Loading session data
- No session data file found for session : session
- Existing session data detected. Injecting...
- Existing session data injected
- Navigating to WA
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /ssd/Workspace/picsize/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.navigateFrame (/ssd/Workspace/picsize/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/ssd/Workspace/picsize/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:416:16)
    at async Page.goto (/ssd/Workspace/picsize/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:819:16)
```

**My screenshot before the error:**
![image](https://user-images.githubusercontent.com/42042433/117346015-96423b00-ae7d-11eb-903d-a464fcee2748.png)

**My screenshot some seconds after the error happened:**
![image](https://user-images.githubusercontent.com/42042433/117346112-b8d45400-ae7d-11eb-8479-fdaaa51469f9.png)

**My memory info:**
```
➜  free
              total        used        free      shared  buff/cache   available
Mem:       18373840    15772260      252592      379176     2348988     1699616
Swap:       2097148     1039616     1057532
```

It looks like the timeout error is triggered but after some time the page is able to load the Whatsapp Web page (so even after this error is triggered the page does not even close itself) 🤔

**Comment by guilhermebkel** [comment]
Other info:

My Disk Memory is almost completely full, so I have got the error below when trying to execute the lib:

```
[Error: ENOSPC: no space left on device, mkdtemp '/tmp/puppeteer_dev_chrome_profile-i17Twc'] {
  errno: -28,
  code: 'ENOSPC',
  syscall: 'mkdtemp',
  path: '/tmp/puppeteer_dev_chrome_profile-i17Twc'
}
```

Maybe the timeout error came from that out of space issue 🤔

**Comment by smashah** [comment]
@guilhermebkel lack of memory would make sense as it would wait for a garbage collection before loading the page. How many sessions were you running that resulted in this lack of space?

During normal operation, the logs show "Navigating to WA" for a few seconds at the most. I'm thinking to restart the process if it takes more than 5+ seconds. At least that way, the library can try again 12 times in the same time it would take to cause the navigation timeout. What do you think?

**Comment by guilhermebkel** [comment]
@smashah Actually that was a lack of *ram memory* and *disk space* and I feel the same about the garbage collection. I was running a single session (the lack of ram memory was caused due to a lot of applications I was running at the same time).

About killing the process, do you mean like putting a timeout and a retry count before assuming that the session failed to start? (when dealing with Navigation Timeout error)

**Comment by smashah** [comment]
@guilhermebkel I have a few suggestions

1. Cycle randomly between multiple user agents for each invocation of `create`
2. Try to set [`useStealth: true`](https://docs.openwa.dev/interfaces/api_model_config.configobject.html#usestealth) in the config object:
3. Make a function that randomly sets the width and height of the window via [`viewport`](https://docs.openwa.dev/interfaces/api_model_config.configobject.html#viewport)

**Comment by guilhermebkel** [comment]
@smashah Thanks for the suggestions, I'll try it out!

About the first suggestion, I'm thinking about using the User Agent provided by the user that is trying to create a session (since he usually makes a request to create a session, I'm able to get its User Agent), is there any problem with that?

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by guilhermebkel** [comment]
@smashah Interesting result! Now since you wrapped the **goTo** method with a try/catch to treat it, the browser will close after this error happens? (I've seen that you added some metrics about the load as well)

**Comment by smashah** [comment]
@guilhermebkel It doesn't throw the error. I will add that back into the code for the next release.

The extra metrics should give us more of an idea of what isn't and what is normal behaviour (specifically page launch times). The library will also dump all response headers if the page load status is not 200. Hopefully the next time this issue comes up with someone, they will provide more useful logs.

**Comment by guilhermebkel** [comment]
@smashah Got it!

**Comment by smashah** [comment]
The error is now thrown. I will close this issue for now until someone else brings it up

**Comment by smashah** [comment]
Bypassing the service worker should fix this? If it doesn't then I can implement some sort of open-wa specific CDN for the latest wa files

**Comment by smashah** [comment]
This should not happen as much on https://github.com/open-wa/wa-automate-nodejs/releases/tag/4.31.0
