### ISSUE TITLE
Error when using the "reply" option

### ISSUE THREAD

**Issue by GladistonXD** [open-wa/wa-automate-nodejs#1645]
When starting the scripts everything works normally

But after a few hours of running it displays this error message:

**ERROR: PLEASE MAKE SURE YOU HAVE SENT AT LEAST ONE REPLY MESSAGE MANUALLY USING THIS ACCOUNT.**

Returns to normal after stopping the script and starting again.

**Comment by smashah** [comment]
hi @GladistonXD,

are you using `client.cutChatCache()` or `client.cutMsgCache()` in your code?

**Comment by GladistonXD** [comment]
if (msg >= 1000) {
      client.cutMsgCache()
}

Use to clear the cache every 1000 msg, if I decrease this flow, does this solve the problem?

**Comment by GladistonXD** [comment]
Yes I use client.cutMsgCache () to clean every 1000 messages, I tested and saw that the problem was this, after 1000 it stopped working, thanks, congratulations for the library

**Comment by smashah** [comment]
@GladistonXD try with `cutChatCache` instead for now. I will check what's going on with `cutMsgCache`
