### ISSUE TITLE
Duplicate sticker after responding to an image.

### ISSUE THREAD

**Issue by GladistonXD** [open-wa/wa-automate-nodejs#1663]
I don't know if this is a bug, or an error in my programming, but I couldn't find a solution using "sendImageAsSticker" always duplicates the replied image with the same initial image

<a href="https://raw.githubusercontent.com/GladistonXD/teste.txt/master/Exemple"><img src="https://raw.githubusercontent.com/GladistonXD/teste.txt/master/Exemple.gif" title="Exemple"/></a>

**Comment by smashah** [comment]
Hey @GladistonXD I've done some testing on this. I'm pretty sure this is only happening to you on your code.

If this continues to happen, please ask for help in the #javascript channel and someone will help you figure this one out.

thanks

**Comment by GladistonXD** [comment]
Okay, thanks
