### ISSUE TITLE
Error: Evaluation failed: f

### ISSUE THREAD

**Issue by oMrRexD** [open-wa/wa-automate-nodejs#1667]
**Describe the bug**

When many people use the bot, Puppeteer starts to have problems until the application crashes, and I have no idea what's going on.
<img src="https://cdn.discordapp.com/attachments/685501923314368513/842045281163280414/unknown.png" width="70%">

**create() code**
```javascript
const settings = {
  sessionId: 'Skye',
  headless: true,
  cacheEnabled: false,
  useChrome: true,
  killProcessOnBrowserClose: true,
  throwErrorOnTosBlock: false,
  chromiumArgs: [
    '--no-sandbox',
    '--disable-setuid-sandbox',
    '--aggressive-cache-discard',
    '--disable-cache',
    '--disable-application-cache',
    '--disable-offline-load-stale-cache',
    '--disk-cache-size=0'
  ]
}
create(settings).then((client) => start(client))
```

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2117.5',
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
  BROWSER_VERSION: 'HeadlessChrome/90.0.4430.212'
}
```
**Additional context**
It starts to give problems randomly, sometimes it takes 1 hour, other times it gives an error with only 2 minutes

**Comment by smashah** [comment]
hi @oMrRexD there's not enough detail here to figure out what's going on.

do you have any more info on this?

I would firstly suggest to remove all of those chrome args.

**Comment by smashah** [comment]
Let me know if this keeps happening.

Closing

Thanks
