### ISSUE TITLE
Big JSON with b64 content

### ISSUE THREAD

**Issue by paulocorcino** [open-wa/wa-automate-nodejs#1669]
**Describe the bug**
I'm started tests with Easy API with a proposal to change my legacy API support, so I'm analyzing the result received with the webhook event, I saw that a message with binary (image or video) on JSON has twice b64 on code, on the "body" and on the "content". How I work with Java is very complicated to work with this big string on Java memory heap.

**Steps to Reproduce**
1. Start Easy API
2. Receive a message "onMessage" or "onAnyMessage" with image, video or any binary content.

**create() code**
N/A

**Expected behavior**
I have 2 proposal, but the first solved my problem.

1. Create an option on Config when I choose which attribute return the base64, on the body or the content. But, how has people that still use  these ways, I will recommend that if someone not defines this configuration keep behavior.

2. Not return base64 on the JSON, but a file URL where is possible download, after with an API call for download and decrypt file return base64.

**DEBUG INFO**
```
Debug Info {
  WA_VERSION: 2.2117.5,
  PAGE_UA: WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) 
 Chrome/89.0.4389.90 Safari/537.36,
  WA_AUTOMATE_VERSION: 3.13.2,
  BROWSER_VERSION: HeadlessChrome/91.0.4469.0
}
```

**Screenshots**
N/A

**Host (please complete the following information):**
 - OS: Windows Server

**Additional context**
N/A

**Comment by smashah** [comment]
Hey @paulocorcino 

In the latest version: Release [3.14.0](https://github.com/open-wa/wa-automate-nodejs/compare/3.13.2...3.14.0) (2021-05-16)

you can now set config.messagePreprocessor

This will attempt to process the message before sending it to your callback and therefore your java process

There are a few options:

- `SCRUB` - Replace `body` and `content` with `""`
- `BODY_ONLY` - Replace `content` with `""`
- `AUTO_DECRYPT` - Replace `body` with the decrypted file DataURL
- `AUTO_DECRYPT_SAVE` - Replace `body` with the filename of the decrypted file which is saved in `/media`, adds `filePath` property to the message object with the path of the file. If you're using the CLI, it will automatically expose an endpoint `/media` from which you can `GET` the files.

> PLEASE NOTE THAT IF YOU SET IT TO `AUTO_DECRYPT_SAVE` THEN YOU HAVE TO MANAGE THE `/media` DIRECTORY YOURSELF! IF YOU DON'T EMPTY IT YOU MAY RUN OUT OF STORAGE!!!


Examples for your situation (`BODY_ONLY`:

node:

```javascript
	create({
		"messagePreprocessor": "BODY_ONLY"
	})
```

cli: 
```bash
> npx @open-wa/wa-automate ... --message-preprocessor="BODY_ONLY"
```

Thanks

**Comment by paulocorcino** [comment]
HI Smashah, 

I did test using your sample, but, not had successful. Open-WA send by webhook same data binary twice. 
I'll show you images with I did to start the process.

I tried with two way:
![image](https://user-images.githubusercontent.com/7800501/118402379-1ae04680-b640-11eb-90fc-84f9ae77786f.png)
and this
![image](https://user-images.githubusercontent.com/7800501/118402328-d0f76080-b63f-11eb-8136-007a246d80e5.png)

Both show me same result with pdf file with b64 twice on code.
![image](https://user-images.githubusercontent.com/7800501/118402457-52e78980-b640-11eb-89b1-a1efa66290a9.png)

I did test with
--message-preprocessor 'AUTO_DECRYPT_SAVE'

Work with image, but not with document file.

Sorry if I did something wrong, follow my config.json

``
{
	"authTimeout":0,
	"qrTimeout":0,
	"sessionId":"83431",
	"port":8003,
	"skipUpdateCheck":true,	
	"popup":8003,
	"useChrome": true,
	"licenseKey":"",
	"logFile": true,
	"cachedPatch": true,
	"throwErrorOnTosBlock": false,
	"useStealth": true,
	"bypassCSP": true,
	"hostNotificationLang": "PT_BR",
	"killProcessOnBrowserClose":true,
	"webhook":[{
		"url":"http://localhost:8049/webrunstudio/gethook.rule?sys=BOT&token=K6MEQJRV3trXMPZ5eQd1Jl8NaaaRZxqy",
		"events":["onMessage","onMessageDeleted","onAck","onIncomingCall","onBattery","onPlugged","onStateChanged","onStory"]
	}]
}
``
Node and NPM version

``
PS C:\what2api\vWA> node --version
v14.15.4
PS C:\what2api\vWA> npm --version
6.14.10
PS C:\what2api\vWA>
``
![image](https://user-images.githubusercontent.com/7800501/118402590-ed47cd00-b640-11eb-99e8-56776038b9a7.png)
I'm appreciate your work and patience to help every one, thank you!

**Comment by smashah** [comment]
@paulocorcino can you provide the full body of those two webhooks please. The screenshot does not show the whole detail.

Also, let me know if the issue persists with this config.json

```javascript
{
	"authTimeout":0,
	"qrTimeout":0,
	"sessionId":"83431",
	"port":8003,
	"skipUpdateCheck":true,	
	"popup":8003,
	"useChrome": true,
	"licenseKey":"",
	"logFile": true,
	"cachedPatch": true,
	"throwErrorOnTosBlock": false,
	"useStealth": true,
	"bypassCSP": true,
	"hostNotificationLang": "PT_BR",
	"killProcessOnBrowserClose":true,
	"webhook":[{
		"url":"http://localhost:8049/webrunstudio/gethook.rule?sys=BOT&token=K6MEQJRV3trXMPZ5eQd1Jl8NaaaRZxqy",
		"events":["onMessage","onMessageDeleted","onIncomingCall","onBattery","onPlugged","onStateChanged","onStory"]
	}]
}
```

**Comment by paulocorcino** [comment]
@smashah So, I did some tests, this was results.

I used 4 kind of file: image, video, pdf and binary (format not commons)

npx @open-wa/wa-automate -a -c './config.json' -i --no-kill-on-logout --message-preprocessor 'BODY_ONLY' --skip-save-postman-collection -k 'K6MEQJRV3trXMPZ5eQd1Jl8NaaaRZxqy'

**Result**
Image: binary thumb twice.
Video: binary full twice.
Audio: nothing, only enc.
PDF:  binary full twice.
File: Nothing (surprise for me, with my old API I had received)

npx @open-wa/wa-automate -a -c './config.json' -i --no-kill-on-logout --message-preprocessor 'AUTO_DECRYPT' --skip-save-postman-collection -k 'K6MEQJRV3trXMPZ5eQd1Jl8NaaaRZxqy'

**Result**
Image: the body with b64 and the content with ""
Video: json corrupt.
Audio: nothing, only enc.
PDF:  binary full twice.
File: Nothing.

npx @open-wa/wa-automate -a -c './config.json' -i --no-kill-on-logout --message-preprocessor 'AUTO_DECRYPT_SAVE' --skip-save-postman-collection -k 'K6MEQJRV3trXMPZ5eQd1Jl8NaaaRZxqy'

**Result**
Image: the body with file name on media folder
Video: the body with file name on media folder
Audio: nothing, only enc.
PDF:  binary full twice, no file media folder.
File: Nothing.

npx @open-wa/wa-automate -a -c './config.json' -i --no-kill-on-logout --message-preprocessor 'SCRUB' --skip-save-postman-collection -k 'K6MEQJRV3trXMPZ5eQd1Jl8NaaaRZxqy'

**Result**
Image: the body with "" and content with thumb.
Video: the body with "" and content with thumb.
Audio: nothing, only enc.
PDF:  binary full twice.
File: Nothing.

Zip with all JSON results, the password to open this file I'll send you by Discord.

[json_results.zip](https://github.com/open-wa/wa-automate-nodejs/files/6489897/json_results.zip)

@smashah, this is result that I have when result using What2Api.

**Result**
Image: body full binary and content ""
Video: body full binary and content ""
Audio: body full binary and content ""
PDF:  body full binary and content ""
File: body full binary and content ""

Regards

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.14.1](https://github.com/open-wa/wa-automate-nodejs/compare/3.14.0...3.14.1) (2021-05-16)

- Release 3.14.1 [`eda9fc9`](https://github.com/open-wa/wa-automate-nodejs/commit/eda9fc9d522be554fafcdf9c765efdda541a9e89)
- 🐛  fix: make sure preprocessors work on pdf files #1669 [`e872f9b`](https://github.com/open-wa/wa-automate-nodejs/commit/e872f9bcfff21ccc613ba7e26aed8657c720926b)
- 📝  docs: add `message.clientUrl` deprecation information [`a8bc1fe`](https://github.com/open-wa/wa-automate-nodejs/commit/a8bc1fefd94c00633404f5b08809265f9a37b806)
