### ISSUE TITLE
Stuck on 'Authenticating' forever

### ISSUE THREAD

**Issue by guilhermebkel** [open-wa/wa-automate-nodejs#1671]
**Describe the bug**
It looks quite random, but sometimes it happens to a session to get stuck on the loading spinner after reading qr code or even after injecting session data (I noticed it when I used the session on my local computer).

I feel like it could be something related to the **phoneIsOutOfReach** since it has no timeout and the message never appears in these rare cases 🤔

![image](https://user-images.githubusercontent.com/42042433/118307096-9d41fc80-b4c0-11eb-8ca7-d99142869e6a.png)

**Steps to Reproduce**
It is only needed to start a session with existing data or even to read the QR Code, but I feel like it happens more to old smartphones with a big amount of chats.

**Expected behavior**
It was expected to get a timeout error due to the authentication getting more time to be done as expected.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  "WA_VERSION": "2.2117.5",
  "PAGE_UA": "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "3.12.0 UPDATE AVAILABLE: 3.13.2",
  "BROWSER_VERSION": "HeadlessChrome/91.0.4469.0",
  "OS": "Linux 4.14",
  "START_TS": 1620996562632
}

Config {
   "sessionData": "EXISTING_SESSION_DATA",
   "authTimeout": 60,
   "qrTimeout": 60,
   "blockCrashLogs": true,
   "disableSpins": true,
   "headless": true,
   "hostNotificationLang": "PT_BR",
   "logConsole": false,
   "qrLogSkip": true,
   "skipSessionSave": true,
   "popup": false,
   "corsFix": true,
   "bypassCSP": true,
   "deleteSessionDataOnLogout": true,
   "idCorrection": true,
   "logConsoleErrors": true,
   "useChrome": false,
   "useNativeProxy": true,
   "useStealth": true,
   "proxyServerCredentials: "EXISTING_PROXY_CONFIG"
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/42042433/118306290-99fa4100-b4bf-11eb-8de2-99f51aad48bd.png)

**Additional context**
This problems looks to happen more times with the session from an old smartphone with a big amount of chats.

**Comment by smashah** [comment]
@guilhermebkel in the Release [3.14.0](https://github.com/open-wa/wa-automate-nodejs/compare/3.13.2...3.14.0) (2021-05-16) it will now wait 20 seconds before ignoring the `phoneIsOutOfReach`
