### ISSUE TITLE
I'm having trouble starting

### ISSUE THREAD

**Issue by x000x000x000x** [open-wa/wa-automate-nodejs#1678]
good morning, could you help me with a bug? whenever I use the "npm start" command I give the following error:

┃
┃   @open-wa/wa-automate                                                                            ┃
┃    💬 🤖 The most reliable NodeJS whatsapp library for chatbots with advanced features.           ┃
┃   Version: 3.15.0                                                                                 ┃
┃   Check out the latest changes: https://github.com/open-wa/wa-automate-nodejs#latest-changes      ┃
┃                                                                                                   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
- Starting
- Version: 3.15.0
- Initializing WA
- Launching Browser
TypeError: storage.getItem is not a function
    at /home/angelo/iris/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:235:46
    at Generator.next (<anonymous>)
    at fulfilled (/home/angelo/iris/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:24:58)

could you help me with that?

**Comment by wlskcode** [comment]
I'm having the same issue... for now the only solution I found is to use an older version.

`npm uninstall @open-wa/wa-automate`
`npm install @open-wa/wa-automate@3.13.2`

**Comment by smashah** [comment]
@x000x000x000x 

What node and npm versions are you running?

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.15.1](https://github.com/open-wa/wa-automate-nodejs/compare/3.15.0...3.15.1) (2021-05-17)

- Release 3.15.1 [`bb6cfc9`](https://github.com/open-wa/wa-automate-nodejs/commit/bb6cfc9e76ae9068fa4249154fdd4d9b90f73abc)
- 🐛 fix: #1678 [`7adf3c7`](https://github.com/open-wa/wa-automate-nodejs/commit/7adf3c721e706ee9220f17f353f779e90d47d59d)

**Comment by smashah** [comment]
@x000x000x000x @wlskcode should be fixed now

**Comment by x000x000x000x** [comment]
> @x000x000x000x 
> 
> What node and npm versions are you running?

    thanks

**Comment by x000x000x000x** [comment]
> @x000x000x000x @wlskcode should 

thanks
