### ISSUE TITLE
Initialization error continues

### ISSUE THREAD

**Issue by wlskcode** [open-wa/wa-automate-nodejs#1679]
I was having the same issue as the other guy in version 3.15.0: "TypeError: storage.getItem is not a function". Now that this is fixed, another error shows up...

- Starting
- Version: 3.15.1
- Initializing WA
- Launching Browser
- Setting Up Browser
- Loading session data
- Found session data file: C:\Users\Caio\Desktop\iris\Iris.data.json
- Existing session data detected. Injecting...
- Existing session data injected
- Navigating to WA
- Navigating to WA
**TypeError: Cannot read property 'status' of null**
    at Object.<anonymous> (C:\Users\Caio\Desktop\iris\node_modules\@open-wa\wa-automate\dist\controllers\browser.js:138:133)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Caio\Desktop\iris\node_modules\@open-wa\wa-automate\dist\controllers\browser.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by smashah** [comment]
@wlskcode does this happen every time?

**Comment by wlskcode** [comment]
> @wlskcode does this happen every time?

Every single time, except for the first time. The first execution it ran just fine, I was able to authenticate on whatsapp web.

![Captura de tela 2021-05-17 221324](https://user-images.githubusercontent.com/84291998/118575574-2e350400-b75d-11eb-8a75-5c6f1b1c99fb.png)

I tried changing my node version but this still happens with both node LTS version and the current version. I'm looking forward to this problem being fixed, thanks for the reply!

**Comment by smashah** [comment]
@wlskcode 
the crazy thing about the error you're getting is that the web page request is returning null which I have never seen before. Please share your config and any other context around this issue. Also, in the future use the issue template.

**Comment by smashah** [comment]
possibly related:

https://github.com/puppeteer/puppeteer/issues/2479

**Comment by smashah** [comment]
@wlskcode 

in the latest version (Release [3.15.2](https://github.com/open-wa/wa-automate-nodejs/compare/3.15.1...3.15.2) (2021-05-18)), you will not get to this error, however you may still have issues with loading - but that will be a different problem.
