### ISSUE TITLE
How to avoid "Authentication timed out. Please open the app on the phone. Shutting down"

### ISSUE THREAD

**Issue by lfernandes** [open-wa/wa-automate-nodejs#1688]
**Describe the bug**
I would like to know what can I do to avoid to phone get disconnected from WhatsApp server.

**Steps to Reproduce**
1. Schedule a cron to send message at specific time of the day

**create() code**
This is the code you use to create the client. e.g
```javascript
crontab.scheduleJob("0 6 * * *", function(){
	wa.create({
		hostNotificationLang: 'PT_BR',
	}).then(async (client) => {
		await sendMessages(client);
		readMessages(client);
	});
});
```

**Expected behavior**
Be able to send scheduled messages all the time (keep the WhatsApp in the phone always connected / active).

**DEBUG INFO**
```
- Authentication timed out. Please open the app on the phone. Shutting down                                                             
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:                                          
Error: App Offliney   r        :    5                                                                                                   
    at Object.<anonymous> (/workspace/nodejs/wpobpc/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:231:23)           
    at Generator.next (<anonymous>)                                                                                                     
    at fulfilled (/workspace/nodejs/wpobpc/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:24:58)
```

**Screenshots**
Not applicable

**Host (please complete the following information):**
 - OS: Ubuntu 20.02

**Additional context**
None.

**Comment by smashah** [comment]
Hey,

Thanks for filling in the template. It's greatly appreciated.

You can achieve this by setting [`authTimeout`](https://docs.openwa.dev/interfaces/api_model_config.configobject.html#authtimeout) to 0 to make it wait forever.

```
crontab.scheduleJob("0 6 * * *", function(){
	wa.create({
		hostNotificationLang: 'PT_BR',
		authTimeout: 0
	}).then(async (client) => {
		await sendMessages(client);
		readMessages(client);
	});
});
```

Ideally, you want to keep the phone on charge, open on the app, and with a good connection to avoid hitting the timeout.
