### ISSUE TITLE
Send file as a playable audio

### ISSUE THREAD

**Issue by urielexis64** [open-wa/wa-automate-nodejs#1711]
How to send a mp3 file as a playable audio? Not as a voice note, but an audio file.

Thanks!

**Comment by smashah** [comment]
@urielexis64 show me what you're trying now so I can help you out

**Comment by urielexis64** [comment]
![photo1621887900](https://user-images.githubusercontent.com/47485144/119403657-edc51100-bc9b-11eb-94ac-ab34209596ff.jpeg)

Something like this when sending an audio file

**Comment by smashah** [comment]
I mean the code you are using

**Comment by urielexis64** [comment]
This
```js
client.sendFile(from, "audio.mp3", videoInfo.videoDetails.title, videoInfo.videoDetails.title, id);
```

It sends a file, not an audio like the one shown in the screenshot

**Comment by smashah** [comment]
Try this: https://github.com/open-wa/wa-automate-nodejs/issues/1039#issuecomment-736962783

```javascript
client.sendFile(from, "audio.mp3", videoInfo.videoDetails.title, videoInfo.videoDetails.title, id, null, true, false, true);
```

**Comment by urielexis64** [comment]
Still not working, it returns a voice note instead of an audio

**Comment by smashah** [comment]
@urielexis64 you can now upgrade to https://github.com/open-wa/wa-automate-nodejs/releases/tag/4.1.0 and use [`sendAudio`](https://docs.openwa.dev/classes/api_client.client.html#sendaudio) to send an mp3 as a normal audio file and not as a voice note. thanks
