### ISSUE TITLE
sendImage error

### ISSUE THREAD

**Issue by Gahtee** [open-wa/wa-automate-nodejs#1725]
**Describe the bug**
Im trying to send a image by a url and its say: "Make sure the file reference is relative, a valid URL or a valid DataURL"

**Steps to Reproduce**
a get from axios to this link https://some-random-api.ml/img/dog
and a simple link solve and tried to use sendImage, but its return a error

**create() code**

```javascript
const rdog = await axios.get(`https://some-random-api.ml/img/dog`)
console.log(rdog.data.link)
await myst.sendImage(from, rdog.data.link)
```

**Expected behavior**
I was expecting to the bot send as a normal image

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2119.6
  PAGE_UA: WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
  WA_AUTOMATE_VERSION: 4.0.2
  BROWSER_VERSION: Windows 10
}
```

**Screenshots**
![WindowsTerminal_KM8j0ewzSH](https://user-images.githubusercontent.com/83777687/119733949-9d42e480-be50-11eb-9964-c5c6d5b7df5d.png)
![sublime_text_6ivqkwnz0O](https://user-images.githubusercontent.com/83777687/119733952-9ddb7b00-be50-11eb-8105-7f14a15c6c22.png)

**Host (please complete the following information):**
 - OS: Android 10 (MIUI 12.0.4)

**Additional context**
Im the guy from discord.. hehe
I also tried sendFileFromUrl and sendImageAsSticker, but it return the same error
and this is the error:
```
[ERROR] FILE_NOT_FOUND: Cannot find file. Make sure the file reference is relative, a valid URL or a valid DataURL
    at Client.<anonymous> (C:\bot\myst\node_modules\@open-wa\wa-automate\dist\api\Client.js:1219:27)
    at Generator.next (<anonymous>)
    at C:\bot\myst\node_modules\@open-wa\wa-automate\dist\api\Client.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (C:\bot\myst\node_modules\@open-wa\wa-automate\dist\api\Client.js:23:12)
    at Client.sendImage (C:\bot\myst\node_modules\@open-wa\wa-automate\dist\api\Client.js:1207:16)
    at Client.<anonymous> (C:\bot\myst\node_modules\@open-wa\wa-automate\dist\api\Client.js:1305:25)
    at Generator.next (<anonymous>)
    at C:\bot\myst\node_modules\@open-wa\wa-automate\dist\api\Client.js:27:71
    at new Promise (<anonymous>)
```

**Comment by smashah** [comment]
Hi,

the reason this is happening is because of the rdog.data.link URL goes to an image that is missing the `content-type` header which is required for determining the file type of a URL based file.

You should inform the developer of this API that the image should return with a proper content-type headers. In the meantime, please keep track of #1727 where I will develop an implicit detection mechanism within the library itself.

**Comment by smashah** [comment]
@Gahtee this should be fixed in the latest version but you should make sure to add a filename with a valid file extension in order to fix this issue.

https://github.com/open-wa/wa-automate-nodejs/releases/tag/4.1.0 

```javascript
await myst.sendImage(from, rdog.data.link , 'dog.jpeg','')
```

thanks
