### ISSUE TITLE
pin and unpin chat

### ISSUE THREAD

**Issue by fajarnurprasetyo** [open-wa/wa-automate-nodejs#1726]
request feature for pin or unpin chat

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.1.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.0.2...4.1.0) (2021-05-27)

- build(deps): bump ts-morph from 10.1.0 to 11.0.0 [`#1728`](https://github.com/open-wa/wa-automate-nodejs/pull/1728)
- build(deps): bump ts-json-schema-generator from 0.92.0 to 0.93.0 [`#1729`](https://github.com/open-wa/wa-automate-nodejs/pull/1729)
- build(deps-dev): bump typescript from 4.2.4 to 4.3.2 [`#1730`](https://github.com/open-wa/wa-automate-nodejs/pull/1730)
- build(deps-dev): bump tsc-watch from 4.2.9 to 4.4.0 [`#1731`](https://github.com/open-wa/wa-automate-nodejs/pull/1731)
- Release 4.1.0 [`e248a00`](https://github.com/open-wa/wa-automate-nodejs/commit/e248a005cbebe9165f59783c9c784971fe8f5162)
- ✨  feat: export all tools, including `getDUrl` #1725 [`e87f6be`](https://github.com/open-wa/wa-automate-nodejs/commit/e87f6be97952153f08bfa25a9b108263888d24a9)
- 📌  dev-deps: pin typscript to 4.2.4 [`9bf31e3`](https://github.com/open-wa/wa-automate-nodejs/commit/9bf31e357838a158195617372dafc2d68cee2ece)
- ✨ feat: automatically detect redundant/missing content types from filename extension #1727 [`2b06ce0`](https://github.com/open-wa/wa-automate-nodejs/commit/2b06ce000051b09dacc09a5379cc22373a0dfd8a)
- ✨ feat: `client.pinChat` #1726 [`50f4cd8`](https://github.com/open-wa/wa-automate-nodejs/commit/50f4cd85f73fa9b111a9857ca177f3fdeaeff890)
- ✨  feat: `sendAudio` now sends native audio (not voicechat/ptt) #1711 [`f7a513f`](https://github.com/open-wa/wa-automate-nodejs/commit/f7a513f2c41fc62f32608bbe66fdc24efd627542)
- 📝  docs: add note about `octet-stream` default resolution to video #1727 [`4d5312a`](https://github.com/open-wa/wa-automate-nodejs/commit/4d5312aa025f770881c940e97102f16b758c75f7)
