### ISSUE TITLE
CheckNumberStatus not working

### ISSUE THREAD

**Issue by erickmourasilva** [open-wa/wa-automate-nodejs#1748]
This function not working more.
Check the result in image:
![image](https://user-images.githubusercontent.com/29979780/120567749-d64afe00-c3e8-11eb-92be-027fc9aa398d.png)

**Comment by lukasportal** [comment]
Yep.. this started happening after the latest version 2.2121.5
issue is on window.Store.WapQuery.queryExist()

a little more info from my debugging:
startComms is an internal function that starts a proxy/network class that makes requests, apparently
sendIq is an internal function that sends a request via ws, possibly lol

from my understand, this latest WA Web version has a bug on queryExist


but one more thing i noticed:
if you inspect the websocket's (ws request) messages, you will notice a queryExist call after clicking on a link to open a new chat (something like https://wa.me/<chatId>)
![image](https://user-images.githubusercontent.com/5941939/120568545-fc35ca00-c40b-11eb-8156-161707ad9181.png)

so apparently they use an internal function that is not the same as the "exposed" Store.WapQuery.queryExist"

anyways, this might all sound useless but it might be worth sharing what i could find so far

I also can't find any workaround

**Comment by krasymyr** [comment]
yes. stuck here too.

**Comment by bobaoapae** [comment]
Just change store discovery for WapQuery, getting wrong reference.


{
            id: "WapQuery",
            conditions: (module) => (module.default && module.default.queryExist) ? module.default : null
        },

**Comment by frankdors** [comment]
FallBack solution (creates always is not exists, ignores not found)

```
letchat = Store.Chat.get(this.cuidToJid(cuid))

if (!chat) {
	const ConstructChat = new Store.UserConstructor(this.cuidToJid(cuid), {intentionallyUsePrivateConstructor: true});
	chat = Store.Chat.find(ConstructChat);
}
```

**Comment by lukasportal** [comment]
@bobaoapae's solution fixed it

**Comment by chirag90851** [comment]
@bobaoapae it's work

**Comment by chirag90851** [comment]
Thanx

**Comment by smashah** [comment]
track #1755 for fix

**Comment by smashah** [comment]
Patched. Restart your sessions. Thanks

**Comment by oltanalkan** [comment]
@bobaoapae 
Store.WapQuery.profilePicFind Not working

**Comment by rajeshshettysrs** [comment]
> Just change store discovery for WapQuery, getting wrong reference.
> 
> {
> id: "WapQuery",
> conditions: (module) => (module.default && module.default.queryExist) ? module.default : null
> },

thank you very much.above solution worked for below error
"javascript error: Comms::sendIq called before startComms"

**Comment by hydenz** [comment]
It's working! Thanks!

> 
> 
> Just change store discovery for WapQuery, getting wrong reference.
> 
> {
> id: "WapQuery",
> conditions: (module) => (module.default && module.default.queryExist) ? module.default : null
> },
