### ISSUE TITLE
SendMessageLinkPreview  function not working

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-nodejs#1754]
When I am sending message using sendLinkWithAutoPreview api, I am getting following error

`Evaluation failed: TypeError: Store[(_0x196877(...) + _0x196877(...) + "ry")][(_0x196877(...) + _0x196877(...) + _0x196877(...) + _0x196877(...) + _0x196877(...) + "w")] is not a function\n    at Object.window.<computed>.<computed> [as sendLinkWithAutoPreview] (__puppeteer_evaluation_script__:1:168918)'}`

**Comment by fire17** [comment]
Im also experincing this issue!
please dont mark it as not following guildines.. pretty sure i've already seen an issue on this closed since it didnt follow the correct style.

Anyone please, do you have a workaround ?? tu

**Comment by smashah** [comment]
track #1755

**Comment by smashah** [comment]
@manojsitapara patched. please restart your instance
