### ISSUE TITLE
BREAKING UPDATE: 2.2121.5 [DO NOT CREATE NEW ISSUES - ADD THEM HERE]

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#1755]
If you are experiencing issues with some features, please add the details here as a comment instead of creating new issues.

TODO:

- [x] profilePicFind
- [x] checkNumberStatus #1748
- [x] mfs
- [x] sendLinkWithAutoPreview #1754

**Comment by fire17** [comment]
can you guys create new groups?
im getting 
`selenium.common.exceptions.JavascriptException: Message: javascript error: window.Store.WapQuery.createGroup is not a function`

**Comment by smashah** [comment]
@fire17 should be fixed now with patch please try again

**Comment by fire17** [comment]
> @fire17 should be fixed now with patch please try again

**i love how you guys in this repo fix shit so quickly!**

Q - do these fixes translate over to wa-autimate-python?
_(honest confession - i'm still using mukulhase/WebWhatsapp-Wrapper cause its almost the same and thats where i started, usually all the fixes posted here also solve the issues over there, but i cant figure what to do with patches.json, is there any change i can do in wapi.js to solve these issues ?? [createGroup, autoPreview])_

Thanks alot !

**Comment by oltanalkan** [comment]
Store.WapQuery.profilePicFind Not working

**Comment by smashah** [comment]
@oltanalkan if you restart your session it should work

@fire17 thank you for your kind words. The patches system is designed so nobody has to upgrade a library/dependency to receive critical updates (like this one) it only requires you to restart your session to get the brand new patch (from our dedicated CDN). The python library also has this baked in so the fixes are translated there in real time.

**Comment by fire17** [comment]
@smashah That would be wonderful!
I'd much rather work on a system that is autopatched - also might consider for people who'd like to set it up so that it will autorestart if it sees a new patch. (I prefer to reset my system instead of not functioning properly)

until i change my code to work with yours (either through sdk or other means), will you push updates to the code repo soon?
im betting these some channge in wapi.js or others that will crossover to my code and fix these problems...
AGAIN THANKS A LOT!

**Comment by oltanalkan** [comment]
@smashah 
When will you release updated wapi.js ?

**Comment by smashah** [comment]
@fire17 a way to subscribe to patch updates via webhook may be a cool feature for users of the lib, however, some days there are multiple patches to fix small edge cases that are irrelevant to 99% of people. Best way to know when a new patch is important is to keep track in the discord where a notification is sent every time there is a new patch.


wapi.js is locked in this library. All updates are now done via patches.

Looks like everything is working now.

Closing.

Thanks

**Comment by fire17** [comment]
please post update wapi.js ! :pray: :pray: :pray:

**Comment by daopapp** [comment]
Hi @smashah , im getting this error displayed on my paid account:

middleware -> error Error: Evaluation failed: p
    at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)

I already restart my session to get the last update
<img width="959" alt="Captura de Tela 2021-06-04 às 10 03 47" src="https://user-images.githubusercontent.com/42589779/120805515-48702f80-c51c-11eb-9961-654defee44d2.png">

**Comment by smashah** [comment]
@daopapp it looks like the number you are trying to send a message to is not linked to a whatsapp account. Can you DM me on discord please

**Comment by daopapp** [comment]
Ok man, i sent a message to you

**Comment by daopapp** [comment]
when i use the checknumberstatus, sometimes the result it's ok and sometimes i get this:

{
  "success": true,
  "response": {
    "id": "5511997794474@c.us",
    "status": {
      "name": "Server5xxDrop",
      "stack": "Server5xxDrop\n    at new i (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:2:361774)/n    at new p (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:5:253201)/n    at Object.on5xx (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:16:518621)/n    at Object.onMessage (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:16:519489)/n    at Object._onParsedMsg (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:21:17338)/n    at Object._onMessage (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:21:16946)"
    },
    "isBusiness": false,
    "canReceiveMessage": false
  }
}


this number have whasapp

**Comment by oltanalkan** [comment]
@smashah 
Store.WapQuery.profilePicFind 
Are you going to do anything to make the function work?

**Comment by smashah** [comment]
@oltanalkan as I mentioned in the other comment, it is working as expected. Unless someone can fill in the issue template with reproducible steps then I'm considering the issue resolved.
