### ISSUE TITLE
The checkNumberStatus method is returning an error

### ISSUE THREAD

**Issue by marcosdemelo** [open-wa/wa-automate-nodejs#1766]
**Describe the bug**
The `WAPI.checkNumberStatus` method is returning an error: 
{id: "<whatsappNumber>#@c.us", status: Error: Comms::sendIq called before startComms
    at O (https://web.whatsapp.com/bootstrap_qr.c1175…, isBusiness: false, canReceiveMessage: false}

**Steps to Reproduce**
1. Inject the WAPI.js on Whatsapp web
2. Open the browser console and call then await ```WAPI.checkNumberStatus(`${whatsappNumber}@c.us`)```

**Expected behavior**
It returns the number status.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
{id: "<whatsappNumber>2#@c.us", status: Error: Comms::sendIq called before startComms
    at O (https://web.whatsapp.com/bootstrap_qr.c1175…, isBusiness: false, canReceiveMessage: false}
canReceiveMessage: false
id: "554884661212#@c.us"
isBusiness: false
status: Error: Comms::sendIq called before startComms at O (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:2:517929) at https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:2:517491 at V (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:2:333049) at new v (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:2:322092) at P (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:2:517468) at t.sendIq (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:2:511397) at t.USyncQuery.execute (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:5:249420) at Object.t.queryExist (https://web.whatsapp.com/bootstrap_qr.c11753ab24650fdf3d67.js:5:35649) at Object.window.WAPI.checkNumberStatus (chrome-extension://kjhmpngcoddhklhbnaeokcjickbfjeji/scripts/inject.js:1:22240) at <anonymous>:1:12
__proto__: Object
```

**Comment by marcosdemelo** [comment]
A possible solution https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/631#issuecomment-855183831

**Comment by smashah** [comment]
The solution to your problem is to use the library as intended
