### ISSUE TITLE
Fix swagger ui documentation links

### ISSUE THREAD

**Issue by ardzz** [open-wa/wa-automate-nodejs#1774]
I've visited [https://docs.openwa.dev/classes/client.html#decryptmedia](https://docs.openwa.dev/classes/client.html#decryptmedia) but it's turned 404

**Comment by smashah** [comment]
hey @ardzz can you show me exactly where you found that link so i can fix it please, thanks.

Correct link:

https://docs.openwa.dev/pages/How%20to/decrypt-media.html

**Comment by ardzz** [comment]
In the Swagger UI @smashah

**Comment by ardzz** [comment]
Btw https://docs.openwa.dev/pages/How%20to/decrypt-media.html is directly from nodejs, what i want is from ease API.
But i found the documentation at [https://docs.openwa.dev/classes/api_client.client.html#decryptmedia](https://docs.openwa.dev/classes/api_client.client.html#decryptmedia)

**Comment by smashah** [comment]
@ardzz maybe you should check this out: 

https://docs.openwa.dev/interfaces/api_model_config.configobject.html#messagepreprocessor

You can set it on the easy API with the following flag:

```
> npx .... --message-preprocessor AUTO_DECRYPT
```

See background here: https://github.com/open-wa/wa-automate-nodejs/issues/1669#issuecomment-841761423

**Comment by smashah** [comment]
Or if you use `AUTO_DECRYPT_SAVE` it will give you a [`filePath`](https://docs.openwa.dev/interfaces/api_model_message.message.html#filepath) property on the Message object which you can use in the [`/media` path of the easy API](https://github.com/open-wa/wa-automate-nodejs/blob/613907eb575f61305723d4faf179a66299d07692/src/cli/server.ts#L142)

You just have to keep an eye on the `/media` folder

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.3.1](https://github.com/open-wa/wa-automate-nodejs/compare/4.3.0...4.3.1) (2021-06-10)

- Release 4.3.1 [`c5cf864`](https://github.com/open-wa/wa-automate-nodejs/commit/c5cf8646542f7ce372d6d4dff78df7238c6e5aab)
- 🐛  fix [config]: `killProcessOnTimeout` now works on Navigation Timeout #1775 [`2ee90cb`](https://github.com/open-wa/wa-automate-nodejs/commit/2ee90cb2e710a93ed5203657a88de9af57d38922)
- 📝 docs [CLI]: fix external docs links in swagger colletions #1774 [`58772d8`](https://github.com/open-wa/wa-automate-nodejs/commit/58772d813edb93886efdf6dcf7d4c7cb5577d57b)

**Comment by smashah** [comment]
docs are fixed thanks for bringing it up @ardzz
