### ISSUE TITLE
"npm i" crash with ESM Loader

### ISSUE THREAD

**Issue by mesutyigit** [open-wa/wa-automate-nodejs#1776]
node -v: 13.7.0
npm -v: 6.13.7
MacOs BigSur
branch: 4.4.0

❯ npm i

> @open-wa/wa-automate@4.4.0 install /Users/mesut/wa-automate-nodejs
> cross-env npm_config_yes=true npx ignore-check@latest -p '**.data.json' -p '**.node-persist**' --comment 'managed by open-wa'

npx: installed 63 in 6.071s
(node:37770) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:33:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:188:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @open-wa/wa-automate@4.4.0 install: `cross-env npm_config_yes=true npx ignore-check@latest -p '**.data.json' -p '**.node-persist**' --comment 'managed by open-wa'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @open-wa/wa-automate@4.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mesut/.npm/_logs/2021-06-11T12_30_43_108Z-debug.log

**Comment by smashah** [comment]
@mesutyigit please update your npm >=7.9.0

```bash
> npm i -g npm
```
