### ISSUE TITLE
Tutorial Requests

### ISSUE THREAD

**Issue by manishkumar1601** [open-wa/wa-automate-nodejs#1777]
hello sir I'm not familiar with coding so can you make a tutorial video how to use bot in WhatsApp so i will be very thankful to you

**Comment by lMartin3** [comment]
learn the language first, if you aren't able to understand the lib with the already available documentation then you should be learning the basics of node js.

**Comment by Sirloya** [comment]
It is very vast and depends on how u want to use it

**Comment by smashah** [comment]
- [ ] using botpress with openwa or easy api

**Comment by smashah** [comment]
If you want a tutorial please ask a question in the discussions section of this repo.

https://github.com/open-wa/wa-automate-nodejs/discussions
