### ISSUE TITLE
onAnyMessage event stops listening

### ISSUE THREAD

**Issue by eyalmichon** [open-wa/wa-automate-nodejs#1781]
**Describe the bug**
When trying to send a file larger than 64MB, onAnyMessage event stops listening.

**Steps to Reproduce**
1. Go to this site: https://scontent.cdninstagram.com/v/t50.2886-16/10000000_1208850152873308_4744059728457855204_n.mp4?_nc_ht=instagram.ftlv5-1.fna.fbcdn.net&_nc_cat=104&_nc_ohc=p-BZE0KdEqoAX9nlM8F&edm=AABBvjUBAAAA&ccb=7-4&oe=60C88CE6&oh=d759e9c6028a2b4f16261765e86dfa08&_nc_sid=83d603
2. Use sendFileFromURL to send this URL:
```javascript
let file = 'https://scontent.cdninstagram.com/v/t50.2886-16/10000000_1208850152873308_4744059728457855204_n.mp4?_nc_ht=instagram.ftlv5-1.fna.fbcdn.net&_nc_cat=104&_nc_ohc=p-BZE0KdEqoAX9nlM8F&edm=AABBvjUBAAAA&ccb=7-4&oe=60C88CE6&oh=d759e9c6028a2b4f16261765e86dfa08&_nc_sid=83d603';
client.sendFileFromUrl(message.from, file, '', null, null, true)
```

**create() code**
This is the code you use to create the client. e.g
```javascript
wa.create({
    sessionId: "HELPER",
    headless: false,
    autoRefresh: true,
    cacheEnabled: false,
    callTimeout: 15000,
    // useChrome: true
    // run instead of chromium
    executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
}).then(client => start(client));
```

**Expected behavior**
Expected to get an exception and the listener to continue working.
**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2121.6
  PAGE_UA: WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
  WA_AUTOMATE_VERSION: 4.5.0
  BROWSER_VERSION: Chrome/91.0.4472.101
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/66881082/121859610-934e2c00-cd00-11eb-9df3-4e801db6d38a.png)

**Host (please complete the following information):**
 - OS: Windows 10

**Comment by gnadelwartz** [comment]
can you send the video from your WhatsApp Client? iirc the Limit for video is 50 mb ...

**Comment by smashah** [comment]
@eyalmichon do you have any updates on this issue? Does it continue to only happen when you upload a masive video?

**Comment by eyalmichon** [comment]
I'm sorry but I have added a check for the size myself so I wouldn't get the error again so I have no idea if it still is happening or not :(

> @eyalmichon do you have any updates on this issue? Does it continue to only happen when you upload a masive video?

**Comment by smashah** [comment]
@eyalmichon in that case I will close this for now. I am working on a video splitting library. I'll let you know when it's ready to try over discord. 

thanks
