### ISSUE TITLE
Error: Evaluation failed: TypeError: c.waitForPrep is not a function

### ISSUE THREAD

**Issue by dngda** [open-wa/wa-automate-nodejs#1786]
**Describe the bug**
when try to use client.reply(...

> Error: Evaluation failed: TypeError: c.waitForPrep is not a function
    at https://web.whatsapp.com/bootstrap_qr.3df7948c21bd43e94300.js:2:424136
    at q (https://web.whatsapp.com/bootstrap_qr.3df7948c21bd43e94300.js:2:333948)
    at MutationObserver.H (https://web.whatsapp.com/bootstrap_qr.3df7948c21bd43e94300.js:2:333529)
    at ExecutionContext._evaluateInternal (C:\Users\Administrator\Documents\nodejs\bot-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\Administrator\Documents\nodejs\bot-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
TimeoutError: Navigation timeout of 30000 ms exceeded
    at C:\Users\Administrator\Documents\nodejs\bot-whatsapp\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:106:111

**Steps to Reproduce**
`client.reply(message.from, ....., message.id)`

**create() code**
This is the code you use to create the client. e.g
```javascript
const options = {
        sessionId: 'session',
        headless: headless,
        useChrome: true,
        qrTimeout: 0,
        authTimeout: 0,
        restartOnCrash: start,
        cacheEnabled: false,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false,
        chromiumArgs: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--aggressive-cache-discard',
            '--disable-cache',
            '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            '--disk-cache-size=0'
        ]
    }
```

**Expected behavior**
.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
─────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2123.7'                                                                  │
│       PAGE_UA       │ 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '4.5.0'                                                                   │
│   BROWSER_VERSION   │                                                        'HeadlessChrome/91.0.4472.77'                                                        │
│         OS          │                                                                'Windows 10'                                                                 │
│      START_TS       │                                                                1623827498908                                                                │
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Windows 10. MEmu Emulator

**Additional context**

**Comment by smashah** [comment]
@dngda thanks for filling in the issue template

can you share which listeners you're using? Also, how frequently does this happen? Does it only happen after replying to a media message or does it happen every time you try to reply to any message? Or does it happen even if you're not replying to a message?

**Comment by syafiqfaiz** [comment]
I am getting the same error message for both case, 
replying to image/sticker and text

**Comment by syafiqfaiz** [comment]
I am randomly getting this error.

Here is my test code
```javascript
var wa = require('@open-wa/wa-automate');
var _config = require('./config.json');

var _waConfig = {
	sessionId: _config.phone,
	licenseKey: _config.license,
};

var _whatsappStart = (whatsapp) => {

	whatsapp.reply(
		'my_number@c.us',
		'cuba reply',
		'true_my_number@c.us_3EB0742FCC629C20A891'
	).then((msgId) => {
		console.log('sendWhatsappReply', msgId);
	});
	
};

wa.create(_waConfig)
.then(async client => await _whatsappStart(client))
.catch(e => {
	console.log('CREATE ERROR', e.message);
});


```

**Comment by dngda** [comment]
> @dngda thanks for filling in the issue template
> 
> can you share which listeners you're using? Also, how frequently does this happen? Does it only happen after replying to a media message or does it happen every time you try to reply to any message? Or does it happen even if you're not replying to a message?

@smashah I'm using `client.onMessage()` listener and it happen every time when it try to reply to any message using `client.reply()`. Anyway, other function with reply like `client.sendFile()` works fine.

**Comment by smashah** [comment]
https://github.com/open-wa/wa-automate-nodejs/commit/1f30c57266e51a5e84a04c24f07102ce4565d188

@dngda please try again and let me know if you're still experiencing this error in relation to `reply`. It may still error out on other methods.

**Comment by dngda** [comment]
Thank you. `reply` is works as expected.

**Comment by smashah** [comment]
I submitted another patch to fix some other methods affected by this issue. Should all be fixed now. Closing. Thanks

**Comment by group2tts** [comment]
window.WAPI.sendVCard 

VM484:32 Uncaught (in promise) TypeError: c.waitForPrep is not a function
    at bootstrap_qr.3df7948c21bd43e94300.js:2
    at q (bootstrap_qr.3df7948c21bd43e94300.js:2)
    at MutationObserver.H (bootstrap_qr.3df7948c21bd43e94300.js:2)

**Comment by smashah** [comment]
@group2tts i submutted a patch for sendvcard last night. can you restart your session and try again please. thanks

**Comment by group2tts** [comment]
@smashah I use https://github.com/open-wa/wa-automate-nodejs/blob/master/src/lib/wapi.js last change was 4 months ago

**Comment by IanosJunior** [comment]
Helo! I use the API in a project where I inject wapi.js into my browser. Will you fix it too?
You only updated patches.json.
I believe you are not using wapi.js in your project anymore.

**Comment by smashah** [comment]
@group2tts @IanosJunior WAPI.js is no longer being updated.

If you want to integrate the patches into your projects, you will need to do the following

1. [Inject wapi.js](https://github.com/open-wa/wa-automate-nodejs/blob/31b03df945b1916de8d01d5f41c61ae9cb263688/src/controllers/browser.ts#L187)
2. [get patches.json, map over the array and `eval` each line](https://github.com/open-wa/wa-automate-nodejs/blob/31b03df945b1916de8d01d5f41c61ae9cb263688/src/controllers/initializer.ts#L387)
3. [If you need licensed features, get the licensed code from the license server and `eval` the response](https://github.com/open-wa/wa-automate-nodejs/blob/31b03df945b1916de8d01d5f41c61ae9cb263688/src/controllers/initializer.ts#L432)
4. [Inject the `initPatch`](https://github.com/open-wa/wa-automate-nodejs/blob/31b03df945b1916de8d01d5f41c61ae9cb263688/src/controllers/init_patch.ts#L6)

Please note the fixes in `patches.json` require the `initPatch` to work. You do not need to pay anything to implement steps 1-4 and I welcome you to do so; however, this setup will make it so your custom solution will have the same feature segmentation as this library. This is something major to consider as it may result in your custom setup losing access to 1 major feature (sending messages to unknown numbers) - all other licensed features are add-ons to wapi.js

Feel free to contact me over discord to talk more about your custom setups. Maybe there is some way open-wa can make steps 1-4 simpler to implement in your solutions (maybe a separate library for 1-4?)

thanks

**Comment by IanosJunior** [comment]
How do I convert patches.json to javascript functions?
Please help me.

**Comment by IanosJunior** [comment]
@group2tts were you able to extract the javascript?

**Comment by smashah** [comment]
@IanosJunior you can join the discord (click on the discord badge in the readme for an invite) to discuss implementation details further

thanks
