### ISSUE TITLE
Return error message when request body is missing (when it is required)

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#1801]
A user today come to the discord complaining that the API wasn't working. The error message mentioned that the message content was missing. The user was setting all arguments as query params.

The API should return an error showing the user what is actually going wrong.

1. If there are query params
2. And there are no arguments in the json request body

Then return "Please set arguments in the JSON request body, not as query params"

**Comment by IanosJunior** [comment]
Hi partner, could you update wapi.js so that the Reply function continues to work?
I only use this library in my project.
If I purchase the license, can I get access to updated wapi.js?

**Comment by smashah** [comment]
@IanosJunior please see my comment here: https://github.com/open-wa/wa-automate-nodejs/issues/1786#issuecomment-865319322
