### ISSUE TITLE
checkNumberStatus response is not clearly defined

### ISSUE THREAD

**Issue by blackchineykh** [open-wa/wa-automate-nodejs#1802]
**Describe the bug**
The checkNumberStatus function signature is documented to return a contact object but actually doesn't. I usually check for the 'status' property on the returned object but the compiler flags this as not available since I upgraded from version 3.X.X to 4.5.1.

**Steps to Reproduce**
1. call the checkNumberStatus 
2. Check for the contact object properties being returned or null object for not found?

**create() code**
This is the code you use to create the client. e.g
```javascript
create({
    sessionId: sessionId,
    sessionDataPath: sessionDataPath,
    useChrome: false,
    restartOnCrash: start,
    headless: process.env.CHROME_HEADLESS === "true",
    resizable: true,
    throwErrorOnTosBlock: true,
    qrTimeout: 0, //set to 0 to wait forever for a qr scan
    authTimeout: 0, //set to 0 to wait forever for connection to phone
    killProcessOnBrowserClose: false, //need to be false to support reload of service from GUI
    autoRefresh: true,
    safeMode: false,
    disableSpins: false,
    qrRefreshS: 15,
    cacheEnabled: false,
    blockCrashLogs: true,
    useStealth: true,
    viewport:{
      height: 800,
      width:800
    },
  })
```

**Expected behavior**
I expect a number status check object to be returned which match the object properties being returned seen below:
```
{
  id: {
    server: 'c.us',
    user: 'XXXXXXXXXXX',
    _serialized: 'XXXXXXXXXXX@c.us'
  },
  status: 200,
  isBusiness: false,
  canReceiveMessage: true,
  numberExists: true
}

```

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                   Values
                                                │
├─────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2123.7'
                                                │
│       PAGE_UA       │ 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '4.5.1'
                                                │
│   BROWSER_VERSION   │                                                            'Chrome/83.0.4103.0'
                                                │
│         OS          │                                                                'Windows 10'
                                                │
│      START_TS       │                                                                1624316796840
                                                │
└─────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Additional context**
I also noticed that the source for checkNumberStatus definition in Client.ts shows `const checkNumberStatus: (contactId: string) => any;` but the implementation returns the Contact object as a promise so im not sure what's the one expected or you wish to have a separate model for this response.

Looking forward to your guidance. Thanks again for your great work!

**Comment by smashah** [comment]
@blackchineykh thank you for filling out the template perfectly. I will fix this asap.

**Comment by smashah** [comment]
@blackchineykh types should be fixed in v 4.6.0 now thanks

**Comment by luidigo** [comment]
Hey, I'am having problem with this function. It's not returning anything.
This problem began with new whatsapp multi-device version.

`{
    id: 'WapQuery',
    conditions: (module) => (module.default && module.default.queryExist) ? module.default : null
}`

and

`Store.WapQuery.queryExist("1111111111@c.us")`

Anyone with same problem?

**Comment by lukasportal** [comment]
same here, the promise never returns
i suspect there's something to do with the new way whatsapp communicates with encrypted messages on a new /ws/chat endpoint
