### ISSUE TITLE
Feature Request: Add in-built awaitMessages like discord.js

### ISSUE THREAD

**Issue by Waxaranai** [open-wa/wa-automate-nodejs#1810]
Reference Links: https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=awaitMessages

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci minor`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.6.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.5.1...4.6.0) (2021-06-23)

- build(deps-dev): bump typedoc from 0.20.36 to 0.21.0 [`#1799`](https://github.com/open-wa/wa-automate-nodejs/pull/1799)
- build(deps-dev): bump @types/node from 15.6.1 to 15.12.4 [`#1800`](https://github.com/open-wa/wa-automate-nodejs/pull/1800)
- build(deps-dev): bump @grupoboticario/news-fragments from 1.10.0 to 1.12.0 [`#1807`](https://github.com/open-wa/wa-automate-nodejs/pull/1807)
- build(deps-dev): bump release-it from 14.8.0 to 14.10.0 [`#1798`](https://github.com/open-wa/wa-automate-nodejs/pull/1798)
- build(deps-dev): bump @typescript-eslint/eslint-plugin from 4.26.1 to 4.28.0 [`#1803`](https://github.com/open-wa/wa-automate-nodejs/pull/1803)
- build(deps-dev): bump eslint from 7.28.0 to 7.29.0 [`#1805`](https://github.com/open-wa/wa-automate-nodejs/pull/1805)
- build(deps): bump open from 8.2.0 to 8.2.1 [`#1806`](https://github.com/open-wa/wa-automate-nodejs/pull/1806)
- build(deps-dev): bump marked from 2.0.7 to 2.1.2 [`#1808`](https://github.com/open-wa/wa-automate-nodejs/pull/1808)
- build(deps): bump type-fest from 1.2.0 to 1.2.1 [`#1788`](https://github.com/open-wa/wa-automate-nodejs/pull/1788)
- build(deps-dev): bump @typescript-eslint/parser from 4.26.1 to 4.28.0 [`#1804`](https://github.com/open-wa/wa-automate-nodejs/pull/1804)
- Release 4.6.0 [`f273664`](https://github.com/open-wa/wa-automate-nodejs/commit/f27366485bdbee5fa3b7f99d3cb6aa43eda2befe)
- 📝 docs: fix `awaitMessages` example docs [`1462cb3`](https://github.com/open-wa/wa-automate-nodejs/commit/1462cb3a692968eba10a8b0d2d5280e89fbd4734)
- ✨ feat: `awaitMessages` #1810 [`3c4034a`](https://github.com/open-wa/wa-automate-nodejs/commit/3c4034a17692aeb7fd47501977cbfc49608b3ab8)
- 🏷️ types: `checkNumberStatus` promise now returns `NumberCheck` #1802 [`757cf81`](https://github.com/open-wa/wa-automate-nodejs/commit/757cf810dbd0f9e806e645b184c95816d2c87188)
- 🥅 cli: Add more information in error message if args miss/query params found #1801 [`173bfcb`](https://github.com/open-wa/wa-automate-nodejs/commit/173bfcbad0cc236410bc12549b0a2a48098fcd91)
- 🐛 #1801 [`7c9fac6`](https://github.com/open-wa/wa-automate-nodejs/commit/7c9fac626efa05affe89f2368806fbe5afa65fea)
- 🥚  patches update [`31b03df`](https://github.com/open-wa/wa-automate-nodejs/commit/31b03df945b1916de8d01d5f41c61ae9cb263688)
- 🥚 patches update [`8b32268`](https://github.com/open-wa/wa-automate-nodejs/commit/8b322689810b1017249cdbc92c370500dbedac7e)
- 🥚 patches update [`b0a4264`](https://github.com/open-wa/wa-automate-nodejs/commit/b0a4264e7d01f09e2e371c1ee72f709858d7a3de)

**Comment by smashah** [comment]
leaving issue open for feedback

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>
