### ISSUE TITLE
[Feature Request] Query `order` by `orderId`

### ISSUE THREAD

**Issue by HypedMind** [open-wa/wa-automate-nodejs#1811]
Summary: To get the order details from an `orderId` embed in `message` object

 ![](https://i.imgur.com/fENdvbx.png)

Scenario:
- User visits WABA and added products to cart
- User sends the cart to WABA
- WABA receives onAck message with an `orderId`

Feature Request:
- To get order details from `orderId`

What I have researched:
- While inspecting WA web app, WA will sends a web socket query request
 ![](https://i.imgur.com/RQtfltN.png)

- and then will receive response as such:
-  ![](https://i.imgur.com/LGiG7tP.png)

- so essentially: convert an `orderId` to the total price and list of products inside the JSON
Hope we will got this feature and will not hesitate to contribute more in license :)

**Comment by smashah** [comment]
@HypedMind that's pretty cool. I'll look into it

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci minor`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
@HypedMind please dm me on discord for your free keys. thanks for the suggestion

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.7.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.6.0...4.7.0) (2021-06-23)

- Release 4.7.0 [`d1cc772`](https://github.com/open-wa/wa-automate-nodejs/commit/d1cc77223133408e5cea2239eb9e55d4a1fbe337)
- 🏷️ added types for cart/order #1811 [`0a7ba88`](https://github.com/open-wa/wa-automate-nodejs/commit/0a7ba88282f1c0dc75a15407afd2da9e85cb10cd)
- ✨ insiders: `getOrder` & `onOrder` for business accounts #1811 [`a14cf78`](https://github.com/open-wa/wa-automate-nodejs/commit/a14cf78658fd416efe7ab1f37a058bb68a9e2936)
- 🏷️  fix collection filter typing #1810 [`7cad7a3`](https://github.com/open-wa/wa-automate-nodejs/commit/7cad7a3bfa98ce495b57947b35b7f26b98020bb0)
- 🚨 fix `CollectorFilter` ts warnings [`f090003`](https://github.com/open-wa/wa-automate-nodejs/commit/f0900032dbd9208d073ce1628d395183ed9ae955)

**Comment by HypedMind** [comment]
@smashah Thanks for the quick release! Am excited to try it 🙏🏻🙏🏻

**Comment by smashah** [comment]
Insiders with 4.7.0 can now use [`client.getOrder`](https://docs.openwa.dev/classes/api_client.client.html#getorder)

```javascript
	client.onMessage(message=>{
		if(message.type=="order"){
			//or you can use message.orderId;
			const order = await client.getOrder(message.id)
		}
	})
```

or listen to incoming orders with [`client.onOrder`](https://docs.openwa.dev/classes/api_client.client.html#onorder)

```javascript
	client.onOrder(order=>{
            console.log("New order from", order.message.from)
            console.log("Products:", order.products.length)
            console.log("First Products", order.products[0].name)
            console.log("Total", order.subtotal)
	})
```

thanks for the great suggestion
