### ISSUE TITLE
Error when running in ubuntu

### ISSUE THREAD

**Issue by Dezkrazzer** [open-wa/wa-automate-nodejs#1822]
**Describe the bug**

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/43921327/123540628-3889eb00-d76a-11eb-9523-e45820075100.png)

**Host (please complete the following information):**
 - OS: ubuntu

**Additional context**

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
