### ISSUE TITLE
Cannot install in ubuntu 20.04 & 18

### ISSUE THREAD

**Issue by DiyRex** [open-wa/wa-automate-nodejs#1832]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @open-wa/wa-automate@4.7.1 install: `cross-env npm_config_yes=true npx ignore-check@latest -p '**.data.json' -p '**.node-persist**' --comment 'managed by open-wa'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @open-wa/wa-automate@4.7.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by smashah** [comment]
@DiyRex please make sure you are using:
node: `v14.15.0+`
npm: `v7.12.0+`

then try again

**Comment by DiyRex** [comment]
> @DiyRex please make sure you are using:
> node: `v14.15.0+`
> npm: `v7.12.0+`
> 
> then try again

I tried to install chrome manually. Then it worked. Thank you for the reply. Stay Safe 🙂❤️
