### ISSUE TITLE
Request : add `message.sendText()` instead of `client.sendText()`

### ISSUE THREAD

**Issue by BbayuGt** [open-wa/wa-automate-nodejs#1837]
To make thing simple. Isn't it good to add `sendText` (or other sending method) to `message` object. Instead of
```js
client.sendText(from, text)
```
it Will be a lot better if we can
```js
message.sendText(text) //the "from" will automatically passed inside
```
Of course `client.sendText` is still good if you want to use it to send message to other number/group. Sometimes its a pain to add `message.from` or `message.id` (especially in `reply`) every single time when you want to send a message

**Comment by wlskcode** [comment]
You know, you can create a function on your app that does that...  lol

```
//const { id, from} = message
const msgText = (text) => client.sendText(from, text);

msgText("I love wa-automate") 
```

Now messageText function is a concise way to send texts with no need to type "client" or "from". However this can be improved upon.

**Comment by BbayuGt** [comment]
Might use it for now.

**Comment by smashah** [comment]
I think @wlskcode is right, just use that.

closing.

thanks
