### ISSUE TITLE
ReferenceError: getQrPng is not defined

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-nodejs#1864]
After new update 4.8.1 getting following error

> - Launching Browser
    - Setting Up Browser
    - Loading session data
    - No session data file found for session : session
    - Navigating to WA
    - Page loaded in 1394ms: 200
    - Browser Launched
    ┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
    │       (index)       │                                                                   Values                                                                    │
    ├─────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
    │     WA_VERSION      │                                                                 '2.2126.10'                                                                 │
    │       PAGE_UA       │ 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
    │ WA_AUTOMATE_VERSION │                                                                   '4.8.1'                                                                   │
    │   BROWSER_VERSION   │                                                       'HeadlessChrome/91.0.4472.114'                                                        │
    │         OS          │                                                                'Linux 4.19'                                                                 │
    │      START_TS       │                                                                1625839993836                                                                │
    └─────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
    - Downloading patches from https://cdn.openwa.dev/patches.json
    - Injecting api
    - WAPI injected
    - Authenticating
    - Authenticate to continue
    - Generating patch hash
    - Downloaded patches in 1.474s
    - Something went wrong while retreiving new the QR code but it should not affect the session launch procedure: Evaluation failed: ReferenceError: getQrPng is not defined
        at __puppeteer_evaluation_script__:1:1

**Comment by ce-marcogaruthi** [comment]
same problem here

**Comment by smashah** [comment]
@manojsitapara keep an eye on #1860, I submitted a release 4.8.2 should have the fix and should be available shortly. thanks for your patience

**Comment by smashah** [comment]
@manojsitapara @ce-marcogaruthi please update to 4.8.2

**Comment by manojsitapara** [comment]
Working Now ! Thank you @smashah for your quick help. Really appreciate your effort.
