### ISSUE TITLE
GA: `clearAllChats`

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#1865]
- [ ] #1869

Please suggest one other insider's feature to migrate to GA in a comment below.

Thanks

**Comment by chgss** [comment]
Thanks @smashah

**Comment by dngda** [comment]
Maybe, I would love to have tag member in caption with `sendImage`

**Comment by smashah** [comment]
@dngda great suggestion. Accepted

**Comment by slavecode** [comment]
`removeParticipant, promoteParticipant, demoteParticipant` not working on open-wa version 4.8.2

**Comment by smashah** [comment]
keep track of #1869 for the extra param in clearallchats.

@dngda you should now be able to tag people in media.

Closing.

Thanks
