### ISSUE TITLE
Session data most likely expired due to manual host account logout.

### ISSUE THREAD

**Issue by aftercxde** [open-wa/wa-automate-nodejs#1867]
### **I can't create a new session**
When I try to create a new session or enter with a session already created i get the error:

**x Session data most likely expired due to manual host account logout. Please re-authenticate this session.**

 I have killed the session from the device but got no changes
 
 
![Captura](https://user-images.githubusercontent.com/44219930/125124792-4589d100-e0be-11eb-93a8-e1af3e43f99b.PNG)

**Comment by viminio** [comment]
I too

**Comment by oAnjinho** [comment]
I too ;-;

**Comment by oAnjinho** [comment]
> I too ;-;

i did the update and now it's working :3

**Comment by smashah** [comment]
@aftercxde please update to the latest version
