### ISSUE TITLE
`getIndicatedNewMessages()` is returning an array of objects with empty indicatedNewMessages arrays

### ISSUE THREAD

**Issue by feliperaul** [open-wa/wa-automate-nodejs#1871]
**Describe the bug**
getIndicatedNewMessages() is returning an array of objects that have no messages. 

**Steps to Reproduce**

I just did a big update in my project from version `3.6.11` to latest (4.8.2), and it broke `client.getIndicatedNewMessages()`. 

According to the [docs](https://docs.openwa.dev/classes/api_client.client.html#getindicatednewmessages), it should return an array of objects like this:

```js
[{
"id": "000000000000@g.us", //the id of the chat
"indicatedNewMessages": [] //array of messages, not including any messages by the host phone
}]
```

Before the update, there were always messages in `indicatedNewMessages`, since an empty array there makes no sense (if there aren't any indicatedNewMessages, then this chat should not be present in `getIndicatedNewMessages` in the first place). 

However, after the update, this is the return I'm getting from this method:

```js
[
  { id: 'xx@c.us', indicatedNewMessages: [] },
  { id: 'xx@c.us', indicatedNewMessages: [] },
  { id: 'xx@c.us', indicatedNewMessages: [] },
  { id: 'xx@c.us', indicatedNewMessages: [] },
  { id: 'xx@c.us', indicatedNewMessages: [] },
  { id: 'xx@c.us', indicatedNewMessages: [] },
  { id: 'xx@c.us', indicatedNewMessages: [] },
  { id: 'xx@c.us', indicatedNewMessages: [] },
  { id: 'xx@c.us', indicatedNewMessages: [] },
  { id: 'xx@c.us', indicatedNewMessages: [] }
]
```

As you can see, the objects have an empty array in indicatedNewMessages. 

1. I just

**create() code**
This is the code you use to create the client. e.g
```javascript
const client = await wa.create({
    sessionId: `session_${LocalConfig.session_name}_${LocalConfig.phone_from}`,
    {
    licenseKey: 'my_license',
    useStealth: true,
    headless: false,
    defaultViewport: false,
    chromiumArgs: ['--start-maximized', '--window-size=1920,1080'],
    useChrome: true,
  }
  });
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
     WA_VERSION      │                                                                 '2.2126.11'                                                                 │
│       PAGE_UA       │ 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '4.8.2'                                                                   │
│   BROWSER_VERSION   │                                                           'Chrome/91.0.4472.114'                                                            │
│         OS          │                                                              'macOS Catalina'
}
```

**Host (please complete the following information):**
 - OS: Mac OSX 10.15.7

**Comment by feliperaul** [comment]
@smashah For reference, you implemented this on  #297

**Comment by smashah** [comment]
@feliperaul got your email. Will be fixed tonight via a patch. thanks

**Comment by smashah** [comment]
@feliperaul I am testing this right now and am unable to replicate the problem.

![CleanShot 2021-07-12 at 21 46 58](https://user-images.githubusercontent.com/5903821/125353744-d7156f00-e35a-11eb-93a3-f3cf1d8c87e9.png)

Can you share a screenshot of your device chat list so we can see what's going on?

**Comment by feliperaul** [comment]
@smashah Just emailed it to you!

**Comment by smashah** [comment]
@feliperaul haven't received an email with the screenshot

**Comment by feliperaul** [comment]
@smashah My bad, just sent it now!

**Comment by smashah** [comment]
@feliperaul thanks. I think this issue is only affecting business accounts. I'll investigate further.

**Comment by smashah** [comment]
2 things.

1. (not shown in this screenshot) A chat may have 6 unread messages indicated but only 1 loaded in the session. In an upcoming patch, it will try to load more messages before returning the result

2. System messages also show up in the indicator. After 1. is resolved you can just ignore the empty arrays going forward.

![CleanShot 2021-07-13 at 01 38 05](https://user-images.githubusercontent.com/5903821/125372511-2e2b3c00-e37b-11eb-86da-3f68c287980b.png)

**Comment by smashah** [comment]
@feliperaul I submitted a new patch to fix this. Can you test out and confirm, please. Thanks

**Comment by feliperaul** [comment]
@smashah Everything is working again! 🚀
