### ISSUE TITLE
Error: Evaluation failed: ReferenceError: getQrPng is not defined     at __puppeteer_evaluation_script__:1:1

### ISSUE THREAD

**Issue by can1871** [open-wa/wa-automate-nodejs#1889]
(node:10096) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: getQrPng is not defined
    at __puppeteer_evaluation_script__:1:1
    at ExecutionContext._evaluateInternal (C:\Users\canma\node_modules\puppeteer\src\common\ExecutionContext.ts:219:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ExecutionContext.evaluate (C:\Users\canma\node_modules\puppeteer\src\common\ExecutionContext.ts:138:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
