### ISSUE TITLE
Error: Evaluation failed: ReferenceError: getQrPng is not defined at __puppeteer_evaluation_script__:1:1

### ISSUE THREAD

**Issue by can1871** [open-wa/wa-automate-nodejs#1890]
![1](https://user-images.githubusercontent.com/53393674/125438926-93a22c4f-ec50-484a-bb7a-0336d41e5078.PNG)

![2](https://user-images.githubusercontent.com/53393674/125438922-48cdd99a-636f-4d92-8d15-deac7eb8ac93.PNG)

**Comment by smashah** [comment]
@can1871 you're using a super old version of the library. Please update it to the latest version 4.9.0 and try again

**Comment by can1871** [comment]
I thought I updated it but I guess it's still using the old version. I will try to remove the old one and install the new one. Thanks

**Comment by can1871** [comment]
I fixed it. it is working now. thanks
