### ISSUE TITLE
Error getProfilePicFromServer()

### ISSUE THREAD

**Issue by slavecode** [open-wa/wa-automate-nodejs#1901]
when they don't use a profile picture an error like this  `Error! Error: Evaluation failed: i`

**Comment by smashah** [comment]
@slavecode This is happening because you are hitting a 429 error

- [ ] Clearly state 429 error (too many requests)
- [ ] First check Chat/contact object for profile picture before trying to grab it from the server

**Comment by smashah** [comment]
@slavecode should now respond with the error status code from now on. thanks
