### ISSUE TITLE
Can't add wapi functions ?

### ISSUE THREAD

**Issue by Cephas369** [open-wa/wa-automate-nodejs#1907]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

When i change something in wapi it throws the error "Session data most likely expired due to manual host account logout. Please re-authenticate this session" and restarts continuously

### Mode

My own code

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

**Comment by smashah** [comment]
@Cephas369 WAPI is locked. If you have any suggestions for features I can implement them as patches.
