### ISSUE TITLE
Making onClick on button

### ISSUE THREAD

**Issue by BbayuGt** [open-wa/wa-automate-nodejs#1911]
Hey i have a suggestion. As you know that button have id. I wonder theres way to hook it. Like when you click it, and send message with text that you get when you click it. It'll run a function. Like

```js
buttonMsg.click(id, callback)
```
Or more "open-wa" way (using client)
```js
client.buttonClick(messageId, buttonId, callback)
```
theres no way id has nothing else todo except just key in object.

**Comment by BbayuGt** [comment]
Update :
Client will respond with messageType "buttons_response".
You also have selectedButtonId inside. So you know what button the user click without needing what text the user send

**Comment by Bautista-Baiocchi-lora** [comment]
Hello, I am also very interested in being able to listen to button clicks. 

I'd suggest an implementation similar to Telegram's chat buttons. Here is an example implementation that uses the [Telegraf API](https://github.com/telegraf/telegraf). Telegraf is a wrapper for the official Telegram API. It adds utility and quality of life methods to the underlying telegram client.

Example:

As we can see in the snippet below, the button schema is predefined. Each button is defined by its text (button text body), callback_data (a simple string), and grid position. The grid position is defined by the index of the button in the 2d-array (helpButtons). We can expect this code snippet to produce a message with 6 buttons organized into 3 rows and 2 columns, respectively. 

```
const helpButtons = [
  [
    { text: "Dólar", callback_data: "dolar-help" },
    { text: "NYSE", callback_data: "nyse-help" },
  ],
  [
    { text: "Cripto", callback_data: "cripto-help" },
    { text: "Granos", callback_data: "granos-help" },
  ],
  [
    { text: "Lista de Comandos", callback_data: "list-commands-help" },
    { text: "Lista de Canales", callback_data: "list-channels-help" },
  ],
];

const helpMessage = ["<strong>Como te puedo ayudar?</strong>"];

const HelpRoute = async (ctx) => {

  await ctx.replyWithHTML(helpMessage.join("\n"), {
    reply_markup: {
      inline_keyboard: helpButtons,
    },
  });
};

const useHelpModule = (bot) => {
  bot.help(HelpRoute);
};

export default useHelpModule;
```


The ```callback_data``` button attribute is registered as an "action" on the Telegraf Bot instance. When a button is clicked, its action is fired, subsequently triggering the listeners for that action. Below is an example of how the "nyse-help" action defined by the "NYSE" button above (helpButtons) is registered to the bot instance with ```WallstreetHelper``` as the trigger function.


```
const WallstreetHelper = async (ctx) => {
  const helpMessage = ["hello" , "world"];

  await ctx.replyWithHTML(helpMessage.join("\n"));
};

const useWallstreetModule = (bot) => {
  bot.action("nyse-help", WallstreetHelper);
};

export default useWallstreetModule;
```

Relevant documentation links:
> [Telegram #sendMessage()](https://telegrafjs.org/#/?id=sendmessage)
> [InlineKeyboardButton](https://core.telegram.org/bots/api#inlinekeyboardmarkup)
> [Button Callback Query](https://core.telegram.org/bots/api#callbackquery)


I'd love to collaborate on the development of this feature through discourse and my own personally coding time. Cheers, friends.

**Comment by OmarAttia** [comment]
This is really confusing and shouldn’t be open, we already have the onincoming event, on any message and even collectors. You have all the tools to make everything!

**Comment by Bautista-Baiocchi-lora** [comment]
> This is really confusing and shouldn’t be open, we already have the onincoming event, on any message and even collectors. You have all the tools to make everything!

Could you elaborate how those tools could be used to create a function listener pattern?

**Comment by BbayuGt** [comment]
> This is really confusing and shouldn’t be open, we already have the onincoming event, on any message and even collectors. You have all the tools to make everything!

What is the use of button if you couldn't do anything with it?

**Comment by smashah** [comment]
Buttons are a new feature and there can be some more quality of life improvements around working with them.

**Comment by kmirea** [comment]
Guys is it ok if i ask here, what is the response (onIncoming) for a button press ? is there a way to distinguish which of the (3) buttons were pressed, im assuming its treated like a regular text message.

Wont be able to test for a while, im many builds behind. D:  But amazing work @smashah i didnt expect wed get this at all <3

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci minor`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.16.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.15.0...4.16.0) (2021-08-18)

- build(deps-dev): bump marked from 2.1.3 to 3.0.0 [`#2022`](https://github.com/open-wa/wa-automate-nodejs/pull/2022)
- Release 4.16.0 [`346b97f`](https://github.com/open-wa/wa-automate-nodejs/commit/346b97f89eabe9477765b2d3b349b4464d5cccb0)
- 📝  docs update [`bc92a68`](https://github.com/open-wa/wa-automate-nodejs/commit/bc92a68bc3afe93e9da587dd0042743e4f9e3daa)
- 🏷️ types: update `Message` types for list and button response messages #1911 [`e8ee17d`](https://github.com/open-wa/wa-automate-nodejs/commit/e8ee17dada6df04c39a4f17b275bbd296347ccc1)
- ✨ feat: `client.onButton` for button and list responses #1911 [`a42910f`](https://github.com/open-wa/wa-automate-nodejs/commit/a42910f9f0bf5f70f8b902033fee0205dd299e03)
- 🐛  fix section type import reference [`3547c1b`](https://github.com/open-wa/wa-automate-nodejs/commit/3547c1bdf095927ef0d64f75d3680d7f83af2adb)
- 🥚 patches update [`a50ba56`](https://github.com/open-wa/wa-automate-nodejs/commit/a50ba568d14cbc5fe7ce97d709cb664d58022c37)
- 🔊 easy api: `onLogout` log fix [`38f79b3`](https://github.com/open-wa/wa-automate-nodejs/commit/38f79b3354c3b761d11e2062dedb5074762a6c62)
- 🥚  patches [`1a28a15`](https://github.com/open-wa/wa-automate-nodejs/commit/1a28a153a5b27a54c6281ee9eb3e610079bd587c)

**Comment by smashah** [comment]
Ok here's a bit of a guide to `onButton`. It basically is the same as onMessage but only emits when a button or list response is detected. The `buttonResponse` object is the same/an extension of the `Message` object. The message type itself has been updated to reflect the new changes


```javascript
client.onButton(async buttonResponse => {
    if (buttonResponse.type == 'buttons_response') {
        //id of selected button is buttonResponse.selectedButtonId
        console.log(`User ${buttonResponse.from} selected ${buttonResponse.selectedButtonId}`)
        const sourceButtons = buttonResponse.quotedMsgObj.buttons
    }
    if (buttonResponse.type == 'list_response') {
        //id of selected list item is buttonResponse.selectedButtonId.rowId
        console.log(`User ${buttonResponse.from} selected ${buttonResponse.listResponse.rowId}`)

        //source list response is buttonResponse.quotedMsgObj.list
        const sourceList = buttonResponse.quotedMsgObj.list
    }
})
```

**Comment by cantiir2** [comment]
> Ok here's a bit of a guide to `onButton`. It basically is the same as onMessage but only emits when a button or list response is detected. The `buttonResponse` object is the same/an extension of the `Message` object. The message type itself has been updated to reflect the new changes
> 
> ```js
> client.onButton(async buttonResponse => {
>     if (buttonResponse.type == 'buttons_response') {
>         //id of selected button is buttonResponse.selectedButtonId
>         console.log(`User ${buttonResponse.from} selected ${buttonResponse.selectedButtonId}`)
>         const sourceButtons = buttonResponse.quotedMsgObj.buttons
>     }
>     if (buttonResponse.type == 'list_response') {
>         //id of selected list item is buttonResponse.selectedButtonId.rowId
>         console.log(`User ${buttonResponse.from} selected ${buttonResponse.listResponse.rowId}`)
> 
>         //source list response is buttonResponse.quotedMsgObj.list
>         const sourceList = buttonResponse.quotedMsgObj.list
>     }
> })
> ```

I've tried this and it works, but the button can't respond to what I make the button
