### ISSUE TITLE
Unable to use wa-automate on Heroku

### ISSUE THREAD

**Issue by Elquemao** [open-wa/wa-automate-nodejs#1915]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

I deployed my project using wa-automate.
But when I deployed it on Heroku, is stucked on this part
![heroku](https://user-images.githubusercontent.com/50182724/126045180-9ac46311-20eb-44ac-832c-68e138cc2ef0.PNG)

I tried on REPL too, but is sutcked at the same part.
![repl](https://user-images.githubusercontent.com/50182724/126045212-b4478dae-d64c-4845-8953-f4c6acd3e66a.PNG)

On local I can use it without problems.
![local](https://user-images.githubusercontent.com/50182724/126045238-2dac6d22-dffb-4a75-999b-f79632c39763.PNG)

Thank you.

### Mode

My own code

### Environment

```markdown
- OS: 
- Node: 12.22.1
- npm: 6.14.12
```

**Comment by wlskcode** [comment]
Yup, I'm having difficulties using wa automate on heroku as well. It just doesn't start up.

`

- 2021-07-19T03:07:41.644357+00:00 app[worker1.1]: 03:07:41 0|ava    | - Starting
- 2021-07-19T03:07:41.644484+00:00 app[worker1.1]: 03:07:41 0|ava    | - Version: 4.11.1
- 2021-07-19T03:07:41.644601+00:00 app[worker1.1]: 03:07:41 0|ava    | - Initializing WA
- 2021-07-19T03:07:41.644727+00:00 app[worker1.1]: 03:07:41 0|ava    | - Launching Browser
- 2021-07-19T03:07:41.879751+00:00 app[worker1.1]: 03:07:41 0|ava    | - Setting Up Browser
- 2021-07-19T03:07:41.893426+00:00 app[worker1.1]: 03:07:41 0|ava    | - Loading session data
- 2021-07-19T03:07:41.894174+00:00 app[worker1.1]: 03:07:41 0|ava    | - Found session data file: /app/Ava.data.json
- 2021-07-19T03:07:41.896219+00:00 app[worker1.1]: 03:07:41 0|ava    | - Existing session data detected. Injecting...
- 2021-07-19T03:07:41.896440+00:00 app[worker1.1]: 03:07:41 0|ava    | - Existing session data injected
- 2021-07-19T03:07:41.896690+00:00 app[worker1.1]: 03:07:41 0|ava    | - Navigating to WA
- 2021-07-19T03:07:42.722265+00:00 app[worker1.1]: 03:07:42 0|ava    | - Page loaded in 824ms: 200
- 2021-07-19T03:07:42.725215+00:00 app[worker1.1]: 03:07:42 0|ava    | - Browser Launched
- 2021-07-19T03:07:43.076203+00:00 app[worker1.1]: 03:07:43 0|ava    | ┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
- 2021-07-19T03:07:43.076297+00:00 app[worker1.1]: 03:07:43 0|ava    | │       (index)       │                                                                   Values                                                                    │
- 2021-07-19T03:07:43.076385+00:00 app[worker1.1]: 03:07:43 0|ava    | ├─────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
- 2021-07-19T03:07:43.076491+00:00 app[worker1.1]: 03:07:43 0|ava    | │     WA_VERSION      │                                                                 '2.2126.11'                                                                 │
- 2021-07-19T03:07:43.076594+00:00 app[worker1.1]: 03:07:43 0|ava    | │       PAGE_UA       │ 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
- 2021-07-19T03:07:43.076702+00:00 app[worker1.1]: 03:07:43 0|ava    | │ WA_AUTOMATE_VERSION │                                                                  '4.11.1'                                                                   │
- 2021-07-19T03:07:43.076822+00:00 app[worker1.1]: 03:07:43 0|ava    | │   BROWSER_VERSION   │                                                       'HeadlessChrome/91.0.4472.164'                                                        │
- 2021-07-19T03:07:43.076883+00:00 app[worker1.1]: 03:07:43 0|ava    | │         OS          │                                                                 'Linux 4.4'                                                                 │
- 2021-07-19T03:07:43.076987+00:00 app[worker1.1]: 03:07:43 0|ava    | │      START_TS       │                                                                1626664062728                                                                │
- 2021-07-19T03:07:43.077096+00:00 app[worker1.1]: 03:07:43 0|ava    | └─────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
- 2021-07-19T03:07:43.080108+00:00 app[worker1.1]: 03:07:43 0|ava    | - Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&debug_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2126.11%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.11.1%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/91.0.4472.164%22,%0A%20%20%22START_TS%22:%201626664062728%0A%7D&environment=-%20OS:%20Linux%204.4%0A-%20Node:%2016.3.0%0A-%20npm:%20%0A
- 2021-07-19T03:07:43.080777+00:00 app[worker1.1]: 03:07:43 0|ava    | - Injecting api
- 2021-07-19T03:07:43.829775+00:00 app[worker1.1]: 03:07:43 0|ava    | - WAPI injected
- 2021-07-19T03:07:43.830286+00:00 app[worker1.1]: 03:07:43 0|ava    | - Authenticating
- 2021-07-19T03:07:45.714063+00:00 app[worker1.1]: 03:07:45 0|ava    | - Authenticated
- 2021-07-19T03:07:45.714696+00:00 app[worker1.1]: 03:07:45 0|ava    | - Reinjecting api
- 2021-07-19T03:07:45.788512+00:00 app[worker1.1]: 03:07:45 0|ava    | - WAPI Reinjected
- 2021-07-19T03:07:45.789158+00:00 app[worker1.1]: 03:07:45 0|ava    | - Checking if session is valid
- 2021-07-19T03:07:45.791080+00:00 app[worker1.1]: 03:07:45 0|ava    | - Downloading patches from https://cdn.openwa.dev/patches.json
- 2021-07-19T03:07:45.791608+00:00 app[worker1.1]: 03:07:45 0|ava    | - Client is ready
- 2021-07-19T03:07:45.862112+00:00 app[worker1.1]: 03:07:45 0|ava    | - Generating patch hash
- 2021-07-19T03:07:45.866089+00:00 app[worker1.1]: 03:07:45 0|ava    | - Downloaded patches in 0.071s
- 2021-07-19T03:07:45.919478+00:00 app[worker1.1]: 03:07:45 0|ava    | - Installing patches
- 2021-07-19T03:07:46.091631+00:00 app[worker1.1]: 03:07:46 0|ava    | - Patches Installed: 2ab7c
- 2021-07-19T03:07:46.113675+00:00 app[worker1.1]: 03:07:46 0|ava    | - Client loaded with 0 contacts, 0 chats & 0 messages in 4.62s
- 2021-07-19T03:07:46.258503+00:00 app[worker1.1]: 03:07:46 0|ava    | Browser page has closed. Killing client
- 2021-07-19T03:07:46.258962+00:00 app[worker1.1]: 03:07:46 0|ava    | Shutting Down
- 2021-07-19T03:07:46.353339+00:00 app[worker1.1]: 2021-07-19T03:07:46: PM2 log: App [ava:0] exited with code [0] via signal [SIGINT]
- 2021-07-19T03:07:46.354628+00:00 app[worker1.1]: 2021-07-19T03:07:46: PM2 log: App [ava:0] starting in -fork mode-
- 2021-07-19T03:07:46.355758+00:00 app[worker1.1]: 03:07:46 PM2      | App [ava:0] exited with code [0] via signal [SIGINT]
- 2021-07-19T03:07:46.357205+00:00 app[worker1.1]: 03:07:46 PM2      | App [ava:0] starting in -fork mode-
- 2021-07-19T03:07:46.364569+00:00 app[worker1.1]: 2021-07-19T03:07:46: PM2 log: App [ava:0] online
- 2021-07-19T03:07:46.365515+00:00 app[worker1.1]: 03:07:46 PM2      | App [ava:0] online

` 
And then the same error keeps going on and on, while on my local machine it runs just fine.

**Comment by smashah** [comment]
It may be due to resource constraints on your heroku deployments. The base 500mb one isn't enough imo.

As you can see, the message ` Browser page has closed` shows that something crashed the browser which in turn crashed the program.

For now I would suggest deploying a 2gb minimum ubuntu vps on DO and deploy there. Soon there will be an official paid openwa managed service and you will be able to deploy easily from there.

Discuss further in discord. thanks
