### ISSUE TITLE
 How does open-wa / wa-automate work on termux

### ISSUE THREAD

**Issue by Sambosa711** [open-wa/wa-automate-nodejs#1919]
How does open-wa / wa-automate work on termux

----------------------

**Comment by smashah** [comment]
https://github.com/open-wa/wa-automate-nodejs/issues/1815#issuecomment-867545354

**Comment by Sambosa711** [comment]
I want it to work like @adiwajshing/baileys

**Comment by Sambosa711** [comment]
WebSocket

**Comment by smashah** [comment]
Keep an eye on the repo. Big feature dropping soon for insiders in that regard

**Comment by Sambosa711** [comment]
Thank you 🤩🤩
