### ISSUE TITLE
GA: ????

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#1925]
I'm taking requests for an insider's feature to become GA

**Comment by WolfDWyc** [comment]
Can you do list messages?

**Comment by smashah** [comment]
@WolfDWyc that was recently made an insiders feature so unfortunately not that one.

**Comment by dngda** [comment]
how about `onMessageDeleted`?

**Comment by smashah** [comment]
@dngda that's a good suggestion. Done

**Comment by danirepos** [comment]
maybe `sendReplyWithMentions`?

**Comment by smashah** [comment]
`onMessageDeleted` is GA in v4.12.0

@danirepos I'll keep that as a suggestion for the next GA event.

thanks!

**Comment by smashah** [comment]
@danilocodes `sendReplyWithMentions` will be GA in upcoming patches. thanks for the suggestion.

track: #1984
