### ISSUE TITLE
Qr code

### ISSUE THREAD

**Issue by marwanabaris** [open-wa/wa-automate-nodejs#1934]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Is there any possibility of fetching the QR code with Nodejs? 
Not sure if it's a bug but even when importing ev using 'const ev = require('@open-wa/wa-automate').ev' it doesn't seem to be working. 

Is this TS specific and only working for TS?

### Expected Behavior

Print QR

### Mode

EASY API/CLI

### create() code

```markdown
const wa = require('@open-wa/wa-automate')
ev = require('@open-wa/wa-automate').ev
//mport ev from '@open-wa/wa-automate';

const Discord = require('discord.js');

let monitorArr = []

//discord()
//waClient()
//async function waClient(){
wa.create().then(client => start(client));

async function start(client) {

    ev.on('qr.**', async qrcode => {
        console.log('QRRRRRR')
        //qrcode is base64 encoded qr code image
        //now you can do whatever you want with it
      //  const imageBuffer = Buffer.from(
       //   qrcode.replace('data:image/png;base64,', ''),
       //   'base64'
      //  );
      //  fs.writeFileSync('qr_code.png', imageBuffer);
      });
```

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

**Comment by smashah** [comment]
In your code, you are registering the QR event listener within your start function which means you are starting to listen for the QR code after you have already authenticated and launched the session!

try something like this:

```javascript
const {create, ev} = require('@open-wa/wa-automate')

let monitorArr = []


ev.on('qr.**', async qrcode => {
    console.log('QRRRRRR')
});

create().then(client => start(client));
```

Please discuss this further in the discord channel (click the discord badge in the readme for an invite).

thanks
