### ISSUE TITLE
Send a message to my contact on a specific date and time

### ISSUE THREAD

**Issue by Sambosa711** [open-wa/wa-automate-nodejs#1937]
Hello, I want to send a message to a group and my contacts on a specific date and time, how do I do that
Is there a feature that does this in open mode

He used moment js in the following code, but it sends the message more than once

     const wa = require('@open-wa/wa-automate');
     const moment = require('moment');

      wa.create({
     sessionId: "COVID_HELPER",
     authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
     blockCrashLogs: true,
     disableSpins: true,
     headless: true,
     hostNotificationLang: 'PT_BR',
    logConsole: false,
    popup: true,
    qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
    }).then(client => start(client));

    async function start(client) {

    
    while (true){  
        const  h1 = await client.getAllChatIds()
        for (lop1 of h1){
        let g1 = await client.getChatById(lop1)
        if (!g1.isReadOnly){
 
         switch (moment().format('h:mm:ss a')){
        
             case '6:58:00 am':
                         
                 await client.sendText(lop1, "  test 2  ")
     
                        break
                
             case '6:57:00 am':
                
                 await client.sendText(lop1, "  test 2  ")
             
          
                       break
                
                }    
        }
           }  
         
         }

       }

**Comment by basboot** [comment]
My best guess is that your endless loop is running faster than once a second, causing it to send multiple messages during that second.

You could add a boolean to check if the message has already been sent, but I think it would be better, and give you more control to use a scheduler instead of this busy-waiting loop. 

I've made a small example using node-schedule (https://www.npmjs.com/package/node-schedule) that might help you.

```
const schedule = require('node-schedule');

// ...

async function start(client: Client) {

  // Send message at 18:11:00 on the 27th of July
  const job = schedule.scheduleJob('0 11 18 27 7 *', function(){
    client.sendText(`${phoneNumber}@c.us`, `Scheduler test`);
  });

}
```

Good luck!

**Comment by smashah** [comment]
Thanks for providing a possible solution to this question @basboot 

For discussing general questions please use the discord.

thanks
