### ISSUE TITLE
Webhook Registration

### ISSUE THREAD

**Issue by cosmo83** [open-wa/wa-automate-nodejs#1942]
If iam passing the webhook using the latest version of EasyAPI with -w , or --webhook, you are checking this with isUrl 

`
if(c.webhook || c.webhook == '') {
	if(isUrl(c.webhook) || Array.isArray(c.webhook)) {
		spinner.succeed('webhooks set already')
	} else {
		if(c.webhook == '') c.webhook = 'webhooks.json';
		c.webhook = tryOpenFileAsObject(c.webhook, true);
		if(!isUrl(c.webhook)) {
			c.webhook = undefined
		}
	}
}
`

The isUrl does not work for custom urls for example when we are trying to run this as part of other containers in docker-compose / kubernetes.

![image](https://user-images.githubusercontent.com/973160/126923447-878d37ab-2f67-4b6b-9560-6e4754bc2ca4.png)

Though this is not trivial, please look at some other options. It took me a while to figure out the issue.

**Comment by smashah** [comment]
pretty sure this is related to https://github.com/open-wa/wa-automate-docker/issues/20

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.12.2](https://github.com/open-wa/wa-automate-nodejs/compare/4.12.1...4.12.2) (2021-07-28)

- build(deps-dev): bump @types/node from 16.4.3 to 16.4.4 [`#1949`](https://github.com/open-wa/wa-automate-nodejs/pull/1949)
- build(deps-dev): bump @types/pino from 6.3.10 to 6.3.11 [`#1950`](https://github.com/open-wa/wa-automate-nodejs/pull/1950)
- build(deps-dev): bump @types/pino from 6.3.9 to 6.3.10 [`#1946`](https://github.com/open-wa/wa-automate-nodejs/pull/1946)
- build(deps-dev): bump @typescript-eslint/eslint-plugin from 4.28.4 to 4.28.5 [`#1947`](https://github.com/open-wa/wa-automate-nodejs/pull/1947)
- build(deps-dev): bump @typescript-eslint/parser from 4.28.4 to 4.28.5 [`#1945`](https://github.com/open-wa/wa-automate-nodejs/pull/1945)
- build(deps-dev): bump @types/node from 16.4.1 to 16.4.3 [`#1940`](https://github.com/open-wa/wa-automate-nodejs/pull/1940)
- build(deps-dev): bump release-it from 14.10.0 to 14.10.1 [`#1941`](https://github.com/open-wa/wa-automate-nodejs/pull/1941)
- Release 4.12.2 [`c8748ab`](https://github.com/open-wa/wa-automate-nodejs/commit/c8748ab63922cf15ba23924f50f5e221bb6549cb)
- 🌐  host notification: added `nl-nl` #743 [`2bcd942`](https://github.com/open-wa/wa-automate-nodejs/commit/2bcd942b9b49709b03cccbf6863050141c18c9c5)
- 🔧 CLI: Use `--skip-url-check` to use non-FQDN webhook addresses #1942 [`4880ef7`](https://github.com/open-wa/wa-automate-nodejs/commit/4880ef75eb3db5c212fa6fdcdc755df965db55a9)
- 🥚  patches update [`edbfdee`](https://github.com/open-wa/wa-automate-nodejs/commit/edbfdee15a9db34bfd53433781961c34ba020ade)
- 🙈  updated `.gitignore` to include multiDevice workaround [`deb2467`](https://github.com/open-wa/wa-automate-nodejs/commit/deb2467bb9b522a578c2346f8303b10c0760a957)

**Comment by smashah** [comment]
@cosmo83 please update your version and use the `--skip-url-check`

thanks
