### ISSUE TITLE
error Evaluation failed: TypeError: e.isUser is not a function 

### ISSUE THREAD

**Issue by mrbarnk** [open-wa/wa-automate-nodejs#1943]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

It auto log me out when I send a message to a new chat.auto-log

### Expected Behavior

It will auto logout the session.

### Steps To Reproduce

Just try to send message to a new chat.

### Mode

EASY API/CLI

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2126.14",
  "WA_AUTOMATE_VERSION": "4.12.1",
  "BROWSER_VERSION": "HeadlessChrome/85.0.4183.121",
  "START_TS": 1627318400437
}
```

### Environment

```markdown
- OS: Linux 5.4
- Node: 16.1.0
- npm:
```

**Comment by smashah** [comment]
Needs more context. Not able to reproduce.
