### ISSUE TITLE
Include getChatById to getAllChatsWithMessages

### ISSUE THREAD

**Issue by mrbarnk** [open-wa/wa-automate-nodejs#1951]
To display the contact with verifiedName on each chats.

**Comment by smashah** [comment]
Can you clarify please

**Comment by mrbarnk** [comment]
![image](https://user-images.githubusercontent.com/37006356/127389483-894eb15e-badc-4b2c-b7b3-15aa831039bc.png)

I want to be able to access the contact object from the response at `getAllChatsWithMessages`.

**Comment by mrbarnk** [comment]
![image](https://user-images.githubusercontent.com/37006356/127389709-5e9f748f-e29e-49ed-bb08-b5d4f66a6216.png)

This object presented under getChatById

**Comment by smashah** [comment]
should be working with latest patches. thanks

**Comment by mrbarnk** [comment]
but it's not returnning msgs array anymore.

**Comment by mrbarnk** [comment]
It's now `null`.

**Comment by smashah** [comment]
@mrbarnk try again, should have all messages properly serialized

**Comment by mrbarnk** [comment]
Thank you, it worked.

but sometimes I get this.
![image](https://user-images.githubusercontent.com/37006356/128362812-34a0f605-1a38-4b46-9bbf-d5d42a879bbb.png)

**Comment by smashah** [comment]
patched. If there's anything else lmk on the discord. thanks
