### ISSUE TITLE
Easy API send Buttons 

### ISSUE THREAD

**Issue by axixu** [open-wa/wa-automate-nodejs#1958]
Dear, thank you for this great tool, may i know how to send buttons from easy API?

from swagger i tried this:
```javascript
{
  "args": {
    "to": "00000000000@c.us",
    "body": "this is body",
    "buttons": "[{id: "1","text": "Click"},{id: "1","text": "Call"},{id: "1","text": "Open Link"}]",
    "title": "this is title",
    "footer": "this is footer"
  }
}
```

and curl:
```bash
 curl -X 'POST' \
  'https://wa.xxx.com/sendButtons' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": {
    "to": "00000000000@c.us",
    "body": "this is body",
    "buttons": "[{id: "1","text": "Click"},{id: "1","text": "Call"},{id: "1","text": "Open Link"}]",
    "title": "this is title",
    "footer": "this is footer"
  }
}'
```

but at server response i got this: Error, Bad Request
![image](https://user-images.githubusercontent.com/28151183/127418286-e9ff7d8a-a103-45e3-bf61-792156199fc8.png)

**Comment by smashah** [comment]
@axixu your json payload isn't formatted correctly.

You have to add `"` to the property names in the buttons object. It's missing around `id`

Try this:
```javscript
{
  "args": {
    "to": "00000000000@c.us",
    "body": "this is body",
    "buttons": "[{"id": "1","text": "Click"},{"id": "1","text": "Call"},{"id": "1","text": "Open Link"}]",
    "title": "this is title",
    "footer": "this is footer"
  }
}
```

**Comment by axixu** [comment]
@smashah it still came with same error, I updated open-wa to 4.12.3 and still got error. here is the screen
![image](https://user-images.githubusercontent.com/28151183/127586908-83a6729f-b6e5-4510-b80a-0bc5ca5bce4c.png)

**Comment by smashah** [comment]
Remove the quotes around the square brackets as well.

**Comment by axixu** [comment]
Finally, thank you.

**Comment by victorfreire100** [comment]
case '!button':
		await client.sendButtons(chatId, "Option", [
		{
        id: "1",
        "text": "Option 1"			
		},
		{
        id: "2",
        "text": "Option 2
		},
		], "")
		
		===========================
		
When the user chooses an option I want him to make a request in an api with the option id and send a confirmation msg. Can anyone help me?
