### ISSUE TITLE
joinGroupViaLink is returning an error string

### ISSUE THREAD

**Issue by phaalonso** [open-wa/wa-automate-nodejs#1964]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Join group via link returns an error string

### Expected Behavior

Either false if it didn't work, or the group object

### Steps To Reproduce

Use the joinGroupViaLink with an invalid link

### Mode

My own code

### create() code

```markdown
create({
    headless: false
}).then(client => {
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2126.14",
  "WA_AUTOMATE_VERSION": "4.12.3",
  "BROWSER_VERSION": "Chrome/92.0.4512.0",
  "START_TS": 1627607269245
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 15.14.0
- npm: 7.7.6
```

### Screenshots

![image](https://user-images.githubusercontent.com/26033899/127585039-22b621e2-9927-4e35-a9fe-47f1b6faf4ed.png)
![image](https://user-images.githubusercontent.com/26033899/127585060-453dd9bb-506b-498e-9e83-222e402073e4.png)

**Comment by smashah** [comment]
@phaalonso I've just tested this and it seems to be working properly. This error you're getting is being forwarded from the web instance itself and isn't generated from any library-based code or patches.

There may be some behavioral context missing to this issue. Does this happen after a certain amount of groups? Does it happen all the time? Does this happen for groups made by any number or a specific number? Either way, this is not something that can be remedied through a library update.

**Comment by smashah** [comment]
Closing. thanks
