### ISSUE TITLE
 Cannot read property 'name' of undefined, node_modules\@open-wa\wa-automate\node_modules\universalify\index.js:15:26

### ISSUE THREAD

**Issue by catur515** [open-wa/wa-automate-nodejs#1974]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

when i make exe, windows x64 with pkg.
Errors :
Cannot read property 'name' of undefined

@open-wa\wa-automate\node_modules\universalify\index.js:15:26

![image](https://user-images.githubusercontent.com/22145610/127926159-b89d0c7e-9269-4733-a32c-9ad6478bd657.png)

### Mode

My own code

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

**Comment by smashah** [comment]
In the future please use the template correctly.

This is probably due to some node/npm version issue. Please make sure you are using current versions of both
