### ISSUE TITLE
add command failing

### ISSUE THREAD

**Issue by vladi9998** [open-wa/wa-automate-nodejs#1978]
addParticipant  property is not working and it is not due to privacy settings, and i am updated, could you please check it? thank you

**Comment by smashah** [comment]
I just checked it out and it seems to be working. If you are still experiencing this then please fill the template

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.yaml&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.yaml&title=)⚠️⚠️⚠️
