### ISSUE TITLE
First sendTextWithMentions sends without tagging

### ISSUE THREAD

**Issue by w0LFzk1nD** [open-wa/wa-automate-nodejs#1979]
When the Bot get restarted, the first sendTextWithMentions, never Tags the Person/s. After the message without tag, it will work as intended.

**Comment by smashah** [comment]
@w0LFzk1nD 

I tested this by making a bot that just sends a tag message and it seems to be working for me.

I have issued a possible fix with the latest patches, if it continues please discuss further in a thread in the discord. thanks
