### ISSUE TITLE
FETCH_ERROR when Installing @open-wa/wa-automate@latest

### ISSUE THREAD

**Issue by anaselfadili** [open-wa/wa-automate-nodejs#1985]
### Are you using the latest version of the library?

- [x] I have checked and am using the latest version of the library.

### Current Behavior

Hey, I try to install the package but I get an error.
can anyone explain how I can solve this problem,
I have the last version of Nodejs And npm.

### Mode

My own code

### Environment

```markdown
- OS: Windows 10
- Node: v14.17.4
- npm: 7.20.5
```

### Screenshots

![image](https://user-images.githubusercontent.com/43721644/128500682-8fd94ca8-3189-4abc-9575-4475b237d8c6.png)

**Comment by smashah** [comment]
@anaselfadili this error has nothing to do with the library. For some reason, `https://registry.npmjs.org/patch-package` was returning a partial/improperly formatted json.

Please try on another machine or debug your environment
