### ISSUE TITLE
Phone must Be always connected ... Any ideas?

### ISSUE THREAD

**Issue by alirezadigi** [open-wa/wa-automate-nodejs#1986]
Hi!
I want to run this great api in my VPS But my phone needs to be always on and connected to the internet.
Do you have any ideas about for example Android Emulators etc?
I use ubuntu vps.

**Comment by NLLucifer** [comment]
Try the whatsapp Beta. 
With the new whatsapp Beta your phone doesn't have to be connected to use whatsapp web.

**Comment by smashah** [comment]
I would hold off using multi device as of yet because there are still a lot of things that do not work due to the fact that multi device is itself in beta. You have to keep the phone connected for the foreseeable future

**Comment by alirezadigi** [comment]
> Try the whatsapp Beta.
> With the new whatsapp Beta your phone doesn't have to be connected to use whatsapp web.

Thanks @NLLucifer! How can I download it?

**Comment by smashah** [comment]
Just a heads up, issues submitted from multi-device sessions will not be a priority.

[Here's how to enable multi device on whatsapp](https://www.techadvisor.com/how-to/social-networks/whatsapp-multi-device-3806627/)

**Comment by alirezadigi** [comment]
@smashah my problem is not multi devices
I want a way to use normal whatsapp on vps
For example an emulator.
