### ISSUE TITLE
Question: How could i open puppeteer session on remote server

### ISSUE THREAD

**Issue by MBayoumi** [open-wa/wa-automate-nodejs#1999]
i'm wondering if i could open puppeteer session on local server and host service on aws to avoid open puppeteer session on different -mobile phone host- network

**Comment by smashah** [comment]
You can host the browser separately from the open-wa process and connect them with `browserWSEndpoint`

1. `docker run -p 3000:3000 browserless/chrome`
2. `npx @open-wa/wa-automate --browser-w-s-endpoint 'ws://localhost:3000'`
or use this config:
```javascript
{
	browserWSEndpoint: 'ws://localhost:3000'
}
```
