### ISSUE TITLE
Pipedream

### ISSUE THREAD

**Issue by marcelocecin** [open-wa/wa-automate-nodejs#2002]
Hello
is it possible to use this repository in [Pipedream](https://pipedream.com)?
thanks

**Comment by smashah** [comment]
@marcelocecin I do recall someone integrating pipedream + openwa but not sure about running open-wa IN pipedream

**Comment by smashah** [comment]
@marcelocecin what are your thoughts on possible building an official open-wa pipedream integration? Do you think it'll be a lot of work?

If you think a lot of people will get use out of it I can add it to the integrations board https://github.com/open-wa/wa-automate-nodejs/projects/2
