### ISSUE TITLE
getAllContacts returns undefined

### ISSUE THREAD

**Issue by syafiqfaiz** [open-wa/wa-automate-nodejs#2007]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

```
	whatsapp.getAllContacts().then((contacts) => {
		debugger
	}).catch((err)=>{
		console.log('getContacts error: ', err)
	});
```
`contacts` returns undefined

### Expected Behavior

`contacts` returns an array of contacts

### Steps To Reproduce

run this

```
	whatsapp.getAllContacts().then((contacts) => {
		debugger
	}).catch((err)=>{
		console.log('getContacts error: ', err)
	});
```

### Mode

My own code

### create() code

```markdown
var _waConfig = {
	sessionId: "something",
	licenseKey: "something",
};
wa.create(_waConfig)
.then(async client => await _whatsappStart(client))
.catch(e => {
	console.log('CREATE ERROR', e.message);
});
```

### DEBUG INFO

```markdown
Debug Info {
  WA_VERSION: '2.2130.9',
  PAGE_UA: 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
  WA_AUTOMATE_VERSION: '4.14.1',
  BROWSER_VERSION:  'HeadlessChrome/93.0.4577.0'
}
```

### Environment

```markdown
- OS: ubuntu 20.04
- Node: v14.15.5
- npm: 7.9.0
```

### Screenshots

![image](https://user-images.githubusercontent.com/8923682/129310003-d2347595-1c44-4dab-a985-6af3ce4ccba8.png)

### Anything else?

it was working fine before,
suddenly breaks few hours ago

**Comment by dekataji** [comment]
I'm experiencing the same problem with getAllUnreadMessages() method

**Comment by gutitrombotto** [comment]
I have the same problem.
I couldn't solve it yet!

**Comment by smashah** [comment]
checking out what's going on

**Comment by smashah** [comment]
@gutitrombotto @dekataji @syafiqfaiz please restart your sessions and try again. this issue is patched

**Comment by gutitrombotto** [comment]
Thanks @smashah.
Bug fixed!

**Comment by dekataji** [comment]
Thanks @smashah , you rock!
