### ISSUE TITLE
Getting groups from an account with bulk amount crashes

### ISSUE THREAD

**Issue by gutitrombotto** [open-wa/wa-automate-nodejs#2009]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Getting groups list with a large amount (1000) throws expection in puppeteer.

### Expected Behavior

List of groups

### Steps To Reproduce

  Running this...

  client.getAllGroups().then((groups) => {
    for (let i = 0; i < groups.length; i++) {
      const group = groups[i];
      groupsData.push({name: group.name, groupId: group.id});
    }
  });

### Mode

My own code

### create() code

```markdown
create({
  sessionId: DEFAULT_SESSION,
  headless: false,
}).then((client) => {
  app.locals.clients[DEFAULT_SESSION] = client;
  prestart(client);
});
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2130.9",
  "WA_AUTOMATE_VERSION": "4.14.1",
  "BROWSER_VERSION": "HeadlessChrome/88.0.4298.0",
  "START_TS": 1628864269042
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 16.6.2
- npm: 
- yarn: 1.22.5
```

### Screenshots

Puppeteer crashes

/home/atrombotto/filadd/capybara/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: p
    at ExecutionContext._evaluateInternal (/home/atrombotto/filadd/capybara/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/atrombotto/filadd/capybara/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)

**Comment by garciabruno** [comment]
Happens to me too.

**Comment by nropelato** [comment]
I'm having a close issue, when i call `getAllUnreadMessages()`  for accounts with thousands of chats the page crashes

**Comment by smashah** [comment]
@nropelato @garciabruno @gutitrombotto when was the last time you tried to test this out? Because around the same time as you reported this issue I pushed new patches. Please retry and confirm if this issue is still happening. thanks

**Comment by gutitrombotto** [comment]
Hi @smashah. Thanks for the reply.

The issue still there!

The last patch is 51f5b I think.
This patch fix the issue in getAllContacts. But this problem is different.

**Comment by smashah** [comment]
@gutitrombotto I am unbale to replicate the issue because I don't have that many chats/groups. I have pushed some new patches that may fix the problem, please try again.

If this continues happening then one of you will need to let me test fixes on your specific sessions. To expedite this please join and ping me on discord

**Comment by gutitrombotto** [comment]
@smashah I have just tested again, with the new patches (97526) and the problem continues.
I think that  puppeteer can't evalute the a large screen in the browser because of the large amount of groups.

I will join discord and ping you in the following days.

**Comment by gutitrombotto** [comment]
@smashah what is the discord link?

**Comment by smashah** [comment]
@gutitrombotto click the discord badge in the readme

**Comment by garciabruno** [comment]
Seems to be fixed. (Using patch **7efdb**)
Thanks a lot @smashah !

Cheers
