### ISSUE TITLE
Python promises issue

### ISSUE THREAD

**Issue by mrodal** [open-wa/wa-automate-nodejs#2021]
Python cant take promises, all values must be resolved in the browser. 
We use `WAPI.pyFunc` which is a wrapper function that awaits the return value from the original function, but we are now getting some promises inside the return object, for example with `getUnreadMessagesInChat` which returns an array of promises.

I think return objects should be navigated resolving all promises before actually returning from `WAPI.pyFunc`

**Comment by smashah** [comment]
resolved with new patches. Any array with promises should resolve the promise before returning.
