### ISSUE TITLE
The methods sendContact and sendVcard are not working,any help?

### ISSUE THREAD

**Issue by fly2012** [open-wa/wa-automate-nodejs#2023]
Uncaught TypeError: window.WAPI.getChat(...).sendContact is not a function
    at Object.window.WAPI.sendContact (VM18 about:blank:1355)
    at <anonymous>:1:13

Uncaught TypeError: chat.addAndSendMsg is not a function
    at Object.window.WAPI.sendVCard (VM18 about:blank:1415)
    at <anonymous>:1:13

**Comment by smashah** [comment]
@fly2012 this was fixed a long time ago via patches. Please use the library as is and fill an issue template in the future thanks

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.yaml&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.yaml&title=)⚠️⚠️⚠️
