### ISSUE TITLE
The link to the config object is broken

### ISSUE THREAD

**Issue by mouhammad-zd** [open-wa/wa-automate-nodejs#2024]
Hello,
I am new to this repository

When i tried to access `ConfigObject` link situated in the `readme` of this repository , it redirects me to `page not found`

This is the link that i have redirected to : [https://docs.openwa.dev/interfaces/api_model.configobject.html](https://docs.openwa.dev/interfaces/api_model.configobject.html)

**Comment by mouhammad-zd** [comment]
I found that the correct `url` is : 
[https://docs.openwa.dev/interfaces/api_model_config.ConfigObject.html](https://docs.openwa.dev/interfaces/api_model_config.ConfigObject.html)

The correct link is situated in the page behind this link : 
[https://docs.openwa.dev/pages/The%20Client/the-client.html](https://docs.openwa.dev/pages/The%20Client/the-client.html)

**Comment by smashah** [comment]
fixed thanks
