### ISSUE TITLE
loadAndGetAllMessagesInChat not working

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#2025]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Running loadAndGetAllMessagesInChat with this args:

{
  "args": {
    "chatId": "55***********@c.us",
    "includeMe": "false",
    "includeNotifications": "true"

}

**Got this error:**

{
  "success": false,
  "error": {
    "name": "Error",
    "message": "Evaluation failed: TypeError: Cannot read properties of undefined (reading 'msgLoadState')\n    at Object.window.<computed>.<computed> [as loadAllEarlierMessages] (__puppeteer_evaluation_script__:1:365412)\n    at Object.window.<computed>.<computed> [as loadAndGetAllMessagesInChat] (__puppeteer_evaluation_script__:1:224437)\n    at __puppeteer_evaluation_script__:1:56"
  }
}

Same error with other chatIds.

### Expected Behavior

Return messages related with ChatId.

### Steps To Reproduce

1. Send and receive messages work well with 4.16.0 (Error identified on 4.14.x)
2. Recovering old messages loadAndGetAllMessagesInChat
3. Got error described - works with 3.x (but can't identify which version broke this method) 

### Mode

EASY API/CLI

### DEBUG INFO

```markdown
WA_VERSION:  '2.2132.6'
PAGE_UA: 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
WA_AUTOMATE_VERSION: '4.16.0'
BROWSER_VERSION:  'HeadlessChrome/93.0.4577.0'
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: v14.17.5
- npm: 7.20.6
```

### Anything else?

**Console error:**

1|open-wa- |     at async ExecutionContext.evaluate (/dados/wa-automate-nodejs/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
1|open-wa- | middleware -> error Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'msgLoadState')
1|open-wa- |     at Object.window.<computed>.<computed> [as loadAllEarlierMessages] (__puppeteer_evaluation_script__:1:365412)
1|open-wa- |     at Object.window.<computed>.<computed> [as loadAndGetAllMessagesInChat] (__puppeteer_evaluation_script__:1:224437)
1|open-wa- |     at __puppeteer_evaluation_script__:1:56
1|open-wa- |     at ExecutionContext._evaluateInternal (/dados/wa-automate-nodejs/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
1|open-wa- |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
1|open-wa- |     at async ExecutionContext.evaluate (/dados/wa-automate-nodejs/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
1|open-wa- | middleware -> error Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'msgLoadState')
1|open-wa- |     at Object.window.<computed>.<computed> [as loadAllEarlierMessages] (__puppeteer_evaluation_script__:1:365412)
1|open-wa- |     at Object.window.<computed>.<computed> [as loadAndGetAllMessagesInChat] (__puppeteer_evaluation_script__:1:224437)
1|open-wa- |     at __puppeteer_evaluation_script__:1:56
1|open-wa- |     at ExecutionContext._evaluateInternal (/dados/wa-automate-nodejs/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
1|open-wa- |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
1|open-wa- |     at async ExecutionContext.evaluate (/dados/wa-automate-nodejs/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)

**Comment by silvaartur** [comment]
Problem is loadAllEarlierMessages.

**Comment by smashah** [comment]
should be fixed with latest patches

**Comment by silvaartur** [comment]
Error changed to:

{
  "success": false,
  "error": {
    "name": "Error",
    "message": "Evaluation failed: TypeError: _0x2a530d[(\"loa\" + _0x21769d(...) + _0x21769d(...) + \"erM\" + \"sgs\")] is not a function\n    at Object.window.<computed>.<computed> [as loadAllEarlierMessages] (__puppeteer_evaluation_script__:1:292060)\n    at __puppeteer_evaluation_script__:1:20"
  }
}
