### ISSUE TITLE
Double post hook

### ISSUE THREAD

**Issue by the-jojo-jj** [open-wa/wa-automate-nodejs#2026]
Somebody also got webhook doublepost?
Please help.

**Comment by smashah** [comment]
@the-jojo-jj please share both webhook payloads and the way you're interfacing with open-wa (if you're using the CLI then I'll need to see your CLI flags also)

My guess is that you're receiving both onMessage and onAnyMessage instead of receiving duplicate webhook payloads

**Comment by the-jojo-jj** [comment]
@smashah thanks for your reply, you right, it’s onmessage and onanymessage. Thanks
