### ISSUE TITLE
Every time i must reAuthenticate with phone connected to internet

### ISSUE THREAD

**Issue by alirezadigi** [open-wa/wa-automate-nodejs#2038]
Hi!
Everytime i restart the script i must turn on the phone's internet to login.
If I dont , It will says "Authentication timed out. Please open the app on the phone. Shutting down"
Any ideas?

**Comment by smashah** [comment]
@alirezadigi for some reason your whatsapp app is being put to sleep. Keep it open and in memory on the phone. Make sure the phone has a solid internet connection. If you can, reuse a second-hand phone and keep it awake on the app for the best connectivity.

You can change the [`authTimeout`](https://docs.openwa.dev/interfaces/api_model_config.ConfigObject.html#authTimeout) (default: 60) by changing it to your desired wait time in seconds. Or set it to `0` to make it wait forever.

If you're using the easy API, set this flag:

```bash
> npx @open-wa/wa-automate --auth-timeout 0
```
