### ISSUE TITLE
(node:11108) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com

### ISSUE THREAD

**Issue by joelvitorniino** [open-wa/wa-automate-nodejs#2052]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

I am using @open-wa with proxy.

### Mode

My own code

### create() code

```markdown
create({
        proxyServerCredentials: {
            address: 'http://192.168.49.1:8000',
            username: '',
            password: ''
        },
        useNativeProxy: true
    }).then(client => start(client));
```

### Environment

```markdown
- OS:  
- Node: 
- npm:
```

**Comment by smashah** [comment]
??? Are you running this in firebase functions? Needs so much more context. I will reopen once more information is provided.
