### ISSUE TITLE
Cannot convert undefined or null to object after update

### ISSUE THREAD

**Issue by Cephas369** [open-wa/wa-automate-nodejs#2053]
Loading the script after authenticate it's giving this error:

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Object.<anonymous> (C:\Users\user\Documents\CursoJS\whatsappbot\node_modules\@open-wa\wa-
automate\dist\controllers\initializer.js:354:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\user\Documents\CursoJS\whatsappbot\node_modules\@open-wa\wa-automate\
dist\controllers\initializer.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by paulocorcino** [comment]
I have same problems with the new version.
```
✓ Patches Installed: 0e437
======= 2021-08-25 01:19:37: TypeError: Cannot convert undefined or null to object TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at C:\what2api\9006\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:354:46
    at Generator.next (<anonymous>)
    at fulfilled (C:\what2api\9006\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Create code

```
useChrome: true,    
	licenseKey: (F.config['licensekey'].toString() == "[licence]" ? "" : F.config['licensekey'].toString()),
    deleteSessionDataOnLogout: false,
    sessionDataPath: "whatsSessions/",
    sessionId: F.config['instance'].toString(),
    headless: true,
	hostNotificationLang: 'PT_BR',
	skipUpdateCheck:true,	
    autoRefresh:true, 
	logFile: true,
    qrTimeout:0,
	authTimeout:0,
    killTimer: 6000,
    blockCrashLogs: true, 
    bypassCSP: true,
	killProcessOnBrowserClose: false  
```

Debug info
```
{
  "WA_VERSION": "2.2132.6",
  "WA_AUTOMATE_VERSION": "4.20.0",
  "BROWSER_VERSION": "HeadlessChrome/91.0.4472.124",
  "START_TS": 1629865145481
}
```

Environment

- OS: Windows 10
- Node:  v16.1.0
- npm: 7.20.3

**Comment by smashah** [comment]
Hi all, I suggest downgrading for now. Will resolve this tomorrow

**Comment by Cephas369** [comment]
> Hi all, I suggest downgrading for now. Will resolve this tomorrow

Ok

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.20.1](https://github.com/open-wa/wa-automate-nodejs/compare/4.20.0...4.20.1) (2021-08-25)

- 🐛 fix #2053 [`#2053`](https://github.com/open-wa/wa-automate-nodejs/issues/2053)
- 🐛  fix #1872 [`#1872`](https://github.com/open-wa/wa-automate-nodejs/issues/1872)
- Release 4.20.1 [`b454ff6`](https://github.com/open-wa/wa-automate-nodejs/commit/b454ff6d9cc0e039d05a45862eb7bbe6360d357e)
- 🥚 patch reversion [`dadbb54`](https://github.com/open-wa/wa-automate-nodejs/commit/dadbb54a38ef0481357a8ab765752c80b8deac97)
- 🥚  patches update [`beb04ed`](https://github.com/open-wa/wa-automate-nodejs/commit/beb04edcca339a126e2f6b1814523e8c31b045f5)
- updated types-only package [`6f0a102`](https://github.com/open-wa/wa-automate-nodejs/commit/6f0a1028aba9f9ccd72eb53a5e6bc31377203ccc)

**Comment by smashah** [comment]
@Cephas369 @paulocorcino resolved in latest version. Due to some reported issues with the major feature in 4.20.0 I had to revert the patch so 4.20.1 is functionally identical to the version before 4.20.0

**Comment by paulocorcino** [comment]
Fix work!
