### ISSUE TITLE
Kill client without kill node application

### ISSUE THREAD

**Issue by DragoSpiro98** [open-wa/wa-automate-nodejs#2064]
I’m creating a simple application that sends a message every hour (I'm using node-schedule for this) to a phone number but I have a problem, my application must perform these steps:
(only one time every hour) open client -> send message -> close client
the problem is that when I close client with client.kill(), this terminates the node application and not only the client. 
What can I do to solve this problem?

**Comment by DragoSpiro98** [comment]
> @DragoSpiro98 `kill()` should not actually stop your process. Please share your config and a code example I can use to replicate the issue.


Ho sistemato il problema ma non riesco a farlo funzionare
I fixed the problem but I can't get it to work. The error I get is "UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed" 


```
const { create, Client } = require("@open-wa/wa-automate");
const schedule = require("node-schedule");

schedule.scheduleJob("*/1 * * * *", function () {
  function start(client = new Client()) {
    client.sendText("39************@c.us", "test message")
    client.kill()
  }

  create({
    sessionId: "Imperial",
    headless: true,
    qrTimeout: 0,
    authTimeout: 0,}).then((client) => start(client));
})
```

**Comment by smashah** [comment]
target closed error is too generic. Please show the whole error log.

I'm pretty sure you're getting this error because you're not using `await` on either command and `kill` would always finish first. So you're killing the client before sending the text. Make sure to use `await` on all client methods.

Try something like this

```javascript
const { create, Client } = require("@open-wa/wa-automate");
const schedule = require("node-schedule");

schedule.scheduleJob("*/1 * * * *", async function () {
	const client = create({
    sessionId: "Imperial",
    headless: true,
    qrTimeout: 0,
    authTimeout: 0,})
	})
	await client.sendText("************@c.us", "test message");
	await client.kill().catch(()=>{})
	delete client;
})
```
