### ISSUE TITLE
Option to disable Notification of beeing automation contontrolled

### ISSUE THREAD

**Issue by gnadelwartz** [open-wa/wa-automate-nodejs#2069]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Your account is currently being controlled by an automation service. If you have not authorized this then please "Log out from all devices" in the "WhatsApp Web" section of this app.
#70363

### Expected Behavior

Option to disable this message

### Steps To Reproduce

Update to current version and restart

### Mode

My own code

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

**Comment by smashah** [comment]
Unless there is another way to confirm that developers have permission to start sessions on host accounts then this will not be implemented.

Please see #743

I'm open to ideas

**Comment by gnadelwartz** [comment]
What about asking for random confimation pin after pairing/startup, like bluetooth?

```
Your account is currently being controlled by an WhatsApp automation service. To confirm this is intended seed the following PIN back: ab25Df

If you have not authorized this then please "Log out from all devices" in the "WhatsApp Web" section of this app.
#70363
```

Message will be sent on each startup until PIN is confimed. in addition  message should not be delivered to automation client e.g. in `client.onAnyMassage()` as of today ...

**Comment by smashah** [comment]
@gnadelwartz and how can the pin confirmation be protected against circumvention?

Am I meant to keep a centralised DB of all confirmations?

What's stopping any developer from reading the message and doing a fake confirmation?

How would revocation be handled?

To be honest the only way I can safely assume a host account has permission to be automated is if a license exists for that account. Even then the permission is implicit (what if someone gets a license for the sole purpose of preventing the message?) This is why even licensed accounts get the message.

**Comment by gnadelwartz** [comment]
I was thinking about a lokal storage, not centralized, and yes it can be circumvented but also the message and the chat can be deleted automatically...

What makes me woundering is that the you implented the message in the last reelease as it was not send in the last 2-3 years I'm using your library ... this is also why I opened the Issue.

But as I understand now it's an "old" feature, probably it was not working.

**Comment by smashah** [comment]
@gnadelwartz I've always tested it with an existing chat with myself which is why I always thought it was working. It was brought to my attention that it wasn't working with accounts that don't already have chats with themselves so I fixed it in the latest version.

If it annoys someone so much that they feel the need to delete the whole chat then fair enough but at least the message is sent initially.
