### ISSUE TITLE
EASY API: Attach metadata to botpress converse API requests

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#2072]

**Comment by smashah** [comment]
![image](https://user-images.githubusercontent.com/5903821/131434272-3124f0b9-1d3d-4754-bbcf-c101268e6e5f.png)

Need to develop a custom botpress module :(

**Comment by smashah** [comment]
You can append message payloads as metadata for botpress converse api

**Comment by smashah** [comment]
https://github.com/botpress/botpress/pull/5165

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.23.10](https://github.com/open-wa/wa-automate-nodejs/compare/4.23.9...4.23.10) (2021-11-14)

- Release 4.23.10 [`c005d99`](https://github.com/open-wa/wa-automate-nodejs/commit/c005d99dd0938fe37c6deac69b00e53a5db8d53c)
- ✨ feat: added `message` as metadata to botpress converse requests #2072 [`d8acd3c`](https://github.com/open-wa/wa-automate-nodejs/commit/d8acd3ce9b350db71eaefa699c0ee802fc34d582)
- updated types-only package [`8cc96bb`](https://github.com/open-wa/wa-automate-nodejs/commit/8cc96bb054917ca4e999fbbef76e05bfa666ff0e)

**Comment by smashah** [comment]
![image](https://user-images.githubusercontent.com/5903821/141696042-0d0af9c0-6b8d-4084-81cb-cc9abfc19dbf.png)


You should now be able to parse the whole message via `event.payload.metadata`

**Comment by scropion86** [comment]
is there a guide on how to config botpress to send outgoing message using open-wa?
