### ISSUE TITLE
develop a wa library in php

### ISSUE THREAD

**Issue by manishkumar1601** [open-wa/wa-automate-nodejs#2079]
develop a wa library in php from which we can connect whatsapp and send messages and receive it

**Comment by smashah** [comment]
@manishkumar1601 There will be no standalone php library for wa-automate any time soon as there are no maintainers for it. Instead, you can directly download a PHP SDK for your own platform using the EASY API

1. Start the EASY API
```bash
> npx @open-wa/wa-automate
```

2. Download the SDK via the URL
```
http://EASY_API_URL/meta/codegen/php
```

Here all the available languages that the `/meta/codegen` endpoint can generate an SDK for:

https://twitter.com/openwadev/status/1394921344324755456/photo/1
