### ISSUE TITLE
Mime Error : message empty

### ISSUE THREAD

**Issue by powermx** [open-wa/wa-automate-nodejs#2087]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Hello, i was using my code to mime stickers or gif just to rename author and description, everything was normal until the last update.

Error: ‼️

[ERROR] Error [MissingCriticalDataError]: Message is missing critical data: size
    at new MissingCriticalDataError (/root/Bot/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:95:28)
    at /root/Bot/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:126:27
    at step (/root/Bot/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:59:23)
    at Object.next (/root/Bot/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:40:53)
    at /root/Bot/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (/root/Bot/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:30:12)
    at decryptMedia (/root/Bot/node_modules/@open-wa/wa-decrypt/dist/decrypt.js:104:67)
    at msgHandler (/root/Bot/message/index.js:5329:49)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

And this is my code: ‼️

case prefix+'robarsticker':
                if (!isRegistered) return await bocchi.reply(from, eng.notRegistered(), id)
                if (!isGroupMsg) return bocchi.reply(from, 'Comando solo para grupos!', id)
            if (limit.isLimit(sender.id, _limit, limitCount, isPremium, isOwner)) return await bocchi.reply(from, eng.limit(), id)
                limit.addLimit(sender.id, _limit, isPremium, isOwner)
                    if (quotedMsg && quotedMsg.type == 'sticker') {
                        if (!q.includes('|')) return await bocchi.reply(from, `Solo puedes usar letras \n\n#robarsticker Power | Texto `, id)
                        await bocchi.reply(from, eng.wait(), id)
                        const packnames = q.substring(0, q.indexOf('|') - 1)
                        const authors = q.substring(q.lastIndexOf('|') + 2)
                        const mediaData = await decryptMedia(quotedMsg)
                        const imageBase64 = `data:${quotedMsg.mimetype};base64,${mediaData.toString('base64')}`
                        await bocchi.sendImageAsSticker(from, imageBase64, { author: `${authors}`, pack: `${packnames}` })
                        .catch(async (err) => {
                            console.error(err)
                            await bocchi.reply(from, 'Error!', id)
                        })
                    } else {
                        await bocchi.reply(from, `Error`, id)
                    }
        break

Thanks in advance for any help.

@PowerMX

### Mode

My own code

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.yaml&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.yaml&title=)⚠️⚠️⚠️
