### ISSUE TITLE
Can not send message to unsaved number

### ISSUE THREAD

**Issue by shail2k4** [open-wa/wa-automate-nodejs#2088]
On using the function to send message like..
WAPI.SendMessage('000000000000@c.us','message') it shows the following message in the browser console.

Promise {<fulfilled>: "Not a contact"}
[[Prototype]]: Promise
[[PromiseState]]: "fulfilled"
[[PromiseResult]]: "Not a contact"

The error only comes when the contact number is unsaved or no chat history is there...
From today only, this message is coming.. it was working fine till yesterday.
Regards,

**Comment by mrizkypk** [comment]
Me, too. This error also exists in other libraries.

**Comment by roysG** [comment]
Same for me, any update?

**Comment by smashah** [comment]
You need a license to send a message to a non-contact

please see: 
https://docs.openwa.dev/pages/The%20Client/licensed-features.html#sending-messages-to-non-contact-numbers
