### ISSUE TITLE
API Not send Message when host phone Switch off or Not in a network

### ISSUE THREAD

**Issue by sakthimj** [open-wa/wa-automate-nodejs#2102]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Hi, 

When Host phone switch off or not in a network , API Message doesn't delivered.
It Delivered once phone back to online. 

### Mode

EASY API/CLI

### Environment

```markdown
- OS: Ubuntu 16.04
- Node: 14.16.0
- npm: 7.7.5
```

**Comment by Sirloya** [comment]
lol
