### ISSUE TITLE
Multiple-account does not retain connection

### ISSUE THREAD

**Issue by lascimmia** [open-wa/wa-automate-nodejs#2116]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

I'm just been activated on multi-account Beta program. I have to authenticate every single time

### Expected Behavior

The traditional one 😁, no need to scan the QRCode every time i launch APIs for the same account

### Mode

EASY API/CLI

### Environment

```markdown
- WA_VERSION: 2.2134.10
- PAGE_UA: 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
- WA_AUTOMATE_VERSION: 4.20.8
- BROWSER_VERSION: Chrome/93.0.4577.0
- OS: Windows 10
```

**Comment by smashah** [comment]
https://github.com/open-wa/wa-automate-python/issues/81#issuecomment-907399653

**Comment by smashah** [comment]
@lascimmia should be working now

**Comment by Helvio88** [comment]
> @lascimmia should be working now #2144

I still have to re-authenticate on MD on every restart. My only config besides sessionId is
`chromiumArgs: ['--no-sandbox']`

But even removing it didn't seem to be enough.
Any ideas?

**Comment by smashah** [comment]
> > @lascimmia should be working now #2144
> 
> I still have to re-authenticate on MD on every restart. My only config besides sessionId is `chromiumArgs: ['--no-sandbox']`
> 
> But even removing it didn't seem to be enough. Any ideas?

Please paste your whole config here

**Comment by Helvio88** [comment]
I did that and tried to authenticate again. My .data.json file content is
now "e30=" which translates to "{}". It does not auto reauthenticate, of
course.

Any suggestions?

Thanks!

**Comment by CloudItaly** [comment]
@Helvio88 hello! Have you problems with QRcode?

**Comment by riccihenrique** [comment]
> 1. Set `mutliDevice: true`
> 2. Change your session ID (or delete the existing .data.json file)
> 3. Remove your chrome args

Heyy @smashah , how are you?

Only suggestion,  `1. Set `mutliDevice: true`` is wrong. Should be > 1. Set `multiDevice: true` 😄
