### ISSUE TITLE
[MAJOR CHANGE] Consume both session id & custom user agent within the configObject.

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#212]
In order to simplify the create method, I am planning to migrate away from a three parameter system to single parameter ConfigObject. I.e remove the first [session id] and last [custom user agent] and instead make them optional properties on the ConfigObject.

This will initially not be a breaking change but support for the original system will eventually be dropped in the next major release.

**Comment by marcelocecin** [comment]
hi there, also try to include this fix: https://github.com/pedroslopez/whatsapp-web.js/commit/8bdecadba47df905917773f03a48435d4bdd596f

**Comment by smashah** [comment]
@marcelocecin they'll be separated fixes if required. I've never come across the first issue myself.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.25](https://github.com/smashah/sulla/compare/1.8.24...1.8.25) (2020-03-29)

- Release 1.8.25 [`0d55717`](https://github.com/smashah/sulla/commit/0d557178713b36c92b18ddfdf4fabc27a2c8ccd0)
- Feature: possible single config paramater for create #212 [`05935b2`](https://github.com/smashah/sulla/commit/05935b2220f620edb8e3cc95cc5ff056153cc0e0)
- remove console.log statement [`9b68007`](https://github.com/smashah/sulla/commit/9b68007ea07a70ec75ef05378e6fea8e2daa706d)

**Comment by smashah** [comment]
You can now optionally use the create method with a single ConfigObject parameter. You can now set [sessionId](https://smashah.github.io/sulla/interfaces/configobject.html#sessionid) & [customUserAgent](https://smashah.github.io/sulla/interfaces/configobject.html#customuseragent) in [ConfigObject](https://smashah.github.io/sulla/interfaces/configobject.html).

```javascript
  create({
  sessionId: 'main',
  customUserAgent: ' 'WhatsApp/2.16.352 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15',
  blockCrashLogs true,
  ...
  })....
```

For now, this is optional but in the next major update (>2.0.0), support for the original 3 parameter set up will be dropped and eventually removed.

**Comment by feliperaul** [comment]
@smashah Shah, I couldn't find your contact details anywhere. Could you please reach to feliperaul87@gmail.com? I promise to go straight to the point and not to waste your time, it's about some freelance / work opportunity.

**Comment by smashah** [comment]
hi @feliperaul I've sent you an email or you can contact me at shah@idk.uno
