### ISSUE TITLE
How can I do this? message button.

### ISSUE THREAD

**Issue by Bintang73** [open-wa/wa-automate-nodejs#2121]
![Screenshot_2021-09-14-00-04-24-38](https://user-images.githubusercontent.com/42708989/133126798-7113503a-dab7-4f89-bdb4-04e02f91d6e8.jpg)

Yes, I know it's been there before.
`client.sendButtons`

But it's different from the picture above.

**Comment by smashah** [comment]
@Bintang73  this is called a listmessage

https://docs.openwa.dev/classes/api_Client.Client.html#sendListMessage

It requires an insider's license thanks
