### ISSUE TITLE
TimeoutError: waiting for function failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by lfernandes** [open-wa/wa-automate-nodejs#2124]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

After update to latest Open-WA version (4.20.8) and enable multiDevice feature, we got this error:

```
/workspace/nodejs/wpobpc/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509
            const timeoutError = new Errors_js_1.TimeoutError(`waiting for ${options.title} failed: timeout ${options.timeout}ms exceeded`);
                                 ^

TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (/workspace/nodejs/wpobpc/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
    at DOMWorld.waitForFunction (/workspace/nodejs/wpobpc/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:464:26)
    at Frame.waitForFunction (/workspace/nodejs/wpobpc/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:909:32)
    at Page.waitForFunction (/workspace/nodejs/wpobpc/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2372:33)
    at /workspace/nodejs/wpobpc/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:182:26
    at Generator.next (<anonymous>)
    at fulfilled (/workspace/nodejs/wpobpc/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected Behavior

Be able to login/use WP.

### Steps To Reproduce

1. Set `multiDevice: true` into config;
2. Update the open-wa to 4.20.8;
3. run the program.

### Mode

My own code

### create() code

```markdown
wa.create({
	hostNotificationLang: 'PT_BR',
	authTimeout: 0,
	qrTimeout: 1000, //0 means it will wait forever for you to scan the qr code
	multiDevice: true
})
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2134.10",
  "WA_AUTOMATE_VERSION": "4.20.8",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
  "START_TS": 1631627796621
}
```

### Environment

```markdown
- OS: Linux 5.4
- Node: 16.4.1
- npm:
```

### Anything else?

Thank you!

**Comment by AffanTheBest** [comment]
Got same issue today.

Have you foundany solutions for it?

**Comment by AffanTheBest** [comment]
Hey @smashah can  you please help us out?

**Comment by smashah** [comment]
This navigation timeout refers to the fact that it took 30 seconds for the WA to respond to the "https://web.whatsapp.com" request - which is not an issue with the library but with the network.

I suggest inspecting what's going on with your network, maybe use a VPN?

All I can do is translate this error message into a "Unable to load WA WEB, please check your network/firewall"

If this is happening consistently @AffanTheBest please discuss further in the discord.

**Comment by AffanTheBest** [comment]
This happens only if I use **{multiDevice:true}** inside **create()**. And it worked well as soon as I removed this config.

BTW can I get discord invite link please.

**Comment by smashah** [comment]
@AffanTheBest click on the discord badge in the readme for an invite

**Comment by smashah** [comment]
in v4.22.5 there will be better logging for this issue.


1. Use chrome
2. Delete all previous .data.json / IGNORE folders
3. Don't switch between chrome/chromium, if you do you will have to delete the ignore folder and re scan qr code
