### ISSUE TITLE
Session data most likely expired due to manual host account logout. Please re-authenticate this session.

### ISSUE THREAD

**Issue by suzuya1331** [open-wa/wa-automate-nodejs#2126]
Session data most likely expired due to manual host account logout. Please re-authenticate this session.
![image](https://user-images.githubusercontent.com/60817875/133337068-13721764-160c-451f-b5bc-5bab4a4804f0.png)

**Comment by DaviZMelo** [comment]
same error here

**Comment by khaadaj** [comment]
here it was like in 4.20.6, so i upgraded to 4.20.8 and now it's giving this error
![image](https://user-images.githubusercontent.com/76663684/133337529-1ac285dd-8234-40df-a815-7c6a8bb72c7a.png)

**Comment by DaviZMelo** [comment]
![image](https://user-images.githubusercontent.com/49699162/133338176-07349d4c-d808-4962-af00-5a70c2bfd966.png)
Apparently the error is here

**Comment by jaykon-w** [comment]
same problem here

**Comment by ngoding-bro** [comment]
![Screenshot (40)](https://user-images.githubusercontent.com/74432059/133340186-6dfd2141-a7a5-4dea-aba7-5e31922bea1c.png)

this is the same as the problem that happened to me

**Comment by ngoding-bro** [comment]
![Screenshot (43)](https://user-images.githubusercontent.com/74432059/133340375-55f2f4c3-81e6-48df-b4dd-e56026088ac8.png)

this is the same as the problem i'm having

**Comment by aymenitc** [comment]
me too

**Comment by joelvitorniino** [comment]
me too

**Comment by DaviZMelo** [comment]
🎉 good news, i believe i managed to fix the bug :)
it was a problem with the qrcode selectors, apparently whatsapp web removed the "window.getQrCode()" method

#2127

**Comment by joelvitorniino** [comment]
>  good news, i believe i managed to fix the bug :)
> it was a problem with the qrcode selectors, apparently whatsapp web removed the "window.getQrCode()" method
> 
> #2127

good work man

**Comment by aymenitc** [comment]
can you please explain how to fix it. I'm not expert

**Comment by DaviZMelo** [comment]
> can you please explain how to fix it. I'm not expert

you can clone my fork and build manually or wait for the project owner to authorize my PR

**Comment by khaadaj** [comment]
Does anyone know how to solve it? I don't have experience in this
![image](https://user-images.githubusercontent.com/76663684/133352271-32af085f-5a99-4aa0-90d4-948dd2e30337.png)

**Comment by DaviZMelo** [comment]
> 🎉 good news, i believe i managed to fix the bug :)
> it was a problem with the qrcode selectors, apparently whatsapp web removed the "window.getQrCode()" method
> 
> #2127

temporary solution (closed the pull request), for those who want to use it with the session already ended

**Comment by smashah** [comment]
Hi all, I'm looking into this. Please share your WA_VERSION, I'm getting 2.2136.9

**Comment by joelvitorniino** [comment]
> Hi all, I'm looking into this. Please share your WA_VERSION, I'm getting 2.2136.9

Me too 2.2136.9

**Comment by axixu** [comment]
yes 2.2136.9

![image](https://user-images.githubusercontent.com/28151183/133362074-f2062135-ad3f-4ac6-b2f8-a7cb2fed74ae.png)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "minor"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.21.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.20.8...4.21.0) (2021-09-15)

- Release 4.21.0 [`5432815`](https://github.com/open-wa/wa-automate-nodejs/commit/5432815a4e35ebb37f22c3593886a619354f00e1)
- ✨ EASY API: `--cors` to enable all cors requests [`465739d`](https://github.com/open-wa/wa-automate-nodejs/commit/465739d9c2e24ad340c7adaea8e9146635ed4dd1)
- 🐛  temporary fix for #2126 [`6b8a0a3`](https://github.com/open-wa/wa-automate-nodejs/commit/6b8a0a3f5a38ee71eced474f60661f317e7bf000)
- updated types-only package [`a68bb5c`](https://github.com/open-wa/wa-automate-nodejs/commit/a68bb5cefb70b7268150f22c1ee95d7f02470087)

**Comment by smashah** [comment]
Everyone please update to the latest version and try again

**Comment by smashah** [comment]
Let me know if this is working for you and I'll close the issue.

Thanks

**Comment by asdasdsdasdasdas** [comment]
It is working, thank you :D

**Comment by smashah** [comment]
Awesome.

The fix is pretty silly but if it works it works I guess

Thanks for all the help and discussion. Love your username @asdasdsdasdasdas 

Closing

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.27.6](https://github.com/open-wa/wa-automate-nodejs/compare/4.27.5...4.27.6) (2021-12-19)

- Release 4.27.6 [`6e9a251`](https://github.com/open-wa/wa-automate-nodejs/commit/6e9a251589cd190f8facdbfb8b8e61215de53473)
- 🐛 fix "Session data most likely expired..." loop #2126 [`72ceeae`](https://github.com/open-wa/wa-automate-nodejs/commit/72ceeaef0393dc6e8abb5addc383aef48de9e453)
- updated types-only package [`e4b8baf`](https://github.com/open-wa/wa-automate-nodejs/commit/e4b8bafac5741d519b3ea6f0dc64c47333e49528)
