### ISSUE TITLE
is there any way to send messages to contacts that i never messaged?

### ISSUE THREAD

**Issue by DaviZMelo** [open-wa/wa-automate-nodejs#2132]
When I use:
`client.sendText(to, content)`

Even if the `ContactID` is valid, if I don't have previous messages with the `ContactID` the function doesn't work
When I manually send a message to this `ContactID` and try again, everything works fine.

is there any way to send messages to contacts that i never messaged?

**Comment by DaviZMelo** [comment]
saw about the restricted license key

**Comment by smashah** [comment]
@DaviZMelo please DM me on discord

**Comment by DaviZMelo** [comment]
> @DaviZMelo please DM me on discord

thanks for answering me :)
how do i get your discord?

**Comment by smashah** [comment]
@DaviZMelo click on the discord badge in the readme

**Comment by DaviZMelo** [comment]
@smashah sent
