### ISSUE TITLE
Please give me an example

### ISSUE THREAD

**Issue by ngoding-bro** [open-wa/wa-automate-nodejs#2137]
Can you give me an example how to use sendButtons

**Comment by smashah** [comment]
https://github.com/open-wa/wa-automate-nodejs/issues/98#issuecomment-881042026

**Comment by ngoding-bro** [comment]
![WhatsApp Image 2021-09-18 at 05 46 43](https://user-images.githubusercontent.com/74432059/133861269-600b9f06-7c4b-4b8f-8c24-2553e712ca7c.jpeg)
![Screenshot (49)](https://user-images.githubusercontent.com/74432059/133861287-b4b02f4c-8370-43fb-9791-4d4eee4346d0.png)
![Screenshot (47)](https://user-images.githubusercontent.com/74432059/133861303-9c764c05-f5a8-4965-9ee5-892f426f3790.png)

it doesn't respond at all? why?

**Comment by smashah** [comment]
If it is not working then you'll need to submit a new issue as it's different from 'give me an example'.

Please use the link in the logs to fill the issue template. Make sure to add all context and code, including whether or not you're using multidevice.
