### ISSUE TITLE
TypeError: Expected a string / is-url-superb

### ISSUE THREAD

**Issue by chgss** [open-wa/wa-automate-nodejs#2139]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

When I start a new session or old session I get this error:

`TypeError: Expected a string
    at module.exports (/root/npm/node_modules/is-url-superb/index.js:5:9)
    at Object.cli (/root/npm/node_modules/@open-wa/wa-automate/dist/cli/setup.js:400:13)
    at /root/npm/node_modules/@open-wa/wa-automate/dist/cli/index.js:44:68
    at Generator.next (<anonymous>)
    at /root/npm/node_modules/@open-wa/wa-automate/dist/cli/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/npm/node_modules/@open-wa/wa-automate/dist/cli/index.js:4:12)
    at start (/root/npm/node_modules/@open-wa/wa-automate/dist/cli/index.js:43:12)
    at Object.<anonymous> (/root/npm/node_modules/@open-wa/wa-automate/dist/cli/index.js:197:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)`

I can't get more logs the issues is the first and then finish, when I downgrade npm version from 7.24.0 to 7.20.6 I have the same results.

### Steps To Reproduce

1. npm 7.24.0, node v14.17.2
2.
```javascript
{
	"useChrome":true,
	"logConsole":true,
	"useNativeProxy": true,
	"proxyServerCredentials":
	{
		"address":"xxx",
		"username":"xxxx",
		"password":"xxx"
	},
	"webhook":
	[
		{
		"url":"https://webhook.net/owa",
		"events":"all"
		}
	],
	"sessionId":"1001",
	"sessionDataPath":"/root/owa/session/1001/",
	"port":9370,
	"pQueueDefault":{
		"intervalCap":1,
		"interval":2000,
		"carryoverConcurrencyCount":true
	},
	"customUserAgent":"Mozilla / 5.0 (compatible; MSIE 10.0; Windows; Windows NT 10.3;; en-US Trident"
}
```
3. 

### Mode

EASY API/CLI

### Environment

```markdown
- OS: CentOS Linux release 7.9.2009
- Node: v14.17.2
- npm: 7.24.0
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.21.2](https://github.com/open-wa/wa-automate-nodejs/compare/4.21.1...4.21.2) (2021-09-17)

- Release 4.21.2 [`5521359`](https://github.com/open-wa/wa-automate-nodejs/commit/55213594417ddc153c620b8825ee9543766de0fb)
- 🐛 check if webhook is string before checking `is-url` #2139 [`38c05b1`](https://github.com/open-wa/wa-automate-nodejs/commit/38c05b18c8764c3f26dd6b1e373f6330f9e28f87)
- updated types-only package [`7fa765b`](https://github.com/open-wa/wa-automate-nodejs/commit/7fa765b7e6a9539013bd176e91b57d861693dfee)

**Comment by smashah** [comment]
Try the latest version with this cli.config.json

```javascript

{
	"useChrome":true,
	"logConsole":true,
	"useNativeProxy": true,
	"proxyServerCredentials":
	{
		"address":"xxx",
		"username":"xxxx",
		"password":"xxx"
	},
	"webhook":"https://webhook.net/owa",
	"sessionId":"1001",
	"sessionDataPath":"/root/owa/session/1001/",
	"port":9370,
	"pQueueDefault":{
		"intervalCap":1,
		"interval":2000,
		"carryoverConcurrencyCount":true
	}}
```

**Comment by chgss** [comment]
Thanks @smashah :)
