### ISSUE TITLE
Check if i have right to send message to group

### ISSUE THREAD

**Issue by mouhammad-zd** [open-wa/wa-automate-nodejs#2143]
Hello

How i can check if i have rights to send messages to a specific group from its id,

I have checked the `restricted` property , but it seems that it has the value `false` in both cases either when i have rights to send messages and when i don't have rights 

Any help , thank you in advance for any regards

**Comment by smashah** [comment]
Check the canSend property on the chat object
https://docs.openwa.dev/interfaces/api_model_chat.Chat.html#canSend
