### ISSUE TITLE
Not reading *.data.json file on restart

### ISSUE THREAD

**Issue by danilocodes** [open-wa/wa-automate-nodejs#2144]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

I have to rescan the qr code every time I restart the app

### Expected Behavior

The app should read the session file that is created by scanning the qr code earlier

### Steps To Reproduce

Authenticate then restart the app

### Mode

My own code

### create() code

```js
const options = {
    sessionId: "Al-fred",
    disableSpins: true,
    skipUpdateCheck: true,
    useChrome: true,
    cacheEnabled: false,
    customUserAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0) Gecko/20100101 Firefox/42.0',
    multDevice: true,
    qrTimeout: 0, 
};
create(options)
    .then((client) => start(client))
    .catch((err) => console.log(err));
```

### DEBUG INFO

```json
{
  "WA_VERSION": "2.2136.10",
  "PAGE_UA": "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.21.2",
  "BROWSER_VERSION": "HeadlessChrome/92.0.4515.131",
  "OS": "Linux 5.4",
  "START_TS": 1631981974170
}
```

### Environment

```markdown
- OS: Linux 5.4
- Node: 14.15.3
- npm: 7.19.0
```

### Anything else?

From what I remember this bug started after enable multi device beta on phone

**Comment by smashah** [comment]
@danilocodes multidevice does not work with session data. I highly suggest not using multi device with this library as it is itself in beta.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "minor"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.22.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.21.2...4.22.0) (2021-09-18)

- Release 4.22.0 [`25ce28c`](https://github.com/open-wa/wa-automate-nodejs/commit/25ce28c3c196f48142aff7e29d8727c7844ce12d)
- ⚡️ perf: huge stability/memory improvement on `client.refresh()` #2089 [`5b76fc7`](https://github.com/open-wa/wa-automate-nodejs/commit/5b76fc75a554392c70e870a298e3d3ae65d51fb9)
- 🚸 improved MD support. Reauthentication working. #2144 [`978972e`](https://github.com/open-wa/wa-automate-nodejs/commit/978972e42df258a23eb49681bd84081fa581b45d)
- ➖ remove `ensure-gitignore` dep [`741a83e`](https://github.com/open-wa/wa-automate-nodejs/commit/741a83e5b03a5857c4186982a005c140172f1252)
- ✨ config: `ignoreNuke: true`/`--ignore-nuke` #2146 [`46fc43c`](https://github.com/open-wa/wa-automate-nodejs/commit/46fc43cb5807f4fc38151cb9dbb2ba07b49c68d3)
- 🥚 patches update [`d5ffb44`](https://github.com/open-wa/wa-automate-nodejs/commit/d5ffb448099c91b87c3a88dffeb012a7f9a31fb6)
- 🥚 patches update [`6441431`](https://github.com/open-wa/wa-automate-nodejs/commit/6441431aff37290e48967a719b180c4ac51436f0)
- updated types-only package [`58c0c49`](https://github.com/open-wa/wa-automate-nodejs/commit/58c0c491db2ebd2cf039ab5466f160dcb6e0db89)
