### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mnovel** [open-wa/wa-automate-nodejs#2145]
Error =>  TypeError: Cannot read property 'owner' of null
    at HandleMsg (E:\xampp\htdocs\whatsapp gateway\HandleMassage.js:74:50)     
    at E:\xampp\htdocs\whatsapp gateway\index.js:18:9
    at Client.<anonymous> (E:\xampp\htdocs\whatsapp gateway\node_modules\@open-wa\wa-automate\dist\api\Client.js:554:92)
    at Generator.next (<anonymous>)
    at fulfilled (E:\xampp\htdocs\whatsapp gateway\node_modules\@open-wa\wa-automate\dist\api\Client.js:24:58)

![image](https://user-images.githubusercontent.com/66077593/133896846-2f067dd1-0c49-45ca-a606-3256dcffb3a1.png)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.yaml&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.yaml&title=)⚠️⚠️⚠️
