### ISSUE TITLE
Send Message Error if multi device activate

### ISSUE THREAD

**Issue by angga30** [open-wa/wa-automate-nodejs#2152]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

i have connected with wa account multidevice but if i sending message error like below.

`POST /api/callback/ 200 18.359 ms - 71
wa_bot_api_1  | {
wa_bot_api_1  |   id_chat: 'REDACTED@c.us',
wa_bot_api_1  |   text: 'asdas',
wa_bot_api_1  |   id_local: 86,
wa_bot_api_1  |   file: null,
wa_bot_api_1  |   filename: null,
wa_bot_api_1  |   caption: null
wa_bot_api_1  | }
wa_bot_api_1  | (node:19) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: CHAT_JID: invalid jid type: Not an instance of WID
wa_bot_api_1  |     at t.CHAT_JID (https://web.whatsapp.com/bootstrap_qr.556a46806765846fd46b.js:3:103045)
wa_bot_api_1  |     at t.default (https://web.whatsapp.com/bootstrap_qr.556a46806765846fd46b.js:8:71721)
wa_bot_api_1  |     at Object.t.sendChatStateComposing (https://web.whatsapp.com/bootstrap_qr.556a46806765846fd46b.js:41:61002)
wa_bot_api_1  |     at Object.window.WAPI.simulateTyping (/usr/src/app/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1703:30)
wa_bot_api_1  |     at __puppeteer_evaluation_script__:1:23
wa_bot_api_1  |     at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
wa_bot_api_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
wa_bot_api_1  |     at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
wa_bot_api_1  | (node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)`

### Mode

My own code

### DEBUG INFO

```markdown
wa_bot_api_1  | - Debug info: {
wa_bot_api_1  |   "WA_VERSION": "2.2136.10",
wa_bot_api_1  |   "PAGE_UA": "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
wa_bot_api_1  |   "WA_AUTOMATE_VERSION": "4.22.1",
wa_bot_api_1  |   "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
wa_bot_api_1  |   "OS": "Linux 4.14",
wa_bot_api_1  |   "START_TS": 1632194674224
wa_bot_api_1  | }
```

### Environment

```markdown
- OS: Ubuntu 18.04
- Node: 14.15
- npm: latest
```

**Comment by smashah** [comment]
fixed with patch
