### ISSUE TITLE
Reply not sending all the time.

### ISSUE THREAD

**Issue by aymenitc** [open-wa/wa-automate-nodejs#2153]
Sometimes when user send the Bot command that call reply() function, it doesn't send the message. No errors happening just miss the sending.
To fix this I have to send the Bot a command that calls sendText() function from any contact. Or restart the session.
This is happening for a month or more and not just for me other Bot owners confirmed this too.

**Comment by jaykon-w** [comment]
I get this exact same problem, to fix it, I always send a user mention before the command result
