### ISSUE TITLE
Error when use ghostForward

### ISSUE THREAD

**Issue by paulocorcino** [open-wa/wa-automate-nodejs#2156]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

It is happen an error when use ghostForward.

![image](https://user-images.githubusercontent.com/7800501/134441583-89058d29-16d1-42ea-9770-234df38ccc41.png)

### Mode

My own code

### create() code

```markdown
{
    useChrome: true,    
    deleteSessionDataOnLogout: false,
    sessionDataPath: "whatsSessions/",
    sessionId: F.config['instance'].toString(),
    headless: true,
	hostNotificationLang: 'PT_BR',
	skipUpdateCheck:true,	
    autoRefresh:true, 
	logFile: true,
    qrTimeout:0,
	authTimeout:0,
    killTimer: 6000,
    blockCrashLogs: true, 
    bypassCSP: true,
	killProcessOnBrowserClose: false,
	maxChats: 1000,
	maxMessages: 1000
  }
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2136.10",
  "WA_AUTOMATE_VERSION": "4.22.2",
  "BROWSER_VERSION": "HeadlessChrome/91.0.4472.124",
  "START_TS": 1632359023039
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.1.0
- npm: 7.20.3
```

### Screenshots

![image](https://user-images.githubusercontent.com/7800501/134441233-c2ac37e4-2519-4148-b08e-5b56b2a3f51c.png)

**Comment by smashah** [comment]
patched

**Comment by paulocorcino** [comment]
It's Work!
Thank you @smashah!
