### ISSUE TITLE
puppeteer@10.2.0 install: `node install.js`

### ISSUE THREAD

**Issue by sakthimj** [open-wa/wa-automate-nodejs#2169]
i cant install in centos, i have some error

npm WARN lifecycle npm is using /opt/cpanel/ea-nodejs10/bin/node but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> puppeteer@10.4.0 install /home/store/wa-automate-nodejs/node_modules/puppeteer
> node install.js

sh: node: command not found
npm WARN swagger-stats@0.99.2 requires a peer of prom-client@>= 10 <= 13 but none is installed. You must install peer dependencies yourself.
npm WARN @open-wa/wa-automate@4.22.4 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! puppeteer@10.4.0 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the puppeteer@10.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-27T07_37_02_830Z-debug.log
[root@server wa-automate-nodejs]# sudo /opt/cpanel/ea-nodejs10/bin/npx @open-wa/wa-automate
sh: node: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! puppeteer@10.2.0 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the puppeteer@10.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-27T07_39_23_877Z-debug.log
Install for @open-wa/wa-automate@latest failed with code 1

**Comment by smashah** [comment]
@sakthimj  

Try this before running the npx command

https://docs.openwa.dev/pages/Getting%20Started/installation.html#centos-installation

**Comment by sakthimj** [comment]
as per instruction i have update the NPM and NODE version.
but i have another issue 

✓ Version: 4.22.4
✖ Error Could not find expected browser (chrome) locally. Run `npm install` to d                                                                                                             ownload the correct Chromium revision (901912). Error: Could not find expected b                                                                                                             rowser (chrome) locally. Run `npm install` to download the correct Chromium revi                                                                                                             sion (901912).

**Comment by smashah** [comment]
ok please fill the issue template. There is absolutely no context to these logs

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.yaml&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.yaml&title=)⚠️⚠️⚠️
