### ISSUE TITLE
healthCheck doesn't updated status when problem happens

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#2170]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Testing healthCheck setting wifi/3G/4G connection to off doesn't reflect on healthCheck.

### Expected Behavior

HealthCheck need be updated and point state to DISCONNECTED, isPhoneDisconnected to true, online to false, and tryingToReachPhone to true.  

### Steps To Reproduce

1. Run everything as normal
2. Disconnect your phone from internet
3. Check healthCheck 

### Mode

EASY API/CLI

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2136.10",
  "WA_AUTOMATE_VERSION": "4.22.4",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.82",
  "START_TS": 1632743936335
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 14.17.6
- npm:
```

**Comment by smashah** [comment]
Closing due to time. If this is still happening then please comment any updates to this issue
