### ISSUE TITLE
Error sending vcard

### ISSUE THREAD

**Issue by djeizan** [open-wa/wa-automate-nodejs#2181]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

When I try to send a vcard the following error is returned:
{"success":false,"error":{"name":"Error","message":"Evaluation failed: ReferenceError: body is not defined\n at Object.window.. [as sendVCard] (puppeteer_evaluation_script:1:193757)\n at puppeteer_evaluation_script:1:58"}}

WA_AUTOMATE Version 4.22.4

### Expected Behavior

vcard sended to contact

### Steps To Reproduce

Payload sended to API:

{"args":{"chatId":"55XXXXXXXXX-1626741097@g.us","vcard":"BEGIN:VCARD\r\nVERSION:3.0\r\nN:;jaison;;;\r\nFN:jaison\r\nORG:Cliente\r\nTITLE:\r\nitem1.TEL;waid=55XXXXXX:55XXXXXX\r\nitem1.X-ABLabel:Celular\r\nEND:VCARD","contactName":null}}

### Mode

EASY API/CLI

### DEBUG INFO

```markdown
Debug Info {
  WA_VERSION: 2.2136.10,
  PAGE_UA: WhatsApp/2.2108.8 Mozilla/5.0 <Macintosh; Intel Mac OSX 11_2_2> AppleWebKit/537.36 <KHTML, like Gecko> Chrome/89.0.4389.90 Safari/537.36,
  WA_AUTOMATE_VERSION: 4.22.4,
  BROWSER_VERSION: r901912
}
```

### Environment

```markdown
- OS: Windows Server 2012
- Node: V14.17.3
- npm: 6.14.13
```

**Comment by smashah** [comment]
resolved
