### ISSUE TITLE
Error sending buttons - ERROR 400

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#2185]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

When I try to send a message with Buttons I got error:
```
{
  "success": false,
  "response": "ERROR: 400"
}
```
### Expected Behavior

Receive a success true and send message with buttons.

### Steps To Reproduce
```
curl -X 'POST' \
  'http://host:51667/sendButtons' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": {
    "to": "***6991990***@c.us",
    "body": "Test",
    "buttons": [ "Yes", "No" ],
    "title": "string",
    "footer": "string"
  }
}'
```
### Mode

EASY API/CLI

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2138.10",
  "WA_AUTOMATE_VERSION": "4.22.4",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.82",
  "START_TS": 1632939815549
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 14.17.6
- npm: 6.14.15
```

**Comment by smashah** [comment]
Please see this for how to format your request: https://github.com/open-wa/wa-automate-nodejs/issues/98#issuecomment-881042026

So your request will need to be something like:

```
curl -X 'POST' \
  'http://host:51667/sendButtons' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": {
    "to": "***6991990***@c.us",
    "body": "Test",
    "buttons": [
        {
            "id": "1",
            "text": "Yes"
        },
        {
            "id": "2",
            "text": "No"
        }
    ],
    "title": "string",
    "footer": "string"
  }
}'
```

**Comment by itzharDev** [comment]
i got the same error:
Step to reproduce:
1. sendButtons to group (which is not allowed) OR add space to 'to' number `client.sendButtons(message.from + ' ', ...)`
2. then try sendButtons to regular c.us number - you start getting this error.

**Comment by smashah** [comment]
@itzharDev A 400 error can happen for many different reasons. It's an error code from the web socket itself telling you that there's something wrong with the payload. I cannot advise further without the exact payload (code) you are using to send the buttons that is causing this error.
