### ISSUE TITLE
Stuck after license validation while using `--safe-mode` flag

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#2187]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

When I use a license key i got stuck as follow:

✓ Authenticated
✓ Downloaded License in 2.931s
✖ You may experience issues in headless mode. Continuing...
✓ WAPI Reinjected
✓ Client is ready
✓ Downloaded patches in 0.031s
✓ Patches Installed: 99bb0
✓ Client loaded for normal account with 72 contacts, 66 chats & 77 messages in 38.473s
✓ License Valid: B2B_RESTRICTED_VOLUME_LICENSE

### Expected Behavior

Load complete with message "Listening on port 5***"!

### Steps To Reproduce

1. Use a license key
2. Run

### Mode

EASY API/CLI

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2138.10",
  "WA_AUTOMATE_VERSION": "4.22.4",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.82",
  "START_TS": 1633009900419
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 14.17.6
- npm: 7.24.1
```

**Comment by smashah** [comment]
@silvaartur resolved with latest patches. I don't think there's much use for safemode anymore but if you still want to use it - it is now timedout for 5 seconds instead of waiting forever for an updated state.
