### ISSUE TITLE
Error: Evaluation failed: Error: GROUP_JID: invalid jid type: Not an instance of WID

### ISSUE THREAD

**Issue by AffanTheBest** [open-wa/wa-automate-nodejs#2194]
Im Unable to get List of groups. 
Tried these methods:
```
- getAllGroups
- iAmAdmin
```
My Basic need is ```iAmAdmin()``` method.

My Code:
```js
async function initializeWhatsApp() {
    const client = await wa.create({sessionId:"vish", multiDevice:true, useChrome: true,  headless: true});
    return client;
}
async function main() {
    const waclient = await initializeWhatsApp();
    const groups = await waclient.getAllGroups();
    console.log(groups);
}
main()
```

Error:
```
(node:17468) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: GROUP_JID: invalid jid type: Not an instance of WID
    at t.GROUP_JID (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:3:119067)
    at https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:3:167602
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.ae27dc4782610dceb543.js:2:63784)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.ae27dc4782610dceb543.js:2:63995)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.ae27dc4782610dceb543.js:2:64054
    at j (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:2:379576)
    at j (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:2:379576)
    at new g (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:2:370471)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.ae27dc4782610dceb543.js:2:63935
    at t.queryGroup (https://web.whatsapp.com/bootstrap_qr.d3ab17b51a79359ce87d.js:3:165077)
```

Details:
```
@open-wa/wa-automate version - ^4.22.5
OS -  Windows 11
node - v14.17.0
npm -  7.17.0
```

**Comment by riservato-thiagomelo** [comment]
I'm afraid this issue has nothing to with the method being called, but rather an iOS or BETA version issue.

I have made a couple reduced tests and the script only ever gives me this error when I try to connect my buddy's iPhone (he's enabled WhatsAppe BETA).

**Comment by smashah** [comment]
I am not able to replicate it on my android devices. Tested both Beta and standard, business and personal.

**Comment by AffanTheBest** [comment]
Try it on multidevice beta

**Comment by smashah** [comment]
Yes, by beta i mean MD

**Comment by AffanTheBest** [comment]
Then why I'm getting that issue?

Is there anything wron in my code?

**Comment by smashah** [comment]
Not sure. With the code you've provided, I am unable to replicate. I suggest you log something after each line and paste all of your logs (including launch logs) here so we can actually track what's going on. Just showing the error provides no context when the code doesn't actually replicate the error.

**Comment by smashah** [comment]
I am unable to replicate this error. What is most likely happening is that this error is popping up due to the chat serializer trying to grab the group metadata and then

Either way the error is saying there is something wrong with the ID of the group. Somehow, it is not a valid Whatsapp ID. I don't know how this could happen to be honest but I'm going to attempt to catch any errors on attempting to grab the metadata and straight out ignore it. Hopefully this prevents this error from popping up. Maybe you'll notice some groups that are missing group metadata and therefore identify a pattern.

**Comment by riservato-thiagomelo** [comment]
If you want to, I can provide access to my account token.

**Comment by smashah** [comment]
If you can provide a screen cast of this error happening with the browser open then I'll take a look at it
