### ISSUE TITLE
getAllGroups() method wont retrive recently joined groups, unless the bot is restarted

### ISSUE THREAD

**Issue by riservato-thiagomelo** [open-wa/wa-automate-nodejs#2197]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

calling getAllGroups() won't retrieved recently joined groups

### Expected Behavior

calling getAllGroups() should retrieve any group, including the ones you have joined after starting the bot

### Steps To Reproduce

- start the bot;
- join a brand new group;
- call getAllGroups();
- `Chat[]` doesn't include the recently joined group.

### Mode

My own code

### create() code

```markdown
just follow "Steps To Reproduce" and you'll see...
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2138.13",
  "WA_AUTOMATE_VERSION": "4.22.5",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
  "START_TS": 1633292948357
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 12.21.0
- npm:
```

**Comment by smashah** [comment]
I just tested by:

Sending my host account a link to join a group
joining group via code 
calling getAllGroups

And the new group showed up ok. There's relevant context missing here which is not allowing me to reproduce this problem.

Note: This was on a normal session (i.e not MD)

**Comment by riservato-thiagomelo** [comment]
ok. I'll close this for now, since I wont be able to give more context for the moment being.
