### ISSUE TITLE
Function getUnsentMessages not working.

### ISSUE THREAD

**Issue by deriknyvo** [open-wa/wa-automate-nodejs#2210]
Hello, sorry for not filling out the template.

I'm calling the getUnsentMessages() function to retrieve the messages that weren't sent because of the disconnected device, but the return is an internal core error. 

function call
![image](https://user-images.githubusercontent.com/33598231/136396913-fe4abff9-5650-49a5-b7ef-24d2a1e604cd.png)

error message :(
![image](https://user-images.githubusercontent.com/33598231/136397139-df2f7005-e3e2-435b-a1f1-09494854b2cb.png)

Is this a bug? or am I using it wrongly? And if it's a bug is there any other way I can get messages that haven't been sent on the device yet due to lack of connection?

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.23.1](https://github.com/open-wa/wa-automate-nodejs/compare/4.23.0...4.23.1) (2021-10-08)

- build(deps): bump eventemitter2 from 6.4.4 to 6.4.5 [`#2199`](https://github.com/open-wa/wa-automate-nodejs/pull/2199)
- Add Text Variation for botpress text [`#2211`](https://github.com/open-wa/wa-automate-nodejs/pull/2211)
- Release 4.23.1 [`f8b365e`](https://github.com/open-wa/wa-automate-nodejs/commit/f8b365e00ba064f9750a29e40a24947bbb198a46)
- Update LICENSE.md [`8892851`](https://github.com/open-wa/wa-automate-nodejs/commit/88928514d1ec34c5d6dabc28c66fff99f880a299)
- 🔧 updated release-it config [`b5daa92`](https://github.com/open-wa/wa-automate-nodejs/commit/b5daa92f65940f35a6bd7bfd2f8f843d303eacaa)
- 🥚 patches update [`f4cbe17`](https://github.com/open-wa/wa-automate-nodejs/commit/f4cbe17430e20ff30d3fe306d04728e90bae4c6c)
- Update .release-it.json [`19d2101`](https://github.com/open-wa/wa-automate-nodejs/commit/19d21018645765ca3a6f1d71a8365566abfce773)
- updated npm release timeout [`ae7c393`](https://github.com/open-wa/wa-automate-nodejs/commit/ae7c393c3c3eaf369b6d131f977bb8e1176b9373)
- 🥚 patches update [`387dacb`](https://github.com/open-wa/wa-automate-nodejs/commit/387dacb620ec30a49b41cb3b5c1b2e1b8b4e34f4)
- updated types-only package [`d6c180d`](https://github.com/open-wa/wa-automate-nodejs/commit/d6c180d9f1ffab6e86ae86b9f3d8a2c32adc1635)
