### ISSUE TITLE
Send Button not working

### ISSUE THREAD

**Issue by ngoding-bro** [open-wa/wa-automate-nodejs#2215]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Send button not working

### Expected Behavior

Hope it works normally

### Steps To Reproduce

1. await indra.sendButtons(from, "Halo", {id:"1","text":"Anjay"},{id:"1","text":"Anjir"},"title")
2. Run Npm
3. Get Error: (Error: Evaluation failed: TypeError: _0x315daa.map is not a function)

### Mode

My own code

### create() code

```markdown
create({sessionId: 'Indra',
        headless: true,
        qrTimeout: 0,
        authTimeout: 0,
        restartOnCrash: start,
        cacheEnabled: false,
        useChrome: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false,
        chromiumArgs: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--aggressive-cache-discard',
            '--disable-cache',
            '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            '--disk-cache-size=0'
        ]
    })
```

### DEBUG INFO

```markdown
Debug Info {
 WA_VERSION: 2.2138.13
 PAGE_UA: WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
 WA_AUTOMATE_VERSION: 4.23.0
 BROWSER_VERSION: HeadlessChrome/94.0.4606.71
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 14.17.4
- npm: 6.14.14
```

### Screenshots

![Screenshot (59)](https://user-images.githubusercontent.com/74432059/136529587-9488df8e-ece2-43d9-9cd4-e0d10f0bad5b.png)

### Anything else?

Nothing, hope it gets back to normal soon

**Comment by cantiir2** [comment]
Can the button response? How to?
