### ISSUE TITLE
Question: How to detect word after command?

### ISSUE THREAD

**Issue by itshaiheree** [open-wa/wa-automate-nodejs#2234]
How to detect word after command? Because I want to create a #ytinfo command with a link

**Comment by justClizz** [comment]
> > How to detect word after command? Because I want to create a #ytinfo command with a link
> 
> I have this approach, dont know if its the best but works for me
> 
> ```js
> const getMemberInfo = async (message) => {
>     let body = message.body.split(' '); // split message content on spaces
>     body.shift(); // remove first item from the result array (the first item is your command)
>     const member = body[0]; // then you can parse command args by its indexes of the array
>     if (!member) return false; // if body[0] is undefined it means that the command message has no args
> 
>     // do your stuff with the args
> };
> ```

ok thanks, i will try it

**Comment by justClizz** [comment]
> > How to detect word after command? Because I want to create a #ytinfo command with a link
> 
> I have this approach, dont know if its the best but works for me
> 
> ```js
> const getMemberInfo = async (message) => {
>     let body = message.body.split(' '); // split message content on spaces
>     body.shift(); // remove first item from the result array (the first item is your command)
>     const member = body[0]; // then you can parse command args by its indexes of the array
>     if (!member) return false; // if body[0] is undefined it means that the command message has no args
> 
>     // do your stuff with the args
> };
> ```

It works, thanks!
