### ISSUE TITLE
it is not an issue but i dont know where to ask this since i cant find any help channel related to the library. if there is a discord channel or something to give support i´d really appreciate that.

### ISSUE THREAD

**Issue by pumpkin39849** [open-wa/wa-automate-nodejs#2253]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

i´d like to know if is there a way to tag a whole group "hidden", something like an hiddentag command, thank you in advance.

### Mode

My own code

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

**Comment by smashah** [comment]
Click the discord badge in the readme
