### ISSUE TITLE
Starting docker automate node with paid license - NO MD

### ISSUE THREAD

**Issue by daopapp** [open-wa/wa-automate-nodejs#2254]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Start the docker
when validate the license key, the process stuck and start to increase the memory and CPU use.

### Expected Behavior

Start docker and finish the setup OK

### Steps To Reproduce

> wa-automate-docker@1.0.0 wa55XXXXXXXXXXX
> npx @open-wa/wa-automate --in-docker -p XXXX --npm-options=--ignore-scripts --authTimeout=0 --qrTimeout=0 -l XXXXXX-XXXXXX-XXXXXX-XXXXXX -w https://XXX.XXXXXXX/whatsapp/message/55XXXXXXXXXXX

- session_STARTUP
- webhooks set already
- Launching EASY API
- Selected port is free
- Generating Swagger Spec
- Postman collection generated: open-wa-session.postman_collection.json
- API collections (swagger + postman) generated successfully
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓┃                                                                              ┃┃   @open-wa/wa-automate                                                       ┃┃   💬 🤖 The most reliable NodeJS whatsapp library for chatbots with          ┃┃   advanced features.                                                         ┃┃   Version: 4.23.6                                                            ┃┃   Check out the latest changes:                                              ┃┃   https://github.com/open-wa/wa-automate-nodejs#latest-changes               ┃┃                                                                              ┃┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
- Starting
- Version: 4.23.6
- Initializing WA
- Launching Browser
- Setting Up Browser
- Loading session data
- Found session data file: /usr/src/app/session.data.json
- Existing session data detected. Injecting...
- Existing session data injected
- Navigating to WA
- Page loaded in 677ms: 200
- Browser Launched
- Debug info: {
  "WA_VERSION": "2.2142.12",
  "PAGE_UA": "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.23.6",
  "BROWSER_VERSION": "HeadlessChrome/79.0.3945.88",
  "OS": "Linux 4.15",
  "START_TS": 1635690009357
}
- Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&debug_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2142.12%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.23.6%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/79.0.3945.88%22,%0A%20%20%22START_TS%22:%201635690009357%0A%7D&environment=-%20OS:%20Linux%204.15%0A-%20Node:%2015.12.0%0A-%20npm:%20%0A
- Injecting api
- WAPI injected
- Authenticating
- Authenticated
- Fetching License: XXXXXXXX
- Reinjecting api
- WAPI Reinjected
- Checking if session is valid
- Downloading patches from https://cdn.openwa.dev/patches.json
- Client is ready
- Generating patch hash
- Downloaded patches in 0.031s
- Installing patches
- Patches Installed: 054b7
- Client loaded for business account with 4655 contacts, 3170 chats & 1476 messages in 18.917s
- Downloaded License in 2.006s
- Checking License
- Injecting License...
- License injected successfully..
- License Valid: Restricted License Key

### Mode

EASY API/CLI

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2142.12",
  "WA_AUTOMATE_VERSION": "4.23.6",
  "BROWSER_VERSION": "HeadlessChrome/79.0.3945.88",
  "START_TS": 1635690009357
}
```

### Environment

```markdown
- OS: Linux 4.15
- Node: 15.12.0
- npm: 7
```

**Comment by smashah** [comment]
This was a regression due to onNewProduct. I've removed it as a feature so your session should load without delay now thanks
