### ISSUE TITLE
Download limit 

### ISSUE THREAD

**Issue by freitas666** [open-wa/wa-automate-nodejs#2261]
Hello

I would like to change my download limit of music/video from 5 minutes to 10 minutes....

I tried check all files but not find where is this limit.... could someone help me?

Thanks!

**Comment by smashah** [comment]
Download or upload? The upload limit in the session is set be WA to be around 60mb if i remember correctly.

**Comment by freitas666** [comment]
@smashah thank you for reply! 

exemple, i have a command like !play "name of song" so it will download the song and convert... but when the song have more 10 minutes not is possible download... I would like change it... I am broken my head in my keyboard to try to find it =P

**Comment by smashah** [comment]
@freitas666 can you give me an example mp4 URL that causes this issue please

**Comment by freitas666** [comment]
@smashah 

//REQUERINDO MÓDULOS
const fs = require('fs-extra')
const msgs_texto = require('../lib/msgs')
const {criarTexto, erroComandoMsg, removerNegritoComando} = require("../lib/util")
const api = require("../lib/api")
const {default: PQueue} = require('p-queue')

//FILAS
const filaPlay = new PQueue({concurrency: 5, timeout: 60000})
const filaYT = new PQueue({concurrency: 1, timeout: 60000})
const filaIg = new PQueue({concurrency: 1, timeout: 60000})
const filaFb = new PQueue({concurrency: 1, timeout: 60000})
const filaTk = new PQueue({concurrency: 1, timeout: 60000})
const filaTw = new PQueue({concurrency: 1, timeout: 60000})
const filaImg = new PQueue({concurrency: 2, timeout: 60000})

module.exports = downloads = async(client,message) => {
    try{
        const { type, id, from, quotedMsg, body, caption} = message
        const commands = caption || body || ''
        var command = commands.toLowerCase().split(' ')[0] || ''
        command = removerNegritoComando(command)
        const args =  commands.split(' ')

        switch(command){      
            case "!play":
                if(args.length === 1) return await client.reply(from,erroComandoMsg(command),id)
                try{
                    var usuarioTexto = body.slice(6).trim(), videoInfo = await api.obterInfoVideoYT(usuarioTexto)
                    if(videoInfo == null) return await client.reply(from, msgs_texto.downloads.play.nao_encontrado, id)
                    if(videoInfo.duration > 300000) return await client.reply(from, msgs_texto.downloads.play.limite, id)
                    var mensagemEspera = criarTexto(msgs_texto.downloads.play.espera, videoInfo.title, videoInfo.durationFormatted)
                    await client.reply(from, mensagemEspera, id)      
                } catch(err){
                    return await client.reply(from,err.message,id)
                }

                try{
                    await filaPlay.add(async () => {
                        var saidaAudio = await api.obterYtMp3(videoInfo)
                        client.sendFile(from, saidaAudio, `${videoInfo.title}.mp3`,"", id).then(()=>{
                            fs.unlinkSync(saidaAudio)
                        }).catch(()=>{
                            fs.unlinkSync(saidaAudio)
                            client.reply(from, msgs_texto.downloads.play.erro_download, id)
                        })
                    })
                } catch(err){
                    await client.reply(from,err.message,id)
                }
                break

**Comment by smashah** [comment]
@freitas666 I need a specific value of `saidaAudio` that triggers this issue. And an error log. To be honest you should've just filled in the issue template.

**Comment by freitas666** [comment]
@smashah 

   obterAudioModificado: (caminhoAudio, tipoEdicao) =>{
        return new Promise((resolve,reject)=>{
            let saidaAudio = path.resolve(`media/audios/${obterNomeAleatorio(".mp3")}`)
            let ffmpegOpcoes = []
            switch(tipoEdicao){
                case "estourar":
                    ffmpegOpcoes = ["-y", "-filter_complex", "acrusher=level_in=3:level_out=5:bits=10:mode=log:aa=1"] 
                    break
                case "reverso":
                    ffmpegOpcoes = ["-y", "-filter_complex", "areverse"]
                    break
                case "grave":
                    ffmpegOpcoes = ["-y", "-af", "asetrate=44100*0.8"]
                    break
                case "agudo":
                    ffmpegOpcoes = ["-y", "-af", "asetrate=44100*1.4"]
                    break
                case "x2":
                    ffmpegOpcoes = ["-y", "-filter:a", "atempo=2.0", "-vn"]
                    break
                case "volume":
                    ffmpegOpcoes = ["-y", "-filter:a", "volume=4.0"]
                    break
                default:
                    reject()
            }

**Comment by freitas666** [comment]
I will put a example for you...

!play ozzy

generate a error saying that my music should have less than 5 minutes

!play baby shark (haha...)
the works well because this music have less than 5 minutes as show in image have 2:17 minutes 

![875D3B5F-5BE5-4148-B463-2C7F792AD233_1_201_a](https://user-images.githubusercontent.com/2224558/139927614-5ce42dbc-5238-4dcb-8395-2be6192b5d63.jpeg)

**Comment by freitas666** [comment]
@smashah my friend... thank you ,.... I find my error in code 🗡️ 

Now everything is working well! thank you very much! if you come to Brazil I will pay a beer for you !

**Comment by freitas666** [comment]
solved!
