### ISSUE TITLE
sendFileFromUrl sending mp4 file without preview

### ISSUE THREAD

**Issue by victorsouzaleal** [open-wa/wa-automate-nodejs#2262]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Hello again, it's been a few months since I've used the open-wa library and now I'm going back to active and I saw that the functions that use sendFileFromUrl aren't sending the preview of the mp4 video just the file to be downloaded.

And I'm even using the documentation example video.

### Expected Behavior

The preview of the video should be displayed and not the file to be downloaded

### Steps To Reproduce

Use : `await client.sendFileFromUrl(from, "https://i.giphy.com/media/oYtVHSxngR3lC/200w.mp4", "previa.mp4")`

### Mode

My own code

### create() code

```markdown
CREATE

create(config(true, start))
    .then(client => start(client))
    .catch((error) => consoleErro(error, 'OPEN-WA'))

CONFIG FILE

module.exports = config = (headless, start) =>  {
    return{
        sessionId: 'session',
        headless,
        qrTimeout: 0,
        authTimeout: 0,
        skipUpdateCheck: true,
        cachedPatch: true,
        cacheEnabled: false,
        restartOnCrash: start,
        useChrome: true,
        stickerServerEndpoint: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false,
        chromiumArgs: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--aggressive-cache-discard',
            '--disable-cache',
            '--disable-gl-drawing-for-tests',
            '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            '--disk-cache-size=0'
        ]
    }
}
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2142.12",
  "WA_AUTOMATE_VERSION": "4.23.6",
  "BROWSER_VERSION": "HeadlessChrome/95.0.4638.69",
  "START_TS": 1635901619745
}
```

### Environment

```markdown
- OS: Windows 11
- Node: 16.13.0
- npm: 8.1.0
```

### Screenshots

![image](https://user-images.githubusercontent.com/4674786/139987695-7884945e-d308-48e4-92ae-8dcb7394a41a.png)

**Comment by smashah** [comment]
Not sure why that's happening especially if `useChrome` is true.

I suggest trying this

```js
await client.sendImage(from, "https://i.giphy.com/media/oYtVHSxngR3lC/200w.mp4", "previa.mp4")
````

with config:

```javascript
{
        sessionId: 'session',
        headless,
        qrTimeout: 0,
        authTimeout: 0,
        skipUpdateCheck: true,
        cacheEnabled: false,
        restartOnCrash: start,
        useChrome: true,
        stickerServerEndpoint: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false,
    }
```

**Comment by victorsouzaleal** [comment]
> Not sure why that's happening especially if `useChrome` is true.
> 
> I suggest trying this
> 
> ```js
> await client.sendImage(from, "https://i.giphy.com/media/oYtVHSxngR3lC/200w.mp4", "previa.mp4", "")
> ```
> 
> with config:
> 
> ```js
> {
>         sessionId: 'session',
>         headless,
>         qrTimeout: 0,
>         authTimeout: 0,
>         skipUpdateCheck: true,
>         cacheEnabled: false,
>         restartOnCrash: start,
>         useChrome: true,
>         stickerServerEndpoint: true,
>         killProcessOnBrowserClose: true,
>         throwErrorOnTosBlock: false,
>     }
> ```
> 
> also, the code you provided can no way reply to that message so something is missing from this issue.
> 
> Please check the docs for updated params:
> 
> https://docs.openwa.dev/classes/api_Client.Client.html#sendImage

I still have the same problem, and the print from before was with a different code (my bad)
```js
await client.sendFileFromUrl(from, "https://i.giphy.com/media/oYtVHSxngR3lC/200w.mp4", "previa.mp4", "caption", id)
```

**Comment by smashah** [comment]
Doesn't work:

`https://i.giphy.com/media/oYtVHSxngR3lC/200w.mp4`

Works:

`https://i.giphy.com/media/oYtVHSxngR3lC/giphy.mp4`

Literally just change `200w` to `giphy`. I will update the demo.

Thanks
