### ISSUE TITLE
iOS multi-device is now out of beta

### ISSUE THREAD

**Issue by lukasportal** [open-wa/wa-automate-nodejs#2268]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

iOS devices now have all been updated to the new multi-device system
when injecting WAPI, i'm getting the following error:

Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported
at serviceworker.js:1
at Generator.next ()
at c (serviceworker.js:1)
at o (serviceworker.js:1)

When you scan the QR Code, it just keeps loading and never connects

### Expected Behavior

Connect properly

### Steps To Reproduce

1. Click on the upgrade button to join the multi device (multi-device is now the default option and can't be reversed)
2. It will log you out
3. Inject WAPI
4. error appears in console
5. Try to scan the QR Code and it will never connect

### Mode

EASY API/CLI

### Environment

```markdown
- OS: Windows 10
- Node: 16.13.0
- npm: 8.1.0
```

**Comment by jeferssonlemes** [comment]
the same here

**Comment by smashah** [comment]
You can ignore the error
```javascript
Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported
at serviceworker.js:1
at Generator.next ()
at c (serviceworker.js:1)
at o (serviceworker.js:1)
```

If you want to use MD with EASY API then you should use the `--multi-device` flag and with a brand new session ID (or just delete the session data file for the respective session)

```
> ... --multi-device --session-id="new_session_id"
```

I just found out today that MD is going to be default 5 days from now - so after that I will probably set `multiDevice` to `true` by default.

**Comment by lukasportal** [comment]
I did all of that, with a clean session, but the main issue right now is that some methods that call the server never return anything
for example: ```await window.Store.WapQuery.queryExist(chatId)```
this gets stuck and never returns anything

**Comment by smashah** [comment]
@lukasportal should be patched. Can you try queryExist  again please

**Comment by lukasportal** [comment]
@smashah still nothing 😢 i see the reference to WapQuery changed but queryExist() still gets stuck

**Comment by smashah** [comment]
@lukasportal since you're in the session anyways

please output the result of 

```
window.isMd()
```

**Comment by lukasportal** [comment]
@smashah ```true```
what exactly should be set/injected to make that work? maybe i can manually insert it

**Comment by smashah** [comment]
@lukasportal ok.

Step 1. Make sure you're getting this patch hash:
![CleanShot 2021-11-10 at 19 18 12](https://user-images.githubusercontent.com/5903821/141178812-875d0cb0-ae04-4a34-ae06-5f3d2b5b9697.png)

Step 2. 

Run `await WAPI.checkNumberStatus('NUMBER@c.us')`

Step 3.
Run

`await Store.WapQuery.queryExist('NUMBER@c.us')`

**Comment by smashah** [comment]
running `WAPI.checkNumberStatus` should fix Store.WapQuery.queryExist

**Comment by lukasportal** [comment]
no luck 😢 

Patch hash is ```2f477```
```isMd()``` is ```true```

following your steps didn't work, they all return nothing, just get stuck
don't know what else to do

**Comment by smashah** [comment]
Please paste all of your launch logs here

**Comment by lukasportal** [comment]
i skipped the qr code part

![image](https://user-images.githubusercontent.com/5941939/141223353-6af3443c-cbb7-4914-8eca-2ba11987f356.png)
![image](https://user-images.githubusercontent.com/5941939/141223392-b5dc19e6-df33-4dc5-a8fc-f1df34f6ba90.png)
![image](https://user-images.githubusercontent.com/5941939/141223469-4c3a63bf-42c3-4147-b501-618ecac873ab.png)
![image](https://user-images.githubusercontent.com/5941939/141223516-22791a3e-7c99-4572-909f-1408ddc350a6.png)

**Comment by smashah** [comment]
@lukasportal please update to the latest version of the library and discuss further in the discord thanks.

Closing

**Comment by lukasportal** [comment]
@smashah  What's the discord link?

**Comment by smashah** [comment]
> @smashah  What's the discord link?

Click on the discord badge in the readme
