### ISSUE TITLE
Hey, I'am having problem with this function. It's not returning anything.

### ISSUE THREAD

**Issue by luidigo** [open-wa/wa-automate-nodejs#2269]
Hey, I'am having problem with this function. It's not returning anything.
This problem began with new whatsapp multi-device version.

`{
    id: 'WapQuery',
    conditions: (module) => (module.default && module.default.queryExist) ? module.default : null
}`

and

`Store.WapQuery.queryExist("1111111111@c.us")`

Anyone with same problem?

_Originally posted by @luidigo in https://github.com/open-wa/wa-automate-nodejs/issues/1802#issuecomment-962089299_

**Comment by lukasportal** [comment]
same here

**Comment by alpires** [comment]
In MD version this function does not work. The create groups function doesn't work either.

**Comment by jeferssonlemes** [comment]
same here

**Comment by smashah** [comment]
@luidigo Please use `WAPI.checkNumberStatus` instead as it's patched to work with MD already.


<img width="1127" alt="CleanShot 2021-11-06 at 00 04 28@2x" src="https://user-images.githubusercontent.com/5903821/140590686-cd2d5c66-9b6b-48cc-87ad-976a58b0aa91.png">

**Comment by lukasportal** [comment]
Hi @smashah what is the patch for ```WAPI.checkNumberStatus(id)```?
I just tried it using the latest code and it still doesn't return anything
seems that the code simply calls ```WapQuery.queryExist(id)``` which is where it hangs
a ```try/catch``` wouldn't fix it as the response is never returned so it will never reach the catch

am I missing something? here's the latest code I see for this function:


```
window.WAPI.checkNumberStatus = async function (id) {
    try {
        const result = await window.Store.WapQuery.queryExist(id);
        if (result.jid === undefined) throw 404;
        const data = window.WAPI._serializeNumberStatusObj(result);
        if (data.status == 200) data.numberExists = true
        return data;
    } catch (e) {
            return window.WAPI._serializeNumberStatusObj({
                status: e,
                jid: id
            });
    }
};
```
