### ISSUE TITLE
client.inviteInfo isn't working on MD

### ISSUE THREAD

**Issue by iluser** [open-wa/wa-automate-nodejs#2270]
### Are you using the latest version of the library?

- [x] I have checked and am using the latest version of the library.

### Current Behavior

when I use `client.inviteInfo` in Multidevice mode, there are no results or error messages in the log

### Mode

My own code

### create() code

```markdown
My code:

let inf = await client.inviteInfo('https://chat.whatsapp.com/__REDACTED__').catch((e) => {sendText(e)})
sendJSON(inf)
```

### Environment

```markdown
- OS: windows
- npm: 8.1.0
```

### Screenshots

__REDACTED__

**Comment by smashah** [comment]
patched
