### ISSUE TITLE
Add forwardMessage function

### ISSUE THREAD

**Issue by eyalmichon** [open-wa/wa-automate-nodejs#2277]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

Would be good to have a forwardMessage function that returns as a promise the id of the message that has been forwarded. (In case I want to be able to reply to that message later on)

### Mode

My own code

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2142.12",
  "WA_AUTOMATE_VERSION": "4.23.7",
  "BROWSER_VERSION": "HeadlessChrome/95.0.4638.54",
  "START_TS": 1636215764894
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 14.17.6
- npm:
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.23.9](https://github.com/open-wa/wa-automate-nodejs/compare/4.23.8...4.23.9) (2021-11-11)

- Release 4.23.9 [`877a300`](https://github.com/open-wa/wa-automate-nodejs/commit/877a300b3a9832af69f0129efc7f41ed6b71201a)
- ✨  feat: `forwardMessages` now returns `MessageID[]` on success #2277 [`5a509fa`](https://github.com/open-wa/wa-automate-nodejs/commit/5a509faf4803ad7232aa4a39bfe9ceeb82e29c16)
- updated types-only package [`1d71e6d`](https://github.com/open-wa/wa-automate-nodejs/commit/1d71e6d34e7aee0c735ced3d72cda40a034328e0)
