### ISSUE TITLE
 After clearing the chat, a new group is detected and members enter

### ISSUE THREAD

**Issue by badriyatus123** [open-wa/wa-automate-nodejs#2280]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

I deleted all messages using
```
const allChats = await client.getAllChats()
for (let delChats of allChats) {
  await client.deleteChat(delChats.id)
}
```
after that I tried restarting my server while waiting for the chat cleanup to be successful, and when the chat cleanup was finished I reactivated it and there all the deleted groups detected `onAddedToGroup `and members `message.groupMetadata.participants .length` only partially detected even 0

### Expected Behavior

I hope it is fixed because it also affects the welcome feature where all members in the group that were affected by deletion are detected as new members entering the group and it becomes welcome spam to the group

### Steps To Reproduce

1.Delete all messages
2.Run the bot which has "onAddedToGroup"
3. After that there will be group members who chat for sure "onAddedToGroup" will detect a new group

### Mode

My own code

### create() code

```markdown
create({
    useChrome: true,
    qrLogSkip: false,
})
```

### DEBUG INFO

```markdown
WA_VERSION : '2.2142.12'
PAGE_UA : 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
WA_AUTOMATE_VERSION : '4.23.7'
BROWSER_VERSION : 'HeadlessChrome/93.0.4577.0'
OS :'Windows 10'
START_TS : 1636426111957
```

### Environment

```markdown
- OS: windows 1-
- Node: v16.13.0
- npm: 8.1.0
```

### Screenshots

![image](https://user-images.githubusercontent.com/87899416/140855086-78bd5e26-a086-4de2-9cbd-22f543e7d276.png)

**Comment by smashah** [comment]
looks like this issue fell through the cracks. Let me know if it this is still a problem. Closing for now
