### ISSUE TITLE
on scan qrcode whatsapp ban the number

### ISSUE THREAD

**Issue by EduardoBezerraDev** [open-wa/wa-automate-nodejs#2282]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

a

### Expected Behavior

a

### Steps To Reproduce

scan the qrcode

### Mode

My own code

### create() code

```markdown
a
```

### DEBUG INFO

```markdown
a
```

### Environment

```markdown
- OS: windows 10
- Node: 
- npm:
```

### Screenshots

a

### Anything else?

a

**Comment by smashah** [comment]
Bans can happen for many reasons + you have not filled in the template with any context. Please discuss further in discord

**Comment by EduardoBezerraDev** [comment]
First scan  qrcode was Ban

Em qua., 10 de nov. de 2021 11:19, Mohammed Shah ***@***.***>
escreveu:
