### ISSUE TITLE
SendButtons, sendLinkWithAutoPreview and session dont work

### ISSUE THREAD

**Issue by manteguinha** [open-wa/wa-automate-nodejs#2284]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

The buttons and sendLinkWithAutoPreview are not working and after closing the session it asks to read the QR again, it is not saving

### Mode

My own code

### Environment

```markdown
- OS: Windows 10 Server
- Node: v14.17.4
- npm: 7.24.2
```

**Comment by smashah** [comment]
This is not an issue with the library

Read this

https://wabetainfo.com/whatsapp-beta-for-android-2-21-23-13-whats-new/

Downgrade your app. And make sure it stays there. Or read the multi device section in the readme.
