### ISSUE TITLE
sendImage return false for non-contact number

### ISSUE THREAD

**Issue by mrizkypk** [open-wa/wa-automate-nodejs#2285]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

```
await client
  .sendImage(
    'NON CONTACT@c.us',
    'https://file-examples-com.github.io/uploads/2017/10/file_example_JPG_100kB.jpg',
    'payment-proof',
    'Payment Proof'
  )
  .then(result => {
    console.log(result);
    //THIS RETURN false
  })
  .catch(erro => {
    console.log(erro);
  });
```
SendImage function not working when sending image with caption to the non-contact number even with License Key.
This function doesn't go into error catch and instead return false.
The message is not sent, but if I use the sendText function, there is no problem and the message is sent to the non-contact number.

### Mode

My own code

### create() code

```markdown
.create({
  licenseKey: ""
})
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2144.8",
  "WA_AUTOMATE_VERSION": "4.23.9",
  "BROWSER_VERSION": "HeadlessChrome/88.0.4298.0",
  "START_TS": 1636609509869
}
```

### Environment

```markdown
- OS: Linux 5.4
- Node: 16.13.0
- npm: 8.1.0
```

**Comment by smashah** [comment]
You cannot start a conversation with an image. This is a feature to prevent your account from being high risk for banning. Always start a chat with an introductory message then add media or other types of messages

**Comment by mrizkypk** [comment]
Oh, I see. Thanks.

**Comment by mrizkypk** [comment]
Hi, this happens again when I use Multi Devices mode. It looks like Store.Chat.find returns false even though a chat already exists.

**Comment by smashah** [comment]
resolved thanks
