### ISSUE TITLE
Suggestion; Custom Sticker;

### ISSUE THREAD

**Issue by swatky** [open-wa/wa-automate-nodejs#2287]
Hi, I suggest implementing the sticker option with "slightly rounded corners", because I think it's beautiful and I think it would look really cool.
Preferably optional, as is the "isCircle" function.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.23.16](https://github.com/open-wa/wa-automate-nodejs/compare/4.23.15...4.23.16) (2021-11-21)

- Release 4.23.16 [`9b3550f`](https://github.com/open-wa/wa-automate-nodejs/commit/9b3550f68c287585a9b4d9206926280ea0a8559c)
- 🏷️ type: improved `Chat` docs #2308 [`236437a`](https://github.com/open-wa/wa-automate-nodejs/commit/236437ae720d61b27d0096a7d4d64b61ec393d56)
- ✨ feat: `StickerMetadata.cornerRadius` #2287 [`42eb122`](https://github.com/open-wa/wa-automate-nodejs/commit/42eb122c74f30d81728490fde814e665bce1211f)
- updated types-only package [`0def80e`](https://github.com/open-wa/wa-automate-nodejs/commit/0def80e29db49e5475f9e929ed4aea4c2460cb20)

**Comment by smashah** [comment]
https://docs.openwa.dev/modules/api_model_media.html#StickerMetadata

You can now set corner radius after setting `circle: true` in sticker metadata:

```js
{
	"circle": true,
	"cornerRadius": 50 //50% of the maximum corner radius possible
}
```


thanks

**Comment by swatky** [comment]
Thanks Very much.
