### ISSUE TITLE
onMessageDeleted not returning the deleted message id and chat id

### ISSUE THREAD

**Issue by syafiqfaiz** [open-wa/wa-automate-nodejs#2289]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

when deleting a message, the `onMessageDeleted` is not returning the deleted message id, its returning a new id.
```
	_whatsapp.onMessageDeleted((message) => {
		//message here is returning a new unknown id
               //while we are at it, can you include the chat id in the response?
	});
```

### Expected Behavior

id is expected to be the deleted message id, so we can find it in the DB and delete it from the db
```
{
  id: 'true_601325062xx@c.us_3EB06B5954E822967757',
  body: 'nak delete',
  type: 'chat',
  t: 1636676586,
  from: '601491598xx@c.us',
  to: '601325062xx@c.us',
  self: 'out',
  ack: 3,
  isNewMsg: true,
  ephemeralStartTimestamp: 1636676587
}
```

### Steps To Reproduce

1. send message
2. delete messsage
3. listen to `onDeleteMessage` event

### Mode

My own code

### create() code

```markdown
listen to event

	_whatsapp.onMessageDeleted((message) => {
		_socket.emit('onMessageDeleted', { message });
	});
```
```


### DEBUG INFO

```markdown
Debug Info {
  WA_VERSION: '2.2144.8',
  PAGE_UA: 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36,
  WA_AUTOMATE_VERSION: '4.23.9',
  BROWSER_VERSION: 'HeadlessChrome/93.0.4577.0'
}
```

### Environment

```markdown
- OS: ubuntu
- Node: 14.15.5
- npm: 7.9.0
```

### Screenshots

![Screenshot 2021-11-12 083348](https://user-images.githubusercontent.com/8923682/141388486-e72e1715-0d95-4ec3-9d2b-a9f36cb48146.png)

**Comment by smashah** [comment]
patched
