### ISSUE TITLE
sendMp4AsSticker Circle: true is not working

### ISSUE THREAD

**Issue by aymenitc** [open-wa/wa-automate-nodejs#2294]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Current Behavior

When setting Circle: true of sendMp4AsSticker method I get error:
``` Request has timed out. Your file may have been too large or the server may be too busy. Try again in a few seconds. ```
It was working before and I haven't change anything in the code.
Another user has reported this too.

### Expected Behavior

When it was working I get circled animated sticker.

### Steps To Reproduce

call :
```
var mediaData = await decryptMedia(message, uaOverride)
                    await client.sendMp4AsSticker(from, mediaData, {fps: 10, startTime: `00:00:00.0`, endTime : `00:00:07.0`,loop: 0, crop: false}, { author: pushname, pack: 'AymenBot 🤖', circle: true }) 
```

### Mode

My own code

### create() code

```markdown
no change in Create
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2144.10",
  "WA_AUTOMATE_VERSION": "4.23.9",
  "BROWSER_VERSION": "HeadlessChrome/95.0.4638.69",
  "START_TS": 1636910719493
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 14.18.1
- npm:
```

**Comment by smashah** [comment]
@aymenitc after quite a long investigation I've found out that the reason this was happen was because the circle command was going on forever because it did not know which frame to stop at. I've hardcoded a max frames # and added a probe to figure out how many frames should be processed. This should be fixed.

Thanks
