### ISSUE TITLE
how to make echo bot ?

### ISSUE THREAD

**Issue by setyo719** [open-wa/wa-automate-nodejs#2301]
I want to make an echo bot like this
bot command: !write
user input: !write hello i'm duck
bot reply: hello duck

how to make something like that?

**Comment by AffanTheBest** [comment]
```js
client.onMessage(async msg => {
       if(msg.body.startsWith('!write ')){
             // Do what ever you want.
             // Use client.sendText() to send text message
       }
})
```

**Comment by smashah** [comment]
thanks @siddiquiaffan 

There are many ways to skin this cat. Please discuss further in the discord (click the discord badge in the readme for an invite).
