### ISSUE TITLE
Forwarded media failed to be sent via web interface

### ISSUE THREAD

**Issue by roigreenberg** [open-wa/wa-automate-nodejs#2302]
Hi.
I have a weird issue, I hope someone here will be able to help me.

Starting a few days ago, the web interface(using selenium-firefox) fail to forward media(except for images) 90% of the time.

There is no code error, and nothing in the console, the forwarded message appears like this:
![image](https://user-images.githubusercontent.com/24591493/142046309-e96b4088-9e6b-48b7-8c4d-76c1d324ff2e.png)

Any idea what can be the issue?

It happened for several numbers in several servers.

**Comment by smashah** [comment]
Odd issue, if this is in relation to open-wa then please fill out the issue template so I can recreate it here.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.yaml&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by roigreenberg** [comment]
I'm not sure what is it related to.
I have the same issue when I forward a media from one group to another using the web interface

**Comment by roigreenberg** [comment]
@smashah I will appreciate it if you can reopen it, at least for a few days, maybe someone will know the solution.
I have no lead so far..

**Comment by smashah** [comment]
@roigreenberg If you can provide a screencast of the issue end to end then I will reopen it because as it stands, the issue is not related to the library and it's missing context for reproduction.

**Comment by roigreenberg** [comment]
There is nothing I can show more than the picture I already showed.

The code I'm using is based on several libraries, including this one (I patched it over time with fixes I found) but since it happens also when I'm not using any code, I don't know what to provide.

The peoples here are probably the most experience and I don't no where else can I ask about it..

**Comment by smashah** [comment]
@roigreenberg sometimes errors also are introduced by zuck and the gang at meta which they usually fix by the end of the following week. If you want to talk about general whatsapp bugs then I suggest discussing with the fine people over at WABETAInfo in their discord. They will most likely be already tracking such an issue.

**Comment by roigreenberg** [comment]
It is already more than a week, and happens for 4 different phones using the same code but in separate servers..

But I will try to ask there, thanks!
