### ISSUE TITLE
Generated code missing response_type

### ISSUE THREAD

**Issue by mrodal** [open-wa/wa-automate-nodejs#2303]
Using the generated clients for python, all endpoints are defined with response_type None:
![image](https://user-images.githubusercontent.com/20667544/142082175-3424b701-b128-4a87-8f80-5d6063743efb.png)

This makes the api client return nothing even though the api call actually returned correctly.

To fix this the right way, there should be a schema defined for each response
[Generator code](https://github.com/OpenAPITools/openapi-generator/blob/9479d350817a36b7c0b21497f0c24e615ba717b8/modules/openapi-generator/src/main/resources/python/api.mustache#L36)

**Workaround:**
Setting response_type to `[dict]` works, so a workarount is wapping the call_api function hardcoding this response type:
```python
call_api_old = client.api_client.call_api
def call_api(*args, **kwargs):
    return call_api_old(*args, **{**kwargs, "response_type":[dict]})
client.api_client.call_api=call_api
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.23.14](https://github.com/open-wa/wa-automate-nodejs/compare/4.23.13...4.23.14) (2021-11-17)

- 🎨 CLI: added types as schemas to swagger  #2303 [`18377f8`](https://github.com/open-wa/wa-automate-nodejs/commit/18377f82af1640f88385f90ca8120615cae7d5e7)
- Release 4.23.14 [`c4bf418`](https://github.com/open-wa/wa-automate-nodejs/commit/c4bf41817d846281f250d9dd9575e8a25e500403)
- updated types-only package [`2cb6453`](https://github.com/open-wa/wa-automate-nodejs/commit/2cb6453ae1b5ef3a5b5a46d413e12b9dd608e889)

**Comment by smashah** [comment]
@mrodal If that doesn't fix it then it's an issue with open-api generator not correctly inferring the returnType

**Comment by mrodal** [comment]
@smashah sadly its still working as before 😕

On swagger im getting this:

![image](https://user-images.githubusercontent.com/20667544/142189183-522e8ddf-2d32-406e-b184-8ad3e6d5decf.png)

**Comment by smashah** [comment]
This is fixed
