### ISSUE TITLE
Error in all operations with group on Multi-device

### ISSUE THREAD

**Issue by smatosjr** [open-wa/wa-automate-nodejs#2307]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

- [X] I am using a multi-device session and I have set multiDevice to true in my config OR am using the --multi-device flag

### Current Behavior

Using multi-device I can't list group participants and add participants to a group.

### Mode

My own code

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

**Comment by smashah** [comment]
Hi this should be patched. Please try again and report back if it is working for you

duplicate #2309
