### ISSUE TITLE
Improve documentation for `Chat`

### ISSUE THREAD

**Issue by SSchaaf** [open-wa/wa-automate-nodejs#2308]
Hello all,

Only a doubt.
What is the meaning of t field in Chat interface ?

[](https://docs.openwa.dev/interfaces/api_model_chat.Chat.html#t)

**Comment by SSchaaf** [comment]
I did some tests here.
It seems that t changes whhen some kind of interaction between the two phones is made.
For example. If a message is sent, t changes. Even if the whatsapp host numeber is disconnected.

**Comment by smashah** [comment]
https://docs.openwa.dev/interfaces/api_model_chat.Chat.html
