### ISSUE TITLE
Error when trying to run any manage participants methods on easy api

### ISSUE THREAD

**Issue by paulorealdev** [open-wa/wa-automate-nodejs#2309]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

- [X] I am using a multi-device session and I have set multiDevice to true in my config OR am using the --multi-device flag

### Current Behavior

When I try to run any of the [manage participants method](https://docs.openwa.dev/pages/How%20to/groups/manage-participants.html#manage-participants), I receive this error on terminal:

```
• Listening on port 8089!
middleware -> error Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'removeParticipants')
    at window.<computed> (__puppeteer_evaluation_script__:1:254251)
    at Object.window.<computed>.<computed> [as promoteParticipant] (__puppeteer_evaluation_script__:1:261045)
    at __puppeteer_evaluation_script__:1:39
    at ExecutionContext._evaluateInternal (/root/.npm/_npx/4fbd8c81366b4add/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/root/.npm/_npx/4fbd8c81366b4add/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
```

I've tested it with version 4.23.10 and it works, above that version it crashes.

I tried with and without multi-device flag.

### Expected Behavior

Get the success response

### Steps To Reproduce

npx @open-wa/wa-automate@latest -a -p 8080

```
curl --request POST 'http://localhost:8080/promoteParticipant' \
--header 'Content-Type: application/json' \
--data-raw '{
    "args": {
        "groupId": "00000000000000000@g.us",
        "participantId": "0000000000000@c.us"
    }
}'
```

### Mode

EASY API/CLI

### create() code

```markdown
/promoteParticipant
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2144.11",
  "WA_AUTOMATE_VERSION": "4.23.14",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
  "START_TS": 1637257392554
}
```

### Environment

```markdown
- OS: Ubuntu 21.04
- Node: 16.13.0
- npm: 8.1.0
```

### Screenshots

![image](https://user-images.githubusercontent.com/5343191/142471149-74003c07-7660-41bc-8e93-d7775628c137.png)

### Anything else?

https://docs.openwa.dev/pages/How%20to/groups/manage-participants.html#manage-participants

**Comment by smashah** [comment]
Hi this should be patched. Please try again and report back if it is working for you

**Comment by paulorealdev** [comment]
Hi.. its working now.
Thanks a lot =)
