### ISSUE TITLE
Login didn't worked even after QR Scanned

### ISSUE THREAD

**Issue by siddiquiaffan** [open-wa/wa-automate-nodejs#2323]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

- [X] I am using a multi-device session and I have set multiDevice to true in my config OR am using the --multi-device flag

### Current Behavior

I'm using `multiDevice: true` in my configs. When I started my app, I got QR Code, scanned it successfully, but it's not logged in.

When I used `headless: false` what I saw is, after scanning QR Code it got logged in successfully but in console it was still showing QR and after sometime it said `✖ QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout`

### Expected Behavior

It should log in successfully and return session data.

### Steps To Reproduce

set `multiDevice` to `true` and run run `wa.create()`

### Mode

My own code

### create() code

```markdown
const client = await wa.create({useChrome: true, headless: false, authTimeout: 0, multiDevice: true, chromiumArgs: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu']});
```

### DEBUG INFO

```markdown
WA_VERSION :'2.2146.9'  
PAGE_UA : 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
WA_AUTOMATE_VERSION : '4.23.17 UPDATE AVAILABLE: 4.24.2'
BROWSER_VERSION : 'Chrome/96.0.4664.45'
OS : 'Windows 10' 
START_TS : 1637837828076
```

### Environment

```markdown
- OS: Windows 11
- Node: 14
- npm: 7
```

### Anything else?

`qrTimeout: 0` didn't help out. It shows QR code indefinetly

**Comment by smashah** [comment]
Update your library version and try again

**Comment by siddiquiaffan** [comment]
Thanks it worked, but now I'm unable to extract session data to reuse it later

**Comment by smashah** [comment]
@siddiquiaffan MD sessions do not rely solely on `session.data.json` therefore MD sessions are NOT PORTABLE.

MD requires a "data directory" that the chrome instance needs to reauthenticate a session. It's a fundamental change but I am working hard to try to implement the sesison.data.json method of reauthentication for MD.
