### ISSUE TITLE
install @open-wa/wa-automate@1.8.79, which is a breaking change

### ISSUE THREAD

**Issue by setyo719** [open-wa/wa-automate-nodejs#2325]
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix --force`
Will install @open-wa/wa-automate@1.8.79, which is a breaking change
node_modules/spinnies/node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/spinnies/node_modules/strip-ansi
    spinnies  >=0.4.0
    Depends on vulnerable versions of strip-ansi
    node_modules/spinnies
      @open-wa/wa-automate  >=1.8.80
      Depends on vulnerable versions of postman-2-swagger
      Depends on vulnerable versions of spinnies
      Depends on vulnerable versions of swagger-stats
      Depends on vulnerable versions of typeconv
      node_modules/@open-wa/wa-automate

please help me, i want to update my bot

**Comment by smashah** [comment]
1. Delete the "open-wa/wa-automate" line in your package.json
2. Delete package.lock.json
3. `npm i --save @open-wa/wa-automate@latest`

**Comment by setyo719** [comment]
> 

thank you sir

**Comment by gibsmon** [comment]
> 1. Delete the "open-wa/wa-automate" line in your package.json
> 2. Delete package.lock.json
> 3. `npm i --save @open-wa/wa-automate@latest`

or use this npm config set registry http://registry.npmjs.org/
