### ISSUE TITLE
Unable to send messages  

### ISSUE THREAD

**Issue by siddiquiaffan** [open-wa/wa-automate-nodejs#2331]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

- [X] I am using a multi-device session and I have set multiDevice to true in my config OR am using the --multi-device flag

### Current Behavior

When trying to send text messages using `client.sendText` it's giving an error.

The error is:

`(node:19) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: _0x3ff5fd[(_0x4d33a6(...) + _0x4d33a6(...) + "es")] is not a function
    at Object.window.<computed>.<computed> [as sendMessage] (__puppeteer_evaluation_script__:1:266281)
    at __puppeteer_evaluation_script__:3:29
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: _0x3ff5fd[(_0x4d33a6(...) + _0x4d33a6(...) + "es")] is not a function
    at Object.window.<computed>.<computed> [as sendMessage] (__puppeteer_evaluation_script__:1:266281)
    at __puppeteer_evaluation_script__:3:29
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)`

### Expected Behavior

It should send a text message successfully.

### Steps To Reproduce

Set `multiDevice` to `true`. Run code and try to send messages using `client.sendText`

### Mode

My own code

### create() code

```markdown
const client = await wa.create({useChrome: true, headless: true, multiDevice: true, authTimeout: 0})
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2146.9",
  "WA_AUTOMATE_VERSION": "4.24.2",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.63",
  "START_TS": 1638337375976
}
```

### Environment

```markdown
- OS: Linux 4.9
- Node: 14.16.0
- npm: 7
```

**Comment by smashah** [comment]
@siddiquiaffan I have just tested this in MD with wa_version `2.2146.9` and it seems to be working fine. I tested with an existing chat (not group chat) in my account (tested with and without a license).

Is there something significant about the chat you're trying to send a message to which would result in the sendMessage property being undefined?

**Comment by smashah** [comment]
I just tested with a group chat also. looks like it's working ok here on `2.2146.9`

Due to the timing (wednesday) this does ring the alarm but I'm not able to replicate unfortunately. Please add more context to this issue, including your config
