### ISSUE TITLE
Authentication sometimes timed out

### ISSUE THREAD

**Issue by MoonLGH** [open-wa/wa-automate-nodejs#2334]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

- [X] I am using a multi-device session and I have set multiDevice to true in my config OR am using the --multi-device flag

### Current Behavior

✖ Authentication timed out. Shutting down. Consider increasing authTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#authtimeout
/home/azureuser/TsukariWa/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:262
                throw new Error(outOfReach ? 'App Offline' : 'Auth Timeout. Consider increasing authTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#authtimeout');
  

### Expected Behavior

Because im not even logged in yet, Authentication supposed to generate a qr 

### Steps To Reproduce

1. clone https://github.com/MoonLGH/TsukariWa
2. npm i
3. npm i -g "ts-node" (if needed)
3. ts-node src/index.ts

### Mode

My own code

### create() code

```markdown
https://github.com/MoonLGH/TsukariWa/blob/main/src/index.ts

create({
    authTimeout:60,
    logConsole: false,
    multiDevice: settings.MultipleDevice,
    cachedPatch: true,
}).then(client => start(client));

function start(client: Client) {
    Handler.LoadComamnds()
    client.onAnyMessage(async (message: Message) => {
        Handler.Handle(message,client);
    });
}
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2146.9",
  "WA_AUTOMATE_VERSION": "4.25.0",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
  "START_TS": 1638548117206
}
```

### Environment

```markdown
- OS: Linux 3.10
- Node: 16.11.1
- npm: https://github.com/MoonLGH/TsukariWa/blob/main/package.json
```

### Anything else?

This authentication timeout is so frequently appear, so that i just put `authTimeout` to 0
Well i can't say it works

**Comment by MoonLGH** [comment]
i havent even authenticating my wa yet, so Wa device fault is almost impossible

**Comment by MoonLGH** [comment]
addition, sometime even when authenticate is success, client still takes a long time to load accounts(like " Client loaded for normal account [MD]... ")

**Comment by MoonLGH** [comment]
> addition, sometime even when authenticate is success, client still takes a long time to load accounts(like " Client loaded for normal account [MD]... ")

my vps connection is stable though
 Download:  1773.20 Mbps (data used: 2.2 GB )
     Upload:   773.82 Mbps (data used: 1.3 GB )
Packet Loss: Not available.
 Result URL: https://www.speedtest.net/result/c/304647f3-0e5d-4ce5-822a-806222952a6b

**Comment by smashah** [comment]
@MoonLGH can you share the launch logs of a successful login please. Also, the only solution to this auth timeout is to set `authTimeout` accordingly (maybe 200?)

**Comment by MoonLGH** [comment]
> @MoonLGH can you share the launch logs of a successful login please. Also, one quick solution to this auth timeout is to set `authTimeout` accordingly (maybe 200?)

sure, 1 second

**Comment by MoonLGH** [comment]
oh wait.. i had my logConsole to false...
only this what i could find

```
{"level":30,"time":1638549510078,"pid":6969,"hostname":"MoonLVM","STAGE":"LAUNCH","sessionInfo":{"WA_VERSION":"2.2146.9","PAGE_UA":"WhatsApp/2.2144.11 Mozilla/5.0 (Macintosh; Intel Mac OS $
{"level":30,"time":1638549510079,"pid":6969,"hostname":"MoonLVM"}
```

**Comment by smashah** [comment]
@MoonLGH I mean everything from here (launch logs)

`
✖ Authentication timed out. Shutting down. Consider increasing authTimeout config variable: open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#authtimeout
/home/azureuser/TsukariWa/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:262
throw new Error(outOfReach ? 'App Offline' : 'Auth Timeout. Consider increasing authTimeout config variable: open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#authtimeout');
`

**Comment by MoonLGH** [comment]
> @MoonLGH I mean everything from here (launch logs)
> 
> `✖ Authentication timed out. Shutting down. Consider increasing authTimeout config variable: open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#authtimeout /home/azureuser/TsukariWa/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:262 throw new Error(outOfReach ? 'App Offline' : 'Auth Timeout. Consider increasing authTimeout config variable: open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#authtimeout');`

I cant cause i just delete that vps...
maybe this sounds wierd, but i just change my vps to a bit better one, and works like a charm,

for now i will close this issues, but maybe if it comes again im gonna mention this issues in future issues, thanks
