### ISSUE TITLE
Bot reacting with message that it left with

### ISSUE THREAD

**Issue by MoonLGH** [open-wa/wa-automate-nodejs#2336]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

- [X] I am using a multi-device session and I have set multiDevice to true in my config OR am using the --multi-device flag

### Current Behavior

Bot interact to message that sended when bot didn’t even online

### Expected Behavior

Bot only interact with message that sended after bot online

### Steps To Reproduce

1. Clone github.com/MoonLGH/TsukariWa
2. npm i
3. Use md
4. Try typing "Test1" before turning on the bot
5. Ts-node src/index.ts

### Mode

My own code

### create() code

```markdown
https://github.com/MoonLGH/TsukariWa
Src => index.ts for more detail
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2146.9",
  "WA_AUTOMATE_VERSION": "4.25.0",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
  "START_TS": 1638548117206
}
```

### Environment

```markdown
- OS: Linux 3.10
- Node: 16.11.1
- npm: https://github.com/MoonLGH/TsukariWa/blob/main/package.json
```

### Anything else?

This error only occur after the onAnyMessage Bug

**Comment by smashah** [comment]
@MoonLGH can you try now please

**Comment by MoonLGH** [comment]
Yep it works
Thanksss
