### ISSUE TITLE
Portable MD

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#2338]

**Comment by smashah** [comment]
bump

**Comment by christiancuri** [comment]
Currently, how to save MD session data? Every time i start the wa-automate, i need scan qr code again to sync my wpp with client

**Comment by willmaraujo** [comment]
> App keep crashing at startup open-wa/wa-automate-deploy-heroku#125

Hi Christian, have you managed to use MD session in order to persist the session?

**Comment by SenpaiCookies** [comment]
> Currently, how to save MD session data? Every time i start the wa-automate, i need scan qr code again to sync my wpp with client

I'm also having the same error :(((

**Comment by smashah** [comment]
What is wpp?

**Comment by SenpaiCookies** [comment]
> What is wpp?

whatsapp

**Comment by t0g3pii** [comment]
#bump for close

**Comment by smashah** [comment]
Closing. Track https://github.com/open-wa/wa-automate-nodejs/issues/2866
