### ISSUE TITLE
Stuck Finalizing Client

### ISSUE THREAD

**Issue by iqbaldwiansyah** [open-wa/wa-automate-nodejs#2341]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

- [X] I am using a multi-device session and I have set multiDevice to true in my config OR am using the --multi-device flag

### Mode

EASY API/CLI

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

### Screenshots

https://imgur.com/a/ZuYkHPr

**Comment by DwiRizqiH** [comment]
For those who experience Stuck Finalizing Client, but can't find a solution.

Try Reinstalling the WhatsApp application, or Change from MD Mode (Multi Device) to Normal Mode, or change from Normal Mode to MD Mode (Multi Device)

It works for me

**Comment by smashah** [comment]
> For those who experience Stuck Finalizing Client, but can't find a solution.
> 
> Try Reinstalling the WhatsApp application, or Change from MD Mode (Multi Device) to Normal Mode, or change from Normal Mode to MD Mode (Multi Device)
> 
> It works for me

If you want to use MD then set `mutliDevice: true` in your config or add the --multi-device flag if using the CLI
