### ISSUE TITLE
sendReply and sendButtons don’t always work unless I send a normal message.

### ISSUE THREAD

**Issue by Sp0derDev** [open-wa/wa-automate-nodejs#2345]

**Comment by TheBooker66** [comment]
This also occurs for me.

**Comment by cantiir2** [comment]
how to respond to a button?

**Comment by TheBooker66** [comment]
> how to respond to a button?

Do you know what WhatsApp buttons are?

**Comment by cantiir2** [comment]
I already know that here's an example https://github.com/open-wa/wa-automate-nodejs/issues/2342#issue-1073925816
But to respond to the message button does not work

**Comment by cantiir2** [comment]
> > how to respond to a button?
> 
> Do you know what WhatsApp buttons are?
I already know that here's an example https://github.com/open-wa/wa-automate-nodejs/issues/2342#issue-1073925816
But to respond to the message button does not work

**Comment by cantiir2** [comment]
> > how to respond to a button?
> 
> Do you know what WhatsApp buttons are?

I already know that here's an example https://github.com/open-wa/wa-automate-nodejs/issues/2342#issue-1073925816
But to respond to the message button does not work

**Comment by smashah** [comment]
@cantiir2 @Sp0derDev @TheBooker66 can you try `reply` now. It should work without sending a normal message

**Comment by smashah** [comment]
Buttons should no longer need a pre-existing message to work

thanks
