### ISSUE TITLE
QR-Code not generating

### ISSUE THREAD

**Issue by almottier** [open-wa/wa-automate-nodejs#2346]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

- [X] I am using a multi-device session and I have set multiDevice to true in my config OR am using the --multi-device flag

### Current Behavior

```
wa.create({
    sessionId: "JULIETTE_TRACKER",
    multiDevice: true, //required to enable multiDevice support
    authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
    blockCrashLogs: true,
    disableSpins: true,
    headless: true,
    hostNotificationLang: 'fr-fr',
    logConsole: false,
    popup: true,
    useChrome: true,
    qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
  }).then(client => start(client));

  function start(client) {
    client.getAllGroups().then(groups => {
      console.log(groups);
    });
  }
```

```
$  node app.js                             
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                   ┃
┃   @open-wa/wa-automate                                                                            ┃
┃    💬 🤖 The most reliable NodeJS whatsapp library for chatbots with advanced features.           ┃
┃   Version: 4.25.1                                                                                 ┃
┃   Check out the latest changes: https://github.com/open-wa/wa-automate-nodejs#latest-changes      ┃
┃                                                                                                   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
You can also authenticate the session at: http://localhost:7000
- Starting
- Version: 4.25.1
- Initializing WA
- Launching Browser
- Setting Up Page
- Loading session data
- No session data file found for session : JULIETTE_TRACKER
- No session data detected. Opting in for MD.
- Make sure to keep the session alive for at least 5 minutes after scanning the QR code before trying to restart a session!!
- Navigating to WA
- Page loaded but something may have gone wrong: 37ms
- Browser Launched
- Please delete the ./_IGNORE_JULIETTE_TRACKER folder and any related data.json files and try again. It is highly suggested to set useChrome: true also.
/Users/alex/dev/marinetraffic/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:513
            const timeoutError = new Errors_js_1.TimeoutError(`waiting for ${options.title} failed: timeout ${options.timeout}ms exceeded`);
                                 ^

TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask (/Users/alex/dev/marinetraffic/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:513:34)
    at DOMWorld.waitForFunction (/Users/alex/dev/marinetraffic/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:468:26)
    at Frame.waitForFunction (/Users/alex/dev/marinetraffic/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:909:32)
    at Page.waitForFunction (/Users/alex/dev/marinetraffic/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2433:33)
    at Object.<anonymous> (/Users/alex/dev/marinetraffic/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:194:26)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/alex/dev/marinetraffic/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.0.1
```

### Mode

My own code

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2147.14",
  "WA_AUTOMATE_VERSION": "4.25.1",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
  "START_TS": 1639051005722
}
```

### Environment

```markdown
- OS: macOS Monterey
- Node: 17.0.1
- npm:
```

### Screenshots

<img width="1187" alt="Screenshot 2021-12-09 at 13 07 45" src="https://user-images.githubusercontent.com/5426740/145394033-d11fe4b7-1ef6-41ae-b2a1-f5d12ab318af.png">

**Comment by See-Now** [comment]
I also receive this warning today, sometimes during startup (before logging in) and always after restart, as if it is no longer logged in.

**Comment by smashah** [comment]
@almottier please use `headless: false` and screen record the web session then share it here

**Comment by smashah** [comment]
Delete `./_IGNORE_JULIETTE_TRACKER ` and try again

**Comment by almottier** [comment]
I tried `rm -rf ./_IGNORE_JULIETTE_TRACKER` but it doesn't fix it.

with `headless: false` : 

<img width="1191" alt="Screenshot 2021-12-10 at 02 12 59" src="https://user-images.githubusercontent.com/5426740/145500608-d74e9e61-0054-434e-b326-d80eac2beccb.png">

**Comment by smashah** [comment]
yeah it looks like you're getting tos blocked.

Update your chrome: I am testing with `HeadlessChrome/96.0.4664.93` and change your sessoin ID from `JULIETTE_TRACKER` to something else.

**Comment by almottier** [comment]
Hello, my Chrome is already the latest version. I am running the ARM64 build on an Apple M1 with Monterey.

![image](https://user-images.githubusercontent.com/5426740/145570537-372dc9b0-e3e8-457f-9bf3-23173e825499.png)

**Comment by smashah** [comment]
@almottier I'm also on M1 (Pro). Hard to pinpoint the issue here. Can you try this

```
> npx @open-wa/wa-automate --use-chrome --disable-spins --debug --headful
```

**Comment by powermx** [comment]
> @almottier I'm also on M1 (Pro). Hard to pinpoint the issue here. Can you try this
> 
> ```
> > npx @open-wa/wa-automate --use-chrome --disable-spins --debug --headful --multi-device
> ```
> 
> and then respond with the logs




This is Mine, after update : 
---------------------------------------------
/root/Bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:175
                throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                      ^

Error: Evaluation failed: ReferenceError: getQrPng is not defined
    at __puppeteer_evaluation_script__:1:1
    at ExecutionContext._evaluateInternal (/root/Bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:175:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/root/Bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)

**Comment by smashah** [comment]
> 

please show all of your logs not just the error

**Comment by smashah** [comment]
#2355

**Comment by smashah** [comment]
@almottier can you try with the latest version please

**Comment by almottier** [comment]
@smashah it is working now, thanks. You may close this issue.
