### ISSUE TITLE
Multidevice fails to reload 

### ISSUE THREAD

**Issue by NSOPORTEDESARROLLO** [open-wa/wa-automate-nodejs#2355]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

- [X] I am using a multi-device session and I have set multiDevice to true in my config OR am using the --multi-device flag

### Current Behavior

After scan QR code and wait arround 10 minutes, everything works fine but when I restart the session it fails.

### Steps To Reproduce

1- Scan QR with multi-device flag
2 - Wait 10 min
3- Stop process 
4 - Start Again 

### Mode

EASY API/CLI

### DEBUG INFO

```markdown
You can also authenticate the session at: http://localhost:8080
- Starting
- Version: 4.26.1
- Initializing WA
- Launching Browser
- Setting Up Page
- Loading session data
- Found session data file: /usr/src/wa/session.data.json
- multi-device enabled. Session data skipped...
- Existing session data injected
- Navigating to WA
- Page loaded but something may have gone wrong: 290ms
- Browser Launched
- Please delete the ./_IGNORE_session folder and any related data.json files and try again. It is highly suggested to set useChrome: true also.
- session_STARTUP
- Error waiting for function failed: timeout 30000ms exceeded TimeoutError: waiting for function failed: timeout 30000ms exceeded
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: v16.13.1
- npm: 8.1.2
```

**Comment by smashah** [comment]
Please share the whole npx command you are using

**Comment by smashah** [comment]
To-do:

- [ ] Snapshot page load failures

**Comment by smashah** [comment]
@NSOPORTEDESARROLLO please use `--headful` and take a screenshot when it logs 

`Page loaded but something may have gone wrong`

**Comment by smashah** [comment]
@NSOPORTEDESARROLLO does the browser show this?

https://github.com/open-wa/wa-automate-nodejs/issues/2346#issuecomment-990480318

**Comment by NSOPORTEDESARROLLO** [comment]
Hi Smashah, thanks for answer,

My npx: 
node ./node_modules/@open-wa/wa-automate/bin/server.js --use-chrome   --port 8080 --headful --multi-device -w https://testchat.316cloud.com/index.php/webhooks/incoming/wa40002853

Log with --headful flag 
![Captura de pantalla de 2021-12-16 11-09-48](https://user-images.githubusercontent.com/47125165/146417185-c5144543-5189-4bd8-b810-4766cd019c55.png)

**Comment by smashah** [comment]
@NSOPORTEDESARROLLO i meant a screenshot of the browser, and these new logs are a completely seperate issue entirely. lets try to solve the original issue first.

**Comment by NSOPORTEDESARROLLO** [comment]
@smashah I did not work a GUI environment, just ubuntu CLI, I tested on Ubuntu desktop and it opens the browser and works. Do I need run a GUI environment for run MD support ?
<img width="987" alt="Captura de Pantalla 2021-12-19 a la(s) 10 19 02 p  m" src="https://user-images.githubusercontent.com/47125165/146711555-38d9eaab-8bc9-49ab-a7fd-38c1bbbe68f7.png">

**Comment by smashah** [comment]
> @smashah I did not work a GUI environment, just ubuntu CLI, I tested on Ubuntu desktop and it opens the browser and works. Do I need run a GUI environment for run MD support ? <img alt="Captura de Pantalla 2021-12-19 a la(s) 10 19 02 p  m" width="987" src="https://user-images.githubusercontent.com/47125165/146711555-38d9eaab-8bc9-49ab-a7fd-38c1bbbe68f7.png">

Well, I am not experiencing this issue in my ubuntu server environment so I don't know what else to say. Make sure there are no `_IGNORE...` folders in your working directory before you try again

**Comment by NSOPORTEDESARROLLO** [comment]
Yes, after delete _IGNORE.. folders it works again but just once, I can scan the QR code and it loads fine, after 6 minutes y relaunch and got the error. I’ m Going to reinstall all again

**Comment by NSOPORTEDESARROLLO** [comment]
I resinstalled everything and all is working fine now, @smashah thanks so much
