### ISSUE TITLE
Add port parameter in config file

### ISSUE THREAD

**Issue by chgss** [open-wa/wa-automate-nodejs#2357]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

- [X] I am using a multi-device session and I have set multiDevice to true in my config OR am using the --multi-device flag

### Current Behavior

With json config file port parameter is deleted and instance take default port 8002.

### Expected Behavior

Add parameter again in json config file

### Steps To Reproduce

Any enviroment

### Mode

EASY API/CLI

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2147.16",
  "WA_AUTOMATE_VERSION": "4.27.0",
  "BROWSER_VERSION": "HeadlessChrome/95.0.4638.69",
  "START_TS": 1639685471461
}
```

### Environment

```markdown
- OS: Linux 4.18
- Node: 14.17.3
- npm: xxx
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.27.1](https://github.com/open-wa/wa-automate-nodejs/compare/4.27.0...4.27.1) (2021-12-17)

- Release 4.27.1 [`5fb1041`](https://github.com/open-wa/wa-automate-nodejs/commit/5fb1041c0b0457f66c94442c20ff425e310c3fd9)
- ⬆️ update pptr deps #2356 @pe77 [`b2bfc2c`](https://github.com/open-wa/wa-automate-nodejs/commit/b2bfc2cb80b52c3239744ddb3a0291c6f8d39676)
- 🐛 fix CLI defaults overriding env vars & config.json #2357 [`422c44e`](https://github.com/open-wa/wa-automate-nodejs/commit/422c44ebeacd093ed447d76fe983b8b402ed3bb1)
- 🔧 update gitignore install script [`b8ee6ce`](https://github.com/open-wa/wa-automate-nodejs/commit/b8ee6ce5e3b63d5c18857e446c4896a97ae7453e)
- updated types-only package [`b5e1f7b`](https://github.com/open-wa/wa-automate-nodejs/commit/b5e1f7ba354e2ed343a0c272cd875d7108320fa2)
