### ISSUE TITLE
How to fix save session code for Multi Device ?

### ISSUE THREAD

**Issue by Mr4sR** [open-wa/wa-automate-nodejs#2393]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

- [X] I am using a multi-device session and I have set multiDevice to true in my config OR am using the --multi-device flag

### Current Behavior

When I try to scan the QR with a whatsapp account that is not MD/MultiDevice
the session code appears and is stored properly in file.data.json,
But when I use a whatsapp account whose MD/MultiDevice the session code is stored is weird like this: `e30=`

### Expected Behavior

The system saving session code is not working properly

### Mode

My own code

### Environment

```markdown
- OS: Windows 8
- Node: 14.17.3
- npm: 6.14.13
```

**Comment by smashah** [comment]
@Mr4sR Please fill the issue template correctly with the config/launch logs etc.
