### ISSUE TITLE
feat [MD]: URL & Call buttons

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#2394]
It's time

- [x] Simple text [no header/footer]
- [x] Start conversation with buttons [at your own risk] [lic]
- [x] Media Buttons [insiders]
- [x] Location buttons [insiders]
- [x] URL & Call Buttons [insiders]
- X Make generic buttons GA for MD

#98

**Comment by smashah** [comment]
URL, Call + standard button example

```
await client.B(chatId, {
    "templateMessage": {
        "hydratedTemplate": {
            "hydratedButtons": [
                {
                    "index": 1,
                    "urlButton": {
                        "displayText": "I am a link",
                        "url": "https://github.com/open-wa/wa-automate-nodejs"
                    }
                },
                {
                    "index": 2,
                    "callButton": {
                        "displayText": "Call me now!",
                        "phoneNumber": "+1234567890"
                    }
                },
                {
                    "index": 3,
                    "quickReplyButton": {
                        "displayText": "Or just click me",
                        "id": "button-1"
                    }
                }
            ],
            "hydratedContentText": "content",
            "hydratedFooterText": "footerer"
        }
    }
});
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.35.5](https://github.com/open-wa/wa-automate-nodejs/compare/4.35.4...4.35.5) (2022-04-14)

- Release 4.35.5 [`2cc114c`](https://github.com/open-wa/wa-automate-nodejs/commit/2cc114cecaf1488f6214aa82d5e23dd667603a2c)
- 🏷️ type: make title and footer optional in sendButton #2394 [`0a5bd64`](https://github.com/open-wa/wa-automate-nodejs/commit/0a5bd6408f880310a272fe8c7f717fb0280bb170)
- updated types-only package [`f7d15dc`](https://github.com/open-wa/wa-automate-nodejs/commit/f7d15dc32a924df104128e6e0ce5223d120f9413)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.35.6](https://github.com/open-wa/wa-automate-nodejs/compare/4.35.5...4.35.6) (2022-04-14)

- Release 4.35.6 [`f33aaab`](https://github.com/open-wa/wa-automate-nodejs/commit/f33aaabf78cbdedf9948cf95fd7f046b09caf61a)
- ✨ feat: `sendButtons` can now take location #2394 [`3803d20`](https://github.com/open-wa/wa-automate-nodejs/commit/3803d201ab6ee988f98f7d263fb0ade5a8b5d270)
- 🥚 patches update [`2edea48`](https://github.com/open-wa/wa-automate-nodejs/commit/2edea48ca8408e5fc0f1af20ea610b4255013568)
- updated types-only package [`36e5d56`](https://github.com/open-wa/wa-automate-nodejs/commit/36e5d5654596bce06eb272ea89d04316a5779de6)

**Comment by idham** [comment]
can you give us example for easy API request  JSON format?

**Comment by smashah** [comment]
> can you give us example for easy API request JSON format?

https://github.com/open-wa/wa-automate-nodejs/discussions/2669

**Comment by idham** [comment]
> > can you give us example for easy API request JSON format?
> 
> #2669

Thank you so much

**Comment by idham** [comment]
> > can you give us example for easy API request JSON format?
> 
> #2669

why is it returning error, is there and update ?

> {
>     "success": false,
>     "error": {
>         "name": "Error",
>         "message": "Evaluation failed: TypeError: _0x8e9447[_0x3ab137(...)](...) is not a function\n    at eval (eval at <anonymous> (:1:10), <anonymous>:1:86675)\n    at Array.map (<anonymous>)\n    at eval (eval at <anonymous> (:1:10), <anonymous>:1:86557)"
>     }
> }

**Comment by smashah** [comment]
Can't tell why you're getting that error unless you share code and context

**Comment by idham** [comment]
sorry for missing the context
 
a day before I was testing  https://github.com/open-wa/wa-automate-nodejs/issues/2394#issuecomment-1128937794 using Postman for Baileys endpoint .. and it works, in the morning all the payload are returning error 

and then I was trying the sendButtons endpoint using last known works example 
{
  "args": {
    "to": "62811229454@c.us",
    "body": {
        "caption": "Paskal Roadshow Jakarta",
        "lat": -6.2,
        "lng": 106.8
    },
    "buttons": [
        {"id":"1","text":"Registrasi"},
        {"id":"2","text":"FAQ"},
        {"id":"1","text":"Term of Service"}
        ],
    "title": "Welcome Message",
    "footer": "Paskal Indonesia"
  }
}


and give return error as 
{"success":false,"error":{"name":"Error","message":"Evaluation failed: TypeError: _0x21a700[_0x581b93(...)](...) is not a function\n    at eval (eval at <anonymous> (:1:10), <anonymous>:1:107964)\n    at Array.map (<anonymous>)\n    at eval (eval at <anonymous> (:1:10), <anonymous>:1:107849)"}} 

I just used the npx easy API and didn't change anything

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "minor"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.39.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.38.1...4.39.0) (2022-06-12)

- Release 4.39.0 [`d4ec9db`](https://github.com/open-wa/wa-automate-nodejs/commit/d4ec9db82e3e4c23e9da3b50a33396688fb54110)
- ✨ feat: `client.sendAdvancedButtons` #2394 [`3bb536f`](https://github.com/open-wa/wa-automate-nodejs/commit/3bb536fa0512cfc0d014c9b0515ccb5da6864769)
- 🔇 dont log message preproc unless it's actually processing something [`c997e0a`](https://github.com/open-wa/wa-automate-nodejs/commit/c997e0a6ec2c3d236a6ccc222da17e4f5ebfd55a)
- 🥚 patches update [`4715329`](https://github.com/open-wa/wa-automate-nodejs/commit/471532928f944f77a4ed0b6fea4e234bd21ea101)
- 🥚 patches update [`27974ee`](https://github.com/open-wa/wa-automate-nodejs/commit/27974ee22b6a7fdd4ef11d84046cc339f5a18c20)
- 🥚 patches update [`2784c98`](https://github.com/open-wa/wa-automate-nodejs/commit/2784c98adc02357eb7ac1a64153dd62653a9f175)
- 🥚 patches update [`4209285`](https://github.com/open-wa/wa-automate-nodejs/commit/42092858cef51d6339418b3798aef2e17508ed73)
- 🥚 patches update [`ec0c25a`](https://github.com/open-wa/wa-automate-nodejs/commit/ec0c25a9b41a03ef608fbd8b45664f169cfb2663)
- updated types-only package [`50ba3e6`](https://github.com/open-wa/wa-automate-nodejs/commit/50ba3e69242bf2551ae9c8ef8eda6a9de8fad73b)

**Comment by idham** [comment]
thx @smashah for the update, I didn't change anything and it works now

**Comment by dafner** [comment]
I'm new to using this library and I'm testing how button submission works for an application I'm developing.

With the code used for the test it has been impossible for me to send the buttons.

Is there any problem or limitation that prevents the correct operation of sending buttons?

I would appreciate any kind of help to be able to send buttons with the sendButtons function

Thank you


const wa = require('@open-wa/wa-automate');

wa.create({
  sessionId: "COVID_HELPER",
  multiDevice: true, //required to enable multiDevice support
  authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
  blockCrashLogs: true,
  disableSpins: true,
  headless: true,
  hostNotificationLang: 'PT_BR',
  logConsole: true,
  popup: true,
  qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
}).then(client => start(client));

function start(client) {
  client.onMessage(async message => {
    console.log(message);

    if (message.body === 'Hi') {
      await client.sendText(message.from, '👋 Hello!');
    }

    if (message.body === 'Buttons') {
        await client.sendButtons(message.from, "Body", [
            {
                id: "1",
                "text": "Click"
            },
            {
                id: "1",
                "text": "Call"
            },
            {
                id: "1",
                "text": "Open Link"
            }
        ], "title", "footer");
    }
  });
}

**Comment by smashah** [comment]
@dafner buttons on MD requires a license 👍

**Comment by dafner** [comment]
Thanks for your prompt answer!

I have a cuestion, I probed other libraries from github and it's 
imposible to send buttons due a limitation of WA Business MultiDevice

If I purchase a license, you can assure me that I could send buttons and 
List without problems?

Wich kind of licence I must be purchase ? A Restricted License Key or 
insiders Programs?

I must purchase one licence for every number that I used in my development?

Thanks

**Comment by smashah** [comment]
@dafner Insiders gives you access to buttons, Restricted will allow you to start conversations with non-contacts.

I just tested - list buttons are working with MD business accounts.

Yes 1 licenses is linked to just 1 host account. If you need more than 5 please email me: shah@openwa.dev

**Comment by smashah** [comment]
Buttons will not be GA for the foreseeable future. It looks like they will be restricting usage of buttons to verified business accounts only anyways soon.
