### ISSUE TITLE
How to sendFile sevaral files one after another

### ISSUE THREAD

**Issue by DiyRex** [open-wa/wa-automate-nodejs#2396]
I have listed few rar files in my project directory. I need to use sendFile option to send those rar files one file at a time. How can I do this

I get memoryError in Heroku while uploading those files using sendFile in for loop. I think it happend because sendFile try to send all files at once 

I will very Thankful If anyone guide me how to achieve this :) 

my list =[
'C:\\Users\\XXXX\\AppData\\Local\\Temp\\rar-botlw7scM\\song.part1.rar',
  'C:\\Users\\XXXX\\AppData\\Local\\Temp\\rar-botlw7scM\\song.part2.rar',
  'C:\\Users\\XXXX\\AppData\\Local\\Temp\\rar-botlw7scM\\song.part3.rar',
  'C:\\Users\\XXXX\\AppData\\Local\\Temp\\rar-botlw7scM\\song.part4.rar',
  'C:\\Users\\XXXX\\AppData\\Local\\Temp\\rar-botlw7scM\\song.part5.rar'
}

**Comment by smashah** [comment]
@DiyRex You need to implement a promise queue which does that one at a time.

```js
import PQueue from 'p-queue';

const singleFileQ = new PQueue({
    concurrency: 1,
    intervalCap: 1,
    carryoverConcurrencyCount: true
  })
  
...
const files =[
'C:\Users\XXXX\AppData\Local\Temp\rar-botlw7scM\song.part1.rar',
'C:\Users\XXXX\AppData\Local\Temp\rar-botlw7scM\song.part2.rar',
'C:\Users\XXXX\AppData\Local\Temp\rar-botlw7scM\song.part3.rar',
'C:\Users\XXXX\AppData\Local\Temp\rar-botlw7scM\song.part4.rar',
'C:\Users\XXXX\AppData\Local\Temp\rar-botlw7scM\song.part5.rar'
]

await Promise.all(files.map(file => singleFileQ.add(()=>client.sendFile(to, file, ...)));

//now you can wait until all the files have been sent

```
