### ISSUE TITLE
Post data with axios fail to online server

### ISSUE THREAD

**Issue by emery68** [open-wa/wa-automate-nodejs#2402]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### Are you using Multi-device?

No

### Current Behavior

Iam using axios for fetch data, is okay until today, my BOT WA can't work properly. I check the post data is empty. I use Postman to try another way to fetch data and it normal. What the bug of my software, can you help me?

### Mode

EASY API/CLI

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2147.16",
  "WA_AUTOMATE_VERSION": "4.28.6",
  "BROWSER_VERSION": "HeadlessChrome/97.0.4691.0",
  "START_TS": 1641457700133
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 14.17.0
- npm:
```

**Comment by smashah** [comment]
I can't help unless you give me some more information/requests that you're trying that are not working

**Comment by emery68** [comment]
` let resdt = "";
    let postData = new FormData();
    postData.append("act", "getall");
    postData.append("token", tokenServer);

    await axios({
        method: 'post',
        url: "https://mywebsite/api.php",
        responseType : 'text',
        data: postData,
        headers: postData.getHeaders()
    })
    .then(function (response){
        resdt = response.data;
    });

    return resdt;`

**Comment by emery68** [comment]
This is my code not working yesterday, this code working good properly previous. I dont know what the problem. I hope you can help me

**Comment by emery68** [comment]
https://stackoverflow.com/questions/61332805/axios-post-request-not-sending-parameters


oh igot the solution there, thank u for your attention
