### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by ruanpablodev** [open-wa/wa-automate-nodejs#2426]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

It was supposed to send the buttons, but it's not sending (I'm using google translator because I'm Brazilian)

### Expected Behavior

Send a message with 2 buttons below and a title and a description

### Steps To Reproduce

just run the command

### create() code

```markdown
case 'test':
						kill.sendButtons(from, 'Mensagem de baixo', [
							{
								"id": "1",
								"text": "Comando aqui"
							}
						], 'Mensagem de cima',)
						break
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2149.4",
  "WA_AUTOMATE_VERSION": "4.28.13",
  "BROWSER_VERSION": "Chrome/97.0.4692.99",
  "START_TS": 1642774400107,
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.13.2
- npm: 8.1.2
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/73912095/150543286-8e3a5040-2d6f-417b-b967-d9bd424bea98.png)

**Note: There is no error in the console after executing the command, it just does not send the expected message with the buttons**

### Anything else?

nope

**Comment by KillovSky** [comment]
Opa, seu código supostamente deveria ter uma mensagem após `'Mensagem de cima'`, abaixo segue um exemplo, e cuidado, você deixou vazar sua `API-KEY`.

```javascript
// Este exemplo é utilizável apenas dentro de uma função 'switch'
// Caso você não utilize o formato 'kill' da BOT Íris, mude-a para a função que você utiliza
case 'teste':
    await kill.sendButtons(from, "Mensagem de cima", [
        {
            "id": "1",
            "text": "OP 1"
        },
        {
            "id": "2",
            "text": "OP 2"
        },
        {
            "id": "3",
            "text": "OP 3"
        }
    ], "Mensagem do meio", "Mensagem no final")
break // Você pode pular a ultima mensagem segundo a documentação da W.A, apenas deixe "" no lugar dela
```
Também teve uma pergunta referente ao uso da `sendButtons` na `M.D`, segundo a resposta, é preciso ter a `Insider's License` até que os botões fossem popularmente disponíveis ou seja, que eles não sejam mais uma função beta.

Não tenho certeza sobre isso ainda ser valido pois não houve nenhum prompt de licença no meu terminal e não existe informação sobre essa necessidade - não que eu tenha visto - na documentação de uso, de toda forma, isso é uma coisa que provavelmente apenas o smashah poderá esclarecer.

Até lá, não obtive problemas fora do MD, sendo uma coisa que só acontece quando ela é usada, ou seja, o meu / seu código me funcionou perfeitamente no modo normal, pode ser conveniente que você utilize sem a MD, somente até a dúvida ser esclarecida ou que aconteça o que eu disse acima.

REF -> https://github.com/open-wa/wa-automate-nodejs/issues/2328#issuecomment-993650827

**Comment by smashah** [comment]
Please see https://github.com/open-wa/wa-automate-nodejs/issues/2394#issuecomment-1094666522
