### ISSUE TITLE
Evaluation failed: TypeError Store[...] is not a function at __puppeteer_evaluation_script

### ISSUE THREAD

**Issue by rickricardo** [open-wa/wa-automate-nodejs#2436]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

Just updated my Mac Os to Monterey 12.1 and now I have errors when trying to send a sticker, or adding labels to messages.

Command: client.addLabel('Enviado', msgID)
Error:
Rejection: Error: Evaluation failed: TypeError: Store[("Wap" + _0x22d646(...) + "ry")][("add" + _0x22d646(...) + _0x22d646(...) + _0x22d646(...) + _0x22d646(...) + "ls")] is not a function
    at Object.window.<computed>.<computed> [as addOrRemoveLabels] (__puppeteer_evaluation_script__:1:295769)
    at __puppeteer_evaluation_script__:1:30

Command: client.sendImageAsSticker(msgs['from'], webpURI,{author:author, pack:pack}) 
Error:
Rejection: Error: Evaluation failed: TypeError: _0x2428c6[("sen" + _0x209a6c(...) + _0x209a6c(...) + "t")] is not a function
    at Object.window.<computed>.<computed> [as _sendSticker] (__puppeteer_evaluation_script__:1:146139)
    at async Object.window.<computed>.<computed> [as sendImageAsSticker] (__puppeteer_evaluation_script__:1:149810)

I already updated puppeteer with command "npm i puppeteer", as well wa-automate is up to date.
Any suggestion on what else to update, or new config for mac os Monterey?

### Steps To Reproduce

Use client.addLabel() or client.sendImageAsSticker(0 functions

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2202.8",
  "WA_AUTOMATE_VERSION": "4.30.1",
  "BROWSER_VERSION": "Chrome/97.0.4692.99",
  "START_TS": 1643148535742,
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: macOS Monterey
- Node: 16.4.0
- npm: 8.3.2
```

**Comment by smashah** [comment]
Should be resolved with latest patches.

Thanks for putting in the effort to fill the template.

Track #2437 for any other issues relating to this latest update.
