### ISSUE TITLE
Update: 2.2202.8

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#2437]
Please add any issues relating to this latest WA update in this issue.

- [x] Stickers [fixed]
- [x] Labels [fixed]
- [x] sendLinkWithAutoPreview
- [x] InviteInfo

**Comment by jeferssonlemes** [comment]
I'm doing some tests and it seems that the usual way the agent uses to look up the number is no longer enabled in the MD, i tested it with:
```js 
WAPI.checkNumberStatus('9999999999999')
```
as well as
wa.me/9999999999999

As I said from what I saw now there is a validation that makes it pass outside of this method.

**Comment by smashah** [comment]
closing.
