### ISSUE TITLE
SendButtons method doesn't work with multiDevice enabled

### ISSUE THREAD

**Issue by DaviZMelo** [open-wa/wa-automate-nodejs#2450]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

I'm not able to use the **sendButtons** function while i use the **multiDevice** feature. It works only with the **multiDevice** disabled.

### Expected Behavior

It should send the buttons as it works with the multiDevice disabled. With it enabled the code just stucks and doesn't reply.

### Steps To Reproduce

Not specified

### create() code

```markdown
create({
      disableSpins: true,
      authTimeout: 0,
      qrTimeout: 0,
      logConsole: false,
      keepUpdated: true,
      multiDevice: false,
    });
```

### DEBUG INFO

```markdown
"WA_VERSION": "2.2202.9",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.30.7",
  "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
  "START_TS": 1643424205039
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: v16.13.0
- npm: v8.1.0
```

**Comment by smashah** [comment]
Buttons on MD requires a license. I update the code. can you try again please.
