### ISSUE TITLE
bulk sending

### ISSUE THREAD

**Issue by abbassnet** [open-wa/wa-automate-nodejs#247]
How many messages can I send continuously per minute to different contacts without blocking?
How much difference between bulk?

**Comment by jesusvalverde** [comment]
I do have test 25 every 30 second..for a total of over 500 (all to user I do have regular contact)

**Comment by smashah** [comment]
Nobody has an answer for this. Just as a general rule of thumb do not spam people as that will result in users reporting your number. If the answer to "Can what I'm doing be called spamming" is not immediately "no" then the answer is yes, you are spamming. This project is not allowed to be used for spam. Hope that is clear.
