### ISSUE TITLE
I can't run the demo

### ISSUE THREAD

**Issue by MarcosDLR** [open-wa/wa-automate-nodejs#2490]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

I can't install the dependencies to run the project.

I had to install the visual studio modules and the latest version of python on my server and I still have problems.

### Expected Behavior

Run the last version

### Steps To Reproduce

Just dowmload the last version and run npm i

### create() code

```markdown
create({
  sessionId: "COVID_HELPER",
  authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
  blockCrashLogs: true,
  disableSpins: true,
  headless: false,
  logConsole: false,
  popup: true,
  qrTimeout: 0, 
  multiDevice: false
})
.then(async client =>{
  clientActive = client;
  await start(client);
})
.catch(e=>{
  console.log('Error',e.message);
});
```

### DEBUG INFO

```markdown
I can't see these values ​​because the error is installing the dependencies.
```

### Environment

```markdown
- Windows: 10
- Node: 12.18.3
- npm: 6.14.6
```

### Screenshots/Logs

![Captura de pantalla 2022-02-04 095720](https://user-images.githubusercontent.com/47016656/152546622-2908232d-ec62-4d1d-88b1-812de1b5e56d.png)

**Comment by smashah** [comment]
update your node and npm version to latest then try again
