### ISSUE TITLE
Refresh call is broken again 

### ISSUE THREAD

**Issue by NSOPORTEDESARROLLO** [open-wa/wa-automate-nodejs#2496]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Tested and experienced on both

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

After execute refresh it stops working, a service restart is needed and most re login 

### Steps To Reproduce

/usr/bin/node ./node_modules/@open-wa/wa-automate/bin/server.js --use-chrome --popup --headless --multi-device

### DEBUG INFO

```markdown
/usr/bin/node ./node_modules/@open-wa/wa-automate/bin/server.js --use-chrome --popup --headless --multi-device
```

### Environment

```markdown
- OS: ubuntu 20.04
- Node: v17.4.0
- npm: 8.3.1
```

### Screenshots/Logs

![Captura de pantalla de 2022-02-09 00-45-50](https://user-images.githubusercontent.com/47125165/153136510-db1c278a-206e-47a5-9554-06e552802d8d.png)

**Comment by smashah** [comment]
Please try https://github.com/open-wa/wa-automate-nodejs/releases/tag/4.31.0 and report back if this is still happening so i can reopen this issue.

thanks
