### ISSUE TITLE
Not a issue just some help please !

### ISSUE THREAD

**Issue by rexdevin8** [open-wa/wa-automate-nodejs#2504]
I need to send 90mb list of 10 files using messagemedia option. It work fine for less than 30mb file but when I try to send more than 30mb file my heroku memory usage goes high and crash the app. Is there any way to send media files more than 30mb ( I want to send 90mb ) without memory usage problem please suggest me.

P.s I'm new to programming and I'm trying to learning :)

**Comment by smashah** [comment]
If that's the limit you experience due to memory constraints then you either have to change your environment to something like a DO ubuntu droplet with 1GB of RAM.


Thanks
