### ISSUE TITLE
Session integrity check failed

### ISSUE THREAD

**Issue by alifax89** [open-wa/wa-automate-nodejs#2505]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

The code works fine if I was not authenticated, I scan the QR and everything works as expected, now, if I restart my code I get a whole of "Session integrity check failed" for 10 times then it fails.
I wanted to checkout on my own, so I changed "Headless" to False in my code (to see whats happen on the browser) and strangely it works!
So at least I think that I gave you a point where to investigate!

### Steps To Reproduce

It cause the same error even with a simple configuration like:
```
wa
  .create({
    sessionId: 'test', //name of session
    multiDevice: true, // for version not multidevice use false.(default: true)
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onMessage((message) => {
    client.kill();
  });
}
```
The first time (when you need to authenticate) it works fine, if you restart, it will loop in the session integrity check

### create() code

```markdown
.create({
    sessionId: 'test', //name of session
    multiDevice: true, // for version not multidevice use false.(default: true)
    // useChrome: true,
    // executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    blockCrashLogs: true,
    disableSpins: true,
    headless: true,
    chromiumArgs: [
        "--disable-gpu",
        "--disable-dev-shm-usage",
        "--disable-setuid-sandbox",
        "--no-sandbox"
    ]
  })
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2204.13",
  "WA_AUTOMATE_VERSION": "4.30.13",
  "BROWSER_VERSION": "Chrome/98.0.4758.102",
  "START_TS": 1644998092480,
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.13.2
- npm: 8.1.2
```

**Comment by smashah** [comment]
Please try https://github.com/open-wa/wa-automate-nodejs/releases/tag/4.31.0 and report back if this is still happening so i can reopen this issue.

thanks
