### ISSUE TITLE
client.deleteMessage not working

### ISSUE THREAD

**Issue by Slavecode** [open-wa/wa-automate-nodejs#2508]
previously I used this `client.deleteMessage(quotedMsgObj.chatId, quotedMsgObj.id, false)` but now it doesn't work

**Comment by smashah** [comment]
Just tried this locally. seems to be working fine. Please fill the issue template with reproducible instructions

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.yaml&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.yaml&title=)⚠️⚠️⚠️

**Comment by Slavecode** [comment]
> Just tried this locally. seems to be working fine. Please fill the issue template with reproducible instructions

![20220217_202943](https://user-images.githubusercontent.com/43001614/154482177-a15f1e87-90b5-4c95-8e15-450989eaa7a2.jpg)
This output
