### ISSUE TITLE
QR code not working

### ISSUE THREAD

**Issue by Rashid-Cal4care** [open-wa/wa-automate-nodejs#2525]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

EASY API/CLI

### Current Behavior

After Creating the whatsapp instance in pm2, when i tried to scan the QR code not refreshing and cant able to scan the QR code.
![image](https://user-images.githubusercontent.com/76432449/155523014-e40085b7-8160-4f26-8a85-f00640887ae7.png)

### Expected Behavior

Should be able to scan on all devices

### Steps To Reproduce

1.Update the libraty to the latest one.
2. running command 
3. PM2 command - 
 npx @open-wa/wa-automate "--in-docker" "--session-id" "c4c-inst13" "--block-assets" "--port" "3012" "--skip-save-postman-collection" "--api-host" "http://206.189.86.180/api/c4c-inst13" "--webhook" "https://uat.baobabgroup.mconnectapps.com/api/v1.0/omni-whatsapp-bot/" "--popup" "--qr-refresh-s" "15" "--multi-device"

### create() code

```markdown
app.post('/create', async (req, res) => {
  let {sessionId, sessionData, webhook} = req.body;
  if(proxyRegistry[sessionId]) return res.send(`${sessionId} already exists`);
  console.log(`starting ${sessionId}`)
  const port = await getPort({port: getPort.makeRange(3001, 3100)})
  console.log("Using PORT", port);
  let env = {
    "WA_API_HOST_ADDR":`http://${ipaddress}:${port}/`,
    "WA_DISABLE_SPINS": true,
    "WA_BLOCK_CRASH_LOGS": true,
    "WA_SESSION_ID": sessionId,
    "WA_AUTO_REFRESH": true
  };
  if(!persistDataJson) env["WA_SKIP_SESSION_SAVE"] = true
  if(sessionData) env["WA_SESSION_DATA"] = sessionData
  pm2.start({
    name: sessionId,
    script: "npm",
    //if api public api port IS NOT 80
    // args    : `run fire -- --in-docker --block-assets --port ${port} --skip-save-postman-collection --api-host 'http://${ipaddress}:${PORT}/api/${sessionId}' --webhook '${webhook}' --popup`,
    //if api public port IS 80
    args    : `run fire -- --in-docker --session-id '${sessionId}'--block-assets --port ${port} --skip-save-postman-collection --api-host 'http://${ipaddress}/api/${sessionId}' --webhook '${webhook}' --popup --qr-refresh-s 20`,
    max_memory_restart : '1000M', 
    env
  }, function(err, apps) {
    pm2.disconnect();   // Disconnects from PM2
    if (err) throw err
  });
  proxyRegistry[sessionId] = `http://${ipaddress}:${port}/`
  return res.send(`${sessionId} started.`);
});
```

### DEBUG INFO

```markdown
Debug info: {
  "WA_VERSION": "2.2206.5",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.31.6",
  "BROWSER_VERSION": "HeadlessChrome/99.0.4844.0",
  "OS": "Linux 5.4",
  "START_TS": 1645704662559
}
```

### Environment

```markdown
- OS:  Ubuntu 20.04 
- Node: 16.14.0
- npm: 8.5.1
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/76432449/155524358-f715a274-50e7-418c-937c-b53e6fe998dd.png)

**Comment by MarcosDLR** [comment]
try version 4.26.1 is currently working

**Comment by Rashid-Cal4care** [comment]
> try version 4.26.1 is currently working

Thank You, After Downgrading its working as usual, but still it wont works with multi-device.

**Comment by lukasportal** [comment]
related to this
https://github.com/open-wa/wa-automate-nodejs/issues/2526

**Comment by smashah** [comment]
see #2526
