### ISSUE TITLE
audios sent using "sendPtt" cannot be accelerated 

### ISSUE THREAD

**Issue by JorgeLukas3D** [open-wa/wa-automate-nodejs#2528]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Tested and experienced on both

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

audios sent using "sendPtt" cannot be accelerated (1.5x/2x) in whatsapp mobile interface, if an audio is heard at 1.5x / 2x and you try to hear an audio sent by the bot it automatically goes back to 1x and if you try to speed up the audio nothing happens, but if you try to listen on desktop/browser version of whatsapp you can do 

### Steps To Reproduce

send audio via Ptt

### create() code

```markdown
sessão.create({     
    useChrome: true, 
    multiDevice: true,
    sessionId: "Nathan_BOT",
    authTimeout: 60, 
    blockCrashLogs: true,
    disableSpins: true,
    headless: false,
    hostNotificationLang: 'PT_BR',
    logConsole: false,
    popup: true,
    qrTimeout: 0, 
}).then(nathan => start(nathan))
```

### DEBUG INFO

```markdown
Debug info: {
  "WA_VERSION": "2.2204.13",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.31.7",
  "BROWSER_VERSION": "Chrome/98.0.4758.102",
  "OS": "Windows 8.1",
  "START_TS": 1645805978018
}
```

### Environment

```markdown
- OS: Windows 8.1
- Node: 16.14.0
- npm: 8.3.1
```

**Comment by smashah** [comment]
@JorgeLukas3D what's the mimetype of a working ptt?

**Comment by smashah** [comment]
Seems like some sort of encoding issue

**Comment by JorgeLukas3D** [comment]
> @JorgeLukas3D what's the mimetype of a working ptt and can you please attach a file which you are using to test to this issue please

I tried to use an audio in .ogg instead of .mp3 and it worked normally. thanks
