### ISSUE TITLE
Error on setGroupTitle with MD

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#2529]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

My own code

### Current Behavior

when i run `client.setGroupTitle(groupId, "Test")`, then error

Also error on : 
`setGroupEditToAdminsOnly`

### Steps To Reproduce

run the script

### create() code

```markdown
await create({
	sessionId: 'HIMA',
	multiDevice: true,
	blockCrashLogs: true,
	logConsole: false,
	headless: true,
	qrTimeout: 0,
	authTimeout: 60,
	autoRefresh: false,
	restartOnCrash: start,
	useChrome: true,
	disableSpins: true,
	popup: true,
	//cacheEnabled: true,
	licenseKey: 'D922F9C1-7BD04EE4-A3FE324E-F3D7B4DA',
}).then(client => start(client));
```

### DEBUG INFO

```markdown
Debug info: {
  "WA_VERSION": "2.2206.5",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.31.7",
  "BROWSER_VERSION": "Chrome/98.0.4758.102",
  "OS": "Windows 10",
  "START_TS": 1645824620668
}
```

### Environment

```markdown
- OS: Windows 11
- Node: v16.13.2
- npm: 8.2.0
```

### Screenshots/Logs

`setGroupTitle` error :
![image](https://user-images.githubusercontent.com/18587059/155805852-756aa0b9-2885-48f6-bca1-464b14b0c090.png)

`setGroupEditToAdminsOnly` error :
![image](https://user-images.githubusercontent.com/18587059/155810373-5f04078d-bff6-428b-91bd-4d96e7cd579a.png)

**Comment by smashah** [comment]
@dandyraka fixed with license server update. please restart and try again. report back if still not working. thanks

**Comment by dandyraka** [comment]
@smashah still not work

`setGroupTitle` error :
![image](https://user-images.githubusercontent.com/18587059/155855687-14131101-f485-45e5-ab6c-1f0c1cb65f98.png)

`setGroupEditToAdminsOnly` error :
![image](https://user-images.githubusercontent.com/18587059/155855717-7027294b-a047-4606-9793-820fb77e1348.png)

**Comment by dandyraka** [comment]
Also `sendImageAsStickerAsReply` not reply the chat

**Comment by smashah** [comment]
@dandyraka try now

**Comment by dandyraka** [comment]
@smashah all work thanks.

Except 'setGroupTitle'
Not working with no error. But state changed OPENING, PAIRING

**Comment by smashah** [comment]
im testing on personal MD, group title is working @dandyraka

**Comment by dandyraka** [comment]
> im testing on personal MD, group title is working @dandyraka 
> 
> 

Thank you, it work now 😁

**Comment by dandyraka** [comment]
@smashah error on `setGroupIcon` and `setGroupIconByUrl`
![image](https://user-images.githubusercontent.com/18587059/155901882-eb74f02c-1905-437a-836b-46d8e71b01c8.png)

**Comment by smashah** [comment]
@dandyraka try now
