### ISSUE TITLE
Not getting all unread messages

### ISSUE THREAD

**Issue by MarcosDLR** [open-wa/wa-automate-nodejs#2532]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

When I use the getAllUnreadMessages method after scanning the code it brings me all the unread messages, but if I restart when I call the getAllUnreadMessages method it doesn't seem to load all the messages, it seems that now the chats are paginated and I can't get all the unread messages , if there is any solution or method for this case please let me know.

### Expected Behavior

Grab all unread messages

### Steps To Reproduce

Restart with a considerable number of conversations

### create() code

```markdown
sessionId: 'COVID_HELPER',
  authTimeout: 60,
  blockCrashLogs: true,
  disableSpins: true,
  headless: false,
  logConsole: false,
  popup: false,
  qrTimeout: 0,
  multiDevice: true,
  useChrome: true
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2206.5",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.31.7",
  "BROWSER_VERSION": "Chrome/98.0.4758.102",
  "OS": "Windows Server 2019",
  "START_TS": 1645900280962
}
```

### Environment

```markdown
- OS: Windows Server 2019
- Node: v14.15.3
- npm: 6.14.9
```

**Comment by smashah** [comment]
@MarcosDLR have you tried this https://docs.openwa.dev/classes/api_Client.Client.html#getIndicatedNewMessages

?

**Comment by MarcosDLR** [comment]
I tried it, it works very well, thanks
