### ISSUE TITLE
Feature Request : Star

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#2535]
Is it possible to : 
- Star & Unstar message
- Get list starred message by chatId (if personal) or groupId (if group)

![image](https://user-images.githubusercontent.com/18587059/156046593-eac41a31-12e0-4559-ac90-dd1e908293cb.png) ![image](https://user-images.githubusercontent.com/18587059/156046693-3ffbacc5-7536-4dc7-b0aa-cea9508afdcf.png)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "minor"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.32.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.31.13...4.32.0) (2022-03-08)

- Release 4.32.0 [`aa7580f`](https://github.com/open-wa/wa-automate-nodejs/commit/aa7580fa17eed549246d78fa28a7a3db0c64f134)
- ✨ feat: `client.unstarMessage` #2535 [`ccffa0a`](https://github.com/open-wa/wa-automate-nodejs/commit/ccffa0a5974a0331474a9232acb7626fe4dd842a)
- ✨ feat: `client.getStarredMessages` #2535 [`cb97b1d`](https://github.com/open-wa/wa-automate-nodejs/commit/cb97b1dcabeb6268da40147639419508b796e025)
- ✨ feat: `client.starMessage` #2535 [`d07f237`](https://github.com/open-wa/wa-automate-nodejs/commit/d07f237da109f5a4d1e353c1aa4e3073ccce0d93)
- 🥚 patches update [`f46842a`](https://github.com/open-wa/wa-automate-nodejs/commit/f46842a28aa9cb6619c812a7b02aee988db385e2)
- updated types-only package [`dbee3a8`](https://github.com/open-wa/wa-automate-nodejs/commit/dbee3a801c33909896cf1e26c27ea8fb7dfe6b99)

**Comment by smashah** [comment]
thanks for the cool suggestion @dandyraka keep em coming! :) enjoy!
