### ISSUE TITLE
Multi sessions dont work!

### ISSUE THREAD

**Issue by shayanfh** [open-wa/wa-automate-nodejs#2537]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Tested and experienced on both

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

I used 2 session instances, first session no problem but the second session didn't get a qr code and stack on Authenticate to continue , nothing happened from the event emitter.

### Steps To Reproduce

node app.js

### create() code

```markdown
let launchConfig = {
    useChrome: true,
    autoRefresh: true,
    // cacheEnabled: true,
    // headless: false,
    logConsoleErrors: true,
    // cachedPatch: true,
    logFile: true,
    disableSpins: true,
    // qrLogSkip: true,
    // qrTimeout: 10,
    // authTimeout:0,

    // multiDevice: true,
  };
create(launchConfig);
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2206.9",
  "WA_AUTOMATE_VERSION": "4.31.7",
  "BROWSER_VERSION": "HeadlessChrome/98.0.4758.102",
  "START_TS": 1646217109239,
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.13.2
- npm: 8.1.2
```

### Screenshots/Logs

- Authenticate to continue
Error while terminating browser PID. You can just ignore this, as the process has most likely been terminated successfully already: kill ESRCH
Error: QR Timeout
    at D:\Prj Nodejs\whatsapp\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:289:27  
    at Generator.next (<anonymous>)
    at fulfilled (D:\Prj Nodejs\whatsapp\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error while terminating browser PID. You can just ignore this, as the process has most likely been terminated successfully already: kill ESRCH
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: QR Timeout
    at D:\Prj Nodejs\whatsapp\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:289:27  
    at Generator.next (<anonymous>)
    at fulfilled (D:\Prj Nodejs\whatsapp\node_modules\@open-wa\wa-automate\dist\controllers\initializer.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by smashah** [comment]
see #2520
