### ISSUE TITLE
Listing all groups after creating a new group doesn't return new group name

### ISSUE THREAD

**Issue by garciabruno** [open-wa/wa-automate-nodejs#2540]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

My own code

### Current Behavior

When creating a new group and subsequently getting all groups from that account, the newly created group only has the "id" field, but not the group's name.

### Expected Behavior

Also fetch the new group's name.

### Steps To Reproduce

1- Create a group with a test name, eg: "NEW_GROUP" (client.createGroup)
2- List all groups (client.getAllGroups), all information about "NEW_GROUP" is there except key "name"

### create() code

```markdown
const inDocker = process.env.IN_DOCKER === "true";
logger.info(`Starting wa-automate. inDocker: ${inDocker}`);

create({
  inDocker,
  sessionId: inDocker ? undefined : "wa-automate-session",
}).then((client) => start(client));
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2206.9",
  "WA_AUTOMATE_VERSION": "4.31.7 UPDATE AVAILABLE: 4.31.8",
  "BROWSER_VERSION": "HeadlessChrome/99.0.4844.0",
  "START_TS": 1646366014634,
  "LATEST_VERSION": false,
  "CLI": false
}
```

### Environment

```markdown
- OS: Linux 5.13
- Node: 17.2.0
- npm: 8.1.4
```

**Comment by smashah** [comment]
Should be resolved now thanks
