### ISSUE TITLE
Sending message with link cause app to crash

### ISSUE THREAD

**Issue by phaalonso** [open-wa/wa-automate-nodejs#2545]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

My own code

### Current Behavior

While sending an message that contains an link using the method `client.sendLinkWithAutoPreview()` the application crashes because an error on puppeteer.

### Expected Behavior

Sending an message with preview to open the link

### Steps To Reproduce

Send an link using the client

### create() code

```markdown
const client = await create({
    disableSpins: true,
    multiDevice: true,
    authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
    blockCrashLogs: true,
    headless: false,
    hostNotificationLang: NotificationLanguage.PTBR,
    logConsole: false,
    cacheEnabled: false, 
    qrTimeout: 0,
    useChrome: true,
    viewport: {
        height: 800,
	width: 800
    },
    chromiumArgs: [
        '--no-sandbox',
	'--aggressive-cache-discard',
	'--disable-cache',
	'--disable-application-cache',
	'--disable-offline-load-stale-cache',
	'--disk-cache-size=0',
	'--mute-audio',
   ],
   killProcessOnBrowserClose: true,
   killClientOnLogout: true,
})
```

### DEBUG INFO

```markdown
Debug info: {
  "WA_VERSION": "2.2206.9",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.31.12",
  "BROWSER_VERSION": "Chrome/94.0.4606.54",
  "OS": "Linux 5.15",
  "START_TS": 1646615145475
}
```

### Environment

```markdown
- OS: Pop-OS 20.04
- Node: 16.13.1
- npm: 8.1.2
```

### Screenshots/Logs

Error log:
```
2022-03-06 22:06:09 error:    Evaluation failed: j Error: Evaluation failed: j
    at ExecutionContext._evaluateInternal (/home/pedro/programacao/leo/zapsql/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ExecutionContext.evaluate (/home/pedro/programacao/leo/zapsql/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
```

**Comment by smashah** [comment]
Auto previews don't work on multi device last I checked. This is an issue from wa itself

**Comment by dandyraka** [comment]
> Auto previews don't work on multi device last I checked. This is an issue from wa itself 

i try on MD tok.
First run error, but second run works

**Comment by smashah** [comment]
I have double checked on vanilla MD session, auto previews simply do not work on MD. I will make sure to avoid this error leading to a crash for now.

**Comment by smashah** [comment]
@phaalonso this error has been suppressed.

**Comment by smashah** [comment]
@phaalonso This is now fixed in the latest version:

https://github.com/open-wa/wa-automate-nodejs/issues/2603#issuecomment-1081332020
