### ISSUE TITLE
License request failed when run refresh()

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#2547]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

when i run `client.refresh()`, then error on license and inject script

### Steps To Reproduce

run the script

### create() code

```markdown
await create({
	sessionId: 'HIMA',
	multiDevice: true,
	blockCrashLogs: true,
	logConsole: false,
	headless: true,
	qrTimeout: 0,
	authTimeout: 60,
	autoRefresh: false,
	restartOnCrash: start,
	useChrome: true,
	disableSpins: true,
	popup: true,
	//cacheEnabled: true,
	licenseKey: 'D922F9C1-7BD04EE4-A3FE324E-F3D7B4DA',
}).then(client => start(client));
```

### DEBUG INFO

```markdown
- Debug info: {
  "WA_VERSION": "2.2206.9",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.31.12",
  "BROWSER_VERSION": "HeadlessChrome/98.0.4758.102",
  "OS": "Windows 10",
  "START_TS": 1646617631735
}
```

### Environment

```markdown
- OS: Windows
- Node: v16.13.2
- npm: 8.2.0
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/18587059/156957928-26f4f539-0626-4d21-9153-21c136a8b723.png)

**Comment by smashah** [comment]
fixed
