### ISSUE TITLE
 Launch inject: 5369ms...won't connect

### ISSUE THREAD

**Issue by JustinBocchi** [open-wa/wa-automate-nodejs#2561]
### Are you using the latest version of the library?

- [x] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

Launch inject: 2609ms
✓ Launch inject: 2386ms
✓ Launch inject: 1552ms

the last sessionid's are not starting

### Expected Behavior

starting all sessionid's

### Steps To Reproduce

Config: https://www.toptal.com/developers/hastebin/katesevapi.js
db=  var hosts = [ "Jeremias_4", "Franco_1".......]
we are using the database instead of this code above, this will do the same job
Starting bot with 20 sessionid'
![Mbm2P8azXd](https://user-images.githubusercontent.com/101510059/158063536-1060abba-a835-42be-8c3a-dc9b3d94452a.png)

### create() code

```markdown
create({
            "sessionDataPath": "/home/whatsapp/Sessions",
            "sessionId": hosts[i].id,
            // "sessionId": "Justin_1", // to start one session
            "headless": true,
            "qrTimeout": 0,
            // "qrLogSkip": false,
            "authTimeout": 0,
            "restartOnCrash": start,
            "cacheEnabled": false,
            "useChrome": true,
        	"disableSpins": false,
            // "logging":[{type:"console"}],
            "killProcessOnBrowserClose": true,
            "throwErrorOnTosBlock": false,
            "chromiumArgs": [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--aggressive-cache-discard',
                '--disable-cache',
                '--disable-application-cache',
                '--disable-offline-load-stale-cache',
                '--disk-cache-size=0'
            ]

        })
```

### DEBUG INFO

```markdown
Debug info: {
  "WA_VERSION": "2.2208.7",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.32.5",
  "BROWSER_VERSION": "HeadlessChrome/99.0.4844.51",
  "OS": "Linux 5.4",
  "START_TS": 1647179798030
}
```

### Environment

```markdown
- OS: Ubuntu 20.04.4 LTS x86_64
- Node: 17.5.0
- npm: 8.4.1
```

### Screenshots/Logs

![wRcWehdUEy](https://user-images.githubusercontent.com/101510059/158063244-ff3d5b27-e926-4eb0-a9ff-b7c1bb249cd9.png)

[application-2022-03-13-15.log.zip](https://github.com/open-wa/wa-automate-nodejs/files/8239812/application-2022-03-13-15.log.zip)

**Comment by smashah** [comment]
Try to start only one bot and see if it works

**Comment by smashah** [comment]
Closing. Please report back if theres more info on this.
