### ISSUE TITLE
Repetitive "middleware -> error Error: Evaluation failed: i" error

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#2571]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

Few minutes before starting I got a sequence of erros like this - incontable:

0|***  | middleware -> error Error: Evaluation failed: i
0|***  |     at ExecutionContext._evaluateInternal (/***/wa-automate-nodejs/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
0|***  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|***  |     at async ExecutionContext.evaluate (/***/wa-automate-nodejs/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)

### Expected Behavior

No erros just the last info about address to access the api-docs.

### Steps To Reproduce

1. Start with ```pm2 start /***/wa-automate-nodejs/bin/server.js --exp-backoff-restart-delay=100 --name **** -- -p 55225 -h *** -a --auto-refresh --skip-save-postman-collection --auto-reject --skip-url-check --cwd /*** --config /***/***.config.json --chatwoot-url "https://***.***.com/api/v1/accounts/1/inbox/4" --chatwoot-api-access-token "***"```

2. Config is: 
```js
{
        "authTimeout": 0,
        "cacheEnabled": false,
        "disableSpins": true,
        "hostNotificationLang": "pt-br",
        "licenseKey": "***",
        "sessionDataPath": "/***",
        "sessionId": "***",
        "killProcessOnBrowserClose": true,
        "killProcessOnTimeout": true,
        "killClientOnLogout": true,
        "useChrome": true
}
```

4. Wait a few minutes (~5min)

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2208.7",
  "WA_AUTOMATE_VERSION": "4.32.11",
  "BROWSER_VERSION": "HeadlessChrome/99.0.4844.51",
  "START_TS": 1647428082218,
  "LATEST_VERSION": true,
  "CLI": true
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 17.7.1
- npm: 8.5.2
```

**Comment by smashah** [comment]
Closing until there's more context. thanks
