### ISSUE TITLE
sessionData as base64 is no longer generated

### ISSUE THREAD

**Issue by garciabruno** [open-wa/wa-automate-nodejs#2578]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Tested and experienced on both

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

My own code

### Current Behavior

Session data in base64 is no longer being generated. What I'm seeing is a session data file being created with the content `e30=` (Which is `{}` when decoded) and a `_IGNORE_{SESSION_NAME}` directory being created on the root directory.

### Expected Behavior

I was expecting to receive the full base64 session data that I can then use to set through an environment variable to log in. I tried forcing multiDevice to false, but I believe the Multi device beta has been ended by WhatsApp, and now we're being forced to use the multidevice feature.

### Steps To Reproduce

1. Scan the login QR code
2. It will deny the first QR and generate a second one.
3. Scan and login with the second QR code
4. {sessionName}.data.json file with contain `e30=` and `_IGNORE_{sessionName}` directory would have been created

### create() code

```markdown
create({ multiDevice: true, inDocker }).then((client) => start(client));

function start(client: Client) {
client.onMessage(async (message: Message) => {
  onMessage(message);
});
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2208.14",
  "WA_AUTOMATE_VERSION": "4.32.14",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4889.0",
  "START_TS": 1647566818739,
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Linux 5.13
- Node: 17.2.0
- npm: 8.1.4
```

**Comment by smashah** [comment]
This is the current standard operating procedure for multi device.

Track #2338
