### ISSUE TITLE
getGroupMembers crashes on MD for groups too down the list.

### ISSUE THREAD

**Issue by garciabruno** [open-wa/wa-automate-nodejs#2579]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

* When calling getGroupMembers() on a group it's too down the list of groups (Beyond the hundreds) crashes.

### Expected Behavior

* Retrieve list of participants/members

### Steps To Reproduce

1. Get a group id for a group that appears way down your chat list (Beyond the hundreds...)
2. Call getGroupMembers()
3. Watch it crash

### create() code

```markdown
create({ multiDevice: true, inDocker }).then((client) => start(client));

function start(client: Client) {
  client.onMessage(async (message: Message) => {
    onMessage(message);
  });
}
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2208.14",
  "WA_AUTOMATE_VERSION": "4.32.14",
  "BROWSER_VERSION": "HeadlessChrome/99.0.4844.74",
  "START_TS": 1647572446444,
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 16.14.0
- npm: 8.3.1
```

### Screenshots/Logs

/usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.js:2133
            const actions = membersIds.map(memberId => {
                                       ^
TypeError: membersIds.map is not a function
    at Client.<anonymous> (/usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.js:2133:40)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@open-wa/wa-automate/dist/api/Client.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Anything else?

I have a WhatsApp account with thousands of chats (Probably beyond 1100) and often do operations over chats that are loaded way down the chat list, if you need access to test please contact me :)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.32.17](https://github.com/open-wa/wa-automate-nodejs/compare/4.32.16...4.32.17) (2022-03-20)

- Release 4.32.17 [`f7713f9`](https://github.com/open-wa/wa-automate-nodejs/commit/f7713f99c3ed5b8f3a574a2dadad16bd9d0aa725)
- 🥚 patches update [`f8ac041`](https://github.com/open-wa/wa-automate-nodejs/commit/f8ac041ae8a9e0c86dde52fba6ab2ec48cfe52d0)
- updated types-only package [`500037c`](https://github.com/open-wa/wa-automate-nodejs/commit/500037c57ee049919c7a0bedd6955524c49ea96d)
- 🔊 verbose log to investigate #2579 [`8e64af6`](https://github.com/open-wa/wa-automate-nodejs/commit/8e64af6c2ab2c9bb8cbc04801dfa3a254e4281f1)

**Comment by smashah** [comment]
@garciabruno please use the latest version and enable `"logging:[{"type":"console"}]` then DM me all the logs

**Comment by garciabruno** [comment]
@smashah DM'd them on Discord :)

**Comment by smashah** [comment]
fixed
