### ISSUE TITLE
how to create a conversation instance with sulla

### ISSUE THREAD

**Issue by xshion13** [open-wa/wa-automate-nodejs#258]
I hope if anyone can provide an example about how to do it, in order to register data based on message.sender asking to bot to store info in chat group or private chat:
**if((message.body).includes('registration'){**
sulla chatbot: Hello, what's your name? (wait for response)
message.sender: Adam
sulla chatbot: Wha'ts your email Adam? (wait for response)
message.sender: adamproject@maildd.com

fetch(url+valuename+phonenumber+email)....
sulla chatbot: thank's Adam, your registration was sucessfully

**Comment by impozzible** [comment]
Check this https://github.com/joaomirandasa/w2api

**Comment by UnKnoWn-Consortium** [comment]
You can make use of the `onMessage` listener, `sendText`, and `reply` method plus some programming to make that happen. It is not that hard as this project has already mapped all functions you need to create a chatbot from WhatsApp Web. You have to manage the chat context externally yourself though. That is not difficult either imo.

**Comment by alishahlakhani** [comment]
Personally I'm using a keyword. I send a message with the keyword "@something" and than I ask them to "inline"-reply to that message. Once I have it. I read the reply obj and parse accordingly.

**Comment by smashah** [comment]
Closing for now. This question has a million different answers. To discuss more please join the discord (link in readme).
