### ISSUE TITLE
🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#2584]
🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫🤫

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.32.16](https://github.com/open-wa/wa-automate-nodejs/compare/4.32.15...4.32.16) (2022-03-19)

- Release 4.32.16 [`67b96af`](https://github.com/open-wa/wa-automate-nodejs/commit/67b96afc39310de2db0c6872e62c312c37db74d5)
- ✨ feat: 🤫 shhhhh #2584 [`4d7a383`](https://github.com/open-wa/wa-automate-nodejs/commit/4d7a3838e41e104fd56d47be36a8c0768d34b281)
- updated types-only package [`7debaa8`](https://github.com/open-wa/wa-automate-nodejs/commit/7debaa81644d1a2f7288dfcf51575f036c4751e2)

**Comment by Sansekai** [comment]
![20220319_170130](https://user-images.githubusercontent.com/34540627/159114884-2a2fbff3-3ec9-458e-a6f0-260fc3b07479.jpg)
Only for MD?

**Comment by smashah** [comment]
@Sansekai i guess. i only tested in MD.

**Comment by WolfDWyc** [comment]
@smashah This is awesome! Great job! Thank you!

**Comment by ivenkatraj** [comment]
> @Sansekai i guess. i only tested in MD.

MD abbreviation?
