### ISSUE TITLE
[#2584] React Issue with quotedMsgObj.id

### ISSUE THREAD

**Issue by t0g3pii** [open-wa/wa-automate-nodejs#2586]
![Screenshot_20220319-125600_WhatsApp](https://user-images.githubusercontent.com/49153387/159120187-0354c84f-6f4d-4488-a57b-6319007dc671.jpg)

So basically the Bot sends a message with sendTextWithMention, the return of that CAN be used for client.react without issues, if we mention the message now and get the id of the quotedMsg and try to use that for the react Feature it CANT be used and returns no message found.
When we replace the last part of the string "_botNumber@c.us" with nothing (just remove it) it works again like a charm.. so idk where exactly the issue lays.. how the messageid gets generated from the quotedMsgObj (it appends a _userId@c.us) or how react tries to find the message and cant find it somehow..

If it doesnt explain me enough, you know where to find me :3

ƬӨGΣPII#1337

**Comment by smashah** [comment]
`_botNumber@c.us` is actually how it's meant to be the bug seems to be the mention command is creating a message with an incorrect ID. This should be fixed in the latest patches where the group mention message will have `_botNumber@c.us` at the end.

**Comment by t0g3pii** [comment]
Tested with the Following command:
`client.react(message.quotedMsgObj.id, "❤️")`
and worked without Problems. Seem to be fixed
