### ISSUE TITLE
Can't consistency get the participants of groups

### ISSUE THREAD

**Issue by OreNope** [open-wa/wa-automate-nodejs#2593]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

EASY API/CLI

### Current Behavior

For the top first 10 groups, the function getGroupParticipants works well,
but for the other groups the function crashes..

### Expected Behavior

Consistently get the participants of groups, without crashes

### Steps To Reproduce

npx @open-wa/wa-automate --license-key=key --multi-device true

### DEBUG INFO

```markdown
WA_VERSION      │                                                                 '2.2208.14'                                                                  │
│       PAGE_UA       │ 'WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '4.32.5'                                                                   │
│   BROWSER_VERSION   │                                                        'HeadlessChrome/100.0.4889.0'                                                         │
│         OS          │                                                               'macOS Monterey'                                                               │
│      START_TS       │                                                                1648230164132
```

### Environment

```markdown
Tested on:
- OS: Windows 10 and MacOS
- Node: v17.4.0
- npm: 8.3.1
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/78981378/160173536-fbb10b62-20b3-4aa0-81b1-b7a0704adabf.png)

**Comment by smashah** [comment]
Please set


`"logging":[{"type":"console"}]`

And paste all logs here
