### ISSUE TITLE
middleware -> error Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'msgs')

### ISSUE THREAD

**Issue by hassanexcelorithm** [open-wa/wa-automate-nodejs#2601]
Cannot receive messages in my chat. following is the log.

- Starting
- Version: 4.31.7
- Initializing WA
- Launching Browser
- Browser launched: 909ms
- Setting Up Page
- Loading session data
- Found session data file: /root/nodejs_process/session.data.json
- Existing session data detected. Injecting...
- Existing session data injected
- Pre page launch setup complete: 9ms
- Navigating to WA
- Page loaded in 5411ms: 200
- Page loaded
┌─────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                    Values                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2208.14'                                                                  │
│       PAGE_UA       │ 'WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                      '4.31.7 UPDATE AVAILABLE: 4.32.17'                                                      │
│   BROWSER_VERSION   │                                                         'HeadlessChrome/98.0.4758.0'                                                         │
│         OS          │                                                                 'Linux 3.10'                                                                 │
│      START_TS       │                                                                1648460714772                                                                 │
└─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
- Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2208.14%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.31.7%20UPDATE%20AVAILABLE:%204.32.17%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/98.0.4758.0%22,%0A%20%20%22START_TS%22:%201648460714772,%0A%20%20%22LATEST_VERSION%22:%20false,%0A%20%20%22CLI%22:%20true%0A%7D&enviro=-%20OS:%20Linux%203.10%0A-%20Node:%2014.18.3%0A-%20npm:%206.14.15&labels=CLI,NCV,Legacy
- Time to injection: 1246ms
- Injecting api
- Injecting scripts
- Base inject: 73ms
- WAPI inject: 10ms
- Checking session integrity
- Session integrity check passed
- Launch inject: 2614ms
- WAPI injected
- Authenticating
- Authenticated
- Reinjecting api
- Injecting scripts
- WAPI inject: 230ms
- Checking session integrity
- Session integrity check passed
- Launch inject: 1983ms
- WAPI Reinjected
- Checking if session is valid
- Downloading patches from https://cdn.openwa.dev/patches.json
- Client is ready
- Downloaded patches in 0.678s
- Installing patches
- Patches Installed: e2ffc
- Client loaded for normal account with 1 contacts, 0 chats & 0 messages in 27.258s
- Finalizing web session...
- Finalizing client...
- 🚀 @OPEN-WA ready for account: 3689
- session_STARTUP
- Setting Up API Explorer
- API Explorer set up successfully
- ...waiting for port 8002 to be free
- Port 8002 is now free.
- 
	API Explorer (​http://localhost:8002/api-docs/ ​)
- 
• Listening on port 8002!
middleware -> error Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'msgs')
    at Object.window.<computed>.<computed> [as getAllMessagesInChat] (__puppeteer_evaluation_script__:1:243927)
    at ExecutionContext._evaluateInternal (/root/nodejs_process/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/root/nodejs_process/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
middleware -> error Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'msgs')
    at Object.window.<computed>.<computed> [as getAllMessagesInChat] (__puppeteer_evaluation_script__:1:243927)
    at ExecutionContext._evaluateInternal (/root/nodejs_process/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/root/nodejs_process/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
- Injecting scripts
- Launch inject: 798ms

**Comment by smashah** [comment]
Don't just dump error logs here.

error suppressed in patches
