### ISSUE TITLE
Detect incoming call

### ISSUE THREAD

**Issue by itzharDev** [open-wa/wa-automate-nodejs#261]
Is there any event for incoming call?

For bots is good to auto reject for calls

**Comment by marcelocecin** [comment]
https://github.com/alfred82santa/whalesong/blob/6837ee3091e64f95166a4588a48395f262ba833e/whalesong/managers/message.py

**Comment by jesusvalverde** [comment]
not able to fin anything ...but sound a great idea

**Comment by smashah** [comment]
I've spent some time on it. It's simple enough to listen to a call event but because Whatsapp web doesn't actually deal with calls, I can't get it to reject the call even, yet.

**Comment by itzharDev** [comment]
I think reject is nice to have, but not mandatory

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.33](https://github.com/smashah/sulla/compare/1.8.32...1.8.33) (2020-04-05)

- Correction in the way of calling the version identifier [`#274`](https://github.com/smashah/sulla/pull/274)
- Fix: wrong port loggin [`#270`](https://github.com/smashah/sulla/pull/270)
- Release 1.8.33 [`0321cd3`](https://github.com/smashah/sulla/commit/0321cd346fa7c7b28f4f794652bcb8e89dcd97b3)
- implemented onIncomingCall #261 [`334dc2b`](https://github.com/smashah/sulla/commit/334dc2ba8faa32e1056c81b9fdab9e18e3da9248)
- updated readme [`d7a2476`](https://github.com/smashah/sulla/commit/d7a24763a57560d1f31b54c4c3a3759ffeb877dc)
- logo fix [`e46bd11`](https://github.com/smashah/sulla/commit/e46bd11fc0b2ffa120a7994b847af7b2b28ecc16)
- added logo in readme [`d654f0b`](https://github.com/smashah/sulla/commit/d654f0b0ed16068ed6cd90f3aed4fca445258641)

**Comment by smashah** [comment]
@itzharDev you can now use `client.onIncomingCall`

https://smashah.github.io/sulla/classes/whatsapp.html#onincomingcall

Here's the call object interface: https://github.com/smashah/sulla/blob/master/src/api/model/call.ts
`peerJid` is the number of the caller.

`client.onIncomingCall(call=>console.log('newcall',call));`

Let me know if this works for you. There may be a solution to rejecting the call but its a slim chance.

Thanks

**Comment by tinyCoder32** [comment]
Thank you so much, Is there a way to reject the incoming call please?

**Comment by smashah** [comment]
@tinyCoder32 not right yet maybe in the future.

**Comment by smashah** [comment]
This is tested so closing for now. Report back if there are further issues.

**Comment by smashah** [comment]
Apparently call rejection is possible now. Reopening to implement rejectCall

**Comment by malakaisbest** [comment]
I'm new to open-wa.
is there any "Easy API" parameter to detect call and send a reply to the caller?

**Comment by jesusvalverde** [comment]
A reply as a text...yes

 client.onIncomingCall(call => { 
  client.sendText(call.peerJid, 'Lo sentimos, pero no podemos atender su llamada, por favor envienos un audio o un mensaje con su consulta');  
; });

**Comment by malakaisbest** [comment]
> A reply as a text...yes
> 
> client.onIncomingCall(call => {
> client.sendText(call.peerJid, 'Lo sentimos, pero no podemos atender su llamada, por favor envienos un audio o un mensaje con su consulta');
> ; });

thank you for the reply.
but I'm using the open-wa webhook method to get messages to my system.
`npx @open-wa/wa-automate -w 'https://my.domain.com/7a00ac21-60f2-411e-a571-515b37b2025a'`
like this.
i trying to find any parameter to handle "Incoming Call"..
or is there any place to input that code.?

**Comment by smashah** [comment]
@malakaisbest If I'm understanding you correctly, it looks like you need some sort of automatic call response message - where you can set a flag with a default message to send to a number that is trying to call you - which is not a feature yet, but it can be.

Would something like this work for you?

```bash
> npx @open-wa/wa-automate -w 'https://my.domain.com/7a00ac21-60f2-411e-a571-515b37b2025a' --on-cal "Please do not call this number"
```

**Comment by malakaisbest** [comment]
yes absolutely.

**Comment by smashah** [comment]
@malakaisbest great idea. I implement that now.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci minor`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.3.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.2.2...4.3.0) (2021-06-10)

- Release 4.3.0 [`1ded4f8`](https://github.com/open-wa/wa-automate-nodejs/commit/1ded4f878c5de30697ce601ab0af0aa9d75c3c04)
- ✨ feat [CLI]: `--on-call` default call response message #261 [`e66cc93`](https://github.com/open-wa/wa-automate-nodejs/commit/e66cc9326f712fe1d3e93ab493e2aea540896349)
- 🏷️  fix missing types on listeners [`a92a6a0`](https://github.com/open-wa/wa-automate-nodejs/commit/a92a6a084f6d560f977b17907d5ca9f2a40bf557)
- 🏷️  fix `Call` type [`a187006`](https://github.com/open-wa/wa-automate-nodejs/commit/a187006e31856a20ce31f51ad1171fe999a481e9)

**Comment by smashah** [comment]
@malakaisbest 

Please update your local npx cache and try it out!

```
> npm i @open-wa/wa-automate@latest
> npx @open-wa/wa-automate -w 'https://my.domain.com/7a00ac21-60f2-411e-a571-515b37b2025a' --on-call "Please do not call this number"
```

**Comment by malakaisbest** [comment]
> @malakaisbest
> 
> Please update your local npx cache and try it out!
> 
> ```
> > npm i @open-wa/wa-automate@latest
> > npx @open-wa/wa-automate -w 'https://my.domain.com/7a00ac21-60f2-411e-a571-515b37b2025a' --on-call "Please do not call this number"
> ```

I updated it.and it's working fine..
thank you very much :D :D :100:  


just idea ~~ if there is any way to decline the call.it will be a good feature...

**Comment by smashah** [comment]
> > @malakaisbest
> > Please update your local npx cache and try it out!
> > ```
> > > npm i @open-wa/wa-automate@latest
> > > npx @open-wa/wa-automate -w 'https://my.domain.com/7a00ac21-60f2-411e-a571-515b37b2025a' --on-call "Please do not call this number"
> > ```
> 
> I updated it.and it's working fine..
> thank you very much :D :D 💯
> 
> just idea ~~ if there is any way to decline the call.it will be a good feature...

Yes. That's the reason this issue is opened actually.

**Comment by malakaisbest** [comment]
> npm i @open-wa/wa-automate@latest

this code works fine and WA_AUTOMATE_VERSION is 4.3.1

then I run `docker-compose up --build` and its WA_AUTOMATE_VERSION is still 4.2.2.
I already run ` docker pull openwa/wa-automate:latest` but it did not change anything.

I followed this instruction
https://github.com/open-wa/wa-automate-docker

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci minor`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.4.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.3.1...4.4.0) (2021-06-10)

- Release 4.4.0 [`eb2d49a`](https://github.com/open-wa/wa-automate-nodejs/commit/eb2d49ac6983212b91d39e94a875dd5450a59da9)
- ✨ feat: `client.autoReject()` #261 [`3d45928`](https://github.com/open-wa/wa-automate-nodejs/commit/3d45928fe353d8a6040ce15bef246159e7ca9ebe)
- ✨ feat [CLI]: Automatic call rejection `--auto-reject` #261 [`8d044c1`](https://github.com/open-wa/wa-automate-nodejs/commit/8d044c142acd86d187b2d79bbb4dc85ae802088a)

**Comment by smashah** [comment]
@malakaisbest

You can now try out local call auto-reject as part of the [Insider's Program](https://docs.openwa.dev/pages/The%20Client/licensed-features.html#keys). Please note, this will automatically reject the call from the host account device. The call from the initiator will continue to ring as if your host account device is offline. As of yet, there is nothing that can be done to remedy this.

Usage:

```javascript

...
	//just reject the call on the host account device
	await client.autoReject()

	//Reject the call and send a message to the call-initiating account.
	await client.autoReject("Please do not call this number") 

	//If you have an insider's key both will return true, else false.

...

```

CLI:

```bash
> npx @open-wa/wa-automate ... --auto-reject --on-call "Please do not call this number" 
```

Everybody in this issue above this comment will be getting a free-for-life Insider's Program license key, please DM me on discord to redeem.

For anyone else, please follow the instructions here: https://docs.openwa.dev/pages/The%20Client/licensed-features.html#keys

**Comment by malakaisbest** [comment]
> @malakaisbest
> 
> You can now try out local call auto-reject as part of the [Insider's Program](https://docs.openwa.dev/pages/The%20Client/licensed-features.html#keys). Please note, this will automatically reject the call from the host account device. The call from the initiator will continue to ring as if your host account device is offline. As of yet, there is nothing that can be done to remedy this.
> 
> Usage:
> 
> ```js
> ...
> 	//just reject the call on the host account device
> 	await client.autoReject()
> 
> 	//Reject the call and send a message to the call-initiating account.
> 	await client.autoReject("Please do not call this number") 
> 
> 	//If you have an insider's key both will return true, else false.
> 
> ...
> ```
> 
> CLI:
> 
> ```shell
> > npx @open-wa/wa-automate ... --auto-reject --on-call "Please do not call this number" 
> ```
> 
> Everybody in this issue above this comment will be getting a free-for-life Insider's Program license key, please DM me on discord to redeem.
> 
> For anyone else, please follow the instructions here: https://docs.openwa.dev/pages/The%20Client/licensed-features.html#keys

@smashah thanks for the call auto-reject function.
I updated to the 4.4.0 version. but till this function not working for me.
The caller and receiver ringing without auto rejecting the call.
how can I fix this?

**Comment by smashah** [comment]
@malakaisbest you need a license to use this feature. Please click on the discord badge in the readme and DM me on discord
