### ISSUE TITLE
Couldn't link device

### ISSUE THREAD

**Issue by ImBIOS** [open-wa/wa-automate-nodejs#2611]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

My own code

### Current Behavior

I scan the QR then the prompt on my phone screen said it cannot be linked, try again later. I tried several times, but it is the same.

### Expected Behavior

Should be logged in and linked with the bot.

### Steps To Reproduce

1. In this environment
2. With this config
3. Run the bot like normal
4. And boom! the error popped out.

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2210.9",
  "WA_AUTOMATE_VERSION": "4.33.1",
  "BROWSER_VERSION": "HeadlessChrome/98.0.4758.106",
  "START_TS": 1648824439734,
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Linux 5.10
- Node: 17.8.0
- npm: 8.5.5
```

**Comment by smashah** [comment]
Please add more information or all, your logs, screenshots and your config to reopen this issue.
