### ISSUE TITLE
How can I use it with Next.js Serverless API routes

### ISSUE THREAD

**Issue by max-programming** [open-wa/wa-automate-nodejs#2612]
## Question

I wanna use this amazing library with Next.js's [serverless API routes](https://nextjs.org/docs/api-routes/introduction). But to use Puppteer there I have to use `chrome-aws-lambda` stuff. So in what way can I use this library with API routes because puppeteer is predefined here

**Comment by gnadelwartz** [comment]
You can use wa-automate API server https://docs.openwa.dev/pages/Getting%20Started/quick-run.html

**Comment by max-programming** [comment]
@gnadelwartz Yes but that starts a separate nodejs API. And I have to deploy it somewhere else in order to get it up and running for production.

**Comment by smashah** [comment]
thanks @max-programming Due to the nature of the sessions being long-lived, you cannot really run them in a "serverless" environment. I suggest deploying it on a DO droplet using the link in the readme
