### ISSUE TITLE
Mention doesn't always work

### ISSUE THREAD

**Issue by shifoc** [open-wa/wa-automate-nodejs#2613]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Steps To Reproduce

await client.sendTextWithMentions(message.from, "1234567@c.us", message.id);

sometimes the mention does not work and it sends it as a text instead (it's usually the first time I use this feature that it happens)

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2210.9",
  "WA_AUTOMATE_VERSION": "4.33.1",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4896.60",
  "START_TS": 1648840268222,
  "LATEST_VERSION": true,
  "CLI": false,
  "LAUNCH_TIME_MS": 66168,
  "ACC_TYPE": "BUSINESS",
  "chats": 80,
  "messages": 164,
  "contacts": 489,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "670a4151-988d-4f8f-9e26-2fbf8f9a2315"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.13.1
- npm: 8.3.0
```

**Comment by smashah** [comment]
hi try now

**Comment by shifoc** [comment]
Thank you, it works now!
