### ISSUE TITLE
first messages come in ciphertext type

### ISSUE THREAD

**Issue by yasin1913** [open-wa/wa-automate-nodejs#2616]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Steps To Reproduce

I used to fix this problem by pulling it again with this method after a while after the message came.
getMessageById()
After going through multi device, I couldn't fix it with this method. The encrypted message keeps coming back to me.

### create() code

```markdown
create({
    multiDevice: true,
    blockCrashLogs: true,
    disableSpins: true,
    logConsole: false,
    useChrome: true,
    sessionId: SESSION_ID,
    headless: true,
    licenseKey: LICENSE_KEY
})
```

### DEBUG INFO

```markdown
Debug info: {                                                            
  "WA_VERSION": "2.2210.9",                                                
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X    
  "WA_AUTOMATE_VERSION": "4.33.1",                                         
  "BROWSER_VERSION": "HeadlessChrome/90.0.4430.93",                        
  "OS": "Linux 5.4",                                                       
  "START_TS": 1648979858297                                                
}
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: 16.14.2
- npm: 8.6.0
```

**Comment by smashah** [comment]
https://faq.whatsapp.com/general/security-and-privacy/seeing-waiting-for-this-message-check-your-phone?lang=en

**Comment by smashah** [comment]
https://github.com/open-wa/wa-automate-nodejs/issues/2278

**Comment by smashah** [comment]
![image](https://user-images.githubusercontent.com/5903821/162070924-dbbeb354-ce93-437c-abfd-79959c76afe0.png)

**Comment by smashah** [comment]
![CleanShot 2022-04-06 at 22 06 42@2x](https://user-images.githubusercontent.com/5903821/162071058-47c86500-c172-460e-92b6-13742ceb6e1f.png)

**Comment by smashah** [comment]
@yasin1913 There's no solution to this as far as i can tell right now.
