### ISSUE TITLE
Session.data.json not getting updated while using multidevice method

### ISSUE THREAD

**Issue by adgamerx** [open-wa/wa-automate-nodejs#2617]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

When I try to login to open-wa client using the multidevice option set to true. It's not updating the session.data.json file and even the login is required after every 10-20 minute or whenever I try to re-run the code again.

### Expected Behavior

It should update the session.data.json file and the client should be logged in until disconnected from the app or the code.

### Steps To Reproduce

1. Create account in Whatsapp Business
2. This only works if your account is forced to opt-in for multidevice support
3. Try to log in with your code using ```node app.js```
4. Terminate the session and try to run again the code using the same command ```node app.js```
5. It'll ask you again to login using qr scan

### create() code

```markdown
authTimeout: 3600, //wait only 60 seconds to get a connection with the host account device
  blockCrashLogs: true,
  // useChrome: true,
  disableSpins: true,
  headless: true,
  hostNotificationLang: "PT_BR",
  logConsole: false,
  popup: true,
  multiDevice: true,    
  // executablePath: '/app/.apt/usr/bin/google-chrome',
  qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
```

### DEBUG INFO

```markdown
"WA_VERSION": "2.2210.9",
"PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
"WA_AUTOMATE_VERSION": "4.33.1",
"BROWSER_VERSION": "HeadlessChrome/100.0.4889.0",
"OS": "Linux 4.4",
"START_TS": 1648991886237
```

### Environment

```markdown
- OS: win 11
- Node: v17.4.0
- npm: 8.3.1
```

**Comment by smashah** [comment]
The session.data.json file merely acts as a placeholder in multi device sessions and the base64 within it represents an empty object when decoded.

Keep the session alive for a few minutes, send a few messages back and forth and then you will be able to reauthenticate back into the session upon restart without re-scanning.
