### ISSUE TITLE
API getBusinessProfilesProducts no data

### ISSUE THREAD

**Issue by trcalgaro** [open-wa/wa-automate-nodejs#2619]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

When executing the "getBusinessProfilesProducts" API call, product data is not returned.

### Expected Behavior

Json returning the data of the registered products

### Steps To Reproduce

1. https://xxxxxxxxxxxx/api-docs/#/default/post_getBusinessProfilesProducts
2. `{
  "args": {
    "id": "xxxxxxxxxxx@c.us"
  }
}`
3. Execute
4. `{
  "success": true,
  "response": false
}`

### create() code

```markdown
curl -X 'POST' \
  'https://xxxxxxxxxxxxxxxxxx/getBusinessProfilesProducts' \
  -H 'accept: */*' \
  -H 'api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxx' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": {
    "id": "xxxxxxxxxxxxxxxxx@c.us"
  }
}'
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2210.9",
  "WA_AUTOMATE_VERSION": "4.33.2",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4889.0",
  "START_TS": 1649029163570,
  "LATEST_VERSION": true,
  "CLI": true,
  "LAUNCH_TIME_MS": 23119,
  "ACC_TYPE": "BUSINESS",
  "chats": 1,
  "messages": 1,
  "contacts": 361,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "05ff3a8b-4d37-4855-a97a-c9c15915c08e"
}
```

### Environment

```markdown
- OS: Windows Server 2019
- Node: 17.8.0
- npm: 8.6.0
```

### Screenshots/Logs

API

### Anything else?

Data did not return after the last update

**Comment by smashah** [comment]
@trcalgaro I just tested this and it's working fine here.

Can you try and see if it works with a personal host account instead please? Maybe this issue is isolated to MD business accounts.

**Comment by trcalgaro** [comment]
> @trcalgaro I just tested this and it's working fine here.
> 
> Can you try and see if it works with a personal host account instead please? Maybe this issue is isolated to MD business accounts.

Please close the issue, I was calling the wrong host! sorry
