### ISSUE TITLE
Button: can't reply users msg. Result false

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#2620]
![image](https://user-images.githubusercontent.com/18587059/161580751-55e36273-55fe-4f22-ae0e-be6e740e06b9.png)

**Comment by trcalgaro** [comment]
How to arrange the buttons side by side? all the ones I made were one below the other!

**Comment by smashah** [comment]
@trcalgaro two buttons get arranged side by side usually.

**Comment by smashah** [comment]
fixed with patches.
