### ISSUE TITLE
 cli: when a new chat is initiated using chatwoot response open a new conversation #2570

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#2621]
#2570 problem persists. Two subsequent messages received generate two conversations as below:

<img width="488" alt="Captura de Tela 2022-04-04 às 23 43 58" src="https://user-images.githubusercontent.com/12688324/161669353-94a13138-8fa0-42de-b3dc-c433e8c3a508.png">

**Comment by smashah** [comment]
@silvaartur did you try this on a completely fresh instance of chatwoot?

**Comment by smashah** [comment]
if you give me replication steps from a fresh instance then i can try to resolve this but im not able to replicate it with zero detail

**Comment by smashah** [comment]
Please check this code and see what the fix can be for your situation:

https://github.com/open-wa/wa-automate-nodejs/blob/master/src/cli/integrations/chatwoot.ts
