### ISSUE TITLE
Error on SendlistMessage

### ISSUE THREAD

**Issue by trcalgaro** [open-wa/wa-automate-nodejs#2623]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Steps To Reproduce

1. On request Easy API /sendListMessage
2. Request  `curl -X 'POST' \
  'https://xxxxxxxxxxxxxxxxxxxxxxxx/sendListMessage' \
  -H 'accept: */*' \
  -H 'api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": {
    "to": "xxxxxxxxxx@c.us",
    "sections": ["Agua","Vinho"],
    "title": "Titulo",
    "description": "Descrição",
    "actionText": "Texto da ação"
  }
}'`
3. Run Request
4. Receive "False positive" `{
  "success": true,
  "response": "true_xxxxxxxxxxxxx@c.us_AWYQ1ZHXCK4ANEPKZ9YR"
}`
![image](https://user-images.githubusercontent.com/41573074/161671102-48ec5649-d10d-4f71-81ed-edf456260cc3.png)
![image](https://user-images.githubusercontent.com/41573074/161671159-ce4f6fe0-0234-4bd4-bc03-240effd42148.png)
No Selections Visible

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2210.9",
  "WA_AUTOMATE_VERSION": "4.33.2",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4889.0",
  "START_TS": 1649127159426,
  "LATEST_VERSION": true,
  "CLI": true,
  "LAUNCH_TIME_MS": 22986,
  "ACC_TYPE": "BUSINESS",
  "chats": 1,
  "messages": 15,
  "contacts": 361,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "c45ca9f1-1462-4840-8f75-3fd1105742e3"
}
```

### Environment

```markdown
- OS: Windows Server 2019
- Node: 17.8.0
- npm: 8.6.0
```

**Comment by smashah** [comment]
@trcalgaro a section is an array of rows, not strings. Please read the docs:

https://docs.openwa.dev/interfaces/api_model_button.Section.html
