### ISSUE TITLE
[Bug] tagEveryone formatting

### ISSUE THREAD

**Issue by t0g3pii** [open-wa/wa-automate-nodejs#2625]
hideTags true
formatting set produces text with no Tags (as it should)

What about ignore formatting when hideTags true?

![Screenshot_20220405-105144_WhatsApp.jpg](https://user-images.githubusercontent.com/49153387/161717794-f1ea7d8a-9ff7-4a87-b9a2-58cec6e3296d.jpg)

**Comment by smashah** [comment]
fixed
