### ISSUE TITLE
[Suggestion] client.openChat(chatId) || client.getSnapshot(chatId)

### ISSUE THREAD

**Issue by t0g3pii** [open-wa/wa-automate-nodejs#2626]

**Comment by smashah** [comment]
?

getSnapshot already exists 
https://docs.openwa.dev/classes/api_Client.Client.html#getSnapshot

What will openChat do?

**Comment by t0g3pii** [comment]
> getSnapshot already exists 
> https://docs.openwa.dev/classes/api_Client.Client.html#getSnapshot but not for a specific chat id. I was in the middle of developing it a while ago. I'll see if I saved that code anywhere
> 
> What will openChat do?

Just open the Chat in Chrome so we can use getSnapshot :P

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.34.2](https://github.com/open-wa/wa-automate-nodejs/compare/4.34.1...4.34.2) (2022-04-10)

- Release 4.34.2 [`e053060`](https://github.com/open-wa/wa-automate-nodejs/commit/e0530603460762d4ec0a6129424fd5dc3c3d91f2)
- ✨ feat: `getSnapshot` can now take chatId param #2626 [`447a21d`](https://github.com/open-wa/wa-automate-nodejs/commit/447a21d58826cdca030039f6fc700ea9646c1ce8)
- 🥚 patches update [`eec6aee`](https://github.com/open-wa/wa-automate-nodejs/commit/eec6aee8fff5b59c819a15b1d34345bf7cd8e4c5)
- 🥚 patches update [`b382e45`](https://github.com/open-wa/wa-automate-nodejs/commit/b382e45d14d2a3b1234e0f714248e6f83c79a0b3)
- 🥚 patches update [`b6cec55`](https://github.com/open-wa/wa-automate-nodejs/commit/b6cec55969643e09d70a5cae404eb198a410a64e)
- updated types-only package [`5b048be`](https://github.com/open-wa/wa-automate-nodejs/commit/5b048be01a5f7974c0055cb429af39d1c7fccabc)

**Comment by smashah** [comment]
https://docs.openwa.dev/classes/api_Client.Client.html#getSnapshot
