### ISSUE TITLE
middleware -> error Error: Evaluation failed: TypeError: _0x159165[(_0x32005d(...) + "lud" + "es")] is not a function

### ISSUE THREAD

**Issue by xerxesb** [open-wa/wa-automate-nodejs#2628]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

I have a Google Apps script that uses a timed interval (daily) to send a WhatsApp message to a group, if a business rule meets a certain criteria. I have a message that (if it meets the business rule criteria) will be sent to the WA group at At 8pm local time. This event is not sent every day, only if certain conditions are met.

The last few times that this condition has been met, the WA interface has failed to send the message, even though it is successfully able to send other messages at other times of the day.

### Steps To Reproduce

1. I use the wa-automate-docker instance to manage the lifecycle of the app.
2. I POST to the `sendText` endpoint with my message.

I can see the following error emitted to the console at the time:
```
middleware -> error Error: Evaluation failed: TypeError: _0x159165[(_0x32005d(...) + "lud" + "es")] is not a function
    at Object.window.<computed>.<computed> [as sendMessage] (__puppeteer_evaluation_script__:1:261658)
    at __puppeteer_evaluation_script__:3:29
    at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
```

### DEBUG INFO

```markdown
- DEBUG - flags: {"sessionId":"session","popup":true,"executablePath":"/usr/bin/google-chrome-stable","useChrome":true,"disableSpins":true,"port":8080,"inDocker":true,"qrTimeout":0,"debug":true,"multiDevice":true,"noApi":fals
e,"host":"localhost","verbose":false,"ef":["qr","STARTUP","MD_DETECT"],"allowSessionDataWh":false,"generateApiDocs":true,"sessionDataOnly":false,"skipSavePostmanCollection":false,"headful":false,"preAuthDocs":false,"stats":fa
lse,"noKillOnLogout":false,"cors":false,"socket":false,"emitUnread":false}
- DEBUG - env vars: {"WA_POPUP":"true","WA_EXECUTABLE_PATH":"/usr/bin/google-chrome-stable","WA_USE_CHROME":"true","WA_DISABLE_SPINS":"true","WA_PORT":"8080"}
```

### Environment

```markdown
- OS: wa-automate-docker
- Node: 
- npm:
```

**Comment by smashah** [comment]
There's something wrong the ID in your request.

**Comment by smashah** [comment]
@xerxesb It should respond with an error if the type of the ID is wrong

**Comment by xerxesb** [comment]
Thanks for your reply @smashah. I'm not sure what you're referring to when you mention the `ID`?

Here's the code I use in my Google Apps Script to post to the WA server. There's no mention of an ID anywhere.
```js
function sendText(content, group_id = WA_GROUP_ID) {
  var payload = {
    "args": {
      "to": group_id,
      "content": content
    }
  }

  var options = {
    'method' : 'post',
    'contentType': 'application/json',
    'payload' : JSON.stringify(payload)
  };
  let response = UrlFetchApp.fetch(WA_SERVER_ENDPOINT + '/sendText', options);
  rawLog_(response.getContentText());  
}
```

**Comment by smashah** [comment]
@xerxesb Can you log `group_id` please.

**Comment by xerxesb** [comment]
Indeed the `group_id` contained incorrect information. 

It looks like the different trigger source in my app was causing the issue. I've since identified and fixed it. Sorry for the mix-up. 

For future use cases, I wonder if it's possible to validate the `group_id` that gets posted to the server to ensure it meets criteria and respond with a different error if it fails.

**Comment by smashah** [comment]
@xerxesb I pushed a new patch the other day to check the type of the chat ID before attempting to send the message.
