### ISSUE TITLE
tagEveryone with hideTags true, no mention notification

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#2631]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

Before patch update it's work normally, after patch update no mention notification on chat.

### Expected Behavior

mention notification like this

![image](https://user-images.githubusercontent.com/18587059/162127232-ca6a56ce-61a7-424d-8a3b-6ad0fb3947c6.png)

### Steps To Reproduce

run the script

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2210.9",
  "WA_AUTOMATE_VERSION": "4.33.2",
  "BROWSER_VERSION": "HeadlessChrome/99.0.4844.84",
  "START_TS": 1649309129487,
  "LATEST_VERSION": true,
  "CLI": false,
  "LAUNCH_TIME_MS": 28803,
  "ACC_TYPE": "BUSINESS",
  "chats": 34,
  "messages": 61,
  "contacts": 1171,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "53c9040a-8c0d-4310-9de6-5166136197db"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.13.2
- npm: 8.2.0
```

**Comment by smashah** [comment]
try now
