### ISSUE TITLE
Error sendRawWebpAsSticker

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#2633]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

Found error when I try this webp [here](https://drive.google.com/file/d/17AHcFp75mEyezB8yC19PzP1Q7OxSdZoH/view?usp=sharing). I don't know why.

### Expected Behavior

send webp sticker normally

### Steps To Reproduce

run the script

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2210.9",
  "WA_AUTOMATE_VERSION": "4.33.3 UPDATE AVAILABLE: 4.33.4",
  "BROWSER_VERSION": "HeadlessChrome/99.0.4844.84",
  "START_TS": 1649354097511,
  "LATEST_VERSION": false,
  "CLI": false,
  "LAUNCH_TIME_MS": 24121,
  "ACC_TYPE": "BUSINESS",
  "chats": 34,
  "messages": 50,
  "contacts": 1153,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "880376eb-5336-437f-89eb-6bc8aa47b489"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.13.2
- npm: 8.2.0
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/18587059/162267783-91285c3c-88ca-4f4b-b720-abb5c04eaf0c.png)

Error: Evaluation failed: a
    at ExecutionContext._evaluateInternal (C:\laragon\www\wabot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\laragon\www\wabot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)

**Comment by dandyraka** [comment]
Update: 

Maybe because filesize.
The original webp is **1MB**, when I try to optimize using ezgif.com [here](https://ezgif.com/optiwebp) and the filesize become **615KB** it work no error.

**Comment by smashah** [comment]
I think this is due to the encoding of the file?

it comes up as a `data:image/octet-stream;`. I'll try to carve out some sort of workaround for this in the meantime. But yeah, best to keep stickers under 1mb. Do some compression. Also, `sendImageAsSticker` does this for you even on webp files - it also encodes the image properly.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.33.6](https://github.com/open-wa/wa-automate-nodejs/compare/4.33.5...4.33.6) (2022-04-08)

- Release 4.33.6 [`88d8b21`](https://github.com/open-wa/wa-automate-nodejs/commit/88d8b216f774b1b12f18150f3072420c65bd15a8)
- 💫 add support for raw webp encoded as octet-streams #2633 [`d692421`](https://github.com/open-wa/wa-automate-nodejs/commit/d69242166ca483043523c680b1ffeea055d8572b)
- 🥚 patches update [`bb52c30`](https://github.com/open-wa/wa-automate-nodejs/commit/bb52c3099b7344029a4edf6c0fadbd1d66e71fc0)
- 🥚 patches update [`0e779bd`](https://github.com/open-wa/wa-automate-nodejs/commit/0e779bd7c566b66a6d56a1848f1a3d2b52608b6d)
- 🥚 patches update [`05f3371`](https://github.com/open-wa/wa-automate-nodejs/commit/05f3371656ef2f8866dc37a20aa78711821939f1)
- updated types-only package [`52ac175`](https://github.com/open-wa/wa-automate-nodejs/commit/52ac175c78a897bc4440d43412ad250e3dcb2dd0)

**Comment by dandyraka** [comment]
@smashah 

Still same error (open-wa v4.33.7), I check the mimetype is `image/webp`
![image](https://user-images.githubusercontent.com/18587059/162380247-b483fb9a-c8f1-4278-96ee-be627a76d68c.png)

and when I use `sendImageAsSticker` show error like this, maybe because it's animated webp.
![image](https://user-images.githubusercontent.com/18587059/162380514-c1a19929-4bf7-4804-9bb5-f9b62f0041ac.png)

How to compress animated webp?

**Comment by dandyraka** [comment]
I test like this, send as document not image
![image](https://user-images.githubusercontent.com/18587059/162381077-4573d3f7-3160-4b2c-a941-28c69c512702.png)

**Comment by dandyraka** [comment]
Solve with sharp 
![image](https://user-images.githubusercontent.com/18587059/162391030-613c1d49-20bb-40a9-8c3f-72d52473bc65.png)
