### ISSUE TITLE
forwardMessages does not return sent messages' id

### ISSUE THREAD

**Issue by powerbling** [open-wa/wa-automate-nodejs#2649]
### Are you using the latest version of the library?

- [x] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

When forwarding a message to another chat I get an empty array on `forwardMessages()` returned promise.

### Expected Behavior

I expect, as said in the documentation, a whole `MessageId` array passed on to the promise.

### Steps To Reproduce

On listed environment, run the create code and the start function:
```node
function start (client) {
    var chatName = "Forwarded Messages";
    var chatInfo = {};

    // Get the group chat managed by bot or create a new one
    client.getAllGroups()
        .then(groups => {
            let chat = groups.find(g => g.name === chatName);
            if (!chat) {
                client.createGroup(chatName, [])
                    .then(g => {
                        chatInfo.id = g.wid._serialized;
                    });
            } else {
                chatInfo.id = chat.groupMetadata.id;
            }
        })

    client.onMessage(async message => {
        if (chatInfo) {

            client.forwardMessages(
                chatInfo.id,
                [message.id]
            ).then((msgId) => {
                console.log("Sent message:");
                console.log(msgId)
            }).catch((err) => console.error(err))

        }
    })
}
```
When the message is received the output looks like this:
```
Sent message:
[]
```
and does not contain the supposed MessageId[].
It does not raise any errors and forwards correctly.

### create() code

```markdown
wa.create({
    sessionId: "Textify",
    multiDevice: true,
    headless: true,
    // logConsole: true,

}).then(client => start(client));
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2212.5",
  "WA_AUTOMATE_VERSION": "4.34.4",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4889.0",
22: 1649667324240,
  "LATEST_VERSION": true,
  "CLI": false,
  "LAUNCH_TIME_MS": 41467,
  "ACC_TYPE": "PERSONAL",
  "chats": 136,
  "messages": 159,
  "contacts": 708,
  "isMd": true,
  "INSTANCE_ID": "f08335ca-198b-4310-ad5a-f406e91e97e3"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 17.9.0
- npm: 7.23.0
```

**Comment by smashah** [comment]
patched. restart and try again.
