### ISSUE TITLE
client.sendButtons is not sending anything

### ISSUE THREAD

**Issue by sayanavr** [open-wa/wa-automate-nodejs#2655]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

The line await globalClient.sendButtons(msgFrom, "Body", [
    {
        id: "1",
        "text": "Click"
    },
    {
        id: "1",
        "text": "Call"
    },
    {
        id: "1",
        "text": "Open Link"
    }
], "title", "footer") is not executing or not responding to user. But globalClient.sendText(msgFrom,msg) seems to be working fine. Also shows no error.

### Expected Behavior

I expected buttons that I am sending to appear for the user.

### Steps To Reproduce

await globalClient.sendButtons(msgFrom, "Body", [
    {
        id: "1",
        "text": "Click"
    },
    {
        id: "1",
        "text": "Call"
    },
    {
        id: "1",
        "text": "Open Link"
    }
], "title", "footer") 
No error is shown.

### create() code

```markdown
wa.create({
  multiDevice: true,
}
)
.then(async client => await start(client)).
catch(err => {
  console.log(err)
});
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2212.5",
  "WA_AUTOMATE_VERSION": "4.35.3",
  "BROWSER_VERSION": "HeadlessChrome/80.0.3987.0",
  "START_TS": 1649780518997,
  "LATEST_VERSION": true,
  "CLI": false,
  "LAUNCH_TIME_MS": 71430,
  "ACC_TYPE": "BUSINESS",
  "chats": 89,
  "messages": 126,
  "contacts": 96,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "f5b244ce-9216-4548-830b-0eed1d7e71ac"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.13.2
- npm: 8.1.2
```

**Comment by smashah** [comment]
@sayanavr Please read the docs :

https://docs.openwa.dev/classes/api_Client.Client.html#sendButtons

You need to add the header and footer params at the end. Also, MD sessions require an insider's license to access buttons

```js
await client.sendButtons(id, "Body", [
{
id: "1",
"text": "Click"
},
{
id: "2",
"text": "Call"
},
{
id: "3",
"text": "Open Link"
}],"header","footer")
```
