### ISSUE TITLE
ERROR: 'Failed to load resource: the server responded with a status of 403 ()

### ISSUE THREAD

**Issue by allanlisboa** [open-wa/wa-automate-nodejs#2659]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

![Captura de Tela 2022-04-13 às 21 47 30](https://user-images.githubusercontent.com/37181884/163292487-acefe8ea-c6d5-4d5a-bcfe-6d59935e4ab4.png)

### Steps To Reproduce

when sending a message to the client we get the above error

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2212.7",
  "WA_AUTOMATE_VERSION": "4.35.3",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4896.75",
  "START_TS": 1649897219781,
  "LATEST_VERSION": true,
  "CLI": false,
  "LAUNCH_TIME_MS": 15212,
  "ACC_TYPE": "BUSINESS",
  "chats": 58,
  "messages": 68,
  "contacts": 155,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "ab92559a-4c22-4b4d-abbc-22fbb5386d03"
}
```

### Environment

```markdown
- OS: macOS Big Sur
- Node: 16.13.1
- npm: 8.1.2
```

**Comment by smashah** [comment]
> when sending a message to the client we get the above error

What message?

Please share the exact request you are sending that results in this error.

Till then closing.
