### ISSUE TITLE
Buttons not working in WA Bussiness MD

### ISSUE THREAD

**Issue by ariona** [open-wa/wa-automate-nodejs#2668]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

Can not send buttons message, the message shown on WA Web is `Click here to update.`

### Expected Behavior

Chat buttons send to user with specified params

### Steps To Reproduce

1. Launch my own script with `headless` set to `false` and `useChrome` set to true
2. On Google Chrome console, try sending button messages, e.g ```await WAPI.sendButtons('623424234223@c.us','testing',[{id:"1",text:"test"}],'title','footer')```
3. On console it return `true_623424234223@c.us_ZTESL1GREMYHEOG93QKG`
4. But on WA Web, the message is not sent, an only showing `Click here to update` on message body

### create() code OR full CLI command + CONFIG

```markdown
wa.create({
  licenseKey: "8B7C9890-XXXXXX-XXXXXX-54CC9D27",
  sessionId: "COVID_HELPER",
  multiDevice: true, //required to enable multiDevice support
  authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
  blockCrashLogs: true,
  disableSpins: true,
  headless: false,
  hostNotificationLang: 'PT_BR',
  logConsole: false,
  popup: true,
  useChrome: true,
  qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
}).then(client => start(client));
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2212.8",
  "WA_AUTOMATE_VERSION": "4.35.6 UPDATE AVAILABLE: 4.35.8",
  "BROWSER_VERSION": "Chrome/100.0.4896.127",
  "START_TS": 1650467253484,
  "RAM_INFO": "Total: 8.59 GB | Free: 0.92 GB",
  "LATEST_VERSION": false,
  "CLI": false,
  "LAUNCH_TIME_MS": 35905,
  "ACC_TYPE": "BUSINESS",
  "chats": 256,
  "messages": 125,
  "contacts": 564,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "72340dd4-a58f-4a73-a8ff-fb37be3713e2"
}
```

### Environment

```markdown
- OS: macOS Monterey
- Node: 16.13.1
- npm: 8.1.2
```

### Screenshots/Logs

<img width="265" alt="Screen Shot 2022-04-20 at 22 42 02" src="https://user-images.githubusercontent.com/752483/164269900-eeb13a1f-3565-4145-a67e-4ee56fb7b7c8.png">

**Comment by smashah** [comment]
closing as we discussed this already and it is working
