### ISSUE TITLE
[Request] Add `mentions` argument in `sendTextWithMentions`

### ISSUE THREAD

**Issue by BbayuGt** [open-wa/wa-automate-nodejs#2670]
Allowing custom number to get hideTagged on sendTextWithMentions
```ts
sendTextWithMentions(to: ChatId, content: Content, hideTags?: boolean, mentions: ChatId[]): Promise<boolean | MessageId>
```

# Usage
```ts
sendTextWithMentions(from, "Hello @12345!", true, ["12345@c.us", "12341@c.us"]) // 12341 will hide tagged, while 12345 will appear like normal mentions.
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.35.9](https://github.com/open-wa/wa-automate-nodejs/compare/4.35.8...4.35.9) (2022-04-21)

- Release 4.35.9 [`49a1d5e`](https://github.com/open-wa/wa-automate-nodejs/commit/49a1d5e5094132ccd9d79780b854229040e1235d)
- ✨ feat: added `mentions` param to `sendTextWithMentions` #2670 [`2dfdd7b`](https://github.com/open-wa/wa-automate-nodejs/commit/2dfdd7b1931417c13af99156ff99c5c3976f4684)
- 🎁 GA: `hideTags` on `sendTextWithMentions` is now GA [`c96d3e9`](https://github.com/open-wa/wa-automate-nodejs/commit/c96d3e9745130984ead2ca5aba4633e04a500a4c)
- 🥚 patches update [`2e2df32`](https://github.com/open-wa/wa-automate-nodejs/commit/2e2df327a3733d1e1a335b3f40112dfe834e1596)
- updated types-only package [`1c6ae87`](https://github.com/open-wa/wa-automate-nodejs/commit/1c6ae87c539234c6bc91e0995476c176465a3710)

**Comment by smashah** [comment]
https://docs.openwa.dev/classes/api_Client.Client.html#sendTextWithMentions

**Comment by dandyraka** [comment]
@smashah can u implement this to `sendReplyWithMentions` too? because after `clearChat` then try to `sendReplyWithMentions` always like this (just plain text, no mention).

[image](https://user-images.githubusercontent.com/18587059/167275168-8f750ba4-fbac-401b-8368-d4d51f851fd4.jpeg)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.42.1](https://github.com/open-wa/wa-automate-nodejs/compare/4.42.0...4.42.1) (2022-06-24)

- Release 4.42.1 [`b6d2721`](https://github.com/open-wa/wa-automate-nodejs/commit/b6d27217a4d4ba9bceed5190e65e1ce5d2bd6b19)
- ✨ feat: `hideTags` & `mentions` params added to `sendReplyWithMentions` #2670 [`a755ecc`](https://github.com/open-wa/wa-automate-nodejs/commit/a755ecc83dfc8d55a114cffa365857bd25b7127d)
- 🥚 patches update [`e6b745d`](https://github.com/open-wa/wa-automate-nodejs/commit/e6b745d3166283bc67b5500376d399e1603520ea)
- updated types-only package [`ab96ba9`](https://github.com/open-wa/wa-automate-nodejs/commit/ab96ba9412a7540ffec456adffac5584c7209a15)
