### ISSUE TITLE
ERROR: Not a contact.

### ISSUE THREAD

**Issue by DevSmith** [open-wa/wa-automate-nodejs#2674]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

ERROR: Not a contact.

### Steps To Reproduce

call  **sendText**
  

### create() code OR full CLI command + CONFIG

```markdown
curl -X 'POST' \
  'http://localhost:9000/sendText' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": {
    "to": "******@c.us",
    "content": "Hi This is test message to new number"
  }
}'
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2214.9",
  "WA_AUTOMATE_VERSION": "4.35.10",
  "BROWSER_VERSION": "HeadlessChrome/101.0.4950.0",
  "START_TS": 1650699526304,
  "RAM_INFO": "Total: 16 GB | Free: 10.71 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": true
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 17.3.0
- npm: 8.3.0
```

**Comment by smashah** [comment]
@DevSmith you need a restricted license to start messages with unknown/new numbers.
