### ISSUE TITLE
Not sending contacts

### ISSUE THREAD

**Issue by thehecht** [open-wa/wa-automate-nodejs#2677]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

This request:
`curl --location --request POST 'localhost:8000/sendContact' \
--header 'Content-Type: application/json' \
--header 'key: CHzIt9fqJC' \
--header 'Cookie: session=rr7d7KQ1un%2BaQRwOtcI%2F8hdfjkFZIR%2Ft72dCuJ26uYD%2Bj7Bva1GF4OVjaBcq24EPHD0rU1tXaEaqBdt%2FFUZv%2FPkebn5H0ghX%2FwC4aZgwn3BTEO6dbhkSEKB0Q%2F40UCJ1JSgiMX3QuMBz7H3HGl6D--cxHyUiUNENxQcYdF--fgS5hksSa86SLsjU2DLWlw%3D%3D' \
--data-raw '{
    "args": {
        "to": "5516981819482@c.us",
        "contactId": "5516981819482@c.us"
    }
}'`

Is crashing and returning:
`{
    "success": false,
    "error": {
        "name": "Error",
        "message": "Evaluation failed: TypeError: e.isGroup is not a function\n    at t.MessageSendPerfReporter._cacheGroupMetadata (https://web.whatsapp.com/bootstrap_qr.b037bf792031d950b323.js:55:105148)\n    at new t.MessageSendPerfReporter (https://web.whatsapp.com/bootstrap_qr.b037bf792031d950b323.js:55:102140)\n    at https://web.whatsapp.com/bootstrap_qr.b037bf792031d950b323.js:5:450112\n    at W (https://web.whatsapp.com/bootstrap_qr.b037bf792031d950b323.js:5:274524)\n    at MutationObserver.x (https://web.whatsapp.com/bootstrap_qr.b037bf792031d950b323.js:5:271101)"
    }
}`

### Expected Behavior

Expected that it would send a Contact.

### Steps To Reproduce

1. Start Easy Cli
2. Use postman sendContact api with a controlled whatsapp number

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2214.9",
  "WA_AUTOMATE_VERSION": "4.35.10",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4889.0",
  "START_TS": 1650776783421,
  "RAM_INFO": "Total: 17.18 GB | Free: 0.52 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": true,
  "LAUNCH_TIME_MS": 19234,
  "ACC_TYPE": "BUSINESS",
  "chats": 3,
  "messages": 11,
  "contacts": 370,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "0566d029-b1ff-403d-855b-438fe08fbaf6"
}
```

### Environment

```markdown
- OS: macOS Monterey
- Node: 16.0.0
- npm: 7.20.5
```

**Comment by anandsork** [comment]
Same issue..  (I am using personal WA.)
Seems to do with latest WA changes.  ( I have same Web WA Version , 2.2214.9)

**Comment by thehecht** [comment]
Yes... it started precisely after WA roll out of multi-devices outside beta.

**Comment by smashah** [comment]
thanks for the clear issue reproduction steps. should be patched now
