### ISSUE TITLE
whatsapp button not send 

### ISSUE THREAD

**Issue by nabil-cpu** [open-wa/wa-automate-nodejs#2681]
anyone can help me why open - wa not send massage button

![WhatsApp Image 2022-04-26 at 22 48 52](https://user-images.githubusercontent.com/64117179/165347542-deaf0756-395e-440b-81a8-10cfefb33521.jpeg)
![WhatsApp Image 2022-04-26 at 22 47 46](https://user-images.githubusercontent.com/64117179/165347625-09d2b596-d7d2-479a-97eb-2cea3f3e4bf1.jpeg)
![WhatsApp Image 2022-04-26 at 22 49 46](https://user-images.githubusercontent.com/64117179/165347651-4137f2e7-594b-4ef6-912b-eaf68e598c00.jpeg)

**Comment by smashah** [comment]
dupe: #2658
