### ISSUE TITLE
session not saved

### ISSUE THREAD

**Issue by pumpkin39849** [open-wa/wa-automate-nodejs#2684]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

it doesnt remember the session and i have to authenticate every time
![Captura de pantalla 2022-04-30 085035](https://user-images.githubusercontent.com/93441461/166095363-0c789c6c-d6a1-4b80-bc00-57e489b93137.png)

### Steps To Reproduce

npm start

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2214.12",
  "WA_AUTOMATE_VERSION": "4.35.12",
  "BROWSER_VERSION": "Chrome/89.0.4389.90",
  "START_TS": 1651203031119,
  "RAM_INFO": "Total: 8.49 GB | Free: 3.47 GB",
  "PPTR_VERSION": "13.5.1",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 14.16.1
- npm: 7.21.1
```

**Comment by powermx** [comment]
Hello bro, how did you solve this one ?
