### ISSUE TITLE
Error decryptMedia on stickers

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#2687]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

Error when decrypt stickers

### Steps To Reproduce

I want to decrypt stickers, then show errors

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2214.12",
  "WA_AUTOMATE_VERSION": "4.35.13",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4896.127",
  "START_TS": 1651488929164,
  "RAM_INFO": "Total: 2.08 GB | Free: 1.31 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": false,
  "LAUNCH_TIME_MS": 21279,
  "ACC_TYPE": "BUSINESS",
  "chats": 100,
  "messages": 326,
  "contacts": 2046,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "e05a5d22-f683-4611-82c0-ced53a096f9c"
}
```

### Environment

```markdown
- OS: Linux 5.4
- Node: 16.14.2
- npm: 8.5.5
```

### Screenshots/Logs

First try show this
![image](https://user-images.githubusercontent.com/18587059/166224397-024a35bd-b086-4571-bb2c-54d9e85bb54d.png)

Second try show this
![image](https://user-images.githubusercontent.com/18587059/166224722-863bfca0-2c0e-4cda-a44b-b9225cc41ecd.png)

**Comment by rickricardo** [comment]
Not sure to be the same error, but I have:

Error: TypeError: Cannot read properties of undefined (reading 'toString') false
TCL: start -> error Error [MissingCriticalDataError]: Message is missing critical data: mediaKey, filehash, mimetype, type, size

```
                    if( message.type==='sticker') {
                        let stickerDecryptable = await client.getStickerDecryptable(message.id);
			if(stickerDecryptable){
                        	//mediaData = await decryptMedia(stickerDecryptable as DecryptableMessage , uaOverride);
                                mediaData = await decryptMedia(stickerDecryptable as any , uaOverride);
			}
                    }
```

**Comment by smashah** [comment]
In the next version you no longer need to use `getStickerDecryptable` the incoming sticker will be ready for decryption like all other media

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.37.5](https://github.com/open-wa/wa-automate-nodejs/compare/4.37.4...4.37.5) (2022-06-05)

- Release 4.37.5 [`2e6c44a`](https://github.com/open-wa/wa-automate-nodejs/commit/2e6c44ad2056dd8676839015d1702a8845a74605)
- 🎉  sticker decryption now GA by default! #2687 [`5170232`](https://github.com/open-wa/wa-automate-nodejs/commit/51702328f448db664c7ab4f78e60614a919f273f)
- 🥚 patches update [`f07d562`](https://github.com/open-wa/wa-automate-nodejs/commit/f07d562cb05ee8d6818bf99e5c4e417425c04c4f)
- 🥚 patches update [`d689cca`](https://github.com/open-wa/wa-automate-nodejs/commit/d689cca4d9f18f9c7245ff66fde9727397e5ba6e)
- updated types-only package [`f04eb24`](https://github.com/open-wa/wa-automate-nodejs/commit/f04eb2438ae05b67743291efcc76d2cae77d4650)
