### ISSUE TITLE
Won't save config in data.json

### ISSUE THREAD

**Issue by luizoti** [open-wa/wa-automate-nodejs#2690]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

When I run the EASY API it works normally, it asks for login via qrcode and it works fine, but when I finish and run it again, it asks for login again.

The data.json, contains only `e30=` which as far as I've seen is just a `{}`.

Current command:

`npx @open-wa/wa-automate --session-id "my-session-id" -p 8085 -k 'my-key'`

### Expected Behavior

Does not save configuration in data.json file.

### Steps To Reproduce

1. Normal execution of easy api

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2214.12",
  "WA_AUTOMATE_VERSION": "4.35.13",
  "BROWSER_VERSION": "HeadlessChrome/101.0.4950.0",
  "START_TS": 1651706794290,
  "RAM_INFO": "Total: 16.51 GB | Free: 9.02 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": true,
  "LAUNCH_TIME_MS": 51105,
  "ACC_TYPE": "PERSONAL",
  "chats": 58,
  "messages": 282,
  "contacts": 360,
  "isMd": true,
  "INSTANCE_ID": "c5e8478c-0112-4cbf-8b0c-04c8b5c6fdde"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.15.0
- npm: 8.5.5
```

**Comment by powermx** [comment]
Same Here

**Comment by powermx** [comment]
Did you solve this ?

**Comment by smashah** [comment]
e30 session data is normal for multi device sessions.

CLI: --multi-device

Config: `"multiDevice": true`

**Comment by luizoti** [comment]
> e30 session data is normal for multi device sessions.
> 
> CLI: --multi-device
> 
> Config: `"multiDevice": true`

In my tests I was using [wa-automate-socket-client-python](https://github.com/open-wa/wa-automate-socket-client-python), and the command described in the post, and when logging in the first time it is not saved and it asks for login if this is normal, what is the correct setup so you don't have to log in again?

**Comment by smashah** [comment]
Try this:

npx @open-wa/wa-automate --session-id "my-session-id" -p 8085 -k 'my-key' --multi-device

And then keep the session alive for a few minutes. Send a few messages back and forth. Then restart it.

**Comment by luizoti** [comment]
I'll test it, vlw.

**Comment by gadingnst** [comment]
same here, any updates?

**Comment by luizoti** [comment]
> same here, any updates?

Test as mentioned by @smashah, for me it seems to have working properly: https://github.com/open-wa/wa-automate-nodejs/issues/2690#issuecomment-1120324417

**Comment by luizoti** [comment]
Everything indicates that the solution is the one informed by @smashah , I will close the issue.

CLI: `--multi-device`

Config: `"multiDevice": true
`

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "minor"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.36.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.35.13...4.36.0) (2022-05-12)

- Release 4.36.0 [`2c1fb04`](https://github.com/open-wa/wa-automate-nodejs/commit/2c1fb04fd45410f6b120c8b0b8085ac0c43e93e1)
- 🔧 [WARNING] `multiDevice` is now `true` by default #2690 [`8490baf`](https://github.com/open-wa/wa-automate-nodejs/commit/8490baf6140cd109433d5d632bdc38846371632d)
- 🥚 patches update [`a40b8af`](https://github.com/open-wa/wa-automate-nodejs/commit/a40b8af42c9548cca4319c4972b43e778a4cb0f8)
- 🥚 patches update [`20db10e`](https://github.com/open-wa/wa-automate-nodejs/commit/20db10efa01f2136bba50a691dea63bb042220aa)
- 🥚 patches update [`912907b`](https://github.com/open-wa/wa-automate-nodejs/commit/912907bcab70e194859abe86b1590af59d17fac2)
- 🥚 patches update [`807caa5`](https://github.com/open-wa/wa-automate-nodejs/commit/807caa5ad9122d36d3158d246afc9d9a12b08bc0)
- 🥚 patches update [`9124b92`](https://github.com/open-wa/wa-automate-nodejs/commit/9124b922ee28ff3ce9cd4b4359ec2f5b7e5f9111)
- 🥚 patches update [`a40e603`](https://github.com/open-wa/wa-automate-nodejs/commit/a40e6036c488bf274ac3a7a60e0f05c9e5494103)
- 🥚 patches update [`baee31b`](https://github.com/open-wa/wa-automate-nodejs/commit/baee31bbd41fe2a4f99778152b46c737eb50dc8c)
- 🥚 patches update [`8c91a2f`](https://github.com/open-wa/wa-automate-nodejs/commit/8c91a2f9f6c5f79b32bb8861d34d3174ca4d34ef)
- 🥚 patches update [`014defe`](https://github.com/open-wa/wa-automate-nodejs/commit/014defeeaf89d538728d876eb3f23d504ea1e82a)
- 🥚 patches update [`9c6c9cb`](https://github.com/open-wa/wa-automate-nodejs/commit/9c6c9cbd7e8920ddbfd63342905ad5a3f079c7c9)
- 🥚 patches update [`64b9809`](https://github.com/open-wa/wa-automate-nodejs/commit/64b98097bfc96ed3f3ad1d29c5be98f08b1dc299)
- 🥚 patches update [`a6d3fac`](https://github.com/open-wa/wa-automate-nodejs/commit/a6d3fac7f6e74ad15e1dc0cee68133e8552bcf02)
- 🥚 patches update [`c2e22e3`](https://github.com/open-wa/wa-automate-nodejs/commit/c2e22e3e7ce1ed5778fafc3fdcb7fc7e98e24e22)
- updated types-only package [`607a764`](https://github.com/open-wa/wa-automate-nodejs/commit/607a7649b268d98335865679b3c072194a169089)

**Comment by smashah** [comment]
`multiDevice` is `true` by default now.
