### ISSUE TITLE
unpin is failed with no error

### ISSUE THREAD

**Issue by ahmeaqas** [open-wa/wa-automate-nodejs#2692]
I have tried to pin a chat and it is successful. But unpin is not working. I have confirmed the bahaviour from api-docs too.

**Payload:** 

`{
  "args": {
    "id": "92XXXXXXXXX5@c.us",
    "pin": "false"
  }
}`

**Curl**

`curl -X 'POST' \
  'http://192.168.100.30:8002/pinChat' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": {
    "id": "92XXXXXXXXX5@c.us",
    "pin": "false"
  }
}'`

**Response**

`{
  "success": true,
  "response": true
}`

**Comment by smashah** [comment]
@ahmeaqas 

the issue is here:
```
"pin": "false"
```

`"false"` is not `false`, it actually resolves as `true`

You need to remove the quotes when using a boolean!

This will work:

```js
"pin": false
```

Whenever you're using a boolean, DO NOT USE `"` MARKS!
