### ISSUE TITLE
Not refreshing QR code in popup

### ISSUE THREAD

**Issue by mgkha** [open-wa/wa-automate-nodejs#2694]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

My own code

### Current Behavior

Although the console print "New QR Code generated.", QR code in the popup is not refreshing and still the same the QR as the first time renders.

### Expected Behavior

The popup QR should be new and refreshed just like in the console

### Steps To Reproduce

ConfigObject
```javascript
{
    sessionId: "session_1"
    multiDevice: true, // required to enable multiDevice support
    authTimeout: 60, // wait only 60 seconds to get a connection with the host account device
    blockCrashLogs: true,
    disableSpins: true,
    headless: true,
    hostNotificationLang: "EN_GB",
    logConsole: false,
    popup: true,
    qrPopUpOnly: true,
    qrLogSkip: true,
    qrTimeout: 0, // 0 means it will wait forever for you to scan the qr code
    useChrome: true,
    sessionDataPath: "session_data",
};
```

1. Create Client
2. Open popup QR
3. Wait for the QR to refresh in console
4. Refresh popup QR url (http://localhost:7000/qr?sessionId=session_1)

### create() code OR full CLI command + CONFIG

```markdown
create({
        sessionId: "session_1",
        multiDevice: true, // required to enable multiDevice support
        authTimeout: 60, // wait only 60 seconds to get a connection with the host account device
        blockCrashLogs: true,
        disableSpins: true,
        headless: true,
        hostNotificationLang: "EN_GB",
        logConsole: false,
        popup: true,
        qrPopUpOnly: true,
        qrLogSkip: true,
        qrTimeout: 0, // 0 means it will wait forever for you to scan the qr code
        useChrome: true,
        sessionDataPath: "session_data",
    }).then((client) => {
        client.onMessage(async (message) => {
            console.log(`${client.getSessionId()} → ${message.body}`);
        });
    });
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2216.4",
  "WA_AUTOMATE_VERSION": "4.35.13",
  "BROWSER_VERSION": "HeadlessChrome/101.0.4951.54",
  "START_TS": 1651928364882,
  "RAM_INFO": "Total: 17.10 GB | Free: 10.09 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": false,
  "LAUNCH_TIME_MS": 15586,
  "ACC_TYPE": "BUSINESS",
  "chats": 1,
  "messages": 10,
  "contacts": 10,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "3dbda301-97cf-4321-a12a-68f86d19ab50"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 14.17.6
- npm: 6.14.15
```

**Comment by smashah** [comment]
Interesting.

After testing using the CLI:

```js
npx @open-wa/wa-automate --popup --session-id=new-popup-qr-test
```

When I checked 

`http://localhost:8060/qr?sessionId=new-popup-qr-test`

it would update the qr code as expected.

Can you try using the CLI please and confirm that this issue is isolated to your code.

If it's isolated to your code then you have to provide more detail/context in order to replicate the issue here.
