### ISSUE TITLE
npx open-wa/wa-automate Error

### ISSUE THREAD

**Issue by kulasse02** [open-wa/wa-automate-nodejs#2695]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Steps To Reproduce

npx @open-wa/wa-automate 

### create() code OR full CLI command + CONFIG

```markdown
npx @open-wa/wa-automate
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2216.4",
  "WA_AUTOMATE_VERSION": "4.35.13",
  "BROWSER_VERSION": "HeadlessChrome/101.0.4950.0",
  "START_TS": 1652076902181,
  "RAM_INFO": "Total: 7.98 GB | Free: 1.71 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": true
}
```

### Environment

```markdown
- OS: Linux 5.13
- Node: 14.19.1
- npm: 6.14.16
```

**Comment by smashah** [comment]
What's the error?
