### ISSUE TITLE
message receiving stopes after a few seconds

### ISSUE THREAD

**Issue by Alien-alfa** [open-wa/wa-automate-nodejs#2696]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Steps To Reproduce

nothing

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2214.12",
  "WA_AUTOMATE_VERSION": "4.35.13",
  "BROWSER_VERSION": "HeadlessChrome/101.0.4950.0",
  "START_TS": 1652082616111,
  "RAM_INFO": "Total: 17.18 GB | Free: 4.72 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": false,
  "LAUNCH_TIME_MS": 73771,
  "ACC_TYPE": "PERSONAL",
  "chats": 21,
  "messages": 51,
  "contacts": 843,
  "isMd": true,
  "INSTANCE_ID": "ce68e51d-dcfd-4d67-9bec-9d15813ab93d"
}
```

### Environment

```markdown
- OS: macOS Big Sur
- Node: 17.8.0
- npm: 8.6.0
```

**Comment by smashah** [comment]
Please add more detail next time.
