### ISSUE TITLE
Checking if someone is Online is giving an error

### ISSUE THREAD

**Issue by shifoc** [open-wa/wa-automate-nodejs#2697]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Steps To Reproduce

await client.isChatOnline("number");

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2216.4",
  "WA_AUTOMATE_VERSION": "4.35.13",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4896.88",
  "START_TS": 1652096392411,
  "RAM_INFO": "Total: 1.01 GB | Free: 0.57 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Linux 5.13
- Node: 18.0.0
- npm: 8.6.0
```

### Screenshots/Logs

```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'presence')
0|index  |     at Object.window.<computed>.<computed> [as isChatOnline] (__puppeteer_evaluation_script__:1:320167)
0|index  |     at ExecutionContext._evaluateInternal (/home/ubuntu/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
0|index  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|index  |     at async ExecutionContext.evaluate (/home/ubuntu/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
```

**Comment by smashah** [comment]
Youre getting this error because the chat object is undefined. I've patched so you should not get to this error next time.
