### ISSUE TITLE
sendTextWithMentions  is sending a message that is not a disappearing message when it should be

### ISSUE THREAD

**Issue by shifoc** [open-wa/wa-automate-nodejs#2698]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

the message is not a disappearing message like it should be since the conversation is in a disappearing message mode

### Steps To Reproduce

await client.sendTextWithMentions(message.from, "@123456@c.us");

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2216.4",
  "WA_AUTOMATE_VERSION": "4.35.13",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4896.88",
  "START_TS": 1652096392411,
  "RAM_INFO": "Total: 1.01 GB | Free: 0.57 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Linux 5.13
- Node: 18.0.0
- npm: 8.6.0
```

**Comment by smashah** [comment]
should be fixed. Let me know if this happens on other messages.
