### ISSUE TITLE
getting puppeteer error when running it on a virtual android 

### ISSUE THREAD

**Issue by pumpkin39849** [open-wa/wa-automate-nodejs#2708]
### Are you using the latest version of the library?

- [x] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

when i run it on a virtual android(noxplayer latest version in this case) i get puppeteer error, it only works fine if i log in on a whatsapp phone

Error: Evaluation failed: i
    at ExecutionContext._evaluateInternal (C:\Users\User\Desktop\BoT-master\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)

### Steps To Reproduce

npm start

### DEBUG INFO

```markdown
latest
```

### Environment

```markdown
- OS: windows
- Node: latest
- npm: latest
```

**Comment by smashah** [comment]
`Error: Evaluation failed: i
at ExecutionContext._evaluateInternal ` is a meaningless error message.

In all wa code, how do you expect anyone to know which `i` exactly this is referring to?

You have an odd use case. So you have to add much more context if you want this issue to have any hope of being resolved.

1. Add these to your config:
```js
{
  "debug": true,
  "headless": false,
  "disableSpins":true,
  "logging": [{
    "type": "console"
  }],
 "logConsoleErrors": true
}
```
2. Screen record the browser window, screen record your AVD also.
3. Attach all the logs and screen recording to this issue.

**Comment by blackchineykh** [comment]
@pumpkin39849 interesting. How did you get past scanning the QR code. I'm interested in doing a virtual setup as well. Hope the puppeteer issue is identified
