### ISSUE TITLE
Multi-device is now mandatory but sendButton still doesn't work

### ISSUE THREAD

**Issue by DaviZMelo** [open-wa/wa-automate-nodejs#2712]
In the last update we can't disable the multi device feature on Whatsapp anymore but the 'sendButtons' method doesn't work if the multiDevice is enabled. So now users that didn't purchase the license can't use this feature?

**Comment by smashah** [comment]
That is the case for now. Based on your open source work you're eligible for an key. Please DM me on discord.

**Comment by smashah** [comment]
@TheBooker66 yes, thanks for putting your project out there for people to use. DM me on discord

**Comment by TheBooker66** [comment]
@smashah Thank you so much! Just one question: where can I find your Discord username?

**Comment by smashah** [comment]
@TheBooker66 click the discord badge in the readme to get an invite to the discord. Then DM me (SHAH)
