### ISSUE TITLE
How do I send VCard

### ISSUE THREAD

**Issue by mrbarnk** [open-wa/wa-automate-nodejs#272]
Hello @smashah, I want to be able to send VCard that will appear like the sendContact function.

Thanks :).

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.39](https://github.com/smashah/sulla/compare/1.8.38...1.8.39) (2020-04-06)

- Bump typedoc from 0.17.3 to 0.17.4 [`#282`](https://github.com/smashah/sulla/pull/282)
- Bump ts-node from 8.8.1 to 8.8.2 [`#281`](https://github.com/smashah/sulla/pull/281)
- Bump prettier from 2.0.2 to 2.0.3 [`#280`](https://github.com/smashah/sulla/pull/280)
- Release 1.8.39 [`c470e72`](https://github.com/smashah/sulla/commit/c470e723cffa6821d22439282dd28c9343ff7a70)
- added `sendVCard` #272 [`094b111`](https://github.com/smashah/sulla/commit/094b111bb7bf8a3f020172f8cd328102aed0ba2b)

**Comment by smashah** [comment]
@mrbarnk you can try:

```javascript
var vCardsJS = require('vcards-js');
...
//create a new vCard
var vCard = vCardsJS();

//set properties
vCard.firstName = 'Eric';
vCard.middleName = 'J';
vCard.lastName = 'Nesser';
vCard.organization = 'ACME Corporation';
vCard.photo.attachFromUrl('https://avatars2.githubusercontent.com/u/5659221?v=3&s=460', 'JPEG');
vCard.workPhone = '+13125551212';
vCard.birthday = new Date(1985, 0, 1);
vCard.title = 'Software Developer';
vCard.url = 'https://github.com/enesser';
vCard.note = 'Notes on Eric';

//get as formatted string
const vcard = vCard.getFormattedString();

//make sure you add the name as the third parameter!!!
client.sendVCard('4477777777777@c.us',vcard,'Eric Nesser')
```

If you don't put the name at the end then it will send it as some random contact in your contact list.

Report back if working.

Thanks

**Comment by joaomirandasa** [comment]
I didn't have success to use, @smashah - When i tried to send, using exactly your exemple above, nothing is received on destination, infinite clock on message queue sender.. probably something with encoding of vCard or something like that,not worked for me, :(

Debug Info {
  WA_VERSION: '0.4.2088',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.8.39',
  BROWSER_VERSION: 'Chrome/80.0.3987.0'
}

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.40](https://github.com/smashah/sulla/compare/1.8.39...1.8.40) (2020-04-06)

- Release 1.8.40 [`bddde0e`](https://github.com/smashah/sulla/commit/bddde0e7c75aaa25408267fddd631a3abaac95cb)
- deprecated old sendVCard method #272 [`9b74602`](https://github.com/smashah/sulla/commit/9b74602dee3d9a1506fcc02d13e797dd4d2680cc)

**Comment by mrbarnk** [comment]
It's not sending @smashah 
`
BEGIN:VCARD
VERSION:3.0
FN;CHARSET=UTF-8:
N;CHARSET=UTF-8:;;;;
TEL;TYPE=WORK,VOICE:2341234567890
REV:2020-04-06T19:54:52.653Z
END:VCARD
`

**Comment by mrbarnk** [comment]
Debug Info {                                                                                              
  WA_VERSION: '0.4.2088',                                                                                 
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, li
hrome/79.0.3945.88 Safari/537.36',                                                                        
  SULLA_HOTFIX_VERSION: '1.8.41',                                                                         
  BROWSER_VERSION: 'HeadlessChrome/80.0.3987.0'                                                           
}

**Comment by mrbarnk** [comment]
Here is my code.

//set properties
vCard.firstName = fname;
vCard.middleName = middleName;
vCard.lastName = lname;
vCard.workPhone = res.contact[0];

//get as a formatted string
const vcard = vCard.getFormattedString();

**Comment by smashah** [comment]
@mrbarnk please share the actual code used to send the vcard.

**Comment by mrbarnk** [comment]
> @mrbarnk you can try:
> 
> ```js
> var vCardsJS = require('vcards-js');
> ...
> //create a new vCard
> var vCard = vCardsJS();
> 
> //set properties
> vCard.firstName = 'Eric';
> vCard.middleName = 'J';
> vCard.lastName = 'Nesser';
> vCard.organization = 'ACME Corporation';
> vCard.photo.attachFromUrl('https://avatars2.githubusercontent.com/u/5659221?v=3&s=460', 'JPEG');
> vCard.workPhone = '+13125551212';
> vCard.birthday = new Date(1985, 0, 1);
> vCard.title = 'Software Developer';
> vCard.url = 'https://github.com/enesser';
> vCard.note = 'Notes on Eric';
> 
> //get as formatted string
> const vcard = vCard.getFormattedString();
> 
> //make sure you add the name as the third parameter!!!
> client.sendVCard('4477777777777@c.us',vcard,'Eric Nesser')
> ```
> 
> If you don't put the name at the end then it will send it as some random contact in your contact list.
> 
> Report back if working.
> 
> Thanks

I'm on phone now, but I sent it as it were from here. Does it work from your side?

**Comment by smashah** [comment]
@mrbarnk I've tested this again. It's working as expected

```javascript
      await client.sendVCard(message.from,"BEGIN:VCARD\r\nVERSION:3.0\r\nFN;CHARSET=UTF-8:Eric J Nesser\r\nN;CHARSET=UTF-8:Nesser;Eric;J;;\r\nBDAY:19850101\r\nPHOTO;TYPE=JPEG:https:\/\/avatars2.githubusercontent.com\/u\/5659221?v=3&s=460\r\nTEL;TYPE=WORK,VOICE:312-555-1212\r\nTITLE;CHARSET=UTF-8:Software Developer\r\nORG;CHARSET=UTF-8:ACME Corporation\r\nURL;CHARSET=UTF-8:https:\/\/github.com\/enesser\r\nNOTE;CHARSET=UTF-8:Notes on Eric\r\nREV:2020-04-10T15:58:21.810Z\r\nEND:VCARD",'TEST CONTACT');
```

If you have more problems please make an issue. This one is resolved now. Thanks

**Comment by mrbarnk** [comment]
NOOOOOOOOOOOOOOOOOOO, it's not working.
APRIL FOOL, you are a genius. It working after upgrading to `@open-wa/wa-automate`

**Comment by mrbarnk** [comment]
![image](https://user-images.githubusercontent.com/37006356/79012103-58f46800-7b1a-11ea-9d70-4ef95a70302d.png)

This is how it's sending, can it be like this?

![image](https://user-images.githubusercontent.com/37006356/79012180-8a6d3380-7b1a-11ea-815b-2d45bd40bd1d.png)

FYI, the two numbers are on whatsapp.

**Comment by smashah** [comment]
@mrbarnk That's a good question. After analyzing a manual vcard message there is something different in the vcard text. It has a little `waid` section injected in the number.

So, using the above example

changing:

`...5659221?v=3&s=460\r\nTEL;TYPE=WORK,VOICE:312-555-1212\r\nTITLE;CHARSET=UTF-8:Softwa`

into 

`...5659221?v=3&s=460\r\nTEL;TYPE=WORK,VOICE;waid=4477777777777:312-555-1212\r\nTITLE;CHARSET=UTF-8:Softwa`

results in the buttons showing up.

So `;waid=4477777777777` is injected before the `:` and after `TEL:TYPE=`.

Can you do me a favour and work on a regex function that injects the string into the middle?

**Comment by mrbarnk** [comment]
Anyway to do that with [`vcard-js`](https://www.npmjs.com/package/vcards-js)

**Comment by smashah** [comment]
Not unless there was a special version of it

**Comment by mrbarnk** [comment]
oh!, I will use the string then.

Thanks!

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.51](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.50...1.8.51) (2020-04-11)

- typo fix #272 [`#272`](https://github.com/open-wa/wa-automate-nodejs/issues/272)
- Release 1.8.51 [`1551a91`](https://github.com/open-wa/wa-automate-nodejs/commit/1551a911b9872e7136e84ed9450ea3f74505b49a)
- automatically inject waid in sendvcard #272 [`528ed5f`](https://github.com/open-wa/wa-automate-nodejs/commit/528ed5fe715792a92805df57d2ab29f9f3711643)

**Comment by smashah** [comment]
@mrbarnk

Try this update. It now takes an extra param:
https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#sendvcard

**Comment by diegozl** [comment]
Hi,

I was able to make the contact appear, as you guided. Thanks! My only question is: Is there a way to define the name on the sticker? Here for me, it is "contact".

Currently, my code is like this:
`await client.sendVCard(message.from, "BEGIN:VCARD\r\nVERSION: 3.0\r\nN:LastName;FirstName;;;\r\nFN:FistName LastName\r\nORG:Business;\r\nTEL;waid=551111111111:+55 11 1111-1111\r\nEND:VCARD", 'New Contact');`

Does anyone know how to proceed?
