### ISSUE TITLE
Session data is being created corrupted

### ISSUE THREAD

**Issue by willmaraujo** [open-wa/wa-automate-nodejs#2722]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

The session.data.json is being created corrupted after scan qrcode. Bellow the content of my session.data.json

`e30=`

### Expected Behavior

Generate the session.data.json properly.

### Steps To Reproduce

1. Run the application
2. Scan the QR Code
3. Check the generated session.data.json

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2218.8",
  "WA_AUTOMATE_VERSION": "4.36.6",
  "BROWSER_VERSION": "HeadlessChrome/101.0.4950.0",
  "START_TS": 1653683901368,
  "RAM_INFO": "Total: 17.18 GB | Free: 0.28 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "e3e64",
  "LAUNCH_TIME_MS": 18054,
  "ACC_TYPE": "BUSINESS",
  "chats": 251,
  "messages": 702,
  "contacts": 1277,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "98c5c308-b212-460d-b09d-baa511b37210"
}
```

### Environment

```markdown
- OS: macOS Monterey
- Node: 14.19.0
- npm: 6.14.16
```

**Comment by smashah** [comment]
session data is placeholder for MD sessions `e30=` is the base64 representation of `{}`

**Comment by willmaraujo** [comment]
> 

First of all, congratulations for the project it's really impressive! 

Is it possible to pass MD sessions using the docker image directly? The documentation says we can pass the session trough the env variable.

**Comment by smashah** [comment]
That's for legacy (non-MD) sessions.

Now you have to scan within the docker container
