### ISSUE TITLE
Every time i start the wa-automate, i need scan qr code again to sync my wpp with client

### ISSUE THREAD

**Issue by SenpaiCookies** [open-wa/wa-automate-nodejs#2729]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

This is happening after **whatsapp** updated **new whatsapp web system**.. Can someone help me to solve it? 

### Steps To Reproduce

?

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2218.8",
  "WA_AUTOMATE_VERSION": "4.37.2",
  "BROWSER_VERSION": "HeadlessChrome/102.0.5005.63",
  "START_TS": 1654262143272,
  "RAM_INFO": "Total: 17.14 GB | Free: 12.08 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "d3aed",
  "LAUNCH_TIME_MS": 14642,
  "ACC_TYPE": "BUSINESS",
  "chats": 1,
  "messages": 9,
  "contacts": 143,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "158ef0f5-3877-4ed6-860f-7793c41eb088"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.15.0
- npm: 8.5.5
```

**Comment by smashah** [comment]
unable to replicate with lack of detail. If you have more information please add it here and i will reopen
