### ISSUE TITLE
Cant Send Image

### ISSUE THREAD

**Issue by shail2k4** [open-wa/wa-automate-nodejs#2737]
Can not send Image or other documents.
`
window.WAPI.procFiles= async function(chat, blobs) {
    if (!Array.isArray(blobs)) {
        blobs = [blobs];
    }
    var mc = new Store.MediaCollection(chat);
    await mc.processFiles((Debug.VERSION === '0.4.613')?blobs:blobs.map(blob=>{return{file:blob}}) , chat, 1);
    return mc
}`

showing the error...
> mc.processFile is not a function

**Comment by smashah** [comment]
patched

**Comment by shail2k4** [comment]
cant find patch

**Comment by smashah** [comment]
Just restart the process

**Comment by shail2k4** [comment]
Which process sir?
I am using only **wapi.js**
