### ISSUE TITLE
Get list of groups sometimes crashes or returns a trimmed number of items

### ISSUE THREAD

**Issue by garciabruno** [open-wa/wa-automate-nodejs#2739]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

I call getAllChats() function expecting to receive ~1305 chats, but it returns a trimmed number of chats (~400).
If I call the same function over and over, the number goes **down**

### Expected Behavior

Obtain a list of all the chats in that account.

### Steps To Reproduce

1. In a docker container, log in to an account with numerous group chats
2. Call the getAllChats function
3. Expect to receive all the chats, but only receive a trimmed array.

### create() code OR full CLI command + CONFIG

```markdown
create({
    inDocker: true,
    useChrome: true,
    licenseKey: "<REDACTED>",
    sessionId: "capybara-session",
    sessionDataPath: "./session-data",
  }).then((client) => start(client));
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2220.8",
  "WA_AUTOMATE_VERSION": "4.38.1",
  "BROWSER_VERSION": "HeadlessChrome/102.0.5005.61",
  "START_TS": 1654734336886,
  "RAM_INFO": "Total: 8.23 GB | Free: 6.93 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "b3c8a",
  "LAUNCH_TIME_MS": 20109,
  "ACC_TYPE": "PERSONAL",
  "chats": 248,
  "messages": 695,
  "contacts": 10841,
  "isMd": true,
  "INSTANCE_ID": "2eb5579c-0f27-4207-b36f-738c89b30bc7"
}
```

### Environment

```markdown
- OS: Linux 5.11
- Node: 18.3.0
- npm: 8.11.0
```

### Screenshots/Logs

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'map')
    at Object.window.WAPI.getAllChats (__puppeteer_evaluation_script__:267:30)
    at __puppeteer_evaluation_script__:1:13
    at ExecutionContext._evaluateInternal (/home/nin/src/capybara/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/home/nin/src/capybara/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)

### Anything else?

Only happens in docker, outside work perfectly.

**Comment by smashah** [comment]
try running with `--verbose` and and then add the logs here.

Also, based on your debug info there are 248 chats at the start and then your error message shows that the chat store has seemingly disappeared.

I cannot replicate this because i don't have 1500 chats and it's tough to debug on docker (i only fix issues outside docker usually).

Based on what I'm seeing, and how simple the getAllChats function is (there's not much there to fix to be honest), i suggest migrating off of docker.

**Comment by smashah** [comment]
I suggest running [`metrics`](https://docs.openwa.dev/classes/api_Client.Client.html#metrics) periodically to keep track of how many chats exactly are loaded into the session (in md, a lot of stuff is not actually synced otherwise the initial sync would take forever)

**Comment by garciabruno** [comment]
I ran with logging to console and I received the object has 500 items. This also checks with the metrics function that prints the following

```
{
  Timestamp: 131931.622943,
  Documents: 2,
  Frames: 1,
  JSEventListeners: 951,
  Nodes: 1147,
  LayoutCount: 393,
  RecalcStyleCount: 630,
  LayoutDuration: 0.121254,
  RecalcStyleDuration: 0.186452,
  ScriptDuration: 238.651684,
  TaskDuration: 242.821215,
  JSHeapUsedSize: 322151812,
  JSHeapTotalSize: 406863872,
  chats: 500,
  messages: 980,
  contacts: 10783,
  purged: {},
  isBiz: false,
  isMd: true
}
```

For your own sake, I won't paste the entire object here, but I can attach it on Discord.

**Comment by garciabruno** [comment]
The issue solved itself by factory resetting the phone and logging into a brand-new WhatsApp session on the phone.
**Note: I have +1300 group chats + occasional individual chats.**

Sorry for the trouble!
