### ISSUE TITLE
getCommonGroups does not return anything

### ISSUE THREAD

**Issue by manteguinha** [open-wa/wa-automate-nodejs#2751]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

Using `getCommonGroups` you get no response.

### Steps To Reproduce

`await client.getCommonGroups('55XXXXXXXXXX@c.us')`

### DEBUG INFO

```markdown
module.exports = config = (headless, start) => {
    return {
        sessionId: 'tetega',
        licenseKey: 'the license is here',
        headless,
        multiDevice: true, 
        qrTimeout: 0,
        authTimeout: 0,
        hostNotificationLang: 'PT_BR',
        skipUpdateCheck: true,
        cachedPatch: true,
        cacheEnabled: false,
        restartOnCrash: start,
        executablePath: '/usr/bin/chromium-browser',
        stickerServerEndpoint: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false
    }
}
```

### Environment

```markdown
- OS: Ubuntu 22.04 LTS 
- Node: v16.15.1
- npm: 8.12.2
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/63943591/174424309-442da8c9-8edd-4df0-8927-4d51a94ff62a.png)
![image](https://user-images.githubusercontent.com/63943591/174424315-98b3b130-8f31-4dc7-b3c4-e5a8dafa3000.png)

**Comment by smashah** [comment]
try doing `console.log(await client.getCommonGroups('5562993153446@c.us'))`

seems as though you're running the code and not doing anything with the output
