### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by yasin1913** [open-wa/wa-automate-nodejs#2755]
### Are you using the latest version of the library?

- [x] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

proxy
    proxyServerCredentials: {
        address: '...',
        username: '...',
        password: '...'
    },

### Expected Behavior

I got this error after the last update ->

www/wa-automate-client/node_modules/puppeteer-page-proxy/src/lib/cdp.js:6
                return (await client.send("Network.getCookies", urls)).cookies;
TypeError: Cannot read properties of undefined (reading 'send')

### Steps To Reproduce

proxy

### DEBUG INFO

```markdown
proxy
```

### Environment

```markdown
- OS: ubuntu or mac
- Node: 
- npm:
```

**Comment by smashah** [comment]
https://github.com/Cuadrix/puppeteer-page-proxy/pull/79

**Comment by smashah** [comment]
Please update to latest version: [4.42.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.41.1...4.42.0)
