### ISSUE TITLE
how to show QR code in VPS?

### ISSUE THREAD

**Issue by MininxD** [open-wa/wa-automate-nodejs#2759]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Tested and experienced on both

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

EASY API/CLI

### Steps To Reproduce

✓ Version: 3.16.1
✓ Downloaded patches in 3.097s
✓ Browser Launched

✖ Session data most likely expired due to manual host account logout. Please re-authenticate this session.

### DEBUG INFO

```markdown
WA_VERSION      │                                                                 '2.2222.11'                                                                 │
│       PAGE_UA       │ 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                      '3.16.1 UPDATE AVAILABLE: 4.41.1'                                                      │
│   BROWSER_VERSION   │                                                       'HeadlessChrome/103.0.5060.53'                                                        │
│         OS          │                                                                'Linux 5.15'                                                                 │
│      START_TS       │                                                                1655878139006
```

### Environment

```markdown
- OS: Ubuntu 22.04 lts
- Node: v12.22.9
- npm: 8.5.1
```

### Screenshots/Logs

on VPS just looping in debug info, and need re-auth

**Comment by smashah** [comment]
You're using a prehistoric version of the library!

```
npm i -s @open-wa/wa-automate@latest
```

Then try again
