### ISSUE TITLE
Get contact name using chat id

### ISSUE THREAD

**Issue by muhammad-bassiouni** [open-wa/wa-automate-nodejs#2762]
How can I get the contact name using chat id, for example the chat id is xxxxxxxxxx@c.us but the user name is John Doe

**Comment by smashah** [comment]
`(await client.getChatById("xxxxxxxxxx@c.us")).formattedTitle`

https://docs.openwa.dev/interfaces/api_model_chat.BaseChat.html#formattedTitle
