### ISSUE TITLE
Error: Error: Evaluation failed: TypeError: r._find is not a function on SendFile

### ISSUE THREAD

**Issue by ChocoPie02** [open-wa/wa-automate-nodejs#2770]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

Error: Error: Evaluation failed: TypeError: r._find is not a function

### Expected Behavior

Sending some file over bulk number

### Steps To Reproduce

Hello Shah Mohammad,

First of all thanks for such a beautiful piece of code.

We have just observed an error while sending a SendFile message via  with my own code its messy but work. only specific number that throw an error

here are sample number 6285881996834@c.us

### create() code OR full CLI command + CONFIG

```markdown
async function start(client) {
  console.log('\x1b[32m%s\x1b[0m', `Wait ${wait / 1000} Second`)
  await sleep(wait)
  let bulan = fs.readFileSync(bulanPath, 'utf8').split('\n');
  let index = fs.readFileSync(noPath, 'utf8');
  while (true) {
    if (!(akun = getAcc(index))) {
      //console.log(getAcc);
      console.log('\x1b[41m%s\x1b[37m', 'List akun empty.\nQuitting...', '\x1b[0m');
      break
    }
    console.log('\x1b[33m%s\x1b[0m', `Executing: ${akun[0]} | ${akun[1]}`);
    let nomer = akun[1].split('\r');
    //let nomer1 = nomer.split(',');
    fs.appendFileSync(logPath, `\n ${akun[0]}|${nomer[0]}| `)
    await sleep(5000)
    try {
      console.log('\x1b[33m%s\x1b[0m', `Sending : ${akun[0]} | ${nomer[0]} | Slip Gaji  - ${akun[0]} - ${bulan}`)
      //let err = Null;
      //try {
      let e = await client.sendFile(`${nomer[0]}@c.us`, `./file/Slip Gaji  - ${akun[0]} - ${bulan[0]}.pdf`, `Slip Gaji  - ${akun[0]} - ${bulan[0]}.pdf`, null, true).catch((err) => new Error(err));

      
     

      //}catch(err){
      //  
      //}
      if (e == 'Not a contact') {
        console.error('\x1b[41m%s\x1b[37m', err, '\x1b[0m');
        console.log('\x1b[41m%s\x1b[37m', e, '\x1b[0m');
        //fs.appendFileSync(logPath, `${err}|`)
      } if (e == false) {
        await client.sendFile(`${nomer[0]}@c.us`, `./file/Slip Gaji  - ${akun[0]} - ${bulan}.pdf`, `Slip Gaji  - ${akun[0]} - ${bulan[0]}.pdf`, null, true).catch((err) => new Error(err));
      } else {
        console.log('\x1b[42m%s\x1b[37m', `Sukses ${nomer[0]}@c.us |  ${akun[0]} | Slip Gaji  - ${akun[0]} - ${bulan}`, '\x1b[0m')
        console.log('\x1b[33m%s\x1b[0m', e, '\x1b[0m')
        fs.appendFileSync(logPath, `Sukses ${nomer[0]} |  ${akun[0]} | Slip Gaji - ${akun[0]} - ${bulan} | ${e}`)
      }

    } catch (eer) {
      console.log('\x1b[41m%s\x1b[37m', eer, '\x1b[0m')
      fs.appendFileSync(logPath, `${eer}|`)
    }
    index++;
    try {
      fs.writeFileSync(noPath, index.toString(), {
        encoding: 'utf8',
        flag: 'w'
      })
    } catch (W) {
      console.log('\x1b[41m%s\x1b[37m', W, '\x1b[0m')
    }
    console.log('\x1b[32m%s\x1b[0m', `Wait ${wait / 1000} Second`)
    await sleep(wait)
  };
};

const options = {
  sessionId: "2",
    headless: true,
    OnError: 'RETURN_ERROR',
    multiDevice: true,
    qrTimeout: 0,
    authTimeout: 0,
    chromiumArgs: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--aggressive-cache-discard',
      '--disable-cache',
      '--disable-application-cache',
      '--disable-offline-load-stale-cache',
      '--disk-cache-size=0'
    ]
  }

create(options).then(start);
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2222.11",
  "WA_AUTOMATE_VERSION": "4.42.2",
  "BROWSER_VERSION": "HeadlessChrome/103.0.5058.0",
  "START_TS": 1656646245247,
  "RAM_INFO": "Total: 17.09 GB | Free: 10.78 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "f4f8c",
  "LAUNCH_TIME_MS": 30670,
  "ACC_TYPE": "PERSONAL",
  "chats": 323,
  "messages": 471,
  "contacts": 3765,
  "isMd": true,
  "INSTANCE_ID": "a96232cb-ecf3-46b3-809c-648186bd89c7"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 18.0.0
- npm: 8.6.0
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/65725993/176819125-d5f68163-95af-46da-be49-ba79aee84347.png)
![image](https://user-images.githubusercontent.com/65725993/176819407-58e40c3d-551d-4915-b3c5-31faed617e0e.png)

Error: Error: Evaluation failed: TypeError: r._find is not a function
    at https://web.whatsapp.com/bootstrap_qr.14fc3e5723bd9ebea58c.js:71:540189
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.010e0b1e6789f30ac249.js:2:65369)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.010e0b1e6789f30ac249.js:2:65580)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.010e0b1e6789f30ac249.js:2:65639
    at Y (https://web.whatsapp.com/bootstrap_qr.14fc3e5723bd9ebea58c.js:32:84242)
    at new y (https://web.whatsapp.com/bootstrap_qr.14fc3e5723bd9ebea58c.js:32:76809)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.010e0b1e6789f30ac249.js:2:65520
    at H._serverQuery (https://web.whatsapp.com/bootstrap_qr.14fc3e5723bd9ebea58c.js:71:540555)
    at H._query (https://web.whatsapp.com/bootstrap_qr.14fc3e5723bd9ebea58c.js:71:539681)
    at file:///C:/WA/SendFile.js:55:223
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async start (file:///C:/WA/SendFile.js:55:15)

**Comment by 3dluis** [comment]
It is the same issue.

https://github.com/open-wa/wa-automate-nodejs/issues/2767

**Comment by smashah** [comment]
duplicate https://github.com/open-wa/wa-automate-nodejs/issues/2767

**Comment by ChocoPie02** [comment]
okey thanks
