### ISSUE TITLE
cutMsgCache/cutChatCache does nothing

### ISSUE THREAD

**Issue by fukumori** [open-wa/wa-automate-nodejs#2781]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

Jul  5 09:49:28 info: MDLWR - cutMsgCache : [] {"timestamp":"2022-07-05T12:49:28.317Z"}
Jul  5 09:49:28 info: IN d5128  {"_args":{},"_method":"cutMsgCache","timestamp":"2022-07-05T12:49:28.318Z"}
Jul  5 09:49:28 info: OUT d5128: 6ms  {"res":507,"timestamp":"2022-07-05T12:49:28.324Z"}
Jul  5 09:49:40 info: MDLWR - cutChatCache : [] {"timestamp":"2022-07-05T12:49:40.272Z"}
Jul  5 09:49:40 info: IN c5c74  {"_args":{},"_method":"cutChatCache","timestamp":"2022-07-05T12:49:40.273Z"}
Jul  5 09:49:40 info: OUT c5c74: 8ms  {"res":{"after":{"chats":99,"msgs":507},"before":{"chats":99,"msgs":507}},"timestamp":"2022-07-05T12:49:

### Expected Behavior

Cut message half

### Steps To Reproduce

Just call this command on easy api

### create() code OR full CLI command + CONFIG

```markdown
/usr/bin/node /root/wa-automate/node_modules/@open-wa/wa-automate/bin/server.js -e http://anotherhost:8888/webhook/ev/$(hostname)
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2222.11",
  "WA_AUTOMATE_VERSION": "4.42.4",
  "BROWSER_VERSION": "HeadlessChrome\/103.0.5060.114",
  "START_TS": 1657025003936,
  "RAM_INFO": "Total: 2.08 GB | Free: 1.67 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "8b2fa",
  "LAUNCH_TIME_MS": 174363,
  "ACC_TYPE": "PERSONAL",
  "chats": 99,
  "messages": 461,
  "contacts": 12572,
  "isMd": true,
  "INSTANCE_ID": "2ea1acf3-d112-49de-b18a-2e42605bc990"
}
```

### Environment

```markdown
- OS: Linux 5.4
- Node: 16.15.1
- npm: 8.11.0
```

**Comment by smashah** [comment]
@fukumori message and chat history works differently in MD - it's all saved to an indexdb database. I suggest not using cutMsgCache/cutChatCache in MD.

Thanks
