### ISSUE TITLE
Empty session data

### ISSUE THREAD

**Issue by gharidev** [open-wa/wa-automate-nodejs#2782]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

The session data on any session is 'e30=' which is base64 of '{}'

### Steps To Reproduce

1. Listens to event `'sessionDataBase64.**'`.
2. sessionDataString got is `'e30='`

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2222.11",
  "WA_AUTOMATE_VERSION": "4.42.4",
  "BROWSER_VERSION": "Chrome/103.0.5060.66",
  "START_TS": 1657028103368,
  "RAM_INFO": "Total: 6.33 GB | Free: 0.86 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "8b2fa",
  "LAUNCH_TIME_MS": 41830,
  "ACC_TYPE": "PERSONAL",
  "chats": 11,
  "messages": 84,
  "contacts": 161,
  "isMd": true,
  "INSTANCE_ID": "2ff06624-3f7e-460a-99a0-8a9b1d2eb585"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 16.15.1
- npm: 8.11.0
```

**Comment by smashah** [comment]
Sorry to tell you my friend but you're no longer using a legacy session. In MD, session data JSON is just a placeholder for when/if we ever figure out MD session portability.

MD session data will be e30= for the foreseeable future.

Track #2338 for updates
