### ISSUE TITLE
Unable to send message to group chat after clearing chat

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#2801]

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.42.7](https://github.com/open-wa/wa-automate-nodejs/compare/4.42.6...4.42.7) (2022-07-16)

- 🐛 fix #2801 [`#2801`](https://github.com/open-wa/wa-automate-nodejs/issues/2801)
- Release 4.42.7 [`ceb47b6`](https://github.com/open-wa/wa-automate-nodejs/commit/ceb47b6760e1e28facb072ff26d8ecdcc0533cd6)
- updated types-only package [`728bc2c`](https://github.com/open-wa/wa-automate-nodejs/commit/728bc2ca2ad62719881bb60692b482ebd0b4d310)

**Comment by fukumori** [comment]
Hello @smashah. The problem persists.

{"success":true,"response":{"WA_VERSION":"2.2224.8","PAGE_UA":"WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36","WA_AUTOMATE_VERSION":"4.42.7","BROWSER_VERSION":"HeadlessChrome/103.0.5060.114","OS":"Linux 5.4","START_TS":1658256901099,"RAM_INFO":"Total: 2.08 GB | Free: 1.62 GB","PPTR_VERSION":"15.0.0","LATEST_VERSION":true,"CLI":true,"PATCH_HASH":"110bd","OW_KEY":"","NUM":"3124","NUM_HASH":"855956fde5367affce2b2c73502b008c","LAUNCH_TIME_MS":35415,"ACC_TYPE":"PERSONAL","chats":89,"messages":185,"contacts":9993,"purged":{},"isMd":true,"INSTANCE_ID":"55b73067-a335-440d-b38b-b114f63c7178"}}

// Just try send
Jul 19 16:32:55[183995]: info: MDLWR - sendImage : {"args":{"to":"xxxxxxxxxxxxxxx@g.us","file":"file.jpeg","filename":"filename.jpeg","caption"...[TRUNCATED]... {"timestamp":"2022-07-19T19:32:55.062Z"}
Jul 19 16:32:55[183995]: info: methodArgs: to,file,filename,caption,quotedMsgId,waitForId,ptt,withoutPreview,hideTags,viewOnce {"timestamp":"2022-07-19T19:32:55.065Z"}
Jul 19 16:32:55[183995]: info: IN affe5  {"_args":{"caption":"...[TRUNCATED]...","file":"file.jpeg","filename":"filename.jpeg","hideTags":true,"ptt":false,"to":"xxxxxxxxxxxxxxx@g.us","viewOnce":false,"waitForId":true,"withoutPreview":false},"_method":"sendImage","timestamp":"2022-07-19T19:32:55.112Z"}
Jul 19 16:32:55[183995]: info: OUT affe5: 320ms  {"res":"Not a contact","timestamp":"2022-07-19T19:32:55.432Z"}
Jul 19 16:32:55[183995]: Not a contact
// After manually send message to group on device
Jul 19 16:38:12[183995]: info: MDLWR - sendImage : {"args":{"to":"xxxxxxxxxxxxxxx@g.us","file":"file.jpeg","filename":"filename.jpeg","caption"...[TRUNCATED]... {"timestamp":"2022-07-19T19:38:12.692Z"}
Jul 19 16:38:12[183995]: info: methodArgs: to,file,filename,caption,quotedMsgId,waitForId,ptt,withoutPreview,hideTags,viewOnce {"timestamp":"2022-07-19T19:38:12.697Z"}
Jul 19 16:38:12[183995]: info: IN 518d4  {"_args":{"caption":"...[TRUNCATED]...","file":"file.jpeg","filename":"filename.jpeg","hideTags":true,"ptt":false,"to":"xxxxxxxxxxxxxxx@g.us","viewOnce":false,"waitForId":true,"withoutPreview":false},"_method":"sendImage","timestamp":"2022-07-19T19:38:12.726Z"}
Jul 19 16:38:14[183995]: info: OUT 518d4: 1410ms  {"res":"true_xxxxxxxxxxxxxxx@g.us_3EB0D6404E34A8C27A43_xxxxxxxxxxx@c.us","timestamp":"2022-07-19T19:38:14.136Z"}
// Calling clearAllChats
Jul 19 16:38:48[183995]: info: MDLWR - clearAllChats : {} {"timestamp":"2022-07-19T19:38:48.159Z"}
Jul 19 16:38:48[183995]: info: IN fc09c  {"_args":{},"_method":"clearAllChats","timestamp":"2022-07-19T19:38:48.161Z"}
Jul 19 16:39:03[183995]: info: OUT fc09c: 15570ms  {"res":true,"timestamp":"2022-07-19T19:39:03.731Z"}
// Another test send message after clear
Jul 19 16:40:53[183995]: info: MDLWR - sendImage : {"args":{"to":"xxxxxxxxxxxxxxx@g.us","file":"file.jpeg","filename":"filename.jpeg","caption"...[TRUNCATED]... {"timestamp":"2022-07-19T19:40:53.230Z"}
Jul 19 16:40:53[183995]: info: methodArgs: to,file,filename,caption,quotedMsgId,waitForId,ptt,withoutPreview,hideTags,viewOnce {"timestamp":"2022-07-19T19:40:53.234Z"}
Jul 19 16:40:53[183995]: info: IN b54dc  {"_args":{"caption":"...[TRUNCATED]...","file":"file.jpeg","filename":"filename.jpeg","hideTags":true,"ptt":false,"to":"xxxxxxxxxxxxxxx@g.us","viewOnce":false,"waitForId":true,"withoutPreview":false},"_method":"sendImage","timestamp":"2022-07-19T19:40:53.261Z"}
Jul 19 16:40:53[183995]: info: OUT b54dc: 8ms  {"res":"Not a contact","timestamp":"2022-07-19T19:40:53.269Z"}
Jul 19 16:40:53[183995]: Not a contact
//after another number post on group
Jul 19 16:49:41[183995]: info: MDLWR - sendImage : {"args":{"to":"xxxxxxxxxxxxxxx@g.us","file":"file.jpeg","filename":"filename.jpeg","caption"...[TRUNCATED]... {"timestamp":"2022-07-19T19:49:41.366Z"}
Jul 19 16:49:41[183995]: info: methodArgs: to,file,filename,caption,quotedMsgId,waitForId,ptt,withoutPreview,hideTags,viewOnce {"timestamp":"2022-07-19T19:49:41.374Z"}
Jul 19 16:49:41[183995]: info: IN b9cfd  {"_args":{"caption":"...[TRUNCATED]...","file":"file.jpeg","filename":"filename.jpeg","hideTags":true,"ptt":false,"to":"xxxxxxxxxxxxxxx@g.us","viewOnce":false,"waitForId":true,"withoutPreview":false},"_method":"sendImage","timestamp":"2022-07-19T19:49:41.406Z"}
Jul 19 16:49:41[183995]: info: OUT b9cfd: 427ms  {"res":"true_xxxxxxxxxxxxxxx@g.us_3EB037585C54287620D1_xxxxxxxxxxx@c.us","timestamp":"2022-07-19T19:49:41.832Z"}

**Comment by smashah** [comment]
You didn't tell me this is happening with images.
