### ISSUE TITLE
Browser wont open on Heroku

### ISSUE THREAD

**Issue by evetixx** [open-wa/wa-automate-nodejs#2805]
I have tried so many things at the stuck overfloiw but cant figure it what is this error. can anyone help me
![image](https://user-images.githubusercontent.com/79743798/179782853-0a053773-656e-484d-bb24-d35984d48f47.png)

**Comment by smashah** [comment]
HI try the digital ocean link in the readme or railway:

https://railway.app/new/template/GUPFHI?referralCode=shah
