### ISSUE TITLE
setGroupEditToAdminsOnly not work property

### ISSUE THREAD

**Issue by fukumori** [open-wa/wa-automate-nodejs#2811]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

```javascript
Jul 22 12:43:15 [179151]: info: MDLWR - setGroupEditToAdminsOnly : {"args":{"groupId":"120363025296245748@g.us","onlyAdmins":true}} {"timestamp":"2022-07-22T15:43:15.107Z"}
Jul 22 12:43:15 [179151]: info: methodArgs: groupId,onlyAdmins {"timestamp":"2022-07-22T15:43:15.109Z"}
Jul 22 12:43:15 [179151]: info: IN d6af2  {"_args":{"groupId":"120363025296245748@g.us","onlyAdmins":true},"_method":"setGroupEditToAdminsOnly","timestamp":"2022-07-22T15:43:15.109Z"}
Jul 22 12:43:15 [179151]: info: OUT d6af2: 235ms  {"res":true,"timestamp":"2022-07-22T15:43:15.344Z"}
```
### Expected Behavior

Returns true but not change to admin only. All participants can edit group info.

### Steps To Reproduce

setGroupEditToAdminsOnly 

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2226.5",
  "WA_AUTOMATE_VERSION": "4.42.8",
  "BROWSER_VERSION": "HeadlessChrome/103.0.5060.134",
  "START_TS": 1658502335377,
  "RAM_INFO": "Total: 2.08 GB | Free: 1.64 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "a92c2",
  "LAUNCH_TIME_MS": 18921,
  "ACC_TYPE": "PERSONAL",
  "chats": 31,
  "messages": 31,
  "contacts": 3606,
  "isMd": true,
  "INSTANCE_ID": "4b94bc94-2d95-486d-9139-c034ecf9f953"
}
```

### Environment

```markdown
- OS: Linux 5.4
- Node: 16.16.0
- npm: 8.11.0
```

**Comment by smashah** [comment]
@fukumori are you sure about this? Seems to be working fine here. Please triple check

**Comment by garciabruno** [comment]
I'm having the same issue, sending "onlyAdmins: true" makes it so every participant can edit group info.
I haven't tested with old groups, but when they're recently created within the same session, then it won't work.

**Comment by smashah** [comment]
thanks for the detail @garciabruno

**Comment by smashah** [comment]
@fukumori @garciabruno are you using a license?

**Comment by smashah** [comment]
@garciabruno @fukumori should be fixed now via patches. please restart and try again
