### ISSUE TITLE
Does not send image sending the text message before and then the image sending.

### ISSUE THREAD

**Issue by 3dluis** [open-wa/wa-automate-nodejs#2813]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

We are trying to send an image using the sendImage method, in some moments it is not sent because it returns the error that an open chat or contact must have, but the logic of this method is wrong, since if you enter another message after the message of text does not send the image and give the license error or that it must have a text message, I understand that the logic of this must be that the chat is open.

### Expected Behavior

It is not sending the image, since it requires that there is a text message before the image, we send the text message, but if you enter a message between the interval of the text message and the sending of the image, it returns the error that you should send a text message first.

### Steps To Reproduce

api.sendText('19999999@c.us','...')
Event: onReciveMessage --> We received a message after sending the text message.
api.sendImage('19999999@c.us', 'base64:image');

### DEBUG INFO

```markdown
{
"WA_VERSION": "2.2224.8",
        "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
        "WA_AUTOMATE_VERSION": "4.42.8",
        "BROWSER_VERSION": "HeadlessChrome/103.0.5060.114",
        "OS": "Linux 5.10",
        "START_TS": 1657407820443,
        "RAM_INFO": "Total: 2.08 GB | Free: 1.16 GB",
        "PPTR_VERSION": "UNKNOWN",
        "LATEST_VERSION": true,
        "CLI": true,
        "PATCH_HASH": "0a030",
        "OW_KEY": "71cedbcc063168bec8e487f7d280bc8909d1bb81fdd4b8b5149c2aa7d8df0f06",
        "NUM": "9456",
        "NUM_HASH": "b63a9a05ee79e79dba75bf1aac2d668a",
        "LAUNCH_TIME_MS": 172057,
        "ACC_TYPE": "PERSONAL",
        "chats": 2,
        "messages": 5,
        "contacts": 37,
        "purged": {},
        "isMd": true,
        "INSTANCE_ID": "5057e411-d157-426e-9db6-756a1d0282eb"
}
```

### Environment

```markdown
OS: Ubuntu 20.04
Node: 13.14.0
npm: 7.6.3
```

**Comment by smashah** [comment]
@3dluis not sure what is going on here but make sure to await all promises:

```js
await api.sendText('[19999999@c.us](mailto:19999999@c.us)','...')
await api.sendImage('[19999999@c.us](mailto:19999999@c.us)', 'base64:image');
```
