### ISSUE TITLE
Session is not retrieved and sendLinkWithAutoPreview does not work

### ISSUE THREAD

**Issue by alexsanderluisdev** [open-wa/wa-automate-nodejs#2827]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Tested and experienced on both

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

Yesterday I started using the library and everything worked fine with the session. Today when running the same code, without changes, again, the session is no longer being recovered. Every time I run the code, the QR code is printed and I have to authenticate again.

Also, the **sendLinkWithAutoPreview** method doesn't work, either on multiDevice=true or multiDevice=false.

### Steps To Reproduce

Just install the latest version and run the sample code from the readme.

### create() code OR full CLI command + CONFIG

```markdown
const wa = require('@open-wa/wa-automate');

wa.create({
  sessionId: "COVID_HELPER",
  multiDevice: true, //required to enable multiDevice support
  authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
  blockCrashLogs: true,
  disableSpins: true,
  headless: true,
  hostNotificationLang: 'PT_BR',
  logConsole: false,
  popup: true,
  qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
}).then(client => start(client));

function start(client) {
  client.onMessage(async message => {
    if (message.body === 'Hi') {
      await client.sendText(message.from, '👋 Hello!');
    }
  });
}
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "^4.43.1",
  "WA_AUTOMATE_VERSION": "4.43.1",
  "BROWSER_VERSION": "HeadlessChrome/103.0.5058.0",
  "START_TS": 1659617960318,
  "RAM_INFO": "Total: 16.91 GB | Free: 3.87 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 18.7.0
- npm: 8.15.0
```

**Comment by alexsanderluisdev** [comment]
About the error on sendLinkWithAutoPreview

Debugging the code, I found that the problem happens when I don't pass the thumbnail parameter and the url has no image preview.

[https://github.com/open-wa/wa-automate-nodejs/blob/master/src/api/Client.ts#L1754](https://github.com/open-wa/wa-automate-nodejs/blob/master/src/api/Client.ts#L1754)

My solution was pass a demo image to the thumbnail and it work.

**Comment by smashah** [comment]
@alexsanderluisdev please share the exact URL you are attempting to send

**Comment by alexsanderluisdev** [comment]
> @alexsanderluisdev please share the exact URL you are attempting to send

https://checkout.juno.com.br/#/checkout/21220EB45E75B0C3970DE2B81EDA4EF989522873F4C7B179/oldLink

**Comment by smashah** [comment]
@alexsanderluisdev 

I put your url in metatags.io and it shows that there's not many metatags there to extract

<img width="1214" alt="CleanShot 2022-08-05 at 03 25 51@2x" src="https://user-images.githubusercontent.com/5903821/182988424-447a6673-8b7e-47a2-909e-4deb0cb2a0c4.png">

If this is your website please make sure you SSR the relevant metatags into the page upon first request and use metatags.io to make sure it looks right.

**Comment by smashah** [comment]
You can see in this project how the library attempts to get the metatags:

https://github.com/smashah/owa-meta-grabber

**Comment by alexsanderluisdev** [comment]
is there any way to send the link without preview? it doesn't make much sense to oblige to have the preview, not all links have

**Comment by smashah** [comment]
@alexsanderluisdev you can do that with [`sendText`](https://openwa.dev/docs/api/classes/api_Client.Client#sendtext).

I have updated the code to fallback to `sendText` if the thumbnail is missing.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.43.4](https://github.com/open-wa/wa-automate-nodejs/compare/4.43.3...4.43.4) (2022-08-14)

- ✨ ✨ ✨ ✨ DOCS V3 INIT ✨ ✨ ✨ ✨ [`d14df96`](https://github.com/open-wa/wa-automate-nodejs/commit/d14df96418f31329772c7a74ba9b44e59e778ed3)
- Release 4.43.4 [`3fc8bfc`](https://github.com/open-wa/wa-automate-nodejs/commit/3fc8bfcb770cb848d09b546f6d415be321305a87)
- 📝 update documentation [`c0e5ccc`](https://github.com/open-wa/wa-automate-nodejs/commit/c0e5cccedbf5d5c13ef29ab5ac2e61ccf52de208)
- 👔 update contact links [`8394289`](https://github.com/open-wa/wa-automate-nodejs/commit/83942896e29b331013c37e94c7710984cfc6c659)
- 🩹 fallback to sendText if thumbnail is missing on `sendLinkWithAutoPreview` #2827 [`b7b99ea`](https://github.com/open-wa/wa-automate-nodejs/commit/b7b99ea926da5b4d72c36bc060edf810e0a5e1f5)
- 🙈 update .npmignore [`c593c18`](https://github.com/open-wa/wa-automate-nodejs/commit/c593c183b7b1a5ed469fc96bfd0ef1bf914a0435)
- 📝 update docs [`79ee931`](https://github.com/open-wa/wa-automate-nodejs/commit/79ee931b76bd8651538c134ce387b269bf0fdfe6)
- 📝 update docs [`b3b6b68`](https://github.com/open-wa/wa-automate-nodejs/commit/b3b6b680a90248e969d87ce491e779fc9d43b6d8)
- 🥚 patches update [`ed304bc`](https://github.com/open-wa/wa-automate-nodejs/commit/ed304bc359407e3a060859551d46482c8e5ed73f)
- 🥚 patches update [`3f23fe1`](https://github.com/open-wa/wa-automate-nodejs/commit/3f23fe1a7b02d49c4964c70b05b4f4457aa07850)
- 🥚 patches update [`a635c6d`](https://github.com/open-wa/wa-automate-nodejs/commit/a635c6dfe2a356e95b49792b397442a34b33781b)
- updated types-only package [`d24b01b`](https://github.com/open-wa/wa-automate-nodejs/commit/d24b01ba6c21165db16bc5e69df498238256acf4)
- 🙈 update .gitigore [`43b1f00`](https://github.com/open-wa/wa-automate-nodejs/commit/43b1f00129bee13e87b33a21956e18c9b764714a)

**Comment by smashah** [comment]
Now it should fallback to sendText
