### ISSUE TITLE
getMyLastMessage not returning

### ISSUE THREAD

**Issue by alexsanderluisdev** [open-wa/wa-automate-nodejs#2829]
### Are you using the latest version of the library?

- [x] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

Sometimes, on call the **getMyLastMessage** function when my last message was sent many minutes ago, the app stops and nothing is returned.

### Steps To Reproduce

Just install the latest version and run the sample code from the readme.

### create() code OR full CLI command + CONFIG

```markdown
const wa = require('@open-wa/wa-automate');

wa.create({
  sessionId: "COVID_HELPER",
  multiDevice: true, //required to enable multiDevice support
  authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
  blockCrashLogs: true,
  disableSpins: true,
  headless: true,
  hostNotificationLang: 'PT_BR',
  logConsole: false,
  popup: true,
  qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
}).then(client => start(client));
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "^4.43.1",
  "WA_AUTOMATE_VERSION": "4.43.1",
  "BROWSER_VERSION": "HeadlessChrome/103.0.5058.0",
  "START_TS": 1659617960318,
  "RAM_INFO": "Total: 16.91 GB | Free: 3.87 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/17579846/183101280-ee0900d2-0d80-4fef-aad0-40b23dabab2f.png)

**Comment by alexsanderluisdev** [comment]
Any update?

**Comment by smashah** [comment]
I think the source of this problem is the fact that wa web kinda just gives up loading messages after a few dozen messages in the chat and you'll get this message:

<img width="390" alt="CleanShot 2022-08-10 at 14 38 11@2x" src="https://user-images.githubusercontent.com/5903821/183915523-7629f0f3-ca88-4ee4-b087-2beff68c9b5c.png">

**Comment by smashah** [comment]
@alexsanderluisdev I have published a new patch that should ensure that if the last message by the host account is not found by the time it hits the top of the chat then it doesn't keep the promisee going. It will just return `undefined`

**Comment by alexsanderluisdev** [comment]
> @alexsanderluisdevPubliquei um novo patch que deve garantir que, se a última mensagem da conta do host não for encontrada no momento em que chegar ao topo do bate-papo, não manterá a promessa. Ele só vai voltar`undefined`

Whats is the number os this version please?

**Comment by smashah** [comment]
@alexsanderluisdev it is a patch so all you need to do is restart your process.

**Comment by alexsanderluisdev** [comment]
@esmagar thanks!

**Comment by alexsanderluisdev** [comment]
@smashah thanks!
