### ISSUE TITLE
sendButtons not working

### ISSUE THREAD

**Issue by ngoding-bro** [open-wa/wa-automate-nodejs#2831]
I've tried several times to check the documentation and it still doesn't show a message with a button, is there anything wrong with this?
![Screenshot (91)](https://user-images.githubusercontent.com/74432059/183888117-5aac32d6-c376-4f6b-b297-ac136857421c.png)
![WhatsApp Image 2022-08-10 at 18 18 08](https://user-images.githubusercontent.com/74432059/183888522-0a73ba55-d28a-46fb-b144-3a13dccd8fd2.jpeg)

**Comment by smashah** [comment]
Do you see that long URL in the console logs? It is there to help you in filling out an issue template. It actually does most of the boring work for you. That context is required to debug an issue like this. Please click that link and fill out the template
