### ISSUE TITLE
SendSeen() and MarkAllRead() does not work

### ISSUE THREAD

**Issue by alanknm01** [open-wa/wa-automate-nodejs#2833]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

My own code

### Current Behavior

My bot does not mark as read any message

Does the mobile phone app is running? Yes, is running
Does the mobile application have the check mark activated? Yes

This problem occurs both in docker and locally

### Expected Behavior

That my bot marks the messages as read.

### Steps To Reproduce

1) I listen the incoming messages and they are send to "MessageRelayer()":
 ```client.onMessage(MessageRelayer(phoneNumber, client, OUT_WAPP_CHANNEL));```

``` 
const MessageRelayer = (bot_id: string, client: Client, redisChannel: string) => async (nativeMessage: Message) => {
    logInboundMessage(nativeMessage);
    
    await client.sendSeen(nativeMessage.chatId);
 ...
}
```

### create() code OR full CLI command + CONFIG

```markdown
wa.create({
  sessionId: "beto-wapp-server-v4",
  disableSpins: true,
  headless: true,
  useStealth: true,
  useChrome: true,
  sessionDataPath: process.env.WAPP_SESSION_PATH,
  authTimeout: 0,
  multiDevice: true,
  licenseKey:  process.env.OPEN_WA_KEY,
  ezqr: true,
  restartOnCrash: start,
})
```

### DEBUG INFO

```markdown
Debug info: {
  "WA_VERSION": "2.2230.10",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.43.2",
  "BROWSER_VERSION": "HeadlessChrome/104.0.5112.79",
  "OS": "Linux 5.15",
  "START_TS": 1660155194998,
  "RAM_INFO": "Total: 8.27 GB | Free: 3.72 GB",
  "PPTR_VERSION": "15.0.0"
}```
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: v14.17.6
- npm: 6.14.15
```

**Comment by smashah** [comment]
this should be fixed now. please restart and try again
