### ISSUE TITLE
cant start the app

### ISSUE THREAD

**Issue by the-jojo-jj** [open-wa/wa-automate-nodejs#2835]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/src/app/node_modules/@open-wa/wa-automate
npm ERR! dest /usr/src/app/node_modules/@open-wa/.wa-automate-Ityjijk9
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/src/app/node_modules/@open-wa/wa-automate' -> '/usr/src/app/node_modules/@open-wa/.wa-automate-Ityjijk9'

### Steps To Reproduce

run from docker 

### create() code OR full CLI command + CONFIG

```markdown
run from docker
```

### DEBUG INFO

```markdown
run from docker
```

### Environment

```markdown
- OS: Debian GNU 10
- Node: v16.16.0
- npm: 8.16.0
```

### Screenshots/Logs

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/src/app/node_modules/@open-wa/wa-automate
npm ERR! dest /usr/src/app/node_modules/@open-wa/.wa-automate-Ityjijk9
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/src/app/node_modules/@open-wa/wa-automate' -> '/usr/src/app/node_modules/@open-wa/.wa-automate-Ityjijk9'

**Comment by smashah** [comment]
@the-jojo-jj Please share all of the logs. not just the error. I need to know exactly when this error occurs and can't determine without wider context.
