### ISSUE TITLE
Getting "ERROR: This feature requires an Insiders license => https://get.openwa.dev/l/__________?v=i", but I'm sure I've got the right license

### ISSUE THREAD

**Issue by hendryhs** [open-wa/wa-automate-nodejs#2839]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

√ Client loaded for normal account [MD] with 3415 contacts, 3 chats & 3 messages in 20.978s
√ Downloaded License in 3.14s
√ License Valid: Restricted License Key
ERROR: This feature requires an Insiders license => https://get.openwa.dev/l/62**********5351?v=i

```js
wa.create({
    licenseKey: WA_LICENSE_KEY,
    multiDevice: true, //required to enable multiDevice support    
    onError: "THROW", 
    useChrome: true,
    headless: false,
    logFile: true,
    authTimeout: 1200, //wait only 60 seconds to get a connection with the host account device
    disableSpins: false,
    resizable: true,
    sessionDataPath: WA_SESSION,
    viewport:{
      height: 800,
      width:800
    },
    qrTimeout: 0 //0 means it will wait forever for you to scan the qr code
  })
```

### Expected Behavior

I've bought the license. 
The message : 
"ERROR: This feature requires an Insiders license => https://get.openwa.dev/l/6281228415351?v=i"

shouldn't show

### Steps To Reproduce

node .\index.js --session session_351 --license .\license_kurir_351 --csv .\test.csv

each execution will have that result. 

### create() code OR full CLI command + CONFIG

```markdown
node .\index.js --session session_351 --license .\license_kurir_351 --csv .\test.csv
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2230.13",
  "WA_AUTOMATE_VERSION": "4.43.4 UPDATE AVAILABLE: 4.44.1",
  "BROWSER_VERSION": "Chrome/104.0.5112.81",
  "START_TS": 1660726134079,
  "RAM_INFO": "Total: 8.48 GB | Free: 1.34 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": false,
  "CLI": false,
  "PATCH_HASH": "d49c1",
  "LAUNCH_TIME_MS": 20978,
  "ACC_TYPE": "PERSONAL",
  "chats": 3,
  "messages": 3,
  "contacts": 3415,
  "isMd": true,
  "INSTANCE_ID": "c80945ff-012c-4ca8-9c72-21dc17902cdd"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 14.15.3
- npm: 6.14.9
```

**Comment by smashah** [comment]
@hendryhs what feature are you trying to use?

With your restricted license you should have access to any and all insiders features.

**Comment by smashah** [comment]
I've updated the patch to indicate exactly which method is causing this error please restart and try again

**Comment by hendryhs** [comment]
updated to newest version 4.44.2. But I can't see any new messages to
indicate which function causes the error text.
Should any new text appear in the terminal ?

Here is my terminal latest execution :

√ Version: 4.44.2
√ Found session data file:
C:\Users\hendr\Desktop\nodejs\wa\session_351\session.data.json
√ Existing session data injected
√ Page loaded
┌─────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────√
Authenticated
√ Session ready for injection
√ Launch inject: 349ms
√ Launch inject: 533ms
√ WAPI Reinjected
√ Client is ready
√ Downloaded patches in 0.209s
√ Patches Installed: 45285
√ Client loaded for normal account [MD] with 3416 contacts, 3 chats & 3
messages in 19.121s
√ Downloaded License in 3.008s
√ License Valid: Restricted License Key
ERROR: This feature requires an Insiders license =>
https://get.openwa.dev/l/6281228415351?v=i&f=onNewProduct
┌───────────────────────────────────────────────────────┐
│                                                       │
│   Use the link below to easily report issues:👇👇👇   │
│                                                       │
└───────────────────────────────────────────────────────┘
√
https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2230.13%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.44.2%22,%0A%20%20%22BROWSER_VERSION%22:%20%22Chrome/104.0.5112.81%22,%0A%20%20%22START_TS%22:%201660806436319,%0A%20%20%22RAM_INFO%22:%20%22Total:%208.48%20GB%20%7C%20Free:%201.46%20GB%22,%0A%20%20%22PPTR_VERSION%22:%20%2215.0.0%22,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20false,%0A%20%20%22PATCH_HASH%22:%20%2245285%22,%0A%20%20%22LAUNCH_TIME_MS%22:%2019121,%0A%20%20%22ACC_TYPE%22:%20%22PERSONAL%22,%0A%20%20%22chats%22:%203,%0A%20%20%22messages%22:%203,%0A%20%20%22contacts%22:%203416,%0A%20%20%22isMd%22:%20true,%0A%20%20%22INSTANCE_ID%22:%20%220bc8747a-2c14-4b26-8d2f-3b4d865916df%22%0A%7D&enviro=-%20OS:%20Windows%2010%0A-%20Node:%2014.15.3%0A-%20npm:%206.14.9&labels=MD,PHA

√ 🚀 @OPEN-WA ready for account: 5351

**Comment by smashah** [comment]
@hendryhs 

As you can see the text has changed:

```
Downloaded License in 3.008s
√ License Valid: Restricted License Key
ERROR: This feature requires an Insiders license =>
https://get.openwa.dev/l/6281228415351?v=i&f=onNewProduct
```

It is showing that the source of the message is onNewProduct.

I have disabled this function for everyone due to the fact that it greatly affects launch times.

This message is normal even for licensed accounts.

**Comment by hendryhs** [comment]
thank you very much Shah.
Wish you all the best. :-D
