### ISSUE TITLE
Error when starting a conversation

### ISSUE THREAD

**Issue by fejorca** [open-wa/wa-automate-nodejs#2852]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Tested and experienced on both

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

I'm trying to connect it to chatwoot using the tutorial here on github but after testing either easy api or docker the error is the same, I've deleted everything related to chatwoot but even so wa-automate crashes everytime I send a message

### Expected Behavior

WA-Automate should connect to chatwoot OR at least doesn't crash when using without connecting to chatwoot

### Steps To Reproduce

Using terminal type:

docker run -d -p 3256:8080 --init openwa/wa-automate -w https://waautomate.site --chatwoot-url "https://chatwoot.site/api/v1/accounts/1/inbox/1" --chatwoot-api-access-token CHATWOOTAPIACCESSTOKEN --socket

### create() code OR full CLI command + CONFIG

```markdown
- Patches Installed: 04a98
- Client loaded for business account [MD] with 769 contacts, 3 chats & 26 messages in 14.518s
- Finalizing web session...
- Finalizing client...
┌───────────────────────────────────────────────────────┐
│                                                       │
│   Use the link below to easily report issues:👇👇👇   │
│                                                       │
└───────────────────────────────────────────────────────┘
- https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2232.7%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.44.5%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/105.0.5195.19%22,%0A%20%20%22START_TS%22:%201661533060596,%0A%20%20%22RAM_INFO%22:%20%22Total:%2025.15%20GB%20%7C%20Free:%2023.98%20GB%22,%0A%20%20%22PPTR_VERSION%22:%20%2215.0.0%22,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20true,%0A%20%20%22PATCH_HASH%22:%20%2204a98%22,%0A%20%20%22LAUNCH_TIME_MS%22:%2014518,%0A%20%20%22ACC_TYPE%22:%20%22BUSINESS%22,%0A%20%20%22chats%22:%203,%0A%20%20%22messages%22:%2026,%0A%20%20%22contacts%22:%20769,%0A%20%20%22isBiz%22:%20true,%0A%20%20%22isMd%22:%20true,%0A%20%20%22INSTANCE_ID%22:%20%226ff8097c-53e3-472b-b8d0-c3230444fd8b%22%0A%7D&enviro=-%20OS:%20Linux%205.15%0A-%20Node:%2018.7.0%0A-%20npm:%208.15.0&labels=CLI,MD,BHA
- 🚀 @OPEN-WA ready for account: 4934
- session_STARTUP
- Setting Up Chatwoot handler
- Make sure to set up the Chatwoot inbox webhook to the following path on this process: /chatwoot
Please set the chatwoot inbox webhook to this sessions URL with path /chatwoot
- Chatwoot handler set up successfully
- Setting Up API Explorer
- API Explorer set up successfully
- Setting up socket
- Socket ready for connection
- ...waiting for port 8080 to be free
- Port 8080 is now free.
- 
	API Explorer (​http://localhost:8080/api-docs/ ​)
- 
• Listening on port 8080!
TypeError: Cannot read properties of undefined (reading 'id')
    at /usr/src/app/node_modules/@open-wa/wa-automate/dist/cli/integrations/chatwoot.js:232:95
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@open-wa/wa-automate/dist/cli/integrations/chatwoot.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Starting the application
Using version: latest
./node_modules/@open-wa/wa-automate/bin/server.js --in-docker --qr-timeout 0 --popup --debug --force-port https://waautomate.site --chatwoot-url "https://chatwoot.site/api/v1/accounts/1/inbox/1" --chatwoot-api-access-token CHATWOOTAPIACCESSTOKEN --socket

up to date, audited 1038 packages in 2s

83 packages are looking for funding
  run `npm fund` for details

16 vulnerabilities (6 moderate, 7 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
Unable to read config file json: /config
- session_STARTUP
- webhooks set already
- DEBUG - PORT: 8080
- DEBUG - flags: {"sessionId":"session","executablePath":"/usr/bin/google-chrome","popup":true,"disableSpins":true,"cliConfig":"/config","useChrome":true,"port":8080,"inDocker":true,"qrTimeout":0,"debug":true,"forcePort":true,"webhook":"https://waautomate.site","chatwootUrl":"https://chatwoot.site/api/v1/accounts/2/inbox/17","chatwootApiAccessToken":"CHATWOOTAPIACCESSTOKEN","socket":true,"noApi":false,"host":"localhost","verbose":false,"ef":["qr","STARTUP","MD_DETECT"],"allowSessionDataWh":false,"generateApiDocs":true,"sessionDataOnly":false,"skipSavePostmanCollection":false,"headful":false,"preAuthDocs":false,"stats":false,"noKillOnLogout":false,"cors":false,"emitUnread":false,"allowIps":[]}
- DEBUG - env vars: {"WA_EXECUTABLE_PATH":"/usr/bin/google-chrome","WA_POPUP":"true","WA_DISABLE_SPINS":"true","WA_CLI_CONFIG":"/config","WA_USE_CHROME":"true","WA_PORT":"8080"}
- Launching EASY API
- Selected port is free
- Generating Swagger Spec
- Postman collection generated: open-wa-session.postman_collection.json
- API collections (swagger + postman) generated successfully
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓┃                                                                              ┃┃   @open-wa/wa-automate                                                       ┃┃   💬 🤖 The most reliable NodeJS whatsapp library for chatbots with          ┃┃   advanced features.                                                         ┃┃   Version: 4.44.5                                                            ┃┃   Check out the latest changes:                                              ┃┃   https://github.com/open-wa/wa-automate-nodejs#latest-changes               ┃┃                                                                              ┃┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
You can also authenticate the session at: http://localhost:8080
- Starting
- Version: 4.44.5
- Initializing WA
- Using custom chromium args with multi device will cause issues! Please remove them: 
- Launching Browser
- MD Enabled, turning off incognito mode.
- Data dir: /sessions/_IGNORE_session
- Browser launched: 93ms
- Setting Up Page
- Loading session data
- Found session data file: /usr/src/app/session.data.json
- No session data detected. Opting in for MD.
- Make sure to keep the session alive for at least 5 minutes after scanning the QR code before trying to restart a session!!
- Pre page launch setup complete: 5ms
- Navigating to WA
- Page loaded in 334ms: 200
- Page loaded
- Debug info: {
  "WA_VERSION": "2.2232.7",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.44.5",
  "BROWSER_VERSION": "HeadlessChrome/105.0.5195.19",
  "OS": "Linux 5.15",
  "START_TS": 1661533101549,
  "RAM_INFO": "Total: 25.15 GB | Free: 23.98 GB",
  "PPTR_VERSION": "15.0.0"
}
- Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2232.7%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.44.5%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/105.0.5195.19%22,%0A%20%20%22START_TS%22:%201661533101549,%0A%20%20%22RAM_INFO%22:%20%22Total:%2025.15%20GB%20%7C%20Free:%2023.98%20GB%22,%0A%20%20%22PPTR_VERSION%22:%20%2215.0.0%22,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20true%0A%7D&enviro=-%20OS:%20Linux%205.15%0A-%20Node:%2018.7.0%0A-%20npm:%208.15.0&labels=CLI,MD
- Time to injection: 797ms
- Injecting api
- Injecting scripts
- Base inject: 15ms
- WAPI inject: 10ms
- Checking session integrity
- Session integrity check passed
- Launch inject: 503ms
- WAPI injected
- Authenticating
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2232.7",
  "WA_AUTOMATE_VERSION": "4.44.5",
  "BROWSER_VERSION": "HeadlessChrome/105.0.5195.19",
  "START_TS": 1661532532329,
  "RAM_INFO": "Total: 25.15 GB | Free: 23.97 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "04a98",
  "LAUNCH_TIME_MS": 14575,
  "ACC_TYPE": "BUSINESS",
  "chats": 3,
  "messages": 25,
  "contacts": 769,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "990a1cc3-419a-4cd7-b270-3f0d6cad8f6f"
}
```

### Environment

```markdown
- OS: Linux 5.15
- Node: 18.7.0
- npm: 8.15.0
```

**Comment by smashah** [comment]
You say it's crashing when starting a conversation but only included the logs up to "authenticating". please include all of the logs up to the crash.

**Comment by smashah** [comment]
Which version of chatwoot are you using?

**Comment by fejorca** [comment]
> You say it's crashing when starting a conversation but only included the logs up to "authenticating". please include all of the logs up to the crash and use `--verbose`

Here's the log

  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  ...[TRUNCATED]... {"data":"Debug info: {\n  \"WA_VERSION\": \"2.2232.7\",\n  \"PAGE_UA\": \"WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36\",\n  ...[TRUNCATED]...","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:57.931Z"}
- Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2232.7%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.44.5%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/105.0.5195.19%22,%0A%20%20%22START_TS%22:%201661534337898,%0A%20%20%22RAM_INFO%22:%20%22Total:%2025.15%20GB%20%7C%20Free:%2023.95%20GB%22,%0A%20%20%22PPTR_VERSION%22:%20%2215.0.0%22,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20true%0A%7D&enviro=-%20OS:%20Linux%205.15%0A-%20Node:%2018.7.0%0A-%20npm:%208.15.0&labels=CLI,MD
info: Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2232.7%22,%0A%20%20%22W...[TRUNCATED]... {"data":"Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2232.7%22,%0A%20%20%22W...[TRUNCATED]...","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:58.320Z"}
- Time to injection: 425ms
info: Time to injection: 425ms  {"data":"Time to injection: 425ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:58.321Z"}
- Injecting api
info: Injecting api  {"data":"Injecting api","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:58.321Z"}
- Injecting scripts
info: Injecting scripts  {"data":"Injecting scripts","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:58.322Z"}
info: GET SCRIPT: jsSha.min.js 8982 {"timestamp":"2022-08-26T17:18:58.328Z"}
info: GET SCRIPT: qr.min.js 18603 {"timestamp":"2022-08-26T17:18:58.329Z"}
info: GET SCRIPT: base64.js 4173 {"timestamp":"2022-08-26T17:18:58.330Z"}
info: GET SCRIPT: hash.js 34983 {"timestamp":"2022-08-26T17:18:58.334Z"}
- Base inject: 24ms
info: Base inject: 24ms  {"data":"Base inject: 24ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:58.352Z"}
info: WAPI CHECK: false {"timestamp":"2022-08-26T17:18:58.359Z"}
info: GET SCRIPT: wapi.js 79911 {"timestamp":"2022-08-26T17:18:58.359Z"}
- WAPI inject: 215ms
info: WAPI inject: 215ms  {"data":"WAPI inject: 215ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:58.575Z"}
- Checking session integrity
info: Checking session integrity  {"data":"Checking session integrity","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:58.576Z"}
- Session integrity check passed
info: Session integrity check passed  {"data":"Session integrity check passed","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:58.604Z"}
info: GET SCRIPT: launch.js 65074 {"timestamp":"2022-08-26T17:18:58.605Z"}
- Launch inject: 308ms
info: Launch inject: 308ms  {"data":"Launch inject: 308ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:58.913Z"}
- WAPI injected
info: WAPI injected  {"data":"WAPI injected","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:58.913Z"}
- Authenticating
info: Authenticating  {"data":"Authenticating","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:58.913Z"}
- Authenticate to continue
info: Authenticate to continue  {"data":"Authenticate to continue","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:59.498Z"}
- First QR: 2759 ms
info: First QR: 2759 ms  {"data":"First QR: 2759 ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:18:59.614Z"}
info: 2@oo/Q8BwlaT3QWZerPEek5CezuzIx3c0fTecIvqFrksJFA3WY2y493+t3jbTA7lUJEVlpRbhI/QERcQ==,yLqi6eQ6BpEbYLDBXimaiBSt28m93hX5TpPisuIZbyI=,qBuLbxLCKPw7eOehemtnYpzQxY9X8AjQRqzgkqaD4FQ=,JgHo+r3v4wpIaGqQMEVdawNK1D...[TRUNCATED]... {"data":"2@oo/Q8BwlaT3QWZerPEek5CezuzIx3c0fTecIvqFrksJFA3WY2y493+t3jbTA7lUJEVlpRbhI/QERcQ==,yLqi6eQ6BpEbYLDBXimaiBSt28m93hX5TpPisuIZbyI=,qBuLbxLCKPw7eOehemtnYpzQxY9X8AjQRqzgkqaD4FQ=,JgHo+r3v4wpIaGqQMEVdawNK1D...[TRUNCATED]...","eventName":"qrData.session","eventNamespace":"qrData","sessionId":"session","timestamp":"2022-08-26T17:18:59.614Z"}
┌────────────────────────── session ──────────────────────────┐
│                                                             │
│   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄   │
│   █ ▄▄▄▄▄ █▄▀  █ █ █▄▀▄█▄  ▄▀▀ ██ ▄▀▀█▄█▄█▀█▄ ▀██ ▄▄▄▄▄ █   │
│   █ █   █ █  █ ▄██▀ ▀▀██▄▄ ███▀ ▀▄▄▄█▀▀  █▄▄█▀▄▀█ █   █ █   │
│   █ █▄▄▄█ █▄▀▀██▄▀▄▀ █▄▄▀▀█ ▄▄▄ ▀▀▄▀ █▀▄▄ █▄▀ ███ █▄▄▄█ █   │
│   █▄▄▄▄▄▄▄█▄▀ █ █▄█ ▀ █▄▀▄▀ █▄█ █▄█ █ █▄█ █ ▀▄▀ █▄▄▄▄▄▄▄█   │
│   █ ▄▄▄▀▀▄▀▄▄█▀ █▄█  █▀▄█ ▀▄▄ ▄▄  ██ ▄ █▀▄ ▄   █▄█▀ ▄▄▀ █   │
│   █▀▄▄ ▀ ▄▀▀▀ ▀ ██▀▄██▄▀▄  █ ▄ ▀▄▄  ▄ ▄▀▀  █ ▄▄▄▄▀▄█▄█▀██   │
│   █▀█  ██▄ █▄█▄▀▀██▄ ▄ ▀▀▀ ▄▀▄▄▀▀█▄▀▀█  ▀▀██▄█   ▄▄▄ ▄▀ █   │
│   ██▄▀▀▄█▄ █ ▀██ █▀██▄▄▄▀██ ▀█   ▄ ▄▀█▀▄█▀█▄▀ ▄█▄█▀▀▀▄▄▄█   │
│   ██▀ ▄▀▄▄█▀██▄▄█▄▄▀█▀██ ▀▀▀█ ▀█ █  ▀  █▄▄▄█▀█ █  ▀▀▄▄█▄█   │
│   █  █▀  ▄█▀▀▄▄█▀███▀ ▀▀ █ █  ▀▀ ▄█▀█▄█ ▄▄▀▀▄█▄▄▀██  ▀▀▀█   │
│   █▄█ ▀ ▄▄▀█▀▀█ █▀ █ ▀ ▄  ▄▄▀█    ▀▀▄▄ ▀██▄▄ ▀▀█▄▄▄▀▄█ ▀█   │
│   ██▄   ▄▄█ ▀▀██ ▀▀▀▀█▄▄▀▀█▄▄▄▄█▀▄  ██▄█▄██▄▄▀ ▀██▀  ▄▄▀█   │
│   █▀█ █ ▄▄▄  ███▄  ▀ ▄▀  ▀  ▄▄▄ ▄▄▄███  ▀ ████▀ ▄▄▄ ▄▄▄▀█   │
│   █▄▄▀  █▄█ ▀█▀ ▄▄█▀█ ▀ ██  █▄█ ▀▀▄ ▄█ ██ █▄ ▄█ █▄█ ▀█ ▄█   │
│   █▄▄ ▀▄ ▄  ██▄█▄▄  █▀█▄▀█▄ ▄▄▄ ▄▄  █▀█▀▄▄▄█▀▄  ▄▄▄▄  ▀▀█   │
│   █ █▀ ▄▀▄██▀▄█▄▀▀█▄█▄█▀ ██ ▀▀ █ ▀█▄▀▄▀▄▄▀▀ █████▀█▄▀▀███   │
│   █▀▀  █▀▄▄ ▄▀ ▄ █ ▄▀█ ▄ ▄  ██ ▄▀ ▀▀▀▄▄█▀██  ▀ ▄ ██ ▄▀▀▄█   │
│   █ █▄▀ ▀▄█▀███ ▀█▄▀ ▄██▄█▄▄   ▀ █▀▄   ▄▀ ██▀▄█ ▄█▀▀██▄██   │
│   █▀▀██▄█▄▀   █▄▀█▀█    █▀▀ ▄█▄██▄▄▀ █▄▄█▀██▄▄█▄▀█▄▄█  ▀█   │
│   █ ▄███▄▄▄  █▀██ ▀█  ▄▄▄ ▀▄▀███  ▀ ▀ █▀▀▄  █▄▄▀▄ ▄▀ ▄ ▄█   │
│   █▀▀▄▀█ ▄▄▄▄ █▄ █▀█▄█▄█ █▄ ▄▄▄█▀█▀▄▄▀▀▀██ █ ▄▀ ███▄ █ ██   │
│   █▄ ▀▄▄▄▄▀▄█▀▀▄▄█  ▄█▄ ▀███▄▀▀▄▄▄▄█▀▄█▄▄▄ ▀▀ ▄█▀▀  ▀  ██   │
│   ████▄██▄▄ ▄ ▄█▀▀█▄▄█ █▄▄▀ ▄▄▄    ███▄█ █▄▄▀▀▄ ▄▄▄ ▀▄███   │
│   █ ▄▄▄▄▄ ██▄▀▄ █ ▄██ ██▀█▀ █▄█ ▀▄▄▀▄▀  ▀▄ ▄▄ ▀ █▄█ ▄█ ▀█   │
│   █ █   █ █▀▄ ▄ ▄▀██ █  ▄▀█▄  ▄▄██ ██▄▄ ▀ ▄█▄▄█ ▄▄  █▄▀██   │
│   █ █▄▄▄█ █ ▄▄█▄   ▄▀▀▀ █▄██▄▄ ██   ▀██▄▄▄▀▀  ████▄▀▀█ ██   │
│   █▄▄▄▄▄▄▄█▄▄▄█▄▄▄█▄██▄███████▄█▄██▄▄███▄▄▄█████▄██▄█▄▄██   │
│                                                             │
│                                                             │
└─────────────────────────────────────────────────────────────┘
info: Waiting for internal QR renderer to load {"timestamp":"2022-08-26T17:18:59.681Z"}
info: Internal QR renderer loaded in 3 ms {"timestamp":"2022-08-26T17:18:59.683Z"}
info: AUTH.session  {"data":true,"eventName":"AUTH.session","eventNamespace":"AUTH","sessionId":"session","timestamp":"2022-08-26T17:19:10.109Z"}
info: AUTH.session  {"data":true,"eventName":"AUTH.session","eventNamespace":"AUTH","sessionId":"session","timestamp":"2022-08-26T17:19:10.110Z"}
info: AUTH.session  {"data":true,"eventName":"AUTH.session","eventNamespace":"AUTH","sessionId":"session","timestamp":"2022-08-26T17:19:10.110Z"}
info: AUTH.session  {"data":true,"eventName":"AUTH.session","eventNamespace":"AUTH","sessionId":"session","timestamp":"2022-08-26T17:19:10.111Z"}
info: FRAME NAV, https://web.whatsapp.com/?post_logout=1&logout_reason=2, false {"timestamp":"2022-08-26T17:22:10.510Z"}
Session most likely logged out
error: framenaverr Execution context was destroyed, most likely because of a navigation.  {"stack":"Error: Execution context was destroyed, most likely because of a navigation.\n    at rewriteError (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:322:19)\n    at proce...[TRUNCATED]...","timestamp":"2022-08-26T17:22:11.335Z"}
info: FRAME NAV, https://web.whatsapp.com/?post_logout=1&logout_reason=2, false {"timestamp":"2022-08-26T17:22:11.337Z"}
Session most likely logged out
info: FRAME NAV, https://web.whatsapp.com/, webpackChunkwhatsapp_web_client {"timestamp":"2022-08-26T17:22:11.599Z"}
- Injecting scripts
info: Injecting scripts  {"data":"Injecting scripts","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:22:11.600Z"}
info: GET SCRIPT: jsSha.min.js 8982 {"timestamp":"2022-08-26T17:22:11.611Z"}
info: GET SCRIPT: qr.min.js 18603 {"timestamp":"2022-08-26T17:22:11.611Z"}
info: GET SCRIPT: base64.js 4173 {"timestamp":"2022-08-26T17:22:11.611Z"}
info: GET SCRIPT: hash.js 34983 {"timestamp":"2022-08-26T17:22:11.612Z"}
- Base inject: 24ms
info: Base inject: 24ms  {"data":"Base inject: 24ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:22:11.635Z"}
info: WAPI CHECK: false {"timestamp":"2022-08-26T17:22:11.710Z"}
info: GET SCRIPT: wapi.js 79911 {"timestamp":"2022-08-26T17:22:11.711Z"}
- WAPI inject: 93ms
info: WAPI inject: 93ms  {"data":"WAPI inject: 93ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:22:11.805Z"}
- Checking session integrity
info: Checking session integrity  {"data":"Checking session integrity","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:22:11.806Z"}
- Session integrity check passed
info: Session integrity check passed  {"data":"Session integrity check passed","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:22:11.842Z"}
info: GET SCRIPT: launch.js 65074 {"timestamp":"2022-08-26T17:22:11.842Z"}
- Launch inject: 438ms
info: Launch inject: 438ms  {"data":"Launch inject: 438ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-08-26T17:22:12.281Z"}

**Comment by fejorca** [comment]
> Which version of chatwoot are you using?

v2.8.1

**Comment by fejorca** [comment]
By some sort of wizardry now is working but I'm having another issue, the docker command works as expected
