### ISSUE TITLE
- Waiting for ripe session... & No QR code

### ISSUE THREAD

**Issue by princecharmx** [open-wa/wa-automate-nodejs#2854]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

EASY API/CLI

### Current Behavior

The QR code not showing up & screen terminal stays at:
Waiting for ripe session...

### Expected Behavior

QR code usually comesup to get started

### Steps To Reproduce

**1. Updated to latest 4.44.5 version.
2. Tried pm2 logs & terminal & below steps got displayed....**

`root@ip-172-31-2-229:/home/ubuntu/whatsapp-bot-api# pm2 logs`
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2022-08-28T04:48:47: PM2 log: PM2 version          : 4.5.6
PM2        | 2022-08-28T04:48:47: PM2 log: Node.js version      : 16.9.1
PM2        | 2022-08-28T04:48:47: PM2 log: Current arch         : x64
PM2        | 2022-08-28T04:48:47: PM2 log: PM2 home             : /root/.pm2
PM2        | 2022-08-28T04:48:47: PM2 log: PM2 PID file         : /root/.pm2/pm2.pid
PM2        | 2022-08-28T04:48:47: PM2 log: RPC socket file      : /root/.pm2/rpc.sock
PM2        | 2022-08-28T04:48:47: PM2 log: BUS socket file      : /root/.pm2/pub.sock
PM2        | 2022-08-28T04:48:47: PM2 log: Application log path : /root/.pm2/logs
PM2        | 2022-08-28T04:48:47: PM2 log: Worker Interval      : 30000
PM2        | 2022-08-28T04:48:47: PM2 log: Process dump file    : /root/.pm2/dump.pm2
PM2        | 2022-08-28T04:48:47: PM2 log: Concurrent actions   : 2
PM2        | 2022-08-28T04:48:47: PM2 log: SIGTERM timeout      : 1600
PM2        | 2022-08-28T04:48:47: PM2 log: ===============================================================================
PM2        | 2022-08-28T04:48:47: PM2 log: App [nodejs-api-boilerplate:0] starting in -cluster mode-
PM2        | 2022-08-28T04:48:47: PM2 log: App [nodejs-api-boilerplate:0] online

/root/.pm2/logs/nodejs-api-boilerplate-out.log last 15 lines:
0|nodejs-a | 
0|nodejs-a |         Yep this is working 🍺
0|nodejs-a |         App listen on port: 3000 🍕
0|nodejs-a |         Env: production 🦄
0|nodejs-a |       
0|nodejs-a | You can also authenticate the session at: http://localhost:7000
0|nodejs-a | Connected to database
0|nodejs-a | ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓┃                                                                              ┃┃   @open-wa/wa-automate                                                       ┃┃   💬 🤖 The most reliable NodeJS whatsapp library for chatbots with          ┃┃   advanced features.                                                         ┃┃   Version: 4.44.5                                                            ┃┃   Check out the latest changes:                                              ┃┃   https://github.com/open-wa/wa-automate-nodejs#latest-changes               ┃┃                                                                              ┃┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
0|nodejs-a | 
0|nodejs-a |         Yep this is working 🍺
0|nodejs-a |         App listen on port: 3000 🍕
0|nodejs-a |         Env: production 🦄
0|nodejs-a |       
0|nodejs-a | You can also authenticate the session at: http://localhost:7000
0|nodejs-a | Connected to database

/root/.pm2/logs/nodejs-api-boilerplate-error.log last 15 lines:
0|nodejs-a |   "START_TS": 1661662130663,
0|nodejs-a |   "RAM_INFO": "Total: 2.04 GB | Free: 0.36 GB",
0|nodejs-a |   "PPTR_VERSION": "15.0.0"
0|nodejs-a | }
0|nodejs-a | - Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2232.7%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.44.5%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/103.0.5058.0%22,%0A%20%20%22START_TS%22:%201661662130663,%0A%20%20%22RAM_INFO%22:%20%22Total:%202.04%20GB%20%7C%20Free:%200.36%20GB%22,%0A%20%20%22PPTR_VERSION%22:%20%2215.0.0%22,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20false%0A%7D&enviro=-%20OS:%20Linux%205.4%0A-%20Node:%2016.9.1%0A-%20npm:%208.12.1&labels=MD
0|nodejs-a | - Time to injection: 1325ms
0|nodejs-a | - Injecting api
0|nodejs-a | - Injecting scripts
0|nodejs-a | - Base inject: 13ms
0|nodejs-a | - WAPI inject: 6ms
0|nodejs-a | - Checking session integrity
0|nodejs-a | - Session integrity check passed
0|nodejs-a | - Launch inject: 877ms
0|nodejs-a | - WAPI injected
0|nodejs-a | - Authenticating

0|nodejs-api-boilerplate  | - Authenticated
0|nodejs-api-boilerplate  | - Waiting for ripe session...

### DEBUG INFO

```markdown
{
  "WA_VERSION": "4.44.5",
  "WA_AUTOMATE_VERSION": "4.44.5",
  "BROWSER_VERSION": "HeadlessChrome/103.0.5058.0",
  "START_TS": 1661662130663,
  "RAM_INFO": "Total: 2.04 GB | Free: 0.36 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Linux 5.4
- Node: 16.9.1
- npm: 8.12.1
```

### Screenshots/Logs

![Uploading image.png…]()

**Comment by deriknyvo** [comment]
I have a similar problem, after reading the QR Code the session does not appear as completed, I'm still investigating if it could be something on my side.

**Comment by smashah** [comment]
@princecharmx please delete your session folder (`IGNORE_...` and try again)

Or update your chrome version to `104.0.5112.101` or greater. `103...` has been known to cause issues.

**Comment by smashah** [comment]
please share the whole `/root/.pm2/logs/nodejs-api-boilerplate-error.log ` file. there are alot of logs missing here.

**Comment by smashah** [comment]
closing. will reopen when there's more info
