### ISSUE TITLE
CLI: one-way EASY chatwoot setup

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#2869]
The annoying thing about the chatwoot integration is it is very chicken and egg.

If I am new to chatwoot I need to set up the api inbox. To do that I need the URL of the EASY API instance. Ok but in order to start the EASY API instance I need the chatwoot inbox URL and the access token.

access token is fine but how can I get the inbox URL if I don't have the EASY API URL?? Very frustrating.

I want to be able to have chatwoot open and give open-wa EASY API the chatwoot api URL and the access token and have open-wa figure out the rest. That includes:

- [x] Automatically determine the right account ID.
- [x] Automatically find the correct inbox if it exists.
- [x] Automatically creating the inbox if it doesn't exist.
- [x] Automatically update the webhook URL based on the `--api-host` of the EASY API instance - If I migrate between servers, I don't want to update the webhook URL in the chatwoot inbox manually
- [x] I should be able to change the name of the inbox without breaking the integration
- [x] Automatically inform dev if there's something wrong with the webhook url
- [x] If the `api_key` has changed on the EASY API then the webhook address on the relevant inbox should be updated also automatically.
- [x] Automatically check for a URL in the message and use autopreview if there is

# Update

The above changes were successfully implemented in version 4.45.1 of the library.

Previously you had to add the whole inbox URL to `--chatwoot-url` (e.g `"http://localhost:3000/app/accounts/1/inbox/2"`).

You no longer have to do this. The account Id can be inferred from the `--chatwoot-api-access-token`. The EASY API process will try to find the correct inbox. If it cannot find the right inbox the inbox will automatically be created.

So now you can just use `"http://localhost:3000"` & the access token - the EASY API will figure out the rest. Ofcourse, you can also choose to continue explicitly set the whole inbox URL (it is advisable).

If you want the EASY API to automatically update the webhook URL on the inbox then make sure to use the:
 `--force-update-cw-webhook` 
boolean flag. This is useful if you dynamically set the api key with `-k` or if you use `--tunnel`.

So if you're just getting started with chatwoot here's the step-by-step guide.

1. Set up chatwoot. 
2. Get your access token (e.g `12345`) by visiting the profile page. Note down the chatwoot URL (e.g `http://localhost:3000`).
3. Run the EASY API with the correct flags/config:

`cli.config.json`: 
```js
{
	"tunnel": true, //this will create a easily accessible link to your EASY API Instance
	"forceUpdateCwWebhook":true,
	"chatwootUrl": "http://localhost:3000",
	"chatwootApiAccessToken": "12345",
	"key": true, //this will automatically generate an API key to protect your EASY API instance,
	"verbose":true //turn on verbose logging to see chatwoot integration logs.
}
```
then run:
```sh
> npx @open-wa/wa-automate
```

OR fully via CLI:
```sh
> npx @open-wa/wa-automate -k --verbose --tunnel --force-update-cw-webhook --chatwoot-url "http://localhost:3000" --chatwoot-api-acccess-token "12345"
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "minor"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.45.1](https://github.com/open-wa/wa-automate-nodejs/compare/4.45.0...4.45.1) (2022-09-02)

- Release 4.45.1 [`9f141ae`](https://github.com/open-wa/wa-automate-nodejs/commit/9f141ae531a14344b09e4267d9817c5ff87c2381)
- 🐛  only do chatwoot setup under certain conditions #2869 [`b8bf4ec`](https://github.com/open-wa/wa-automate-nodejs/commit/b8bf4ec70623d49fa6a3819fa1ea559c6b862224)
- updated types-only package [`995dbad`](https://github.com/open-wa/wa-automate-nodejs/commit/995dbad235ddbf9f772bb1396fdf9d39c09dd19c)

**Comment by fejorca** [comment]
Excellent! I'll test it and I'll report if I found anything

**Comment by smashah** [comment]
@fejorca please see the update paragraph at the top
