### ISSUE TITLE
tunnel Error status is 408

### ISSUE THREAD

**Issue by scropion86** [open-wa/wa-automate-nodejs#2873]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

when using newlly tunnel in latest version when i try to proccess call using the tunnle URL i got error 408

![image](https://user-images.githubusercontent.com/5569470/188399926-c5473ab5-bd2b-4c2d-af3e-926b58a807a4.png)

### Expected Behavior

the call should be proccessed normally 

### Steps To Reproduce

run server using easyapi  `npx @open-wa/wa-automate -p 8000  --tunnel`

### create() code OR full CLI command + CONFIG

```markdown
npx @open-wa/wa-automate -p 8000 --tunnel
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2232.8",
  "WA_AUTOMATE_VERSION": "4.46.0",
  "BROWSER_VERSION": "HeadlessChrome/103.0.5058.0",
  "START_TS": 1662364395752,
  "RAM_INFO": "Total: 8.21 GB | Free: 7.43 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "97ec0",
  "LAUNCH_TIME_MS": 14937,
  "ACC_TYPE": "PERSONAL",
  "chats": 149,
  "messages": 184,
  "contacts": 544,
  "isMd": true,
  "INSTANCE_ID": "d94b3ef4-3bd2-4c20-99ea-4939ea758380"
}
```

### Environment

```markdown
- OS: Linux 5.10
- Node: 18.4.0
- npm: 8.12.1
```

**Comment by smashah** [comment]
It's really impossible to figure out why a timeout is occurring within 477ms without having the session logs, curl request, request body or the url.

If this happens again DM me. It needs to be debugged in real time
