### ISSUE TITLE
Stuck on Organizing messages

### ISSUE THREAD

**Issue by axixu** [open-wa/wa-automate-nodejs#2875]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

the CLI cannot finish start process, and stuck on eventName : internal_launch_progress

### Expected Behavior

running normally

### Steps To Reproduce

run cli command:
$ npx @open-wa/wa-automate --verbose --debug --disable-spins --multi-device --use-chrome

### create() code OR full CLI command + CONFIG

```markdown
$ npx @open-wa/wa-automate --verbose --debug --disable-spins --multi-device --use-chrome
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2232.8",
  "WA_AUTOMATE_VERSION": "4.46.0",
  "BROWSER_VERSION": "HeadlessChrome/105.0.5195.102",
  "START_TS": 1662456495328,
  "RAM_INFO": "Total: 1.07 GB | Free: 0.87 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": true
}
```

### Environment

```markdown
- OS: Linux Debian 11 x64
- Node: 16.17.0
- npm: 8.19.1
```

### Screenshots/Logs

- Time to injection: 1051ms
info: Time to injection: 1051ms  {"data":"Time to injection: 1051ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:16.373Z"}
- Injecting api
info: Injecting api  {"data":"Injecting api","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:16.377Z"}
- Injecting scripts
info: Injecting scripts  {"data":"Injecting scripts","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:16.377Z"}
info: GET SCRIPT: jsSha.min.js 8982 {"timestamp":"2022-09-06T09:28:16.396Z"}
info: GET SCRIPT: qr.min.js 18603 {"timestamp":"2022-09-06T09:28:16.397Z"}
info: GET SCRIPT: base64.js 4173 {"timestamp":"2022-09-06T09:28:16.397Z"}
info: GET SCRIPT: hash.js 34983 {"timestamp":"2022-09-06T09:28:16.397Z"}
- Base inject: 40ms
info: Base inject: 40ms  {"data":"Base inject: 40ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:16.434Z"}
info: WAPI CHECK: false {"timestamp":"2022-09-06T09:28:16.449Z"}
info: GET SCRIPT: wapi.js 79911 {"timestamp":"2022-09-06T09:28:16.449Z"}
- WAPI inject: 9ms
info: WAPI inject: 9ms  {"data":"WAPI inject: 9ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:16.459Z"}
- Checking session integrity
info: Checking session integrity  {"data":"Checking session integrity","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:16.459Z"}
- Session integrity check passed
info: Session integrity check passed  {"data":"Session integrity check passed","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:16.464Z"}
info: GET SCRIPT: launch.js 65074 {"timestamp":"2022-09-06T09:28:16.465Z"}
- Launch inject: 577ms
info: Launch inject: 577ms  {"data":"Launch inject: 577ms","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:17.042Z"}
- WAPI injected
info: WAPI injected  {"data":"WAPI injected","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:17.042Z"}
- Authenticating
info: Authenticating  {"data":"Authenticating","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:17.042Z"}
info: AUTH.session  {"data":true,"eventName":"AUTH.session","eventNamespace":"AUTH","sessionId":"session","timestamp":"2022-09-06T09:28:26.015Z"}
info: AUTH.session  {"data":true,"eventName":"AUTH.session","eventNamespace":"AUTH","sessionId":"session","timestamp":"2022-09-06T09:28:26.016Z"}
info: AUTH.session  {"data":true,"eventName":"AUTH.session","eventNamespace":"AUTH","sessionId":"session","timestamp":"2022-09-06T09:28:26.017Z"}
info: AUTH.session  {"data":true,"eventName":"AUTH.session","eventNamespace":"AUTH","sessionId":"session","timestamp":"2022-09-06T09:28:26.018Z"}
- Authenticated
info: Authenticated  {"data":"Authenticated","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:26.104Z"}
- Waiting for ripe session...
info: Waiting for ripe session...  {"data":"Waiting for ripe session...","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:26.165Z"}
- 100%:  Connecting…
info: 100%:      Connecting…  {"data":"100%:\t Connecting…","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:28.245Z"}
info: internal_launch_progress.session  {"data":{"text":"Connecting…","value":100},"eventName":"internal_launch_progress.session","eventNamespace":"internal_launch_progress","sessionId":"session","timestamp":"2022-09-06T09:28:28.245Z"}
- 100%:  Organizing messages
info: 100%:      Organizing messages  {"data":"100%:\t Organizing messages","eventName":"STARTUP.session","eventNamespace":"STARTUP","sessionId":"session","timestamp":"2022-09-06T09:28:29.105Z"}
info: internal_launch_progress.session  {"data":{"text":"Organizing messages","value":100},"eventName":"internal_launch_progress.session","eventNamespace":"internal_launch_progress","sessionId":"session","timestamp":"2022-09-06T09:28:29.105Z"}

**Comment by snikpic** [comment]
Hey @axixu, we are having the same issue. 
Have you been able to solve it ? If yes, could you please share with us how you did it ?

Thanks a ton for your help !

**Comment by axixu** [comment]
@snikpic No I did not solve it, you may try as @smashah solution, I hope it will solve your problem. 
Thanks
