### ISSUE TITLE
Advanced buttons with raw payload not working as expected

### ISSUE THREAD

**Issue by DaviZMelo** [open-wa/wa-automate-nodejs#2877]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

That's the code I'm trying to use.
```
        await client.B(cid, {
          templateMessage: {
            hydratedTemplate: {
              hydratedButtons: [
                {
                  index: 1,
                  urlButton: {
                    displayText: 'I am a link',
                    url: 'https://github.com/open-wa/wa-automate-nodejs',
                  },
                },
                {
                  index: 2,
                  callButton: {
                    displayText: 'Call me now!',
                    phoneNumber: '+1234567890',
                  },
                },
              ],
              hydratedContentText: 'content',
              hydratedFooterText: 'footerer',
            },
          },
        });
```

In Whatsapp Web it works ok

![image](https://user-images.githubusercontent.com/49699162/189131609-e6b615d0-a06a-47bb-9220-192a8d7adcd7.png)

But in the mobile app it just look like it

![image](https://user-images.githubusercontent.com/49699162/189131739-9f29fd1c-19e5-4067-9b2e-ade01d931794.png)

### Steps To Reproduce

Just try to use this following code:

```
        await client.B(cid, {
          templateMessage: {
            hydratedTemplate: {
              hydratedButtons: [
                {
                  index: 1,
                  urlButton: {
                    displayText: 'I am a link',
                    url: 'https://github.com/open-wa/wa-automate-nodejs',
                  },
                },
                {
                  index: 2,
                  callButton: {
                    displayText: 'Call me now!',
                    phoneNumber: '+1234567890',
                  },
                },
              ],
              hydratedContentText: 'content',
              hydratedFooterText: 'footerer',
            },
          },
        });
```

### create() code OR full CLI command + CONFIG

```markdown
create({
      session: 'arti-whatsapp',
      licenseKey: 'some-valid-license-key',
      useChrome: true,
      chromiumArgs: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--aggressive-cache-discard',
        '--disable-cache',
        '--disable-application-cache',
        '--disable-offline-load-stale-cache',
        '--disk-cache-size=0',
      ],
    })
```

### DEBUG INFO

```markdown
┌─────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                   Values                                                                   │
├─────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2232.8'                                                                 │
│       PAGE_UA       │ 'WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                  '4.46.2'                                                                  │
│   BROWSER_VERSION   │                                                      'HeadlessChrome/105.0.5195.102'                                                       │
│         OS          │                                                                'Windows 10'                                                                │
│      START_TS       │                                                               1662635547550                                                                │
│      RAM_INFO       │                                                      'Total: 8.54 GB | Free: 0.28 GB'                                                      │
│    PPTR_VERSION     │                                                                  '15.0.0'                                                                  │
```

### Environment

```markdown
- OS: Windows 11
- Node: v16.13.0
- npm: 8.5.5
```

**Comment by smashah** [comment]
what device is that screenshot from? iOS or android? Also what versions?

WA is cracking down on buttons. Everytime I try to fix it a few weeks later they implement some sort of block to prevent end devices from being able to see buttons despite them being sent from the session just fine.

At a certain point these buttons will stop working.

**Comment by smashah** [comment]
I've just checked with:

`android beta personal ====> android business`

and it is working as expected.

If you are sending to iOS try clearing the iOS cache:

https://www.macrumors.com/how-to/clear-cache-iphone-ipad/

**Comment by DaviZMelo** [comment]
The device from the screenshots is an iPhone 13/IOS 15.6.1. I will try clear the cache, thanks

**Comment by DaviZMelo** [comment]
Sorry, should I clear the cache of the app receiving the message or the one sending it?

**Comment by smashah** [comment]
@DaviZMelo The issue is not on the sender side. WA is literally blocking the recipient app from rendering buttons messages from non-verified accounts. So you have to clear the cache of the recipient device.

**Comment by DaviZMelo** [comment]
@smashah got it, thanks. By "unverified accounts" do you mean this problem won't happen if I don't use Whatsapp business?

**Comment by smashah** [comment]
Green tick = verified wa business account

**Comment by DaviZMelo** [comment]
Yup but a personal wa account isn't going to be verified anyway so the buttons are supposed to work on it?

**Comment by smashah** [comment]
@DaviZMelo as I said, there is a workaround in place right now. It works on my android personal accounts - sending and receiving FOR NOW. 

Pre-workaroubd they would block the message on the recipient device by blocking the rendering of buttons if the sender is not verified.

**Comment by DaviZMelo** [comment]
@smashah okay, thank you.
