### ISSUE TITLE
Session data most likely expired due to manual host account logout. Please re-authenticate this session.

### ISSUE THREAD

**Issue by shifoc** [open-wa/wa-automate-nodejs#2878]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

I often get this error "Session data most likely expired due to manual host account logout. Please re-authenticate this session." after restarting 

### Steps To Reproduce

Restart the bot

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2232.8",
  "WA_AUTOMATE_VERSION": "4.46.2",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4896.88",
  "START_TS": 1662713055307,
  "RAM_INFO": "Total: 1.01 GB | Free: 0.45 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Linux 5.15
- Node: 17.9.0
- npm: 8.5.5
```

**Comment by shifoc** [comment]
I think it's only happening when I restart the bot from crontab

**Comment by smashah** [comment]
please update to the latest version and try again. if it is still happening report back with more context.
