### ISSUE TITLE
/getAllGroups not returning any groups

### ISSUE THREAD

**Issue by scropion86** [open-wa/wa-automate-nodejs#2879]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

when calling the API `/getAllGroups` the response is empty array

```
{
  "success": true,
  "response": []
}
```

### Expected Behavior

should return all the groups which i am member of

### Steps To Reproduce

```
curl -X 'POST' \
  'https://myserver/getAllGroups' \
  -H 'accept: */*' \
  -H 'api_key: my api key' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": {
    "withNewMessagesOnly": "false"
  }
}'
```

### create() code OR full CLI command + CONFIG

```markdown
n/a
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2232.8",
  "WA_AUTOMATE_VERSION": "4.46.2",
  "BROWSER_VERSION": "HeadlessChrome/103.0.5058.0",
  "START_TS": 1662882665090,
  "RAM_INFO": "Total: 1.07 GB | Free: 0.81 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "97ec0",
  "LAUNCH_TIME_MS": 31788,
  "ACC_TYPE": "PERSONAL",
  "chats": 151,
  "messages": 61,
  "contacts": 596,
  "isMd": true,
  "INSTANCE_ID": "9ed69352-b9c1-42fa-8342-80adb2be2900"
}
```

### Environment

```markdown
- Ubuntu 22.04
- OS: Linux 5.2
- Node: 18.7.0
- npm: 8.15.0
```

**Comment by smashah** [comment]
@scropion86 

The reason you're getting an empty result is because you are using a string instead of a boolean. The string `"false"` resolves to `true` actually. You have to remove the `"` marks in order for the value to be false!

So if you want to get all the groups then do this:

```bash
curl -X 'POST' \
  'https://myserver/getAllGroups' \
  -H 'accept: */*' \
  -H 'api_key: my api key' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": {
    "withNewMessagesOnly": false
  }
}'
```

or omit the args altogether:

```bash
curl -X 'POST' \
  'https://myserver/getAllGroups' \
  -H 'accept: */*' \
  -H 'api_key: my api key' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": {}
}'
```
