### ISSUE TITLE
empty session file

### ISSUE THREAD

**Issue by ihervin** [open-wa/wa-automate-nodejs#2880]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

saved session data contain empty json object `{}`, this file checked right after successfully qrcode scan and after few minutes later. after issuing `client.logout(true)` and starting application again (with the same sessionid), application prompt again qrcode.

### Expected Behavior

After successfully login using qr-code, session data file (`[sesssionid].data.json`) should contain session info and after issuing logout using `client.logout(true)` , starting application should automatically signed-in using saved session data.

### Steps To Reproduce

1. start program using this config
```
{
   sessionId: 'xxxx:403497854',
    maxQr: 5,
    qrTimeout: 120,
    authTimeout: 30,
    useChrome: true,
    autoRefresh: true,
    cacheEnabled: false
}
```
3. start client
4. application created session data, but with empty json (base64 = `e30=` decoded into `{}` )
5. logout application using `client.logout()`
6. try restart application with same session-id, application prompt new qrCode
7. debugging session using 
8. debugging session using:
```
ev.on('sessionData.**', async (sessionData, sessionId, namespace) => {
   console.log(se
   // print { WASecretBundle: undefined, WAToken1: undefined, WAToken2: undefined }
})
```
9. debugging session using:
 ```
ev.on('sessionDataBase64.**', async (sessionDatastring, sessionId) => {
    console.log("session data base64 ", sessionId, sessionDatastring)
    // print e30=
})

```
### create() code OR full CLI command + CONFIG

```markdown
var client = await create({
    sessionId: 'xxxx:403497854',
    maxQr: 5,
    qrTimeout: 120,
    authTimeout: 30,
    useChrome: true,
    autoRefresh: true,
    cacheEnabled: false
})

await start(client)
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2232.8",
  "WA_AUTOMATE_VERSION": "4.46.2",
  "BROWSER_VERSION": "HeadlessChrome/105.0.5195.102",
  "START_TS": 1662893649236,
  "RAM_INFO": "Total: 17.18 GB | Free: 0.10 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "97ec0",
  "LAUNCH_TIME_MS": 50786,
  "ACC_TYPE": "PERSONAL",
  "chats": 39,
  "messages": 69,
  "contacts": 666,
  "isMd": true,
  "INSTANCE_ID": "fe0b3b51-507f-4616-bfb9-9d48ff9b36bb"
}
```

### Environment

```markdown
- OS: macOS Monterey
- Node: 16.17.0
- npm: 8.15.0
```

**Comment by smashah** [comment]
Your account is not legacy anymore. It's multi device now.

The session.data.json file is {} on MD sessions. It is a placeholder for when I figure out how to return to a JSON based authentication system. Till then MD relies on a folder (e.g `_IGNORE_session`)

**Comment by smashah** [comment]
Please track #2866
