### ISSUE TITLE
caption is undefined when there is none

### ISSUE THREAD

**Issue by shifoc** [open-wa/wa-automate-nodejs#2882]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

the caption is undefined instead of not having a caption

### Expected Behavior

no caption

### Steps To Reproduce

 await client.sendImage(message.from, './data/img.jpg', message.id);

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2232.8",
  "WA_AUTOMATE_VERSION": "4.46.2",
  "BROWSER_VERSION": "HeadlessChrome/100.0.4896.88",
  "START_TS": 1663095674468,
  "RAM_INFO": "Total: 1.01 GB | Free: 0.44 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Linux 5.15
- Node: 17.9.0
- npm: 8.5.5
```

**Comment by smashah** [comment]
@shifoc can you show a screenshot of the issue and how it is supposed to look please
