### ISSUE TITLE
Restore session broken

### ISSUE THREAD

**Issue by DevSamuelOliveira** [open-wa/wa-automate-nodejs#2883]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Tested and experienced on both

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

every time i start the bot i need to authenticate

### Expected Behavior

auto-authenticate if session name is the same

### Steps To Reproduce

just run

### create() code OR full CLI command + CONFIG

```markdown
{
  sessionId: 'session1',
}
```

### DEBUG INFO

```markdown
'2.2232.8'
'WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36'
'4.46.2'
'HeadlessChrome/103.0.5058.0'
'Linux 5.10'
1663161200898
'Total: 8.24 GB | Free: 5.94 GB'
'15.0.0'
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Node: 18.0.0
- npm: 8.6.0
```

**Comment by smashah** [comment]
@DevSamuelOliveira 

step 1. delete your `_IGNORE_...` folder

Step 2. Start your session

Step 3. WAIT 5 MINUTES. SEND SOME MESSAGES TO AND FROM YOUR SESSION 

Step 4. Restart your process.

If it continues then please try again with more logs + code/CLI command

**Comment by smashah** [comment]
> @smashah, Hi, its possible to delete _IGNORE_ Folder to when we set 'deleteSessionDataOnLogout: true' on configObject,.?
> 
> its send message : ✖ Session data most likely expired due to manual host account logout. Please re-authenticate this session.

This is already the case.

If it continues to not delete the session folder when deleteSessionDataOnLogout is `true` please use the CLI with `-v` to replicate the problem and then submit a new issue with the logs.

**Comment by crescent1** [comment]
@smashah Hi,  `_IGNORE_` deleted after add `killClientOnLogout: true` on config. thank you.
