### ISSUE TITLE
Send Location not working. WAPI.js typo?

### ISSUE THREAD

**Issue by JoeDozan24** [open-wa/wa-automate-nodejs#289]
**Describe the bug**
Send Location not working

**Steps to Reproduce**
1. Use `headless: false`
2. sulla.create like usual
3. try to send location with lat, lng, loc
4. Promise error on Devmode Chromium

**Expected behavior**
Location sent

**DEBUG INFO**
```
Debug Info {
  WA_VERSION: '0.4.2088',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10
7.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.8.41',
  BROWSER_VERSION: 'Chrome/80.0.3987.0'
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/58735845/78776892-c2f9f980-79c2-11ea-881e-f7ca04e5bca5.png)

**Host (please complete the following information):**
 - OS: Windows

**Additional context**
Written on wapi.js:
```js
window.WAPI.sendLocation = async function (chatId, lat, lng, loc) {
    var chat = Store.Chat.get(chatId);
    var tempMsg = Object.create(Store.Msg.models.filter(msg => msg.x_isSentByMe && !msg.quotedMsg)[0]);
    var newId = window.WAPI.getNewMessageId(chatId);
```

should it be like this?
```js
window.WAPI.sendLocation = async function (chatId, lat, lng, loc) {
    var chat = Store.Chat.get(chatId);
    var tempMsg = Object.create(Store.Msg.models.filter(msg => msg.__x_isSentByMe && !msg.quotedMsg)[0]);
    var newId = window.WAPI.getNewMessageId(chatId);
```

**Comment by JoeDozan24** [comment]
chanced it into `msg.__x_isSentByMe and it works..

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.42](https://github.com/smashah/sulla/compare/1.8.41...1.8.42) (2020-04-08)

- Bump prettier from 2.0.3 to 2.0.4 [`#285`](https://github.com/smashah/sulla/pull/285)
- Release 1.8.42 [`8fb0f7c`](https://github.com/smashah/sulla/commit/8fb0f7c132d8738b01fb6d5745f2f7375ba16727)
- fix for #289 & added deprecation message [`dadd9a0`](https://github.com/smashah/sulla/commit/dadd9a0624c548df7296140f5c7ecbeef3fe3671)
- readme fix [`17b8c93`](https://github.com/smashah/sulla/commit/17b8c93ef0d0a7a9308462d8729ad9feb5d435cc)
- update readme with better membership instructions [`5716bce`](https://github.com/smashah/sulla/commit/5716bce1c749dbbedcc3ff999b63da0c1e3d3315)

**Comment by smashah** [comment]
@JoeDozan24 thanks for bringing this up. Please let me know if the new version works for you.

**Comment by JoeDozan24** [comment]
It works. Thanks

**Comment by smashah** [comment]
@JoeDozan24 awesome. Also, please migrate to using the `@open-wa/wa-automate` package. Thanks
