### ISSUE TITLE
Amazon URL does not generate image thumbnail in link preview endpoint

### ISSUE THREAD

**Issue by khushdadhaniya** [open-wa/wa-automate-nodejs#2897]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

Amazon URL does not show link preview, it was working perfectly fine till yesterday but suddenly stopped working. 
Currently it displays title, description etc. but image thumbnail not generating

### Expected Behavior

Amazon link should generate image thumbnail 

### Steps To Reproduce

use following Amazon link to reproduce issue

https://amzn.to/3SswFxn

### DEBUG INFO

```markdown
NA
```

### Environment

```markdown
OS: Ubuntu 20.04
Node: 13.14.0
npm: 7.6.3
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/64799317/193397879-42fc9e37-394b-4101-b57e-94dc6467d637.png)

**Comment by manojsitapara** [comment]
+1

**Comment by smashah** [comment]
thanks for the PR @manojsitapara 

should be fixed now
