### ISSUE TITLE
publishing status

### ISSUE THREAD

**Issue by itzharDev** [open-wa/wa-automate-nodejs#290]
**Feature request**
I tried to send status

this code helps to get all broadcasts and user status among them
```javascript
const contacts = await client.getAllContacts();
for (const contact of contacts) {
    if (contact.id.server === 'broadcast' && contact.id._serialized !== 'status@broadcast') {
        console.log(contact)
    }
}
```

which mean `status@broadcast` is also broadcast

when sending message to broadcast evrything works just greate: text, media, location etc.

we need to add ability for 'status@broadcast' as:
`await client.sendText("status@broadcast", "test");`
and figure out how to do that.
let me help invastigate it if you need some help

i assume we need to select background color for text status, limit video length for 15 seconds etc.
i dont see any option to do that by whatsapp web write now

**Comment by smashah** [comment]
@itzharDev is this referring to the same status in #293 (like a Snapchat story)?

**Comment by itzharDev** [comment]
Yes. That's the story I'm talking about

**Comment by smashah** [comment]
From my investigation, I've found some status specific attributes for text statuses:

```
font: '1' (1/2/3/4 etc. represent different fonts)
textColor: 4294967295 (some random number - need to find the function that converts rgb to this special whatsapp number) 
backgroundColor: 4294937228 (same)
__x_statusV3TextBg: "rgba(193, 160, 63, 255)"
```

**Comment by itzharDev** [comment]
great. let me know where it is ill try to figure it out

**Comment by smashah** [comment]
I was extremely close to giving up on this.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.52](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.51...1.8.52) (2020-04-11)

- Release 1.8.52 [`f247f70`](https://github.com/open-wa/wa-automate-nodejs/commit/f247f70a68324f9e2c89864bc8d61c68e98c0f9a)
- implemented `postStatus` #290 [`9f4a46f`](https://github.com/open-wa/wa-automate-nodejs/commit/9f4a46f7508e2870cfad562d6789ace94adf3c3d)

**Comment by smashah** [comment]
@itzharDev Almost gave up on this one.

```
  const statusResult = await client.postStatus('test!!!!');
  console.log(statusResult);
  // { status: 200, t: 1586626288 }  
```

This feature is behind a paywall currently and will be GA on May 1, 2020. Please read the docs for more info.

https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#poststatus

**Comment by impozzible** [comment]
Works perfectly

**Comment by smashah** [comment]
TODO:

- getMyStatusArray() //return all current status objects
- deleteStatus(id) //delete a status
- deleteAllStatus() //clear out my story, remove all statuses

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.53](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.52...1.8.53) (2020-04-12)

- Release 1.8.53 [`22a6dc8`](https://github.com/open-wa/wa-automate-nodejs/commit/22a6dc8f665f7cdefe63864f32a909d8b63f8629)
- `getMyStatusArray` + `deleteAllStatus` + `deleteStatus` #290 [`b37ed76`](https://github.com/open-wa/wa-automate-nodejs/commit/b37ed762c5c0d3928e46f437564d5f8ef9c982bd)

**Comment by smashah** [comment]
https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#getmystatusarray
https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#deletestatus
https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#deleteallstatus

@impozzible @itzharDev

**Comment by smashah** [comment]
Closing for now as the initial issue is now resolved. If there are more problems please make a new issue.
