### ISSUE TITLE
Unexported types.

### ISSUE THREAD

**Issue by UnpopularOpinion** [open-wa/wa-automate-nodejs#2902]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Tested and experienced on both

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

I'm using typescript for type assertions. Experienced the following issue:

> type wa.Call = /*unresolved*/ any
> Namespace '"c:/Projects/NodeJs/wa-bot-personal/node_modules/@open-wa/wa-automate/dist/index"' has no exported member 'Call'.ts(2694)

I checked several types (not all) but from what I'm experiencing, these are the unexported types:
- ParticipantChangedEventModel
- Call

### Expected Behavior

Types can be imported.

### Steps To Reproduce

Sample code:
` import * as wa from "@open-wa/wa-automate";
 client.onGlobalParticipantsChanged(async (participantChangedEvent: wa.ParticipantChangedEventModel) => {
    console.log("onGlobalParticipantsChanged()", participantChangedEvent);
  });

  client.onIncomingCall((call: wa.Call) => {
    console.log("onIncomingCall()", call.id);
  });`

### create() code OR full CLI command + CONFIG

```markdown
const waConfig: wa.ConfigObject = {
  sessionId: "session-testing",
  useChrome: true,
  multiDevice: true,
  cacheEnabled: false,
  logConsole: false,
  headless: true,
  popup: true,
  hostNotificationLang: wa.NotificationLanguage.ENGB,
  qrTimeout: 0,
  authTimeout: 60,
};

wa.create(waConfig)
  .then((client) => start(client))
  .catch((e) => {
    console.log("Error", e.message);
  });
```

### DEBUG INFO

```markdown
> type wa.Call = /*unresolved*/ any
> Namespace '"c:/Projects/NodeJs/wa-bot-personal/node_modules/@open-wa/wa-automate/dist/index"' has no exported member 'Call'.ts(2694)

![image](https://user-images.githubusercontent.com/48537975/194759601-4ed49944-3be5-4a4a-aaba-09b06d3c1904.png)
```

### Environment

```markdown
- OS: Windows 10 Home v21H2
- Node: v16.17.1
- npm: 8.15.0
```

### Anything else?

Was instructed to create issue from the discord.

**Comment by smashah** [comment]
https://github.com/open-wa/wa-automate-nodejs/issues/2907#issuecomment-1274921208
