### ISSUE TITLE
Buttons and messageList are raising error

### ISSUE THREAD

**Issue by aymenitc** [open-wa/wa-automate-nodejs#2904]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

Buttons and messageList are raising error. it was working fine yesterday.

the error:
`[ERROR] Error: Evaluation failed: TypeError: mmrrf(...) is not a function
    at eval (eval at <anonymous> (:1:10), <anonymous>:1:98818)
    at Array.map (<anonymous>)
    at eval (eval at <anonymous> (:1:10), <anonymous>:1:98302)
    at ExecutionContext._ExecutionContext_evaluate (/home/aymenitc/whatsapp-bot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:228:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/aymenitc/whatsapp-bot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
`

### Expected Behavior

show Buttons

### Steps To Reproduce

    await client.sendButtons( from, "Hi, how can I help you?\n ", [
                 {
                  id: "1",
                  "text": "!help"
                  },
                  {
                  id: "2",
                  "text": "list"
                  },
                  {
                  id: "3",
                  "text": "!contact"
                  }
             ], "welcome", "At")

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2238.6",
  "WA_AUTOMATE_VERSION": "4.47.0",
  "BROWSER_VERSION": "HeadlessChrome/105.0.5195.125",
  "START_TS": 1665386575988,
  "RAM_INFO": "Total: 4.08 GB | Free: 2.10 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "CACHED-e6792",
  "LAUNCH_TIME_MS": 37324,
  "ACC_TYPE": "PERSONAL",
  "chats": 144,
  "messages": 362,
  "contacts": 6068,
  "isMd": true,
  "INSTANCE_ID": "4f054c45-4701-4805-9288-9bb6ef1577d9"
}
```

### Environment

```markdown
- OS: Linux 5.15
- Node: 16.17.0
- npm: 8.1.0
```

**Comment by smashah** [comment]
fixed. please restart and try again
