### ISSUE TITLE
feat: `onCallState`

### ISSUE THREAD

**Issue by UnpopularOpinion** [open-wa/wa-automate-nodejs#2905]
It would be a great feature to have a way of knowing whether a call was answered or missed. (Issue created per instructed in discord).

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.47.4](https://github.com/open-wa/wa-automate-nodejs/compare/4.47.3...4.47.4) (2022-10-17)

- ✨ feat: `onCallState` #2905 [`04d78e2`](https://github.com/open-wa/wa-automate-nodejs/commit/04d78e2375576e6d0f0a60b7665598c4b30d4a61)
- Release 4.47.4 [`a772b05`](https://github.com/open-wa/wa-automate-nodejs/commit/a772b051626ae437b145ba3a268a6bdf89c9620d)
- updated types-only package [`733de95`](https://github.com/open-wa/wa-automate-nodejs/commit/733de95c2dbb4f5a1d879e1a1733e3c5c27b099e)
- 🔧 CLI: set `--disable-spins` when `-v` #2915 [`0e7a61d`](https://github.com/open-wa/wa-automate-nodejs/commit/0e7a61d893e2740ac9912fa9788b2f6ce33a780a)

**Comment by smashah** [comment]
@UnpopularOpinion 

https://openwa.dev/docs/api/classes/api_Client.Client#oncallstate

https://openwa.dev/docs/api/enums/api_model_call.CallState
