### ISSUE TITLE
Out of Control Recurrent Message Sending to some numbers

### ISSUE THREAD

**Issue by mesutyigit** [open-wa/wa-automate-nodejs#2913]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

After integrating with easy api, it sends the same messages to some numbers at certain intervals, continuously, unintentionally.

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/11429147/196131247-bc21afef-0008-433c-a18a-d343b83d2b29.png">

### Expected Behavior

Should not happen this issue. 

### Steps To Reproduce

1. up with npx easy api cli.
2. continue to   general use 
3. track to sending message that out of control 

### create() code OR full CLI command + CONFIG

```markdown
npx @open-wa/wa-automate -h 0.0.0.0 -p 8653 -e http://localhost:80/bot/626a81dbb48d41771060f3bd/launch-event --ready-webhook  http://localhost:80/bot/626a81dbb48d41771060f3bd/ready-event  --webhook https://socket.supsis.live/webhook/whatsapp/626a81dbb48d41771060f3bd -a -d  --multi-device  --skip-save-postman-collection --cache-enabled false     --skip-update-check --session-id 626a81dbb48d41771060f3bd --session-data-path /home/ec2-user/temp/626a81dbb48d41771060f3bd --popup --qr-timeout 60 --auth-timeout 60 --kill-process-on-timeout  --throw-on-expired-session-data  --delete-session-data-on-logout   > /home/ec2-user/temp/626a81dbb48d41771060f3bd.log
```

### DEBUG INFO

```markdown
WA_VERSION:'2.2238.7'
PAGE_UA:'WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36'
WA_AUTOMATE_VERSION:'4.46.2'
BROWSER_VERSION:'HeadlessChrome/103.0.5058.0'
OS:'Linux 4.14'
START_TS:1665997458275
RAM_INFO:'Total: 16.67 GB | Free: 8.73 GB'
PPTR_VERSION:'15.0.0'
```

### Environment

```markdown
- OS: Amazon Linux 2
- Node: 17.5.0
- npm: 8.5.1
```

### Screenshots/Logs

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/11429147/196134721-17bba02e-e5c1-45e0-94d4-a92d6d61c565.png">

### Anything else?
* This issue sometimes fires. This is not reproducible with manual methods.  
* I'm paid customer , I've 2 license key (2 restricted)
_No response_

**Comment by smashah** [comment]
What?? There no built in retries. Are you sure this isn't externally triggered???

Please use the --verbose flag, replicate this strange behavior and then share the subsequent logs.

Thanks

**Comment by mesutyigit** [comment]
sorry, have this problem for a month. when we deep trace to events , we found main reason of problem. It's not releated with wa-automate. I'm closing to issue. Thanks @smashah
