### ISSUE TITLE
Bought license key but forgot to enter number in notes

### ISSUE THREAD

**Issue by alishahlakhani** [open-wa/wa-automate-nodejs#292]
I am really sorry, it's too late here and I bought a membership for month but forgot to add in notes :( did I waste my 5 GBP? 😭😭😭😭

**Comment by alishahlakhani** [comment]
It shows this **Ali Shah Lakhani is now a member** but no way to edit or add notes :(

**Comment by smashah** [comment]
@alishahlakhani I'll email you

**Comment by alishahlakhani** [comment]
@smashah Thanks man. it's alishah.lakhani1@gmail.com
