### ISSUE TITLE
How to get Reply to Status

### ISSUE THREAD

**Issue by impozzible** [open-wa/wa-automate-nodejs#293]
**Describe the bug**

**Steps to Reproduce**
1. Go to 'Status Uploaded by Whatsapp Bot Number'
2. Reply To the status
3. Bot does not identify the reply

**Expected behavior**
Bot should able to identify the reply sent via status reply also

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by smashah** [comment]
Hey @impozzible please share screenshots of the process in Whatsapp web as I've personally never used the feature. Thanks

**Comment by impozzible** [comment]
<img width="1679" alt="Screenshot 2020-04-09 at 10 27 40 AM" src="https://user-images.githubusercontent.com/30698707/78880156-e23d6900-7a4c-11ea-8456-c83d13d88b7e.png">
<img width="1659" alt="Screenshot 2020-04-09 at 10 27 58 AM" src="https://user-images.githubusercontent.com/30698707/78880165-e79ab380-7a4c-11ea-99a2-f402c92c2127.png">
<img width="1653" alt="Screenshot 2020-04-09 at 10 28 08 AM" src="https://user-images.githubusercontent.com/30698707/78880178-eb2e3a80-7a4c-11ea-8b03-9235429096b8.png">
<img width="972" alt="Screenshot 2020-04-09 at 10 28 21 AM" src="https://user-images.githubusercontent.com/30698707/78880194-ef5a5800-7a4c-11ea-8ab5-6a7d14dc7af6.png">

**Comment by impozzible** [comment]
@smashah

**Comment by smashah** [comment]
Thanks for the screenshots @impozzible I'll look into it

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.45](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.44...1.8.45) (2020-04-10)

- Bump release-it from 13.5.1 to 13.5.2 [`#288`](https://github.com/open-wa/wa-automate-nodejs/pull/288)
- Release 1.8.45 [`3557bbb`](https://github.com/open-wa/wa-automate-nodejs/commit/3557bbbd63a95d788c692ae2541d2c10e665b69c)
- Update documentation [`0797ad5`](https://github.com/open-wa/wa-automate-nodejs/commit/0797ad5dbc2b22a4e6ce78f4c22e2c964c369a01)
- edited comment-run action [`8bc7a57`](https://github.com/open-wa/wa-automate-nodejs/commit/8bc7a57220ca6d853e39a60ca891ed8a5187e916)
- possible fix for #293 [`e823e0c`](https://github.com/open-wa/wa-automate-nodejs/commit/e823e0c387773ee07a1fb0ea690a80f7a2f46255)
- updated supported wa version to 2.2013.6 [`519dff6`](https://github.com/open-wa/wa-automate-nodejs/commit/519dff6a5d9f9d79905fdec8a174c75de3b3881f)

**Comment by smashah** [comment]
@impozzible can you try the latest version please and confirm if the problem is fixed for you thanks

**Comment by impozzible** [comment]
Yes confirmed fixed in the latest version
