### ISSUE TITLE
sendMessageWithThumb is not sending messages

### ISSUE THREAD

**Issue by MarceloSkank** [open-wa/wa-automate-nodejs#2932]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

the method sendMessageWithThumb is not sending the messages to groups

### Steps To Reproduce

.curl -X POST http://localhost/sendMessageWithThumb -d '{"args": {"thumb":"data:image;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wgARCAEsASwDASIAAhEBAxEB/8QAHAABAAIDAQEBAAAAAAAAAAAAAAMEAgUGBwEI/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/2gAMAwEAAhADEAAAAfVAAAAAAAAMa3mxcrcp8PWui8DuHuLznrDdAAAAAAAAAAAAAAV5vJjRZ6zaEfzKco17WZBNDmbfrPOJz2jZeGbk9afPoAAAAAAAAAAOPNTydjA1GyobArSYzFeG8KEsv0r5zZF7nOg0dnsPR8R28oAAAAAAAAAplDz7Z0inBbhNLep3Cpep2jPPHMw+2vhWwuCDU9FqTsvQPNPSwAAAAAAAAfDDkNloypja3Bp9D1PPHO24Zijf12xJcmZ8+5fT7JnkY6nca8v+reP+wAAAAAAAADUz6EhjzpGzn1Nsw0251xyuf3Ep7TWbU+fc/onj+kmcWRPWsxGq9r8K91AAAAAAAFazoypUeTneY6qyX5tbmbn5hZONgkwKmz1m1M8sPpPlhIfZcZD7FYxOR988B95JgAAAAAAOZ6bkzmdfsdqcxsdvsDk983ZrMdtrDz75NEUtzpduZyY5EsmEhnNHMZssjhvcfD/aDagAAAAAA+ch1vHlaX5KQTQ/Sj0/L9QZ6/YUThKM1YrbnTbgkkhmJssMyWaCYsPv04j17yP1U6QAAAAAAEXH9doDS3dRsjFjkaXtPPO/J6dqqcFr7FUrbrRbwymhmJJIsyaxVtE33GY4f03zX0I7QAAAAAAFblOq5Y4/X9FxpuftXQnad14p6SdLWwyPOql+gU97oN6ZzQyn2WGYltVpS1PVnOP7XjOoPSgAAAAAAU+Y6XmjU8z1emOd1t+gR4/Yz1DfaDenn9G3SKe90G6LEsEpJLXlLEleQuz07Rzezo/T2UAAAAAAGu5zoefKOn3OrNLzXd8cUcJMT0vdaPbHCUrVEr7fT7YsSV8yxJWlLSLIvWtdaNZR2OgP0AAAAAAADU6Pc6cpUNjUKmo6D4eZT93bMLkGByFK1TINvptsTZQfSxLXlJ8oJCzYoTnzmOn5U/RElS2AAAAAAaLUbLUiH7EfcI4iSKOIlwgwOfp2KpDtNTszPKPInkqyFqSrmTS1pCzy3R82e87XQb8AAAAAA5fU39SfYfkJ9hxiMosYzLHDE0lWxWIdlrL5JlEJpK+RuvnSas0U9Gcs89udGe1dTxfaAAAAAAHEaq5rBChPsKMYMD7i+Gkry1jC9r7xJ9jyMpIsyTOLM+yQ5E2k3GlPWu+869FAAAAAAPN9bJwB2sWr9cPM8PSIDzzHvYDifk2rNVSziJJ99055599HlPNMvTMzzHLv/LjaZ6e0X603uBD0QAAAAAYxTjS6fshxU/XDi8O3+HCVfQoDxDQ+/wBA8Kg92yOL6/Y3DVy7eU5+p1uRwPlv6S+n5wvfoEeL+u2xHIAAAH//xAAyEAABBAEBBQYFBQADAAAAAAABAAIDBAUREBIhMjMGEyIwMUEUIyQ0QBUWIDVCJURQ/9oACAEBAAEFAvwXENGXy0ne1c9YYq2ZqToEEf8AgWrEVWH9Ulvyo8Aq9iaua2elaq2Tq2PzrEzK8OXuyXrGJ5WjVwZvBw+VqQg9ahVrliuq2dVe7XsflOIa3L3zemsDR+L5BzFSdPvt+z4TO9mh1KDkCq2WkqSg6j8fN5Dv3aaKxz4zkHF3i0Wi0TSWtHBM55K+k9tu5JgZu9pfjZq9ujd0RU/PjuRnOdm4tzgAtFu8WTPEuRO8ezJ8H4uSt9wwhFFTdSj02HxoBe+i0RatzRbpWRHyuzB8X4lqbuWTEvcQiiFP1KfSi6mnAahAjQALTYAgsoPp+y7vnfhyPDG2pC95CZE6R9yBkURCn6tTpR842f50XFaFcEFkh9P2YP1H4ROgtTakoMLjE0RtyHIQpx86sPlR8w2hBN9EGq+36fs075/4VmZHidNU0aAFXOUhWOvX6cHU3AuIGqBBWiGwK6Na/Z46Tfg2JdA46l5DRv8AESFNepzq0hWuvB063V26BaIa7NQVZ6WFO7J+BM/dD3bxlkbGHy77t5ByD007zSFc4WIeSv1BsH8AtNVIwd3jeEo9PPtP3pLEzIIr1yW1YglEsWq1WqrcWaK+dyzFyV+oNoXuhskGranC1CdYfPdzTt+Mufo8L308fLE19WVqEUm/ToCxW+GNbZlutFwZBz7RsCGw+kXDIUjrU8+U6R4+B0YcNWu8Rjfvph0yeJ+yu86ybS601V+Mm0IJqGw+nplMWdaHnH0sfbt4RPb8o80T/HkYwG4j7C51FecG2WlV+psCGxqbsPpP4cthTrQ85/Jb+1PhY4Duf9MPC/0sR/X2+ospxlaq/OdjdoQQR9LvDJ4E/RedL07v2sEvfQnTuh6s5Mk7R2J/r7XVV4B1n3rdTYPTYEE30WU4W+zx+T50/S/zjW7lHXiNVqNy1Wks3cL/AFdnqrIkiYKvzt2ex9QvYJuzNcJOzp8+x0bYLobLntXx1lqbkpgm5U92y9DvYgf8ZP1VkGl8h4KDmZsHKE31CadUNmcC7Nu+b51ro2eRzR3XjfPkYxXnKicGnH5unFUbYjs7LBPxLuCg5mbPYbWeoQWZ6XZp3z/Ot9KzyvHyt1/eXHufOSidmD/rlP8AcyKDmbsb6BBD0/031CzA+R2bd9R51zpWFL0q+u/ZBZMSidmE/rlN9xIoPVp2D0BXsE08UxZb7fs87SfzrvJMpOStvb1+Ilp124b+uUvXkUHqFqtU3Y1e7fRqyHGvgnaSede5ZVLyV9QXetlpil12YnhQ1UnVkUH8GHiEET4mng08LfGDEu08+8nqXkg9XDjei34tUyGSQUh3dTVO6kqg268Gpq18K/y08LHTx/BRneZ5t/mcpeWNFpC3UynE1261EreR5pVAvYbGoLXwIFA6Cbkp9Smd6p5uQ6m81O4j0XAIlEolarVe8qh2hNPEFa8CUECnHVtb7nFHex3m5A/OJRKJRKJRKJWq1XvKovT3CCbt9gUE70i4XcEdcX5uQP1BKJRKJRKJRK1WuyVReh2a7RUl+DtV5KsgKYiV/wB7s2dcd5uQP1JKJRKJRKJWu0KZR+hOz2BRPClZMOIzhd8Z7tOhBUnC52Xd9J5t8/VkolEolE/xHpMo/T+LCWonUha8VP8AcdlD4fNvH6slEolE/wAgpSmeSNlnn7J67/m3D9USiUf5l26EFvOW89bz1vSLekW9Kt6VayrelWsyfDLIcFW+Hx/m9qgWXZrMzZMCZbmTOKqFHDVSjhIEcExHAlZJnwFkWWav13vfD4iTJMHZiVDsw9fthftgL9stV/ACvS756716jLnNoh081fF1ID5m6EYmlWMbXsJ/Z6mVFg4oHGhMF8LYC7qyETaCfYtBZeR8jyn9Qc2BtmtUbkXlC89fGuTr7wnZWUKXMTOZ+n2kMXdKixV8NxOMuwW2yPKBP4eiLGlOgjKfRgcnYak9ft/Hlft/HpmHpsTaFdqFaELuo13bFutWg87/xAAXEQADAQAAAAAAAAAAAAAAAAABEVCA/9oACAEDAQE/AaYeNv/EABcRAAMBAAAAAAAAAAAAAAAAAAERUID/2gAIAQIBAT8BplY2/8QAPhAAAQICBQoCCAUDBQAAAAAAAQACAxEQEiExcQQgIjAyQVFhcoFAkRMjM0JSYqGxNHOSwdGCk+EUQ1Ciwv/aAAgBAQAGPwLwMzYF6PJnlgF8r1KM1sUeRUi/0TuD7FMXf8C6LHdVYFlLtiEyHNjf3oto9REczC5SyiGHjiywqTYlV3wvsPjnRIpk1qrvsYNlvBZX+UhgohN7Sg/c5Gn1UVwHC8KWUQu7P4Xqoon8JsPiiXGQCqs9g3ZHHmuyyv8AKXagM3ApsSOK497mtGdQuWjaKf5UMOiOdDJkWm1Ai4+IOTwT6obR+KnK/wApBC3zVoVi4FSqzRsBoDBvCbPcVVN8M1fDnJ4B0vfPDlmZV+WgpZl1Ie7SI4qtKU3KOMPDVIftT9MwrKvy12zirFdNd1E6R4Xi43BEkzJvOYVlPQghKi3OKxh+EmUZ3/aiq1Mqi3jQVlPRQKCgr1dS5QubT4O1fblRIKQQocsp6KBn2J2Cgdx4OzNFD1lHQuyssW4q0ZzsFA6/BSVqtovoFD1H6EMMy1WTW5XFWFOQ5RPBzccOamc56j7tFdtRajeFE5O8DLgnRIpk0L0hm0N2BwQeN+YcaIh5qP0oYakqOEw/KPAFZVAjCbWVWMkDMHiOaZUc8CUnBtpN/lgrIjXzNw3DjNPNWbW7xvQbUdWNoCD65acFVLg6dtETFRuhDDUlRgoJ+UeAeeRTy9wcYtU3l0+29ESnIXX+7wH3Rnb9eHYYqtPfaf8AO5Q52aH7JuJTcKHgcVG6UMNSU7mFBw15UTpKY0/C2w/wL8U8VbibKvLgLsVzn5WjsFOtynPHfcME2JbM6PK5Q+6GFEYusAKi9KGqbzTMTr3YKJggLrrNn3eF6lL3jISl9P5UrZzu4aXC4d1Wndvn8vG7sodnvcOXO1Ql2ojT+NROlNw1AohFEcHa92CiSBNm5CIG1Q4kfTjf2TRxPnpcPeTRvNwlPefd/lO3yb/58v3UE7i51tvDioGC7URQfiUTBN1UAqKPm17sE/pP2UOQtkSSBLfx/hcif16XmUBvcBZK+w7h90+VsgTuO7hd3WUuZFGgC611bcsm6KY0jLTTulM1UI81HGB17kQ11Wd5UP0DnShWznconrLXmZKBcxph3EXVjxPNNESEHGdvCXIcVlcRznetY4NrC1ZL0BGiOG3+kTsE3NOa3FRObBrygolkrE+bS8gVW27IUSDC2DI0OrCejJQYUT0gLGgHRXpYJmw76I3WUcE3MNJpGKbzh+ACcq0IWmwp5JDpnfmMxNEbrK7JuYaSjQ7kVk/SRr+6FEmi8pwpuUPvRF6zQzVRFk3VLXtxQo0eKrC8LdRcofeiL1n70NzSghS9QOUTXtpsoLd26mFRE6z96GZpQzHDkhyeNeymW6iYGk21f5U2QyRx3KE3gKInUfvQzVOT8U08RrmUyVshirifophjR2n91bbjbS/qP3oZmnNOCihQT8g1zcFKdqu81fLCxWZzsSgm6uIsnPy64Yao4oJuoFLlB5TH113bVHFBNzmZRo+jcZC1ejiyrSnYc3B51ztWEM0qGQyG9odVtPNCu5rnVfd3ZjVFHB/7a6JqwhnaJsO5TN+Y0rKRzB10XHVgKWrCyk7pDXReo63ZWwthbC2FsLYC2Qtlq2WoVpBMs0n6R1zCwltZm7FGUR0sVChRXF0O0uC2CP6iv9wf1KyJECsju8lZlH/VeifpXWhCx18kVJRHNiNhhhlaJr8Wz9Ctywf21+MP9tfjH/oC/FxP0hRo0OPEc9ja0iAr1tFTrlQmlx0nhqm2EHHi63X+tbWxWx9VWgaLuIKsiP8ANbb/ADXtH+a23LacmvizmOKPJ6ciqrTtOmr1etyuC9nNOYclLgRJWQXnsrMmieSI/wBLEUF8XJn1WOrFeycFsnwly2Va1Wwl7N36l7H6rRh/VWQ17MLYC2QtkK7Xf//EACoQAAIBAgQGAwEBAQEBAAAAAAABESExQVFhcRCBkaGxwTBA8NHhIPFQ/9oACAEBAAE/IfotL0i7ZjB1r2+WxC5vr/zIppuH5WEJibWa/wDgrY4l4vJZsiCXWRebUqoiW2qvcROhXBkKPTJNo7z0WIz89SdCKTZ+J/egi6WxQY8R0X+nc/ZEDMKgShZqa9B0GU6Id5VyShQUwxOphkyNieN9tjKSNf2/pHpn9BP7SUiUtuyRJBpu4zEIKN57LcBYU1GaSunzcfwaKNEQVGadRQFN4GQpmO0CkxoPbqpFukhQYLGEaYoU8SiU/sOqm08WWwucV7UUbz2IlHkYKcuA3My8qjR3E5pQcp5Me4pYpwSigPPAWUVXakC2Wqmt2OTuhY2RmoaYfXbUBROD2FAIJXsijd+ztxoT5iFXVEHdTSBukab51GQ55kJJUPk6DhkY2+1VhA4wjI54fz9aqFGmnMkbbbbdZeIogvYO8eyAIu9P6QNdPAsmhRyqZRLVBJqmqYCxE2UIVcNCnZu+qmVfldCUdpzOFGYlTlwk7ZTD+1IOdJidSGpGwk+xOVIYVIaGUuAtKlSWDTLT8U+ox9LMaDV30ZLgKSa4vBFchG5e74Cdko3PssbDUCICLQWS3MUEujQTlEw9aCVJto5YvpoY2hIdQvg8hOAznxbzKt/gdq8HWPs8AoSIv0KEi7gwnfIVmWw6OjqIt/sP6aIizDUmxu7KwqJc+BVv8Fex4O/eyDqSeocFTyQzOdgkpkW1RBRrYdCMIvRQ68ENtR+kh6PcZMJQKpcImyOdOAkb/o/NuVEThIw4SJwTIpVJTMZXi7CcX5VRPqCchJQbbvo09UbxyHSYYEDylwmbJDOgLIXCRkto+BCXnRch25kxsC5yT4GEY8hIwkEhE9xSDkMeLkPuPKPP6EwlqTyZfotRdmCi6f7KakKrJ4iCKP62QwtxROp9B1mTfyMUEu0aaCuXcCFuREj9Ec+ezWpnb6FWo2JQzqEhOuBzDS0S4PiyalQ4Kq2BAnkY1VxHAvXUS0rMaTi6C6J462oqRFqjBpQNFivygrSd/wCBiKkamEmXAriC1Iq+HXXF/Po2TEF0zsOxOmoWXMr2OpROkrfAkh2saXZjXCp1dilZpXjBOoqF1JI7OXsbajENukVzlYsx6+b+5UBouLv+SlLP4hIIWGiErC4cBg4Yqdkfg5Em2d/n7YeG/iBJ5DeAyobnBdhUdFZsca4noL92jvBvvul6pkUtCdWxw0fowLgomUalnWex3flwKB2SuLJJ4P0GhunomsieJXHArFheYGXkJsHo2Ejv89O4Hgauiyg4XywXa2Ys1BQobElTBtTyEpWwikUuViuaWoZZrcLcUlRfUh5c0uUp8Fx7DOxfllngVJWMNSePofk0LGLHhToLDj1PYIN5QiXMPr56d8S21JLuIhrisKiKlw5NT4UumFrk0dSbqXBkklMS0rRW6arFOi7HYUJVVVNKSY6uNT9OrPA4VRVMtu/B2PoWIrHmJtIn4LFxtYP0czY3p89BlRuTw9pirQ4jdrrqFDQrOKGrN3VQ9BGUabyeBqDc7s0JiJLyQ1hRsqQRUcxYSTDGnbeWXNlweEimeY1GrXFsPG16GmZMxGyXsTGDbhinMWEwgVfnDtyvVokwxICyiFiq8CoDwMamnMp4cil9odgnDFW4gENSYoJTYSxch1Y9DeDgiK8XgymJo6lZMn8D9H0VrkhPhM6zhTgKE9ygK2OyykimJlZj527Z3wvRI6oKUp1slYxt5HdtTSdawSzGNAbJuTodVSnqSMvQmUW4MLmF7xVzB2vowbESkK88ptcVho3ENEjyuYsseB/F5fPd3R3JzsSWkumyU3G/hlUr2GZLqaBO5+bnwb9OJU+Y7X0epLT5l0uTMaIY8hYGjIFTJK8eedg/nsCznLm5XSaDeVTVM2qYD9DQXXgbr+RI/wCXEbwxu1wXfmNAmZMtsPZbHUUE6zmNKZUrWSY6vnMS8JNbjcgglHU8jcW0wIA28l1HvKaMf6JH/DiHryfAtQY/ovE6bBp5BtomlBoQldkyfZHlfO3VZchKR1EtG5bFcrPkRgWKrAeZLqONDuXngb9uIvXMavIWJG6cC9Q1eCd++CcxNfMfO9m/FShByuxmQe9Z0GqxQ9CHKxvudC2s1YtMl4348Q9VzGryEypG+A1ZGoxXNB3FkJH/AGJ2EDUckNFR/M9DRlhplOo8zUEX/id69hicpnFXP+B0IU2nR14pv0Yi9Ho4GpUmY3LnsOUwbhrcfLR0AsA0fhc1Rb2+ZqH7Uek7pKWMoJ80eCqUg/WoqrRJvH/hVm8b/ViXhqGaPg52BXEiiIhDUTLxvMFKs5NtK+alfBAVWbyeq88aSWqXowMTrcmhgJEHxnIapFD3PzBV81ZonwAKDFxPc8jhgaqZMJCCdNibjje5SZgUVpminCaaaEiYnG7+EOsr79/N0teP+zAGGySx7vyWbuFoGA3VwOlGOLQ4bopBTXFThCqdLieDgFIaRqibXvVPm64vH/VANjY2TUard+S3fwisYF0K4rkmmKs9QxzW2dW8eC4Yj8wjZfZP6eQBsbHwxHo935FyDw0EyRO5iSZjYnC4G6FL9RKDWmda/NK39TxBhsbJ44ki9X5G5csetSq4kISNpDRGg4Aj1DQG3+g4kixkrSFwvp2+ZPunc4lr/Qi18CFcyUxSX/h4iBaOQHvNJ+jBHdWYS5/7H3M0ypXHqFNSlyZGTYpwBIWFTJxIn/T/AE9Mf6E+PSf0WL+DUWKI7jpIBxfsanhz8yy2VxuxMRP5z8rZdGHPqRzlKzawzbVe4wTUSJPdCP8Atwwj+yiH3joGiU6H/o0cz1KdwaoPkGV/HrgFzBwWLBaVDEBmSTsyZ0jeXYC9B0FjF6Ium+aGro+m0eCLgpdUMfyej5UJEubcJOLrFcRrcWILAKVboi/wyL+JFZOnzf/aAAwDAQACAAMAAAAQ88888888wkM088888888888888sgAccs8088888888888cAw8I4Uc8888888884sIMwUUkMc888888888EMYkoQw000888888888EQ0wM4kk8U88888888EE0AQAokE848888888swsYEwkgA0sk8888888Uw4sU8QI8Yg08888888ccU4IcIoo0cw8888888g8cAU0EA4Ek48888888M0skwccA4cAU88888880cU8U0AsQIwE8888888w0IEEQIE04MQ0888888ocMAMIYAcowgc888888ow4wgww0s4ssc888888owQ0YkUA4QsQU888888Q44YYg4Qo8Ac888888MMs88IgEY8kM8s888//EABYRAAMAAAAAAAAAAAAAAAAAAFBRgP/aAAgBAwEBPxAmyNv/xAAXEQADAQAAAAAAAAAAAAAAAAARMVCA/9oACAECAQE/EKZFjb//xAAqEAEAAgEDAgUFAQEBAQAAAAABABEhMUFRYaFxgZGxwRAw0eHwQPEgUP/aAAgBAQABPxD/AAn7O0UBHjAMx4LI041bsp+WH3otehGK0DCL0zfrDBpaLE6P/wAESuZyOwGqbBHKAlC5Mu+Omhobq04RqNq0tXdtuBVtOB17wRF4zYWayl8G26eLtek27ct5jmeSRXQODJwaHyWCII6/7TGWi1eAN1cBuw6SINrGvCzV8tIczFcLQ29Ah4oPAsZdVOHFs0CqoII2YrJW+t8tqqI31GolZowtZYdd8DZKR/3qFXkkrh7XO8X4FHFPuU+k+n+p5mn6AWq7ECozsOlVymhsdVmJ6Ie7BZIGmicceBFINkDXgfzAAAmGpkZ8kUemk05TpR4AdYgOOJYNqs3zi8+cC4WX5Z9MPoQlihuIoq8GGUStTgF14O0qF4Vnqpujo10h5iAaIlj/AKLkVBOBdHJfV6GanK1YEK2T3mYdwjQPRpzUCywCgs051j1XNbdOPHaMYLHTf084ZSaAahkfWLIasshxqP5lyi9UkUNiJ3N5hUFHiNa7xV+JhSjQ6dZU0Pq2R/UHuVC3qPY15f51mh2esaHkaux1cHpHhWn0v4TaefexFBHQD2j1OhWuhcGqG98xWBhsE0bZktLKwaPMwzbWk6cP5iay6pC1+cW7IIiYiozArQbWEelWK2y1tXLLux8wfH+a/M3lqc/rweehLxEUlqW1XfP1+oKNPZAldZ9qCC3ovmiVRywOvhFAqy3sgF0OLe82NTE+n5iaTpqeiQAoirSTHYQ0rPRxHpiqcr/J7S+lBwnX0lg3b/B/f+VcRYE3eXo39N47JJW7jwNK6V9IjXJZbKc19DCdPYSyKZd+kVABAp8o5ZlZdmhsygGnuZaQFBbMpi65PGXu4DRs2lSBo/CzK8P6iqKZqv70lIpmtfWC/sAJgW/W/wCRpAmAarYJdIOkONj+u7KiqgoLZTR5fxvBcqVM6Ar0xg0Pp0n6PIhLPpdI116X9peW1X2JRrXX4lKMXXx+oOwpdUw5qF1YgaDeMecKBKvXfZjcCzTJvzNPmxl74v6VKiurPyF+P8ZJAWrH46rXA5dWf2wieXVdA5YJPLl6vl6TCu30/kPwSzW1O0Z1xb+MIumhmHZjV7aSqnZ91zG8Y8Ugo7axOzIkqNBLGYJbLZqrbjSX82paUmOmJZ719d+SGn+FxrDWrOjnz4Rodpay1Bjl4m9t9U9SCtx8Wa0ooNEdk5X/ACghpbtCy6JbKV1oKrhxADg5MljR2sgGzJhw35ZhK0iuWfSBdwX3ZoO7dxIeMHhOPeULXI7S0XVfqqH+HEOMI36EZNlxXBxETVsHLF5NPR0gABdBzFGRecAwOLZ8GdGEDensiqnde0EEoFrXwhCW6D2jdDGC+0yCbl0+cAW45LmE3UGHo2QXojuW06fiLQJT0O2e0tI23U+jmOtZYssF1ZvzPx/hFkpW8HMsSw6IFG2RBoujdwx81GxoJ1J1Y5wxFuydmYWKx5TQWuGhNRAFKXozI+UdolDLDDU865S1qf8APxGUdb95nHwRLNWmsSjbS81GrYVYLhC8DhafJs4jMrfoinQ4P+DrLnV3gMAZXVOgbrYmcc1sA3fVVl300iC+gDR6xfHwiVvOvFZ6foNmfctCh8+UIlgtLXeWZWrQo7TN1D5S8eRLocQ2OJpkjmrmvSqdpa6MVUyfzeUGXRjfE/8APOf9ngf4LN1fNZixRggVw6xmCAGLvDv0G3mgta3rXU701dSZnkgAcGtYyKE21zwK8NGJkmaaLFidKGLtF0MDXRi5kgLAKyMtJeoVcZEpABHUZqThvaK4NfZiFvNAQdAzW1xpB8p3JmLnNQth2xApJzLs3U7peja9gr760LEHoI8NkY/aXbELCli1DcaVGWWqRWSIENyjQcWI5y4VFvQump0NkCMG9Au2zQGh2NSDru4ctPfth2mKfsMfhl7/AEKCszLVAt7TWRyLd44kV7QKl1D5mDwxqi6VcLv5wbjaWXwR3pvnvKWrR5gE6/pCwOqfz0nOA/Qj77pOE9p0M95FIE6RQvMwVuFFujYhq8Q6TZqyalV2lMyvKsLaELVKMDyC7mPiVGvUQWZyBG7VJEBnZRUIy1yeraHQ3Tvmg/mY6ooclppghAsoSG6ljFPpLU2ExYbVCUuzxGmDNTZZiBcTQBqlkVXebHb9xqDonqpX/wCg/P31a4Tsyw9Z60fMFoowHShbNTATSYVzjoi0jbTzWeqOfauRK2DO1M0YyShbZospKhidlTRqMUFrQOgOwMbYCYLy8s/B+7Eh/KQQ1cmka4Iqo7Qrp3UC+gTRTSviYXwNSoOmp7w8MXnwiqj+0l7MuuvmStjkSpVsNdoKjd3j8zmgPqL76tfxUzjAFuABaOhb5Qv5hzBEyW5vdmmwvamK7YHgLVKRUxQroXBNBWWxYyRN9oCn0Q10rqjghvqaCgQHpRoBMmhPVJk7px8kTEJTLVdaOIAAaKCjojvxZ3QGLriHI6TUzDngM+8MU2R8zb7pCDSPMa4NJHxEE9P+ThTYvpjrW631/T77t9UWRqmeMohHVwKN8C2VoqBkUZFAtACRRps1Qwl2SijTXFg5IK2IKAytwGdoY6jyDMBasfQAMpUxdYrOkdLaupBX/diOkYUyR1ByrrHvIs6tOvWWA4RYXKu8HHCb+yixghW0QkbY7y8VikjyXfVBhHVaPSUyQtUHeV6G5ft17T9911AdyXPYWRvo0mGL2Yldcq5AqaBtAEhQU1Qqr30RA3E9PXCg2JdS1GtdGl0IYb940S0IaoKNDjw5jUsV8kzu4HYjD5WKWqrXMHXA66Jm5Uy8ntKMXqvzDzxUUtamErDuecNJ2+E0Hb8fqAs4oIrHhlAdC/qTa4p/BPz9+jqI7kqk0jpd8MI8IoBjOfKW7sjLFaFJZObTrCUDXkG6C5q1hOzzKle8qF0yhjF5YGBlETUHdvktQDhzrcWAA6waue+0coUPtxwsAuBN+sAj5mIml17Q4Yzmjey95TMvU+JVFMdyPaZbNJhrv9oyhWrPjU4nQ9LfH33Rcl3mQdXtKrNECPiQBRN4L+bjSZa5B0ta4bcQLS70p7kBcs8KZ0UPOetbvlzM4/dl0rB8MdjtSLgDxO8ATYpFbvkRm2sS3sad2UCZFvsQ3c37kvJMaX6SxRzpGrabPG2UZv6Dt990PJ9mUQ8XtAbNPzIXWJKqjuz0uNlumLKpsZZbF4qfEvc+kii6vIlRZ6/jmLLHre75ma/ojCcHsmRz6+M3zksrDbMI2tvmJwtA95SBjHsPxGNWV8IuLBl7/iZVrLV2MHaVs/lqfMNPvVBz8WZ9AfeGoJtbt8eEdg0q63f9jZRvbNV+HGvrG2b+aRt23gYm8+QDFQVlglVlNZLlLzMGuf8AhM+qHtKB1CIadY0o1qKi5sO8egdlHnKgcKPeIRgEX0r4gg1KT+9Ze+P5jJyKoln+f98oHlu0A+BKqOV94nmrSKoNGIFodRWSO6znVleW2nlBfgIHkPIx0uR901mZautrBeh7JmP5iW9G3cjffNPsTBNVX2lZPCZBcBfciCdPlggrSkr1lBRqvcJkW5EO6QiMKHtP67U/EPvVeZ9obR6QY+fzCC3CiGCoBBfyZfwsBR/AZ8oqW1cgmYDVoB61d0uRdZ5qy6dzrvNDMua9ZFHgx6zG4Vn8TcNiu0QjxYQRtll3WEfUlAtoqlFqt2HrcsU3L3P1MAS6vX+bwbxWh/eE6pd7/if9mUH73gRu5NN3ga1ZzvoVL4hELdXtHMyTGe+A5fIYZlnod49kJm6tqDeLA8hKRW+01nIYHkEHmajO8tbl4LPtn6C25fEtybVMgHEOs93FITZU7RHb7RcuyxfgwCW6TXwjrTwz43M72VPaet3ovzP4KD96njWhlsaqgeQQ8UAq6HpZ7kLA/APcZesDamgMvi6s6k6k6s68cWd5l+fcxeo+0qbioBB1/wCS8lPSNjPHxLyOjADOR9oIWS3HkSwpdrp5ypDVvsS5DvUq1dU7R9LLufmfzWMfH3vAR92apeJrTrzrTUnWnU+k4G95qHf30dPjfaPs+8Ug2SVnxY6q2Lip3rhWdnzcAlXZe0yoOlxgZLH5g4Oz3Rso09yLrAe36nX49L7xg+H7yideZ2db6z1fpuDO8Nb+bTF432lXiHvKbGSNhKi3w95TfDhGrbS7mMA9hSAnFjmP61NBUoNngzGG5brKltf0SI/k+JRo4fup/wBVFPvGG4HsnXnI/wDj/qzWls1njFf8eUdLe72jryPeXBOnvBsRjcv9wMnMoXfPtBe/WUspKqrvLe5K/bZ+QCFN755MTM6H5iByay1W0ZMygtKP71madf8Ag6feu6Idn/pPOv8AVNDxn9lui9R7RV4/zLMD7JsHEwPSveJOjBLY0BKCGxrkY0Fyq1W2ruwtlO0MgXkhRRcXKNv8hL7ujeYfH3XSWZdGegH/AL+MUXMHDbM/it0RiWNvSWZs4eS/obPCUQsmjPDLopN3qzMdagceEuDywPGQu49ZHxv71VOKO6c8s/8ADDwi5iwcPGEtrUHLaIyWuZYBVmx4iYCOS6ZhdHWBNOcbyxs735lyUO39mDrWXr+4L6uv7lDrXl/cLTla/uAUGeD8wMEsg4N1zDuWnlUQC+QfFfuWcyzklDxwpULxvhLT8GwgIO/jHiIohbtWFmaazT3dN8z5AHuMv/MojL6Z+UJvT43xAFkgdELs5wiQEQIEUp5x08owLyrLWCwbsttl7C0KSqx6w4Ejo02Yn8Wwm1PgUHczwKH7mYDK1F7o6R6sX/JKIAo0xZAYsZBHsx4hWKo8NB6Qxp9tB1+lmoj4OI0bpBR0bxK+i3fyxWCiqVHa70xEFV/HM0qVpeHlTTW88ZbHDlG3Jra5PNAbHAeWFR/uPpQJVS0XoDtBRi+RC9XygJu8oK15ZhriuBmc2JgCO3DLPjlfgnxIZldJTDjxhm86ihkrPNQQ/uPM7+qfmCupX+GpqSeUtrvlDn0kBQy7NPxHLS9bHsI3PLW5Z+3xaH2loSrtHyrK2r5TGh8sBp6OGmDyw0B8BDQ7v/2Q==", "url": "https://google.com", "title" : "ola titulo", "description": "ola descricao", "text":"ola Texto", "chatId" : "xxxxxxxxx@c.us"}}'

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2241.7",
  "WA_AUTOMATE_VERSION": "4.48.0",
  "BROWSER_VERSION": "HeadlessChrome/106.0.5249.103",
  "START_TS": 1666968302445,
  "RAM_INFO": "Total: 13.22 GB | Free: 11.02 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": true
}
```

### Environment

```markdown
- OS: Linux 5.10
- Node: 18.7.0
- npm: 8.19.2
```

**Comment by smashah** [comment]
hi @MarceloSkank there is something wrong with your base64/dataurl

If you copy paste it in the url bar in google chrome and hit enter it should show you the image. but it is not working on the dataurl you provided:

<img width="1216" alt="CleanShot 2022-11-04 at 11 51 18@2x" src="https://user-images.githubusercontent.com/5903821/200053037-ef7a656b-1ff7-42f1-8d91-2a6ec23ba5f8.png">



what is the source image?

**Comment by smashah** [comment]
Please comment back when you have the source image ready. closing. thanks
