### ISSUE TITLE
Send /sendLinkWithAutoPreview

### ISSUE THREAD

**Issue by ihervin** [open-wa/wa-automate-nodejs#2937]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

Sending link with auto preview (/sendLinkWithAutoPreview) not working. Messages not shown at all in whatsapp browser nor in destination number. API response return "true".

### Expected Behavior

Messages sent with link preview. Messages id returned in API response.

### Steps To Reproduce

Sending using curl

```Shell
curl --location --request POST 'https://myserver.com/sendLinkWithAutoPreview' \
--header 'key: XXXXXX' \
--header 'Content-Type: application/json' \
--data-raw '{
    "args": {
        "to": "xxxxxxxx@c.us",
        "url": "https://www.republika.co.id/berita/rkq53j438/toni-kroos-tegaskan-ingin-pensiun-di-real-madrid",
        "text": "Hello World!"
    }
}'
```

```json
{
    "success": true
}
```

### create() code OR full CLI command + CONFIG

```markdown
npx @open-wa/wa-automate -p 8322 --auth-timeout 0 --qr-timeout 0 \
	-w '[server]' \
	-k '[api-key]' --cache-enabled false --use-chrome \
	--headful --license-key "[license]"
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2241.7",
  "WA_AUTOMATE_VERSION": "4.49.1",
  "BROWSER_VERSION": "Chrome/102.0.5005.61",
  "START_TS": 1667397778214,
  "RAM_INFO": "Total: 67.49 GB | Free: 21.10 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "43f33",
  "LAUNCH_TIME_MS": 36883,
  "ACC_TYPE": "BUSINESS",
  "chats": 2689,
  "messages": 120,
  "contacts": 19939,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "176d238a-0665-4b60-be72-3e20ed26a8d6"
}
```

### Environment

```markdown
- OS: Linux 4.19
- Node: 16.17.0
- npm: 8.15.0
```

**Comment by smashah** [comment]
should be patched please try again
