### ISSUE TITLE
setGroupDescription throws error

### ISSUE THREAD

**Issue by fukumori** [open-wa/wa-automate-nodejs#2938]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

Nov  4 08:17:03 [100742]: info: MDLWR - setGroupDescription : {"args":{"groupId":"xxx@g.us","description":"some description" {"timestamp":"2022-11-04T11:17:03.270Z"}
Nov  4 08:17:03 [100742]: info: methodArgs: groupId,description {"timestamp":"2022-11-04T11:17:03.273Z"}
Nov  4 08:17:03 [100742]: info: IN 65b73  {"_args":{"description":"some description","groupId":"xxx@g.us"},"_method":"setGroupDescription","timestamp":"2022-11-04T11:17:03.278Z"}
Nov  4 08:17:03 [100742]: middleware -> error Error: Evaluation failed: V
Nov  4 08:17:03 [100742]:     at ExecutionContext._ExecutionContext_evaluate (/root/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
Nov  4 08:17:03 [100742]:     at runMicrotasks (<anonymous>)
Nov  4 08:17:03 [100742]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Nov  4 08:17:03 [100742]:     at async ExecutionContext.evaluate (/root/wa-automate/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)

### Steps To Reproduce

Just call method

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2242.6",
  "WA_AUTOMATE_VERSION": "4.49.1",
  "BROWSER_VERSION": "HeadlessChrome/107.0.5304.87",
  "START_TS": 1667560860674,
  "RAM_INFO": "Total: 4.11 GB | Free: 3.49 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "57efa",
  "LAUNCH_TIME_MS": 25623,
  "ACC_TYPE": "PERSONAL",
  "chats": 69,
  "messages": 89,
  "contacts": 12114,
  "isMd": true,
  "INSTANCE_ID": "0f3c1a56-1088-4a97-ad34-437262aa8399"
}
```

### Environment

```markdown
- OS: Linux 5.15
- Node: 16.18.0
- npm: 8.19.2
```

**Comment by smashah** [comment]
Hmm there's not enough here for me to reproduce. can you tell me more about the group. is the host account the admin?

**Comment by fukumori** [comment]
It is a new group created. The function works despite the error.

**Comment by smashah** [comment]
@fukumori how long do you wait to update the group description?

Try adding a 2/3second delay between group creation and everything else
