### ISSUE TITLE
client.deleteMessage doesn't work

### ISSUE THREAD

**Issue by eliellima00** [open-wa/wa-automate-nodejs#2939]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

When I try to delete a messege using the deleteMessage method, nothing actions is executed. When I add last argument to true, than it's throw an error

I dont know if it is an Bug or if I'm making anything wrong

### Expected Behavior

Delete a message of given messageId
deleteMessage(chatId, messageId, onlyLocal?): Promise<void>

### Steps To Reproduce

```js
import { create } from '@open-wa/wa-automate';

create({
  sessionId: "TEST",
  multiDevice: true, //required to enable multiDevice support
  authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
  blockCrashLogs: true,
  disableSpins: true,
  headless: true,
  hostNotificationLang: 'PT_BR',
  logConsole: false,
  popup: true,
  qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
}).then(client => start(client));

function start(client) {
  client.onMessage(async message => {
    console.log(message)
    const chatId = message.chatId
    const messageId = message.id

    await client.sendText(message.from, 'Deleting')
    console.log(chatId)

    await client.deleteMessage(chatId, messageId, true)
  });
}

```

### create() code OR full CLI command + CONFIG

```js
import { create } from '@open-wa/wa-automate';

create({
  sessionId: "TEST",
  multiDevice: true, //required to enable multiDevice support
  authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
  blockCrashLogs: true,
  disableSpins: true,
  headless: true,
  hostNotificationLang: 'PT_BR',
  logConsole: false,
  popup: true,
  qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
}).then(client => start(client));

function start(client) {
  client.onMessage(async message => {
    console.log(message)
    const chatId = message.chatId
    const messageId = message.id

    await client.sendText(message.from, 'Deleting')
    console.log(chatId)

    await client.deleteMessage(chatId, messageId, true)
  });
}
```

### DEBUG INFO

```markdown
- Debug info: {
  "WA_VERSION": "2.2242.6",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel 
Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.49.1",
  "BROWSER_VERSION": "HeadlessChrome/103.0.5058.0",
  "OS": "Windows 10",
  "START_TS": 1667675258738,
  "RAM_INFO": "Total: 17.00 GB | Free: 9.08 GB",
  "PPTR_VERSION": "15.0.0"
}
```

### Environment

```markdown
- OS: Windows
- Node: v16.17.0
- npm: 8.15.0
```

### Screenshots/Logs

`Error: Evaluation failed: TypeError: _0x320fb5[("sen" + _0x3c4e61(...) + _0x3c4e61(...) + "eMs" + "gs")] is not a function    
    at window.<computed>.<computed> [as smartDeleteMessages] (pptr://__puppeteer_evaluation_script__:1:190685)
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\eliel\Documents\projetos\Node\wa-bot\node_modules\puppeteer\src\common\ExecutionContext.ts:279:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\eliel\Documents\projetos\Node\wa-bot\node_modules\puppeteer\src\common\ExecutionContext.ts:145:12)`

**Comment by smashah** [comment]
patched. please restart and try again thanks
