### ISSUE TITLE
Store.Presence.getPresence?

### ISSUE THREAD

**Issue by IanosJunior** [open-wa/wa-automate-nodejs#294]
I would like to keep my whatsapp always online.
I have the option setPresence but I wanted to trigger it only when I get different from online.
Is there a function to check my presence?

**Comment by smashah** [comment]
@IanosJunior This is almost the exact same, but opposite, issue as #276

I suggest running a delayed loop that sets the presence to online. Something like:

```
(function setOnline() {
   client.setPresence(true)
    setTimeout(setOnline, 10000);
})();
```

reference: https://github.com/open-wa/wa-automate-nodejs/issues/276#issuecomment-609440362

**Comment by smashah** [comment]
@IanosJunior hope that worked for you. Closing for now. Thanks
