### ISSUE TITLE
Error send list & button message on group

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#2947]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Steps To Reproduce

run the script

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2243.7",
  "WA_AUTOMATE_VERSION": "4.49.1",
  "BROWSER_VERSION": "HeadlessChrome/107.0.5304.110",
  "START_TS": 1668409015769,
  "RAM_INFO": "Total: 8.14 GB | Free: 7.26 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "edf80",
  "LAUNCH_TIME_MS": 15953,
  "ACC_TYPE": "BUSINESS",
  "chats": 30,
  "messages": 116,
  "contacts": 4237,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "a43d97af-2f25-43c0-9b39-adf315c6bba6"
}
```

### Environment

```markdown
- OS: Linux 5.4
- Node: 16.17.0
- npm: 8.18.0
```

### Screenshots/Logs

![E7CF623D-2364-44B5-BD8C-7A97FA8ED03D](https://user-images.githubusercontent.com/18587059/201596080-6af01cdb-a137-45b9-a2fe-ff240bffac86.jpeg)

`Error: Evaluation failed: TypeError: e.isGroup is not a function
0|wabot  |     at o (https://web.whatsapp.com/bootstrap_qr.05be0932a7796d566db1.js:57:99801)
0|wabot  |     at t.isGroupLidFromChatWid (https://web.whatsapp.com/bootstrap_qr.05be0932a7796d566db1.js:57:99672)
0|wabot  |     at https://web.whatsapp.com/bootstrap_qr.05be0932a7796d566db1.js:46:292637
0|wabot  |     at Generator.next (<anonymous>)
0|wabot  |     at t (https://web.whatsapp.com/vendor1~bootstrap_qr.ef018a7bfbd9257ea51d.js:2:66483)
0|wabot  |     at s (https://web.whatsapp.com/vendor1~bootstrap_qr.ef018a7bfbd9257ea51d.js:2:66694)
0|wabot  |     at https://web.whatsapp.com/vendor1~bootstrap_qr.ef018a7bfbd9257ea51d.js:2:66753
0|wabot  |     at Y (https://web.whatsapp.com/bootstrap_qr.05be0932a7796d566db1.js:40:119795)
0|wabot  |     at new y (https://web.whatsapp.com/bootstrap_qr.05be0932a7796d566db1.js:40:112362)
0|wabot  |     at https://web.whatsapp.com/vendor1~bootstrap_qr.ef018a7bfbd9257ea51d.js:2:66634
0|wabot  |     at ExecutionContext._ExecutionContext_evaluate (/root/BOT/wabot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
0|wabot  |     at runMicrotasks (<anonymous>)
0|wabot  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|wabot  |     at async ExecutionContext.evaluate (/root/BOT/wabot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16) `

**Comment by smashah** [comment]
thanks for filling the issue template

**Comment by aymenitc** [comment]
button and list show only in private chats for me.

**Comment by smashah** [comment]
@aymenitc @dandyraka please restart and try again

**Comment by aymenitc** [comment]
Yes it is working now for my in groups.
