### ISSUE TITLE
Feature request: archive/unarchive chats

### ISSUE THREAD

**Issue by blackchineykh** [open-wa/wa-automate-nodejs#295]
Hi Guys,

I have to admit this is the most comprehensive and structured solution ive seen written for nodejs for WA. I have been using checking out WAPI.js for python and was looking for a nodejs version and landed here. Great work! 

Is the archive/unarchive feature on the roadmap? I have a long load time at startup from archived conversations on the device and want to programatically unarchive then delete when necessary

**Comment by smashah** [comment]
Good idea!

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.46](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.45...1.8.46) (2020-04-10)

- Release 1.8.46 [`36b32f6`](https://github.com/open-wa/wa-automate-nodejs/commit/36b32f64403a923444adcfe70e1b8225f3184fed)
- implemented archive + unarchive chat #295 [`e1bda2c`](https://github.com/open-wa/wa-automate-nodejs/commit/e1bda2c00821128eac8404854212dc4649735108)

**Comment by smashah** [comment]
@blackchineykh try it out and report back if it works for you. Thanks

```javascript

//archive chat
client.archiveChat('4477777777777@c.us',true);

//unarchive chat
client.archiveChat('4477777777777@c.us',false);

```

**Comment by blackchineykh** [comment]
Great. Will test it out and report back

**Comment by smashah** [comment]
Great. Please note that if returns false it just means that the chat is already in that state.

```javascript
//If chat is already archived, running:
const archiveJob = await client.archiveChat('4477777777777@c.us',true)
//will result in archiveJob = false

```

**Comment by blackchineykh** [comment]
This works perfectly! Thanks a lot man. Very much appreciated. Will close this issue
