### ISSUE TITLE
infer filetype if filename is missing

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#2952]

**Comment by smashah** [comment]
User report:

```
await client.sendFile(message.chat.id, "media/audios/oof.mp3");
```

resulting in:

`Error: Evaluation failed: Error: MediaFileEmpty`

**Comment by luizgununes** [comment]
Same happens with me. Maybe the way that a audio file is sent on WhatsApp Web have changed. Others libraries are having the same problem.

**Comment by crescent1** [comment]
i have same problem when send image with `GetURL`.

**Comment by smashah** [comment]
while resolving this issue i came across this interesting video:

https://www.youtube.com/watch?v=0twDETh6QaI

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "minor"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`cd ./types-only && npm version $VERS && npm run build && npm publish && cd ..`);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by luizgununes** [comment]
I still can't send audio files with the lib.

**Comment by smashah** [comment]
@luizgununes make sure the file is ogg/oga. if that's not working then fill the issue template with all of the detail, test code & files.

**Comment by luizgununes** [comment]
I can't understand, until last week it was possible to send mp3 files and the player shows to play the file. Sending .ogg instead of .mp3 in fact works, it sends the file, but not as an audio file to reproduce without manually downloading.

**Comment by smashah** [comment]
@luizgununes please at least share the files. The more context and information you can provide for replicating an issue the quicker it can be resolved. Otherwise we just go back and forth aimlessly

**Comment by smashah** [comment]
@luizgununes 

I was able to send an mp3 file as a playable audio file by using `sendPtt(chatId, "https://file-examples.com/storage/fe7589721d63762859d6962/2017/11/file_example_MP3_700KB.mp3")`

**Comment by luizgununes** [comment]
Okay, sendPtt is working for me now. Thanks.

**Comment by luizgununes** [comment]
I discovered that the problem isn't the way I send the file (sendPtt works), but something with the path. That's weird because nothing was changed recently.

The error happens when I send a local file or url.

Debugging on localhost it works, but when I deploy, gives error.

* I'm using a Oracle VM with Ubuntu.

`
Error: Evaluation failed: Error: MediaFileEmpty
at h.sendToChat (https://web.whatsapp.com/app.77ee8aa7a4c593101105.js:75:729330)
at pptr://__puppeteer_evaluation_script__:1:203630
at async window.<computed>.<computed> [as sendImage] (pptr://__puppeteer_evaluation_script__:1:200123)
at ExecutionContext._ExecutionContext_evaluate (/home/ubuntu/bot-jaguara/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ExecutionContext.evaluate (/home/ubuntu/bot-jaguara/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)
`

**Comment by smashah** [comment]
@luizgununes when you have some reproducible code then please make a new issue
