### ISSUE TITLE
Capture poll data

### ISSUE THREAD

**Issue by manteguinha** [open-wa/wa-automate-nodejs#2958]
Would it be possible to capture/read the poll data?  
Ex: Read the result, voters and etc.

**Comment by yiftachn** [comment]
Joining to the question. Would be a great alternative to Buttons, that are not present in groups

**Comment by smashah** [comment]
@yiftachn group buttons are fixed.

**Comment by smashah** [comment]
You can now grab poll data with [`getPollData`](https://openwa.dev/docs/api/classes/api_Client.Client#getpolldata) and listen to incoming poll votes with [`onPollVote`](https://openwa.dev/docs/api/classes/api_Client.Client#onpollvote)

**Comment by victorfreire100** [comment]
if (body.startsWith("!vida")) {
				  const pollOptions = ["🟥 1 - vigia do suicidio", "⬛️ 2 - me odeio", "🟫 3 - odeio minha vida", "🟧 4 - tolerando a vida", "⬜️ 5 - ok", "🟨 6 - contente", "🟩 7 - bem", "🟦 8 - feliz!", "🟪 9 - amo minha vida  a a", "✨ 10 - não dá pra melhorar"];
				  const pollId = await client.sendPoll(from, "Checkpoint do estado mental", pollOptions);

				  client.onPollVote((pollData) => {
					if (pollData.pollId === pollId) {
					  console.log(`A opção "${pollOptions[pollData.optionIndex]}" foi votada por ${pollData.voter}`);
					}
				  });
				}
				
				is correct?
