### ISSUE TITLE
Cannot deploy on cloud host provider

### ISSUE THREAD

**Issue by d0ct0r4r6a** [open-wa/wa-automate-nodejs#296]
@smashah Hello. I couldn't figure out the way to correctly deploy to Zeit Now/Heroku/Openode. Can anybody provide the steps to deploy it on one (or more) cloud service(s) I mentioned?

on Zeit Now, I don't know what command to run on the build process, and if I add command like ```node --version``` as the build script, I couldn't find a way to get the QR code to scan.

on Openode, the deploy process failed with a message saying:
```
failed to launch the browser process! spawn /opt/app/node_modules/puppeteer/
```

on Heroku, it is similar to what I experience on Zeit Now

And if I could request further, maybe adding some docs about deployment would help greatly. Thank you for your attention.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️

**Comment by smashah** [comment]
@d0ct0r4r6a https://github.com/open-wa/wa-automate-nodejs/issues/1146#issuecomment-739574338
