### ISSUE TITLE
Por que al solicitar el QR lanza este error en mi servidor mientras que en mi local funciona perfecto

### ISSUE THREAD

**Issue by CristhianCAM** [open-wa/wa-automate-nodejs#2966]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/69518355/205071707-3012bb0b-93c2-4229-b1f3-ac808667a117.png)

### DEBUG INFO

```markdown
nn
```

### Environment

```markdown
- OS: Debian 11
- Node: 16.17.5
- npm: 8.15.0
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/69518355/205071553-7d4e2f7a-1d8b-4dca-9cb4-487cdc8d5bbd.png)

**Comment by smashah** [comment]
You need to fix the permissions of your setup.

Don't run the process as root.

Make sure the process user has permission to use `npm`.

This is an issue of your environment

**Comment by smashah** [comment]
Also make sure you're using current/lts version of node/npm. Closing.
