### ISSUE TITLE
I can't send message

### ISSUE THREAD

**Issue by gabrielvsb** [open-wa/wa-automate-nodejs#2967]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

I try to send message, but i receive the messageId with "_out" in the end.

### Steps To Reproduce

`const configObject = {
    sessionId: "AMIGO_SECRETO_v2",
    useChrome: true,
    multiDevice: true, //required to enable multiDevice support
    authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
    blockCrashLogs: true,
    disableSpins: true,
    headless: true,
    hostNotificationLang: 'PT_BR',
    logConsole: false,
    popup: true,
    qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
    intervalCap: 5, //process 5 events
    interval: 3000, //within every three second window
    concurrency: 2, //make sure to process, at most, 2 events at any one time
    timeout: 100, //make sure there is a 100ms gap between each event processing.
    carryoverConcurrencyCount: true
}
wa.create(util.configObject).then(client => enviarMensagemUnica(client));

async function enviarMensagemUnica(client){
    const chatId = 'mynumber@c.us';
    const mensagem = 'Test'
    const resultado = await client.sendText(chatId, mensagem)
    console.log(resultado)
    console.log('\n\nMensagen enviada')
    process.exit()
}

`

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2245.9",
  "WA_AUTOMATE_VERSION": "4.51.6",
  "BROWSER_VERSION": "HeadlessChrome/107.0.5304.123",
  "START_TS": 1669987348988,
  "RAM_INFO": "Total: 8.29 GB | Free: 1.04 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "3ea9b",
  "LAUNCH_TIME_MS": 16992,
  "ACC_TYPE": "PERSONAL",
  "chats": 563,
  "messages": 997,
  "contacts": 919,
  "isMd": true,
  "INSTANCE_ID": "e36ceade-990f-4afc-898b-c1b5401c6e07"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 14.17.6
- npm: 6.14.15
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/53629458/205302794-e5903ad6-94ea-452a-8e7f-7b251bae27fb.png)

**Comment by smashah** [comment]
`I try to send message, but i receive the messageId with "_out" in the end.`

What makes you think `_out` means that you can't send a message? `_out` just means that the message is going OUT of the session.

**Comment by smashah** [comment]
Closing. Please add more info if you can.
