### ISSUE TITLE
Session not persistent

### ISSUE THREAD

**Issue by M0in4** [open-wa/wa-automate-nodejs#2969]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

Every time that I start the server I've to scan the QR code.
How can I scan it only one time and after a server restart the session persist?

### Steps To Reproduce

  wa.create({
    sessionId: "SESSION_TESTER",
    multiDevice: false, //required to enable multiDevice support
    authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
    blockCrashLogs: true,
    disableSpins: true,
    headless: true,
    hostNotificationLang: 'IT_IT',
    logConsole: true,
    useChrome: true,
    popup: true,
    //cacheEnabled: true,
    qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
  }).then(client => start(client));

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2245.9",
  "WA_AUTOMATE_VERSION": "4.51.6",
  "BROWSER_VERSION": "HeadlessChrome/108.0.5359.71",
  "START_TS": 1670204693422,
  "RAM_INFO": "Total: 4.02 GB | Free: 2.37 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Linux 5.13
- Node: 18.12.1
- npm: 9.1.2
```

**Comment by t0g3pii** [comment]
> Error: Execution context was destroyed, most likely because of a navigation. at rewriteError (/home/ubuntu/xx/apps/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:337:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ExecutionContext._ExecutionContext_evaluate (/home/ubuntu/xx/apps/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:225:60) at async ExecutionContext.evaluate (/home/ubuntu/xx/apps/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16) Session most likely logged out Error while terminating browser PID. You can just ignore this, as the process has most likely been terminated successfully already: kill ESRCH UNHANDLER REJECTION! Shutting down... Error Execution context was destroyed, most likely because of a navigation.
> 
> When I try to put multiDevice: true

Delete your old Session Files before trying to change the Setting

**Comment by M0in4** [comment]
Its crashing

You can also authenticate the session at: http://localhost:7000
- Starting
- Version: 4.51.6
- Initializing WA
- Launching Browser
- MD Enabled, turning off incognito mode.
- Data dir: ./_IGNORE_SESSION_TESTER
- Data dir doesnt exist, creating...: ./_IGNORE_SESSION_TESTER
- Browser launched: 1333ms
- Setting Up Page
- Loading session data
- No session data file found for session : SESSION_TESTER
- No session data detected. Opting in for MD.
- Make sure to keep the session alive for at least 5 minutes after scanning the QR code before trying to restart a session!!
- Pre page launch setup complete: 7ms
- Navigating to WA
- Page loaded in 6443ms: 200
- Page loaded
- Debug info: {
  "WA_VERSION": "2.2245.9",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.51.6",
  "BROWSER_VERSION": "HeadlessChrome/108.0.5359.94",
  "OS": "Linux 5.13",
  "START_TS": 1670339831430,
  "RAM_INFO": "Total: 4.02 GB | Free: 2.26 GB",
  "PPTR_VERSION": "15.0.0"
}
- Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2245.9%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.51.6%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/108.0.5359.94%22,%0A%20%20%22START_TS%22:%201670339831430,%0A%20%20%22RAM_INFO%22:%20%22Total:%204.02%20GB%20%7C%20Free:%202.26%20GB%22,%0A%20%20%22PPTR_VERSION%22:%20%2215.0.0%22,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20false%0A%7D&enviro=-%20OS:%20Linux%205.13%0A-%20Node:%2018.12.1%0A-%20npm:%209.1.2&labels=MD
- Time to injection: 2191ms
- Injecting api
- Injecting scripts
- Base inject: 97ms
Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (/home/ubuntu/xx/apps/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:337:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext._ExecutionContext_evaluate (/home/ubuntu/xx/apps/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:284:56)
    at async ExecutionContext.evaluate (/home/ubuntu/appbull/apps/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)
Error while terminating browser PID. You can just ignore this, as the process has most likely been terminated successfully already: kill ESRCH
UNHANDLER REJECTION! Shutting down...

**Comment by smashah** [comment]
Please try the latest version.
