### ISSUE TITLE
client.getAllUnreadMessages is not working (always returns empty array even tough there are new messages)

### ISSUE THREAD

**Issue by feliperaul** [open-wa/wa-automate-nodejs#297]
**Describe the bug**
Can't get a list of unread messages.

**Steps to Reproduce**
As per indicated in the **pest practices** in the readme, one should be able to process new messages when wa-automate session is created.

The docs state that this could be accomplished by `  const unreadMessages = await client.getAllUnreadMessages();`

However, as you can see from the attached screenshot, this is not working, as it returns empty arrays:

![image](https://user-images.githubusercontent.com/743879/79007266-2d30ac80-7b31-11ea-8867-fb585d61438a.png)

**create() code**
This is the code you use to create the client. e.g
```javascript

const client = await wa.create(
    `session_123`,
{
    headless: false,
    defaultViewport: false,
    args: ['--start-maximized', '--window-size=1920,1080' ]
  },
  );
```

Trying to debug this, I followed the code path and noticed that `WAPI.getAllNewMessages()` works up until the filter of `c.msgs._models`, because even the new messages, still unread (haven't clicked it's chat window yet) are being returned with `isNewMsg: undefined` 

![image](https://user-images.githubusercontent.com/743879/79007219-168a5580-7b31-11ea-9d30-650c6a94ea8a.png)

**Expected behavior**
It should return new messages for processing. 

**DEBUG INFO**

```
────┤
│     WA_VERSION      │                                                                 '2.2013.7'                                                                  │
│       PAGE_UA       │ 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                  '1.8.44'                                                                   │
│   BROWSER_VERSION   │                                                            'Chrome/80.0.3987.0'
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: macOs / iPhone

**Additional context**
The documentation is not very clear about the difference between `getAllUnreadMessages` and `getAllUnreadMessages` and `getAllNewMessages`.

**Comment by smashah** [comment]
Hey @feliperaul,

Thanks for following the issue template.

The distinction is based on the actual properties of the messages - which may not get updated in real time. 

1. getAllUnreadMessages return messages where `ack: -1`
2. getAllNewMessages returns messages where `isNewMsg: true`

So although they're technically correct, it's not really what people expect (i.e the messages represented with the numbers in the chat list).

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.48](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.47...1.8.48) (2020-04-10)

- Release 1.8.48 [`6626a1e`](https://github.com/open-wa/wa-automate-nodejs/commit/6626a1edacf7b20cf041eb8a861d4671dce1beeb)
- implemented `getIndicatedNewMessages` #297 [`0af07a6`](https://github.com/open-wa/wa-automate-nodejs/commit/0af07a63a2f461ddf8b59f11b980505b2f4a020c)

**Comment by smashah** [comment]
@feliperaul Please try:

```javascript
const newChatsWithNewMessages = await client.getIndicatedNewMessages
```
It returns an array of objects:

```javascript
[{
"id": "000000000000@g.us", //the id of the chat with new messages
"indicatedNewMessages": [] //array of messages, not including any messages by the host phone
}]
```

**Comment by feliperaul** [comment]
@smashah Working great Shah! **Thank you so much**.

Just a correction, it was missing the function invocation:

```
const newChatsWithNewMessages = await client.getIndicatedNewMessages();
```
