### ISSUE TITLE
Can't send messages to new numbers, I am using a restricted license key, Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by palasbo** [open-wa/wa-automate-nodejs#2972]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

I have a  restricted license key but I can't send messages to new numbers, when I try to send the message I get the error:
```js
/root/microservicios/node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'filter')
    at eval (eval at <anonymous> (:1:10), <anonymous>:1:66558)
    at H (https://web.whatsapp.com/app.77ee8aa7a4c593101105.js:40:119931)
    at MutationObserver.B (https://web.whatsapp.com/app.77ee8aa7a4c593101105.js:40:116508)
    at ExecutionContext._ExecutionContext_evaluate (/root/microservicios/node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/root/microservicios/node/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:117:16)
```
I don't have any problems sending messages to existing conversations.

### Steps To Reproduce

client.sendText(number, message);

If I don't have an existing conversation with the number I get the error.

### create() code OR full CLI command + CONFIG

```markdown
wa.create({
  sessionId: "ibot",
  multiDevice: true, //required to enable multiDevice support
  authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
  blockCrashLogs: true,
  disableSpins: true,
  headless: true,
  hostNotificationLang: 'PT_BR',
  logConsole: false,
  popup: true,
  qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
  licenseKey:license_key,//ends in -1F1248B9
}).then(client => start(client));
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2245.9",
  "WA_AUTOMATE_VERSION": "4.51.6",
  "BROWSER_VERSION": "HeadlessChrome/103.0.5058.0",
  "START_TS": 1670356898918,
  "RAM_INFO": "Total: 4.09 GB | Free: 3.03 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "3ea9b",
  "LAUNCH_TIME_MS": 18276,
  "ACC_TYPE": "PERSONAL",
  "chats": 17,
  "messages": 16,
  "contacts": 260,
  "isMd": true,
  "INSTANCE_ID": "1e088ca9-90d2-4a1b-8f2e-06f5efb04bcc"
}
```

### Environment

```markdown
- OS: Linux 5.10
- Node: 18.9.1
- npm: 8.19.1
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/7673738/206012718-1433e6fa-6cb3-4545-b2c0-f2a578c94236.png)

**Comment by smashah** [comment]
@palasbo does the message actually get sent?

**Comment by palasbo** [comment]
No, it doesn't

**Comment by smashah** [comment]
@palasbo please DM me on discord so I can get into your session and fix this

**Comment by palasbo** [comment]
@smashah the problem has been resolved thank you for your time, the issue will hapen only when sending two or more messages at the same time.

Error:
client.sendText(new_contact_number,message);
client.sendText(new_contact_number,message);

Solution:
await client.sendText(new_contact_number,message);
await client.sendText(new_contact_number,message);

**Comment by smashah** [comment]
oh yes @palasbo It is extremely important that you always `await` any `client` methods.

Closing thanks
