### ISSUE TITLE
BUG 

### ISSUE THREAD

**Issue by moha-abdi** [open-wa/wa-automate-nodejs#2979]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

AFTER I RUN THE CODE WHICH IS THE SIMPLE CODE GIVEN IN THIS REPOSITORY I AM RECIEVING THIS ERROR:

Traceback (most recent call last):
  File "/home/moha/PycharmProjects/wapy/firsmo.py", line 5, in <module>
    client = SocketClient('http://localhost:8085/', 'secure_api_key')
  File "/home/moha/.local/lib/python3.10/site-packages/wa_automate_socket_client/__init__.py", line 43, in __init__
    self.io.connect(self.url, auth={'apiKey': api_key})
TypeError: Client.connect() got an unexpected keyword argument 'auth'

### Expected Behavior

I DONT KNOW

### Steps To Reproduce

YES

### create() code OR full CLI command + CONFIG

```markdown
client = SocketClient('http://localhost:8085/', 'secure_api_key')
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2245.9",
  "WA_AUTOMATE_VERSION": "4.52.0",
  "BROWSER_VERSION": "HeadlessChrome/103.0.5058.0",
  "START_TS": 1670858904926,
  "RAM_INFO": "Total: 4.01 GB | Free: 0.70 GB",
  "PPTR_VERSION": "15.0.0",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "c26a7",
  "LAUNCH_TIME_MS": 42797,
  "ACC_TYPE": "PERSONAL",
  "chats": 1,
  "messages": 1,
  "contacts": 222,
  "isMd": true,
  "INSTANCE_ID": "63178abe-4cf8-4ddb-bc2f-7399eab248c7"
}
```

### Environment

```markdown
- OS: Linux 5.14
- Node: 18.12.1
- npm: 9.1.2
```

### Anything else?

NOTHNG ELSE

**Comment by smashah** [comment]
If you're not using an API key, you shouldn't need the second parameter which is resulting in the error. Upgrade to latest python. Closing as there's already an issue ok the python socket repo.
