### ISSUE TITLE
Get Last sent message Id

### ISSUE THREAD

**Issue by blackchineykh** [open-wa/wa-automate-nodejs#298]
The sendImage and sendFile methods dont seem to return a value representing the Id of the message that was sent. Is this deliberate since the docs shows that sendText returns the Id? This would be useful to know the id of the messages sent for all message types. Would like to know if there's plans for this or it already exists using some other method?

**Comment by smashah** [comment]
This is mainly because the method to send the file to the chat doesn't return a promise (or anything for that matter). So returning a key right after sending the image file wouldn't always be correct

**Comment by smashah** [comment]
@blackchineykh 

In the latest version, it returns last message key however I wouldn't trust it. 

I suggest double checking by running getChat then getting the lastReceivedKey

https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#getchatbyid
https://open-wa.github.io/wa-automate-nodejs/interfaces/chat.html#lastreceivedkey
```javascript
const possibleLastKey = await sendImage(....
//maybe add a delay here
const chat = await client.getChat(....
console.log(possibleLastKey, chat.lastReceivedKey)
```

**Comment by blackchineykh** [comment]
Was it deliberate that you still allowed the module to return **void** instead of a **string** in the sendImage function of wapi.ts given that it now returns the lastReceivedKey?

`const sendImage: (
    base64: string,
    to: string,
    filename: string,
    caption: string
  ) => void;`

**Comment by blackchineykh** [comment]
I find that a solution that works for me is to add a new method to the wapi.js and WAPI module which gets the last sent message to that chatId and call it after 1 second of sending the image or file. So if for a single chat we dont send another message without getting the id of the last one from the msg object then this could work.

`window.WAPI.getLastSentMsg = function(chatId, done){
    var validMessages = Store.Msg.models.filter(msg => msg.to._serialized === chatId&& msg.isSentByMe);
  
   if (typeof validMessages !== "undefined" && validMessages.length > 0) {
     var lastMsg = validMessages[validMessages.length - 1];
     var message = WAPI._serializeMessageObj(lastMsg);
     if (done !== undefined) done(message);
     return message;
   } else {
     if (done !== undefined) done(false);
     return false;
   }
}`
