### ISSUE TITLE
high consumption of cpu and very low performance on server

### ISSUE THREAD

**Issue by andy661** [open-wa/wa-automate-nodejs#2980]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

It is expected that it will be faster to process requests and that it will not consume a lot of cpu

### Expected Behavior

This error is generated when starting the session, it takes time to generate the qr code and all the responses arrive later than expected, also while processing them it generates a high CPU consumption by the chrome execution, try using useChrome in true but no change in performance

I also tried the latest version and the error still exists,
I will be waiting for your answers I appreciate all the help you can give me.

### Steps To Reproduce

1. start pm2 or npm start
2. make request to the api

### create() code OR full CLI command + CONFIG

```markdown
const createSession = (whastappPhone,licenseKey) => {
    //return new Promise ((resolve, reject) => {
        wa.create({
            licenseKey:licenseKey,
            //headless: false,
            // ezqr: true, // Expone la url para scenear el qr
            killClientOnLogout : true, // Mata el cliente si cierra la sesión
            killProcessOnTimeout: true, // eliminará todo el proceso del nodo cuando se alcance un authTimeout o un qrTimeout . Esto es útil para evitar que los procesos se cuelguen
            sessionId: whastappPhone + "_sesion",
            useChrome: true,
            multiDevice: true,
            authTimeout: 60, //wait only 60 seconds to get a connection with the host account device
            blockCrashLogs: true,
            disableSpins: true,
            //headless: true,
            hostNotificationLang: 'PT_BR',
            logConsole: false,
            popup: false,
            qrPopUpOnly: false,
            cacheEnabled: false,
            qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
            deleteSessionDataOnLogout: true, //Elimina datos se sesion si esta es cerrada por el cliente,
            maxMensajes:30, //cantidad máxima de mensajes que estarán presentes en una sesión
            maxChats: 20 // cantidad máxima de chats para estar presente en una sesión.
        })
        .then(client => {
            clientSessionRegistry[client.getSessionId()] = client;
            misce.deleteQrOld(whastappPhone);     
            // data.chats = client._sessionInfo.chats
            // data.messages = client._sessionInfo.messages
            // data.contacts = client._sessionInfo.contacts
            
            //resolve(data);
        })
        .catch(err => {
            console.log('----------------------Error en la función wa.create------------------------');
            console.log(err);
            //reject(err);
        })
    //})
}
```

### DEBUG INFO

```markdown
Debug info: {
0|app    |   "WA_VERSION": "2.2246.10",
0|app    |   "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
0|app    |   "WA_AUTOMATE_VERSION": "4.49.1 UPDATE AVAILABLE: 4.52.0",
0|app    |   "BROWSER_VERSION": "HeadlessChrome/93.0.4577.0",
0|app    |   "OS": "Linux 5.10",
0|app    |   "START_TS": 1670972395486,
0|app    |   "RAM_INFO": "Total: 0.50 GB | Free: 0.35 GB",
0|app    |   "PPTR_VERSION": "15.0.0"
0|app    | }
```

### Environment

```markdown
- OS: debian 11
- Node: v16.17.0
- npm: 8.15.0
-SEVER: aws lightsail
```

### Screenshots/Logs

![image](https://user-images.githubusercontent.com/119872187/207465815-7cc0b082-e4f5-452d-bab9-337322dec859.png)
![image](https://user-images.githubusercontent.com/119872187/207466263-5e6ead21-6e7b-452f-9718-b86f04572ab7.png)
![image](https://user-images.githubusercontent.com/119872187/207466589-7ee0d4a0-75df-4b0c-b8fc-056fc4e1694d.png)
![image](https://user-images.githubusercontent.com/119872187/207611180-a702d456-daaa-4d93-9974-fc36a65232f6.png)
![image](https://user-images.githubusercontent.com/119872187/207955408-0f02e19b-679d-4bca-9a7f-f57367110370.png)

### Anything else?

in most executions it ends with a time exception.

**Comment by smashah** [comment]
Hi,

what are the specs of your vm?

**Comment by andy661** [comment]
- OS: debian 11
- 500 mb RAM
- 700 mb SWAP
its a  Lightsail instance of AWS

**Comment by smashah** [comment]
@andy661 the session is being limited by the resources.

Please upgrade to an instance with at least 2gb of ram.
