### ISSUE TITLE
Kill or EXIT wa-automate process on EASY API?

### ISSUE THREAD

**Issue by nrs1022** [open-wa/wa-automate-nodejs#2985]
Hi @smashah! Generally using EASY API works great but sometimes my session stops receiving new messages, in these cases I simply CTRL-C on the console open-wa is loaded and all restarts fine... but I wish to kill or restart without using CTRL-C or killing the process.

If I use the /kill from API Explorer, the console shows this:

_Killing client. Shutting Down
Browser page has closed. Killing client
Error while terminating browser PID. You can just ignore this, as the process has most likely been terminated successfully already: kill ESRCH_

But wa-automate doesn't restart. Is there any way to completely EXIT (so wa-automate itself can be closed too) from API Explorer? Or maybe restart browser and page?

I'm using this setup as example:
wa-automate: 4.53.0
Node: 16.19.0
Npm: 8.19.3

Thank you!

**Comment by nrs1022** [comment]
> ok i see. good suggestion thanks @nrs1022 i will look into it
> 
>     * [x]  `/process/kill`
> 
>     * [ ]  `/process/restart`

Thank you very much @smashah, I'll check it soon.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
try {
	execSync(cmd, {stdio: 'inherit'})
}  catch (error) {
    console.log(`Status Code: ${error.status} with '${error.message}'`);
 }
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN && npm run types:publish `);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.54.6](https://github.com/open-wa/wa-automate-nodejs/compare/4.54.5...4.54.6) (2022-12-30)

- ✨ CLI: `/meta/process/exit` & `/meta/process/restart` #2985 [`2801ebc`](https://github.com/open-wa/wa-automate-nodejs/commit/2801ebce46935f027ef9a45cbcfe68bce029e3fe)
- Release 4.54.6 [`b929f14`](https://github.com/open-wa/wa-automate-nodejs/commit/b929f1444533896df94a08e9493e2b3771c28df6)
- updated types-only package [`601070b`](https://github.com/open-wa/wa-automate-nodejs/commit/601070ba6b3f53ea548d486399990cce0c56d616)

**Comment by smashah** [comment]
This was actually a pretty tough feature to implement but now it should be working as expected + works with `--tunnel` & `--pm2`.

It's actually pretty powerful with pm2 so I suggest you try it with that.

Basically just send an empty post req to the endpoints:

`POST /meta/process/exit {}`
`POST /meta/process/restart {}`

Thanks
