### ISSUE TITLE
Error when sendTextWithMentions

### ISSUE THREAD

**Issue by ozkcs** [open-wa/wa-automate-nodejs#300]
**Describe the bug**
When i try to use client.sendTextWithMentions i got this error Error: Evaluation failed: Error: wid error: invalid wid: @c.us

**create() code**
This is the code you use to create the client. e.g
```javascript
                    var jogador = "554192218181@c.us"
                    var jogadorName = message.sender.pushname
                    var jogadorID = jogador.slice(0, -5)

                    var adversario = "554196039438@c.us"
                    var adversarioName = await client.getContact(adversario).pushname
                    var adversarioID = adversario.slice(0, -5)
await client.sendTextWithMentions(message.from, `O jogador @${jogadorID}, convidou o @${adversarioID} para jogar uma partida de jogo da velha!\n@Digite *aceitar* ou *recusar*`)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2013.7,
  PAGE_UA: WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36,
  WA_AUTOMATE_VERSION:'1.8.49',
  BROWSER_VERSION: 'HeadlessChrome/80.0.3987.0'
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/35303121/79038374-2779ac00-7baf-11ea-8efb-0320c9b8623f.png)

**Host (please complete the following information):**
 - OS: ANDROID WINDOWS

**Additional context**

**Comment by smashah** [comment]
@ozkcs as mentioned in the documentation:

https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#sendtextwithmentions

you don't need to use `@c.us` when using this method.

So this should work:

```javascript
                    var jogador = "554192218181"
                    var jogadorName = message.sender.pushname
                    var jogadorID = jogador.slice(0, -5)

                    var adversario = "554196039438"
                    var adversarioName = await client.getContact(adversario).pushname
                    var adversarioID = adversario.slice(0, -5)
await client.sendTextWithMentions(message.from, `O jogador @${jogadorID}, convidou o @${adversarioID} para jogar uma partida de jogo da velha!\n@Digite *aceitar* ou *recusar*`)
```

**Comment by ozkcs** [comment]
but the jogadorID, slices 5 characters from jogador, so the jogadorID should be 5541922

**Comment by ozkcs** [comment]
what I use before it wasnt correct?
```javascript
                    var jogador = "554192218181@c.us"
                    var jogadorName = message.sender.pushname
                    var jogadorID = jogador.slice(0, -5) //554192218181
```
and when i reply i use the JogadorID var

**Comment by smashah** [comment]
> but the jogadorID, slices 5 characters from jogador, so the jogadorID should be 5541922

Maybe try this for now:

```javascript
                    var jogador = "554192218181@c.us"
                    //so the tag will be '@554192218181';
                    var jogadorName = message.sender.pushname
                    var jogadorID = jogador.replace('@c.us','')
                    var adversario = "554196039438@c.us"
                    var adversarioName = await client.getContact(adversario).pushname
                    var adversarioID = adversario.replace('@c.us','')

await client.sendTextWithMentions(message.from, `O jogador @${jogadorID}, convidou o @${adversarioID} para jogar uma partida de jogo da velha!\n@Digite *aceitar* ou *recusar*`)
```

**Comment by ozkcs** [comment]
![image](https://user-images.githubusercontent.com/35303121/79038730-f9499b80-7bb1-11ea-9f6b-d076f5e8cbfc.png)
i had the same issue

**Comment by ozkcs** [comment]
I tried to mention another person, happened the same error, for the final test i asked for my friend do the command for me mentioning me, and the error happened too

**Comment by smashah** [comment]
This is happening because of `@Digite`. Remove it.

**Comment by ozkcs** [comment]
![image](https://user-images.githubusercontent.com/35303121/79038872-48dc9700-7bb3-11ea-9a47-88aad115cfb3.png)
 same error

**Comment by smashah** [comment]
you didn't remove it

**Comment by ozkcs** [comment]
hoho, sorry for now i understood what to to

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by ozkcs** [comment]
Finally, thanks @smashah

**Comment by smashah** [comment]
@ozkcs In the upcoming release, you should be able to use `@Digite`

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.50](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.49...1.8.50) (2020-04-11)

- Release 1.8.50 [`e5dce24`](https://github.com/open-wa/wa-automate-nodejs/commit/e5dce2457d9c7254ec4051b22d8819a8d2a83f47)
- filter incorrect mentions from `sendMessageWithMentions` #30 [`6d2e2fa`](https://github.com/open-wa/wa-automate-nodejs/commit/6d2e2facda5f6d35055b252ee1e3655aa584f12a)
