### ISSUE TITLE
How to Status Viewers

### ISSUE THREAD

**Issue by impozzible** [open-wa/wa-automate-nodejs#301]
I am not sure if this is a bug just yet, but I would like to ask us there anyway to know users that have viewed my status, an ack is sent when a status is viewed but this does not include the chat id of the user that viewed the status, is there anyway to pull this?

**Comment by smashah** [comment]
@impozzible please share screenshots of how you can check the viewers of a story on Whatsapp web.

**Comment by impozzible** [comment]
<img width="564" alt="Screenshot 2020-04-11 at 2 19 48 PM" src="https://user-images.githubusercontent.com/30698707/79044837-8ebf4c80-7bff-11ea-8f33-102a476f9baf.png">

It seems it only shows the numbers count on WhatsappWeb

**Comment by smashah** [comment]
Yeah that's what I've found also.

**Comment by smashah** [comment]
Closing for now as this doesn't seem possible at the moment
