### ISSUE TITLE
[FRQ] participantsChanged who

### ISSUE THREAD

**Issue by t0g3pii** [open-wa/wa-automate-nodejs#3011]
Docs states that were no longer able to see who commited the event (same on globalParticipantsChanged) 

Can we build that back in?

who commited it is not fetched from the group-participants.update event (its not in there), it is directly fetched from the messages.upsert event 
(Baileys)

Example Screenshot of Baileys:
![Screenshot_20230110_153055_WhatsApp](https://user-images.githubusercontent.com/49153387/211598948-b4f3bc22-1627-4531-be00-809be331026b.jpg)

**Comment by smashah** [comment]
This already exists. doesn't work for promote/demote

**Comment by t0g3pii** [comment]
> This already exists. doesn't work for promote/demote

doesnt work becaaauseee...?
(just asking for the technical aspect as it is indeed working in baileys)

**Comment by smashah** [comment]
try now
