### ISSUE TITLE
Is there a way to get a callback for Group Icon Changed (Event)?

### ISSUE THREAD

**Issue by fire17** [open-wa/wa-automate-nodejs#3019]
Hi there,
Was wondering if there is an existing event I'm missing here, I am listening to onAnyMessage
but it seems the Group Icon Change does not register.

Please lemme know how this is possible 🙏 
Thanks a lot! and have a good one! :)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
try {
	execSync(cmd, {stdio: 'inherit'})
}  catch (error) {
    console.log(`Status Code: ${error.status} with '${error.message}'`);
 }
}
//set the version type
process.env.VERS = "patch"

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci $VERS`);

// types only package
exec('npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN')
exec(`npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN && npm run types:publish `);
exec(`git commit -a -m 'updated types-only package'`);
exec(`git push --force`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.55.1](https://github.com/open-wa/wa-automate-nodejs/compare/4.55.0...4.55.1) (2023-01-20)

- ✨ feat: [INSIDERS] `client.onGroupChange` #3019 [`07c5de7`](https://github.com/open-wa/wa-automate-nodejs/commit/07c5de7862256a024145d5948c829ffb259d1d6d)
- Release 4.55.1 [`75efd55`](https://github.com/open-wa/wa-automate-nodejs/commit/75efd55c9b0b1b8cc1b90c0783a6af3cc76e8853)
- 🥚 patches update [`211064c`](https://github.com/open-wa/wa-automate-nodejs/commit/211064c8ebe3f3b0d8eb49191080d4c76cf951dc)
- 🥚 patches update [`20832e3`](https://github.com/open-wa/wa-automate-nodejs/commit/20832e3deee649193f3e55d66959a14cc34b18f7)
- 🥚 patches update [`4cdc404`](https://github.com/open-wa/wa-automate-nodejs/commit/4cdc40434ff668d9b9484889fd34267b46c4b595)
- 🥚 patches update [`7e454d6`](https://github.com/open-wa/wa-automate-nodejs/commit/7e454d68f0b1c46a5a34e56846ff1b53dd0da7fb)
- 🥚 patches update [`4edb775`](https://github.com/open-wa/wa-automate-nodejs/commit/4edb7752b89f7f619c94fbb310c28a6cc0fffb41)
- 🥚 patches update [`a25da1d`](https://github.com/open-wa/wa-automate-nodejs/commit/a25da1d3ff62594ec914e8b72fe1c513ef9e0374)
- 🥚 patches update [`7d18ef7`](https://github.com/open-wa/wa-automate-nodejs/commit/7d18ef72afd33c5f96924358c8b47896bd52bda9)
- updated types-only package [`85ccd9a`](https://github.com/open-wa/wa-automate-nodejs/commit/85ccd9ae82c15f6990dc91261d2323c4a41ff6bc)

**Comment by smashah** [comment]
@fire17 `onGroupChange` should now be emitted to your webhooks in the latest version. this includes all `gp2` (group meta) events.

you should look out for when the event.type == 'picture' and the event.body === 'set' to get an idea for when the icon has changed. event.groupPic will have the base64 img.


thanks for the suggestion. enjoy!

**Comment by fire17** [comment]
Mmmmmmmmm I was wondering where that gp2 suddenly came from, love the patches system its incredible
I'll start experimenting with this soon! :)
Thanks a lot @smashah youre the best 💛
