### ISSUE TITLE
setGroupTitle Not Working for me

### ISSUE THREAD

**Issue by fire17** [open-wa/wa-automate-nodejs#3020]
Hi there, 
I am managing to create groups with any name, but can't change them after the fact with `setGroupTitle `
is anyone else getting this?
is this connected to some update on whatsapp's end?
Any ideas when this could be resolved?

Thanks a lot and a have a good one! :)

**Comment by smashah** [comment]
fixed. Please restart and try again

**Comment by fire17** [comment]
@smashah 💪 🙏 
Thanks man I will check it out and confirm!
All the best!
