### ISSUE TITLE
Created group:  Error: ServerStatusCodeError: rate-overlimit

### ISSUE THREAD

**Issue by fire17** [open-wa/wa-automate-nodejs#3021]
I'm trying to create a new group and I'm getting this error:
```
res = driver.createGroup(Name, participants)
print("Created group: ", res)
>>> Created group:  Error: ServerStatusCodeError: rate-overlimit
```

Usually This works, I'm wondering if the rate limiting comes from open-wa or whatsapp itself,
in any case please advise 🙏

**Comment by fire17** [comment]
Damn... I just tried it on my phone and I get the same error.
It's on whatsapp's side,
does anyone know the of this behavior and if there are any workarounds/known limits/different behavior in business accounts, etc?
thanks

**Comment by smashah** [comment]
@fire17 yeah there's no limit imposed by open-wa.

How often are you attempting to create groups?

Closing as not an issue.

**Comment by fire17** [comment]
Hi there :)
I know this is not on open-wa's end, i just thought i should go here incase someone else is looking for info (was hoping to get some myself)

It took 24 hrs for whatsapp to allow me to continue opening groups after i was blocked.
But since then i've tried with another number and was just blocked again.
I dont know if the treatment is equal for every account but this fresh new account created about 45 groups in a bit under 24 hours before getting blocked aswell.

this is really frustrating as it wasn't like this in the past. I do alot of my work within groups rather than direct chat
currently i have another number that creates a group for my main number everytime a send it a specific message
but if anyone has another creative/better idea that would be great!

Thanks a lot! :)

**Comment by smashah** [comment]
Thanks for the context. Seems like they're limiting group creation for some accounts.

**Comment by fire17** [comment]
Do you think business accounts will have higher group creation limits?
Or can you confirm if you have open many groups somehow without this restriction?
Thanks a lot :)
Hope you have a great weekend ( Im here hard at work ha ha)
