### ISSUE TITLE
Backup a conversation?

### ISSUE THREAD

**Issue by tinyCoder32** [open-wa/wa-automate-nodejs#303]
Hello, was thinking if there is a possible option to backup a specific chat? Right now i'm using `chat.loadEarlierMsgs()` to load the latest 50 messages, hopefully there is a way to load and save the whole conversation?

Thanks.

**Comment by smashah** [comment]
Please read the docs. I know they're not great but it's best to check there first. 

https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#getallmessagesinchat

Just FYI, it takes a long time.

**Comment by tinyCoder32** [comment]
Thank you, accept my apologies.
