### ISSUE TITLE
How to change group setting to Only Admins

### ISSUE THREAD

**Issue by yogiepribadi** [open-wa/wa-automate-nodejs#304]
How to change group setting to Only Admins ?

**Comment by smashah** [comment]
@yogiepribadi what do you mean? As in only allow admins into a group? Please be as specific as possible.

**Comment by yogiepribadi** [comment]
On whatsapp mobile or whatsapp web there are an options who can post message in group. We can choose All Participants or Only Admins.  Group info details screen -> Group Settings -> Edit Group Info.

Thanks Shah..

**Comment by smashah** [comment]
Thanks for the details @yogiepribadi

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.55](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.54...1.8.55) (2020-04-13)

- Release 1.8.55 [`64b04cc`](https://github.com/open-wa/wa-automate-nodejs/commit/64b04ccac1f7ac6d52cbfcfe5cfa2db6f6d4f558)
- implemented advanced group settings #304 [`317afbd`](https://github.com/open-wa/wa-automate-nodejs/commit/317afbd65b4235ec81bcbc4bbf34e222d4045670)

**Comment by smashah** [comment]
@yogiepribadi with the latest update you can now try:

```javascript
//Only group admins can send messages
client.setGroupToAdminsOnly('123463453245-000000000@g.us',true)

//Everyone can send messages
client.setGroupToAdminsOnly('123463453245-000000000@g.us',false)

//Oonly admins can edit group info
client.setGroupEditToAdminsOnly('123463453245-000000000@g.us',true)

//Everyone can edit group info
client.setGroupEditToAdminsOnly('123463453245-000000000@g.us',false)
```

Thanks for your membership and the good suggestion.

Note: This feature is now part of the [Insiders Program.](https://github.com/open-wa/wa-automate-nodejs#insiders-program)

**Comment by yogiepribadi** [comment]
It works, Thank you so much @smashah
