### ISSUE TITLE
[Feature Request]: Standard method to download profile photo

### ISSUE THREAD

**Issue by blackchineykh** [open-wa/wa-automate-nodejs#305]
I've been trying different methods of downloading the profile photos. I always get the URL correctly whether from the chat object or the download from the server (for older chats). However it doesnt always get the image downloaded (im trying to get in base64). I notice that sometimes i get 200 and most times 500 http codes for the requested URL. I have tried using the client user agent and also external ones but still same. If I open these URLs in a browser, they load fine. Can u provide a standard method to download the profile image taking the url as an arg so we decide on if we want the thumb or the full image? or maybe have some arg that controls which is returned as base64?

**Comment by smashah** [comment]
@blackchineykh check the implementation in `wa-decrypt-nodejs`

https://github.com/open-wa/wa-decrypt-nodejs/blob/dc5d97d97c9adc0ca545c50df5ed8cba9ebe4730/src/decrypt.ts#L16

Let me know if that worked for you. Also can you share your code for the request. Thanks

**Comment by blackchineykh** [comment]
Hi,

It didn't work as i'm still seeing http 500 errors.

Here's my code snippet
`var request = require("request").defaults({ encoding: null }); //in the imports

const options = {
	url: photoUrl,
	encoding: null,
	simple: false,
	resolveWithFullResponse: true,
	headers: {
	'User-Agent': 'WhatsApp/2.16.352 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36'
	}
  };
  
request.get(options, function (error, response, body) {
	log.info(`Response code for photo url is ${response.statusCode}`)
	log.info(`Response body `, body)
  
	if (!error && response.statusCode == 200) {
	
		let data = "data:" + response.headers["content-type"] + ";base64," + new Buffer(body).toString("base64");
		log.debug(`Fetched profile photo from url ${photoUrl}. Image data`,data);   
	} 
}`

See my log snippet:
[2020-04-12T20:00:55.364] [INFO] default - Response code for photo url is 500

**Comment by smashah** [comment]
Does it work sometimes? One major factor of the decrypt method is it keeps trying until it resolves
https://github.com/open-wa/wa-decrypt-nodejs/blob/dc5d97d97c9adc0ca545c50df5ed8cba9ebe4730/src/decrypt.ts#L28

**Comment by blackchineykh** [comment]
> Does it work sometimes? One major factor of the decrypt method is it keeps trying until it resolves
> https://github.com/open-wa/wa-decrypt-nodejs/blob/dc5d97d97c9adc0ca545c50df5ed8cba9ebe4730/src/decrypt.ts#L28

Yes it works sometimes. I haven't implemented the use of this method since I when I try from a browser to get the url, it works 100% of the time. I'm suspecting me getting http error code 500 means something is wrong. In the wapi.js file, there's a download function that I think should get the job done based on using it in a former python project but it's not exposed in your client. Is there a reason these methods aren't exposed in the client directly?

**Comment by smashah** [comment]
Things get added ad hoc. The main reason this lib doesn't use any downloading jobs from the browser is that it puts extra load on the browser instance whereas the node instance should be able to handle it. Next I would suggest updating your user agent simply to your browser's user agent.

**Comment by smashah** [comment]
@blackchineykh please try this:

```javascript
var request = require("request").defaults({ encoding: null }); //in the imports
const options = {
	url: photoUrl,
	encoding: null,
	simple: false,
	resolveWithFullResponse: true,
	headers: {
	'User-Agent': 'WhatsApp/2.16.352 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
      'DNT':1,
      'Upgrade-Insecure-Requests':1
	}
  };
  
request.get(options, function (error, response, body) {
	log.info('Response code for photo url is ${response.statusCode}')
	log.info('Response body ', body)
  
	if (!error && response.statusCode == 200) {
	
		let data = "data:" + response.headers["content-type"] + ";base64," + new Buffer(body).toString("base64");
		log.debug('Fetched profile photo from url ${photoUrl}. Image data',data);   
	} 
}
```

**Comment by smashah** [comment]
Also, please share the code that you are using to get the photo.

**Comment by blackchineykh** [comment]
I ran some tests and realized that the when I use the photo url from the contact object, it has the periodic http 500 error. However when I use the url returned from "getProfilePicFromServer" instead, this works consistently. I will run some more tests and share the code

**Comment by smashah** [comment]
I assumed you were using that method already. It'll probably be quicker next time to fill the issue template. If this continues make a new issue. Thanks.
