### ISSUE TITLE
[Bug] acceptGroupJoinRequest

### ISSUE THREAD

**Issue by t0g3pii** [open-wa/wa-automate-nodejs#3055]
As seen in the screenshot the type of a GroupJoinRequest is normal "chat", would love to see it as something like "invite" or "joinRequest".

2nd problem is that if the acceptGroupJoinRequest fails due to missing permissions (group restriction from the user) it still returns true instead of any invite code or something.

![Screenshot_20230301_051157_WhatsApp](https://user-images.githubusercontent.com/49153387/222046105-37bf4d03-503d-4abe-99e3-ff764ebb2f98.jpg)

**Comment by t0g3pii** [comment]
maybe my 2nd issue is related to #2971

**Comment by smashah** [comment]
1. https://openwa.dev/docs/api/interfaces/api_model_message.Message#isgroupjoinrequest

2. the function returns the result of the group participant add function - but in a different way to the addParticipants. I'll see if I can use the same system for both. Also why would group restrictions come into affect when the recipient is the one requesting an invite????

**Comment by t0g3pii** [comment]
> 2. the function returns the result of the group participant add function - but in a different way to the addParticipants. I'll see if I can use the same system for both. Also why would group restrictions come into affect when the recipient is the one requesting an invite????
WhatsApp being WhatsApp^^ We dont know why WhatsApp is like that xD

**Comment by smashah** [comment]
updates for group approval in 4.59.0

https://github.com/open-wa/wa-automate-nodejs/issues/3070#issuecomment-1481615307
