### ISSUE TITLE
give many errors in console

### ISSUE THREAD

**Issue by Kizuno18** [open-wa/wa-automate-nodejs#3063]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Steps To Reproduce

just authenticate

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2310.5",
  "WA_AUTOMATE_VERSION": "4.58.0",
  "BROWSER_VERSION": "HeadlessChrome/111.0.5555.0",
  "START_TS": 1678223428629,
  "RAM_INFO": "Total: 4.12 GB | Free: 2.93 GB",
  "PPTR_VERSION": "19.7.3",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "38f47",
  "LAUNCH_TIME_MS": 45260,
  "ACC_TYPE": "BUSINESS",
  "chats": 65,
  "messages": 951,
  "contacts": 1091,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "5e788bce-7ce2-4168-8b69-130e39c3bbac"
}
```

### Environment

```markdown
- OS: Linux 5.4
- Node: 14.21.3
- npm: 6.14.18
```

### Screenshots/Logs

![Untitled](https://user-images.githubusercontent.com/110933270/223553974-f84d40db-e383-40e3-b6ef-cc3d153d9597.png)

**Comment by smashah** [comment]
Everything after that license link is errors from your own code.

Closing.

Please track #3090
