### ISSUE TITLE
(feature) pic properties on chat

### ISSUE THREAD

**Issue by MoonLGH** [open-wa/wa-automate-nodejs#3069]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

#eval 
message.chat.pic

// undefined

### Expected Behavior

throw sender picture

### Steps To Reproduce

1. evaluate or run message.chat.pic

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2311.5",
  "WA_AUTOMATE_VERSION": "4.42.4 UPDATE AVAILABLE: 4.58.0",
  "BROWSER_VERSION": "HeadlessChrome/103.0.5060.114",
  "START_TS": 1678806674158,
  "RAM_INFO": "Total: 8.34 GB | Free: 2.36 GB",
  "PPTR_VERSION": "UNKNOWN",
  "LATEST_VERSION": false,
  "CLI": false
}
```

### Environment

```markdown
- OS: Linux 5.4
- Node: 19.7.0
- npm: 9.5.0
```

**Comment by smashah** [comment]
fixed in 4.59.0

https://github.com/open-wa/wa-automate-nodejs/issues/3070#issuecomment-1481615307

use `chat.pic`
