### ISSUE TITLE
sendImageAsSticker description

### ISSUE THREAD

**Issue by arelxcode** [open-wa/wa-automate-nodejs#307]
![Screenshot_20200412-2206102-1](https://user-images.githubusercontent.com/54056041/79077552-c546b580-7d2c-11ea-897e-18da03fd9487.jpg)
sendImageAsStiker can give the information like this?

**Comment by smashah** [comment]
That's a disturbingly cute sticker you have there.

**Comment by zaheeraws** [comment]
is it possible to save incoming stickers to file/base64?

**Comment by smashah** [comment]
@arelxcode This does not seem possible on Whatsapp web. There are no references to author or name anywhere in the code. Please reopen this when Whatsapp web is able to show you this information.

@zaheeraws please make a new issue for that.

thanks
