### ISSUE TITLE
Buttons not showing on mobile phones  but working on receiver's web.whatsapp (sendButtons,sendAdvancedButtons,sendListMessage)

### ISSUE THREAD

**Issue by mesutyigit** [open-wa/wa-automate-nodejs#3073]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

Buttons showing on receiver's WebWhatsapp but not viewing on mobile devices.

### Expected Behavior

...

### Steps To Reproduce

...

### create() code OR full CLI command + CONFIG

```markdown
@open-wa/wa-automate -h 0.0.0.0 -p 8924 -e http://localhost:80/bot/63ca761069766687ff8227cf/launch-event --ready-webhook http://localhost:80/bot/63ca761069766687ff8227cf/ready-event --webhook https://socket.XX.XX/webhook/whatsapp/63ca761069766687ff8227cf -a -d --skip-save-postman-collection --cache-enabled false --session-id 63ca761069766687ff8227cf --session-data-path /home/ec2-user/temp/63ca761069766687ff8227cf --popup --license-key ****** --use-chrome --skip-url-check --qr-timeout 60 --emit-unread --auth-timeout 60 --kill-process-on-timeout --throw-on-expired-session-data --delete-session-data-on-logout --debug --verbose
```

### DEBUG INFO

```markdown
WA_Version: "2.2312.7"
```

### Environment

```markdown
- OS: Linux
- Node: 17.5.0
- npm: 8.5.1
```

**Comment by smashah** [comment]
Buttons seem to be dead

- [ ] Deprecate all buttons in docs

**Comment by mesutyigit** [comment]
Is this a solvable situation?

We have a few insiders and a few restricted license keys. We do this just to send the button. Buttons are very important to our customers.

Should we wait or look for alternative solutions? 

This issue valid for sendAdvencedButtons and sendListMessage

**Comment by smashah** [comment]
@mesutyigit every single project is having this issue - offical verified wa biz api accounts send messages with an extra metadata payload with information around the conversation payment id. If the mobile clients are now verifying this with wa servers before rendering a message then there is no solution to this unfortunately. If you have licenses just for this feature I unfortunately understand that you will need to cancel them.

I will be spending the upcoming week doing a deeper dive and reaching out to the other devs of the other projects to come up with some sort of solution. To be honest I don't see a way around this if they are verified these payloads with wa servers.

**Comment by smashah** [comment]
Reference:

![image](https://user-images.githubusercontent.com/5903821/227748350-45dff6d0-d367-456e-be84-68f537bd712a.png)

node content 1 is a verified biz signature
node content 2 is a payload that has the metadata for the wa biz api convo.

**Comment by smashah** [comment]
https://github.com/open-wa/wa-automate-nodejs/commit/1d756310181957f55289f73855ae6b8b062e0e4e

**Comment by smashah** [comment]
- [ ] undprecate list message
- [ ] undprecate buttons message

**Comment by mesutyigit** [comment]
Is it fixed for next release?

**Comment by smashah** [comment]
@mesutyigit it was fixed yesterday. this was just a documentation update. go ahead and try them out.

NOTE: ANYTHING WITH URL OR CALL BUTTON WILL NOT WORK!

**Comment by mesutyigit** [comment]
I tested it a few minute ago (4.62.2 release) with Restricted License.  

🟢 sendListMessage                 =>   OK both on     (app and web.whatsapp)
🔴 sendButtons                         =>    Not receiving (app and web.whatsapp)
🔴 sendAdvancedButtons        =>    Not receiving (app and web.whatsapp)

fyi

**Comment by smashah** [comment]
Btw @mesutyigit you can use sendAdvancedButtons but just don't use URL or CALL buttons inside that method. It should still work
