### ISSUE TITLE
[Bug] joinGroupViaLink with enabled approve Setting in Groups

### ISSUE THREAD

**Issue by t0g3pii** [open-wa/wa-automate-nodejs#3076]
The Approve Setting is now not only available for Communitys, its now available for every group.
After enabling that Feature a User who wants to join the group needs to press a Button to "Ask for Join"^ 

Current Error appears on Groups with that enabled when trying to join:
ERROR: ServerStatusCodeError: not-authorized

I left u a WhatsApp Group Invite in ur Discord DMs where u can test it if you dont have a group with that enabled^

**Comment by smashah** [comment]
Ok so you want the [`joinGroupViaLink`](https://openwa.dev/docs/api/classes/api_Client.Client#joingroupvialink) to request to join instead of erroring out?

**Comment by t0g3pii** [comment]
> 

It doesn't even error out^^ it returns the mentioned error as a string^^ 
But yes, would be nice if it automatically request to join :)

**Comment by smashah** [comment]
patched.

**Comment by victorfreire100** [comment]
joinGroupViaLink it's in error.
my code:

 client.joinGroupViaLink(linkGrupo).then(async (gId)
 console.log(gId)
 
the expected response was the group id, for example: xxxx@g.us,

reespose now is: ERROR: UnexpectedJoinGroupViaInviteResponse
