### ISSUE TITLE
mething went wrong while retreiving new the QR

### ISSUE THREAD

**Issue by victorfreire100** [open-wa/wa-automate-nodejs#3082]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

√ Launch inject: 244ms
{
  a: true,
  b: true,
  c: true,
  d: '663987e12470230371b6429000f909e3d8ebe918',
  e: '0551e72b30f9b8cdaa7939399bb4d2017ef5b10a'
}
🌔  Something went wrong while retreiving new the QR code but it should not affect the session launch
procedure: Protocol error (Runtime.evaluate): Promise was collected

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### DEBUG INFO

```markdown
────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2313.8'                                                                 │
│       PAGE_UA       │ 'WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                  '4.61.2'                                                                  │
│   BROWSER_VERSION   │                                                          'Chrome/111.0.5563.147'                                                           │
│         OS          │                                                           'Windows Server 2019'                                                            │
│      START_TS       │                                                               1680108458079                                                                │
│      RAM_INFO       │                                                    'Total: 137.17 GB | Free: 88.88 GB'                                                     │
│    PPTR_VERSION     │                                                                  '19.8.2'                                                                  │
```

### Environment

```markdown
- OS: 
- Node: 
- npm:
```

**Comment by victorfreire100** [comment]
After this error, I close the cmd and restart and then it stays on the whatsapp loading screen.

**Comment by smashah** [comment]
Please update to [4.62.2](https://github.com/open-wa/wa-automate-nodejs/compare/4.62.1...4.62.2) and try again
