### ISSUE TITLE
Session seems to start, but no messages are passed

### ISSUE THREAD

**Issue by WEBudoGT** [open-wa/wa-automate-nodejs#3084]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

I'm using wa-automate-docker and suddenly the account stopped sending/receiving messages so I thought I should scan QR again, but logs show connected behavior.
Even if I unlink the device, the session seems to be authenticated but it's not.

Then I restarted the instance and it authenticated and went normal again, but no messages exchanged.
Checking via API healthCheck shows:
`{
    "success": true,
    "response": {
        "queuedMessages": 0,
        "state": "OPENING",
        "isPhoneDisconnected": true,
        "isHere": true,
        "wapiInjected": true,
        "online": true,
        "tryingToReachPhone": false,
        "retryingIn": 0,
        "isMd": true
    }
}`

Then I unlinked from whatsapp on my mobile phone and restarted docker-compose again, but it never requested for QR scan again, as it shows as authenticated, but with some things to notice on logs:

`- Starting
- Version: 4.61.2
- Initializing WA
- Using custom chromium args with multi device will cause issues! Please remove them: 
- Launching Browser
- MD Enabled, turning off incognito mode.
- Data dir: /sessions/_IGNORE_session
- Browser launched: 200ms
- Setting Up Page
- Loading session data
- No session data file found for session : session
- No session data detected. Opting in for MD.
- Make sure to keep the session alive for at least 5 minutes after scanning the QR code before trying to restart a session!!
- Pre page launch setup complete: 10ms
- Navigating to WA
- Page loaded in 501ms: 200
- Page loaded
- Debug info: {
  "WA_VERSION": "2.2313.8",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.61.2",
  "BROWSER_VERSION": "HeadlessChrome/111.0.5563.146",
  "OS": "Linux 5.10",
  "START_TS": 1680135946327,
  "RAM_INFO": "Total: 16.79 GB | Free: 9.66 GB",
  "PPTR_VERSION": "19.8.0"
- Time to injection: 1647ms
- Injecting api
- Injecting scripts
- Base inject: 11ms
- WAPI inject: 11ms
- Checking session integrity
- Session integrity check passed
- Launch inject: 746ms
- WAPI injected
- Authenticating
**- 0%:	 WhatsApp
- Authenticated**
- Waiting for ripe session...
- You may experience issues in headless mode. Continuing...
- Reinjecting api
- Injecting scripts
- Base inject: 9ms
- WAPI inject: 143ms
- Checking session integrity
- Session integrity check passed
- Launch inject: 424ms
**- WAPI Reinjected**
- Checking if session is valid
- Downloading patches from https://cdn.openwa.dev/patches.json
**- Client is ready**
- Downloaded patches in 0.119s
- Installing patches
- Patches Installed: 90118
- Client loaded for business account [MD] with **0 contacts, 0 chats & 0 messages** in 44.46s
- Finalizing web session...
- Finalizing client...
- 🚀 @OPEN-WA ready for account: 2822
- session_STARTUP
- ...waiting for port 8002 to be free
- Port 8002 is now free.
- 
• Listening on port 8002!
`

How can I make it "forget" the session and ask for QR again?
How can I force an older version of open-wa using docker? (as I saw some new issues, I would like to try 4.60.0)

### Steps To Reproduce

Using wa-automate-docker
Restarted the instance and it authenticated and went normal again, but no messages exchanged.
Checking via API healthCheck shows:
`{
    "success": true,
    "response": {
        "queuedMessages": 0,
        "state": "OPENING",
        "isPhoneDisconnected": true,
        "isHere": true,
        "wapiInjected": true,
        "online": true,
        "tryingToReachPhone": false,
        "retryingIn": 0,
        "isMd": true
    }
}`

Then I unlinked from whatsapp on my mobile phone and restarted docker-compose again, but it never requested for QR scan again, as it shows as authenticated, but with some things to notice on logs:

`- Starting
- Version: 4.61.2
- Initializing WA
- Using custom chromium args with multi device will cause issues! Please remove them: 
- Launching Browser
- MD Enabled, turning off incognito mode.
- Data dir: /sessions/_IGNORE_session
- Browser launched: 200ms
- Setting Up Page
- Loading session data
- No session data file found for session : session
- No session data detected. Opting in for MD.
- Make sure to keep the session alive for at least 5 minutes after scanning the QR code before trying to restart a session!!
- Pre page launch setup complete: 10ms
- Navigating to WA
- Page loaded in 501ms: 200
- Page loaded
- Debug info: {
  "WA_VERSION": "2.2313.8",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.61.2",
  "BROWSER_VERSION": "HeadlessChrome/111.0.5563.146",
  "OS": "Linux 5.10",
  "START_TS": 1680135946327,
  "RAM_INFO": "Total: 16.79 GB | Free: 9.66 GB",
  "PPTR_VERSION": "19.8.0"
- Time to injection: 1647ms
- Injecting api
- Injecting scripts
- Base inject: 11ms
- WAPI inject: 11ms
- Checking session integrity
- Session integrity check passed
- Launch inject: 746ms
- WAPI injected
- Authenticating
**- 0%:	 WhatsApp
- Authenticated**
- Waiting for ripe session...
- You may experience issues in headless mode. Continuing...
- Reinjecting api
- Injecting scripts
- Base inject: 9ms
- WAPI inject: 143ms
- Checking session integrity
- Session integrity check passed
- Launch inject: 424ms
**- WAPI Reinjected**
- Checking if session is valid
- Downloading patches from https://cdn.openwa.dev/patches.json
**- Client is ready**
- Downloaded patches in 0.119s
- Installing patches
- Patches Installed: 90118
- Client loaded for business account [MD] with **0 contacts, 0 chats & 0 messages** in 44.46s
- Finalizing web session...
- Finalizing client...
- 🚀 @OPEN-WA ready for account: 2822
- session_STARTUP
- ...waiting for port 8002 to be free
- Port 8002 is now free.
- 
• Listening on port 8002!
`

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2313.8",
  "WA_AUTOMATE_VERSION": "4.61.2",
  "BROWSER_VERSION": "HeadlessChrome/111.0.5563.146",
  "START_TS": 1680135403978,
  "RAM_INFO": "Total: 16.79 GB | Free: 9.70 GB",
  "PPTR_VERSION": "19.8.0",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "90118",
  "LAUNCH_TIME_MS": 44255,
  "ACC_TYPE": "BUSINESS",
  "chats": 0,
  "messages": 0,
  "contacts": 0,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "72203d59-12bf-4b65-b6a6-8c9e1eb0a525"
}
```

### Environment

```markdown
- OS: Linux 5.10
- Node: 19.8.1
- npm: 9.6.2
```

**Comment by nrs1022** [comment]
Hi, it's related to issue #3083, as @smashah has pointed in the mentioned issue you can use 4.61.0 until bug is fixed.

Use the W_A_V environment variable to use a previous version (Not tested, this example is taken from wa-automate-docker):

`docker run -e W_A_V=4.61.0 -p 8080:8080 --init openwa/wa-automate -w https://webhook.site.... --socket`

**Comment by WEBudoGT** [comment]
Thanks @nrs1022 !
The environment variable you pointed out works just fine:
  "WA_AUTOMATE_VERSION": "4.61.0"

But I'm still having the issue that I unlinked the device from my phone, and it still thinks it's authenticated.
Do you know of a way to force to refresh QR (forget the stored session)?

**Comment by WEBudoGT** [comment]
Nevermind, I found this one: WA_NO_KILL_ON_LOGOUT = false
Thanks!

**Comment by WEBudoGT** [comment]
Thanks @smashah 
I have a couple of accounts running, and one worked with the WA_NO_KILL_ON_LOGOUT = false
but the other keeps on trying to use the stored session and breaks with:

`- Downloaded License in 2.782s
- Injecting License...
- License injected successfully..
- License Valid: B2B_RESTRICTED_LICENSE
- Finalizing web session...
- Finalizing client...
ProtocolError: Runtime.callFunctionOn timed out.
    at new Callback (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:61:35)
    at CallbackRegistry.create (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:106:26)
    at Connection._rawSend (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:26)
    at CDPSessionImpl.send (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:419:78)
    at ExecutionContext._ExecutionContext_evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:234:46)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:140:16)
Browser page has closed. Killing client
Killing client. Shutting Down: PAGE_CLOSED
node:events:490
      throw er; // Unhandled 'error' event
      ^
Error: spawn ps ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {

  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-A', '-o', 'ppid,pid,stat,comm' ]
}
Node.js v19.8.1
Starting the application
Using version: 4.61.0
./node_modules/@open-wa/wa-automate/bin/server.js --in-docker --qr-timeout 0 --popup --debug --force-port
up to date, audited 1070 packages in 8s
101 packages are looking for funding
  run `npm fund` for details
31 vulnerabilities (16 moderate, 12 high, 3 critical)
To address issues that do not require attention, run:
  npm audit fix
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.
Unable to read config file json: /config
- session_STARTUP
- DEBUG - PORT: 8002`

This happens after staying a bit on "Finalizing client".

On mobile phone I had unlinked the account, so it should ask for a QR scan.
How can I force it?

Thanks in advance

**Comment by smashah** [comment]
Please update to [4.62.2](https://github.com/open-wa/wa-automate-nodejs/compare/4.62.1...4.62.2) and try again
