### ISSUE TITLE
Error after "Finalizing client..."

### ISSUE THREAD

**Issue by WEBudoGT** [open-wa/wa-automate-nodejs#3085]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

Using v4.61.0

After finalizing client I get the following errors:

`- Finalizing web session...
- Finalizing client...
ProtocolError: Runtime.callFunctionOn timed out.
    at new Callback (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:61:35)
    at CallbackRegistry.create (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:106:26)
    at Connection._rawSend (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:26)
    at CDPSessionImpl.send (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:419:78)
    at ExecutionContext._ExecutionContext_evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:234:46)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:140:16)
Browser page has closed. Killing client
Killing client. Shutting Down: PAGE_CLOSED
node:events:490
      throw er; // Unhandled 'error' event
      ^
Error: spawn ps ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
������
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-A', '-o', 'ppid,pid,stat,comm' ]
}
Node.js v19.8.1
Starting the application
Using version: 4.61.0
./node_modules/@open-wa/wa-automate/bin/server.js --in-docker --qr-timeout 0 --popup --debug --force-port
up to date, audited 1070 packages in 9s
101 packages are looking for funding
  run `npm fund` for details
31 vulnerabilities (16 moderate, 12 high, 3 critical)
To address issues that do not require attention, run:
  npm audit fix
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.
Unable to read config file json: /config
- session_STARTUP
- DEBUG - PORT: 8002
- DEBUG - flags: {"sessionId":"session","executablePath":"/usr/bin/google-chrome","popup":true,"disableSpins":true,"cliConfig":"/config","keepAlive":true,"useChrome":true,"chatwootUrl":"https://*****","chatwootApiAccessToken":"","licenseKey":"OW-*********-","popupQrOnly":true,"skipSavePostmanCollection":true,"onCall":"Por el momento no estamos recibiendo llamadas vía Whatsapp, si desea comunicarse con nosotros puede hacerlo llamando directamente al número PBX ******* o escribiendo mediante este mismo número en Whatsapp. Estaremos felices de atenderle.","autoReject":true,"generateApiDocs":false,"noKillOnLogout":true,"multiDevice":true,"inDocker":true,"qrTimeout":0,"debug":true,"forcePort":true,"noApi":false,"forceUpdateCwWebhook":false,"port":8002,"host":"localhost","verbose":false,"ef":["qr","STARTUP","MD_DETECT","qrUrl"],"allowSessionDataWh":false,"sessionDataOnly":false,"headful":false,"preAuthDocs":false,"stats":false,"cors":false,"socket":false,"emitUnread":false,"allowIps":[]}
- DEBUG - env vars: {"WA_EXECUTABLE_PATH":"/usr/bin/google-chrome","WA_POPUP":"true","WA_DISABLE_SPINS":"true","WA_CLI_CONFIG":"/config","WA_KEEP_ALIVE":"true","WA_USE_CHROME":"true","WA_CHATWOOT_URL":"https://****","WA_CHATWOOT_API_ACCESS_TOKEN":"","WA_LICENSE_KEY":"***********","WA_POPUP_QR_ONLY":"true","WA_SKIP_SAVE_POSTMAN_COLLECTION":"true","WA_ON_CALL":"Por el momento no estamos recibiendo llamadas vía Whatsapp, si desea comunicarse con nosotros puede hacerlo llamando directamente al número PBX o escribiendo mediante este mismo número en Whatsapp. Estaremos felices de atenderle.","WA_AUTO_REJECT":"true","WA_GENERATE_API_DOCS":"false","WA_NO_KILL_ON_LOGOUT":"true","WA_MULTI_DEVICE":"true"}
- Launching EASY API
- Selected port is free
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓┃                                                                              ┃┃   @open-wa/wa-automate                                                       ┃┃   💬 🤖 The most reliable NodeJS whatsapp library for chatbots with          ┃┃   advanced features.                                                         ┃┃   Version: 4.61.0                                                            ┃┃   Check out the latest changes:                                              ┃┃   https://github.com/open-wa/wa-automate-nodejs#latest-changes               ┃┃                                                                              ┃┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
You can also authenticate the session at: http://localhost:8002
- Starting
- Version: 4.61.0
- Initializing WA
- Using custom chromium args with multi device will cause issues! Please remove them: 
- Launching Browser
- MD Enabled, turning off incognito mode.
- Data dir: /sessions/_IGNORE_session
- Browser launched: 614ms
- Setting Up Page
- Loading session data
- Found session data file: /usr/src/app/session.data.json
- No session data detected. Opting in for MD.`

### Steps To Reproduce

Restar docker-compose instance

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2314.7",
  "WA_AUTOMATE_VERSION": "4.61.0",
  "BROWSER_VERSION": "HeadlessChrome/111.0.5563.146",
  "START_TS": 1680194607723,
  "RAM_INFO": "Total: 16.79 GB | Free: 14.04 GB",
  "PPTR_VERSION": "19.8.0",
  "LATEST_VERSION": true,
  "CLI": true
}
```

### Environment

```markdown
- OS: Linux 5.10
- Node: 19.8.1
- npm: 9.6.2
```

**Comment by ccaverna** [comment]
I'm having the same issue

**Comment by smashah** [comment]
Please update to [4.62.2](https://github.com/open-wa/wa-automate-nodejs/compare/4.62.1...4.62.2) and try again

**Comment by WEBudoGT** [comment]
@smashah but this would make me experience the bug on #3083 ?
