### ISSUE TITLE
Make sure your computer has an active internet connection

### ISSUE THREAD

**Issue by demartinoalexis** [open-wa/wa-automate-nodejs#3086]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

When i execute the script again, and the session is store, whatsapp tells me "Make sure your computer has an active internet connection" and the script continue to working but of course doesn't take real data from whatsapp, this is part of the console:

- Client loaded for normal account [MD] with 0 contacts, 0 chats & 0 messages in 47.041s
- Finalizing web session...
ConsoleMessage {}
- Finalizing client...
ConsoleMessage {}
ConsoleMessage {}
ConsoleMessage {}
ConsoleMessage {}
ConsoleMessage {}
ConsoleMessage {}
ConsoleMessage {}
ConsoleMessage {}

### Steps To Reproduce

.

### create() code OR full CLI command + CONFIG

```markdown
{
    sessionId: sessionName,
    authTimeout: 60, 
    restartOnCrash: start,
    blockCrashLogs: true,
    disableSpins: true,
    headless: false,
    useChrome: true,
    hostNotificationLang: 'ES_AR',
    //hostNotificationLang: 'EN_US',
    logConsole: true,
    sessionDataPath: 'open-wa/sessiones',
    popup: false,
    qrTimeout: 0, //0 means it will wait forever for you to scan the qr code
    killProcessOnBrowserClose: true,
    skipUpdateCheck: true,
    useStealth: true,
    //throwErrorOnTosBlock:true,
    multiDevice: true,
    deleteSessionDataOnLogout: true,
    //qrLogSkip: true,
    skipSessionSave: true
  }
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2314.7",
  "WA_AUTOMATE_VERSION": "4.61.2",
  "BROWSER_VERSION": "Chrome/96.0.4664.45",
  "START_TS": 1680208652775,
  "RAM_INFO": "Total: 7.76 GB | Free: 2.68 GB",
  "PPTR_VERSION": "19.8.0",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "8785d",
  "LAUNCH_TIME_MS": 47041,
  "ACC_TYPE": "PERSONAL",
  "chats": 0,
  "messages": 0,
  "contacts": 0,
  "isMd": true,
  "INSTANCE_ID": "0181fa7f-dc3c-4ed7-98bf-d82ca523499e"
}
```

### Environment

```markdown
- OS: Linux 5.15
- Node: 16.13.0
- npm: 9.6.2
```

**Comment by smashah** [comment]
@demartinoalexis 

please update to the latest version and try again

https://github.com/open-wa/wa-automate-nodejs/issues/3083#issuecomment-1490945212
