### ISSUE TITLE
DECRYPT JPEG ERROR

### ISSUE THREAD

**Issue by areltiyan** [open-wa/wa-automate-nodejs#3097]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Steps To Reproduce

copy from example

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2314.7",
  "WA_AUTOMATE_VERSION": "4.63.0",
  "BROWSER_VERSION": "Chrome/111.0.5563.147",
  "START_TS": 1680572864979,
  "RAM_INFO": "Total: 34.36 GB | Free: 30.59 GB",
  "PPTR_VERSION": "19.8.3",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "c92bb",
  "LAUNCH_TIME_MS": 15982,
  "ACC_TYPE": "BUSINESS",
  "chats": 11,
  "messages": 40,
  "contacts": 894,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "8bd705ee-b51c-4cac-b928-8371a2afd140"
}
```

### Environment

```markdown
- OS: Windows
- Node: Latest
- npm: Latest
```

### Screenshots/Logs

TypeError: Cannot read properties of null (reading '0')
    at C:\Users\Administrator\Desktop\arel\node_modules\@open-wa\wa-automate\dist\utils\tools.js:423:97
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Administrator\Desktop\arel\node_modules\@open-wa\wa-automate\dist\utils\tools.js:28:58)

**Comment by smashah** [comment]
That error log is not relating to decryption. It is relating to some sort of file sending method call. Please paste your file sending code and the file you're trying to send. If you're attempting to resend a decrypted file then show your code.

Till proper context is added, closing.
