### ISSUE TITLE
addLabel() doesn't sync label with phone

### ISSUE THREAD

**Issue by rickricardo** [open-wa/wa-automate-nodejs#3104]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

When a message label is added through addLabel() function it works only in the WhatsApp Web, while the phone doesn't get the label synced.

However, if I manually add a label on WhatsApp Web (not using addLabel), it is normally synced with the phone.

### Expected Behavior

Message labels to be synced with the phone when added through addLabel() function.

### Steps To Reproduce

Use addLabel() function to add any label on any message.
Check on the phone that the label wasn't added to the message. 

### DEBUG INFO

```markdown
│     WA_VERSION      │                                                                 '2.2316.4'                                                                 │
│       PAGE_UA       │ 'WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                  '4.64.2'                                                                  │
│   BROWSER_VERSION   │                                                           'Chrome/112.0.5615.49'                                                           │
│         OS          │                                                              'macOS Unknown'                                                               │
│      START_TS       │                                                               1681421765974                                                                │
│      RAM_INFO       │                                                      'Total: 8.59 GB | Free: 0.04 GB'                                                      │
│    PPTR_VERSION     │                                                                  '19.9.0'
```

### Environment

```markdown
- OS: Ventura 13.2
- Node: 19.9.0
- npm: 9.6.3
```

**Comment by smashah** [comment]
patched
