### ISSUE TITLE
feat: Add takeScreenshot to EasyAPI

### ISSUE THREAD

**Issue by Sp0derDev** [open-wa/wa-automate-nodejs#3110]
If it's possible, the screenshot endpoint would be helpful in determining why a session is unresponsive. My sessions end up getting in that state without me being able to pinpoint the issue. A screenshot would be nice. The session is running as a pm2 process so I can't use the "press s to screenshot" feature.

**Comment by smashah** [comment]
You can already do this at the `GET /snapshot` path
