### ISSUE TITLE
getAllChats() has become very slow

### ISSUE THREAD

**Issue by jampy** [open-wa/wa-automate-nodejs#3111]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

`getAllChats()` takes very long to return a result

### Expected Behavior

`getAllChats()` was much quicker in earlier versions or at least it was a few weeks ago (at least less than 30 seconds).

I can't tell which version was better since I often reinstall the Node modules and always use the most current `wa-automate` version.

### Steps To Reproduce

1. `client = require('@open-wa/wa-automate').create({useChrome: true, sessionDataPath: '/foo/session', multiDevice: true})`
2. `await client.getAllChats()`
3. wait up to a minute for a response

### create() code OR full CLI command + CONFIG

```markdown
create({
    useChrome: true,
    sessionDataPath: "/root/.config/session",
    licenseKey: "...",
    multiDevice: true,
  })
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2317.10",
  "WA_AUTOMATE_VERSION": "4.64.5",
  "BROWSER_VERSION": "HeadlessChrome/96.0.4664.110",
  "START_TS": 1682532834920,
  "RAM_INFO": "Total: 8.36 GB | Free: 2.20 GB",
  "PPTR_VERSION": "19.11.1",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Linux 4.4, Debian Bullseye in Docker
- Node: 16.13.1
- npm: 8.1.2
```

### Screenshots/Logs

open-wa startup info:

✓ Launch inject: 281ms
✓ Authenticated
✓ Launch inject: 307ms
✖ You may experience issues in headless mode. Continuing...
✓ Launch inject: 205ms
✓ WAPI Reinjected
✓ Client is ready
✓ Downloaded patches in 0.209s
✓ Patches Installed: fae3e
✓ Client loaded for business account [MD] with 4002 contacts, 506 chats & 584 messages in 17.966s
✓ Downloaded License in 7.846s
✓ License Valid: Restricted License Key

**Comment by smashah** [comment]
@jampy should be patched. please restart and try again thanks

**Comment by jampy** [comment]
Confirmed - thanks a lot!
