### ISSUE TITLE
Feature Request: enable beta for whatsapp web

### ISSUE THREAD

**Issue by shifoc** [open-wa/wa-automate-nodejs#3113]

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [4.65.0](https://github.com/open-wa/wa-automate-nodejs/compare/4.64.5...4.65.0) (2023-05-02)

- ⬆️ upgrade pptr dep [`06e47bd`](https://github.com/open-wa/wa-automate-nodejs/commit/06e47bdd423780d69f8855ebda7bb3f4e67d2a03)
- Release 4.65.0 [`dc1c680`](https://github.com/open-wa/wa-automate-nodejs/commit/dc1c6803ec4ff40191b01fd7927ac2418e6fdbf6)
- 🏷️ type updates #3108 [`4c2216b`](https://github.com/open-wa/wa-automate-nodejs/commit/4c2216b46b384994af3a3709f65c8e0582692856)
- ✨ feat: `joinWebBeta` #3113 [`77b722a`](https://github.com/open-wa/wa-automate-nodejs/commit/77b722afc32b41e2c78f490cbfd72775ac508646)
- 🥚 patches update [`b3b56b1`](https://github.com/open-wa/wa-automate-nodejs/commit/b3b56b19ebe4f329a7b04c995f29474503690f30)
- 🥚 patches update [`1826b0f`](https://github.com/open-wa/wa-automate-nodejs/commit/1826b0fa1ec6c0b529359fa4a9d3dba05ca4db42)
- 🥚 patches update [`2718db5`](https://github.com/open-wa/wa-automate-nodejs/commit/2718db58f3c635ff531a7ef5123c4990d76a80d5)
- 🥚 patches update [`744ec00`](https://github.com/open-wa/wa-automate-nodejs/commit/744ec00217c2a0192e6a31a9c35b9e0ef6699598)
- 🥚 patches update [`97e8869`](https://github.com/open-wa/wa-automate-nodejs/commit/97e886909e04d7ac5438e25fd6ec49c934620f51)
- 🥚 patches update [`6d238ad`](https://github.com/open-wa/wa-automate-nodejs/commit/6d238ad4453e61b591a5b3ffe996343ee47f6e6f)
- 🥚 patches update [`b1a6058`](https://github.com/open-wa/wa-automate-nodejs/commit/b1a60589a0df0b1eeef6c7c90585eed7f8fca887)
- 🥚 patches update [`c75441d`](https://github.com/open-wa/wa-automate-nodejs/commit/c75441db0b96508edfd1395f3c9cb002b0375a2c)
- 🥚 patches update [`0aed269`](https://github.com/open-wa/wa-automate-nodejs/commit/0aed269eb265abcbf25fcafd0df07a6ca494cba7)
- 🥚 patches update [`6ceb710`](https://github.com/open-wa/wa-automate-nodejs/commit/6ceb710b7f6650f70fe1bb9025e49c0a22edaaac)
- 🥚 patches update [`6de2819`](https://github.com/open-wa/wa-automate-nodejs/commit/6de2819bd4aac97bc051d44691f4dd9549057a4a)
- updated types-only package [`a24d42b`](https://github.com/open-wa/wa-automate-nodejs/commit/a24d42b62486853f666524dfec24bbbb3d345a24)
