### ISSUE TITLE
recreate client on page error

### ISSUE THREAD

**Issue by itzharDev** [open-wa/wa-automate-nodejs#315]
sometimes I have puppeteer page error that make my client lose his reference
<img width="1680" alt="Screen Shot 2020-04-14 at 1 11 17" src="https://user-images.githubusercontent.com/12482438/79168129-c5f54f80-7df1-11ea-9440-3d5b74ca28c2.png">
need to implement a new flag to recreate a session on page error

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.57](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.56...1.8.57) (2020-04-14)

- Bump @types/marked from 0.7.3 to 0.7.4 [`#319`](https://github.com/open-wa/wa-automate-nodejs/pull/319)
- Bump typedoc from 0.17.3 to 0.17.4 [`#320`](https://github.com/open-wa/wa-automate-nodejs/pull/320)
- Fix typo in whatsapp.ts [`#314`](https://github.com/open-wa/wa-automate-nodejs/pull/314)
- Release 1.8.57 [`81d9d31`](https://github.com/open-wa/wa-automate-nodejs/commit/81d9d31ecc8cc1cf0b54aab37695f999b451db90)
- added `restartOnCrash` confif variable #315 [`015facd`](https://github.com/open-wa/wa-automate-nodejs/commit/015facd8234b331297081e59465c3569a22059ab)

**Comment by smashah** [comment]
@itzharDev check it out:

https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#restartoncrash

**Comment by smashah** [comment]
Reported and tested to be working. Closing.
