### ISSUE TITLE
Dead links on README file

### ISSUE THREAD

**Issue by sudoevans** [open-wa/wa-automate-nodejs#3150]
THe easyAPI hyperlink points to:
https://docs.openwa.dev/pages/Getting%20Started/quick-run.html

Which is a dead link.
![image](https://github.com/open-wa/wa-automate-nodejs/assets/75899973/83e578f7-e7b7-49fa-9852-d830f9f38394)

![image](https://github.com/open-wa/wa-automate-nodejs/assets/75899973/eb913635-5ce4-4c8f-b4be-ab61bcceeeee)

**Comment by smashah** [comment]
Fixed thanks
