### ISSUE TITLE
[ HELP ] Getting Stuck Finalizing Client After Wrong NVM [MUST WIPE TO USE]

### ISSUE THREAD

**Issue by fire17** [open-wa/wa-automate-nodejs#3166]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

If I accidently ran openwa with npx **without** doing `nvm use 20.11`
Now openwa is stuck at Finalizing Client
not sure if its a puppeteer issue or what ( v19.11.1 )
but even if I switch 20.11, it is still stuck

The only way I found to make openwa work again is wiping (or renaming) all the assosiated env data (session, npx, puppeteer cache) i could find
 
```
mv ~/.cache/puppeteer ~/.cache/puppeteer_x
mv ~/.npm/_npx ~/.npm/_npx_x
mv session.data.json session.data.json_xxx    # inside your project

# Now running npx openwa will need to install again, 
# And you will need to re-scan the barcode 
```

### Expected Behavior

I should get a message saying that the Node version i use is not compatible with a helpful
`nvm use 20.11`
or permenantly `echo 'nvm use 20.11' >> ~/.zshrc` (or the rc of your choice)

**I SHOULD BE ABLE TO USE OPENWA AGAIN after switching to the correct nvm WITHOUT WIPING**

### Steps To Reproduce

my nvm system default is `v18.17.1` which is problemtic with openwa
working on 20.11 but using a wrong version once
*Bricks* my openwa env

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2404.2",
  "WA_AUTOMATE_VERSION": "4.67.0",
  "BROWSER_VERSION": "HeadlessChrome/112.0.5614.0",
  "START_TS": 1706259130695,
  "RAM_INFO": "Total: 13.32 GB | Free: 11.88 GB",
  "PPTR_VERSION": "19.11.1",
  "LATEST_VERSION": true,
  "CLI": true
}
```

### Environment

```markdown
- OS: Linux 5.10
- Node: v18.17.1 (Problematic) then go v20.11.0 (working normally)
- npm: 10.3.0
```

### Screenshots/Logs

![image](https://github.com/open-wa/wa-automate-nodejs/assets/9356048/ddfc6f9b-de1d-4798-a5e7-a5a73f092d3f)
![image](https://github.com/open-wa/wa-automate-nodejs/assets/9356048/b08be545-31ab-43ec-9351-a292a530db35)

### Anything else?

Please let me know of a better way to fix my enviorenment, and not loose my session
i already put nvm use 20.11 in my zshrc, but incase such case happens again to me or someone it could be useful
using wrong nvm should brick my openwa env
cant tell you how much time ive wasted trying to solve this

Thanks a lot as always, and all the best!

**Comment by smashah** [comment]
Sorry it's been a while @fire17 

Please update to the latest version and try again. If it continues then feel free to bump this.
