### ISSUE TITLE
sendLinkWithAutoPreview not working

### ISSUE THREAD

**Issue by fire17** [open-wa/wa-automate-nodejs#3167]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

throws error and not sending message

### Steps To Reproduce

sendLinkWithAutoPreview(number, url, text) #not working

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.2404.2",
  "WA_AUTOMATE_VERSION": "4.67.0",
  "BROWSER_VERSION": "HeadlessChrome/112.0.5614.0",
  "START_TS": 1706275400234,
  "RAM_INFO": "Total: 13.32 GB | Free: 12.80 GB",
  "PPTR_VERSION": "19.11.1",
  "LATEST_VERSION": true,
  "CLI": true,
  "PATCH_HASH": "83450",
  "LAUNCH_TIME_MS": 95750,
  "ACC_TYPE": "PERSONAL",
  "chats": 509,
  "messages": 871,
  "contacts": 16423,
  "isMd": true,
  "INSTANCE_ID": "5829f303-29a1-4c60-a1a4-97216fb81142"
}
```

### Environment

```markdown
- OS: Linux 5.10
- Node: 20.11.0
- npm: 10.3.0
```

### Screenshots/Logs

![image](https://github.com/open-wa/wa-automate-nodejs/assets/9356048/79050159-9373-4578-af1c-3197d1d98d44)

### Anything else?

I'm pretty sure im not the only one having this issue, can anyone confirm otherwise?

hope this can be solved soon 🤞 
Thanks a lot 🙏 & All the best

**Comment by smashah** [comment]
should be fixed in latest version please restart and try again

**Comment by fire17** [comment]
> should be fixed in latest version please restart and try again

Your the best @smashah
