### ISSUE TITLE
Send custom message types, is it possible?

### ISSUE THREAD

**Issue by tinyCoder32** [open-wa/wa-automate-nodejs#317]
Hi, thanks again for the incredible work here.

Is there a way to send custom message types? Like the "Missed call" message or "User changed number" or other notification messages in chat? is it possible to send any of them with a custom text?

**Comment by smashah** [comment]
Why would you want to do something like that?

**Comment by tinyCoder32** [comment]
I want to "title" chat messages with some kind of topics, like the one I made below (inspected dom)

![image](https://user-images.githubusercontent.com/17817239/79226589-50c46180-7e67-11ea-9af0-db74c5609293.png)

Do you think this is possible?

**Comment by smashah** [comment]
Ok so you want to hijack these type of messages to add some custom text. Interesting proposal.

**Comment by tinyCoder32** [comment]
An missed call, or a "User changed phone number" notification, there are several ones we can use, but I don't know how to change the text, (the image above inspected in the browser).

**Comment by UnKnoWn-Consortium** [comment]
I doubt if the content or body of these "system" messages can be hijacked. This kind of messages are usually governed by `type` and `subtype` and the body is either used to carry payload to populate some existing templates inside the WhatsApp application or is simply left unused. 

We may be able to send such a crafted message and get it delivered via the WhatsApp network but I am not sure if the modified body will get displayed at all. One may very likely receive a few "Missed call" messages instead.

**Comment by smashah** [comment]
Yeh I managed to send one but it only showed up on the web instance. Generally these messages are sent by your device to your device in the chat after some sort of event. It's not sent to/from an external device. Might give it a few more attempts though.

**Comment by smashah** [comment]
Yeah not possible.... for now. Gets rejected by the phone. Maybe in the future. Closing for now.
