### ISSUE TITLE
sendPtt and sendAudio problem with crash

### ISSUE THREAD

**Issue by GladistonXD** [open-wa/wa-automate-nodejs#3172]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

My own code

### Current Behavior

When you sent more than one audio in the chat, WhatsApp web crashes and no longer sends any messages, I found a solution by disabling a parameter from 'waitForId' true to false.

```javascript
    sendPtt(to, file, quotedMsgId) {
        return __awaiter(this, void 0, void 0, function* () {
            return this.sendImage(to, file, 'ptt.ogg', '', quotedMsgId ? quotedMsgId : null, false, true);
        });
    }
```

### Expected Behavior

Find the id and send the audio.

### Steps To Reproduce

I send the audio, receive the audio, send another audio and the web crashes and doesn't send anything else.

### DEBUG INFO

```markdown
Error [TypeError]: Cannot read properties of undefined (reading 'id')
```

### Environment

```markdown
- OS: Windows 10
- Node: 20.11.1
- npm: 8.0.0
```

**Comment by smashah** [comment]
please restart and try again
