### ISSUE TITLE
Best way to send files from URL directly

### ISSUE THREAD

**Issue by tinyCoder32** [open-wa/wa-automate-nodejs#318]
Hi, thanks for the great work again.
I was working on bad methods to send a media message (an image as example) directly from a remote link, grapping the file and converting to base64 then sending .... etc, i couldn't achieve a reliable function.

Can you please advice me?

**Comment by blackchineykh** [comment]
You should download your file from the url as base64 first. You can use [fetch-base64](https://www.npmjs.com/package/fetch-base64). Then look at the params for sendImage or sendFile in the whatsapp client library

**Comment by smashah** [comment]
There are a million different ways to download a file. I agree with @blackchineykh 's suggestion. Might start using that one myself actually. Thanks

**Comment by m7mdcc** [comment]
> You should download your file from the url as base64 first. You can use [fetch-base64](https://www.npmjs.com/package/fetch-base64). Then look at the params for sendImage or sendFile in the whatsapp client library

I have tryout this package , but Iam facing this issue : https://github.com/gamell/fetch-base64/issues/11

but i did that in another way .

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.66](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.65...1.8.66) (2020-04-19)

- Release 1.8.66 [`af5db53`](https://github.com/open-wa/wa-automate-nodejs/commit/af5db5306fd8aedc2c08be90aeb9569dc65cbfac)
- implemented `sendFileFromUrl` #318 [`facff51`](https://github.com/open-wa/wa-automate-nodejs/commit/facff51e34a3cddd02fc53e0b1116c4f73d331e8)

**Comment by smashah** [comment]
@tinyCoder32 @blackchineykh @m7mdcc @apnerve You can now use [`sendFileFromUrl`](https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#sendfilefromurl) like so:

```javascript

//simple get

client.sendFileFromUrl(
'0000000000@c.us',
'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
dummy.pdf',
'Here is your dummy pdf')

//OR
//custom request using: https://github.com/axios/axios#request-config

client.sendFileFromUrl(
'0000000000@c.us',
'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
dummy.pdf',
'Here is your dummy pdf',{
    method: "post",
    proxy: {
    host: '127.0.0.1',
    port: 9000,
    auth: {
      username: 'mikeymike',
      password: 'rapunz3l'
    }
  },
})
```

**Comment by m7mdcc** [comment]
@smashah , requestConfig is just freaking good option , Thanks !

**Comment by smashah** [comment]
Np. Tested and confirmed to be working. Closing. Thanks
