### ISSUE TITLE
 Error upon restarting application: Checking session integrity > Session integrity check failed, trying again... 2 > WAPI inject: 3ms

### ISSUE THREAD

**Issue by TVARecordings** [open-wa/wa-automate-nodejs#3180]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

Dear SHAH.

Recently my Host-number was changed, i deleted the session data etc and connected the new host.
The first connection goes without a flaw. However, upon restarting the session after waiting at least 10 minutes, it returns this error:
`Checking session integrity`
`Session integrity check failed, trying again... 55`
`WAPI inject: 2ms`

### Expected Behavior

Just boot up like it did in the past. 

### Steps To Reproduce

Step 1: Connect new host.
Step 2: Wait anywhere between 10 minutes and infinite hours.
Step 3: Close the application (_npx pm2 stop index.js_ **or** close _cmd.exe_ if using npm start)
Step 4: Start the application again (_npx pm2 start index.js **or** cmd.exe _npm start_)
Step 5: Watch the output :D

### create() code OR full CLI command + CONFIG

```markdown
const configObject = {
  sessionId: 'aNewNameEachTimeTheSessionFails',
  authTimeout: 0,
  cacheEnabled: true,
  useChrome: true,
  cachedPatch: true,
  devtools: false,
  chromiumArgs: ['--no-sandbox'],
  disableSpins: true,
  headless: false, //new
  popup: false,
  qrTimeout: 0,
  messagePreprocessor: "AUTO_DECRYPT", 
  linkParser: "https://link.openwa.cloud/api",
  restartOnCrash: true,
  logInternalEvents: false, //ONLY TURN THIS ON IF ASKED TO!
  discord: 'That's a secret!',
  ezqr: true,
  callTimeout: 60000, // 600000
  licenseKey: "Mine <3", 
  screenshotOnInitializationBrowserError: false,
  hostNotificationLang: 'nl-nl',
  killProcessOnBrowserClose: true,
  killProcessOnTimeout: false,
  logConsole: false,
  logConsoleErrors: true,
  logFile: true,
  onError: "LOG_AND_FALSE",
};
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.3000.1012447370",
  "WA_AUTOMATE_VERSION": "4.68.0",
  "BROWSER_VERSION": "Chrome/123.0.6312.86",
  "START_TS": 1711987673274,
  "RAM_INFO": "Total: 68.62 GB | Free: 46.63 GB",
  "PPTR_VERSION": "19.11.1",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 20.11.1
- npm: 10.2.4
```

### Anything else?

Thanks for your hard work :-)

**Comment by victorfreire100** [comment]
I have the same problem. :(

**Comment by itzharDev** [comment]
same problem

**Comment by dmzoneill** [comment]
same problem

**Comment by TVARecordings** [comment]
> Same problem here, is it because of whatsapp changed their framework?

Most likely yes.

**Comment by victorfreire100** [comment]
Could it be that this repository died again? no updates :(

**Comment by donnyirianto** [comment]
any update?

**Comment by smashah** [comment]
#3184

Please update to the latest version and try again thanks
