### ISSUE TITLE
Error: TOSBLOCK

### ISSUE THREAD

**Issue by rickricardo** [open-wa/wa-automate-nodejs#3181]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

TOSBLOCK error message after loading whatsapp QRCode, whenever with headless true or not.

### Expected Behavior

Loading QRcode normally and inject message succesfull

### Steps To Reproduce

Iniatilize wa-automate to login a device

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.3000.1012503000",
  "WA_AUTOMATE_VERSION": "4.68.0",
  "BROWSER_VERSION": "Chrome/123.0.6312.106",
  "START_TS": 1712127944418,
  "RAM_INFO": "Total: 8.59 GB | Free: 0.48 GB",
  "PPTR_VERSION": "19.11.1",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: macOS Unknown
- Node: 19.9.0
- npm: 9.6.3
```

### Anything else?

I saw past issues related to TOSBLOCK, but none of the steps suggested solved for me.

**Comment by TVARecordings** [comment]
Hey, just stopping by to say there's a new NodeJS version (20.12.0 Long-Time-Service) and NPM 10.

But that's not related to your problem. 

PS: Please share your config-object. Perhaps consider upgrading your ram. You're hitting the 8gb limit.

**Comment by rickricardo** [comment]
create({
  sessionId:'session'+numId,
  multiDevice: multiDevice,
  useChrome: true,
  restartOnCrash: start,
  headless:false,
  throwErrorOnTosBlock:true,
  qrTimeout:40,
  authTimeout:40,
  killProcessOnBrowserClose: true,
  autoRefresh:true,
  qrRefreshS:15, 
  safeMode: false,
  customUserAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36',
  licenseKey: licenseKey
})
.then(async client => await start(client))
.catch(e=>{
  console.log('Error',e.message);
});

**Comment by smashah** [comment]
Rolling into #3184
