### ISSUE TITLE
Authentication timed out. Shutting down. Consider increasing authTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#authtimeout node:events:489

### ISSUE THREAD

**Issue by missoy** [open-wa/wa-automate-nodejs#3182]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

What is the problem？

when developer with docker

Authentication timed out. Shutting down. Consider increasing authTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#authtimeout
node:events:489

![微信截图_20240403173215](https://github.com/open-wa/wa-automate-nodejs/assets/30122532/c2ce502d-e374-4225-8c27-1ebe392cb2d6)

### Steps To Reproduce

1. docker run --name wa_8003 -e PORT=8003 -p 8003:8003 --init openwa/wa-automate -w 'http://wapi.lingxhair.com/api/openwa/webhook'

### DEBUG INFO

```markdown
{
"WA_VERSION": "2.3000.1012505996",
"PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
"WA_AUTOMATE_VERSION": "4.68.0",
"BROWSER_VERSION": "HeadlessChrome/114.0.5735.198",
"OS": "Linux 3.10",
"START_TS": 1712135706854,
"RAM_INFO": "Total: 7.92 GB | Free: 2.64 GB",
"PPTR_VERSION": "19.11.1"
}
```

### Environment

```markdown
- OS: CentOS 7
- Node: 16.20.2
- npm: 8.19.4
```

**Comment by TVARecordings** [comment]
Hello @missoy ,

I'd like to point out you're using a outdated version of NodeJS. You're NodeJS version 16.20.2 is outdated and no longer maintained.

I recommend you to updating to version 20.12.0, which is a Long-Time-Service (LTS) version. 
Your 16.20.2 version expired around Oct. 2023. 

https://nodejs.org/en/download

PS: I'm not a OPEN-WA/WA-AUTOMATE Developer.

**Comment by missoy** [comment]
> Hello @missoy ,
> 
> I'd like to point out you're using a outdated version of NodeJS. You're NodeJS version 16.20.2 is outdated and no longer maintained.
> 
> I recommend you to updating to version 20.12.0, which is a Long-Time-Service (LTS) version. Your 16.20.2 version expired around Oct. 2023.
> 
> https://nodejs.org/en/download
> 
> PS: I'm not a OPEN-WA/WA-AUTOMATE Developer.

Thank you for your answer. Have you encountered this bug during use？

**Comment by nrs1022** [comment]
> > Hello @missoy ,
> > I'd like to point out you're using a outdated version of NodeJS. You're NodeJS version 16.20.2 is outdated and no longer maintained.
> > I recommend you to updating to version 20.12.0, which is a Long-Time-Service (LTS) version. Your 16.20.2 version expired around Oct. 2023.
> > https://nodejs.org/en/download
> > PS: I'm not a OPEN-WA/WA-AUTOMATE Developer.
> 
> Thank you for your answer. Have you encountered this bug during use？

Hi, it seems WA changed QR display, if you use screenshot QR is shown in image.

**Comment by SenpaiCookies** [comment]
> > > Hello @missoy ,
> > > I'd like to point out you're using a outdated version of NodeJS. You're NodeJS version 16.20.2 is outdated and no longer maintained.
> > > I recommend you to updating to version 20.12.0, which is a Long-Time-Service (LTS) version. Your 16.20.2 version expired around Oct. 2023.
> > > https://nodejs.org/en/download
> > > PS: I'm not a OPEN-WA/WA-AUTOMATE Developer.
> > 
> > 
> > Thank you for your answer. Have you encountered this bug during use？
> 
> Hi, it seems WA changed QR display, if you use screenshot QR is shown in image.

I also have the same problem, I can't connect via WhatsApp and the QR display doesn't appear.

**Comment by smashah** [comment]
Rolling into #3184
