### ISSUE TITLE
QR does not appear

### ISSUE THREAD

**Issue by SenpaiCookies** [open-wa/wa-automate-nodejs#3183]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

Yesterday this problem started occurring, the QR image does not appear for me to connect via WhatsApp.

### Steps To Reproduce

npm start

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.3000.1012536975",
  "WA_AUTOMATE_VERSION": "4.68.0",
  "BROWSER_VERSION": "Chrome/123.0.6312.88",
  "START_TS": 1712231490459,
  "RAM_INFO": "Total: 17.14 GB | Free: 12.89 GB",
  "PPTR_VERSION": "19.11.1",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 21.7.1
- npm: 10.5.1
```

### Screenshots/Logs

![error](https://github.com/open-wa/wa-automate-nodejs/assets/76668695/bad9e057-bfb5-4ba3-88a8-746c4c700f46)

**Comment by donnyirianto** [comment]
iya saya juga menagalami, apakah sudah ada solusi?

**Comment by Sordinni** [comment]
![image](https://github.com/open-wa/wa-automate-nodejs/assets/69143644/72aa414a-9e0d-4a70-b274-fd7e283523b6)

**Comment by smashah** [comment]
Rolling into #3184
