### ISSUE TITLE
I'm stuck on authenticating

### ISSUE THREAD

**Issue by TBCCARDOSO** [open-wa/wa-automate-nodejs#3185]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

My own code

### Current Behavior

- Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.3000.1012569841%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.68.0%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/112.0.5614.0%22,%0A%20%20%22START_TS%22:%201712330153951,%0A%20%20%22RAM_INFO%22:%20%22Total:%2016.62%20GB%20%7C%20Free:%2013.11%20GB%22,%0A%20%20%22PPTR_VERSION%22:%20%2219.11.1%22,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20false%0A%7D&enviro=-%20OS:%20Linux%206.5%0A-%20Node:%2018.16.1%0A-%20npm:%209.5.1&labels=MD
- Time to injection: 615ms
- Invariant Violation Avoidance: 9ms
- Authenticating   ---> stuck here

### Steps To Reproduce

*

### create() code OR full CLI command + CONFIG

```markdown
*
```

### DEBUG INFO

```markdown
Debug info: {
  "WA_VERSION": "2.3000.1012569841",
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
  "WA_AUTOMATE_VERSION": "4.68.0",
  "BROWSER_VERSION": "HeadlessChrome/112.0.5614.0",
  "OS": "Linux 6.5",
  "START_TS": 1712330153951,
  "RAM_INFO": "Total: 16.62 GB | Free: 13.11 GB",
  "PPTR_VERSION": "19.11.1"
}
```

### Environment

```markdown
- OS: Ubuntu 20.04
Node: 13.14.0
npm: 7.6.3
```

**Comment by Sordinni** [comment]
![image](https://github.com/open-wa/wa-automate-nodejs/assets/69143644/6fafc30a-3756-4732-9809-80082c32df71)

**Comment by TBCCARDOSO** [comment]
Ok Thanks
