### ISSUE TITLE
client.inviteInfo return undefined

### ISSUE THREAD

**Issue by GamiDPC** [open-wa/wa-automate-nodejs#3187]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

when i use client.inviteInfo return undefined

### Expected Behavior

No response

### Steps To Reproduce

No response

### create() code OR full CLI command + CONFIG

```markdown
you.inviteInfo(req.body.url)
        .then(d => {
		  res.json({success: true, inviteInfo: d})
        })
        .catch(e => {
		  res.json({success: true, inviteInfo: e})
        })


return

{"success":true,"inviteInfo":{}}
```

### DEBUG INFO

```markdown
WA_VERSION - '2.3000.1012605925'                                                             PAGE_UA - 'WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' │
WA_AUTOMATE_VERSION - '4.71.1'                                                                  
BROWSER_VERSION - 'HeadlessChrome/112.0.5614.0'
```

### Environment

```markdown
- OS: Windows 10
- Node: v18.16.0
- npm: 9.5.1
```

### Screenshots/Logs

No response

### Anything else?

No response

**Comment by GamiDPC** [comment]
Will you fix it?

**Comment by smashah** [comment]
@GamiDPC this is fixed, update to latest version restart and try again
