### ISSUE TITLE
client.deleteMessage() returns Error [TypeError]: mmrrf(...) is not a function

### ISSUE THREAD

**Issue by TVARecordings** [open-wa/wa-automate-nodejs#3192]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

Dear, whenever i try to execute the `deleteMessage()` function, it errors. This is the console output:

> Error [TypeError]: mmrrf(...) is not a function
> at _0x1af873.<computed>._0x1af873.<computed> (evaluate at E:\AmecaCore\node_modules\@open-wa\wa-automate\dist\controllers\patch_manager.js:127:50, <anonymous>:0:301729)
> at window.<computed>.<computed> (evaluate at E:\AmecaCore\node_modules\@open-wa\wa-automate\dist\controllers\patch_manager.js:127:50, <anonymous>:0:302388)
> at #evaluate (E:\AmecaCore\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:222:56)
> at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> at async ExecutionContext.evaluate (E:\AmecaCore\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:117:16)
> at async IsolatedWorld.evaluate (E:\AmecaCore\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\IsolatedWorld.js:124:16)
> at async CdpFrame.evaluate (E:\AmecaCore\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:342:20)
> at async CdpPage.evaluate (E:\AmecaCore\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:828:20)

Code where i'm attempting to deleteMessage()
`await client.deleteMessage(from, id, false);`

### Steps To Reproduce

`await client.deleteMessage(from, id, false);`

### create() code OR full CLI command + CONFIG

```markdown
const configObject = {
  sessionId: 'aName',
  authTimeout: 0,
  cacheEnabled: true,
  useChrome: true,
  cachedPatch: true,
  devtools: false,
  chromiumArgs: ['--no-sandbox'],
  disableSpins: true,
  headless: false, //new
  popup: false,
  qrTimeout: 0,
  messagePreprocessor: "AUTO_DECRYPT", //"AUTO_DECRYPT","SCRUB"
  linkParser: "https://link.openwa.cloud/api",
  restartOnCrash: true,
  logInternalEvents: false, //ONLY TURN THIS ON IF ASKED TO!
  discord: 'Mine',
  ezqr: true,
  callTimeout: 0, // 600000
  licenseKey: "Mine"
  screenshotOnInitializationBrowserError: false,
  hostNotificationLang: 'nl-nl',
  killProcessOnBrowserClose: true,
  killProcessOnTimeout: false,
  logConsole: false,
  logConsoleErrors: true,
  logFile: true,
  onError: "LOG_AND_FALSE",
};
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.3000.1012730881",
  "WA_AUTOMATE_VERSION": "4.71.6",
  "BROWSER_VERSION": "Chrome/123.0.6312.107",
  "START_TS": 1712896586560,
  "RAM_INFO": "Total: 68.62 GB | Free: 49.70 GB",
  "PPTR_VERSION": "19.11.1",
  "LATEST_VERSION": true,
  "CLI": false
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 20.11.1
- npm: 10.2.4
```

### Anything else?

I'm aware of the framework update, i'm TangoOliverMike in your Discord.

Just reporting the bugs to help you & reporting them here so you have them all in 1 place.

**Comment by smashah** [comment]
should be patched. please restart and try again
