### ISSUE TITLE
Memory leak + cannot receive any message

### ISSUE THREAD

**Issue by BbayuGt** [open-wa/wa-automate-nodejs#3204]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

No message is being received, also its using abnormally high cpu and ram usage

![image](https://github.com/open-wa/wa-automate-nodejs/assets/49893593/36728536-38ad-449d-8725-8c9449f1602c)

### Expected Behavior

It normally using 500-700mb of ram, especially when it first boots up.

### Steps To Reproduce

Just start openwa normally

### create() code OR full CLI command + CONFIG

```markdown
services:

  wa:
    image: openwa/wa-automate
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
      - WA_SOCKET=true
      - WA_KEY=X
      - WA_LICENSE-KEY=X
      - WA_CUSTOM_USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
      - WA_BLOCK_ASSETS=true
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 4G
```

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.3000.1013215824",
  "WA_AUTOMATE_VERSION": "4.71.10",
  "BROWSER_VERSION": "HeadlessChrome/124.0.6367.60",
  "START_TS": 1714648159386,
  "RAM_INFO": "Total: 6.21 GB | Free: 5.51 GB",
  "PPTR_VERSION": "19.11.1",
  "LATEST_VERSION": true,
  "CLI": true
}
```

### Environment

```markdown
- OS: Linux 5.15
- Node: 21.7.3
- npm: 10.5.2
```

**Comment by BbayuGt** [comment]
Update: the memleaks seems to be gone, it uses ~400mb of ram now, but still no message received

**Comment by TVARecordings** [comment]
Happening here too. Just no response to onMessage() or onAnyMessage(). 
 Client.onGroupApprovalRequest() is down too.

**Comment by BbayuGt** [comment]
This has been fixed, thanks
