### ISSUE TITLE
await Client.forwardMessages('aChatId@g.us',message.id) returns error: [TypeError]: _0x5cfd3f[("Nlo" + "jX")](...) is not a function

### ISSUE THREAD

**Issue by TVARecordings** [open-wa/wa-automate-nodejs#3208]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

Forwarding messages is not working. 

Error output: 

> Error [TypeError]: _0x5cfd3f[("Nlo" + "jX")](...) is not a function
> at window.<computed>.<computed> (evaluate at E:\AmecaCore\node_modules\@open-wa\wa-automate\dist\controllers\patch_manager.js:127:50, <anonymous>:0:524852)
> at #evaluate (E:\AmecaCore\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:222:56)
> at async ExecutionContext.evaluate (E:\AmecaCore\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:117:16)
> at async IsolatedWorld.evaluate (E:\AmecaCore\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\IsolatedWorld.js:124:16)
> at async CdpFrame.evaluate (E:\AmecaCore\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:342:20)
> at async CdpPage.evaluate (E:\AmecaCore\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:828:20)

Code:
`await Client.forwardMessages('aChatIdHere@g.us',message.id)`

### Expected Behavior

Expected it to forward. 

### Steps To Reproduce

`await Client.forwardMessages('aChatIdHere@g.us',message.id)`

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.3000.1013449566",
  "WA_AUTOMATE_VERSION": "4.71.9 UPDATE AVAILABLE: 4.71.10",
  "BROWSER_VERSION": "Chrome/124.0.6367.119",
  "START_TS": 1715453973954,
  "RAM_INFO": "Total: 68.62 GB | Free: 48.39 GB",
  "PPTR_VERSION": "19.11.1",
  "LATEST_VERSION": false,
  "CLI": false,
  "PATCH_HASH": "CACHED-13180",
  "LAUNCH_TIME_MS": 6804,
  "ACC_TYPE": "BUSINESS",
  "chats": 102,
  "messages": 114,
  "contacts": 2433,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "1f6de42f-7816-43af-ba42-354b363cb1fe"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 20.11.1
- npm: 10.2.4
```

**Comment by smashah** [comment]
should be fixed

**Comment by smashah** [comment]
restart and try again
