### ISSUE TITLE
BROKEN METHODS:  2.2013.7

### ISSUE THREAD

**Issue by natanaelsimoes** [open-wa/wa-automate-nodejs#321]
**Describe the bug**
After read the QR Code, wpp behaves as it was opened at another place (but its not). If I press "Use here" nothing happens.

It also suggests to add this to the body of this issue:

```
[ 'Store.Conn.on' ]
```

**Steps to Reproduce**
1. Initialize wpp
2. Read QR
3. Get stuck

**Expected behavior**
Load contacts screen

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2013.7,
  PAGE_UA: WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36,
  WA_AUTOMATE_VERSION: 1.8.56,
  BROWSER_VERSION: Chrome/80.0.3987.163
}
```

**Host (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by smashah** [comment]
1. Try with the latest version
2. Which language/region are you in?
3. Please share your code

Thanks

**Comment by smashah** [comment]
Closing for now. If this continues please let me know.
