### ISSUE TITLE
Documentation still broken.

### ISSUE THREAD

**Issue by SvenPGH** [open-wa/wa-automate-nodejs#3219]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Tested and experienced on both

### What type of host account are you experiencing this issue on?

Tested and experienced on both

### Mode

My own code

### Current Behavior

Documentation is not accessible.

![Screenshot 2024-06-11 164259](https://github.com/open-wa/wa-automate-nodejs/assets/33489231/0442be9f-ab27-4249-9de2-10fd1a71f7e6)

### Expected Behavior

To be able to view the Documentation.

### Steps To Reproduce

Open the Docs: https://docs.openwa.dev/

### create() code OR full CLI command + CONFIG

```markdown
https://docs.openwa.dev/
```

### DEBUG INFO

```markdown
Failed to load resource: the server responded with a status of 404 ()
```

### Environment

```markdown
- OS: Windows
- Node: Not relevant
- npm: Not relevant
```

### Screenshots/Logs

![image](https://github.com/open-wa/wa-automate-nodejs/assets/33489231/e1673b1b-f623-452e-8c0b-34ba18e5a608)

### Anything else?

https://docs.openwa.dev/

**Comment by smashah** [comment]
fixed now thanks
