### ISSUE TITLE
Incoming message doesn’t work

### ISSUE THREAD

**Issue by ehsanhsnzd** [open-wa/wa-automate-nodejs#3223]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

Incoming message doesn’t work in chatwoot
there is error in console on headless false. console log attached below

### Expected Behavior

Incoming message works in chatwoot

### Steps To Reproduce

Incoming and sending message to any contact makes console error 

### create() code OR full CLI command + CONFIG

```markdown
npx @open-wa/wa-automate -p 4004 -k  --verbose  --force-update-cw-webhook --chatwoot-url "http://localhost:3000/" --chatwoot-api-access-token "your chatwoot access token"
```

### DEBUG INFO

```markdown
│ WA_VERSION          │ '2.3000.1014555762'                                                                                                                        │
│ PAGE_UA             │ 'WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' │
│ WA_AUTOMATE_VERSION │ '4.71.14'                                                                                                                                  │
│ BROWSER_VERSION     │ 'HeadlessChrome/112.0.5614.0'                                                                                                              │
│ OS                  │ 'macOS Unknown'                                                                                                                            │
│ START_TS            │ 1719579037996                                                                                                                              │
│ RAM_INFO            │ 'Total: 17.18 GB | Free: 0.51 GB'                                                                                                          │
│ PPTR_VERSION        │ '19.11.1'                                                                                                                                  │
```

### Environment

```markdown
- OS: MACOS
- Node: v22.1.0
- npm: 10.7.0
```

### Screenshots/Logs

![Screenshot 2024-06-28 at 3 31 53 PM](https://github.com/open-wa/wa-automate-nodejs/assets/44667607/fc462394-3eeb-4a5c-b91c-acf905a109e5)

**Comment by smashah** [comment]
this should be fixed now thanks
