### ISSUE TITLE
 Does not receive messages or send my bot

### ISSUE THREAD

**Issue by larevalo16** [open-wa/wa-automate-nodejs#3225]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Legacy (Normal)

### What type of host account are you experiencing this issue on?

Business account

### Mode

My own code

### Current Behavior

Does not receive messages or send my bot, It runs and was working very well but now it has stopped working, why is it?

### Steps To Reproduce

![Screenshot_1](https://github.com/open-wa/wa-automate-nodejs/assets/118988131/27022e3b-1602-458c-aa64-c43653014f89)

### DEBUG INFO

```markdown
{
  "WA_VERSION": "2.3000.1014557036",
  "WA_AUTOMATE_VERSION": "4.71.14",
  "BROWSER_VERSION": "HeadlessChrome/112.0.5614.0",
  "START_TS": 1719593604128,
  "RAM_INFO": "Total: 4.18 GB | Free: 0.68 GB",
  "PPTR_VERSION": "19.11.1",
  "LATEST_VERSION": true,
  "CLI": false,
  "PATCH_HASH": "65177",
  "LAUNCH_TIME_MS": 74868,
  "ACC_TYPE": "BUSINESS",
  "chats": 64,
  "messages": 470,
  "contacts": 846,
  "isBiz": true,
  "isMd": true,
  "INSTANCE_ID": "8fea1f7a-8e5a-4397-aad9-2484ee8d489d"
}
```

### Environment

```markdown
- OS: Windows 10
- Node: 20.14.0
- npm: 10.7.0
```

**Comment by puluceno** [comment]
same problem here, it started today

**Comment by Guilhermossauro** [comment]
same here 2

**Comment by byldrm** [comment]
same here

**Comment by smashah** [comment]
hey @byldrm @Guilhermossauro @puluceno @larevalo16 please restart and try again

**Comment by puluceno** [comment]
Yes, it just came back a few minutes ago. Thank you
