### ISSUE TITLE
stickerUrl.replace is not a function

### ISSUE THREAD

**Issue by keevferreira** [open-wa/wa-automate-nodejs#3229]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Personal account (normal)

### Mode

EASY API/CLI

### Current Behavior

Im trying to make a sticker with an image and this error apears "stickerUrl.replace is not a function" investigating i find the code and i see this
![error](https://github.com/user-attachments/assets/f322de1c-1a64-4fd1-8609-d84395cad4e6)
an boolean var doing a replace

### Steps To Reproduce

i use sendImageAsSticker function with this params

base 64
[base64-error.txt](https://github.com/user-attachments/files/16215464/base64-error.txt)

stickermetadata

{
  author: "trevas",
  pack: "trevas Stickers",
  keepScale: true,
  circle: false,
  discord: "701084178112053288",
}

and i call  
   
   client.sendImageAsSticker(chatId, imagemBase64, stickerMetadata).catch(err=>{
     consoleErro(err.message, "STICKER")
       client.reply(chatId, msgs_texto.figurinhas.sticker.erro_s,id)
     })

### DEBUG INFO

```markdown
WA_VERSION      2.3000.1014871542

PAGE_UA         WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

WA_AUTOMATE_VERSION 4.71.14

BROWSER_VERSION   Chrome/126.0.6478.126

OS Linux 6.9

START_TS 1720924745018

RAM_INFO Total: 8.20 GB | Free: 5.58 GB

PPTR_VERSION  19.11.1
```

### Environment

```markdown
- OS: Manjaro 6.9.5-1-MANJARO
- Node: 18.15.0
- npm: 9.5.0

  "dependencies": {
    "@open-wa/wa-automate": "^4.67.0",
    "@open-wa/wa-decrypt": "^1.0.6",
```

### Screenshots/Logs

![error-debbug](https://github.com/user-attachments/assets/2262d84d-b03f-4468-b525-40bd7371bc2f)

**Comment by Sordinni** [comment]
Oi boa noite. Na sua config, adicione `stickerServerEndpoint: false,`

**Comment by victorfreire100** [comment]
> Oi boa noite. Na sua config, adicione `stickerServerEndpoint: false`

Não funcionou aqui :(

**Comment by keevferreira** [comment]
> Oi boa noite. Na sua config, adicione `stickerServerEndpoint: false`

Muito obrigado! funcionou para as imagens, porem para o video esta dando erro para a propriedade message.clientUrl em decrypt.js pelo oq eu vi ela nao existe no objeto message

**Comment by Sordinni** [comment]
Essa aqui é a minha config

```
module.exports = config = (headless, start) =>  {
    return{
        sessionId: 'SordBOT_Business',
        authTimeout: 0,
        blockCrashLogs: true, 
        cacheEnabled: true, 
        cachedPatch: true, 
        callTimeout: 600000, 
        disableSpins: true, 
        ezqr: true,
        headless: true,
        logFile: true,
        messagePreprocessor: "AUTO_DECRYPT",
        onError: "LOG_AND_FALSE",
        popup: false,
        qrTimeout: 0,
        useChrome: true,
        debug: true,
        logging: [{
        type: console}],
        logInternalEvents: true, 
        logConsoleErrors: true,
    }}
``` Tem umas paradas que não sei pra que serve, mas o importante que está fazendo figurinhas estáticas tanto animadas.

**Comment by victorfreire100** [comment]
> Essa aqui é a minha config
> 
> ```
> module.exports = config = (headless, start) =>  {
>     return{
>         sessionId: 'SordBOT_Business',
>         authTimeout: 0,
>         blockCrashLogs: true, 
>         cacheEnabled: true, 
>         cachedPatch: true, 
>         callTimeout: 600000, 
>         disableSpins: true, 
>         ezqr: true,
>         headless: true,
>         logFile: true,
>         messagePreprocessor: "AUTO_DECRYPT",
>         onError: "LOG_AND_FALSE",
>         popup: false,
>         qrTimeout: 0,
>         useChrome: true,
>         debug: true,
>         logging: [{
>         type: console}],
>         logInternalEvents: true, 
>         logConsoleErrors: true,
>     }}
> ```
> 
> Tem umas paradas que não sei pra que serve, mas o importante que está fazendo figurinhas estáticas tanto animadas.

Deu certo, muito obrigado!!!

**Comment by keevferreira** [comment]
> Essa aqui é a minha config
> 
> ```
> module.exports = config = (headless, start) =>  {
>     return{
>         sessionId: 'SordBOT_Business',
>         authTimeout: 0,
>         blockCrashLogs: true, 
>         cacheEnabled: true, 
>         cachedPatch: true, 
>         callTimeout: 600000, 
>         disableSpins: true, 
>         ezqr: true,
>         headless: true,
>         logFile: true,
>         messagePreprocessor: "AUTO_DECRYPT",
>         onError: "LOG_AND_FALSE",
>         popup: false,
>         qrTimeout: 0,
>         useChrome: true,
>         debug: true,
>         logging: [{
>         type: console}],
>         logInternalEvents: true, 
>         logConsoleErrors: true,
>     }}
> ```
> 
> Tem umas paradas que não sei pra que serve, mas o importante que está fazendo figurinhas estáticas tanto animadas.

cara, funcionou aqui, nao sei exatamente qual flag fez a diferenca, na vdd suponho que seja uma combinacao delas, muito obrigado to usando essa sua agora
