### ISSUE TITLE
Timeout error on simulate typing false

### ISSUE THREAD

**Issue by devalexanderdaza** [open-wa/wa-automate-nodejs#327]
I have tried the "simulate typing" method and when it receives the parameter in true, in the receiving whatsapp it actually shows "typing". However, when it ends, it does not end and after a while the connection timeout.
I tried setTimeout to wait 3 seconds and it didn't work, I also just tried awaits and it didn't work either.

What I can be doing wrong? or is it a method error

**Comment by smashah** [comment]
Hey @devalexanderdaza it'd be hard to debug your issue without seeing the code however, there can be some improvements made to `simulateTyping`. I will be updating it in #326.

**Comment by smashah** [comment]
@devalexanderdaza try out 1.8.62. It should be working as expected now.
