### ISSUE TITLE
Using SendFile & Reply Message ?

### ISSUE THREAD

**Issue by m7mdcc** [open-wa/wa-automate-nodejs#332]
Hi , 

Can we sendfile as a reply to message ? 

Thanks

**Comment by smashah** [comment]
Not yet but it can be implemented.

**Comment by m7mdcc** [comment]
> Not yet but it can be implemented.

Do you know how to check if upload was finished from whatsapp side ?

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.64](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.63...1.8.64) (2020-04-18)

- Release 1.8.64 [`30e2954`](https://github.com/open-wa/wa-automate-nodejs/commit/30e295419af6530ea2fa99c1aa39e9c35e3b3235)
- now able to reply to messages with images, videos, files and gifs #332 [`4bfb20f`](https://github.com/open-wa/wa-automate-nodejs/commit/4bfb20fbc3c53137ccd8bad8c81dea356460088b)
- improved `reply` and `getNewMessageId` [`9534ece`](https://github.com/open-wa/wa-automate-nodejs/commit/9534ece28295e089ac046f4561cd1345fd0a5c78)
- updated release-image [`4ed6ab7`](https://github.com/open-wa/wa-automate-nodejs/commit/4ed6ab71eb71ca8321bfeecfa4c3efd29bbdf72b)

**Comment by smashah** [comment]
@m7mdcc You can now [sendImage](https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#sendimage), [sendFile](https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#sendfile) and [sendVideoAsGif](https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#sendvideoasgif) as a reply to a message.

```javascript
// You just need to add the message.id as the last parameter on each of those methods to reply to said message. E.g
await client.sendImage('data:image/jpe...`,'0000000000@c.us`,'file.jpeg','cool caption','false_000000000@c.us__32IUH2IUNFI2U3')
```

**Comment by m7mdcc** [comment]
I will test , sendFileFromUrl doesn't have this option right ? :(

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.68](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.67...1.8.68) (2020-04-19)

- Release 1.8.68 [`3415882`](https://github.com/open-wa/wa-automate-nodejs/commit/34158822e10bac2cd7b3c010f32719911ce4d75f)
- added `quotedMsgId` param to `sendFileFromUrl`, fixed docs #332 [`78a36b6`](https://github.com/open-wa/wa-automate-nodejs/commit/78a36b6d7678224d75a26c481330506d3197dd28)

**Comment by smashah** [comment]
@m7mdcc it should work now.

**Comment by m7mdcc** [comment]
>  it should work now.
Tested , working as exactly expected ! Thanks
