### ISSUE TITLE
Default user agent

### ISSUE THREAD

**Issue by classic-gentleman** [open-wa/wa-automate-nodejs#337]
https://github.com/open-wa/wa-automate-nodejs/blob/04274698f28c97973c25a900ea157927fde1d16e/src/config/puppeteer.config.ts#L46

Despite the numerous prominent warnings regarding the UA I have a kind of silly question to ask: why is this hardcoded? Why isn't the browser UA used by default?

I'm positive there are quirks in the WA code that look for this, and some might be platform specific. And the updating of the browser might be on a completely different regime than the update of the app (rolling release distros or auto update if running under Windows for instance).

And for all intents and purposes the current UA follows your development machine. I kind of got that hunch when I noticed the test UA on `wa-decrypt` matched mine exactly. Felt spooky at first but made sense after a couple seconds. 😅

**Comment by smashah** [comment]
A tale as old as time, you see, before #136 we used to have to play whack-a-mole with the user agent to stop our sessions from getting TOS_BLOCKED. That was hardcoded but also frequently updated to the most recently stable user agent that would seemingly prevent a TOS_BLOCK. Thankfully we don't need to do that anymore and the sessions remain valid. That function should just be deprecated and deleted.

**Comment by classic-gentleman** [comment]
Since we're down this topic would you like a PR that augments the client startup code with an optional session object so that it doesn't have to necessarily live in the file system? PRing is probably tidier than me pointing trivial patches here and there 😛 And of course definitely tidier for the nontrivial cases.

**Comment by smashah** [comment]
@classic-gentleman this functionality exists since around the same time 136 was resolved:

https://github.com/open-wa/wa-automate-nodejs/blob/a2af1166b47a18a116667f7e6d4d68be76f75166/src/api/model/index.ts#L92

https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#sessiondata

If you want you can make a PR for better documentation of this existing feature.

**Comment by classic-gentleman** [comment]
Hah, sorry, somehow I thought this was on another project but not on this. How clever of me. 😅
