### ISSUE TITLE
[FEATURE] Ability to change group icons.

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#338]
We can change everything about the group except the icon for now. Can't be that hard.

**Comment by smashah** [comment]
You should now be able to use [`setGroupIcon`](https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#setgroupicon) and [`setGroupIconByUrl`](https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#setgroupIconbyurl):

Please make sure to keep the icon small otherwise the method will fail

```javascript

import '@open-wa/wa-automate'

//set by datauri
await client.setGroupIcon('0000000000_0000000000@g.us','data:image/jpeg;base64,...');

//or by get request to url
await client.setgroupIconbyurl('0000000000_0000000000@g.us','https://upload.wikimedia.org/wikipedia/commons/3/38/JPEG_example_JPG_RIP_001.jpg');

//or with a custom request
await client.setgroupIconbyurl('0000000000_0000000000@g.us','https://upload.wikimedia.org/wikipedia/commons/3/38/JPEG_example_JPG_RIP_001.jpg', {
method:'post'
});

```

@roysG

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by roysG** [comment]
Thanks i will check it!!

**Comment by roysG** [comment]
I checked, i got error: 
"Failed to update group icon,Please try again later"

code:
await client.setGroupIconByUrl('972559661703-1587456110@g.us', 'https://res.cloudinary.com/picktags-com/image/upload/v1587297034/unnamed_3_vbkodw.png');

i also tried:

await client.setGroupIconByUrl('972559661703_1587456110@g.us', 'https://res.cloudinary.com/picktags-com/image/upload/v1587297034/unnamed_3_vbkodw.png');

**Comment by roysG** [comment]
Also method
