### ISSUE TITLE
sendImageAsSticker is not working

### ISSUE THREAD

**Issue by renato-macedo** [open-wa/wa-automate-nodejs#340]
**Describe the bug**
client.sendImageAsSticker never resolves and does not throw any error

**Steps to Reproduce**
1. Run the code

**create() code**
This is the code you use to create the client. e.g
```javascript
const fs = require('fs')
const wa = require('@open-wa/wa-automate');

wa.create({
  headless: false,
  devtools: true 
}).then(client => start(client));

function start(client) {
  client.onMessage(async message => {
    if (message.body === 'Hi') {
      await client.sendText(message.from, '👋 Hello!')
      const mimetype = 'jpg'
      const b64 = fs.readFileSync('./assets/image.jpg').toString('base64')
      await client.sendImageAsSticker(`data:${mimetype};base64,${b64}`, message.from)
    }
  });
}
```

**Expected behavior**
client.sendImageAsSticker should send the given image as sticker

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2013.7',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  WA_AUTOMATE_VERSION: '1.8.69',
  BROWSER_VERSION: 'Chrome/80.0.3987.0'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: [e.g. iOS] Windows 10

**Additional context**
The image I'm trying to send https://avatars2.githubusercontent.com/u/31698109?s=400&u=5788383d90807c8c157a778426431fff3d6dd8f3&v=4

**Comment by smashah** [comment]
@renato-macedo Thanks for making the issue. One last question. Are you sure the paths are correct? When you have a relative path it goes from your pwd and not relative from the file with the code. Either way looks like it would be useful here to have a sendStickerfromUrl method.

**Comment by smashah** [comment]
@renato-macedo 

In the upcoming version, this has been tested to be working:

```javascript
      await client.sendStickerfromUrl(message.from, 'https://avatars2.githubusercontent.com/u/31698109?s=400&u=5788383d90807c8c157a778426431fff3d6dd8f3&v=4')
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.72](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.71...1.8.72) (2020-04-20)

- Release 1.8.72 [`d85c936`](https://github.com/open-wa/wa-automate-nodejs/commit/d85c936d31151c5a39b8a97851486375e58d1f24)
- added `sendStickerfromUrl` switched params in `sendImageAsSticker` !BREAKING! #340 [`5fe40c6`](https://github.com/open-wa/wa-automate-nodejs/commit/5fe40c6aa55a552ce41ab3b5c45817056d75a3ce)
- Update comment-run.yml [`e6c7d79`](https://github.com/open-wa/wa-automate-nodejs/commit/e6c7d791f3246eb514fdc83ec3141eda9fcc7458)
- Update comment-run.yml [`1a94995`](https://github.com/open-wa/wa-automate-nodejs/commit/1a94995f6fa4a9ae11d58d02af273730919c802e)
- update release image [`761ae52`](https://github.com/open-wa/wa-automate-nodejs/commit/761ae52847e0736a847fef039eca34940ba4ad34)

**Comment by smashah** [comment]
@renato-macedo it should be live in v1.8.72

Please report back if it is working for you.

Thanks

**Comment by renato-macedo** [comment]
Thank you very much!
It's working now.
