### ISSUE TITLE
setGroupToAdminsOnly not working

### ISSUE THREAD

**Issue by roysG** [open-wa/wa-automate-nodejs#346]
Methods setGroupToAdminsOnly And setGroupEditToAdminsOnly not working

client.setGroupToAdminsOnly('972559661703-1587456110@g.us', true);
Nothing happens

client.setGroupEditToAdminsOnly('972559661703-1587456110@g.us', true);
WAPI.setGroupEditToAdminsOnly not function

**Comment by smashah** [comment]
That feature is for insiders only right now.

https://github.com/open-wa/wa-automate-nodejs/blob/master/README.md
