### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot destructure property 'presence' of 'Store.Chat.get(...)' as it is undefined.

### ISSUE THREAD

**Issue by SerhanCeetin** [open-wa/wa-automate-nodejs#347]
Sorry I am very new in this language. I am trying get all my contacts with their isOnline and lastSeen status.

```
const wa = require('@open-wa/wa-automate');

wa.create().then(client => start(client));


function start(client) {
	
	getirKe = async () => {
		const contacts = await client.getAllContacts();
		for (var i = 0; i < contacts.length; i++){
			if(contacts[i].isUser){
			console.log(i);			
			var lastSeen = await client.getLastSeen(contacts[i].id._serialized);
			var isOnline = await client.isChatOnline(contacts[i].id._serialized);
			
			console.log(contacts[i].id._serialized);
			console.log(lastSeen);
			console.log(isOnline);
			
			}
		}
	}
	getirKe();
  client.onMessage(message => {
    if (message.body === "Hi") {
      client.sendText(message.from, '👋 Hello!');
    }
  });
}
```

Error:

> √ Authenticated
> √ WAPI Reinjected
> √ Whatsapp is ready
> 2
> (node:13240) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot destructure property 'presence' of 'Store.Chat.get(...)' as it is undefined.
>     at Object.window.WAPI.getLastSeen (C:\Users\Serhan\node_modules\@open-wa\wa-automate\dist\lib\wapi.js:2286:10)
>     at __puppeteer_evaluation_script__:1:34
>     at ExecutionContext._evaluateInternal (C:\Users\Serhan\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async ExecutionContext.evaluate (C:\Users\Serhan\node_modules\puppeteer\lib\ExecutionContext.js:48:12)
>   -- ASYNC --
>     at ExecutionContext.<anonymous> (C:\Users\Serhan\node_modules\puppeteer\lib\helper.js:111:15)
>     at DOMWorld.evaluate (C:\Users\Serhan\node_modules\puppeteer\lib\DOMWorld.js:112:20)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>   -- ASYNC --
>     at Frame.<anonymous> (C:\Users\Serhan\node_modules\puppeteer\lib\helper.js:111:15)
>     at Page.evaluate (C:\Users\Serhan\node_modules\puppeteer\lib\Page.js:860:43)
>     at Page.<anonymous> (C:\Users\Serhan\node_modules\puppeteer\lib\helper.js:112:23)
>     at Whatsapp.<anonymous> (C:\Users\Serhan\node_modules\@open-wa\wa-automate\dist\api\whatsapp.js:855:50)
>     at step (C:\Users\Serhan\node_modules\@open-wa\wa-automate\dist\api\whatsapp.js:44:23)
>     at Object.next (C:\Users\Serhan\node_modules\@open-wa\wa-automate\dist\api\whatsapp.js:25:53)
>     at C:\Users\Serhan\node_modules\@open-wa\wa-automate\dist\api\whatsapp.js:19:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Serhan\node_modules\@open-wa\wa-automate\dist\api\whatsapp.js:15:12)
>     at Whatsapp.getLastSeen (C:\Users\Serhan\node_modules\@open-wa\wa-automate\dist\api\whatsapp.js:852:16)
>   -- ASYNC --
>     at Page.<anonymous> (C:\Users\Serhan\node_modules\puppeteer\lib\helper.js:111:15)
>     at Whatsapp.<anonymous> (C:\Users\Serhan\node_modules\@open-wa\wa-automate\dist\api\whatsapp.js:855:50)
>     at step (C:\Users\Serhan\node_modules\@open-wa\wa-automate\dist\api\whatsapp.js:44:23)
>     at Object.next (C:\Users\Serhan\node_modules\@open-wa\wa-automate\dist\api\whatsapp.js:25:53)
>     at C:\Users\Serhan\node_modules\@open-wa\wa-automate\dist\api\whatsapp.js:19:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Serhan\node_modules\@open-wa\wa-automate\dist\api\whatsapp.js:15:12)
>     at Whatsapp.getLastSeen (C:\Users\Serhan\node_modules\@open-wa\wa-automate\dist\api\whatsapp.js:852:16)
>     at getirKe (C:\Users\Serhan\Desktop\WHATSAPP\index.js:13:32)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:13240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:13240) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by smashah** [comment]
@SerhanCeetin you are not able to check isOnline or last seen on the contact object, only the chat object. So instead of looping through contacts, loop through the chats.

**Comment by SerhanCeetin** [comment]
> @SerhanCeetin you are not able to check isOnline or last seen on the contact object, only the chat object. So instead of looping through contacts, loop through the chats.

It is working now, thanks.

**Comment by smashah** [comment]
@SerhanCeetin great, in the next update, if a chat does not exist it will return false instead of an error.

**Comment by SerhanCeetin** [comment]
Is there any way for get isOnline status while don't already have chats with?

**Comment by smashah** [comment]
@SerhanCeetin nope. Change is now live in v1.8.74
