### ISSUE TITLE
isChatOnline, getLastSeen return 'false'

### ISSUE THREAD

**Issue by SerhanCeetin** [open-wa/wa-automate-nodejs#348]
**Describe the bug**
They return "false" all-time, even if the contact is online. I used to have conversation with the contact but deleted it, no more.

**index.js code**

```const wa = require('@open-wa/wa-automate');

wa.create().then(client => start(client));


function start(client) {
	
	getirKe = async () => {
		const chats = await client.getAllChats();
		const yuksel = await client.getChatById('x@c.us');
		const sonGorulme = await client.getLastSeen('x@c.us');
		const durumOnlinemi = await client.isChatOnline('x@c.us');
		console.log(yuksel);
		console.log(sonGorulme);
		console.log(durumOnlinemi);
	}
	getirKe();
  client.onMessage(message => {
    if (message.body === 'Hi') {
      client.sendText(message.from, '👋 Hello!');
    }
  });    
}
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2013.7,
  PAGE_UA: WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36,
  WA_AUTOMATE_VERSION: 1.8.74,
  BROWSER_VERSION: HeadlessChrome/80.0.3987.0
}
```

**Host (please complete the following information):**
 - OS: [WINDOWS 10]

**Comment by smashah** [comment]
I would not run this once at the beginning. You will need to call it multiple times to give you a proper result. So you should trigger them on an event and run it a few times before moving forward. If it continues, report back with the new code used.
