### ISSUE TITLE
Automatically maintain or reconnect session

### ISSUE THREAD

**Issue by devalexanderdaza** [open-wa/wa-automate-nodejs#355]
Hello! I am having a very particular problem and it is the following:

In my project, I use and manage wa-automate sessions without any problem. However, when a whatsapp is not used for a while even though it is connected to the api through my platform, the connection dies and I must restart the wa-automate server so that the user can scan the QR code again.

I have a couple of questions:

1. This may be a problem of the library or is it clearly the correct use of the exposed methods?
2. How can I automatically keep the session started without the user having to scan the QR code again in several days?
3. Is there an example that allows me to understand if this process should be done in the whatsapp status change listener?

Thank you very much for the time and the response.

**Comment by smashah** [comment]
That's really odd @devalexanderdaza the only way I've seen where a session is logged out and requires another scan, recently, is if the user logs out of the session from their phone. If you want to keep the session awake, a good idea would be to constantly ping a service WhatsApp number with a message and have that be an uptime indicator. With proper reproduction steps it'll be hard to solve this one. The sessions should restart without needing to scan QR code automatically. If you have the .data.json file in your process working directory (or injected through the create config.sessionData). I suggest filling out an issue template.

**Comment by smashah** [comment]
If this is consistently happening several days after you start the session, maybe try to restart them every night to keep them fresh.

**Comment by devalexanderdaza** [comment]
@smashah thanks. I will create a cron for the ping and another to restart the instances at night.
