### ISSUE TITLE
onParticipantsChanged

### ISSUE THREAD

**Issue by areltiyan** [open-wa/wa-automate-nodejs#356]
**Describe the bug**
Why onParticipantsChanged giving spam result like this?
before version running perfectly.

![image](https://user-images.githubusercontent.com/54056041/79993466-fc605800-84de-11ea-8b20-1f213a4492e6.png)

**Steps to Reproduce**
1. start whatsapp
2. and if someone chat in group, spamming messages happens
this is happened because of no chat in group (Clear Chat) and then someone send a message maybe?

**create() code**
This is the code you use to create the client. e.g
```
wa.create('akunbot', {
        executablePath: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
        headless: false,
       // restartOnCrash: start,
        autoRefresh: true,
    })
    .then(client => {
        start(client)
})
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2013.7
  PAGE_UA: WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
  WA_AUTOMATE_VERSION: 1.8.77
  BROWSER_VERSION: Chrome/81.0.4044.92
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Android 10

**Additional context**

**Comment by smashah** [comment]
@areltiyan fill in the steps to reproduce.

**Comment by areltiyan** [comment]
@smashah done

**Comment by smashah** [comment]
@areltiyan I've followed your steps. still cant reproduce. Please share you client code.

**Comment by areltiyan** [comment]
```
function anjay()
{
    return sulla
    .create('akunbot', {
        executablePath: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
        headless: false,
       // restartOnCrash: start,
        autoRefresh: true,
    })
    .then(async client => {
        start(client)
   })
}

async function start(client)
{
result.forEach(async hasil => { //result is array of GroupID
                         await client.onParticipantsChanged(`${hasil.groupowner}-${hasil.groupid}@g.us`, async message =>
                        {
                            console.log(message)
                            if(message.action == 'remove')
                            {
                                //await client.sendText(`${hasil.groupowner}-${hasil.groupid}@g.us`, hasil.remove)
                            }else if(message.action == 'leave')
                            {
                               // await client.sendText(`${hasil.groupowner}-${hasil.groupid}@g.us`, hasil.leave)
                            }else if(message.action == 'invite'){
                               // await client.sendText(`${hasil.groupowner}-${hasil.groupid}@g.us`, hasil.invite)
                            }else if(message.action == 'add'){
                                //await client.sendText(`${hasil.groupowner}-${hasil.groupid}@g.us`, hasil.add)
                            }
                        });       
                    });
}

anjay()
```

**Comment by smashah** [comment]
@areltiyan is this happening for every group? If not is it only for groups with no messages? Is it happening only once on start up or every time someone sends a message?

**Comment by smashah** [comment]
Also, are you sure someone isn't just adding all of those people into the group?

**Comment by areltiyan** [comment]
1. Maybe yes in every grup, but random group.
2. If started and someone send text in group.
3. Old group, and i not have group inactive.
4. I do not understand what you are asking

**Comment by areltiyan** [comment]
![image](https://user-images.githubusercontent.com/54056041/80040312-00629900-8524-11ea-931c-714d299a135d.png)

Maybe fixed, but need test @smashah

**Comment by areltiyan** [comment]
saya akan menutup masalah ini sebentar, akan terbuka lagi jika terjadi lagi 

i will close this issue for a while, will re-open if happens again.

**Comment by areltiyan** [comment]
still happens

**Comment by smashah** [comment]
Needs more information + screenshots of the chats that have the issue

**Comment by smashah** [comment]
@areltiyan you can now use the old onParticipanantsChanged by adding a third param.

```javascript
client.onParticipanantsChanged('00000000--00000000@g.us',x=>console.log(x),true);
```
