### ISSUE TITLE
[HOW TO] get a message id after sending it

### ISSUE THREAD

**Issue by ozkcs** [open-wa/wa-automate-nodejs#357]
how to get a message id after using client.reply(), 
for ex: client.reply(message.from, "blabla", message.id) then get the msg id for the message "blabla"sent

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.78](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.77...1.8.78) (2020-04-22)

- Bump ora from 4.0.3 to 4.0.4 [`#350`](https://github.com/open-wa/wa-automate-nodejs/pull/350)
- Bump @types/node from 13.13.1 to 13.13.2 [`#352`](https://github.com/open-wa/wa-automate-nodejs/pull/352)
- Bump prettier from 2.0.4 to 2.0.5 [`#351`](https://github.com/open-wa/wa-automate-nodejs/pull/351)
- Bump release-it from 13.5.4 to 13.5.5 [`#353`](https://github.com/open-wa/wa-automate-nodejs/pull/353)
- Release 1.8.78 [`a517d9d`](https://github.com/open-wa/wa-automate-nodejs/commit/a517d9d6d58b17989f5514a3c08ce4801ae3182d)
- reply should now return message id or false #357 [`0f8af9e`](https://github.com/open-wa/wa-automate-nodejs/commit/0f8af9e82ae229b29ebba1b6229fb9d43a4a908e)
- if chat doesn't exist when sending location, it will return false [`75b2714`](https://github.com/open-wa/wa-automate-nodejs/commit/75b271441723ab6a664b1e1f5fc4f105f5bce3ba)

**Comment by smashah** [comment]
@ozkcs please report back if it works in latest version.

**Comment by ozkcs** [comment]
![image](https://user-images.githubusercontent.com/35303121/80043532-61647f80-84d8-11ea-9515-7a3fdedb2b1d.png)
worked, can u add to sendText(), sendTextWithMentions(), etc?

**Comment by smashah** [comment]
great. @ozkcs those methods already return ids.
