### ISSUE TITLE
[REQUEST] Check if is updated

### ISSUE THREAD

**Issue by ozkcs** [open-wa/wa-automate-nodejs#358]
Basically always at the start of module, check if it is updated comparing to https://github.com/open-wa/wa-automate-nodejs/blob/a517d9d6d58b17989f5514a3c08ce4801ae3182d/package.json#L3, if yes, log to user update the module before try to inject

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.79](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.78...1.8.79) (2020-04-23)

- Release 1.8.79 [`913aa15`](https://github.com/open-wa/wa-automate-nodejs/commit/913aa158509bb682fdbd6ad61ea655180366f756)
- WA_AUTOMATE_VERSION shows update message + at process kill #358 [`a68f2e3`](https://github.com/open-wa/wa-automate-nodejs/commit/a68f2e364f4c23d4a51915f05b772f3be0314577)

**Comment by smashah** [comment]
The update message should show up in the debug info the second time after a new update and it will show up with the standard update box when the process is killed (idk why it shows up at the end). Should be good enough for now.
