### ISSUE TITLE
!!!!!BROKEN METHODS DETECTED!!!!

### ISSUE THREAD

**Issue by Animeliza** [open-wa/wa-automate-nodejs#369]
Boa noite amigo, recebi essa msg ao subir uma nova instancia do container no docker

!!!!!BROKEN METHODS DETECTED!!!!

Please make a new issue in:

 https://github.com/open-wa/wa-automate-nodejs/issues

with the following title:

BROKEN METHODS:  2.2017.6

Add this to the body of the issue:

 [ 'Store.bp', 'Store.MsgKey' ]

!!!!!BROKEN METHODS DETECTED!!!!

**Comment by m7mdcc** [comment]
I faces this, but its happened sometimes , if i restart the app then its gone .. 

Text message is not working now

**Comment by smashah** [comment]
@Animeliza thanks for bringing this up. They've pushed a new version and some features of this lib are now broke. Will fix soon. Thanks

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.2](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.1...1.9.2) (2020-04-28)

- Bump ts-node from 8.9.0 to 8.9.1 [`#365`](https://github.com/open-wa/wa-automate-nodejs/pull/365)
- Bump typedoc from 0.17.4 to 0.17.6 [`#366`](https://github.com/open-wa/wa-automate-nodejs/pull/366)
- Bump @types/node from 13.13.2 to 13.13.4 [`#367`](https://github.com/open-wa/wa-automate-nodejs/pull/367)
- Bump shelljs from 0.8.3 to 0.8.4 [`#368`](https://github.com/open-wa/wa-automate-nodejs/pull/368)
- Release 1.9.2 [`ba325f5`](https://github.com/open-wa/wa-automate-nodejs/commit/ba325f5a5a24419fac1d325c16805d2345b25bce)
- Fix: Working for latest version of WA (2.2017.6) #369 [`14fbbcd`](https://github.com/open-wa/wa-automate-nodejs/commit/14fbbcd32d07f834bd85a0e1e083e24a046d68a8)
- Fix: Working for latest version of WA (2.2017.6) [`f0be616`](https://github.com/open-wa/wa-automate-nodejs/commit/f0be616b30d0e9df3fccf2c4736bc19c9b1b2b91)

**Comment by smashah** [comment]
@m7mdcc @Animeliza should be working now. Thanks for reporting! WA updates go out in alphabetical order so places like brazil get it before other places. Please try it out and report back if it worked for you or if there are any issues. Thanks

**Comment by m7mdcc** [comment]
Thanks for update , Text message working now .. but media messaging is not .

**Comment by m7mdcc** [comment]
Last update fix media messaging , Thanks @smashah
