### ISSUE TITLE
Get All Messages in Chat error if there's a "reply Status" message

### ISSUE THREAD

**Issue by JoeDozan24** [open-wa/wa-automate-nodejs#372]
**Describe the bug**

**Steps to Reproduce**
1. Start open-wa as usual
2. Reply someone's status like #293 
3. Get all messages using client.getAllMessagesInChat("xxxx@c.us", true)
4. Error shown on cmd/console

**Expected behavior**
Get All Messages in chat return messages in chat

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2017.6,
  PAGE_UA: WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36,
  WA_AUTOMATE_VERSION: 1.9.2,
  BROWSER_VERSION: HeadlessChrome/80.0.3987.0
}
```

**Screenshots**
![status reply](https://user-images.githubusercontent.com/58735845/80504401-40e76a00-899d-11ea-8798-115232833d0b.png)
![image](https://user-images.githubusercontent.com/58735845/80504581-7d1aca80-899d-11ea-837a-e7fa443456b8.png)

**Host (please complete the following information):**
 - OS: Windows

**Comment by smashah** [comment]
@JoeDozan24 please share the whole error log as text. Not a screenshot. You've cropped all pertinent information out of the logs. If this happens again I will automatically close the issue.

**Comment by smashah** [comment]
@JoeDozan24 I think the issue is the message above the last one. If the status reply was the issue then the error logs would show status@broadcast instead of the number.

**Comment by JoeDozan24** [comment]
Sorry for this misinformation..
Found out the "Status Reply" was fine, but not the reply
I'm closing this and reopen new issue
