### ISSUE TITLE
Audio Messages & voice notes not detected 

### ISSUE THREAD

**Issue by m7mdcc** [open-wa/wa-automate-nodejs#374]
**Describe the bug**
Audio Messages & Voice notes not been detected . I made catch to all messages received . 

so if any contact send audio or voice notes i can't catch it .

**Steps to Reproduce**
1. run main script
2. lets any one send audio message or voice notes
3. catch all command doesn't show this message since its catch all other messages
4. I dont see any error 

**create() code**
This is the code you use to create the client. e.g
```

` 

    console.log("We got message from "+msg.from+" Mime type for this message is "+msg.mimetype)

  }`
```

**Expected behavior**

IT's must catch those messages types .

**DEBUG INFO**
 No logs
```
Debug Info {
│     WA_VERSION      │                                                                 '2.2017.6'                                                                  │
│       PAGE_UA       │ 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '1.9.3'                                                                   │
│   BROWSER_VERSION   │                                                       'HeadlessChrome/81.0.4044.122'   
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
Please share the actual code you are using after creating the client. I've just tested with voice notes and it's working as expected.

**Comment by m7mdcc** [comment]
```
const sulla =  require('@open-wa/wa-automate');
sulla.create("session1", {
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
    headless: true,
    executablePath: "/usr/bin/google-chrome"
  }).then(async client => {


    processMessages(client)
  }
  
```

**Comment by smashah** [comment]
@m7mdcc The issue is with `processMessages`. Please share that code.

**Comment by m7mdcc** [comment]
@smashah , My bad ! this function manipulate msg.body which cause error when the message is sticker , audio message or voice notes since msg.body is undefined in this cases . 
Closing
