### ISSUE TITLE
BROKEN METHODS:  2.2017.6

### ISSUE THREAD

**Issue by ichiopro** [open-wa/wa-automate-nodejs#377]
Hi.. i found this error after scanned the qrCode =

 [ 'Store.Participants.removeParticipants',
  'Store.Participants.addParticipants',
  'Store.Participants.promoteParticipants',
  'Store.Participants.demoteParticipants' ]

Note : i use centos 7 CLI as a server

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
