### ISSUE TITLE
BROKEN METHODS:  2.2017.6

### ISSUE THREAD

**Issue by llakes** [open-wa/wa-automate-nodejs#381]
[ 'Store.bp', 'Store.MsgKey' ] 

**Describe the bug**

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by m7mdcc** [comment]
update to latest version 
npm update

**Comment by llakes** [comment]
Okay, thanks.

**Comment by m7mdcc** [comment]
Close if that solved your issue 👯‍♂️
