### ISSUE TITLE
Reply to message doesn't sendSeen ? 

### ISSUE THREAD

**Issue by m7mdcc** [open-wa/wa-automate-nodejs#383]
**Describe the bug**
If you reply to a message via Client.reply , this message still not read even if you replied to  it . 
Should i send it manually ? 

**Steps to Reproduce**
1. let any contact send message to you
2. reply to this message 
3. the message still un seen for the original sender
4. No error

Reply to message code 
```javascript
 await client.reply(msg.from, "some text here ", msg);
```

**Expected behavior**

The message must be seen if the bot replied to it . 

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```

Debug Info {
│     WA_VERSION      │                                                                 '2.2017.6'                                                                  │
│       PAGE_UA       │ 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '1.9.3'                                                                   │
│   BROWSER_VERSION   │                                                       'HeadlessChrome/81.0.4044.122'   
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**
message object passed as last parameter for reply function 

If you use sendtext its will send SendSeen without any issue .

**Comment by smashah** [comment]
@m7mdcc yes, send it manually for now.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.5](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.4...1.9.5) (2020-05-01)

- Bump release-it from 13.5.6 to 13.5.7 [`#378`](https://github.com/open-wa/wa-automate-nodejs/pull/378)
- Bump puppeteer from 3.0.1 to 3.0.2 [`#379`](https://github.com/open-wa/wa-automate-nodejs/pull/379)
- Release 1.9.5 [`9f78895`](https://github.com/open-wa/wa-automate-nodejs/commit/9f7889524adbe06cdec9960df4d4dd1801ae5307)
- chore: clean up WAPI.js refactor out buttons [`c5fd7dd`](https://github.com/open-wa/wa-automate-nodejs/commit/c5fd7ddc57fe7aae94eb21858ab3fde5f55dcc03)
- update readme [`79b6a90`](https://github.com/open-wa/wa-automate-nodejs/commit/79b6a90b5961fe0eb83934e17714daa8472d07c7)
- feature: Optionally sendSeen on reply #383 [`4423c91`](https://github.com/open-wa/wa-automate-nodejs/commit/4423c91e96f94083cbc6eff3104f0ecf2f6a116a)
- stability improvements [`df0aaf1`](https://github.com/open-wa/wa-automate-nodejs/commit/df0aaf1af8f18381566e13dbb0a50704a4fc83d3)
- Checks for update when broken methods are detected [`f9aebd7`](https://github.com/open-wa/wa-automate-nodejs/commit/f9aebd75ba03a5657f36b8178468a04dc5fcb5d8)

**Comment by smashah** [comment]
@m7mdcc you can now use the following code to sendSeen automatically before sending the reply.

```javascript

//if fourth param is true then it will sendSeen before reply
 await client.reply(msg.from, "some text here ", msg, true);
```

**Comment by m7mdcc** [comment]
Tested , Thanks .. 

But i think its normal behavior to mark message as seen if you reply to it , i mean automatic way .

**Comment by m7mdcc** [comment]
Tested , Thanks @smashah  ..

But i think its normal behavior to mark message as seen if you reply to it , i mean automatic way .

**Comment by smashah** [comment]
@m7mdcc if more people bring it up I'll set it as true by default.
