### ISSUE TITLE
[FEATURE]  to search chat or contact

### ISSUE THREAD

**Issue by hasanbasri1993** [open-wa/wa-automate-nodejs#389]
![Search Chats ](https://i.imgur.com/hPqviRIl.png)
Hope this _pandemi_ (CORONA VIRUS) will end shortly 

thanks you.

**Comment by smashah** [comment]
There are no plans to automate the UI. Try:

https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#getcontact

https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#getchat
