### ISSUE TITLE
Message triggered As new message multiple times 

### ISSUE THREAD

**Issue by m7mdcc** [open-wa/wa-automate-nodejs#390]
**Describe the bug**
If you send one message to bot its will be triggered as new message , 
then if you send another one , first one & second one will be triggered as new message . 

Issue is affecting in versions : 1.9.5 & 1.9.6 . rollback to 1.9.4 for now 

**Steps to Reproduce**
1. Send Message to bot
2. then send another message 
3. first message will be triggered as new message twice 
4. if you send another message , all of message above will be triggered as new message 

**create() code**
This is the code you use to create the client. e.g
```
  client.onMessage(async message => {
       console.log("We got newMessage !! Message from "+message.from+" Message body "+message.body)

```

**Expected behavior**
the message must be triggered as new message one time . 

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION      │                                                                 '2.2017.6'                                                                  │
│       PAGE_UA       │ 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '1.9.6'                                                                   │
│   BROWSER_VERSION   │                                                       'HeadlessChrome/81.0.4044.129'                                                        │
└─────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: ubuntu

**Additional context**

**Comment by smashah** [comment]
I don't see how rolling back to 1.9.4 would fix your issue. Is that all you're changing?

**Comment by m7mdcc** [comment]
@smashah  Yes. Same code on  1.9.4  .

**Comment by UnKnoWn-Consortium** [comment]
I have encountered the exact same issue. It seems it is triggered when a lot of new messages arrive at a short time span. It even crashed the runtime ultimately. The only thing I have touched is bumping from 1.9.4 to 1.9.6. Reverted to 1.9.4 and this issue is gone.

**Comment by smashah** [comment]
Please try v1.9.7 @m7mdcc @UnKnoWn-Consortium

**Comment by m7mdcc** [comment]
Tested , Thanks @smashah

**Comment by UnKnoWn-Consortium** [comment]
@smashah It seems to have fixed the issue. Will keep an eye on it. Thanks a lot.
