### ISSUE TITLE
Authentication time

### ISSUE THREAD

**Issue by areltiyan** [open-wa/wa-automate-nodejs#391]
can i set the timeout while Authentication ?
and then if time is up restarting.

**Comment by smashah** [comment]
https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#killtimer

**Comment by areltiyan** [comment]
![image](https://user-images.githubusercontent.com/54056041/80921050-e9cb0600-8d9d-11ea-9e2a-4b34f04ded99.png)

work for this? maybe that for QR and kill only not restart seasson.
