### ISSUE TITLE
state "UNLAUNCHED" when the whatsapp open after 10 - 15 minutes (estimated)

### ISSUE THREAD

**Issue by roysG** [open-wa/wa-automate-nodejs#397]
When the whatsapp got on state "UNLAUNCHED" the WAPI object removed from to window object

Version: 1.8.74

headless option is "false"

**Comment by smashah** [comment]
@roysG please don't use such old versions of the library. There are so many fixes and updates from this end and from WhatsApp themselves. You should always use the latest version before making an issue (with the template).

**Comment by roysG** [comment]
I do not paste the correct version,
My version is: 1.9.5

**Comment by smashah** [comment]
The main problem here is that your session is becoming UNLAUNCED in the first place.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
