### ISSUE TITLE
Broken Method Detected

### ISSUE THREAD

**Issue by mrbarnk** [open-wa/wa-automate-nodejs#398]
Hi @smashah , I woke up to this, this morning.

It seems the `sendContact` and `sendLocation` methods are not working any longer.

`!!!!!BROKEN METHODS DETECTED!!!!
0|index  | Please make a new issue in:
0|index  |  https://github.com/smashah/sulla/issues
0|index  | with the following title:
0|index  | BROKEN METHODS:  2.2017.6
0|index  | Add this to the body of the issue:
0|index  |  [ 'Store.bp', 'Store.MsgKey' ]
0|index  | !!!!!BROKEN METHODS DETECTED!!!!`

I'm using the latest version.

` WA_VERSION      │                                                                 '2.2017.6'
                                                           │
0|index  | │       PAGE_UA        │ 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36' │
0|index  | │ SULLA_HOTFIX_VERSION │                                                                  '1.8.42'`

**Comment by smashah** [comment]
@mrbarnk v1.8.42 is an ancient version of this library. Please clear you're node modules folder and explicitly use the latest version of this library. We should be at v.1.9.9 right now

**Comment by mrbarnk** [comment]
Thanks so much, I just discovered that I was using the sulla-hotfix.

Now, I've tried cleaning the node_modules, but I am not getting this error.
`Failed to launch the browser process!
0|index  | /root/**/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory`

**Comment by mrbarnk** [comment]
but after writing `ls file path`, I found this.
![image](https://user-images.githubusercontent.com/37006356/81103703-49bccc00-8ec6-11ea-9f15-b94365a388b5.png)

**Comment by mrbarnk** [comment]
but after writing `ls /root/**/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome`, I found this.

![image](https://user-images.githubusercontent.com/37006356/81103873-84beff80-8ec6-11ea-9bb1-6dad73afbc5a.png)

**Comment by mrbarnk** [comment]
You don't have to bother anylonger, I think it's Linux chrome error.
