### ISSUE TITLE
Get online status without chat

### ISSUE THREAD

**Issue by metinkun** [open-wa/wa-automate-nodejs#401]
On official WhatsApp web we can see contacts online status wihtout any chat message. But in this repository , isChatOnline function needs chatid parameter. i need isChatOnline function with contactid parameter. ( Exp: isChatOnline(contactId)).

**Comment by smashah** [comment]
Duplicate #283 

https://github.com/open-wa/wa-automate-nodejs/issues/283#issuecomment-609714049
