### ISSUE TITLE
How to send --proxy-server to args?

### ISSUE THREAD

**Issue by sandro-salles** [open-wa/wa-automate-nodejs#402]
Hey guys! First of all, great work here... ! Congrats!

Now, i'm trying to set the browser instance to use a proxy-server (i'm currently using luminati), and they point to these instructions page in order to configure puppeteer to use their proxy:
https://luminati.io/integration/puppeteer

But i was taking a look to the code e it seems to me that currently i cannot send that to puppeteer instance... i'm i right or there's a way to do that?

By the way, let me know if i can help with something!

Regards!

**Comment by smashah** [comment]
Rtfd https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#chromiumargs
