### ISSUE TITLE
cant find selector error when qr show on screen for long time

### ISSUE THREAD

**Issue by roysG** [open-wa/wa-automate-nodejs#405]
Version: 1.9.9

When the qr code scan show on screen for long time and user scan it

he got error some error: cant find selector [alt="Scan me"]....

My Code:

const client = await create({
            autoRefresh:true, //default to true
            qrRefreshS:25,
            executablePath: process.platform === 'linux' ? "/usr/bin/google-chrome" : "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
            headless: process.platform === 'linux' ? true : false,
        });

**Comment by smashah** [comment]
Nowhere in the code does it check for the selector `[alt="Scan me"]`. Please make sure you're using the latest version of this library.

If you continue to fail to use the issue template properly as instructed, all of your issues will be auto-closing from now on with no response.
