### ISSUE TITLE
Error decrypting media sent

### ISSUE THREAD

**Issue by weverkley** [open-wa/wa-automate-nodejs#407]
**Describe the bug**
When i try to decrypt a media inside a message wich was sent by me it fires an error and doesn't decrypt correctly.

**Steps to Reproduce**
1. Setup onAnyMessage event handler
2. try to decrypt message await decryptMedia(message)

**create() code**
This is the code you use to create the client. e.g
```javascript
create('session', {
  headless: true,
  autoRefresh: true,
  args: [
    '--proxy-server="direct://"',
    '--proxy-bypass-list=*'
  ]
}).then(client => start(client));
```

**Expected behavior**
receive a file decrypt to be saved on a folder.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2017.6',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  WA_AUTOMATE_VERSION: '1.9.9',
  BROWSER_VERSION: 'HeadlessChrome/81.0.4044.0'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Windows

**Additional context**
Some screenshot [image](https://prnt.sc/sc97pm)

**Comment by smashah** [comment]
@weverkley Please attach all relevant images to the issue next time. That page is full of garbage ads.

This is happening because you get the message when the file starts uploading. At that point, there is no clientUrl leading to the error.

**Comment by weverkley** [comment]
> @weverkley Please attach all relevant images to the issue next time. That page is full of garbage ads.
> 
> This is happening because you get the message when the file starts uploading. At that point, there is no clientUrl leading to the error.

So, which event is fired when the image is fully uploaded? or how to wait to it?

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.10](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.9...1.9.10) (2020-05-07)

- Bump @types/node from 13.13.4 to 13.13.5 [`#403`](https://github.com/open-wa/wa-automate-nodejs/pull/403)
- Release 1.9.10 [`170e296`](https://github.com/open-wa/wa-automate-nodejs/commit/170e296ef164867f3caf422b90124fd05ae4b2c3)
- wait for mediaData when self uploads file in onAnyMessage #407 [`0b75132`](https://github.com/open-wa/wa-automate-nodejs/commit/0b751325200cd24498e2e926d34b5d47b97ffd71)
- feature: added getMessageById [`ac614ed`](https://github.com/open-wa/wa-automate-nodejs/commit/ac614ed84cfdba8b4913bc46c5caf57410aa9b83)
- feature: allow on-demand injection of jsSha [`a3e5025`](https://github.com/open-wa/wa-automate-nodejs/commit/a3e5025025b6581d3e583d1a050a40967f0ce77b)

**Comment by smashah** [comment]
@weverkley try the new version. It now waits for the clientUrl before firing the callback. Let me know if it works for you.

**Comment by weverkley** [comment]
> @weverkley try the new version. It now waits for the clientUrl before firing the callback. Let me know if it works for you.

awesome, thanks ill try it now

**Comment by weverkley** [comment]
![image](https://user-images.githubusercontent.com/13935185/81250788-36aa1900-8ff8-11ea-9b4b-b3a4c44ed553.png)
Still the same error, its not waiting

**Comment by smashah** [comment]
@weverkley how are you testing this? I've fixed it for when you upload a file from the host phone. But yeah it doesn't seem to work when sending a file from the bot for which I would ask why you need to decrypt media that you just sent with the bot??

**Comment by weverkley** [comment]
> @weverkley how are you testing this? I've fixed it for when you upload a file from the host phone. But yeah it doesn't seem to work when sending a file from the bot for which I would ask why you need to decrypt media that you just sent with the bot??
I am reproducing whatsapp web so i need to send and save them in a local cache to display in the client side


> @weverkley how are you testing this? I've fixed it for when you upload a file from the host phone. But yeah it doesn't seem to work when sending a file from the bot for which I would ask why you need to decrypt media that you just sent with the bot??

I am reproducing whatsapp web so i need to send and save them in a local cache to display in the client side

**Comment by smashah** [comment]
ok, give me a few mins.

**Comment by smashah** [comment]
This should fix it: 170e296

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.11](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.10...1.9.11) (2020-05-07)

- Release 1.9.11 [`099df2c`](https://github.com/open-wa/wa-automate-nodejs/commit/099df2cb6f1d7825802cf56427a9b0b1ba38c9af)
- Decrypt should work on all media in onAnyMessage + improved sendImage [`9f5d966`](https://github.com/open-wa/wa-automate-nodejs/commit/9f5d9669f050eed8c82fa79493283eb29804eeb3)

**Comment by smashah** [comment]
@weverkley try it out let me know if it's working now.

**Comment by weverkley** [comment]
@smashah now its working, i can decrypt and save the media.
