### ISSUE TITLE
Nothing happens in the function onLiveLocation

### ISSUE THREAD

**Issue by ctoveloz** [open-wa/wa-automate-nodejs#409]
**Describe the bug**
I'm testing the functionality `onLiveLocation` but I only get an encrypted message on the console.

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```
client.onLiveLocation("559892099xxx@c.us", (liveLocation) => {
    console.log("You are moved", liveLocation);
  });
```

**Expected behavior**
latitude, longitude, speed

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 1.9.7
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
![download11](https://user-images.githubusercontent.com/2256755/81249856-111c1000-8ff6-11ea-9f0f-b98ab73e94b5.png)
![download1](https://user-images.githubusercontent.com/2256755/81249865-15e0c400-8ff6-11ea-8de6-234b18b8d7fa.png)

**Host (please complete the following information):**
 - Windows 10

**Additional context**

**Comment by smashah** [comment]
You have to subscribe to the location after they have shared it with you. It will return false if you call `onLiveLocation` before they've shared it with you.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.13](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.12...1.9.13) (2020-05-07)

- Release 1.9.13 [`64929cd`](https://github.com/open-wa/wa-automate-nodejs/commit/64929cd053730cea7f7dee83f958e7ccd07c46ec)
- feature: added forceUpdateLiveLocation #409 [`98428a5`](https://github.com/open-wa/wa-automate-nodejs/commit/98428a5c84b8a242d215f63b73a7715ad31c8d13)

**Comment by smashah** [comment]
@ctoveloz 

You can now force an location update event.

```javascript
start( client ) {
    client.onMessage( async message => {
        if ( message.type === "location" ) {
          //this is how you determine if someone started a live location
          if ( message.shareDuration ) {
            console.log( 'This user has started sharing their live location', message.author || message.from )
            client.onLiveLocation( message.from, location => console.log( location ) )

            //next line is new. It will trigger the above event. You can call the following line every 30ish seconds ideally. Maybe put it in a loop.
            const forcedLiveLocation = await client.forceUpdateLiveLocation( message.from )
            console.log( forcedLiveLocation[ 0 ] );
          }
        }
      }
    }
```

Here is the documentation:
https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#forceupdatelivelocation

Thanks

**Comment by ctoveloz** [comment]
Hi @smashah 
Thanks this work,

I have another question...
I created a loop to pull information `forceUpdateLiveLocation`  each 10 seconds, the intention is to update this information but they are always the same as the first time it is sent.

```javascript

if ( message.type === "location" ) {
            //this is how you determine if someone started a live location

              if ( message.shareDuration ) {

                  client.onLiveLocation( message.from, location => console.log( location ) )
                  
                  const forcedLiveLocation = await client.forceUpdateLiveLocation( message.from );         

                  const motoristaNumber = forcedLiveLocation[0].id.replace('@c.us','');
                  const motoristaLatitude = forcedLiveLocation[0].lat;
                  const motoristaLongitude = forcedLiveLocation[0].lng;
                  const motoristaData = forcedLiveLocation[0].lastUpdated;

                  client.sendTextWithMentions(message.from, `@${motoristaNumber} your location is being monitored 🔍`);

                  // Loop to update informations
                  setInterval(function(){

                    console.log('Latitude: ' + motoristaLatitude, 
                                'Longitude: ' + motoristaLongitude, 
                                'Last Update: ' + motoristaData); 
                  
                  }, 10000);

                  

              }
      }
```
![Sem título](https://user-images.githubusercontent.com/2256755/81352065-01570700-909c-11ea-970d-4038d5dc2608.jpg)

**Comment by smashah** [comment]
If you read the docs you can see that it should be used every 30 seconds at least. Also, use a fake GPA app to test on the monitored phone.

**Comment by ctoveloz** [comment]
> @ctoveloz
> 
> You can now force an location update event.
> 
> ```js
> start( client ) {
>     client.onMessage( async message => {
>         if ( message.type === "location" ) {
>           //this is how you determine if someone started a live location
>           if ( message.shareDuration ) {
>             console.log( 'This user has started sharing their live location', message.author || message.from )
>             client.onLiveLocation( message.from, location => console.log( location ) )
> 
>             //next line is new. It will trigger the above event. You can call the following line every 30ish seconds ideally. Maybe put it in a loop.
>             const forcedLiveLocation = await client.forceUpdateLiveLocation( message.from )
>             console.log( forcedLiveLocation[ 0 ] );
>           }
>         }
>       }
>     }
> ```
> 
> Here is the documentation:
> https://open-wa.github.io/wa-automate-nodejs/classes/whatsapp.html#forceupdatelivelocation
> 
> Thanks

Hi @smashah 

I tried do 'onLiveLocation' without the trigger sending a message, something directly when the bot start, he takes all live locations in the chat.
something like this, but he is trying to pull the message scoope.

```
start( client ) {
    client.onMessage( async message => {

          client.onLiveLocation( message.from, location => console.log( location ) )

            const forcedLiveLocation = await client.forceUpdateLiveLocation( message.from )

            var jsonData = JSON.parse(forcedLiveLocation);

            console.log(jsonData);

      }
    }
```

you now if is possible call onlivelocation after bot start ? Thanks
