### ISSUE TITLE
[Question] There is any way to get client by session ID?

### ISSUE THREAD

**Issue by willianmaria** [open-wa/wa-automate-nodejs#412]
I would like to know if there is any way to get the client by session ID.
I have an express APP and methods to create new sessions, kill sessions and send message to especific sessions.

**Comment by devalexanderdaza** [comment]
I do it by storing the client object in an array whose identifier is the sessionId and with it, I access the methods of the object and everything works without problem

**Comment by willianmaria** [comment]
I'm saving in a global object variable each session I have.
But dont know if is the bettert way.

**Comment by smashah** [comment]
Running multiple sessions per process is largely a convenience tool for development with a few open sessions. If you're orchestrating more sessions I suggest running a cluster of sessions then orchestrating them through a single API process

**Comment by willianmaria** [comment]
Hello @smashah . Do you have an example of this? I'm using Kubernetes with one single container with multiple sessions. But I'll need multiple sessions, one for each my clients. How can I orchestrate with multiple containers?

**Comment by smashah** [comment]
@willianmaria I haven't done it myself. Maybe this can help https://cloud.google.com/kubernetes-engine/docs/concepts/multitenancy-overview

**Comment by willianmaria** [comment]
Thanks! I'll check this.
