### ISSUE TITLE
Is message sender on mobile or web

### ISSUE THREAD

**Issue by tinyCoder32** [open-wa/wa-automate-nodejs#420]
Hi, is it possible somehow to get any information about the environment of the message sender?

**Comment by smashah** [comment]
Nope. You can only check if the message sent was from within your own Whatsapp web session, not whether or not it was received from web (or mobile) (i.e you can only check if your own messages were sent in Whatsapp web). You can check this with `message.local` if true it means your message was sent from Whatsapp web.
