### ISSUE TITLE
Check license not response

### ISSUE THREAD

**Issue by devalexanderdaza** [open-wa/wa-automate-nodejs#421]
Hi! After update to last version, in console show "Checking license" for several minutes.

After time passes, a 503 response appears on the console:
``Error: Request failed with status code 503``

**Comment by devalexanderdaza** [comment]
Upgrade. The system is already validating the license, but when sending a message to an unsaved number, it does not send the message.

Should I create a new thread for this case or can you help me here?

**Comment by smashah** [comment]
@devalexanderdaza no need. I'm working on it. What's the response when trying to send the message?

**Comment by devalexanderdaza** [comment]
It does not show any errors, nor does it show shipping information. When it sends messages correctly it returns the id of the message but not in this case.

**Comment by smashah** [comment]
@devalexanderdaza will need more information. Does it return false? Is it a specific number etc?

**Comment by devalexanderdaza** [comment]
It only returns true and happens with any number that has not been added to my contact list and that I have never had a conversation on WhatsApp. With the numbers that I do not have saved but that I previously had a conversation if you send the message without any problem

**Comment by smashah** [comment]
@devalexanderdaza ok please fill an issue template. Thanks

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
