### ISSUE TITLE
Wa-Automate not send messages to unknown numbers

### ISSUE THREAD

**Issue by devalexanderdaza** [open-wa/wa-automate-nodejs#423]
Reference for [https://github.com/open-wa/wa-automate-nodejs/issues/421](#421 )

**Describe the bug**
When sending a message to a number not saved in the contact list and without previous conversations, you do not send the message

**Steps to Reproduce**
1. Define the license serial number when creating the connection between Wa-Automate with WhatsApp.
2. Start the connection and request the QR code
3. Connect your whatsapp with Wa-Automate
4. Send a message to a number that you do not have stored in your contact list and that you did not have any previous conversations
5. The message never reaches the recipient

**create() code**
This is the code you use to create the client. e.g
```javascript
openWA.create("/" + F.config['instance'], {
                licenseKey: XXXXXXXXXXXXXXXXXXX
                headless: true,
                autoRefresh: true,
                qrRefreshS: 15,
                killTimer: 6000
            }).then(function (client) {});
```

**Expected behavior**
I hope that the message is received by the recipient even if I do not have it in my contacts and I have never had a previous conversation with him

**DEBUG INFO**
```
Debug Info {
"WA_VERSION": "2.2019.6",
	"PAGE_UA": "WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
	"WA_AUTOMATE_VERSION": "1.9.18",
	"BROWSER_VERSION": "HeadlessChrome/81.0.4044.0"
}
```
**Host (please complete the following information):**
 - OS: OSX Catalina and Ubuntu 18.04

**Additional context**
At the time of sending the messages to the contacts or to the numbers with which I have previously had a conversation on WhatsApp, the message arrives without problem and the response of the sending is the message id.

When sending the same message to a non-contact number and with whom a previous conversation has not been held, the message never arrives and the sent message id is not displayed either.

**Comment by smashah** [comment]
@devalexanderdaza can you hop into the discord and DM me please

**Comment by smashah** [comment]
@devalexanderdaza I'm going to close this for now. Please let me know if this is still happening. Thanks

**Comment by edu1525** [comment]
I'm having the same problem, how to solve it?

**Comment by smashah** [comment]
@edu1525 

https://open-wa.github.io/wa-automate-nodejs/pages/The%20Client/licensed-features.html#sending-messages-to-non-contact-numbers
