### ISSUE TITLE
BROKEN METHODS:  2.2019.8

### ISSUE THREAD

**Issue by sgmaxi** [open-wa/wa-automate-nodejs#428]
Please make a new issue in:

 https://github.com/open-wa/wa-automate-nodejs/issues

with the following title:

BROKEN METHODS:  2.2019.8

Add this to the body of the issue:

 [ 'Store.bp', 'Store.MsgKey' ]

!!!!!BROKEN METHODS DETECTED!!!!

**Comment by smashah** [comment]
This happens sometimes whena new version comes out. I checked and everything seems to be ok. Please update to the latest version.
