### ISSUE TITLE
Set Profile Pic?

### ISSUE THREAD

**Issue by dimar-hanung** [open-wa/wa-automate-nodejs#429]
Is there a way to change profile photo?
i found this command ``` Store.ProfilePicThumb ``` but I can only use get(id), idk how to set profile image.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.30](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.29...1.9.30) (2020-05-18)

- build(deps-dev): bump typedoc from 0.17.6 to 0.17.7 [`#445`](https://github.com/open-wa/wa-automate-nodejs/pull/445)
- build(deps): bump sharp from 0.25.2 to 0.25.3 [`#441`](https://github.com/open-wa/wa-automate-nodejs/pull/441)
- build(deps-dev): bump @types/shelljs from 0.8.7 to 0.8.8 [`#442`](https://github.com/open-wa/wa-automate-nodejs/pull/442)
- build(deps-dev): bump tsc-watch from 4.2.5 to 4.2.6 [`#443`](https://github.com/open-wa/wa-automate-nodejs/pull/443)
- build(deps-dev): bump release-it from 13.6.0 to 13.6.1 [`#444`](https://github.com/open-wa/wa-automate-nodejs/pull/444)
- build(deps-dev): bump marked from 1.0.0 to 1.1.0 [`#446`](https://github.com/open-wa/wa-automate-nodejs/pull/446)
- Release 1.9.30 [`acf4d55`](https://github.com/open-wa/wa-automate-nodejs/commit/acf4d55704f54085f2b5653000cd175f8d7af706)
- Features (insiders): onRemovedFromGroup & setProfilePic #440 #429 [`c2e77e5`](https://github.com/open-wa/wa-automate-nodejs/commit/c2e77e565581a3e054b14985fae9f4d07ae713a7)
- updated release image [`223d2f2`](https://github.com/open-wa/wa-automate-nodejs/commit/223d2f2c4274b8207ab88f50dbd43603adbe82a1)

**Comment by smashah** [comment]
@dimar-hanung please dm me on discord so I can give you a license key for this feature. thanks

https://open-wa.github.io/wa-automate-nodejs/classes/client.html#setprofilepic
