### ISSUE TITLE
[Feature Request] Download the picture as base64

### ISSUE THREAD

**Issue by ozkcs** [open-wa/wa-automate-nodejs#434]
Hey, can u make an feature to download the picture image as base64 please

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.27](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.26...1.9.27) (2020-05-17)

- Release 1.9.27 [`b96058a`](https://github.com/open-wa/wa-automate-nodejs/commit/b96058ad076eb97c61c0eb3eb90fbbe9ca2aadc2)
- chore: refactored main class to `Client` [`e30fc0e`](https://github.com/open-wa/wa-automate-nodejs/commit/e30fc0e5ee6e6cc527a80d3a57a28d6b359cae7d)
- feature: Implemented convenient method to download profile pics as base64 #434 [`6eb0c2b`](https://github.com/open-wa/wa-automate-nodejs/commit/6eb0c2bcb99ddcd7d5b38412d85894d88161943e)
- updated release-image [`0f1b2c8`](https://github.com/open-wa/wa-automate-nodejs/commit/0f1b2c85bfbe6421e235265e27e84109b8ec22b6)

**Comment by smashah** [comment]
@ozkcs 

This was a tough one. The reason it never worked is that before the image is downloaded, it determines if you have any existing valid WA cookies. So the best way around this was to implement axios within the browser and download it through the running session.
```javascript
      const filename = `profilepic_${message.from}.jpeg`;
      const data = await client.downloadProfilePicFromMessage(message);
      const dataUri = `data:image/jpeg;base64,${data}`;

      fs.writeFile(filename, data, 'base64', function(err) {
        if (err) {
          return console.log(err);
        }
        console.log('The file was saved!');
      });
```

Tested and closing. Thanks.
