### ISSUE TITLE
Feature: Expose a basic express middleware from Client

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#466]
Implementing this library with express shouldn't be so complicated and verbose. A simple middleware should be able to manage the vast majority of functionality from the client. This feature needs to be implemented with minimal increased library footprint.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.37](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.36...1.9.37) (2020-05-22)

- Release 1.9.37 [`f6e11c8`](https://github.com/open-wa/wa-automate-nodejs/commit/f6e11c8567d65901814e865ce4b10126f5c63594)
- added docs for middleware #466 [`e61c8c2`](https://github.com/open-wa/wa-automate-nodejs/commit/e61c8c2788f2c7d2a69b96e2ae8b2049544095b8)
- feature: client exposes basic express middleware #466 [`880091e`](https://github.com/open-wa/wa-automate-nodejs/commit/880091e9f3631b7d50fd6204abcd166b51ad7c21)
- added express middleware example demo #466 [`63cc3bc`](https://github.com/open-wa/wa-automate-nodejs/commit/63cc3bccf5ee9a7a9c0c9cd22b41bceb041069f7)

**Comment by smashah** [comment]
How to use the middleware:

```javascript

import { create } from '@open-wa/wa-automate';
const express = require('express')
const app = express()
app.use(express.json())
const PORT = 8082;

function start(client){
  app.use(client.middleware);
  app.listen(PORT, function () {
    console.log(`\n• Listening on port ${PORT}!`);
  });
  ...
}


create({
  sessionId:'session1'
}).then(start)

```

All requests need to be `POST` requests. You use the API the same way you would with `client`. The method can be the path or the method param in the post body. The arguments for the method should be properly ordered in the args array in the JSON post body.

Example:

```javascript
  await client.sendText('4477777777777@c.us','test')
  //returns "true_4477777777777@c.us_3EB0645E623D91006252"
```
as a request with a path:

```javascript
const axios = require('axios').default;
axios.post('localhost:8082/sendText', {
    args: [
       "4477777777777@c.us",    
       "test"    
        ]
  })
```

or as a request without a path:

```javascript
const axios = require('axios').default;
axios.post('localhost:8082', {
    method:'sendText',
    args: [
       "4477777777777@c.us",    
       "test"   
        ]
})
```

**Comment by teezzan** [comment]
Thanks for your incredible work and superb documentation. I got this to work very easily with your help.
I will continue to explore it. 


Thanks

**Comment by teezzan** [comment]
Hello, 
I cant seem to send an image. I am wsing the latest version of the library and was able to get most things to work except sending of files. 
it usually returns `b64Data.split is not a function` among other errors. My simple axios request is as follows
```javascript

const file = 'iVBORw...cx';
const axios = require('axios').default;
axios.post('http://localhost:8082/sendFile', {
    args: [
        "2348168494355@c.us",
        [file],
        'ing.png',
        'ntesho!'
    ]
}).then((res) => console.log(res.data))
    .catch(err => console.log(err))
```
Thanks once again for your incredible work.

**Comment by roelandp** [comment]
afaik you need to send the base64 data directly. Here is how i send it (not with the REST api, mind you)

```
client.sendImage(
          to,
          `data:${mime.lookup(FILE)};base64,${fs.readFileSync(FILE).toString('base64')}`,
           FILE.substring(FILE.lastIndexOf('/') + 1).trim(),
          caption
        );

```
Here i am using the libs `mime` and `fs` in node. 
mime to lookup the mimetype and then fs to open and read the FILE. 

Note that FILE is a filepath

**Comment by teezzan** [comment]
Oh. Thanks. I will try that in a minute
