### ISSUE TITLE
Deprecated API usage: PDFDocumentLoadingTask.then method, use the `promise` getter instead.

### ISSUE THREAD

**Issue by sandro-salles** [open-wa/wa-automate-nodejs#479]
**Describe the bug**

When sending a pdf file, although the file is correctly sent, logConsoleErrors shows the messages below:

> ConsoleMessage {
>   _type: 'log',
>   _text: 'Deprecated API usage: PDFDocumentLoadingTask.then method, use the `promise` getter instead.',
>   _args: [
>     JSHandle {
>       _disposed: false,
>       _context: [ExecutionContext],
>       _client: [CDPSession],
>       _remoteObject: [Object]
>     }
>   ],
>   _location: {
>     url: 'https://web.whatsapp.com/vendors~pdf.f9726adaf222bcf2d628.js',
>     lineNumber: 23,
>     columnNumber: 3994
>   }
> }
> ConsoleMessage {
>   _type: 'log',
>   _text: 'Deprecated API usage: getViewport is called with obsolete arguments.',
>   _args: [
>     JSHandle {
>       _disposed: false,
>       _context: [ExecutionContext],
>       _client: [CDPSession],
>       _remoteObject: [Object]
>     }
>   ],
>   _location: {
>     url: 'https://web.whatsapp.com/vendors~pdf.f9726adaf222bcf2d628.js',
>     lineNumber: 23,
>     columnNumber: 3994
>   }
> }
> ConsoleMessage {
>   _type: 'log',
>   _text: 'Deprecated API usage: RenderTask.then method, use the `promise` getter instead.',
>   _args: [
>     JSHandle {
>       _disposed: false,
>       _context: [ExecutionContext],
>       _client: [CDPSession],
>       _remoteObject: [Object]
>     }
>   ],
>   _location: {
>     url: 'https://web.whatsapp.com/vendors~pdf.f9726adaf222bcf2d628.js',
>     lineNumber: 23,
>     columnNumber: 3994
>   }
> }

**Steps to Reproduce**
1. Send a pdf file using sendFileFromUrl

**create() code**
This is the code you use to create the client. e.g
```javascript
create({
        sessionId: `sessions/${bot_id}`,
        chromiumArgs,
        sessionData,
        headless: true,
        autoRefresh: false,
        blockCrashLogs: true,
        cacheEnabled: true,
        throwErrorOnTosBlock: true,
        logConsole: true,
        logConsoleErrors: true,
        executablePath: config.CHROME_BIN ? config.CHROME_BIN : null,
        useChrome: false,
        qrLogSkip: true,
        bypassCSP: true,
        disableSpins: true,
        restartOnCrash: (client) => {
          on_initialize(bot, client)
        },
        // qrTimeout: config.WA_QR_TIMEOUT,
        authTimeout: config.AUTH_TIMEOUT,
        proxyServerCredentials
      })
      .then((client) => {
        on_initialize(bot, client)
      })
```

**Expected behavior**
The file to be sent without errors/warnings

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2021.3,
  PAGE_UA: WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36,
  WA_AUTOMATE_VERSION: 1.9.35,
  BROWSER_VERSION: HeadlessChrome/81.0.4044.138
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Docker image (node:12.13.0)

**Additional context**

As I told, it's working, and i didn't test using latest version... just wanted to point out so maybe it's something to keep an eye on.

Regards

**Comment by smashah** [comment]
thanks @sandro-salles i'll look into this

**Comment by smashah** [comment]
@sandro-salles you can ignore this. It happens when uploading a pdf manually also.
