### ISSUE TITLE
Get All New Messages

### ISSUE THREAD

**Issue by jesusvalverde** [open-wa/wa-automate-nodejs#488]
Describe the bug A clear and concise description of what the bug is.

 I was looking for a way to read the new messages on the host phone after scan the qr, all those received and not marked as seen (blue mark)

I do have try 
  const chatsgetAllNewMessages = await client.getAllNewMessages();
  console.log("TCL: chatsgetAllNewMessages ->", chatsgetAllNewMessages.length);
  console.log(chatsgetAllNewMessages);

But I do get an empty array 

TCL: chatsgetAllNewMessages -> 1
[ [] ]

Steps to Reproduce Steps to reproduce the behavior:

    Go to '...'
    Click on '....'
    Scroll down to '....'
    See error

create() code This is the code you use to create the client. e.g

	const idAcount = process.argv[2];
	wa.create(idAcount,{cacheEnabled:false, qrRefreshS:20}).then(client => start(client));

Expected behavior A clear and concise description of what you expected to happen.

	Get an array of new messages

DEBUG INFO This is the info printed to the console when you start your app. It should look like this

}
 WA_VERSION      │                                                                  '2.2021.4'                                                                   │
│       PAGE_UA       │ 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '1.9.49'                                                                    │
│   BROWSER_VERSION   │                                                         'HeadlessChrome/83.0.4103.0'   

Screenshots If applicable, add screenshots to help explain your problem. Use headless: false to get screenshots

Host (please complete the following information):

Additional context Add any other context about the problem here.

**Comment by smashah** [comment]
f94681ef079b83c4882fc9c850b6fff19bf3642c

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
There has been too much confusion around `getAllNewMessages` (any message where isNew==true) and `getAllUnreadMessages` (ack==-1) etc.

The above commit represents a breaking change. `getAllUnreadMessages` will now represent the messages that correspond to the little unread dots next to the chat. This should clear it up once and for all.

From now on use `getAllUnreadMessages`.

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.51](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.50...1.9.51) (2020-05-27)

- Release 1.9.51 [`cc08822`](https://github.com/open-wa/wa-automate-nodejs/commit/cc08822cc60052eaaeffb3e69ab696bb50dc2dbb)
- fix: updated `getAllUnreadMessages`, no longer ack==-1 [`f94681e`](https://github.com/open-wa/wa-automate-nodejs/commit/f94681ef079b83c4882fc9c850b6fff19bf3642c)
