### ISSUE TITLE
Spy isOnline of non-contact

### ISSUE THREAD

**Issue by NeoArcanjo** [open-wa/wa-automate-nodejs#497]
Is possible? I want listen a list of leads and map yours time of use in app

**Comment by jesusvalverde** [comment]
No.. getLastSeen will not work if:

    They have set it so you cannot see their last seen via privacy settings.
    You do not have an existing chat with the contact.

**Comment by smashah** [comment]
Don't be a creep. This library is supposed to be used for making bots. Not for spying on people. Thanks @jesusvalverde for the answer
