### ISSUE TITLE
browser.setMaxListeners is not a function

### ISSUE THREAD

**Issue by mrbarnk** [open-wa/wa-automate-nodejs#505]
**Describe the bug**

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```
await sulla.create(this.sessionName, {
            // licenseKey: "...",
            autoRefresh: true,
            killTimer: 60
        }).catch(e => console.log(e.message))
```

**Expected behavior**
It hangs after printing, "Initializing wa", and display this error..

browser.setMaxListeners is not a function

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
#No debug info. Check screenshot, but I am on the updated  server.
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/37006356/83290751-1298bc80-a1df-11ea-8fea-42ee20d5cb51.png)

**Host (please complete the following information):**
 - OS: Ubuntu 20

**Additional context**

**Comment by sandro-salles** [comment]
I can confirm it's happening as well.

**Comment by jesusvalverde** [comment]
Same issue here diferent whay to show error

(node:2097) UnhandledPromiseRejectionWarning: TypeError: browser.setMaxListeners is not a function
    at StealthPlugin.onBrowser (/home/ubuntu/boot/node_modules/puppeteer-extra-plugin-stealth/index.js:155:13)
    at StealthPlugin._bindBrowserEvents (/home/ubuntu/boot/node_modules/puppeteer-extra-plugin/dist/index.cjs.js:479:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PuppeteerExtra.callPlugins (/home/ubuntu/boot/node_modules/puppeteer-extra/dist/index.cjs.js:376:13)
    at async PuppeteerExtra.launch (/home/ubuntu/boot/node_modules/puppeteer-extra/dist/index.cjs.js:131:9)
(node:2097) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2097) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sandro-salles** [comment]
For further investigation:
https://github.com/berstend/puppeteer-extra/issues/211

**Comment by jesusvalverde** [comment]
npm i puppeteer@3.1.0 

Just go down to one older version and all back

**Comment by mrbarnk** [comment]
ok, thanks so much.

It's fixed.

**Comment by feliperaul** [comment]
@mrbarnk Can you please reopen the issue? I think this should be fixed in the lib, even if it's to downgrade the Puppeteer dependency.

**Comment by smashah** [comment]
@feliperaul this issue is fixed in the latest version and the workaround is no longer required.

**Comment by feliperaul** [comment]
Hi @smashah I just tried on `1.9.60` and it still happens:

```
(node:94091) UnhandledPromiseRejectionWarning: TypeError: browser.setMaxListeners is not a function
    at StealthPlugin.onBrowser (node-whatsapp/node_modules/puppeteer-extra-plugin-stealth/index.js:155:13)
    at StealthPlugin._bindBrowserEvents (node-whatsapp/node_modules/puppeteer-extra-plugin/dist/index.cjs.js:479:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PuppeteerExtra.callPlugins (node-whatsapp/node_modules/puppeteer-extra/dist/index.cjs.js:376:13)
    at async PuppeteerExtra.launch (node-whatsapp/node_modules/puppeteer-extra/dist/index.cjs.js:131:9)
```

Maybe it's due to the `useStealth: true` ? Do you want me to open a new issue?

**Comment by smashah** [comment]
@feliperaul useStealth is off by default as it is mentioned in the docs. Clear your node modules and remove `useStealth` from your configuration or set it to false. It's pretty much redundant. And as you can see this problem is due to puppeteer stealth. So if you want to make a new issue make it there.
