### ISSUE TITLE
Can't getAllChatsMessage using Node JS

### ISSUE THREAD

**Issue by nuzulr24** [open-wa/wa-automate-nodejs#506]
I tried to call a Client-> getAllChatsMessage (false) function with await into the imperial async below (which I attached the image to) but an error occurred that await could not be called inside async. Please help
![carbon (1)](https://user-images.githubusercontent.com/40730150/83343469-e6875380-a324-11ea-9330-4a18427f59b3.png)

**Comment by nuzulr24** [comment]
![carbon (1)](https://user-images.githubusercontent.com/40730150/83343471-f30bac00-a324-11ea-8e5b-48b98fdf7ba3.png)

**Comment by YogaSakti** [comment]
there is no getAllChatsMessage function in the client

![image](https://user-images.githubusercontent.com/24309806/83354258-a30f0280-a381-11ea-8d6c-fb24088c7124.png)

**Comment by smashah** [comment]
Please read the docs.

https://open-wa.github.io/wa-automate-nodejs/classes/client.html

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
