### ISSUE TITLE
Request failed with status code 404 after loading all earlier messages

### ISSUE THREAD

**Issue by kaykyr** [open-wa/wa-automate-nodejs#512]
Code:

`async getChat(socket, data) {
		const { session, chat, includeMe, includeNotifications } = data

		if (await SessionController.checkSession(socket, data)) {
			const client = await this.getClient(socket, { data })

			if (client) {
				var conversation = await client.getAllMessagesInChat(
					chat,
					includeMe,
					includeNotifications
				)

				const conversationPromises = conversation.map(
					async (message, index) => {
						if (message.mimetype) {
							let mediaData = await decryptMedia(message)
							let imageBase64 = `data:${
								message.mimetype
							};base64,${mediaData.toString('base64')}`

							return {
								...conversation[index],
								decryptedMedia: imageBase64,
							}
						}

						return conversation[index]
					}
				)

				const conversationDecrypted = await Promise.all(
					conversationPromises
				)

				socket.emit('getChat', {
					session: session,
					status: 'ok',
					conversation: conversationDecrypted,
				})
			}
		}
	}

	async getEarlier(socket, data) {
		const { session, chat } = data

		if (await SessionController.checkSession(socket, data)) {
			const client = await this.getClient(socket, { data })

			if (client) {
				const conversation = await client.loadEarlierMessages(chat)
				socket.emit('getEarlier', {
					session: session,
					status: 'ok',
					conversation,
				})
			}
		}
	}`

To reproduce this error:
`
(node:59214) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/Users/kaykyramos/Desktop/wpp/backend/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/kaykyramos/Desktop/wpp/backend/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/kaykyramos/Desktop/wpp/backend/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:59214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:59214) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Steps:
1 - Call getEarlier until load all messages
2 - Call getChat

**Comment by kaykyr** [comment]
I think the issue is related to media decrypt, when I load all media and decrypt I got this error. Isn't possible to get only last messages using getAllMessagesInChat() or maybe a pagination? Because after loading all earlierMessages the function getAllMessagesInChat will return all loaded messages and this can spend too much time and cause this error in case of decrypting all media.

**Comment by smashah** [comment]
The media doesn't exist forever you know. If you're getting all messages AND decrypting then the old media urls will 404.

**Comment by kaykyr** [comment]
> The media doesn't exist forever you know. If you're getting all messages AND decrypting then the old media urls will 404.

Alright! How about the possibility to create a pagination on getAllMessagesInChat?

**Comment by smashah** [comment]
Pagination requires control of the data which this library doesn't have so that will not be implemented. LoadEarlierMessages returns 50 older messages use that instead.


https://open-wa.github.io/wa-automate-nodejs/classes/client.html#loadearliermessages
