### ISSUE TITLE
Error in new Version Whatsapp Web 2.2023.2

### ISSUE THREAD

**Issue by alpires** [open-wa/wa-automate-nodejs#514]
Hi Guys,
wapi.js is not working on version 2.2023.2 of whatsapp web.
Some idea?
Thanks

**Comment by jesusvalverde** [comment]
Seem to have problem over '2.2023.2"  and '1.9.61'   and halt  over  "Authenticate to continue"..  I'll test more tomorow and try to make a "template request"

**Comment by arwanfiles** [comment]
I have same problem here

**Comment by arturromaorocha** [comment]
I have same problem here

**Comment by camvishalpathak** [comment]
I have same problem here

**Comment by willsilvano** [comment]
Same here.

**Comment by kaiqmo** [comment]
same

**Comment by UnKnoWn-Consortium** [comment]
The 2.2023.2 update has removed the class `app` the authenticated check depends on, thus preventing the client to start.

**Comment by smashah** [comment]
pushing new version very soon

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by jesusvalverde** [comment]
Small test and NOT working 
│     WA_VERSION      │       '2.2023.2'

**Comment by smashah** [comment]
The release bot had a bit of a mess up:

https://github.com/open-wa/wa-automate-nodejs/blob/master/CHANGELOG.md#1962---2020-06-04

this is fixed in 1.9.62

**Comment by jesusvalverde** [comment]
Solved !!!!

**Comment by smashah** [comment]
@jesusvalverde @UnKnoWn-Consortium @kaiqmo @willsilvano @camvishalpathak @arturromaorocha @arwanfiles @alpires please try 1.9.62+ and let me know if worked for you. Thanks

**Comment by alpires** [comment]
Yes, Solved, thanks !!!

**Comment by arwanfiles** [comment]
It works now.
Thanks @smashah

**Comment by willsilvano** [comment]
Yep, it works now here.
Thanks!

**Comment by stefano71** [comment]
Now wapi.js works me it is no longer possible to send a message to a new contact .
