### ISSUE TITLE
Thanks! Subscribed as Donor on Gumroad.

### ISSUE THREAD

**Issue by roelandp** [open-wa/wa-automate-nodejs#520]
Thanks a lot for the active development on this project. I love your automation in notifying on broken API calls and such. 

As a thank you i have subscribed as a donor on Gumroad.

@smashah Occasionally I would like to submit fixes and am trying to wrap my head around the inner workings. Could you enlighten on how you reverse engineer on a continuous basis the WA for Web code? If I can replicate your dev environment or dev tools it would be great to learn from you.

**Comment by smashah** [comment]
Thanks so much @roelandp !!

I might write a book about how to do this stuff but it's mainly a lot of `cmd+f`, reading the code and trial and error.

As for my dev environment, VS Code and a lot of chrome dev tools. I use Glitch to make some of these github bots and the license server.

I kinda fell into doing this by being frustrated with the slow releases of sulla and have learnt a lot along the way. 

Thanks again!
