### ISSUE TITLE
Loading QR loop even when sessionData set and valid

### ISSUE THREAD

**Issue by sandro-salles** [open-wa/wa-automate-nodejs#526]
**Describe the bug**
Even when setting a valida sessionData json, create function enters a Loading QR Loop. Although it successfully connects, maybe that loop should not be started. If session is not valid, maybe should throw a specific error, but not try to generate a QR.

**Steps to Reproduce**
1. call **create** setting a valid sessionData
2. See loop in logs

**create() code**
This is the code you use to create the client. e.g
```javascript
create({
        sessionId: 'mySessionId',
        sessionDataPath: 'sessions',
        chromiumArgs,
        sessionData, // this is a valid sessionData
        headless: true,
        autoRefresh: false,
        blockCrashLogs: true,
        cacheEnabled: true,
        throwErrorOnTosBlock: true,
        logConsole: false,
        logConsoleErrors: true,
        useChrome: true,
        qrLogSkip: true,
        bypassCSP: true,
        disableSpins: true,
        useStealth: true,
        restartOnCrash: (client) => {
             ....
        },
        authTimeout: config.AUTH_TIMEOUT,
      })
      .then((client) => {
            ...
      })
```

**Expected behavior**
Validate sessionData and connect (if valid) or throw error (if not valid)

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2023.2,
  PAGE_UA: 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36'
  WA_AUTOMATE_VERSION: 1.9.63,
  BROWSER_VERSION: 'HeadlessChrome/81.0.4044.138'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Docker container (node:12.18.0-buster-slim)

**Additional context**
Below the output of the loop (before success connection):

```
- Passed Integrity Test
- Injecting api
- Loading QR
- Loading QR
- Passed Integrity Test
- WAPI injected
- Loading QR
- Loading QR
- Passed Integrity Test
- Authenticating
- Loading QR
- Loading QR
- Passed Integrity Test
- Authenticated
- Loading QR
- Loading QR
- Passed Integrity Test
- Reinjecting api
- Loading QR
- Loading QR
- Passed Integrity Test
- WAPI Reinjected
- Loading QR
- Loading QR
- Passed Integrity Test
- Checking if session is valid
- Loading QR
- Loading QR
- Passed Integrity Test
- Client is ready
- Loading QR
- Loading QR
```

Regards!

**Comment by smashah** [comment]
@sandro-salles this new update had really screwed up a lot of things and I really don't have the time to debug all of those config properties. Can you try the demo. And isolate which of these things are not working then report back so I can quickly fix it. Thanks

**Comment by sandro-salles** [comment]
@smashah, I'll try to debug locally here to isolate and let you know! But i don't this is related to the new update.. i saw that on previous versions as well, just didn't have the time to stop and report :/

I'll let you know as soon as i have something!

**Comment by smashah** [comment]
@sandro-salles is this still happening using the latest version?

**Comment by sandro-salles** [comment]
@smashah still occurring. I think the line:
https://github.com/open-wa/wa-automate-nodejs/blob/993c7a88c1fdcae704ef5dc3b3235671df3feb6e/src/controllers/initializer.ts#L120

Should be changed to something like:

`
else if (!config.sessionData) {
... start the QR Code routines... 
}
`

This way, if a sessionData was set i think it does not make any sense to generate a QR Code.. the session is either valid (and everything should work fine) or invalid (and the validation would fail) ... what you think?

Regards

**Comment by smashah** [comment]
So this is happening when you have an expired sessionData?

**Comment by smashah** [comment]
Also, please set `useStealth: false` or just remove it.

**Comment by smashah** [comment]
I just tested an invalid sessionData and am still unable to recreate this issue. @sandro-salles please update to latest version and try again.

**Comment by sandro-salles** [comment]
@smashah it's happening even when i have a valid sessionData. What i'm checking here is if those logs are really coming from the same client, since i'm connecting multiple clients (sessions).

Maybe it would be a nice improvement to prefix all logs with the sessionId in the future, so on a mutiple session setup those investigations would be much more easy to troubleshoot.

Something like:
spinner.start(`Session ${config.sessionId}: Initializing WA`);
spinner.start(`Session ${config.sessionId}: Injecting api`);

And so on... just an idea!

I'll mark this as resolved for now and if anything i'll let you know.

Thanks man!
