### ISSUE TITLE
Unable to send text and image messages with wapi.js to unknown numbers

### ISSUE THREAD

**Issue by stefano71** [open-wa/wa-automate-nodejs#528]
**Describe the bug**

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
It's not a bug.

https://github.com/open-wa/wa-automate-nodejs/blob/master/README.md

**Comment by stefano71** [comment]
I purchased your subscription but I can't find any downloads with the new wapi.js features

**Comment by smashah** [comment]
There are no downloads. Each key is used for one number. You can use multiple keys per number. The code gets downloaded to your instance when u add the license key config variable in the create method.

**Comment by stefano71** [comment]
how do I only send the text message and the file with WAPI javascript?

**Comment by smashah** [comment]
This is not possible anymore due to the amount of spam being sent by users of other projects. It has been patched by WhatsApp

**Comment by stefano71** [comment]
This works well
https://github.com/felippeefreire/WebWhatsapp-Wrapper/blob/master/webwhatsapi/js/wapi.js
