### ISSUE TITLE
QR generated successfully , but scan with app  , no response 

### ISSUE THREAD

**Issue by jj449** [open-wa/wa-automate-nodejs#529]
**Describe the bug**
QR generated successfully , but scan with app  , no response 

**Steps to Reproduce**
Steps to reproduce the behavior:  run js
1.  node wa.js 

node wa.js
         ██████╗  ██████╗ ██████╗ ███████╗███╗   ██╗      ██╗    ██╗ █████╗         
        ██╔═══██╗██╔═══██╗██╔══██╗██╔════╝████╗  ██║      ██║    ██║██╔══██╗        
        ██║██╗██║██║   ██║██████╔╝█████╗  ██╔██╗ ██║█████╗██║ █╗ ██║███████║        
        ██║██║██║██║   ██║██╔═══╝ ██╔══╝  ██║╚██╗██║╚════╝██║███╗██║██╔══██║        
        ╚█║████╔╝╚██████╔╝██║     ███████╗██║ ╚████║      ╚███╔███╔╝██║  ██║        
         ╚╝╚═══╝  ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝       ╚══╝╚══╝ ╚═╝  ╚═╝        
                                                                                    
        ██╗    ██╗██╗  ██╗ █████╗ ████████╗███████╗ █████╗ ██████╗ ██████╗          
        ██║    ██║██║  ██║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔══██╗         
        ██║ █╗ ██║███████║███████║   ██║   ███████╗███████║██████╔╝██████╔╝         
        ██║███╗██║██╔══██║██╔══██║   ██║   ╚════██║██╔══██║██╔═══╝ ██╔═══╝          
        ╚███╔███╔╝██║  ██║██║  ██║   ██║   ███████║██║  ██║██║     ██║              
         ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝              
                                                                                    
     █████╗ ██╗   ██╗████████╗ ██████╗ ███╗   ███╗ █████╗ ████████╗ ██████╗ ██████╗ 
    ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗████╗ ████║██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗
    ███████║██║   ██║   ██║   ██║   ██║██╔████╔██║███████║   ██║   ██║   ██║██████╔╝
    ██╔══██║██║   ██║   ██║   ██║   ██║██║╚██╔╝██║██╔══██║   ██║   ██║   ██║██╔══██╗
    ██║  ██║╚██████╔╝   ██║   ╚██████╔╝██║ ╚═╝ ██║██║  ██║   ██║   ╚██████╔╝██║  ██║
    ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝
                                                                                    
✓ Initializing WA
┌─────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                    Values                                                                     │
├─────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                  '2.2023.2'                                                                   │
│       PAGE_UA       │ 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                       '1.9.63 UPDATE AVAILABLE: 1.9.64'                                                       │
│   BROWSER_VERSION   │                                                         'HeadlessChrome/83.0.4103.0'                                                          │
└─────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
    Injecting api
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▄ ▀█▀▄▄█ ▄▄ ▀▄ ██▀██▄ ▄▀██ ▄▄▄▄▄ █
█ █   █ ██ █ █  ▄▀▀▄ ▀ ▄█▀▄▄▄▀▀▄ ██ █   █ █
█ █▄▄▄█ ██▀█▄▄▄▀█ ████ ▀▀█▀▄▄ █ ▄ █ █▄▄▄█ █
█▄▄▄▄▄▄▄█ █ ▀ ▀ ▀▄█ █▄█▄▀▄▀ █ █▄▀▄█▄▄▄▄▄▄▄█
█ ▄█ ▄▀▄▀▀  ▀▄▀▄███▀▄█ ▀▄█▀ ▄█ █  █▄█▀█▀▀▄█
█ █▀ ▀▀▄ ████▀█▀▄ ▀▀▀▄█▀▄ ▄▄▄   █▀ ▀ █▀▄▄▀█
█▀█▄▄▀█▄█▀██▄▀▀▄█  ▀██▀▀▄▄▄█▄▀▀██▀▀▄ ▀▄▀▀▄█
█▄ ▀▀█▀▄▄█ ██▀█▄▄▀██  █ █▄█ ▄▀█▄ ▄ █ ▀  █ █
█ ▀▄  █▄▀▀▄ ▄▀ ▀██ █▄▀█ █▀ █ ▄▀██ ██▄ █ ▄██
█  ▀ ██▄ ██▄   █▄ █ ▄▀█  ▀   █▄▄ █  ▄ █▀█▄█
██ ▀█▀ ▄ ██ █▄▄▀▄▄▄▄████▀ ▄▄ ▄█▀▄▄ ▄▀▀ █▄▀█
████▄▄▀▄▄▀█ █▄▄▀ █▀▄█ █▄ ███ ▄ ██▀ █   █▀▀█
█▄▀▀▀▀▄▄  ▄▄█▄██  █▄▀▄ █▀█▀▀ █ ▀ █▀▄█▀██▄▄█
█▀█ ▄▄ ▄  █▄█▀▀ ▄▄▄  ▀█ ▀▄█▄▄▀▄ ▄█ ▀▄█ ▀▀ █
█ █▄▄ ▀▄ ██▄ ▀██▀  ██ ▄▄▄▀▄▀▄██▄█ ██▀▀▀▄ ▄█
█   ▀▀ ▄▄█ ▄▄▀▀  ▄█▄ ▀██▄ ▀▀ ▀▄  ▄▀  ▀▄▀▄▄█
█▄▄█▄█▄▄▄ ██▀▄▄▄█▄██▄▄▄███▄▄▄█▄█  ▄▄▄ █▀ ▄█
█ ▄▄▄▄▄ ██  ▄▀█  ▄  ▀▀▄█▄██▄▄▀ █  █▄█  ▄▄██
█ █   █ █   ▄▄ ▄▄▀▀▄ █ ▀ ▀ █▀▀▄▀▄  ▄▄▄▄ ▄▄█
█ █▄▄▄█ █▀▀  ▄▄▀▄ ▄ ▄ █ █▄█▀▄▄██ ▄██ ▄▀▀▄▀█
█▄▄▄▄▄▄▄█▄▄█████▄█▄█▄██▄▄▄▄██▄▄██▄▄███▄▄███

 
🌓  Authenticate to continue
✓ Loading QR

**create() code**

const wa = require('@open-wa/wa-automate');

wa.create().then(client => start(client));

function start(client) {
  client.onMessage(message => {
    if (message.body === 'Hi') {
      client.sendText(message.from, '👋 Hello!');
    }
  });
}

**Expected behavior**
after scan QR with whatsapp app , should be authorized 

**DEBUG INFO**
as described above 

**Screenshots**
as described above 

**Host (please complete the following information):**
as described above

**Comment by smashah** [comment]
As it says in the logs

```
 '1.9.63 UPDATE AVAILABLE: 1.9.64'
```

Update to the latest version @jj449

**Comment by jj449** [comment]
update to 1.9.64  , same problem 

node wa.js
         ██████╗  ██████╗ ██████╗ ███████╗███╗   ██╗      ██╗    ██╗ █████╗         
        ██╔═══██╗██╔═══██╗██╔══██╗██╔════╝████╗  ██║      ██║    ██║██╔══██╗        
        ██║██╗██║██║   ██║██████╔╝█████╗  ██╔██╗ ██║█████╗██║ █╗ ██║███████║        
        ██║██║██║██║   ██║██╔═══╝ ██╔══╝  ██║╚██╗██║╚════╝██║███╗██║██╔══██║        
        ╚█║████╔╝╚██████╔╝██║     ███████╗██║ ╚████║      ╚███╔███╔╝██║  ██║        
         ╚╝╚═══╝  ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝       ╚══╝╚══╝ ╚═╝  ╚═╝        
                                                                                    
        ██╗    ██╗██╗  ██╗ █████╗ ████████╗███████╗ █████╗ ██████╗ ██████╗          
        ██║    ██║██║  ██║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔══██╗         
        ██║ █╗ ██║███████║███████║   ██║   ███████╗███████║██████╔╝██████╔╝         
        ██║███╗██║██╔══██║██╔══██║   ██║   ╚════██║██╔══██║██╔═══╝ ██╔═══╝          
        ╚███╔███╔╝██║  ██║██║  ██║   ██║   ███████║██║  ██║██║     ██║              
         ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝              
                                                                                    
     █████╗ ██╗   ██╗████████╗ ██████╗ ███╗   ███╗ █████╗ ████████╗ ██████╗ ██████╗ 
    ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗████╗ ████║██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗
    ███████║██║   ██║   ██║   ██║   ██║██╔████╔██║███████║   ██║   ██║   ██║██████╔╝
    ██╔══██║██║   ██║   ██║   ██║   ██║██║╚██╔╝██║██╔══██║   ██║   ██║   ██║██╔══██╗
    ██║  ██║╚██████╔╝   ██║   ╚██████╔╝██║ ╚═╝ ██║██║  ██║   ██║   ╚██████╔╝██║  ██║
    ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝
                                                                                    
✓ Initializing WA
┌─────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                    Values                                                                     │
├─────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                  '2.2023.2'                                                                   │
│       PAGE_UA       │ 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '1.9.64'                                                                    │
│   BROWSER_VERSION   │                                                         'HeadlessChrome/83.0.4103.0'                                                          │
└─────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
    Authenticating
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀▄█▀██▄   ▄█▀▀▀ ▄█▄ █▄▄▄██ ▄▄▄▄▄ █
█ █   █ █▄▀██ █▄ █ ▀ ▀█▀▄▄█    ▀▀▄█ █   █ █
█ █▄▄▄█ █ ▄█▄▀▀█▀   ▀▀ █▄▀▀▀ ▄█ ▀██ █▄▄▄█ █
█▄▄▄▄▄▄▄█ ▀ ▀ █▄▀▄▀ ▀ ▀▄▀ █ █ ▀ █ █▄▄▄▄▄▄▄█
█  █ █▀▄▄▀ ▀ ▀█▄▀ ▀▀█   ▄█  █ ██▀ █▄▄▄▀  ▀█
██▄ ▄ ▄▄ ▀▄ █▄ █▀██▀ █ █▀█▀▀▀▄█▀▄▄▀▄ ██  ██
█▀█▄█▀▄▄██▀▀▀█  ██▀█▀█ █▀▀▄██▄▄█▀ █▄ ██▄▄██
██▀ ▀▀▀▄▄▀▀▀ █▀█▀▀▀▄▀▀▀▀  ▀█▀█ ▄▀▀  ▀█▄▄ ▄█
██▄▄▀▄█▄█▀█ ▀█▄█▄  ███  ▄▀▀▀█▀ █▄█▄▀ ▄▄█▀▀█
██▀▀ ▀ ▄ █▀▀▀██▀█▀ ▄▀▄  █▀▄▄▀▀ ▀█ ▀  █ █  █
█▀▀▄█ █▄▄▀ █▀ ▀██ ▀█ ▀ ██▄▄▀▄███▄▀▄ ▄██▀▀██
█ █▀▀ ▄▄▀▀▄▄   █▀█▄▄   ██▀  ▀███ ▀███  ▀▄██
█ ▀▀▀ ▀▄█▀ ▄  ▀▀ █ ▀ ▀▄█  ▀▀ █▄ █ ▄ ██▄▀█▄█
█ ▀▄ ▀▀▄▀█ █▄▄▄▄█▀▀ ▀█▀▄▄▀▀▀▀  ▀█▀▄▄ █▀▄  █
██▀▄  ▀▄█▀▄ ██▄▀▄▀██▀▄ ▀▀██ ▄▄█▀▀▄ █▄█ ▀▄▀█
█▄██▀ ▀▄▀▀ █▀██▄█▀  ▀ ▀▄▀▀█▄█ ▀▀█▀▀▀▄██▄▀ █
█▄█▄███▄▄▀▄▄ ▀ █  █ ▀ ▄ ▄ █▄  ▀█▀ ▄▄▄ █ ▀ █
█ ▄▄▄▄▄ █▄▀▀██ ▄▀▀██▄ ▀██▄▀▄█▄▄██ █▄█ █▀ ▀█
█ █   █ █▀▄   ▀  ▄ ▀█  ▀    █▄▄▀█▄   ▄▄▀▀ █
█ █▄▄▄█ █▀▀▀█  ▀█  ▄█  ▄▄█ ▀█▄ █ █▄█▀▄▄▄▀██
█▄▄▄▄▄▄▄█▄▄█▄█▄███▄█▄▄▄▄█████▄▄██▄██▄▄██▄██

 
^C  Authenticate to continue
✓ Loading QR


or what Im doing wrong  ? any clue ?  Thanks.

**Comment by smashah** [comment]
Needs more information

**Comment by jj449** [comment]
> Needs more information

 smashah 
sorry  , Im new to here .  all info i can provide , just like above  , for now . 
I will try again & try to collect more info later .  Thanks .

**Comment by smashah** [comment]
please share wa.js

**Comment by smashah** [comment]
Closing due to inactivty. Please share the wa.js file so we can help. Thanks
