### ISSUE TITLE
Send link and location is returning promise error

### ISSUE THREAD

**Issue by andremacola** [open-wa/wa-automate-nodejs#530]
**Describe the bug**
sendText is working fine but when I try to use sendYoutubeLink, sendLinkWithAutoPreview, sendLocation and maybe other methods the WAPI Promise is returning `rejected` (see image below)

**Steps to Reproduce**
1. Start a normal basic server
2. Try to send a link: `const link = await client.sendYoutubeLink('xyz@c.us', 'https://www.youtube.com/watch?v=L_LUpnjgPso');`
3. See error

**create() code**
```javascript
const whpServerStart = async function() {
	wa.create({
		headless: false,
		sessionId: process.env.SESSION_TOKEN,
	})
		.then(async (client) => await whpConfigureClient(client))
		.catch((error) => {
			console.log('Error', error.message);
		});
};

const whpConfigureClient = async function(client) {
	const link = await client.sendYoutubeLink('xyz@c.us', 'https://www.youtube.com/watch?v=L_LUpnjgPso');
}
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2023.2',
  PAGE_UA: 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36',
  WA_AUTOMATE_VERSION: '1.9.64',
  BROWSER_VERSION: 'Chrome/83.0.4103.0'
}
```

**Screenshots**
![Captura de Tela 2020-06-08 às 01 19 32](https://user-images.githubusercontent.com/3408809/83992700-86497080-a927-11ea-9658-80888c96252a.png)

**Host (please complete the following information):**
 - OS: iOS and OSX Catalina 10.5.4
 - Node : v12.16.1

**Comment by andremacola** [comment]
**Edit:** Now I see, the text needs to be sent even width empty string.

like: `const link = await client.sendYoutubeLink('xyz@c.us', 'https://www.youtube.com/watch?v=L_LUpnjgPso', '');`

I think the text string can be optional.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.65](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.64...1.9.65) (2020-06-08)

- build(deps-dev): bump @types/node from 14.0.10 to 14.0.11 [`#522`](https://github.com/open-wa/wa-automate-nodejs/pull/522)
- Release 1.9.65 [`5d2795f`](https://github.com/open-wa/wa-automate-nodejs/commit/5d2795f643ba63665572cc367f59cccb7a8d8ffd)
- breaking: `reply` now only allows message id, not whole object #525 [`2281858`](https://github.com/open-wa/wa-automate-nodejs/commit/2281858f42f347157a4f7cbb21b9ab8dcf3a18b3)
- improved docs: `getAllMessagesInChat` [`21d5d96`](https://github.com/open-wa/wa-automate-nodejs/commit/21d5d96bf5c9731e0fb7b69ca72492462a890cc6)
- feature: make text optional in location and youtube messages #530 [`21c6e7a`](https://github.com/open-wa/wa-automate-nodejs/commit/21c6e7ad1c15feea9acdaede12cd6bd843841ffe)
- updated readme [`e53347f`](https://github.com/open-wa/wa-automate-nodejs/commit/e53347f82397facf2b55fe6c2cec91672c36ca05)

**Comment by smashah** [comment]
thanks for bringing this up @andremacola

Should be fixed now.
