### ISSUE TITLE
Error: Cannot find module 'p-queue'

### ISSUE THREAD

**Issue by sandro-salles** [open-wa/wa-automate-nodejs#536]
**Describe the bug**
Latest release depends on p-queue module, but it's only listed as devDependency, throwing an error if not installed on import time.

**Steps to Reproduce**
1. import wautomate from '@open-wa/wa-automate' and see the error

**Expected behavior**
P-queue should be an optional dependency (including the webhooks funcionality)

**Comment by smashah** [comment]
Not removing the functionality just after it was implemented.

**Comment by smashah** [comment]
Keep an eye on #535 for the release
