### ISSUE TITLE
SEND IMAGE, AUDIO and PDF EXAMPLE

### ISSUE THREAD

**Issue by contatodct** [open-wa/wa-automate-nodejs#539]
Você quis dizer: por favor me envie um exemplo de como enviar imagem, audio video e PDF, se precisa instalar algo a mais e etc.... me da uma ajuda por favor
140/5000
please send me an example of how to send image, audio video and PDF, if you need to install something else and etc ....

help me please

**Comment by mcroni** [comment]
```
import { create, Client} from '@open-wa/wa-automate';

function start(client: Client) {
await client.sendFile('xyz@c.us',[BASE64 FILE DATA],'some file.pdf', `Hello this is the caption`);
}

create().then(client => start(client));``` . Kindly read the docs

**Comment by smashah** [comment]
Read the documentation before making issues. https://open-wa.github.io/wa-automate-nodejs/classes/client.html#sendfile
