### ISSUE TITLE
Not receive message is not in the phone's contact list.

### ISSUE THREAD

**Issue by 3cubos** [open-wa/wa-automate-nodejs#544]
Hi, I'm doing some tests. Using the example: **new_messages_observer.py**. The problem is when I send a message from a new number, I don't read a new message from the new number. How to fix this?
ex:
my phone = A, sister = b, mom = c, father = d
b -> sender text -> A OK
c -> sender text -> A OK
d -> sender text -> A NOT receive, is not in the phone's contact list.
How to fix this?
Sorry my bad English, from Brazil.

**Comment by smashah** [comment]
I suggest sending d a WhatsApp link which starts a message with A

https://github.com/open-wa/wa-automate-nodejs/blob/master/README.md#starting-a-conversation

**Comment by jesusvalverde** [comment]
Is part of the software..to avoid spamers .

https://github.com/open-wa/wa-automate-nodejs#starting-a-conversation

**Comment by 3cubos** [comment]
> I suggest sending d a WhatsApp link which starts a message with A
> 
> https://github.com/open-wa/wa-automate-nodejs/blob/master/README.md#starting-a-conversation

I'm using python! do i need the key? what the value? $$$

**Comment by smashah** [comment]
If you're using python why are you making an issue here? Please use https://github.com/open-wa/wa-automate-python

**Comment by 3cubos** [comment]
> If you're using python why are you making an issue here? Please use https://github.com/open-wa/wa-automate-python

sorry when i posted i hadn't seen it from node's github!

**Comment by smashah** [comment]
@3cubos ha no worries! The answer is the same for python also 👍
