### ISSUE TITLE
Feature: expose a way to kill qr code generation loop on demand.

### ISSUE THREAD

**Issue by sandro-salles** [open-wa/wa-automate-nodejs#548]
**The scenario**

- **create** function is called with **autoRefresh: true** and **qrTimeout** also set.
- During the qr code loop, while waiting for a scan, for any reason the user decides not to complete the scan and just finish the process. 

In this case it would be nice to have a function to force stop the qr code loop (and the browser session) for that specific sessionId so we can save the resources used to keep the browser and the loop running by killing it immediately, instead of having to wait for qrTimeout to complete.

What you think?

Regards.

**Comment by smashah** [comment]
I've thought a lot about this and the short answer is no. This feature won't be properly possible until the initializer itself is a class. So it would require a full rearchitecture, maybe it will happen one day but right now, this isn't enough reason to do it.

I suggest wrapping each instance of open-wa in PM2 then managing it using that/docker.

I will reopen this when there is enough reason to rebuild the initializer.

Good suggestion though.

**Comment by smashah** [comment]
@sandro-salles check this out https://pm2.keymetrics.io/docs/usage/pm2-api/

**Comment by sandro-salles** [comment]
Hmm... very nice... i have to check on that, to understand how to kill a specific session, since the i don't use a node process per session, the node process is the same... i just open multiple clients within that same process... 

Let me check! Thanks again!

**Comment by sandro-salles** [comment]
Just as a follow-up, since implementing pm2 on my project would also involve a hard re-architecture on my code (although it's really interesting), i decide to follow a different path (for now).

I'm adding a "custom" chromiumArg to create method (ex.: --bot-ID-browser), and if i need to kill the process before qrcode generation reaches the timeout, i'm using this code:

`
import treekill from 'tree-kill'
import psaux from 'psaux'

await psaux().then((list) => {
    for (let bot_browser of list.query({ command: `~--bot-${bot_id}-browser` })) {
      logger.info(`Killing bot id (${bot_id}) browser process with pid (${bot_browser.pid})`)
      treekill(bot_browser.pid, 'SIGKILL')
    }
  })
`
Of course it trigger an exception on create method, but since i know the current state for that specific bot (awaiting qr code scan), i can just logger.warn that exception and ignore it.

Regards
