### ISSUE TITLE
error Run Debian 9 Help-me

### ISSUE THREAD

**Issue by contatodct** [open-wa/wa-automate-nodejs#549]
root@mk-auth:/var/www/wppboot/admin# node index.js
         ██████╗  ██████╗ ██████╗ ███████╗███╗   ██╗      ██╗    ██╗ █████╗
        ██╔═══██╗██╔═══██╗██╔══██╗██╔════╝████╗  ██║      ██║    ██║██╔══██╗
        ██║██╗██║██║   ██║██████╔╝█████╗  ██╔██╗ ██║█████╗██║ █╗ ██║███████║
        ██║██║██║██║   ██║██╔═══╝ ██╔══╝  ██║╚██╗██║╚════╝██║███╗██║██╔══██║
        ╚█║████╔╝╚██████╔╝██║     ███████╗██║ ╚████║      ╚███╔███╔╝██║  ██║
         ╚╝╚═══╝  ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝       ╚══╝╚══╝ ╚═╝  ╚═╝

        ██╗    ██╗██╗  ██╗ █████╗ ████████╗███████╗ █████╗ ██████╗ ██████╗
        ██║    ██║██║  ██║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██╔══██╗
        ██║ █╗ ██║███████║███████║   ██║   ███████╗███████║██████╔╝██████╔╝
        ██║███╗██║██╔══██║██╔══██║   ██║   ╚════██║██╔══██║██╔═══╝ ██╔═══╝
        ╚███╔███╔╝██║  ██║██║  ██║   ██║   ███████║██║  ██║██║     ██║
         ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝

     █████╗ ██╗   ██╗████████╗ ██████╗ ███╗   ███╗ █████╗ ████████╗ ██████╗ ██████╗
    ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗████╗ ████║██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗
    ███████║██║   ██║   ██║   ██║   ██║██╔████╔██║███████║   ██║   ██║   ██║██████╔╝
    ██╔══██║██║   ██║   ██║   ██║   ██║██║╚██╔╝██║██╔══██║   ██║   ██║   ██║██╔══██╗
    ██║  ██║╚██████╔╝   ██║   ╚██████╔╝██║ ╚═╝ ██║██║  ██║   ██║   ╚██████╔╝██║  ██║
    ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝
(node:22840) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/var/www/wppboot/admin/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/var/www/wppboot/admin/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at Interface.<anonymous> (/var/www/wppboot/admin/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:22840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sandro-salles** [comment]
@contatodct take a look to this... it may help:
https://medium.com/@ssmak/how-to-fix-puppetteer-error-while-loading-shared-libraries-libx11-xcb-so-1-c1918b75acc3

**Comment by smashah** [comment]
Puppeteer issue
