### ISSUE TITLE
Can't npm install from github link

### ISSUE THREAD

**Issue by kakema7272** [open-wa/wa-automate-nodejs#550]
**Describe the bug**
npm install from github resulting in index.js mising

**Steps to Reproduce**
1. npm init -y
2. npm install https://github.com/open-wa/wa-automate-nodejs

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**
Compile npm after installing

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
There are frequent enough updates to not need to install from GitHub. Please just use the npm
