### ISSUE TITLE
Bot hang if running longer than a week and can't restarted

### ISSUE THREAD

**Issue by gnadelwartz** [open-wa/wa-automate-nodejs#554]
**Describe the bug**
After running longer than a week˜bot stop working and hang on restart at Initializing WA forever,
even updated to latest version. If I reboot my linux box it works again.

this happens since round about 4 weeks

**Steps to Reproduce**
- Create a simple bot, simply saving all messages recieved to a file
- run it until it stops receiving new messages
- kill and restart bot

**create() code**
This is the code you use to create the client. e.g
```javascript
import * as sulla from '@open-wa/wa-automate';

async function start(client) {                                                                                                         
  // START execute on every new message                                                                                                
  client.onAnyMessage(async message => {
    console.log(message.content);
  }
}
sulla.create('session',                                                                                                
{                                                                                                                                      
  // For Linux:                                                                                                                        
  // executablePath: '/usr/bin/chromium',                                                                                              
  // headless: false                                                                                                                   
}                                                                                                                                      
).then(client => start(client));

```

**Expected behavior**
bot restart should be possible without restart OS
**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
✓ Initializing WA                                                                                                                                                                                                 
┌─────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐                                           
│       (index)       │                                                                    Values                                                                     │                                           
├─────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤                                           
│     WA_VERSION      │                                                                  '2.2023.2'                                                                   │                                           
│       PAGE_UA       │ 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36' │                                           
│ WA_AUTOMATE_VERSION │                                                                   '1.9.74'                                                                    │                                           
│   BROWSER_VERSION   │                                                         'HeadlessChrome/83.0.4103.0'                                                          │                                           
└─────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: OpenSuSE Leap 15.1

**Additional context**

**Comment by gnadelwartz** [comment]
today this happened with 1.9.64 and can't restart after update to 1.9.74.

**Comment by smashah** [comment]
Please make sure to restart your bot frequently to prevent memory leaks. WA releases new versions frequently so it is possible that you restarted the session using an expired open-wa. You should always use the latest version and restart your session frequently. 

There's not much else that can be done to be honest, there are no error logs, I don't know which messages might've triggered an issue, etc. 

Also, your restarting of the OS has almost nothing to do with this library, may have just been a coincidence that that worked. Closing for now, please report back with more context if it happens again.

**Comment by gnadelwartz** [comment]
I tried everthing:

- update automate: not working
- delete session: not working
- try start an other script: not working
- log out and in (without running bot): not working
- look for running chrome instances: no chrome running
- reboot: working

may be a long running chrome/pupetter block ressources.
before it happend the first time it was possible to run and restart the bot for weeks ..

OK, I'll try to restart and update more often. hm and may be an older version of pupeteer, as it worked in the past ...

**Comment by smashah** [comment]
@gnadelwartz clear node modules and run npm i 

If this issue continues after a few weeks, DM me on discord and I'll have a look at the code as it may provide some more clues

**Comment by gnadelwartz** [comment]
it looks like the advise update and restart often fixed the problem :-)

I rund the bot in a TMUX session in background and created an rc script to start, stop, restart and attach to the bot. may be you can place the rc script in the demo folder as an example for others.

**Comment by smashah** [comment]
@gnadelwartz Awesome. Always healthy to restart regularly. Maybe you can also try this feature I just implemented:

https://github.com/open-wa/wa-automate-nodejs/issues/582

It refreshes the page and sets up the listeners again without needing to restart the whole process.

Also, i will be making a docker-compose.yaml which will be very easy to use and keep fresh
