### ISSUE TITLE
Send message to a new chat

### ISSUE THREAD

**Issue by alpires** [open-wa/wa-automate-nodejs#556]
Hi Guys, how send message to a new contact without chat? Previously I did something like this:

That added a chat:
Store.Chat.add({ id: new window.Store.UserConstructor("5511969787687@c.us", {intentionallyUsePrivateConstructor: true})}, { merge: true, add: true, });

But now with new version of whatsapp web it doesn't work anymore.
Please, some idea how fix this?

**Comment by smashah** [comment]
@alpires https://github.com/open-wa/wa-automate-nodejs/blob/master/README.md

**Comment by smashah** [comment]
Duplicate #254

**Comment by alpires** [comment]
@smashah I need only de JS to do this, if a buy a License Key you send me a JS?

**Comment by smashah** [comment]
Hmmm possibly. Let me think about this and get back to you.

**Comment by alpires** [comment]
@smashah I have a software, my software send message to contact list, but I need create a chat before, I use only JS to send message, so please help me. 
I buy a monthly license...please.

**Comment by smashah** [comment]
Ok I'll work something out tonight.

**Comment by alpires** [comment]
@smashah I will get the license, but just so you know, in another project (mukulhase) this function is working, take a look at it.

**Comment by alpires** [comment]
Take a look on this, this code works with no contact:

if (!window.Store) {
(function () {
function getStore(modules) {
let foundCount = 0;
let neededObjects = [
{ id: "Store", conditions: (module) => (module.Chat && module.Msg) ? module : 
null },
{ id: "MediaCollection", conditions: (module) => (module.default && 
module.default.prototype && module.default.prototype.processAttachments) ? 
module.default : null },
{ id: "MediaProcess", conditions: (module) => (module.BLOB) ? module : null },
{ id: "Wap", conditions: (module) => (module.createGroup) ? module : null },
{ id: "ServiceWorker", conditions: (module) => (module.default && 
module.default.killServiceWorker) ? module : null },
{ id: 'Presence', conditions: (value) => (value.default && value.default.Presence) 
? value.default : null },
{ id: "State", conditions: (module) => (module.STATE && module.STREAM) ? 
module : null },
{ id: "WapDelete", conditions: (module) => (module.sendConversationDelete && 
module.sendConversationDelete.length == 2) ? module : null },
{ id: "Conn", conditions: (module) => (module.default && module.default.ref && 
module.default.refTTL) ? module.default : null },
{ id: "WapQuery", conditions: (module) => (module.queryExist) ? module : 
((module.default && module.default.queryExist) ? module.default : null) },
{ id: "CryptoLib", conditions: (module) => (module.decryptE2EMedia) ? module : 
null },
{ id: "OpenChat", conditions: (module) => (module.default && 
module.default.prototype && module.default.prototype.openChat) ? 
module.default : null },
{ id: "UserConstructor", conditions: (module) => (module.default && 
module.default.prototype && module.default.prototype.isServer && 
module.default.prototype.isUser) ? module.default : null },
{ id: "SendTextMsgToChat", conditions: (module) => 
(module.sendTextMsgToChat) ? module.sendTextMsgToChat : null },
{ id: "SendSeen", conditions: (module) => (module.sendSeen) ? module.sendSeen 
: null },
{ id: "sendDelete", conditions: (module) => (module.sendDelete) ? 
module.sendDelete : null }
];
for (let idx in modules) {
if ((typeof modules[idx] === "object") && (modules[idx] !== null)) {
let first = Object.values(modules[idx])[0];
if ((typeof first === "object") && (first.exports)) {
for (let idx2 in modules[idx]) {
let module = modules(idx2);
if (!module) {
continue;
}
neededObjects.forEach((needObj) => {
if (!needObj.conditions || needObj.foundedModule)
return;
let neededModule = needObj.conditions(module);
if (neededModule !== null) {
foundCount++;
needObj.foundedModule = neededModule;
}
});
if (foundCount == neededObjects.length) {
break;
}
}
let neededStore = neededObjects.find((needObj) => needObj.id === "Store");
                    window.Store = neededStore.foundedModule ? 
neededStore.foundedModule : {};
                    neededObjects.splice(neededObjects.indexOf(neededStore), 1);
                    neededObjects.forEach((needObj) => {
                        if (needObj.foundedModule) {
                            window.Store[needObj.id] = needObj.foundedModule;
                        }
                    });
                    window.Store.sendMessage = function (e) {
                        return window.Store.SendTextMsgToChat(this, ...arguments);
                    };
					
					if (window.Store.Presence) {
						for (const prop in 
window.Store.Presence) {
							if (prop === 
"Presence") {
								
continue;
							}
							console.log
(prop);
							
window.Store[prop] = window.Store.Presence[prop] || window.Store[prop];
						}
					}
					
                    return window.Store;
                }
            }
        }

		
        
    }

    if (typeof webpackJsonp === 'function') {
        webpackJsonp([], {'parasite': (x, y, z) => getStore(z)}, ['parasite']);
    } else {
        webpackJsonp.push([
            ['parasite'],
            {
                parasite: function (o, e, t) {
                    getStore(t);
                }
            },
            [['parasite']]
        ]);
    }

})();

}

window.WAPI = {
    lastRead: {}
};

**Comment by smashah** [comment]
There are no issues with the code used through the license server. It works perfectly fine using a more robust method not available in any other library.

**Comment by alpires** [comment]
@smashah I bought the license
Username: alpires
Can you send me JS to my purchase email?
Thanks

**Comment by smashah** [comment]
@alpires Please check out the latet version of wapi.js

Now you can unlock features like this:

1. Install [this chrome extension](https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden/related?hl=en). Disable CSP (AT YOUR OWN PERIL)

2. In the console, run 

```javascript
await WAPI.addLicenseKey('U2YB3B-IN23NIOF2U-2K023DK20-2J90J8J2F')
``` 


3. send a text to unknown number as you would any other number

```javascript
await WAPI.sendMessage('551234567890@c.us','test')
```

**Comment by alpires** [comment]
@smashah in await WAPI.addLicenseKey

CSP is disabled but:

VM25:2194 Refused to connect to 'https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/master/package.json' because it violates the following Content Security Policy directive: "connect-src 'self' https://*.whatsapp.net https://www.facebook.com https://*.giphy.com https://*.tenor.co blob: https://crashlogs.whatsapp.net/wa_clb_data https://crashlogs.whatsapp.net/wa_fls_upload_check https://www.bingapis.com/api/v6/images/search https://*.google-analytics.com wss://*.web.whatsapp.com wss://web.whatsapp.com https://dyn.web.whatsapp.com".

window.WAPI.addLicenseKey @ VM25:2194
(anonymous) @ VM66:1
VM25:2194 Refused to connect to 'https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/master/package.json' because it violates the document's Content Security Policy.
window.WAPI.addLicenseKey @ VM25:2194
(anonymous) @ VM66:1
VM25:2195 Uncaught TypeError: Failed to fetch
    at Object.window.WAPI.addLicenseKey (<anonymous>:2194:25)
    at <anonymous>:1:12

**Comment by alpires** [comment]
@smashah now works. Does it work to send image, vcard and pdf too?

**Comment by smashah** [comment]
Yes

**Comment by alpires** [comment]
@smashah  it didn't work, some idea?

await WAPI.addLicenseKey('my-key');
true
await WAPI.sendMessage('5517995412547@c.us','test');
undefined

**Comment by smashah** [comment]
@alpires can you join the discord to continue this convo thanks

**Comment by tsapap** [comment]
Hi smashah I wrote you an email to ask if I can receive wapi.js which allows sending messages and files to numbers not included in the address book. I'm waiting for your answer
