### ISSUE TITLE
Issue on decoding and saving short ptt 

### ISSUE THREAD

**Issue by dantenol** [open-wa/wa-automate-nodejs#558]
**Describe the bug**
Running the very same example on the READE.md section about Decrypting Media, the voice note is not sent back and the file is not saved locally. I tried comparing the base64 values from the sent ptt to the one from `decryptMedia` and they don't match.

Recordings longer than two seconds work fine, with an almost unnoticeable cut on the very last milliseconds (which is also an smaller problem). The example on the docs works fine with audio files (not ptt), images and videos.

Tested on Chrome and Chromium and got same results.

**Steps to Reproduce**
1. Add the example media decryption to the client `onMessage`
2. Send a ptt one second long to the number
3. Notice that _sometimes_ the message will not be sent back
4. Send a longer ptt (4-5 seconds) to the number
5. Check that the audio file was sent back but with a cut on the end of the audio

**create() code**
```javascript
wa.create({
  licenseKey: *****,
  headless: false,
  devtools: false,
  useChrome: true,
  debug: true,
  logQR: true,
}).then((client) => start(client));
```

**Expected behavior**
the client should be able do properly decrypt voice notes. Being able to save and play short ones and not cutting the end of longer ones.

**DEBUG INFO**
```
Debug Info {
  WA_VERSION:2.2025.6,
  PAGE_UA: WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.3,
  WA_AUTOMATE_VERSION: 1.9.75,
  BROWSER_VERSION: Chrome/83.0.4103.97.
}
```

**Screenshots**
![WhatsApp Image 2020-06-18 at 11 24 29](https://user-images.githubusercontent.com/20271959/85032561-5cc5eb80-b156-11ea-93f2-e833815cdb6f.jpeg)

**Host (please complete the following information):**
 - OS: Ubuntu 20.04
- Phone: Moto G7 (Android 10)
.

**Comment by smashah** [comment]
#360 #123

Thanks for filling out the template properly. 

This is a known issue on whatsapp's end. Before, it would cut out at least 1 second off the end of the clip. I've looked into this for a while and haven't been able to find a solution other than telling recipients start talking after 2 seconds of holding the voice note button.

**Comment by smashah** [comment]
I'm going to close this for now. Thanks
