### ISSUE TITLE
Program stuck on 'Checking license' 

### ISSUE THREAD

**Issue by dantenol** [open-wa/wa-automate-nodejs#559]
**Describe the bug**
Stuck on 'Checking License'.

**Steps to Reproduce**
1.Run the code with subscribed license key and the system either gets stuck on 'Checking license' or passes and does nothing.

**create() code**
This is the code you use to create the client. e.g
```javascript
wa.create({
        licenseKey: "..."
});
```

**Expected behavior**
The app should successfully connect with client and proceed with next callback.

**DEBUG INFO**
```
Debug Info {
  WA_VERSION:2.2025.6,
  PAGE_UA: WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.3,
  WA_AUTOMATE_VERSION: 1.9.75,
  BROWSER_VERSION: Chrome/83.0.4103.97.
}
```

It appeared before on #485 but is back again

**Comment by smashah** [comment]
Duplicate #499 

Stupid glitch is so unreliable. This will be migrated today. I've had enough of this.
