### ISSUE TITLE
UnhandledPromiseRejectionWarning: state: OPENING

### ISSUE THREAD

**Issue by realunreals** [open-wa/wa-automate-nodejs#575]
**Describe the bug**
**1st problem:** I have updated version from 1.9.64 to 1.9.81 few hours ago. Then started state problem. When state is changing I'm getting warning **"(node:24776) UnhandledPromiseRejectionWarning: state: OPENING"** Also same warning on PAIRING etc...

**2nd problem:** After the update also globalClient.kill(); working only one time but I'm receiving message 2 times "shutting down" then again "shutting down".

**create() code**
create({
        sessionId:'./sessions/session_1',
	useChrome: true,
	headless:true,
	throwErrorOnTosBlock:true,
	killTimer:40,
	autoRefresh:true, 
	qrRefreshS:15,
})

Debug Info {
  WA_VERSION: 2.2025.6,
  PAGE_UA: WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36,
  WA_AUTOMATE_VERSION: 1.9.64,
  BROWSER_VERSION: HeadlessChrome/83.0.4103.116
}

**Screenshots**
(node:24776) UnhandledPromiseRejectionWarning: state: OPENING
(node:24776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Host (please complete the following information):**
 - OS: Windows

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.82](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.81...1.9.82) (2020-06-25)

- Release 1.9.82 [`279b105`](https://github.com/open-wa/wa-automate-nodejs/commit/279b10598ccc9ec1c6b5fb378b362283afa8d7dd)
- docs: renamed WAState to State [`e428aa8`](https://github.com/open-wa/wa-automate-nodejs/commit/e428aa8e2f8de559bcaa2672a87e16d778bda802)
- Story feature: get list of users that read your story #574 [`0b95620`](https://github.com/open-wa/wa-automate-nodejs/commit/0b956204077c72560eb8fe793702f588595e521d)
- state check only in safe mode #575 [`1b1e109`](https://github.com/open-wa/wa-automate-nodejs/commit/1b1e10941041c6aa9384071534f3aab0cdd3adf7)
- delay config changes #563 [`33972d0`](https://github.com/open-wa/wa-automate-nodejs/commit/33972d0d71ddff4d6d6f6249268fc9049db94b5b)
- kill process on initializer kill #563 [`8de92bc`](https://github.com/open-wa/wa-automate-nodejs/commit/8de92bc0243e7ba2696fc1989ebf0a6518662fc7)

**Comment by smashah** [comment]
@realunreals please use the latest version and make sure you **don't** have `safeMode` set to true
