### ISSUE TITLE
Broken method 'getAllChatsWithMessages' 

### ISSUE THREAD

**Issue by blackchineykh** [open-wa/wa-automate-nodejs#576]
**Describe the bug**
When getting all chats with new messages **getAllChatsWithMessages(true)**, this method seems broken as it returns false for all of the chats instead of the array of chat objects. This was working fine in version 1.9.64 and I just upgraded to the latest 1.9.83

**Steps to Reproduce**
1. Start the client
2. I check for the total unread messages and if greater than 0, I get all chats with unread messages 
3. I then process them to get the unread messages and handle them
4. See log showing that an array of "false" is returned instead of the array of chat objects

**create() code**
This is the code you use to create the client. e.g
```javascript
create({
    sessionId: sessionId,
    sessionDataPath: sessionDataPath,   
    useChrome: false,
    restartOnCrash: start,
    headless: false,
    throwErrorOnTosBlock: true,
    killTimer: 40,
    autoRefresh: true,
    qrRefreshS: 15, 
    safeMode: true,
    cacheEnabled: false,
    // devtools:true,
    blockCrashLogs: true,
  })
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2025.6',
  PAGE_UA: 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36',
  WA_AUTOMATE_VERSION: '1.9.83',
  BROWSER_VERSION: 'Chrome/83.0.4103.0'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Windows 10 + Linux (same result)

**Additional context**
```
    log.debug(`Request received to resync unread messages`);
    const results = await this.whatsapp.getAllChatsWithMessages(true);

    log.debug(`Found ${results.length} chats with unread messages`);
    log.debug(results);
````

**Logs**
```
[2020-06-25T18:51:24.548] [DEBUG] default - Request received to resync unread messages
[2020-06-25T18:51:24.727] [DEBUG] default - Found 10 chats with unread messages
[2020-06-25T18:51:24.728] [DEBUG] default - [ false, false, false, false, false, false, false, false, false, false ]
```

**Comment by smashah** [comment]
@blackchineykh Thanks for filling out the issue template perfectly. 

Getting new/unread messages is a bit of a mess right now, as there are some old ways to do it and some new ways. Can you try `client.getAllUnreadMessages()`? If that fulfills your needs, I'll deprecate `getAllChatsWithMessages(true)`

**Comment by blackchineykh** [comment]
@smashah the `client.getAllUnreadMessages()` seems to work. Saved me a bit of code too!
Thank you for your continued work on this project

**Comment by smashah** [comment]
My pleasure. I really appreciate that people are using this work even though there are alternatives 🙏
