### ISSUE TITLE
"How to" requests

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#579]
I know the documentation for this library can use some work so please respond to this issue for the "How to" that you'd like to see. Even if the documentation exists already somewhere, if it's not clear to you then the documentation is not good enough. 

E.g

- How do I check if a number is valid?
- How do I decrypt media?

**Comment by mmc16** [comment]
Haven't you considered creating a wiki for this module, since it has an active community, and making a "How To" page there?

**Comment by smashah** [comment]
@mmc16 yes that's exactly the plan but some things seem simple to me but aren't clear to others which is why I want to get users to submit topics that they would like more clarity or a clear guide on

**Comment by jesusvalverde** [comment]
- How to get status of a message send [ one, doble, blue tick ]
- How to manage incoming calls 
- How to get old mesages [ All, some, unread ]
- How to send a image, pdf, ..other files
- How to recive a image, pdf, .. other files
- How to send a location

[Some of my question over my project]

**Comment by mmc16** [comment]
- how to handle disconnection (kill the process, etc.)
- how to: error handling

**Comment by smashah** [comment]
Awesome. Keep them coming all

**Comment by DeLuca92** [comment]
how to handle logout (kill the process and resart )

**Comment by xshion13** [comment]
how to send a different message if someone enter or leaves the current group?

**Comment by tokinaa** [comment]
Anyone know how to send gif sticker?

**Comment by smashah** [comment]
@xshion13 @DeLuca92 @mcavazotti @jesusvalverde Please check out the new docs:

https://open-wa.github.io/wa-automate-nodejs/index.html

This was pretty hard so don't be too hard however make sure to make new issues if you see room for improvement and use the documentation label.

Thanks
