### ISSUE TITLE
Feature: Support sticker decryption (animated + non animated)

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#580]

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.103](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.103-1...1.9.103) (2020-07-21)

- build(deps): bump open from 7.0.4 to 7.1.0 [`#663`](https://github.com/open-wa/wa-automate-nodejs/pull/663)
- build(deps-dev): bump typescript from 3.9.6 to 3.9.7 [`#656`](https://github.com/open-wa/wa-automate-nodejs/pull/656)
- build(deps): bump cfonts from 2.8.5 to 2.8.6 [`#657`](https://github.com/open-wa/wa-automate-nodejs/pull/657)
- Fix client.page reference in readme to the new client.getPage() [`#660`](https://github.com/open-wa/wa-automate-nodejs/pull/660)
- Insiders feature: Implemented `getStickerDecryptable` to decrypt stickers correctly #580 [`031317f`](https://github.com/open-wa/wa-automate-nodejs/commit/031317f3283163ec25fda8ef4b5ecd516fd00112)
- Release 1.9.103 [`202be5f`](https://github.com/open-wa/wa-automate-nodejs/commit/202be5fc20373e542987231ce65bfbfe8019ca6a)

**Comment by smashah** [comment]
You are now able to decrypt sticker's (including animated stickers):

```javascript

      let mediaData;
      if( message.type==='sticker') {
        let stickerDecryptable = await client.getStickerDecryptable(message.id);
        mediaData = await decryptMedia(stickerDecryptable);
      } else {
        mediaData = await decryptMedia(message);
      }
      fs.writeFile(filename, mediaData, function(err) {
        if (err) {
          return console.log(err);
        }
        console.log('The file was saved!');
      });

```

Note: This is an Insider's feature for now and requires a license key.

**Comment by MarsVard** [comment]
can you explain in more detail what this does?

**Comment by smashah** [comment]
@MarsVard  Without this, the decrypt method will result in a transparent empty `webp` file as that is the background of the sticker. 

With `getStickerDecryptable`, the **actual** sticker message is retrieved which will allow the decrypt function to output the sticker (including an animated sticker).
