### ISSUE TITLE
Get list of groups that i'm admin of?

### ISSUE THREAD

**Issue by tinyCoder32** [open-wa/wa-automate-nodejs#584]
Hi, is there a function that queries the groups that I am admin in, without having to loop through all the groups metadatas?

Thanks.

**Comment by smashah** [comment]
@tinyCoder32 I don't think there's any other way to do this but it would be quicker if it was in wapi instead of looping in the client.

**Comment by tinyCoder32** [comment]
I was hoping to find a way other than query 100 or 200 groups metadata members to check if the user is admin there or not.

**Comment by smashah** [comment]
Is there a similar feature to easily see this on WhatsApp itself?

**Comment by tinyCoder32** [comment]
No Mohammed, there is no way as far as I know.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.86](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.85...1.9.86) (2020-06-27)

- Release 1.9.86 [`2465f40`](https://github.com/open-wa/wa-automate-nodejs/commit/2465f40c3824997431acb8e97a2a738b237ba3a4)
- Multiple enhancements #584 [`cfafce1`](https://github.com/open-wa/wa-automate-nodejs/commit/cfafce1cd74171fdb58b2e7a331fad197f02cfb4)

**Comment by smashah** [comment]
From 1.9.86+:

```javascript

//get the groups that host is admin of
await client.iAmAdmin();

//get information about a group using the invite code or link
await client.inviteInfo("https://chat.whatsapp.com/Bw26dSlAFhnIVXdEEtIJ1t")

//Join a group using the invite code or link
await client.inviteInfo("https://chat.whatsapp.com/Bw26dSlAFhnIVXdEEtIJ1t")

```

https://open-wa.github.io/wa-automate-nodejs/classes/client.html#iamadmin
https://open-wa.github.io/wa-automate-nodejs/classes/client.html#inviteinfo

**Comment by tinyCoder32** [comment]
Hi, thanks for your efforts. I think you should also add iAmSuperAdmin(). However, something is wrong there. Out of 25 groups that I am admin of, or creator, it only returned 4 groups, even with using iAmSuperAdmin.

Any suggestions?

**Comment by tinyCoder32** [comment]
I see now, when i click on the groups one by one (in WhatsApp Web), it quires the metadata, then your functions works and count the missing groups.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.91](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.90...1.9.91) (2020-06-28)

- Release 1.9.91 [`4614cf4`](https://github.com/open-wa/wa-automate-nodejs/commit/4614cf439da072798f410edd3b78772e58b8541d)
- Fix: iAmAdmin now loads all possible groups and also checks if super admin #584 [`65ee6fa`](https://github.com/open-wa/wa-automate-nodejs/commit/65ee6fa455715b3fd178c352d9e329e6f7a05652)

**Comment by smashah** [comment]
@tinyCoder32 try now

**Comment by tinyCoder32** [comment]
You're the best, Mohammed.
