### ISSUE TITLE
Feature Request: Missed call

### ISSUE THREAD

**Issue by blackchineykh** [open-wa/wa-automate-nodejs#585]
I used previously another wapi js library that allowed me to get access to the missed calls. This message type is 'call_log' and is received after the caller hangs up. This was useful to maybe trigger responses to a user to advise them to message instead.

Is this something that can be added to the callback for 
```
client.onAnyMessage((message: any) => {
    //do processing here
});
```

Thanks again for the great work!

**Comment by smashah** [comment]
This is working now in v1.9.85
