### ISSUE TITLE
Stuck after WAPI Reinjected

### ISSUE THREAD

**Issue by kresnaputra** [open-wa/wa-automate-nodejs#590]
**Describe the bug**
I try to running with simple code as showing in the Readme.md. But I got stuck after WAPI Reinjected.

**Expected behavior**
Can running simple usage example like on Readme.md

**DEBUG INFO**
(node:2869) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'safeMode' of undefined
    at Object.<anonymous> (/home/gevanni/Documents/Development/NodeJS/AutoTexting/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:240:33)
    at step (/home/gevanni/Documents/Development/NodeJS/AutoTexting/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:63:23)
    at Object.next (/home/gevanni/Documents/Development/NodeJS/AutoTexting/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:44:53)
    at fulfilled (/home/gevanni/Documents/Development/NodeJS/AutoTexting/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:35:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2869) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2869) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Debug Info {
  WA_VERSION: '2.2025.6'
  PAGE_UA: 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36',
  WA_AUTOMATE_VERSION: '1.9.86',
  BROWSER_VERSION:  'HeadlessChrome/83.0.4103.0'
}
```

**Host (please complete the following information):**
 - OS: iOS

**Comment by smashah** [comment]
please share your create code @kresnaputra

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.87](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.86...1.9.87) (2020-06-27)

- Release 1.9.87 [`e267ece`](https://github.com/open-wa/wa-automate-nodejs/commit/e267ece658742a987a89d74beebedb5584f22ec6)
- Massively simplified majority of listeners, register listeners #589 [`9628a28`](https://github.com/open-wa/wa-automate-nodejs/commit/9628a28fed36d43a571228bc6fbc631744ac36e0)
- Feature: Implemented `client.refresh()` #582 [`bc997c5`](https://github.com/open-wa/wa-automate-nodejs/commit/bc997c5decb42947c939b9b9d5587356fba4c391)
- Prelim work for refresh and reinjection #582 [`5abc74b`](https://github.com/open-wa/wa-automate-nodejs/commit/5abc74b529aedbda6152cb094d91d52f21383602)
- Replaced `ExposedFn` with `SimpleListener` #588 [`cb2e132`](https://github.com/open-wa/wa-automate-nodejs/commit/cb2e13237c762c27ca6cd5c410d26ce705a3cde0)
- Using SimpleListener wherever applicable #588 #589 [`279f202`](https://github.com/open-wa/wa-automate-nodejs/commit/279f202288c23e7ab42322c1ab951a928287f375)
- BREAKING: Refactor `AvailableWebhooks` to `SimpleListener` #588 [`a226e80`](https://github.com/open-wa/wa-automate-nodejs/commit/a226e80eb1cf0d62bcbc1848e970803d1e5c2380)
- Migrate `onAck` from middleware to client #588 [`c058eee`](https://github.com/open-wa/wa-automate-nodejs/commit/c058eeef99d5632f522ad29635ad6f1beb28db0b)
- Migrate `onMessage` from middleware to client #588 [`2320773`](https://github.com/open-wa/wa-automate-nodejs/commit/2320773dde8fe5a01072fcdc620e102fecd2dcdd)
- chore: remove redundant code in client [`63e5794`](https://github.com/open-wa/wa-automate-nodejs/commit/63e57947e302a58901ecbdfaf6eaff76713258d3)
- Replaced string function names with `SimpleListener` #588 [`bb10f61`](https://github.com/open-wa/wa-automate-nodejs/commit/bb10f61cba56f42c9fdedce94d8c8103d4d44fea)
- Migrate `onAnyMessage` from middleware to client #588 [`8e811f6`](https://github.com/open-wa/wa-automate-nodejs/commit/8e811f6cb478920dcc02bd89a91ef2c179669338)
- remove redundant code, added sessionInfo model to docs [`e19c5d3`](https://github.com/open-wa/wa-automate-nodejs/commit/e19c5d325afb4361ffc1574bd5af550277db685a)
- Refactor page close listener #582 [`411ab28`](https://github.com/open-wa/wa-automate-nodejs/commit/411ab28454e198f5c05f98fc8435f74023a5616f)
- Commented out middleware script tag #588 [`14904d4`](https://github.com/open-wa/wa-automate-nodejs/commit/14904d4b700ad0d59d9cc44cddbe7e165557d601)
- fix: add missing optional chaining for safemode config #590 [`cfcb136`](https://github.com/open-wa/wa-automate-nodejs/commit/cfcb13613b82b28758ac154fbc4134557944fa4f)
- Export license check url [`eb647ee`](https://github.com/open-wa/wa-automate-nodejs/commit/eb647ee74687a70401701747973749c54898f874)

**Comment by kresnaputra** [comment]
> please share your create code @kresnaputra

`const format = require("date-fns/format");
const wa = require("@open-wa/wa-automate");
const dotenv = require("dotenv");
dotenv.config();

const MEGA = process.env.PHONE_NUMBER;

wa.create().then((client) => start(client));

function calculationTime(client) {
  setInterval(() => {
    if (format(new Date(), "k m s") === "7 0 0") {
      client.sendText(MEGA, "Hello");
    }
  }, 1000);
}

function replyMega(message, client) {
  if (message.body.toLocaleLowerCase().includes("Test"))
    client.sendText(MEGA, "Testing");
}

function start(client) {
  calculationTime(client);

  client.onMessage((message) => {
    // Checking if sender is mega
    if (message.from === MEGA) {
      replyMega(message, client);
    }
  });
}`

I already updated to newest version '1.9.88'

**Comment by smashah** [comment]
wa.create({}).then((client)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.90](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.89...1.9.90) (2020-06-28)

- fix #590 [`#590`](https://github.com/open-wa/wa-automate-nodejs/issues/590)
- Release 1.9.90 [`6c97524`](https://github.com/open-wa/wa-automate-nodejs/commit/6c97524ae1453f814be148a74a4bd4960372f1e2)

**Comment by smashah** [comment]
Should be fixed now

**Comment by kresnaputra** [comment]
> Should be fixed now

Thanks, it's work like charm now
