### ISSUE TITLE
getAllMessagesInChat is wrongfully returning an array of strings (ids), while it should be returning message objects

### ISSUE THREAD

**Issue by feliperaul** [open-wa/wa-automate-nodejs#591]
**Describe the bug**
I just upgraded from 1.9.60 to 1.9.88, and noticed `client.getAllMessagesInChat` is now returning an Array of strings like so:

```
[
  'false_554412345@c.us_3AD01SC8D6515D265736',
  'true_5544123452@c.us_3AD01SC8D6515D265736',
]
```

**Expected behavior**

The documentation states that `getAllMessagesInChat` should return an array of Message objects.

So, in version 1.9.60, I was able to filter the recent messages on the chat sent by me using `const messages = await getAllMessagesInChat(message.from, true); messages.filter(msg => msg.sender.isMe);` now, it's impossible.

I spent 30 minutes trying to pinpoint which commit broke this functionality to no avail, so I couldn't be more precise.

Also, this was not listed as breaking change in the CHANGELOG, so I believe it's a bug.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
✓ Initializing WA
┌─────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                    Values                                                                    │
├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                  '2.2025.6'                                                                  │
│       PAGE_UA       │ 'WhatsApp/0.4.315 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '1.9.88'                                                                   │
│   BROWSER_VERSION   │                                                            'Chrome/83.0.4103.116'                                                            │
└─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Host (please complete the following information):**
 - OS: Mac Os 10.13

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.89](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.88...1.9.89) (2020-06-28)

- Better listener docs [`851ac42`](https://github.com/open-wa/wa-automate-nodejs/commit/851ac4292843deccd1c6f1c13d545a11759dd75a)
- Release 1.9.89 [`971d915`](https://github.com/open-wa/wa-automate-nodejs/commit/971d915b02849cb990e72847b19166de94bdeb50)
- fix: getAllMessagesInChat returning messages again #591 [`9b7ef81`](https://github.com/open-wa/wa-automate-nodejs/commit/9b7ef818c819a8f675f2a4c3e632b3bb5b2d06c0)

**Comment by smashah** [comment]
@feliperaul this is fixed

**Comment by feliperaul** [comment]
@smashah thank you! will try and report back if not fixed. Closing.
