### ISSUE TITLE
Reload Server

### ISSUE THREAD

**Issue by DeLuca92** [open-wa/wa-automate-nodejs#596]
If I connect to my webwhats or disconnect the wa instance from my cell phone it is waiting for an answer, correct?
Is there a method for the console to ask for the qrcode again or if I switched from whats web back to wa?

**Comment by jesusvalverde** [comment]
You can explore the  onStateChange 

client.onStateChanged(state=>{
   ....
 });

**Comment by DeLuca92** [comment]
My console dont show the 
CONFLICT/UNPAIR/  :/

**Comment by jesusvalverde** [comment]
Some alternative method I do USE

When I do try to send a Whta and I do not get the ID  .... an alert signal.
When I do try to get some "me" data, phone, name, ..... other alert signal 

So I do try to make a mix of that whe the conflit / unpair not showing

**Comment by smashah** [comment]
No there's no method to reauthenticate a de-authed session. You should detect it using onStateChange and then restart the process which will go through the authentication again

**Comment by DeLuca92** [comment]
@smashah , Hey.
I find one part of solution.

I think I need chance ```create({sessionId:'test' , executablePath: '/usr/bin/google-chrome', headless:true, throwErrorOnTosBlock:true, killTimer:40, autoRefresh:true, qrRefreshS:15, cacheEnabled:false }).then(client => start(client));```  for a cmd to execute again the file.ts  like  ```ts-node file.ts```?


```node
const stateChanged = state => {
  console.log('statechanged', state)
  if(state==="CONFLICT") globalClient.forceRefocus();
  if(state==="UNPAIRED") {
	  globalClient.kill();
	  create({sessionId:'daniel' , executablePath: '/usr/bin/google-chrome', headless:true, throwErrorOnTosBlock:true, killTimer:40, autoRefresh:true, qrRefreshS:15, cacheEnabled:false }).then(client => start(client));
	}
}


async function start(client: Client) {
  app.use(client.middleware(true));
  globalClient = client;
  client.onStateChanged(stateChanged);
  client.onAnyMessage(wh('any_message'));
  app.listen(PORT, function () {
    console.log(`\n• Listening on port ${PORT}!`);
  });
```

**Comment by smashah** [comment]
This is not a bug. You have to handle a sign out event yourself. Best thing to do is kill/restart the process. Closing.

**Comment by DeLuca92** [comment]
Yes, but If I close the session in my phone the wa dont show any msg.
