### ISSUE TITLE
Client.kill() is killing my node process

### ISSUE THREAD

**Issue by kaykyr** [open-wa/wa-automate-nodejs#613]
Hello!

There are a way to avoid my node script to be killed when I call Client.kill()?

That's a strange behaviour, because sometimes I just want to kill an instance of many instances I have running in the same script.

**Comment by smashah** [comment]
@kaykyr please set this to false https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#killprocessonbrowserclose
