### ISSUE TITLE
Javascript out of memory when reading all unread messages

### ISSUE THREAD

**Issue by abraaocaldas** [open-wa/wa-automate-nodejs#618]
**Describe the bug**
heap limit Allocation failed - JavaScript heap out of memory when reading all unread messages

**Steps to Reproduce**
1. Start Session
2. Try to read all unread messages

**create() code**
Using the sample code from docs 
```javascript
 const unreadMessages = await client.getAllUnreadMessages();
  unreadMessages.forEach(processMessage)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
───────┤
│     WA_VERSION      │                                                                  '2.2027.9'
        │
│       PAGE_UA       │ 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '1.9.94'
        │
│   BROWSER_VERSION   │                                                         'HeadlessChrome/83.0.4103.0'


 1: _onMessage [0000009DA714EB09] [E:\Dev\WhatsNode\node_modules\puppeteer\lib\Connection.js:~67] [pc=000000C338CEE56C](this=0x035e1233ee09 <EventEmitter map = 000000ADD3C4A259>,0x034d828c0119 <Very long string[582838...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7D2B446CF napi_wrap+113583
 2: 00007FF7D2AEF7C6 v8::base::CPU::has_sse+66646
 3: 00007FF7D2AF05C6 v8::base::CPU::has_sse+70230
 4: 00007FF7D33042AE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7D32EC381 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF7D31B88CC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF7D31C3B00 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF7D31C0624 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF7D31B5E23 v8::internal::Heap::CollectGarbage+1283
10: 00007FF7D31B4494 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF7D31DC14F v8::internal::Factory::NewRawTwoByteString+95
12: 00007FF7D30FB356 v8::internal::TimedHistogram::Stop+52294
13: 00007FF7D30FC41C v8::internal::TimedHistogram::Stop+56588
14: 00007FF7D30FB7CA v8::internal::TimedHistogram::Stop+53434
15: 00007FF7D327D521 v8::internal::Builtins::builtin_handle+83297
16: 00007FF7D327DACE v8::internal::Builtins::builtin_handle+84750
17: 00007FF7D375780D v8::internal::SetupIsolateDelegate::SetupHeap+546893
18: 000000C338CEE56C 
```

**Additional context**
I have more than 800K unread messages so ....

**Comment by smashah** [comment]
Haha I love the additional context. I think there's your issue mate. Is that normal though? How long did it take for you to get 800k unreads??

**Comment by abraaocaldas** [comment]
> 
> 
> Haha I love the additional context. I think there's your issue mate. Is that normal though? How long did it take for you to get 800k unreads??

I think the issue in on pupeteer, I'm trying to find out what message is this one that is so huge that can't be read.
To get 800K unreads is pretty fast in fact, in a couple of hours, the problem now is this stupid message that is breaking the app

First I tought that there was a memory issue, like something on gc, but this happen at random times, sometimes just after 10k messages read, sometimes after 100K reads.

**Comment by smashah** [comment]
Try this for now:

https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas

I am working on containerizing this which will separate the browser process from the open-wa process.

**Comment by abraaocaldas** [comment]
> Try this for now:
> 
> https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas
> 
> I am working on containerizing this which will separate the browser process from the open-wa process.

It helps, but just delay the memory problem :/

**Comment by abraaocaldas** [comment]
Found the problem, it's my fault :)

I just forgot to clean the variable after reading a Message
