### ISSUE TITLE
After buy license not start chat with unknown number

### ISSUE THREAD

**Issue by devalexanderdaza** [open-wa/wa-automate-nodejs#619]
Hi @smashah yesterdey and today buy restricted license (10E c/u). I have the license code, but want send message to unknown number, the function .sendText(number, message), return false.

If send message to known number, the response is: true_57320XXXXXXX@c.us_3EB0CCE0B812FEA32220

What is the problem.

Thanks for your help

**Comment by devalexanderdaza** [comment]
Hi. I have solved the problem and it is basically that at the time I registered the number for the license, I prepended the + sign and it does not integrate when doing the license validation.

Thank you very much!

**Comment by smashah** [comment]
@devalexanderdaza great I'll fix that in the back end in about an hour when I get back to the computer

**Comment by smashah** [comment]
Should be working. Please enter the number properly next time to avoid delay. Thanks
