### ISSUE TITLE
sendText not working for start a chat with license key

### ISSUE THREAD

**Issue by dantenol** [open-wa/wa-automate-nodejs#622]
**Describe the bug**
`sendText(...)` doesn't send message to chats without previous messages. 

**Steps to Reproduce**
1. Start the client with a license key
2. `sendMessage(...)` to a non-existing chat (it can be your contact or not)
3. The message wont send and `sendText`returns undefined

Reproduce license-key issue:
1. Start the client **without** a license key
2. `sendMessage(...)` to an existing chat (but with no previous messages)
3. The message is sent and everything works as supposed

**create() code**
This is the code you use to create the client. e.g
```javascript
wa.create({
      killProcessOnBrowserClose: false,
      restartOnCrash: start,
      licenseKey: '...',
      sessionDataPath: './session',
      headless: true, // Headless chrome
      devtools: false, // Open devtools by default
      useChrome: true, // If false will use Chromium instance
      debug: true, // Opens a debug session
      logQR: true,
    }).then((client) => start(client));
```

**Expected behavior**
The function should send the message and start the new chat

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2027.9',
  PAGE_UA: 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36',
  WA_AUTOMATE_VERSION: '1.9.94',
  BROWSER_VERSION: 'Chrome/83.0.4103.116'
}
```

**Host (please complete the following information):**
 - OS: Ubuntu 20.04
- Phone: Moto G7 plus, Android 10

**Additional context**
It works fine for existing contacts **if I don't set the license key**

**Comment by smashah** [comment]
@dantenol can you test something for me.

Does it work the second time you try to `sendText`??

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.95](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.94...1.9.95) (2020-07-04)

- build(deps): bump puppeteer from 4.0.1 to 5.0.0 [`#620`](https://github.com/open-wa/wa-automate-nodejs/pull/620)
- Release 1.9.95 [`420544d`](https://github.com/open-wa/wa-automate-nodejs/commit/420544d963a7e6beba63604033c668330cf28293)
- possible fix for #622 [`2d33a45`](https://github.com/open-wa/wa-automate-nodejs/commit/2d33a4528002450b5bb3eebeaffb80427dfc76b2)

**Comment by jesusvalverde** [comment]
Same error here ,  WA_AUTOMATE_VERSION    '1.9.96'   and a Licence Key (purchase minutes ago).

const wa = require('@open-wa/wa-automate');
wa.create('test',{  licenseKey:........... ", sessionId: 'test' }).then(client => start(client));

async function start(client) {
  console.log("Enviando texto " + await client.sendText('506zzzzzzz0@c.us', 'Hello la prueba llega'));
  console.log("Enviando texto " + await client.sendText('506zzzzz@c.us', 'Hello la prueba llega'));
}


✓ Initializing WA
┌─────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                    Values                                                                     │
├─────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                  '2.2027.9'                                                                   │
│       PAGE_UA       │ 'WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '1.9.96'                                                                    │
│   BROWSER_VERSION   │                                                             'Chrome/83.0.4103.0'                                                              │
└─────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
✓ Authenticated
✓ WAPI Reinjected
✓ Client is ready
✓ Passed Integrity Test
✓ License Valid
Enviando texto false
Enviando texto false

**Comment by dantenol** [comment]
@jesusvalverde does the message get sent afterall? Sometimes my function returns undefined but the message is sent, According to my experience, it indicates that it might not be a valid whatsapp number

**Comment by jesusvalverde** [comment]
Nop....I do own 3 of the whatsaapp s and in the headless: false config of the test any of those number appears on the web.whatsapp and also not in the source phone.

**Comment by dantenol** [comment]
That would be unlikely to solve, but did you try removing `node_modules` and rum `npm i` again?
(PS.: don't forget to skip puppeteer install)

**Comment by smashah** [comment]
@dantenol the update fix it for you? @jesusvalverde can you dm your test numbers on discord so I can test them out

**Comment by smashah** [comment]
Closing for now. DM me for any further help

**Comment by andazlan** [comment]
i am facing this issue, do i need a lisence to solve this issue?
