### ISSUE TITLE
Promise error

### ISSUE THREAD

**Issue by StoicaNicusor** [open-wa/wa-automate-nodejs#623]
`(node:3008) UnhandledPromiseRejectionWarning: Error: No spinner initialized with
 name session_STARTUP
    at Spinnies.setSpinnerProperties (C:\Users\Admin\Documents\whatsapp\wa-autom
ate\node_modules\spinnies\index.js:107:37)
    at Spinnies.succeed (C:\Users\Admin\Documents\whatsapp\wa-automate\node_modu
les\spinnies\index.js:62:10)
    at Spin.succeed (C:\Users\Admin\Documents\whatsapp\wa-automate\node_modules\
@open-wa\wa-automate\dist\controllers\events.js:83:23)
    at Object.<anonymous> (C:\Users\Admin\Documents\whatsapp\wa-automate\node_mo
dules\@open-wa\wa-automate\dist\controllers\initializer.js:238:29)
    at step (C:\Users\Admin\Documents\whatsapp\wa-automate\node_modules\@open-wa
\wa-automate\dist\controllers\initializer.js:63:23)
    at Object.next (C:\Users\Admin\Documents\whatsapp\wa-automate\node_modules\@
open-wa\wa-automate\dist\controllers\initializer.js:44:53)
    at fulfilled (C:\Users\Admin\Documents\whatsapp\wa-automate\node_modules\@op
en-wa\wa-automate\dist\controllers\initializer.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 1)
(node:3008) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.`
Why this error ?

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
