### ISSUE TITLE
UNPAIRED = KIll Create not Works

### ISSUE THREAD

**Issue by DeLuca92** [open-wa/wa-automate-nodejs#642]
**Describe the bug**
When stateChanged show UNPAIRED I kill the process and sleep and create again, but not works.
THe console show me 
Shutting Down

LOGO WA

Shutting Down
Terminal...

**Steps to Reproduce**
1. Scan QR code
2. Wait to login
3. LOgout in your mobile
4. See  in the  console UNPAIRED

**create() code**
This is the code you use to create the client. e.g
```javascript
const stateChanged = state => {
  console.log('statechanged', state)
  if(state==="UNPAIRED"){   
	globalClient.kill();
	 sleep(5000);
	create({sessionId:'teste' , executablePath: '/usr/bin/google-chrome', headless:false, throwErrorOnTosBlock:true, killTimer:40, autoRefresh:true, qrRefreshS:15, cacheEnabled:false }).then(client => start(client));
	}
}
```

**Expected behavior**
KIll the process and open again

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION:   '2.2027.10'  ,
  PAGE_UA: WhatsApp/2.2019.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36,
  WA_AUTOMATE_VERSION: 1.9.97,
  BROWSER_VERSION: Chrome/81.0.4044.129'
}

**Comment by smashah** [comment]
Set this to false in your create config

https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#killprocessonbrowserclose
