### ISSUE TITLE
Error adding contact to group

### ISSUE THREAD

**Issue by GamiDPC** [open-wa/wa-automate-nodejs#648]
> app.post('/addParticipant', (req, res) => {
>   try {
>       you.addParticipant(req.body.groupId, req.body.phone+'@us.c')
>         .then(d => {
>           console.log(d)
> 		  res.json({success: true, addParticipant: d})
>         })
>         .catch(e => {
>           console.log(e)
> 		  res.json({success: true, addParticipant: e})
>         })
>   } catch (error) {
>     res.json({
>       success: false,
>       error
>     })
>   }
> })

![image](https://user-images.githubusercontent.com/17031085/87412729-0a031680-c5d2-11ea-9371-71435e2f1282.png)

It is also not possible to add multiple numbers at the same time when creating a group through a separator
"Number | Number | Number"

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️

**Comment by GamiDPC** [comment]
I don’t understand English, so I can’t arrange it differently ... I will be glad to help
