### ISSUE TITLE
Don't receive file

### ISSUE THREAD

**Issue by MagicLead** [open-wa/wa-automate-nodejs#655]
- Initializing WA
- Initializing WA
┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                           Values                                                            │
├─────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                         '2.2029.4'                                                          │
│       PAGE_UA       │ 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                          '1.9.99'                                                           │
│   BROWSER_VERSION   │                                                    'Chrome/84.0.4147.89'                                                    │
└─────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
- Injecting api
- WAPI injected
- Authenticating
- Authenticated
- Reinjecting api
- WAPI Reinjected
- Checking if session is valid
- Client is ready
- Checking client integrity
- Passed Integrity Test
- 🚀 Ready!
(node:25756) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'split' of undefined
    at Object.window.WAPI.base64ImageToFile (C:\Users\alexandreteixeira\Projetos\git-hub-e-neural\e-neural-whatsapp\node_modules\@open-wa\wa-automate\dist\lib\wapi.js:1684:23)
    at C:\Users\alexandreteixeira\Projetos\git-hub-e-neural\e-neural-whatsapp\node_modules\@open-wa\wa-automate\dist\lib\wapi.js:1532:37
    at K (https://web.whatsapp.com/app.28a86c90d20ffcb7a7cc.js:1:1033337)
    at MutationObserver.W (https://web.whatsapp.com/app.28a86c90d20ffcb7a7cc.js:1:1032918)
    at ExecutionContext._evaluateInternal (C:\Users\alexandreteixeira\Projetos\git-hub-e-neural\e-neural-whatsapp\node_modules\puppeteer\lib\cjs\common\ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:25756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by smashah** [comment]
You clearly did not send the image base64/data URL to the method. Please read the docs. 

https://open-wa.github.io/wa-automate-nodejs/classes/client.html

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
