### ISSUE TITLE
Long Term Backlog

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#659]
This issue is for tracking all features that are not currently possible, not an immediate priority or stale.

**Comment by smashah** [comment]
#636

**Comment by smashah** [comment]
Advanced Search Queries: #469

**Comment by smashah** [comment]
Buttons: #98 

This is currently impossible

**Comment by smashah** [comment]
A serverless function template that processes videos/gifs to animated stickers: https://github.com/open-wa/wa-automate-nodejs/issues/699#issuecomment-673016379

Useful and not rocket science. Just not a high priority. If you really need this then react with a thumbs up to this comment.

**Comment by smashah** [comment]
Sticker metadata: #682 

This is currently impossible until WA Web actually shows sticker information (e.g name).

**Comment by smashah** [comment]
Create `npm init` templates: #750

Not a priority any more.

**Comment by joedutra** [comment]
<img src="https://media.giphy.com/media/sNZddQMtrqpS0HEEMC/giphy.gif"></img>
Man, you know it sucks, how we copy your repo, if we have functions that you don’t even have, all for free, we perform almost every day, I came from Sulla and you too, but if you look at following the week, we redid it all lib again, now you will no longer be able to copy us, you copy and keep saying that we copy, nor compete with you ours and for free and your payment

**Comment by joedutra** [comment]
I come to apologize and say that we have nothing against this, only that they accuse us of copying and we never copied anything, if someone copied it was when someone changed our lib, I apologize and the intention was not to be slandered anymore of copying something we worked on every day. just like you, we will not do that anymore.

**Comment by smashah** [comment]
Authentication hanging promise:[No issue currently]

The needsToScan function races a `waitForFunction` and a `waitForSelector`. needsToScan is itself raced against another function that checks if the session is authenticated. This leads to needsToScan awaiting completion of it's own raced promise throughout the duration of the process. Not good, the authentication logic needs to be rewritten/redesigned. It's not the end of the world but it is pretty stupid. If written correctly with native promises, we can get rid of rxjs completely as a dependency.

**Comment by smashah** [comment]
Implement in-browser ffmpeg wasm https://github.com/ffmpegwasm/ffmpeg.wasm

**Comment by smashah** [comment]
Check if sender saved me as contact in his device: #1107

Not currently possible

**Comment by smashah** [comment]
Releasing some insiders features to GA: #1164 

As we get ready for v4, this library is almost at feature parity (and in some cases more advanced) than WA web. Going forward, GA requests will be prioritised and will be granted as long as there is an incoming insiders feature to replace it. This ensures that insiders get the advanced features for their support and people keep coming up with new ideas for insiders features. Therefore, when a few new insiders features are developed, the ones mentioned in the referenced issue will become GA.

**Comment by smashah** [comment]
Documentation for raspberry pi: #899

Apparently, it works fine as is. This will be picked back up after v4 is released.

**Comment by smashah** [comment]
#1756

**Comment by smashah** [comment]
⬇️

Mult device beta support: #1923

Explaination: https://github.com/open-wa/wa-automate-nodejs/issues/1923#issuecomment-885810793

**Comment by smashah** [comment]
MD stories needs to be fixed eventually:

https://github.com/open-wa/wa-automate-nodejs/issues/2260
