### ISSUE TITLE
ciphertext messages do not include the body or text

### ISSUE THREAD

**Issue by kmirea** [open-wa/wa-automate-nodejs#665]
Greetings

**Describe the bug**
ciphertext messages do not include the body or text. The text can be seen on the phones chat

**Steps to Reproduce**
Unsure, possibly specific to senders device location / keyboard setting ?

The actual message on phone is:- **hi**

The message object as follows (sender number removed):-
```javascript
{
     type: 'ciphertext',
     from: '---------@c.us',
     filelink: null,
     time: 1595050648,
     msg:
     {
          id: 'false_--@c.us_--',
          type: 'ciphertext',
          t: 1595050648,
          notifyName: '',
          from: '----------@c.us',
          to: '-----------@c.us',
          self: 'in',
          ack: -1,
          invis: false,
          isNewMsg: true,
          star: false,
          recvFresh: true,
          broadcast: false,
          mentionedJidList: [],
          isForwarded: false,
          labels: [],
          chatId: '27---------@c.us',
          fromMe: false,
          sender:
          {
               id: '27---------@c.us',
               type: 'in',
               formattedName: '+27 -- --- ----',
               isMe: false,
               isMyContact: false,
               isPSA: false,
               isUser: true,
               isWAContact: true,
               profilePicThumbObj: {},
               msgs: null
          },
          timestamp: 1595050648,
          isGroupMsg: false,
          isMMS: false,
          isMedia: false,
          isNotification: false,
          isPSA: false,
          chat:
          {
               id: '27---------@c.us',
               lastReceivedKey: [Object],
               unreadCount: 0,
               muteExpiration: 0,
               msgs: null,
               kind: 'chat',
               isGroup: false,
               formattedTitle: '+27 -- --- ----',
               contact: [Object],
               groupMetadata: null,
               presence: [Object]
          },
          quotedMsgObj: null,
          mediaData: {}
     }
}
```

**Expected behavior**
I cannot find any reference to ciphertext,  any suggestions where I can look, or where i should add it.  If i can see what the text value is (body) then can analyse the binary / chars or encoding.

**DEBUG INFO**
latest release

**Host (please complete the following information):**
 - OS: Ubuntu 18

**Comment by kmirea** [comment]
Interesting finding - when i fetch same message using "**getAllMessagesInChat**" i get the expected correct result, shows as chat type & has body  The msgId is identical.  This seems to have happened twice.  If there is any more kind of logging or tests i can do to catch it in future, let me know,

`"messages": [
        {
            "id": "false_---------@c.us_A92E2A00EF46459066D3DFF74BD8B17A",
            "body": "Hi",
            "type": "chat",
            "t": 1595050648,`

**Comment by kmirea** [comment]
temp dirty fix im using:
```
CLIENT.onMessage(message => {
  if(message.type == 'ciphertext')
  {
    //console.log(message);
    CLIENT.getAllMessagesInChat(message.chat.id,false,false).then(function(msgs){
      var msgdata = msgs[msgs.length-1];
      if(msgdata.type != 'ciphertext')
      {
        //console.log(msgdata);
        message = msgdata;
      }
    });
  }
});
```

**Comment by smashah** [comment]
@kmirea Everyone usually ignore's `ciphertext` messages. Does the `Hi` message not come up as a text message? Can anyone corroborate this?

**Comment by smashah** [comment]
I'm going to close this for now. Let me know if there is any more info. thanks
