### ISSUE TITLE
how to send image directly

### ISSUE THREAD

**Issue by xshion13** [open-wa/wa-automate-nodejs#677]
i have been using this in other repo:
```
await client.sendImage(
message.from,
'C:/Users/XSHION/Pictures/Capture.PNG',
'Capture.PNG',
'some text'
);
```

but i am moving my project on this but i dont know how to send, i can't understand how to use base64 since i have my pictures stored in folder, anyone can help

**Comment by smashah** [comment]
@xshion13 

Try this:

```javascript
const fs = require('fs').promises;
...

const imgData = await fs.readFile('/path/to/file.jpg',{encoding: 'base64'});

await client.sendImage(
	message.from,
	imgData,
	'Capture.PNG',
	'some text'
);
```

or this could possibly work (I've never tried it on a local file:

```javascript
await client.sendFileFromUrl(
message.from,
'C:/Users/XSHION/Pictures/Capture.PNG',
'Capture.PNG',
'some text'
);
```

Let me know what works for you, if it's the first one I may add it as an option

**Comment by xshion13** [comment]
i think first option will work fine so i tried the second one, because i have some lag working in my server finally i've installed IIS and replaced c:/ route for http:/localhost+imagefolder and now its working fine =P idk if that's the best way atm but will be nice for keep practicing javascript, thanks @smashah

**Comment by smashah** [comment]
Np. Maybe a convenience method just for local files using FS built in would be useful. I'll add it to the to-do list.

**Comment by xshion13** [comment]
hello, sendfilefromurl stopped working for me

**Comment by smashah** [comment]
In the next version you will be able to use file paths

**Comment by guijob** [comment]
@smashah is there no way to still send images using base64?
