### ISSUE TITLE
Sticker API (including setting metadata)

### ISSUE THREAD

**Issue by vsilva472** [open-wa/wa-automate-nodejs#682]
Hi!! Is there one way to set metadata inside a sticker? Like image bellow?

![image](https://user-images.githubusercontent.com/4265802/88713063-18cceb80-d0f1-11ea-895b-117035f2b4e2.png)

**Comment by kevin4dhd** [comment]
Any solution?

**Comment by smashah** [comment]
I'll look into it

**Comment by smashah** [comment]
@vsilva472 WA web gets the generic sticker pack information but nothing specific regarding the sticker (e.g the name). This will not be possible until you can achieve your screenshot in WA web itself.

**Comment by smashah** [comment]
requires `webpmux` as a dependency. The library has too many dependencies as is so this feature will need to be offloaded onto another process entirely.

**Comment by TheAyos** [comment]
@smashah are you working on it ? i think i found a track, an npm library that has no dependencies and that seems to be robust. Could i help ? I definitely can look deeper into it if i have some time ! 😄

**Comment by smashah** [comment]
@TheAyos feature is in development and will be released very soon along with other major changes which will eliminate many dependencies from the library

**Comment by TheAyos** [comment]
@smashah neat ! one question though : does having less dependencies make the library faster ? and btw, great work 👏

**Comment by smashah** [comment]
@TheAyos the simple answer is yes.

There is a CLI with this project and the dependencies make that CLI a pain to load.

Also, I'm always surprised as to the machines and operating systems people decide to run this library on. The less dependencies, the less potential for edge case issues and the less headache for me.

There are some which cannot be avoided, like ffmpeg and chrome/chromium but sharp is not required for every instance.

Another thing is unbundling this library. The sticker logic can be refactored into it's own library, same for the pop-up code. People are asking for some utility functions which can also be set up as its own library.

Unbundling this library will allow for more space/memory saving while also enabling users of the lib to make better bots.

**Comment by smashah** [comment]
Please see this comment for a current implementation of the sticker metadata code

https://github.com/open-wa/wa-automate-nodejs/issues/1233#issuecomment-760991029

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci minor`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.2.0](https://github.com/open-wa/wa-automate-nodejs/compare/3.1.16...3.2.0) (2021-01-25)

- Release 3.2.0 [`cff00f9`](https://github.com/open-wa/wa-automate-nodejs/commit/cff00f915cfc51f89c31dcb0f0b469891e2b411d)
- Feature: Implemented framework for offloading sticker processing to an API #682 [`4204797`](https://github.com/open-wa/wa-automate-nodejs/commit/4204797278a33e03952d3293985aeb2674074db6)

**Comment by smashah** [comment]
in V3.2.0 you can now set sticker metadata

https://docs.openwa.dev/classes/client.html#sendmp4assticker

https://docs.openwa.dev/classes/client.html#sendimageassticker

in `sendImageAsSticker`, the `_m` (3rd) parameter is the [`StickerMetadata`](https://docs.openwa.dev/globals.html#stickermetadata)

The API will remain open without limits over the next day or two. It only outputs SFW stickers.

Please leave feedback. thanks

**Comment by smashah** [comment]
This is implemented and fully working. 

Soon, the API will only process unlimited stickers per day for those with insider's keys.

Closing for now thanks.
