### ISSUE TITLE
Feature Request:  Better Error Management On The Middleware

### ISSUE THREAD

**Issue by DeLuca92** [open-wa/wa-automate-nodejs#683]
When you send a text for a number not your contact the api/Middleware show this error on the post
`
{
    "success": true,
    "response": false
}
`

And the console show  
`
Not a Contact
`

But, when u send a sendGiphy or VideoAsGIf

The post show only
`
{
    "success": true
}
`

The API shows the success: true, because the parameters are corrects, but the  response not show :/

**Comment by smashah** [comment]
Thanks for making an issue @DeLuca92 but I'll just roll this over into #684 as it has more detail 

duplicate #684

**Comment by DeLuca92** [comment]
Thx, bro
