### ISSUE TITLE
Decrypt media. Error: "Request failed with status code 404".

### ISSUE THREAD

**Issue by jazZcarabazZ** [open-wa/wa-automate-nodejs#694]
Hello, there is a question "Request failed with status code 404 after
loading all earlier messages". You answered that "If you're getting all
messages AND decrypting then the old media urls will 404."

But, if the old files are manually loaded through the web interface,
then they become active on the whatsapp servers and in the future these
files can be downloaded using your library!

Actually the question is, is it possible to introduce into the library
the ability to "activate" (so to speak) files on whatsapp servers,
similar to how it is done via the web?

**Comment by smashah** [comment]
@jazZcarabazZ thanks for bringing this up. duplicate #692

**Comment by smashah** [comment]
@jazZcarabazZ please DM me in discord thanks

**Comment by jazZcarabazZ** [comment]
Hello!!! Good to hear from you)

**Comment by jazZcarabazZ** [comment]
How I can discord you?
