### ISSUE TITLE
New feature: getAllChatIds

### ISSUE THREAD

**Issue by dantenol** [open-wa/wa-automate-nodejs#696]
I am pretty sure WAPI already supports it.
There should be a method to return only the array of chatIds, something like `getAllChatIdsa()`.

My workaround at this moment is `await client.getPage().evaluate(() => window.WAPI.getAllChatIds())`.
It is pretty simple and should be implemented on open-wa

**Comment by smashah** [comment]
This will be added to the upcoming version
