### ISSUE TITLE
Memory Leak: onMessage

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#713]
It is highly likely that the way `onMessage` is built is causing memory issues.

wapi.js was developed within a python library [https://github.com/mukulhase/WebWhatsapp-Wrapper/blob/master/webwhatsapi/js/wapi.js] and the `onMessage` functionality was probably built more than 2 years ago - all this to say that `onMessage` may not be optimized for memory efficiency.

There are some possible fixes to this and eventually the massive memory consumption some users deal with.

If you've had issues with massive memory consumption please respond to this issue with your experience.

**Comment by manojsitapara** [comment]
I am also facing same issue, for my case I have minimum 10 whatsapp users, all 10 users posting messages in their selected groups.

This consume use memory and also CPU.

**Comment by smashah** [comment]
Closing for now.
