### ISSUE TITLE
 SEND AUDIO RECORDING DIRECTLY FROM HTML

### ISSUE THREAD

**Issue by petryck** [open-wa/wa-automate-nodejs#721]
I'm having trouble sending audio, when I record the audio on the client side with javascript and convert it to base64 when I send it to the server it understands it as a document, in theory I believe the problem is in the encoding of the format when I record the audio on the web, can you help me?
sorry for English...

**Comment by smashah** [comment]
@petryck are you using this: https://open-wa.github.io/wa-automate-nodejs/classes/client.html#sendptt?

**Comment by petryck** [comment]
> @petryck você está usando isto: https://open-wa.github.io/wa-automate-nodejs/classes/client.html#sendptt ?

yes, front javascript 

const blob = new Blob(chunks, { type:'audio/ogg; codecs=opus'})

reader.readAsDataURL(blob)
reader.onloadend = () => {
      socket.emit('send_audio', reader.result);
      
    }

it sends, however in document.

**Comment by petryck** [comment]
`let mediaRecorder

  
  navigator
  .mediaDevices
  .getUserMedia({audio: true})
  .then( stream => {
    mediaRecorder = new MediaRecorder(stream)

    mediaRecorder.mimeType;
    let chunks = []
    mediaRecorder.ondataavailable = data => {
      chunks.push(data.data)
    }
    mediaRecorder.onstop = () => {
      console.log(chunks)
      const blob = new Blob(chunks, { type:'audio/ogg; codecs=opus'})
      const reader = new window.FileReader();
      reader.readAsDataURL(blob)
      reader.onloadend = () => {

        socket.emit('envio_audio', reader.result);

      }
    }
   
     
  }, err =>{
      console.log(err)
  })
`

**Comment by petryck** [comment]
`
let mediaRecorder

  
  navigator
  .mediaDevices
  .getUserMedia({audio: true})
  .then( stream => {
    mediaRecorder = new MediaRecorder(stream)

    mediaRecorder.mimeType;
    let chunks = []
    mediaRecorder.ondataavailable = data => {
      chunks.push(data.data)
    }
    mediaRecorder.onstop = () => {
      console.log(chunks)
      const blob = new Blob(chunks, { type:'audio/ogg; codecs=opus'})
      const reader = new window.FileReader();
      reader.readAsDataURL(blob)
      reader.onloadend = () => {

        socket.emit('envio_audio', reader.result);

      }
    }
   
     
  }, err =>{
      console.log(err)
  })


`

**Comment by petryck** [comment]
let mediaRecorder

  
  navigator
  .mediaDevices
  .getUserMedia({audio: true})
  .then( stream => {
    mediaRecorder = new MediaRecorder(stream)

    mediaRecorder.mimeType;
    let chunks = []
    mediaRecorder.ondataavailable = data => {
      chunks.push(data.data)
    }
    mediaRecorder.onstop = () => {
      console.log(chunks)
      const blob = new Blob(chunks, { type:'audio/ogg; codecs=opus'})
      const reader = new window.FileReader();
      reader.readAsDataURL(blob)
      reader.onloadend = () => {

        socket.emit('envio_audio', reader.result);

      }
    }
   
     
  }, err =>{
      console.log(err)
  })

**Comment by smashah** [comment]
@petryck 

hmm, can you save the file you've made and attach it here please

**Comment by petryck** [comment]
[rec.zip](https://github.com/open-wa/wa-automate-nodejs/files/5076131/rec.zip)



follows files for recording audio in javascript, I'm trying to send this output in base64 but it is sending in doc format.

**Comment by petryck** [comment]
I just found out that chrome doesn't accept

mediaRecorder = new MediaRecorder (stream, {mimeType: 'audio / ogg; codecs = opus'})


only


mediaRecorder = new MediaRecorder (stream, {mimeType: 'audio / webm; codecs = opus'})


with the first function it is possible to send the audio to whatsapp with the second in chrome no, I don't know what to do

**Comment by petryck** [comment]
I managed to solve the recording by chrome / chromium and conversion to ogg to send audio, is there anything you can do to send as audio and not as if it were being forwarded?

**Comment by dantenol** [comment]
yes, on the docs there's the function `sendPtt()`. By the way, i'm also interested on how did you do it. Do you mind sharing a snippet?

**Comment by smashah** [comment]
> is there anything you can do to send as audio and not as if it were being forwarded?

can you share a screenshot of this please @petryck

**Comment by smashah** [comment]
Is it just me or are the PTT messages not being received by the recipient device??

**Comment by dantenol** [comment]
No they aren't even sent

**Comment by smashah** [comment]
@dantenol @petryck This is now working as expected in the latest version. 

Test it using: https://pastebin.com/raw/rBvnrSTw

Closing
