### ISSUE TITLE
Ongoing: Host notification translations

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#743]
Please comment translations of the host notification in the following format:

`en-gb`:
1. `Your account is currently being controlled by an automation service. If you have not authorized this then please "Log out from all devices" in the "WhatsApp Web" section of this app.`
2. `This is the estimated location of the service. It may be behind a proxy. The ip address is`

Note: Make sure the country code (en-gb in the example above) is a [ISO 639-1 language code](https://www.andiamo.co.uk/resources/iso-language-codes/).

Learn more at #709

**Comment by smashah** [comment]
For example:

`pt-br`
1.`Sua conta está sendo utilizada por um serviço de automação. Se você não autorizou isso, saia de todos os dispositivos, na sessão "WhatsApp Web" do aplicativo.`
2. `Esta é a localização estimada do serviço. Pode estar atrás de um proxy. O endereço IP é`

**Comment by rathmerdominik** [comment]
`de-DE`
1.`Dein Account wird derzeitigt von einem Automatisierungsdienst kontrolliert. Solltest du diesem nicht zugestimmt haben, dann gehe bitte in der "WhatsappWeb" Sektion der App auf "Von allen Geräten abmelden"`
2.`Dies hier ist der ungefähre Standort, wo sich der Service befindet. Dieser kann sich hinter einer Proxy befinden. Dies ist die IP Adresse:`

**Comment by jesusvalverde** [comment]
es-*

[All Spanish language] 

Su cuenta está actualmente controlada por un servicio de automatización. Si no ha autorizado esto, "Cierre sesión en todos los dispositivos" en la sección "WhatsApp Web" de esta aplicación.
Esta es la ubicación estimada del servicio. Puede estar detrás de un proxy. La dirección IP es :

**Comment by smashah** [comment]
@jesusvalverde @rathmerdominik both should be ready to use without needing to upgrade to a new version

```
{
	hostNotificationLang: 'de-de'
//or
	hostNotificationLang: 'es'
}
```

**Comment by haqiramadhani** [comment]
`id-id`:

1. `Akun Anda sedang dikendalikan oleh bot. Jika Anda tidak melakukannya Anda bisa "Keluar dari semua perangkat" yang ada di bagian "WhatsApp Web" di aplikasi ini.`
2. `Perkiraan lokasi bot. Ini bisa saja menggunakan proxy. Alamat IP-nya adalah`

**Comment by darkash** [comment]
> `id-id`:
> 
> 1. `Akun Anda sedang dikendalikan oleh bot. Jika Anda tidak melakukannya Anda bisa "Keluar dari semua perangkat" yang ada di bagian "WhatsApp Web" di aplikasi ini.`
> 2. `Perkiraan lokasi bot. Ini bisa saja menggunakan proxy. Alamat IP-nya adalah`

I think it can be reworded with:
```
1. Akun Anda sedang dikendalikan oleh bot. Jika Anda tidak pernah mengijinkannya, Pilih "Keluar dari semua perangkat" yang berada di bagian menu "WhatsApp Web" aplikasi ini.
2. Lokasi bot ini hanyalah perkiraan. Mungkin saja menggunakan proxy. Alamat IP-nya adalah
```

**Comment by roysG** [comment]
This message is coming from the plugin or whatsapp?

**Comment by roysG** [comment]
How do i hide this message?

**Comment by smashah** [comment]
It's not possible to disable this message @roysG

**Comment by smashah** [comment]
`id-id` translation added.

**Comment by roysG** [comment]
Sometimes the qr code scanned good but the whatsapp is not connected.

Is this known issue?

Or maybe there is a solution?

**Comment by smashah** [comment]
@roysG That sounds like a separate issue. Can you fill an issue template, please? Thanks

**Comment by Claxl** [comment]
it-it
1. Il tuo account sembra essere controllato da un sistema di automatizzazione. Se non hai autorizzato qusto "Effettua il log out da tutti i device" nella sezione "WhatsApp Web" dell'applicazione
2. Questa è la posizione approssimativa del servizio. Potrebbe essere un proxy. L'indirizzo ip è

**Comment by smashah** [comment]
@Claxl  `it-it` added

**Comment by joedutra** [comment]
<img src="https://media.giphy.com/media/sNZddQMtrqpS0HEEMC/giphy.gif"></img>
Man, you know it sucks, how we copy your repo, if we have functions that you don’t even have, all for free, we perform almost every day, I came from Sulla and you too, but if you look at following the week, we redid it all lib again, now you will no longer be able to copy us, you copy and keep saying that we copy, nor compete with you ours and for free and your payment

**Comment by joedutra** [comment]
I come to apologize and say that we have nothing against this, only that they accuse us of copying and we never copied anything, if someone copied it was when someone changed our lib, I apologize and the intention was not to be slandered anymore of copying something we worked on every day. just like you, we will not do that anymore.

**Comment by basboot** [comment]
```nl, or nl-nl:```

1. ```Uw account wordt op het moment beheerd door een geautomatiseerd proces. Als u hier geen toestemming voor heeft gegeven, selecteer dan "Uitloggen" in de app op uw device voor dit proces bij "Gekoppelde apparaten".```
2. ```De locatie van dit proces is geschat en kan afwijken als het bijvoorbeeld achter een proxy zit. Het ip adres is```

**Comment by lascimmia** [comment]
`it-it`:

1. `Il tuo account è attualmente controllato da un servizio automatico. Se non sei stato tu ad autorizzarlo, vai in "WhatsApp Web" (oppure "Dispositivi Collegati") e disconnettiti da tutti i dispositivi elencati.`
2. `Questa è la posizione (stimata) del servizio automatico; potrebbe trovarsi dietro un proxy. L'indirizzo IP è`

**Comment by lascimmia** [comment]
> @Claxl `it-it` added

I'm sorry, I didn't see that 😞

**Comment by smashah** [comment]
@basboot available in latest version thanks

**Comment by TVARecordings** [comment]
**nl** (according to ISO 639-1 Standard language codes) for Dutch

1: Uw account wordt momenteel beheerd door een automatiseringsservice. Als u hier geen toestemming voor hebt gegeven, log dan uit op alle apparaten in de sectie 'WhatsApp Web' van deze app.

2: Dit is de geschatte locatie van de service. Het kan zich achter een proxy bevinden. Het IP-adres is

**nl-be** for Belgium:

1: Uw account wordt momenteel beheerd door een automatiseringsservice. Als u hier geen toestemming voor hebt gegeven, gelieve dan uit te loggen op alle toestellen in de sectie 'WhatsApp Web' van deze app

2: Dit is de geschatte locatie van de service. Het kan achter een proxy liggen. Het IP-adres is
