### ISSUE TITLE
Cannot read property 'stickerSendOrigin' of undefined

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#744]
After update to 2.0.3 i find this error when running sendImageAsSticker

```
[ERROR] Error: Evaluation failed: TypeError: Cannot read property 'stickerSendOrigin' of undefined
    at https://web.whatsapp.com/app2.b1418e7fa3daad670335.js:2:805421
    at z (https://web.whatsapp.com/app.4fa7407870a8bad3cbd3.js:1:1192666)
    at MutationObserver.H (https://web.whatsapp.com/app.4fa7407870a8bad3cbd3.js:1:1192247)
    at ExecutionContext._evaluateInternal (C:\xampp\htdocs\Test2\imageToSticker\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (C:\xampp\htdocs\Test2\imageToSticker\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
```

**Comment by mukhlisakbr** [comment]
I also experienced the same thing

![image](https://user-images.githubusercontent.com/27577560/91275317-305bca80-e7aa-11ea-8cb1-fbfb0e8c8604.png)

**Comment by smashah** [comment]
@mukhlisakbr @dandyraka when does this happen?

**Comment by mukhlisakbr** [comment]
> @mukhlisakbr @dandyraka what WhatsApp version is this happening on? Need the logs

I use version 2.20.197.17

**Comment by dandyraka** [comment]
> @mukhlisakbr @dandyraka what WhatsApp version is this happening on? Need the logs

v2.20.157

**Comment by smashah** [comment]
@dandyraka @mukhlisakbr I mean whatsapp web version, it should show up in the logs when launching

**Comment by mukhlisakbr** [comment]
> @dandyraka @mukhlisakbr I mean whatsapp web version, it should show up in the logs when launching

wa version 2.2035.12

**Comment by dandyraka** [comment]
> @dandyraka @mukhlisakbr I mean whatsapp web version, it should show up in the logs when launching

oh sorry, v2.2035.12

**Comment by smashah** [comment]
Got it. Patch on the way

**Comment by smashah** [comment]
@dandyraka @mukhlisakbr The new patch should propagate in about 5 minutes, so restart the process in like 6 minutes and try again

**Comment by mukhlisakbr** [comment]
> @dandyraka @mukhlisakbr The new patch should propagate in about 5 minutes, so restart the process in like 6 minutes and try again

I've tried and it works well now

**Comment by dandyraka** [comment]
> @dandyraka @mukhlisakbr The new patch should propagate in about 5 minutes, so restart the process in like 6 minutes and try again

it works, thank you!
