### ISSUE TITLE
Can't run easy API using npx after update

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#745]
NPX 6.14.5
NODE 14.5.0
NPM 6.14.5

Tested on Mac OS Catalina and Ubuntu Linux 20.04 LTS.

Got this error: Unexpected token '...'

![Captura de Tela 2020-08-26 às 08 24 53](https://user-images.githubusercontent.com/12688324/91297993-a0039280-e775-11ea-8216-89c16ad8c78f.png)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [2.0.4](https://github.com/open-wa/wa-automate-nodejs/compare/2.0.3...2.0.4) (2020-08-26)

- Release 2.0.4 [`0cddbea`](https://github.com/open-wa/wa-automate-nodejs/commit/0cddbea675af9ca648fe5ee33466b884081f443f)
- Feature: `sessionData` base64 string  can now be set as environmental variable when `inDocker` is `true`. `WA_SESSION_DATA` [`92662ac`](https://github.com/open-wa/wa-automate-nodejs/commit/92662ac45aef38f86a4b1bba6d0d5b310e561837)
- added `de-de` and `es` host notification translations #743 [`40c266f`](https://github.com/open-wa/wa-automate-nodejs/commit/40c266f988f4eedfb88b583b783b044d4479acb1)
- removed `patches.json` from npm package [`87ad855`](https://github.com/open-wa/wa-automate-nodejs/commit/87ad8551ac01342ac45b72c518b159243e4e63fe)
- Remove `sessionData` description to prevent `...` issue #745 [`acf0eae`](https://github.com/open-wa/wa-automate-nodejs/commit/acf0eae00897291f8968a6cc8e8c29dfa559bc01)
- patches update [`16284e0`](https://github.com/open-wa/wa-automate-nodejs/commit/16284e0b82eddcc2c712e1af5d3d839b343db136)
- Patch: Fix `stickerSendOrigin` issue when sending sticker #744 [`8bd4720`](https://github.com/open-wa/wa-automate-nodejs/commit/8bd4720ab8c5c36c944566e96627668c202c1454)
- Added links to readme [`2e62066`](https://github.com/open-wa/wa-automate-nodejs/commit/2e6206639ed4116be817512f6371c62c4830f66b)

**Comment by smashah** [comment]
@silvaartur please let me know if this is now working for you. Thanks

**Comment by silvaartur** [comment]
Working, tks!
