### ISSUE TITLE
Feature request: get QR using Easy API

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#747]
It's very helpful if we can get QR code using "easy api".

**Comment by smashah** [comment]
How do you mean? It already asks you to scan the QR code

**Comment by silvaartur** [comment]
Sorry, I explain. At moment QR can be scanned only from the terminal. The request is for a API method to get base64 of the QR, so I can scan anywhere.

**Comment by smashah** [comment]
@silvaartur  Try with `--pop-up`

**Comment by nrs1022** [comment]
Hi @smashah is it possible to run @open-wa with npx in non-headless mode so I scan QR from Chrome? I've tried with --pop-up but seems to not to cause any effect... I'm new on @open-wa, maybe headless mode is hardcoded on?

P.S. Very good work with Easy-API and @open-wa of course!!!

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [2.0.6](https://github.com/open-wa/wa-automate-nodejs/compare/2.0.5...2.0.6) (2020-08-27)

- Release 2.0.6 [`3e988eb`](https://github.com/open-wa/wa-automate-nodejs/commit/3e988eb4d3c02996b6e5ac47e4bb198f1c6f7ecf)
- Fix: `popup` config now working in `npx` [`12a75fe`](https://github.com/open-wa/wa-automate-nodejs/commit/12a75fe719f15d91658959488f248c73597578e6)

**Comment by smashah** [comment]
@nrs1022 @silvaartur sorry it's `--popup` not `--pop-up`

**Comment by nrs1022** [comment]
Thank you very much @smashah !!!

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [2.0.8](https://github.com/open-wa/wa-automate-nodejs/compare/2.0.7...2.0.8) (2020-08-28)

- Release 2.0.8 [`3a3504c`](https://github.com/open-wa/wa-automate-nodejs/commit/3a3504c65dbcf422bb4fd994eb460fc48735e7d2)
- Feature: Get QR Code as png file via popup api on launch #747 [`4ceec04`](https://github.com/open-wa/wa-automate-nodejs/commit/4ceec042dada3eaaac95cd91f31476525bae4e14)
- Patched: Fixed `waitForId` delay, now able to send files to broadcasts #718 and #752 [`8924c08`](https://github.com/open-wa/wa-automate-nodejs/commit/8924c0858c2bb7d8923b7db1e53f0f7422f514ad)

**Comment by smashah** [comment]
@silvaartur @nrs1022 

In the upcoming update, you'll be able to `GET` the QR Code PNG file when using `--popup`.

If you want to set it on a specific port, use `--popup-port`.

By default, the popup is on port 3000. So you can get the QR code using:

```
http://localhost:3000/qr
```

It won't automatically update like the base popup path but you can keep refreshing it to get the latest QR code.

**Comment by smashah** [comment]
@silvaartur @nrs1022 in 2.0.17 both popup and API are now on the same port. `--popup-port` is now deprecated. As soon as the initialization process is complete, the popup endpoints will stop working entirely
