### ISSUE TITLE
sendFileFromUrl not returning message id

### ISSUE THREAD

**Issue by priteshpmehta** [open-wa/wa-automate-nodejs#752]
**Bug**
sendFileFromUrl not returning message id when you pass "waitForId as true". Before It was taking a few seconds to retreive to the key of the message. Now it takes forever but doesn't return anything.. may be it stuck there.

**sendFileFromUrl(to: ChatId, url: string, filename: string, caption: Content, quotedMsgId?: MessageId, requestConfig?: any, waitForId?: boolean): Promise<any>**

This is the code
```javascript
await client.sendFileFromUrl('xxx@c.us', 'https://i.giphy.com/media/oYtVHSxngR3lC/200w.mp4', 'video.mp4', 'xxxxx', null, null, true).then((serialized) => {
        console.log(`sendFileFromUrl has serialized ${serialized}\n`);
    }, (err) => {
        console.log(`sendFileFromUrl has error ${err}\n`);
    });
```

**Expected behavior**
It should return the id of the message. e.g: true_xxx@c.us_3XXXXF7BF8AXXXX7376D.

**DEBUG INFO**
```
Debug Info {
  WA_VERSION: '2.2035.14',
  PAGE_UA: 'WhatsApp/2.2029.4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Sa
fari/537.36',
  WA_AUTOMATE_VERSION: '2.0.6',
  BROWSER_VERSION: 'Chrome/84.0.4147.125'
}
```

**Host:**
 - OS: Windows

**Comment by smashah** [comment]
@priteshpmehta Can you please try again in like 6 minutes and report back if it is fixed for you. Thanks

**Comment by priteshpmehta** [comment]
Yes it is fixed @smashah . Thanks for support.

**Comment by priteshpmehta** [comment]
Hi,

Facing same issue again..
