### ISSUE TITLE
Question: Can we add new products to whatsapp business?

### ISSUE THREAD

**Issue by roysG** [open-wa/wa-automate-nodejs#754]
**Describe the bug**

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
It is possible to hijack an existing product in the business account's catalog and add a custom description, price, etc. Possibly a custom image too.

But from spending all day on this, and using a development version, I was not able to add products into the business account catalog.

Seems like creating new products is not in the near future for WAweb (but maybe editing products is coming soon).

I'll implement this custom product method for now.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [2.0.9](https://github.com/open-wa/wa-automate-nodejs/compare/2.0.8...2.0.9) (2020-08-31)

- Release 2.0.9 [`164f205`](https://github.com/open-wa/wa-automate-nodejs/commit/164f205a3fc3a1665c4f94fe3d97ddafeaee9912)
- Most client methods now correctly typed #759 [`561657a`](https://github.com/open-wa/wa-automate-nodejs/commit/561657af176180ad7809b266d85f1ef24c44cd00)
- Feature: [Premium] Implemented `sendCustomProduct` #754 [`6c1d7c5`](https://github.com/open-wa/wa-automate-nodejs/commit/6c1d7c59aa50bfad42d86ff8315642490853be08)
- Fix: remove logging namespace on every event [`ed583ac`](https://github.com/open-wa/wa-automate-nodejs/commit/ed583acc1b0a94b79d8ccd2e8aa533231ebd2f2a)
- Feature: Implemented `getMessageReaders` #756 [`d36a5e6`](https://github.com/open-wa/wa-automate-nodejs/commit/d36a5e6c3c27e77cced9da01fb2eda8ed94e7e68)
- Fix: Better error handling on sending files Send a image / file / to a non contact #684 [`1b81862`](https://github.com/open-wa/wa-automate-nodejs/commit/1b8186226d8d06ceaa062b85a76fe2905aa9bf1a)
- Docs: Fixed `Client.decryptMedia` documentation [`073270d`](https://github.com/open-wa/wa-automate-nodejs/commit/073270df5291ef7b0a21d4be4979ab97645da17d)

**Comment by smashah** [comment]
@roysG This feature (sending a custom product) is now implemented.

For now, this feature is restricted to premium key holder and then will be available to restricted key holders later on.

As you've brought up the issue please contact me on discord for a temporary key to test try out the feature.

**Comment by roysG** [comment]
First thanks,
This good option to suggest customer, 
But i also meant if  i have the option to upload new product

is this possible too?

**Comment by smashah** [comment]
As I mentioned previously. This is not currently possible
