### ISSUE TITLE
Feature Request: Get all message reader on group

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#756]
**Describe the bug**

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/18587059/91656746-3bce2f00-eae5-11ea-899b-204a50d204d6.png)
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**
It is possible to get all message reader on group?

**Comment by smashah** [comment]
@dandyraka Implemented in v2.0.9

**Comment by dandyraka** [comment]
> @dandyraka Implemented in v2.0.9
> 
> https://open-wa.github.io/wa-automate-nodejs/classes/client.html#getmessagereaders

can it be used at this time?

**Comment by smashah** [comment]
@dandyraka you should be able to use it in the latest version

**Comment by dandyraka** [comment]
> @dandyraka you should be able to use it in the latest version

i try it show empty array, maybe you forgot to update wapi.js I think

```
│     WA_VERSION      │                                                                  '2.2035.14'
│       PAGE_UA       │ 'WhatsApp/2.2029.4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                    '2.0.9'
│   BROWSER_VERSION   │                                                        'HeadlessChrome/84.0.4147.135'
```
![image](https://user-images.githubusercontent.com/18587059/91700980-d63f7880-eba0-11ea-89f4-6630f80c9017.png)

**Comment by smashah** [comment]
@dandyraka try again in like 5 minutes
