### ISSUE TITLE
Error 415 when try to send image/video file using proxy

### ISSUE THREAD

**Issue by roysG** [open-wa/wa-automate-nodejs#757]
**Describe the bug**
When sending image/video i get this error:

Failed to load resource: the server responded with a status of 415 (Unsupported Media Type)

**Steps to Reproduce**
1. send image
2. see the error.

**create() code**
This is the code you use to create the client. e.g
```javascript
 const client = await create({
            autoRefresh:true, //default to true
            qrRefreshS:60,
            //useChrome: true,
            executablePath: process.platform === 'linux' ? "/usr/bin/google-chrome" : "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
            headless: process.platform === 'linux' ? true : false,
            proxyServerCredentials:{
                address:this.server.proxy.ip+':'+this.server.proxy.port,
                username:this.server.proxy.username,
                password:this.server.proxy.password
            },
            disableSpins: true,
            sessionId:'session_'+this.ip
        });
```

**Expected behavior**
The image/video should be sent

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```bash
┌─────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                    Values                                                                     │
├─────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                  '2.2035.14'                                                                  │
│       PAGE_UA       │ 'WhatsApp/2.2029.4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                    '2.0.8'                                                                    │
│   BROWSER_VERSION   │                                                             'Chrome/81.0.4044.92'                                                             │
└─────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

```

**Host (please complete the following information):**
 - OS: Macbook pro

**Comment by smashah** [comment]
@roysG Based on the error the file type was unsupported. Not related to open-wa

**Comment by roysG** [comment]
I uploaded regular jpg file, I can also send the base64

**Comment by roysG** [comment]
I also tried with mp4 file and the error was th same, please check that you
can send image

I will also paste the bse64 file

**Comment by smashah** [comment]
@roysG please send the dataurl using pastebin

**Comment by roysG** [comment]
https://ctxt.io/2/AAAgwLUPFA

**Comment by smashah** [comment]
@roysG This file is working perfectly fine for me.

You will need to share the rest of your code surrounding the `sendImage` to figure out what's going wrong.

**Comment by roysG** [comment]
Sorry, wrong image, try this one:
https://pastebin.pl/

**Comment by roysG** [comment]
Sorry, wrong image
Please try this one: https://ctxt.io/2/AAAgwIMeFA

**Comment by roysG** [comment]
You can also try this video base64
https://ctxt.io/2/AAAgRAhCFA

**Comment by roysG** [comment]
The error of 512 is happen even i try to upload video from the whatsapp upload video file
I do my tests on browser version: 81.0.4044.92

When i am trying to use with the latest chrome browser, i get these errors:

https://ibb.co/ChN2Q1d

Please tell me, what browser version should i use, what i miss?

A week ago everything was fine

**Comment by smashah** [comment]
@roysG please use Pastebin in the future. These two files are working fine also.

**Comment by smashah** [comment]
@roysG Looks like CORS is causing issues again. for some reason this happens sometimes. 

I tested on Chrome/84.0.4147.135.

You should upgrade your chrome on your machine or if that doesn't work set `bypassCSP` to true

https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#bypasscsp

**Comment by roysG** [comment]
I am using the latest version of chrome: 85.0.4183.83 (Official Build) (64-bit)
I added bypassCSP:true

But still i get all the cors error messages

**Comment by roysG** [comment]
I also tried with version:  84.0.4147.135,
Still have the cors problem,

https://ibb.co/x5ftTpF

**Comment by smashah** [comment]
Related: https://github.com/open-wa/wa-automate-nodejs/issues/503

**Comment by smashah** [comment]
@roysG Can you try without the proxy

**Comment by roysG** [comment]
Works!
But i need to use proxy, what should i do?

**Comment by smashah** [comment]
@roysG use a different proxy. Try luminati using this link:

https://luminati.io/?affiliate=ref_5f1b9ae8c7669177abfd9fb8

I've tested and it works fine. Eventually you can upgrade to the residential package

**Comment by roysG** [comment]
I used in the past in luminati, i need to pay them by usage, they are expensive.

What is different if i buy proxy v4 in their company or others?

**Comment by roysG** [comment]
I also tried to to it with luminati ip and i get the same error.

**Comment by roysG** [comment]
The problem is not connect to the type company of proxy, 
what may be the other options?

**Comment by smashah** [comment]
Do you need to use a proxy? Apparently some people are using the library just fine with 10+ clients on one machine

**Comment by roysG** [comment]
So why i have cors erros with proxy, please suggest for me some solution

**Comment by roysG** [comment]
If you need more information, just tell me

**Comment by smashah** [comment]
@roysG which proxy service are you using?

**Comment by roysG** [comment]
proxy6.net - ipv 4

**Comment by roysG** [comment]
I checked it with clean puppeter browser and added proxy connection.
The image and video send with no problem of cors.

FYI.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [2.0.10](https://github.com/open-wa/wa-automate-nodejs/compare/2.0.9...2.0.10) (2020-09-01)

- build(deps): bump puppeteer-extra-plugin-devtools from 2.2.12 to 2.2.14 [`#727`](https://github.com/open-wa/wa-automate-nodejs/pull/727)
- build(deps): bump puppeteer-extra-plugin-stealth from 2.4.14 to 2.6.1 [`#740`](https://github.com/open-wa/wa-automate-nodejs/pull/740)
- build(deps): bump update-notifier from 4.1.0 to 4.1.1 [`#725`](https://github.com/open-wa/wa-automate-nodejs/pull/725)
- build(deps): bump rxjs from 6.6.0 to 6.6.2 [`#691`](https://github.com/open-wa/wa-automate-nodejs/pull/691)
- build(deps-dev): bump typedoc from 0.17.8 to 0.18.0 [`#705`](https://github.com/open-wa/wa-automate-nodejs/pull/705)
- build(deps): bump ts-json-schema-generator from 0.70.2 to 0.72.1 [`#738`](https://github.com/open-wa/wa-automate-nodejs/pull/738)
- build(deps-dev): bump @types/node from 14.0.25 to 14.6.2 [`#761`](https://github.com/open-wa/wa-automate-nodejs/pull/761)
- build(deps-dev): bump release-it from 13.6.5 to 13.7.0 [`#762`](https://github.com/open-wa/wa-automate-nodejs/pull/762)
- build(deps): bump meow from 7.0.1 to 7.1.1 [`#763`](https://github.com/open-wa/wa-automate-nodejs/pull/763)
- build(deps): bump p-queue from 6.6.0 to 6.6.1 [`#726`](https://github.com/open-wa/wa-automate-nodejs/pull/726)
- Release 2.0.10 [`baf958b`](https://github.com/open-wa/wa-automate-nodejs/commit/baf958bd61f16af412d7ed6a4d741cf1eef75741)
- Fix: Implemented `corsFix` #757 [`20b6874`](https://github.com/open-wa/wa-automate-nodejs/commit/20b68741268e0c908b54d0475c8e2a8ec3d5f28a)
- Fix: #760 `sendLinkWithAutoPreview` now returns message Id [`44cb058`](https://github.com/open-wa/wa-automate-nodejs/commit/44cb0585af6680f7587cd6012925ac935f76721a)
- fix: Make `getMessageReaders` find the message before querying readers #756 [`301a712`](https://github.com/open-wa/wa-automate-nodejs/commit/301a7126a04442d230c73f583608e4db70b771cd)
- Docs: fix `forceStaleMediaUpdate` docs [`106c88a`](https://github.com/open-wa/wa-automate-nodejs/commit/106c88ade2c2e980c725cb4b842d84a4b0f6183e)

**Comment by smashah** [comment]
@roysG 

Please set `corsFix` to `true` in your config

https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#corsfix

**Comment by roysG** [comment]
Hi, 
The new version fix the cors for some videos files
These 2 videos, one work ok, and the other fail on error 415

This works: https://res.cloudinary.com/picktags-com/video/upload/q_10/v1595542346/ryulpy12cyxoxmrxasb0.mp4

This not works: https://res.cloudinary.com/picktags-com/video/upload/q_50/v1595542346/ryulpy12cyxoxmrxasb0.mp4

I attached also the base64 the one who not worked:


https://ctxt.io/2/AADAV5lQEg

I trie to paste the text with pastebin it tells me that i have blocked words.

Tested with and without proxy.
