### ISSUE TITLE
Error getting info from license server

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#758]
Checking license got error 503.

<img width="385" alt="Captura de Tela 2020-08-30 às 10 47 38" src="https://user-images.githubusercontent.com/12688324/91660788-3acddb00-eaae-11ea-8ccd-7b928e705c17.png">

**Comment by silvaartur** [comment]
@smashah, after trying several times works.

Suggestion: leave pass mention loaded without license and send a message for whatsapp number (self) alerting (as the message "controlled by a automation...").

**Comment by smashah** [comment]
I think there was a global outage today. https://twitter.com/InternetDsrptns/status/1300084665487851527

> Suggestion: leave pass mention loaded without license and send a message for whatsapp number (self) alerting (as the message "controlled by a automation...").

@silvaartur can you explain what you mean by this

**Comment by smashah** [comment]
Closing for now thanks
