### ISSUE TITLE
feature sendLinkWithAutoPreview always returning undefined

### ISSUE THREAD

**Issue by votanruchel** [open-wa/wa-automate-nodejs#760]
**Describe the bug**
The function is not returning the message id, but "undefined".

**Steps to Reproduce**
Just executing and waiting for the return should be enough to debug

**create() code**
This is the code you use to create the client. e.g
```javascript
client.sendLinkWithAutoPreview('chatid','url','message').then((res)=>{ console.log(res) });
```

**Expected behavior**
The expected operation was to return the message id as well as its parent functions (sendText and sendMessage)

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2035.14,
  PAGE_UA: WhatsApp/2.2029.4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36,
  WA_AUTOMATE_VERSION: 2.0.9 UPDATE AVAILABLE: 2.0.9,
  BROWSER_VERSION: HeadlessChrome/85.0.4182.0
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Linux Ubuntu 20.04 LTS

**Additional context**

**Comment by smashah** [comment]
@votanruchel This issue is now patched. Please try again in about 5 minutes

**Comment by votanruchel** [comment]
Hello @smashah , I received the update, however I still receive undefined with the function ... I am sending you an attached print of my code, maybe it will be misuse of the function ? 
code:

```javascript
await client.sendLinkWithAutoPreview('555491228584@c.us', post_list[randomLink].link, post_list[randomLink].title)
                .then(res => {
                    console.log(res);
                })
```

Terminal printscreen:

https://imgur.com/ZsQ9w2i

**Comment by votanruchel** [comment]
Hello @smashah , I received the update, however I still receive undefined with the function ... I am sending you an attached print of my code, maybe it will be misuse of the function ? 
code:

```javascript
await client.sendLinkWithAutoPreview('5554####8584@c.us', post_list[randomLink].link, post_list[randomLink].title)
                .then(res => {
                    console.log(res);
                })
```

Terminal printscreen:

https://imgur.com/ZsQ9w2i

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [2.0.12](https://github.com/open-wa/wa-automate-nodejs/compare/2.0.11...2.0.12) (2020-09-02)

- Release 2.0.12 [`26f9c4f`](https://github.com/open-wa/wa-automate-nodejs/commit/26f9c4fdf362c3af5a4e53cade0b5dd36488df67)
- Docs: Added instrcutions for handling multiple sessions [`edfbd76`](https://github.com/open-wa/wa-automate-nodejs/commit/edfbd76750073301783a8749271d7eaf2e80d68e)
- Docs: fix documentation for `getCommonGroups` #764 [`fc9fc5e`](https://github.com/open-wa/wa-automate-nodejs/commit/fc9fc5ef59bdf5788dafcebe2c0e30d0e74a1a85)
- Feature: Implemented `getSessionId()` [`087e07b`](https://github.com/open-wa/wa-automate-nodejs/commit/087e07bc8088c09d49aea503ce4fc4e012d7fe2e)
- Fixed: Make `sendLinkWithAutoPreview` return value #760 [`30c8aeb`](https://github.com/open-wa/wa-automate-nodejs/commit/30c8aeb38e8e7e88d0813c4852bbdc1f13b3914b)
- Fix typo [`2951120`](https://github.com/open-wa/wa-automate-nodejs/commit/2951120ddaeb492f07e64f513a9f2c5a707b8793)

**Comment by smashah** [comment]
@votanruchel should be working now

**Comment by votanruchel** [comment]
If i send a message to myself, it returns the message id normally, but if i send it to a group it simply has no return ...
My idea is to use it together with the client.getMessageReaders () function.

**Comment by votanruchel** [comment]
It worked, this is returning the message id... But in some cases the function crashes, and it simply does not return anything else in the promise, this only applies to group shipments, sending to normal users returns the id.

**Comment by smashah** [comment]
@votanruchel fixed. Try again in 5 minutes
