### ISSUE TITLE
feature getCommonGroups always returning false 

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#764]
**Describe the bug**
The function is not returning an array of common groups, but "false".

**Steps to Reproduce**
executing and waiting for the return

**create() code**
This is the code you use to create the client. e.g
```javascript
client.getCommonGroups('contactId').then((res)=>{ console.log(res) });
```

**Expected behavior**
Return an array of common groups

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2035.14
  PAGE_UA: WhatsApp/2.2029.4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
  WA_AUTOMATE_VERSION: 2.0.11
  BROWSER_VERSION: HeadlessChrome/84.0.4147.135
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
@dandyraka this actually an insiders feature

https://open-wa.github.io/wa-automate-nodejs/pages/The%20Client/licensed-features.html
