### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Could not find browser revision 782078

### ISSUE THREAD

**Issue by lacerdabh** [open-wa/wa-automate-nodejs#769]
**Describe the bug**
The error runs when I start the application. We are using the latest version that is available.

**Steps to Reproduce**
cd /demo
ts-node auto.ts

**create() code**
This is the code you use to create the client. e.g
```javascript
// import { create, Client } from '@open-wa/wa-automate';
const wa = require('@open-wa/wa-automate');

wa.create().then(client => start(client));

function start(client) {
  client.onMessage(message => {
    if (message.body === 'Hi') {
      client.sendText(message.from, '👋 Hello!');
    }
  });
}
```

**Expected behavior**

**DEBUG INFO**
```
--
```

**Screenshots**

![image](https://user-images.githubusercontent.com/68659425/92134995-9961c480-ede0-11ea-8486-abbe8d4c1c8f.png)

**Host (please complete the following information):**
 - SO: Linux Ubuntu 18.04 LTS 

**Additional context**
(node:1449) UnhandledPromiseRejectionWarning: Error: Could not find browser revi                                                                                                                                                                   sion 782078. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=f                                                                                                                                                                   irefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (/home/ubuntu/node_modules/puppeteer/lib/cjs/puppet                                                                                                                                                                   eer/node/Launcher.js:86:23)
    at PuppeteerExtra.launch (/home/ubuntu/node_modules/puppeteer-extra/src/inde                                                                                                                                                                   x.ts:172:21)
(node:1449) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This                                                                                                                                                                    error originated either by throwing inside of an async function without a catch                                                                                                                                                                    block, or by rejecting a promise which was not handled with .catch(). To termina                                                                                                                                                                   te the node process on unhandled promise rejection, use the CLI flag `--unhandle                                                                                                                                                                   d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio                                                                                                                                                                   ns_mode). (rejection id: 1)
(node:1449) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre                                                                                                                                                                   cated. In the future, promise rejections that are not handled will terminate the                                                                                                                                                                    Node.js process with a non-zero exit code.

**Comment by smashah** [comment]
@lacerdabh try deleting node_modules and run `npm i`

**Comment by smashah** [comment]
Report back if the issue is still happening but this is primarily a puppeteer issue.

**Comment by lacerdabh** [comment]
tks..
