### ISSUE TITLE
How to create multiple easy api using 1 port?

### ISSUE THREAD

**Issue by brainplusplus** [open-wa/wa-automate-nodejs#770]
How to create multiple session and using easy api with 1 port?

**Comment by smashah** [comment]
@brainplusplus It's not really designed to be used with multiple sessions.

How many sessions are you looking to manage with a single process?

**Comment by brainplusplus** [comment]
@smashah around 5-10 sessions

**Comment by smashah** [comment]
@brainplusplus If one error occurs on one of those sessions, all of them will go down. I suggest using a proxy to merge and expose all of them onto a single endpoint

E.g https://github.com/jc21/nginx-proxy-manager

Or use https://github.com/open-wa/wa-automate-docker with Kubernetes

**Comment by smashah** [comment]
Or maybe an express layer on top which redirect requests to their respective session ports.

**Comment by smashah** [comment]
Closing for now thanks
