### ISSUE TITLE
sendFileFromUrl not returning message id

### ISSUE THREAD

**Issue by priteshpmehta** [open-wa/wa-automate-nodejs#772]
**Describe the bug**
#752 same issue occurred again

**Steps to Reproduce**
1. sendFileFromUrl(to: ChatId, url: string, filename: string, caption: Content, quotedMsgId?: MessageId, requestConfig?: any, waitForId?: boolean): Promise

**create() code**
This is the code you use to create the client. e.g
```javascript
await client.sendFileFromUrl('xxx@c.us', 'https://i.giphy.com/media/oYtVHSxngR3lC/200w.mp4', 'video.mp4', 'xxxxx', null, null, true).then((serialized) => {
        console.log(`sendFileFromUrl has serialized ${serialized}\n`);
    }, (err) => {
        console.log(`sendFileFromUrl has error ${err}\n`);
    });
```

**Expected behavior**
It should return the id of the message. e.g: true_xxx@c.us_3XXXXF7BF8AXXXX7376D.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2035.14',
  PAGE_UA: 'WhatsApp/2.2029.4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Sa
fari/537.36',
  WA_AUTOMATE_VERSION: '2.0.12',
  BROWSER_VERSION: 'HeadlessChrome/85.0.4183.83'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Windows

**Comment by smashah** [comment]
@priteshpmehta I'm not able to reproduce this issue with your instructions. Can you share more context of this issue? Does it happen every time? How long do you have to wait for a response? What does it show when you run headful? etc. Need lots more detail

**Comment by priteshpmehta** [comment]
Hi @smashah ,

It is a strange, from last couple of hours I am examining this and **it is working as expected**. It was not working only yesterday and as I noticed, headful browser was showing timer icon after sending file and it wasn't returning any message id. I have tried by waiting 5 mins for response but it wasn't returning any success/error message.

![image](https://user-images.githubusercontent.com/33055448/92300942-46b71280-ef70-11ea-9ae9-a4b9921ff03a.png)

For quick debugging, I have tested :

- Internet speed
- Android device on which WA is installed
- file url whether it has proper file or not.

Even it was working fine, when I have called method by passing **waitForId as false**.

Now it is working fine but really wanted to know the reason, So in future I can debug with more possible conditions.

Thanks you for beautiful library.

**Comment by smashah** [comment]
@priteshpmehta I think there was a system issue at whatsapp that was causing this around that time.

Please see this comment for sending the same thing to multiple chats at the same time. Upload once, send to multiple chats using ghostForward: 

https://github.com/open-wa/wa-automate-nodejs/issues/771#issuecomment-687504454
