### ISSUE TITLE
sendContact not working

### ISSUE THREAD

**Issue by pboero** [open-wa/wa-automate-nodejs#775]
**Describe the bug**
sendContact function is not working.

Text returned is:
Error: Evaluation failed: TypeError: window.WAPI.getChat(...).sendContact is not a function

The error is generated in line 1635 of wapi.js.

I modified WAPI in order to check if the chat object is actually found. This is what I did

`
window.WAPI.sendContact = function (to, contact) {
    if (!Array.isArray(contact)) {
        contact = [contact];
    }
    contact = contact.map((c) => {
        return WAPI.getChat(c).__x_contact;
    });

    let chat = window.WAPI.getChat(to); // line added
    console.log(chat); // line added. Prints chat object properly. There is no sendContact function

    if (contact.length > 1) {
        window.WAPI.getChat(to).sendContactList(contact);
    } else if (contact.length === 1) {
        window.WAPI.getChat(to).sendContact(contact[0]); //
    }
};
`
Apparently, sendContact function is not a member of chat object any longer.

**Steps to Reproduce**
Just try to send a contact to a user

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
This has already been fixed with a patch and there's not enough details to determine if this issue is any different. Please update to the latest version and try again.

**Comment by pboero** [comment]
I updated to the latest version. This is my code:

const { create, Client } = require('@open-wa/wa-automate');

function start(client) {
  client.sendContact('5492215714495@c.us', '5492215714495@c.us');
}

create({headless: false}).then(async client => await start(client));

This is the result:
✓ Authenticated
✓ WAPI Reinjected
✓ Client is ready
✓ Client loaded in 6.887s
✓ Patches Installed
✓ � @OPEN-WA ready for account: 5492215923892
(node:27340) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'vcardFromContactModel' of undefined

**Comment by smashah** [comment]
I'll issue a new patch ASAP. Going forward please try to remove numbers from your logs/code snippets.
