### ISSUE TITLE
Error not found modules

### ISSUE THREAD

**Issue by Eroo768** [open-wa/wa-automate-nodejs#800]
![Screenshot_2020-09-10-11-27-59-90](https://user-images.githubusercontent.com/70959670/92681790-cc640500-f358-11ea-910e-066cd1f2ebc9.jpg)
This

**Comment by smashah** [comment]
Why is there a space between `index.` and `ts`????

You have to run:

```bash
> ts-node index.ts
```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️

**Comment by Eroo768** [comment]
![Screenshot_2020-09-11-06-04-52-63](https://user-images.githubusercontent.com/70959670/92821059-dc312700-f3f4-11ea-9858-84161cbbba03.jpg)
This
