### ISSUE TITLE
Feature Request: Reply with Sticker from Url

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#804]
**Describe the bug**

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/18587059/92752884-88eab480-f3b3-11ea-9ce4-ab6dca5e3fc5.png)

If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
For future reference, you don't need to use the issue template for feature requests.

**Comment by dandyraka** [comment]
> For future reference, you don't need to use the issue template for feature requests.
> 
> 

Haha ok sorry 😂

**Comment by smashah** [comment]
@dandyraka dm me on the discord pls

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [2.0.22](https://github.com/open-wa/wa-automate-nodejs/compare/2.0.21...2.0.22) (2020-09-11)

- Fixes #802 `ghostForward` now returns Id [`#802`](https://github.com/open-wa/wa-automate-nodejs/issues/802)
- Release 2.0.22 [`6d49b53`](https://github.com/open-wa/wa-automate-nodejs/commit/6d49b5322638a3e6aeefb33029ca229be106d7d2)
- enhancement: migrate popup from http-server to express [`5c9f263`](https://github.com/open-wa/wa-automate-nodejs/commit/5c9f2631cdd0530ad338eb93b9c2869028a8470a)
- Enhancement: splt logs and qr code in the popup [`6430fa2`](https://github.com/open-wa/wa-automate-nodejs/commit/6430fa204c495e9d252c6345f3f607fcc86a1857)
- Insiders Feature: Implemented `sendStickerfromUrlAsReply`  #804 [`66aa410`](https://github.com/open-wa/wa-automate-nodejs/commit/66aa4103898186523c081fcee2d84b9e37583536)
- `sendImageAsSticker` returns message id [`310bc33`](https://github.com/open-wa/wa-automate-nodejs/commit/310bc33eea3bb1e682a7502dfdf82ba7d006f661)
- fix: namespace override now working correctly on `ev.emit` [`2f7f6a5`](https://github.com/open-wa/wa-automate-nodejs/commit/2f7f6a5ce8244988e0f82c52073907a6915483a5)

**Comment by smashah** [comment]
https://open-wa.github.io/wa-automate-nodejs/classes/client.html#sendstickerfromurlasreply

**Comment by dandyraka** [comment]
Hi @smashah , can you add sendImageAsSticker with reply too?
