### ISSUE TITLE
Why command not found

### ISSUE THREAD

**Issue by Eroo768** [open-wa/wa-automate-nodejs#805]
![Screenshot_2020-09-11-06-04-52-63](https://user-images.githubusercontent.com/70959670/92821437-421dae80-f3f5-11ea-82fc-3fa351b281d3.jpg)
This

**Comment by jesusvalverde** [comment]
npm install -g ts-node

**Comment by smashah** [comment]
It is a dev dependency. 

```bash
> npm install --only=dev
> npm i
```

If you're having trouble with that simple error, I suggest not messing around with the demo folder. Just use the CLI:

```
> npx @open-wa/wa-automate
```
