### ISSUE TITLE
onStateChanged not working

### ISSUE THREAD

**Issue by kodmanyagha** [open-wa/wa-automate-nodejs#807]
I upgraded from 2.0.12 to v2.0.22 today. After upgrade onStateChanged function not working properly.

	let sessionId = "whatsapp/" + this.uniqid;
	let waConfig = {};
	waConfig.headless = false;
	waConfig.useChrome = false;
	waConfig.chromiumArgs = ["--disable-notifications"];
	waConfig.logQR = true;
	waConfig.qrTimeout = 45;
	waConfig.authTimeout = 45;
	waConfig.qrRefreshS = 15;
	waConfig.autoRefresh = true;

	waConfig.sessionId = sessionId;

-------------------------

	self.waClient.onStateChanged(function(state) {
		Logger.log(self.cellphone + " state changed to " + state);

		if (state === "CONFLICT") {
			self.waClient.forceRefocus();
		}

		if (state === "UNPAIRED") {
			
		}
	});

Not detecting UNPAIRED state in v2.0.22. It was work on 2.0.12

**Comment by smashah** [comment]
@kodmanyagha looks like it has changed to `UNLAUNCHED` instead of `CONFLICT`

```javascript
self.waClient.onStateChanged(function(state) {
	Logger.log(self.cellphone + " state changed to " + state);

	if (state === "UNLAUNCHED") {
		self.waClient.forceRefocus();
	}

	if (state === "UNPAIRED") {
		//logged out
	}
});
```
