### ISSUE TITLE
My number is block, and return this error

### ISSUE THREAD

**Issue by eliasvasconcelos** [open-wa/wa-automate-nodejs#808]
Hy, my number was blocked.. i sended one e-mail for whatsapp and the whatsapp unblock my number.
more i'm check the my whatsapp, and the chat is my was number spamed this message

Your account is currently being controlled by an automation service. If you have not authorized this then please "Log out from all devices" in the "WhatsApp Web" section of this app.

This is one error in wa automate? or this is one error in my aplication?
what is the solution?

Thanks

**Comment by smashah** [comment]
Please discuss this in the discord
