### ISSUE TITLE
getLastSeen not working

### ISSUE THREAD

**Issue by Crucial288** [open-wa/wa-automate-nodejs#811]
**Describe the bug**
the getLastSeen method is returning undefined in every case. This happens even when: User does NOT have last seen blocked, we have a chat open, and the chat type is not "group"

**Steps to Reproduce**
1. Find all chats
2. Find a specific chat by filtering all chats by name, and kind == "chat"
3. Use the getLastSeen() method with the chat Id as an argument

**Expected behavior**
Expecting the epoch time of the last seen of the user

**Comment by smashah** [comment]
@Crucial288 I've made it a bit more reliable via a new patch. Make sure you're using the latest version then try again.
