### ISSUE TITLE
The removeParticipant is not working

### ISSUE THREAD

**Issue by hbarcellos** [open-wa/wa-automate-nodejs#827]
I'm trying to remove a participant from the group but it doesn't seem to work.

I'm trying this way:
```javascript
await client.removeParticipant(message.chat.groupMetadata.id, message.from);
```

The following error appears:

> (node:28) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'groupMetadata' of undefined
> whatsbot    |     at Object.window.WAPI.removeParticipant (/app/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1950:21)

```
Debug Info {
  WA_VERSION: 2.2037.6
  PAGE_UA: WhatsApp/2.2029.4 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
  WA_AUTOMATE_VERSION: 2.0.23
  BROWSER_VERSION: HeadlessChrome/85.0.4183.102
}
```

**Comment by cauebs** [comment]
Do you remember what the problem was?
