### ISSUE TITLE
sessionId parameter on create() being ignored

### ISSUE THREAD

**Issue by rickricardo** [open-wa/wa-automate-nodejs#831]
Hi, I used to work with session1 and session2 of wa-automate for 2 different numbers in the same folder.
To do that I just needed to change the sessionId parameter like below:

create({
  sessionId:'**session1**',
  ...
})
.then(async ...

or

create({
  sessionId:'**session2**',
  ...
})
.then(async ...

After updating from version 2.0.8 to 2.0.23 I cannot do it anymore.
Whatever the string I send on 'sessionId', now it always create session files named as "qr_code_session.png" and "session.data.json".

Before I had "qr_code_session1.png" / "qr_code_session2.png" and "session1.data.json" / "session2.data.json".

Was it on purpose for this new version?
I am lunching my application with the command: "ts-node program_name.ts"

**Comment by kodmanyagha** [comment]
same problem. I'M trying this: https://open-wa.github.io/wa-automate-nodejs/pages/The%20Client/the-client/multiple-sessions.html
not working.

**Comment by smashah** [comment]
I'm going to fix this for now but in the future major release there will only be one parameter which will be the config object. As far as I'm concerned, using the first param as session Id string is already deperecated so please migrate to config object only.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [2.0.24](https://github.com/open-wa/wa-automate-nodejs/compare/2.0.23...2.0.24) (2020-09-22)

- Release 2.0.24 [`488b7d0`](https://github.com/open-wa/wa-automate-nodejs/commit/488b7d01902feec0ae7bcd242382518144e3e94d)
- extended support for deprecated sessionId as first param. Please migrate to config object as nonly param. config session id overrides session id parameter #831 [`b291198`](https://github.com/open-wa/wa-automate-nodejs/commit/b291198d0a2ff2f796a9671042d7f017e701ce08)
- Update user agent [`c8c4b1a`](https://github.com/open-wa/wa-automate-nodejs/commit/c8c4b1ac1b96c9b04568559b0fda65a5a1f1add9)
