### ISSUE TITLE
Starting new Chat

### ISSUE THREAD

**Issue by dhevanthareza** [open-wa/wa-automate-nodejs#832]
Hello, i want to ask how to create new message, i cant find that in documentation

**Comment by smashah** [comment]
Just use `sendText` to a number. That will start a chat. If you need to start a chat with a non contact then you'll need a restricted key.

**Comment by dhevanthareza** [comment]
if i see the documentation sendText need ChatId, what i want to ask is, how can i make a new chat so i can get a ChatId, or i can replace ChatId with specific number. And how can i get restricted key, my goal is sendText to a non contact

**Comment by Gidraf** [comment]
@dhevanthareza ChatId is the number you want to send the message to with a concatenation of @c.us e.g. if you want to send the message to this number `+2547123456XXX` the chat id will be `2547123456XXX@c.us` here 254 is the country code. Hope this help. you can have a restricted key or you can combine different library to achieve the same.

**Comment by dhevanthareza** [comment]
what is @c.us mean

**Comment by smashah** [comment]
@dhevanthareza it's just something you have to add to the end for WhatsApp. Basically it means the number you're referring to is a chat.
