### ISSUE TITLE
About upgrade to new version

### ISSUE THREAD

**Issue by kodmanyagha** [open-wa/wa-automate-nodejs#839]
Thanks for your project. I faced a big problem about this project. Please don't change big things for minor upgrades. In 2.0.12 we can use "create" function like that: create(sessionId, configObj) then in 2.0.23 create method usage is changed. This is wrong. And we can't set sessionId in config object. Probably there is a bug. I'M looking your codes if I find then I write here. Thanks.

**Comment by kodmanyagha** [comment]
I found the solution. In node_modules/@open-wa/wa-automate/dist/controllers/initializer.js add these to line 133

	sessionId = '';
	if (typeof _sessionId === 'object' && _sessionId) {
		config = _sessionId;
	}
	config = __assign(__assign({}, config), configSchema_1.getConfigFromProcessEnv(configWithCases));
	config.chromiumArgs = (config === null || config === void 0 ? void 0 : config.chromiumArgs) || [];
	sessionId = config.sessionId;
	customUserAgent = config.customUserAgent;

Full code should be like that:

	case 3:
		sessionId = '';
		if (typeof _sessionId === 'object' && _sessionId) {
		config = _sessionId;
		}
		config = __assign(__assign({}, config), configSchema_1.getConfigFromProcessEnv(configWithCases));
		config.chromiumArgs = (config === null || config === void 0 ? void 0 : config.chromiumArgs) || [];
		sessionId = config.sessionId;
		customUserAgent = config.customUserAgent;

		if (!sessionId)
		sessionId = 'session';
		spinner = new events_1.Spin(sessionId, 'STARTUP', config === null || config === void 0 ? void 0 : config.disableSpins);
		_c.label = 4;

I don't know typescript. You can change main source code like that. I'm using with this change. Please make test for every change. Thanks.

**Comment by smashah** [comment]
Duplicate #831
