### ISSUE TITLE
How do I listen for ack changes?

### ISSUE THREAD

**Issue by lukasportal** [open-wa/wa-automate-nodejs#841]
All messages have an "ack" property
0 = pending
1 = sent
2 = delivered
3 = read
4 = downloaded
(from what i could understand)

there are lots of events from the modules exported, but i can't find one that will trigger an ack change

Any ideas?

**Comment by smashah** [comment]
RTFD - https://open-wa.github.io/wa-automate-nodejs/classes/client.html#onack
