### ISSUE TITLE
Trial for Premium License Key

### ISSUE THREAD

**Issue by rohankm** [open-wa/wa-automate-nodejs#842]
Hi @smashah ,
YOU ARE A LEGEND... !  Thanks for creating such an awesome project.
I would like to test the Premium Features before I want to buy it. I am building a an application for music collaboration, so if you let me try the premium features it would be helpful :)

**Comment by smashah** [comment]
Thanks @rohankm please email me.

**Comment by rohankm** [comment]
@smashah Emailed you Please check
