### ISSUE TITLE
Suddenly got error when using Easy API

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-nodejs#849]
When I try to run I got error:

✖ The session is invalid. Retrying

<img width="993" alt="Captura de Tela 2020-09-23 às 23 45 19" src="https://user-images.githubusercontent.com/12688324/94094827-da089880-fdf6-11ea-9d9b-6fdf485af01e.png">

**Comment by silvaartur** [comment]
Same if trying to use 2.0.24.

**Comment by silvaartur** [comment]
![Uploading Captura de Tela 2020-09-24 às 00.03.25.png…]()

**Comment by silvaartur** [comment]
<img width="407" alt="Captura de Tela 2020-09-24 às 00 03 57" src="https://user-images.githubusercontent.com/12688324/94096026-75027200-fdf9-11ea-8662-ea46f1209277.png">

**Comment by hangsbreaker** [comment]
Same. Waiting for solution

**Comment by NovaSampoerna24** [comment]
Same. Waiting for solution

**Comment by nikkoenggaliano** [comment]
Any update? Facing same problem.

**Comment by areltiyan** [comment]
Waiting for solution.

**Comment by silvaartur** [comment]
@areltiyan correctly reported the bug on #850

**Comment by smashah** [comment]
duplicate #852
