### ISSUE TITLE
× The session is invalid. Retrying

### ISSUE THREAD

**Issue by areltiyan** [open-wa/wa-automate-nodejs#850]
**Steps to Reproduce**
1. run bot
2. scan qr
3. see **× The session is invalid. Retrying**

**create() code**
This is the code you use to create the client. e.g
```javascript
wa.create('session', {
        executablePath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
        headless: false,
        bypassCSP: true,
        restartOnCrash: false,
        killProcessOnBrowserClose: false,
        
        autoRefresh: false,
    })
    .then(async client => {
        start(client);
    })
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2039.9
  PAGE_UA: WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
  WA_AUTOMATE_VERSION: 2.0.24
  BROWSER_VERSION: Chrome/85.0.4183.121
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/54056041/94096728-018b4f80-fe4f-11ea-84b9-3f2e528304c6.png)

**Host (please complete the following information):**
 - OS: Android

**Additional context**

**Comment by silvaartur** [comment]
Same as reported #849

**Comment by areltiyan** [comment]
> Same as reported #849

well, i see close now.

**Comment by acqrdeveloper** [comment]
right now I have the same problems, Help!

**Comment by AlenSaito1** [comment]
Same here

**Comment by edu1525** [comment]
Same here on v2.0.23

**Comment by NovaSampoerna24** [comment]
I solved it by updating the wapi.js file https://github.com/open-wa/wa-automate-nodejs/pull/851/commits/f4cc51423aa367ad3c7b735a799d6f7d6ab05051

**Comment by edu1525** [comment]
> I solved it by updating the wapi.js file [f4cc514](https://github.com/open-wa/wa-automate-nodejs/commit/f4cc51423aa367ad3c7b735a799d6f7d6ab05051)

After using you solution my session is now created successfully, but after that I receive another error:

`` TypeError: Cannot set property 'skipBrokenMethodsCheck' of undefined --> initializer.js:324``

**Comment by myfrizqi** [comment]
> I solved it by updating the wapi.js file [f4cc514](https://github.com/open-wa/wa-automate-nodejs/commit/f4cc51423aa367ad3c7b735a799d6f7d6ab05051)

Great, Work for me..

**Comment by Eroo768** [comment]
> Saya menyelesaikannya dengan memperbarui file [wapi.js f4cc514](https://github.com/open-wa/wa-automate-nodejs/commit/f4cc51423aa367ad3c7b735a799d6f7d6ab05051)

how to update it

**Comment by YogaSakti** [comment]
> I solved it by updating the wapi.js file [f4cc514](https://github.com/open-wa/wa-automate-nodejs/commit/f4cc51423aa367ad3c7b735a799d6f7d6ab05051)

this work for me, but I think it's better to wait for the official update..

**Comment by gnadelwartz** [comment]
> > Saya menyelesaikannya dengan memperbarui file [wapi.js f4cc514](https://github.com/open-wa/wa-automate-nodejs/commit/f4cc51423aa367ad3c7b735a799d6f7d6ab05051)
> 
> how to update it

```bash
on linux e.g.:

curl "https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js" >wapi.js


```

**Comment by shansekai** [comment]
> > > Saya menyelesaikannya dengan memperbarui file [wapi.js f4cc514](https://github.com/open-wa/wa-automate-nodejs/commit/f4cc51423aa367ad3c7b735a799d6f7d6ab05051)
> > 
> > 
> > how to update it
> 
> ```shell
> on linux e.g.:
> 
> curl "https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js" >wapi.js
> ```



> I solved it by updating the wapi.js file [f4cc514](https://github.com/open-wa/wa-automate-nodejs/commit/f4cc51423aa367ad3c7b735a799d6f7d6ab05051)

Thx, work for me

**Comment by shansekai** [comment]
> I solved it by updating the wapi.js file [f4cc514](https://github.com/open-wa/wa-automate-nodejs/commit/f4cc51423aa367ad3c7b735a799d6f7d6ab05051)

Thx, work for me

**Comment by Eroo768** [comment]
> > > Saya menyelesaikannya dengan memperbarui file [wapi.js f4cc514](https://github.com/open-wa/wa-automate-nodejs/commit/f4cc51423aa367ad3c7b735a799d6f7d6ab05051)
> > 
> > 
> > bagaimana memperbaruinya
> 
> ```shell
> di linux misalnya:
> 
> curl " https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js "  > wapi.js
> ```

Jika di rdp bagaimana

**Comment by shansekai** [comment]
> > > > Saya menyelesaikannya dengan memperbarui file [wapi.js f4cc514](https://github.com/open-wa/wa-automate-nodejs/commit/f4cc51423aa367ad3c7b735a799d6f7d6ab05051)
> > > 
> > > 
> > > bagaimana memperbaruinya
> > 
> > 
> > ```shell
> > di linux misalnya:
> > 
> > curl " https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js "  > wapi.js
> > ```
> 
> Jika di rdp bagaimana

Aku pakai rdp pakai cara ini

Copy semua text di dalam link ini : [https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js](https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js) 
Terus masuk ke folder : `@open-wa => wa-automate => dist => lib => wapi.js`  dan replace yang text lyang kamu copy tadi.

**Comment by ben-dev2609** [comment]
saya tidak paham wkwk

**Comment by ben-dev2609** [comment]
× QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout
√ Loading QR

----------
EV QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout customer-support STARTUP


ini maksudnya apa

**Comment by Eroo768** [comment]
> > > > > Saya menyelesaikannya dengan memperbarui file [wapi.js f4cc514](https://github.com/open-wa/wa-automate-nodejs/commit/f4cc51423aa367ad3c7b735a799d6f7d6ab05051)
> > > > 
> > > > 
> > > > bagaimana memperbaruinya
> > > 
> > > 
> > > ```shell
> > > di linux misalnya:
> > > 
> > > curl " https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js "   > wapi.js
> > > ```
> > 
> > 
> > Jika di rdp bagaimana
> 
> Aku pakai rdp pakai cara ini
> 
> Salin semua teks di dalam link ini: https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js
> Terus masuk ke folder: `node_mudules/@open-wa/wa-automate/dist/lib/wapi.js` dan ganti teks yang kamu salin tadi .

![Screenshot_2020-09-24-16-06-06-42_fb47b6c93b99596be3e79670c6246005](https://user-images.githubusercontent.com/70959670/94124948-e97ff400-fe7f-11ea-992e-108daa070a7e.jpg)
Yang mana yang di ganti

**Comment by shansekai** [comment]
> ![Screenshot_2020-09-24-16-06-06-42_fb47b6c93b99596be3e79670c6246005](https://user-images.githubusercontent.com/70959670/94124948-e97ff400-fe7f-11ea-992e-108daa070a7e.jpg)
> Yang mana yang di ganti

Gak ada yang perlu diganti copy aja semua

**Comment by ben-dev2609** [comment]
kalau yang nodejs gmn?

**Comment by shansekai** [comment]
> × QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout
> √ Loading QR
> 
> EV QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout customer-support STARTUP
> 
> ini maksudnya apa

Ini pakai punya bang yogasakti kah?

**Comment by ben-dev2609** [comment]
> > × QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout
> > √ Loading QR
> > EV QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout customer-support STARTUP
> > ini maksudnya apa
> 
> Ini pakai punya bang yogasakti kah?

ga tau saya bang saya copy yang  di code

**Comment by Eroo768** [comment]
> > ![Screenshot_2020-09-24-16-06-06-42_fb47b6c93b99596be3e79670c6246005](https://user-images.githubusercontent.com/70959670/94124948-e97ff400-fe7f-11ea-992e-108daa070a7e.jpg)
> > Yang mana yang di ganti
> 
> Gak ada yang perlu diganti copy aja semua

Yang itu APUS semua ya bang terus ganti yang Abang kasih ya

**Comment by shansekai** [comment]
> Yang itu APUS semua ya bang terus ganti yang Abang kasih ya

Iya betull

**Comment by ben-dev2609** [comment]
cd buat di npm apa ya bang
kok saya begini mulu

> × QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout
> √ Loading QR
> 
> EV QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout customer-support STARTUP
> 
> ini maksudnya apa

**Comment by Eroo768** [comment]
> > Yang itu APUS semua ya bang terus ganti yang Abang kasih ya
> 
> Iya betull

![Screenshot_2020-09-24-16-52-19-55_fb47b6c93b99596be3e79670c6246005](https://user-images.githubusercontent.com/70959670/94130141-77f77400-fe86-11ea-8173-fa0554b8e503.jpg)
Kok masih tetep yang bang

**Comment by smashah** [comment]
Duplicate #852
