### ISSUE TITLE
Cant able scan QR from PM2

### ISSUE THREAD

**Issue by rashid-techie** [open-wa/wa-automate-nodejs#857]
**Describe the bug**
Cant able to scan the qr code. it was worked sometimes and sometime it wont

**Steps to Reproduce**
1. Refresh or Reload the session
2. the url to scan the qr
3. it was scanned and shows the last active time in mobile
4. but not reflecting in WA

**create() code**
This is the code you use to create the client. e.g
``` let {sessionId} = req.body;
  if(proxyRegistry[sessionId]) {
    await pm2.restart(sessionId);
    res.send(`${sessionId} restarted`)
  }
>>return await res.send(`${sessionId} is not started. Use '/create'`)
});


pm2.connect(async function(err) {
  if (err) {
```

**Expected behavior**
Need to scan the QR properly

**DEBUG INFO**
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at ServerResponse.header (/home/nodejs/admin-api/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/home/nodejs/admin-api/node_modules/express/lib/response.js:170:12)
    at /home/nodejs/admin-api/index.js:109:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: 2.0.22,
  BROWSER_VERSION: ...
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Web app(angular)

**Additional context**
Test Code to Scan the QR with auto refresh
<img src='ip/api/sessionname/qr' onload='imageRefresh(this, 10000);'>

function imageRefresh(img, timeout) {
                setTimeout(function() {
                var d = new Date;
                var http = img.src;
                if (http.indexOf("&d=") != -1) { http = http.split("&d=")[0]; } 
                img.src = http;
                }, timeout);
            }

**Comment by smashah** [comment]
@rashid-techie please update to latest version 2.0.25
