### ISSUE TITLE
Send Message function not working

### ISSUE THREAD

**Issue by riquedev** [open-wa/wa-automate-nodejs#864]
Hello guys!
I have a problem in the function "send message", because after executing it I get a "false".
When done in promise, I get the error "chat.sendMessage does not exist".

```js
window.WAPI.getChat("xxx@c.us").sendMessage("test")
```

This results in false for some contacts, however others that are in my phonebook and even my own number are back to working normally. However, others do not.

**Comment by smashah** [comment]
@riquedev of the chat doesn't exist then you won't be able to send a message to it.
