### ISSUE TITLE
Feature: Analytics layer

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#865]
It would be useful to have a general overview of the accounts general statistics

- [x] Implement swagger-stats on CLI
- [x] Make sure to patch error/longestRequests

**Comment by joedutra** [comment]
<img src="https://media.giphy.com/media/sNZddQMtrqpS0HEEMC/giphy.gif"></img>
Man, you know it sucks, how we copy your repo, if we have functions that you don’t even have, all for free, we perform almost every day, I came from Sulla and you too, but if you look at following the week, we redid it all lib again, now you will no longer be able to copy us, you copy and keep saying that we copy, nor compete with you ours and for free and your payment

**Comment by joedutra** [comment]
I come to apologize and say that we have nothing against this, only that they accuse us of copying and we never copied anything, if someone copied it was when someone changed our lib, I apologize and the intention was not to be slandered anymore of copying something we worked on every day. just like you, we will not do that anymore.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci minor`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.6.0](https://github.com/open-wa/wa-automate-nodejs/compare/3.5.1...3.6.0) (2021-02-18)

- Release 3.6.0 [`951d87e`](https://github.com/open-wa/wa-automate-nodejs/commit/951d87ede2068f5fd96e27c10709828bdc2400e8)
- feature [CLI]: use `--stats` to view API statistics, added robots handler #865 [`55aa2cc`](https://github.com/open-wa/wa-automate-nodejs/commit/55aa2ccdaaab984d6f6e9ba9214d627f9beb347d)
- Revert "improved message and chat typings" [`d6867ac`](https://github.com/open-wa/wa-automate-nodejs/commit/d6867ac7238793b05ed269474409be385e92a397)
- quotedMsg optional on Message type [`c2307ef`](https://github.com/open-wa/wa-automate-nodejs/commit/c2307efe188e855248f2e0d844e2fa10c50faeb2)

**Comment by smashah** [comment]
You can now use the `--stats` flag on the CLI command to expose a statistics dashboard, specifically swagger-stats.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.6.1](https://github.com/open-wa/wa-automate-nodejs/compare/3.6.0...3.6.1) (2021-02-18)

- Release 3.6.1 [`55e895b`](https://github.com/open-wa/wa-automate-nodejs/commit/55e895b1d7907cc690de1892234f6df1b8116dac)
- fix: added `patch-package` to fix `swagger-stats` memory leak issue on CLI when using `--stats` #865 [`80d8658`](https://github.com/open-wa/wa-automate-nodejs/commit/80d8658a81ac77ca4a7fe847dbe74a25764706d6)
