### ISSUE TITLE
is there a way to report instead of blocking? thank you

### ISSUE THREAD

**Issue by chicken999** [open-wa/wa-automate-nodejs#867]

**Comment by smashah** [comment]
You mean reporting for spam?

**Comment by chicken999** [comment]
> 
> 
> You mean reporting for spam?

yes sir , reporting a contact instead of just blocking, report and block

**Comment by smashah** [comment]
@chicken999 how often are you reporting numbers? I think this is a very dangerous feature that should not be implemented. What's stopping anyone from making a program to mass report numbers? This will not be GA if there's even a good reason for this feature to be automated

**Comment by chicken999** [comment]
> 
> 
> @chicken999 how often are you reporting numbers? I think this is a very dangerous feature that should not be implemented. What's stopping anyone from making a program to mass report numbers? This will not be GA if there's even a good reason for this feature to be automated

i see po**bots joining my grooups every single day sending infected links with por**graphy they rejoin constantly , i cant even share my link and whatsapp doesnt seem to do anything against it, i just wanted to know if does that feauture exists on your api, thank you tho

**Comment by smashah** [comment]
Can you give me some idea of the numbers of bots you're dealing with please

**Comment by chicken999** [comment]
> 
> 
> > @chicken999 how often are you reporting numbers? I think this is a very dangerous feature that should not be implemented. What's stopping anyone from making a program to mass report numbers? This will not be GA if there's even a good reason for this feature to be automated
> 
> i see po`bots joining my grooups every single day sending infected links with por`graphy they rejoin constantly , i cant even share my link and whatsapp doesnt seem to do anything against it, i just wanted to know if does that feauture exists on your api, thank you tho



> 
> 
> Can you give me some idea of the numbers of bots you're dealing with please. If this is to be implemented it will be a restricted feature.

they use many country codes,but the most i see are +44/+371/+48...basically all these virtual ones that can be made with some apps for free, but like i said i couldnt unfortunatelly tell you a specific country code since they use a lot of different codes, i dont know who is behind these p * rnbots but its a thing of months ago and still the same , whatsapp didnt take any action on this yet and it has been reported endless times

**Comment by smashah** [comment]
@chicken999 I meant the amount of accounts that are doing this, not specific numbers.

If you want you can start a project to create a honeypot bot where I give you a free license key to access this feature. But I don't feel like it's a good idea to make the ability to automatically report accounts available open sourced.

**Comment by chicken999** [comment]
> 
> 
> @chicken999 I meant the amount of accounts that are doing this, not specific numbers.
> 
> If you want you can start a project to create a honeypot bot where I give you a free license key to access this feature. But I don't feel like it's a good idea to make the ability to automatically report accounts available open sourced.

the amount of accounts are endless smashah , its every day continually and its not just in my grops its practically in every group i am in, its really annoying. And thank you that seems a good idea to get ride of it

**Comment by smashah** [comment]
@chicken999 This feature has now been implemented in version 2.0.27

https://open-wa.github.io/wa-automate-nodejs/classes/client.html#reportspam

Please dm me on discord so you can access this feature.
