### ISSUE TITLE
Problem at start using Ubuntu 20

### ISSUE THREAD

**Issue by indragunawan82** [open-wa/wa-automate-nodejs#870]
**Describe the bug**
Problem at start running in linux

**Steps to Reproduce**
1. Fresh install
2. node src/index.js

**Screenshots**
![image](https://user-images.githubusercontent.com/9045625/94427963-20c10e80-01ba-11eb-94b9-fc0a95d5155b.png)

**Host (please complete the following information):**
 - Ubuntu 20

**Comment by smashah** [comment]
please share `src/index.js`

**Comment by JoeDozan24** [comment]
Did you trying to run `headless = false` on a device that don't have monitor? It happened recently to me if you try to use that config on a device that don't have display

**Comment by smashah** [comment]
@indragunawan82 install chrome on your server then try with `useChrome: true`

**Comment by smashah** [comment]
Closing for now. Thanks
