### ISSUE TITLE
SendImageAsSticker return  Input buffer contains unsupported image format

### ISSUE THREAD

**Issue by responsablyat** [open-wa/wa-automate-nodejs#874]
**Describe the bug**
The SendImageAsSticker return Input buffer contains unsupported image format
![image](https://user-images.githubusercontent.com/25841530/94573510-5d653680-029c-11eb-951b-f0999ab6bcc1.png)

**Steps to Reproduce**
1. I send image with specific command
2. Bot  should  send sticker with the same picture inside
3. Instead of sending the sticker the bot return an error [Error: Input buffer contains unsupported image format]

**create() code**
This is the code you use to create the client. e.g
```javascript
create('BUZZZER', {
            devtools: false,
            useChrome: true,
            autoRefresh: true,
            //cacheEnabled: false,
            headless: true,
            executablePath: '/usr/bin/google-chrome-stable',
            args: ["--no-sandbox", "--disable-setuid-sandbox"]
        })
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION:   '2.2039.9' 
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36'
  WA_AUTOMATE_VERSION: '2.0.26'  
  BROWSER_VERSION: 'HeadlessChrome/84.0.4147.125'    
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots
this is the error log
![image](https://user-images.githubusercontent.com/25841530/94573982-d795bb00-029c-11eb-946a-a2bbe88757c0.png)
this is the code
![image](https://user-images.githubusercontent.com/25841530/94574132-fd22c480-029c-11eb-9e38-bb6898b39159.png)

**Host (please complete the following information):**
 - OS: Android

**Additional context**
This thing happened after i update from 21 to the latest(26), but when i tried to back to 21, the qr code seems to be stuck

**Comment by smashah** [comment]
@responsablyat Thanks for filling out the form, however, we can't really fix this without the file that is causing this error. I ran the demo and the sticker conversion is working fine

**Comment by responsablyat** [comment]
![image](https://user-images.githubusercontent.com/25841530/94890971-fe294100-04aa-11eb-9392-fcea9d9d9915.png)
the first image is me using windows 10 screenshot and immediately send it to my bot
and the second image is from 9gag
This is the first image
![image](https://user-images.githubusercontent.com/25841530/94891013-1bf6a600-04ab-11eb-9fed-35fb9dc061f1.png)

And this is the second image
![Who-else-likes-running-as-administrator](https://user-images.githubusercontent.com/25841530/94890962-f9648d00-04aa-11eb-9169-b39cf5731c66.jpg)

**Comment by smashah** [comment]
@responsablyat I tested both and both are working fine. Please update to latest version and try again.

See: https://github.com/open-wa/wa-automate-nodejs/issues/868#issuecomment-702978529
