### ISSUE TITLE
Feature: Fix cross platform libvip install annoyances by replacing sharp with lipo

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#875]
Sharp isn't a core part of the library and honestly causes more headache than it solves for most people. Lipo is a drop-in replacement for sharp that basically offloads all conversions to an API - or a self-hosted central sharp implementation. This should save 40+mb from install.

The only downside is that the api has rate limits per IP. This can be bypassed by manually setting up a lipo server.

Todo:

- [ ] Replace Sharp with Lipo

- [ ] Add lipo config options to config object

https://github.com/lipojs/lipo

Status: Blocked by https://github.com/lipojs/lipo/issues/18

**Comment by smashah** [comment]
Update. This will need a custom open-wa fork of lipo.

**Comment by joedutra** [comment]
I come to apologize and say that we have nothing against this, only that they accuse us of copying and we never copied anything, if someone copied it was when someone changed our lib, I apologize and the intention was not to be slandered anymore of copying something we worked on every day. just like you, we will not do that anymore.

**Comment by smashah** [comment]
Closing

Please see:

https://github.com/open-wa/wa-automate-nodejs/issues/659#issuecomment-673017034
