### ISSUE TITLE
Image does not send via sendImage / sendFile

### ISSUE THREAD

**Issue by allanlisboaweb** [open-wa/wa-automate-nodejs#876]
<img width="1232" alt="Captura de Tela 2020-09-29 às 22 01 53" src="https://user-images.githubusercontent.com/37181884/94631981-c1d5c500-029f-11eb-9724-5acd83a45c3b.png">
Image does not send via sendImage / sendFile

**Comment by smashah** [comment]
@allanlisboaweb please make sure you are sending a [DataURL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs), not just Base64

**Comment by allanlisboaweb** [comment]
As you can see, I am sending a file that is in jpg format

<img width="948" alt="Captura de Tela 2020-09-29 às 22 29 03" src="https://user-images.githubusercontent.com/37181884/94633283-378f6000-02a3-11eb-9344-651bc679a288.png">

**Comment by JoeDozan24** [comment]
Found out sendImage does not sending message if Patching is on..
I did `skipPatches=true` and it can sendImage but with problem on #881

**Comment by smashah** [comment]
@allanlisboaweb I have added an example in the demo of sending a file from the filepath. 

I was able to recreate your error when I added the file without `./`

For example, if the file is called `picture.jpg`:

'picture.jpg' => results in your error
'./picture.jpg' => works perfectly

Remember, it will take the reference relative to the process working directory.

For example, if you have your code in a folder called `src` and you call `npm run start` from 'above' that folder, then the references will need to be relative to the root folder, not `src`. So if you have another folder called `assets` in your root (i.e same level as `src`) then the references will need to start with `./assets/...` not `../assets/`

```
project-folder
 ∟ src
	∟ index.js
 ∟ assets
	∟ picture.jpg
 ∟ package.json
```

package.json
```javascript
	"start": "node ./src/index.js"
```

then you start your process by:

```bash
.../project-folder > npm run start
```

then the reference to `project-folder/assets/picture.jpg` will need to be:

```javascript
'./assets/picture.jpg' // NOT '../assets/picture.jpg'
```


In the next version, it will throw an error if it cannot find the file.

**Comment by catur515** [comment]
Try this... 
--------------------------------------------------
![image](https://user-images.githubusercontent.com/22145610/94895973-a98bc300-04b6-11eb-86e5-d805933eea5f.png)

let image_local = await base64fromLocal(process.cwd()+'/public/images/bg-title-01.jpg');
await client.sendImage(message.from, image_local, 'filename.jpg', 'bla bla bla....').then((result)=>{
    console.log("send image")
}).catch((erro)=>{
      console.error("Error when sending image"); //return object error
});

async function base64fromLocal(filename){
  const ffs = require('fs').promises;
  const img = await ffs.readFile(filename,{encoding: 'base64'});
  let mime = ContentTypes[path.extname(url)];
  return "data:"+mime+";base64,"+img;
}

const ContentTypes = {
    '.ico': 'image/x-icon',
    '.html': 'text/html',
    '.js': 'application/javascript',
    '.json': 'text/json',
    '.css': 'text/css',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.wav': 'audio/wav',
    '.mp3': 'audio/mp3',
    '.svg': 'image/svg+xml',
    '.pdf': 'application/pdf',
    '.doc': 'application/doc'
}

**Comment by smashah** [comment]
thanks for the example @catur515 

@allanlisboaweb Please update to the latest version and try again. 


Closing for now.

Thanks

**Comment by allanlisboaweb** [comment]
@catur515 
Thank you for the tip!! Images work well with their function. However I am getting error when uploading videos. It displays the following error.

<img width="920" alt="Captura de Tela 2020-10-03 às 12 46 33" src="https://user-images.githubusercontent.com/37181884/94995764-d69faa80-0576-11eb-895c-bfceb730b942.png">
<img width="836" alt="Captura de Tela 2020-10-03 às 12 47 16" src="https://user-images.githubusercontent.com/37181884/94995768-e0291280-0576-11eb-92ae-9150b80f21cb.png">
[base64.txt](https://github.com/open-wa/wa-automate-nodejs/files/5321922/base64.txt)

**Comment by catur515** [comment]
@allanlisboaweb  
The file that you sent mp4.
whereas in the content type there is no list for mp4.

try adding in the content type:

."mp4" : "video / mp4"
=======================

const ContentTypes = {
    ."mp4" : "video / mp4",
    '.ico': 'image/x-icon',
    '.html': 'text/html',
    '.js': 'application/javascript',
    '.json': 'text/json',
    '.css': 'text/css',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.wav': 'audio/wav',
    '.mp3': 'audio/mp3',
    '.svg': 'image/svg+xml',
    '.pdf': 'application/pdf',
    '.doc': 'application/doc'
}


But..... I haven't tried with large files.

**Comment by allanlisboaweb** [comment]
When trying to send a video via "sendFileFromUrl" I also get flaws

<img width="1089" alt="Captura de Tela 2020-10-03 às 13 02 19" src="https://user-images.githubusercontent.com/37181884/94996086-d43e5000-0578-11eb-9fcb-274b52545b87.png">
<img width="925" alt="Captura de Tela 2020-10-03 às 13 01 51" src="https://user-images.githubusercontent.com/37181884/94996090-d7d1d700-0578-11eb-8296-6e98f001b45b.png">

**Comment by allanlisboaweb** [comment]
> @allanlisboaweb
> O arquivo que você enviou mp4.
> enquanto no tipo de conteúdo não há lista para mp4.
> 
> tente adicionar o tipo de conteúdo:
> 
> # ".mp4": "video / mp4"
> const ContentTypes = {
> '.mp4': 'video / mp4',
> '.ico': 'image / x-icon',
> '.html': 'text / html',
> '.js': 'application / javascript',
> '.json': 'text / json',
> '.css': 'text / css',
> '.png': 'imagem / png',
> '.jpg': 'image / jpeg',
> '.wav': ' audio / wav ',
> ' .mp3 ':' audio / mp3 ',
> ' .svg ':' image / svg + xml ',
> ' .pdf ':' application / pdf ',
> ' .doc ':' application / doc '
> }
> 
> Mas ... eu não tentei com arquivos grandes.

I already added the mp4 format. Base64 is ok. I still can't send it ..

**Comment by catur515** [comment]
Maybe you can try this add .mp4 in contenttype  :

const ContentTypes = {
'.mp4' : 'video/mp4',
'.ico': 'image/x-icon',
'.html': 'text/html',
'.js': 'application/javascript',
'.json': 'text/json',
'.css': 'text/css',
'.png': 'image/png',
'.jpg': 'image/jpeg',
'.wav': 'audio/wav',
'.mp3': 'audio/mp3',
'.svg': 'image/svg+xml',
'.pdf': 'application/pdf',
'.doc': 'application/doc'
}

**Comment by catur515** [comment]
what is the file size?

**Comment by allanlisboaweb** [comment]
> what is the file size?

Approximately 1mb

<img width="254" alt="Captura de Tela 2020-10-03 às 13 09 12" src="https://user-images.githubusercontent.com/37181884/94996238-b58c8900-0579-11eb-8056-7318f497ad3f.png">

**Comment by catur515** [comment]
> When trying to send a video via "sendFileFromUrl" I also get flaws
> 
> <img alt="Captura de Tela 2020-10-03 às 13 02 19" width="1089" src="https://user-images.githubusercontent.com/37181884/94996086-d43e5000-0578-11eb-9fcb-274b52545b87.png">
> 
> <img alt="Captura de Tela 2020-10-03 às 13 01 51" width="925" src="https://user-images.githubusercontent.com/37181884/94996090-d7d1d700-0578-11eb-8296-6e98f001b45b.png">


if from url treatment maybe a little different, but I haven't tried it either, try this, using request :
sori my english not so well  :D

 function base64fromUrl (url){
        const promise = new Promise((resolve, reject) => {
            request.get(url, function (error, response, body) {
                  if (!error && response.statusCode == 200) {
                      data = "data:" + response.headers["content-type"] + ";base64," + new  Buffer.from(body).toString('base64');
                      resolve (data);
                  }else{
                      resolve (0);
                  }
              });
        });
        return promise;
    }

**Comment by catur515** [comment]
![image](https://user-images.githubusercontent.com/22145610/94996481-3b86ef00-05cf-11eb-987b-210701a0f2ce.png)

Return file not video hehe...
