### ISSUE TITLE
Is it possible to logout?

### ISSUE THREAD

**Issue by lukasportal** [open-wa/wa-automate-nodejs#879]
I looked everywhere but couldn't find how to logout (disconnecting the existing number so I can scan a new one)
Any help appreciated 👍

**Comment by smashah** [comment]
@lukasportal kill the client then call create with a different session id

**Comment by darkash** [comment]
though I'm not sure how this node library flow for qr are, in the python library, you can log out from your phone and call the client get qr method to get the new qr and scan it again to log in to new number.
