### ISSUE TITLE
How to check phone number if whatsapp true?

### ISSUE THREAD

**Issue by wulandrima1** [open-wa/wa-automate-nodejs#885]
hello anyone..
How to check phone number whatsapp?
ex : 62812131415 = true ( registered whatsapp)
ex : 62812134444 = false (not registered whatsapp)

**Comment by smashah** [comment]
@wulandrima1 https://open-wa.github.io/wa-automate-nodejs/classes/client.html#checknumberstatus

based on your example:

```javascript
const is_on_whatsapp = await client.checkNumberStatus('62812131415@c.us') // returns true
const is_not_on_whatsapp = await client.checkNumberStatus('62812134444@c.us') // returns false
```
