### ISSUE TITLE
sendRawWebpAsSticker blank sticker

### ISSUE THREAD

**Issue by dandyraka** [open-wa/wa-automate-nodejs#887]
**Describe the bug**
I tried sending webp as image & file, then waited for bot response. 
Show blank sticker on bot.
For receiver, bot didn't send anything.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2039.9,
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36,
  WA_AUTOMATE_VERSION: 2.0.27,
  BROWSER_VERSION: HeadlessChrome/85.0.4183.121
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots
![image](https://user-images.githubusercontent.com/18587059/94987934-07420d00-0594-11eb-9a1f-8f040c4df652.png)

**Host (please complete the following information):**
 - OS: Android

**Additional context**

**Comment by smashah** [comment]
Please share the dataurl of the webp you're trying to send

**Comment by dandyraka** [comment]
> Please share the dataurl of the webp you're trying to send

https://pastebin.com/raw/k6CwPfus

**Comment by smashah** [comment]
@dandyraka also this method isn't really ready for use. Why not just use the normal sticker method?

**Comment by dandyraka** [comment]
I try to make animated gif to sticker.
So i convert gif to webp, and try run sendRawWebpAsSticker.
I think it will work.

Can you can make a feature gif (default on whatsapp app) to animated sticker? 
or send video as animated sticker maybe.

**Comment by smashah** [comment]
Done already

https://github.com/open-wa/wa-automate-nodejs/issues/868

**Comment by dandyraka** [comment]
![image](https://user-images.githubusercontent.com/18587059/94997029-835b4580-05d2-11eb-8a6c-4766c0ee0197.png)

I mean like this, my expect the output will be animated sticker

**Comment by smashah** [comment]
@dandyraka when WhatsApp shows you a gif it is actually an mp4 file. This is because gifs are not memory efficient.

Just use a normal gif file please.
