### ISSUE TITLE
Feature : Error send sticker

### ISSUE THREAD

**Issue by MRHRTZ** [open-wa/wa-automate-nodejs#889]
**Describe the bug**
I'm using sendImageAsSticker that catch Error: Input buffer contains unsupported image format and also using sendStickerFromUrl that catch Error: VipsOperation: class "webpsave_buffer" not found
![IMG-20201004-WA0006](https://user-images.githubusercontent.com/52845610/95006148-4ff8d500-062b-11eb-88cf-349065c66a47.jpg)

And i using latest version
![IMG-20201004-WA0007](https://user-images.githubusercontent.com/52845610/95006151-630ba500-062b-11eb-86c2-d46d4d1c5662.jpg)

**Steps to Reproduce**
1. I sending an image
2. And reply the image which command i use to convert that to sticker
3. The output must be a sticker from that image but that return [Error: Input buffer contains unsupported image format]
4. And second i sending an command which that for send sticker from url
5. The output must be sticker with url i gave but that return Error: VipsOperation: class "webpsave_buffer" not found

**create() code**
This is the code you use to create the client. e.g
```module.exports = options = (headless, start) => {
    
    const options = {
        headless: headless,
        autoRefresh: true,
        restartOnCrash: start,
        cacheEnabled: false,
        useChrome: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false,
        chromiumArgs: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--aggressive-cache-discard',
            '--disable-cache',
            '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            '--disk-cache-size=0'
        ]
    }

    return options
}
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 2.2039.9,
  PAGE_UA: WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36,
  WA_AUTOMATE_VERSION: 2.0.28,
  BROWSER_VERSION: HeadlessChrome/83.0.4103.116
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

Error log 
![IMG-20201004-WA0006](https://user-images.githubusercontent.com/52845610/95006247-913db480-062c-11eb-9970-02a897320ea9.jpg)

My code
![IMG-20201004-WA0008](https://user-images.githubusercontent.com/52845610/95006255-ba5e4500-062c-11eb-9ec9-37ef00508eba.jpg)

**Host (please complete the following information):**
 - OS: Android

**Additional context**
Just Android OS have this error, if i test with Win10 or Linux like Kali it's working fine.

**Comment by smashah** [comment]
There's an issue with your sharp install. And what do you mean you're using android os? Are you running this code on android??

**Comment by MRHRTZ** [comment]
What i gonna do with my sharp module? 

This is my sharp version
![IMG-20201007-WA0022](https://user-images.githubusercontent.com/52845610/95282130-ff7bb480-0882-11eb-8680-790276075e6d.jpg)

Before that im failed install sharp and install libvips so the sharp success installed



Yes i'm running this code from android, i'm using ubuntu LTS 18.04, that was installed on termux

**Comment by smashah** [comment]
@MRHRTZ I'm pretty sure the issues are arising from the fact that you're running this as root. 

Also please see this: https://sharp.pixelplumbing.com/install#prerequisites

I suggest waiting for #875 also.

If you find out the solution please post it here. Closing for now thanks.
