### ISSUE TITLE
Failed to send video with sendFileFromUrl

### ISSUE THREAD

**Issue by allanlisboaweb** [open-wa/wa-automate-nodejs#890]
When trying to send a video with the send file from url I get the following error:

<img width="942" alt="Captura de Tela 2020-10-04 às 12 12 59" src="https://user-images.githubusercontent.com/37181884/95019668-15983380-063d-11eb-8a5b-5f7952d4b150.png">

<img width="871" alt="Captura de Tela 2020-10-04 às 12 13 23" src="https://user-images.githubusercontent.com/37181884/95019639-de298700-063c-11eb-86c8-a95c60c42142.png">

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
