### ISSUE TITLE
Failed to start session

### ISSUE THREAD

**Issue by alexanderoskin** [open-wa/wa-automate-nodejs#900]
When I try to start a session it doesn't go up:
Authenticate to continue
Reinjecting api
WAPI Reinjected
Checking if session is valid
Client is ready
Checking client integrity
Passed Integrity Test
Client loaded in 19.536s
Installing patches -- stopped on this step

Sentry logs show 404 error code during request to this url https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/master/patches.json

But this url can be opened fine in browser.

**create() code**
```javascript
create({
            licenseKey: 'B93A683B-FB324F1F-885E4375-C1F44A08',
            sessionData: {},
            autoRefresh: true,
            disableSpins: true,
            qrLogSkip: true,
            qrTimeout: 60,
            sessionId: '799XXXXXXXX',
            skipSessionSave: true,
            logConsole: true,
            logConsoleErrors: true,
            killProcessOnBrowserClose: true
        })
```

**Expected behavior**
Session start

**DEBUG INFO**
```
Debug Info {
  WA_VERSION: 2.2039.9,
  PAGE_UA: WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36,
  WA_AUTOMATE_VERSION: 2.0.28,
  BROWSER_VERSION: Chrome/85.0.4182.0
}
```

**Host (please complete the following information):**
 - OS: macOS and Ubuntu 18.04

**Comment by smashah** [comment]
@alexanderoskin odd.

can you go to `node_modules/@open-wa/wa-automate/package.json` and changes 

```
  "patches": "https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/master/patches.json",
```

to 

```
 "patches": "https://raw.githack.com/open-wa/wa-automate-nodejs/master/patches.json"
```

then try again please.

**Comment by alexanderoskin** [comment]
404 error too and else 404 in browser
<img width="1253" alt="Снимок экрана 2020-10-06 в 11 21 04" src="https://user-images.githubusercontent.com/5063096/95176871-20320480-07c6-11eb-8107-06a71b3ca0c9.png">

**Comment by alexanderoskin** [comment]
Tried again with https://raw.githack.com/open-wa/wa-automate-nodejs/master/patches.json url and now session starts perfectly.

But got error in console

`
ConsoleMessage {
  _type: 'error',
  _text: `Refused to connect to 'https://api.ipify.org/?format=json' because it violates the following Content Security Policy directive: "connect-src 'self' data: blob: https://*.whatsapp.net https://www.facebook.com https://*.giphy.com https://*.tenor.co https://crashlogs.whatsapp.net/wa_clb_data https://crashlogs.whatsapp.net/wa_fls_upload_check https://www.bingapis.com/api/v6/images/search https://*.google-analytics.com wss://*.web.whatsapp.com wss://web.whatsapp.com https://dyn.web.whatsapp.com".\n`,
  _args: [],
  _location: { url: undefined, lineNumber: 1 }
}
`

**Comment by smashah** [comment]
You can ignore that new error. I'll change the URL in the package to the new githack url

**Comment by smashah** [comment]
@alexanderoskin is this all happening on the same network?

**Comment by smashah** [comment]
@alexanderoskin added githack cdn links in 2.0.29 Please update. Thanks
