### ISSUE TITLE
How do I send a VCard?

### ISSUE THREAD

**Issue by allanlisboaweb** [open-wa/wa-automate-nodejs#901]
I am trying to send a Vcard but on my device it is displayed that way
![WhatsApp Image 2020-10-06 at 12 34 26](https://user-images.githubusercontent.com/37181884/95224179-c5ea7100-07d0-11eb-9035-8bfe3bf63070.jpeg)

**Comment by smashah** [comment]
https://open-wa.github.io/wa-automate-nodejs/classes/client.html#sendvcard

or

https://open-wa.github.io/wa-automate-nodejs/classes/client.html#sendcontact

**Comment by allanlisboaweb** [comment]
what do I put in the vcard parameter: string ??

**Comment by allanlisboaweb** [comment]
what do I put in the vcard parameter: string ??

**Comment by allanlisboaweb** [comment]
<img width="169" alt="Captura de Tela 2020-10-07 às 16 58 53" src="https://user-images.githubusercontent.com/37181884/95381340-65d1f880-08be-11eb-9855-91da24fad78c.png">

**Comment by smashah** [comment]
@allanlisboaweb it's the vcard formatted as a string

**Comment by smashah** [comment]
https://www.npmjs.com/package/vcf#format-vcf

**Comment by allanlisboaweb** [comment]
Thanks!!!!
