### ISSUE TITLE
Easy API not sending messages.

### ISSUE THREAD

**Issue by muzammilgit** [open-wa/wa-automate-nodejs#902]
Easy API not sending messages. is license key required to send message. i am using docker

**Comment by smashah** [comment]
@muzammilgit did you open the api docs? You should be able to send messages using sendText to a contact

**Comment by muzammilgit** [comment]
yes i checked, but its not working

**Comment by smashah** [comment]
@muzammilgit did this issue just start happening or is this the first time you tried it?

**Comment by muzammilgit** [comment]
i just tried first, its sending now, only saved contact are allowed to send message?

**Comment by smashah** [comment]
@muzammilgit Yes. If you want to start a new chat I suggest reading this:

https://open-wa.github.io/wa-automate-nodejs/pages/The%20Client/licensed-features.html#sending-messages-to-non-contact-numbers

My suggestion would be to set up a website where people can explicitly start a chat with you. That way you are least likely to get reported for spam/get your account banned.

**Comment by smashah** [comment]
Please fill the issue template in the future. Thanks

**Comment by max-programming** [comment]
@smashah Can I not send messages to numbers not saved in my contact? Or can I message any number?
