### ISSUE TITLE
Block Country Codes

### ISSUE THREAD

**Issue by Correa2K** [open-wa/wa-automate-nodejs#904]
Hey, I'm coding one whatsapp bot and I want to block a certain Country Code from using it.
Does have a way to the bot block everyone with a certain Country Code that sends a message to me?

I'd seen the `contactBlock()`, but it needs a complete contactId.

srry about the simple question lol.

**Comment by smashah** [comment]
@Correa2K You can't really preemptively block them. The best solution in would be to block them as they message you in `onMessage` by using 
```javascript
if(message.from.startsWith('<country-code>')) {
await client.contactBlock(message.from);
await client.deleteChat(message.from);
}
```.

**Comment by Correa2K** [comment]
Thanks! 
it worked.
