### ISSUE TITLE
Sending Audio Files

### ISSUE THREAD

**Issue by Correa2K** [open-wa/wa-automate-nodejs#907]
Hey, 

I'm trying to send audio files using the `client.sendFile()`:
![image](https://user-images.githubusercontent.com/68694438/95335760-28517900-0886-11eb-9e87-b16a13cd82ec.png)
```
```

But it gives me the error **Error: Cannot find file. Make sure the file reference is relative or valid DataURL**: 
![image](https://user-images.githubusercontent.com/68694438/95335923-5e8ef880-0886-11eb-9128-bbd3c6e22ab6.png)
```
```

I'm not having sucess with this, does have a way to I use `fromFilePath(path.resolve())`?

**Comment by smashah** [comment]
Why is there a comma between the folder and the file? It is meant to be:

```javascript
return client.sendFile(from, `./downloads/${videoId}.mp3`, ...
```

Please make sure you're always using the latest open-wa and fill the issue template properly.

Closing as this is not an issue with open-wa
