### ISSUE TITLE
The method onAck of the cliente isn't working

### ISSUE THREAD

**Issue by tadeubarbosa** [open-wa/wa-automate-nodejs#915]
**Describe the bug**
So, all methods of Client still working, but the method onAck isn't.
Some days ago that method was working, maybe this stoped in the lasts updates.
I'd updated to the latest version today (2.0.29)

**Steps to Reproduce**
- create a client like in the demo
- connect a mobile phone
- send a message to a contact on my contact list
- open the phone and view the message
- no messages has been passed on onAck method

**create() code**
This is the code you use to create the client. e.g
```javascript
create({
    sessionId: myVariable,
    sessionDataPath: myDirVariable,
    useChrome: true,
    qrTimeout: 600,
  })
```

**Expected behavior**
I expect that when I receive and 

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2041.6',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '2.0.29',
  BROWSER_VERSION: 'Chrome/85.0.4183.121'
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - OS: Android 9 (where I run the whatsapp)
 - OS: Ubuntu 20.04 (where I run the wa-automate-nodejs)

**Additional context**

**Comment by smashah** [comment]
@tadeubarbosa Thanks for filling in the issue template thoroughly. I have issued a patch and it is working now. Thanks
