### ISSUE TITLE
Add basic documentation to generated postman collections

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#918]
At the moment, all postman collection requests link back to the documentation website. It is better to [arse the comments into the collections themselves

**Comment by joedutra** [comment]
<img src="https://media.giphy.com/media/sNZddQMtrqpS0HEEMC/giphy.gif"></img>
Man, you know it sucks, how we copy your repo, if we have functions that you don’t even have, all for free, we perform almost every day, I came from Sulla and you too, but if you look at following the week, we redid it all lib again, now you will no longer be able to copy us, you copy and keep saying that we copy, nor compete with you ours and for free and your payment

**Comment by joedutra** [comment]
I come to apologize and say that we have nothing against this, only that they accuse us of copying and we never copied anything, if someone copied it was when someone changed our lib, I apologize and the intention was not to be slandered anymore of copying something we worked on every day. just like you, we will not do that anymore.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i -D`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.2.4](https://github.com/open-wa/wa-automate-nodejs/compare/3.2.3...3.2.4) (2021-02-02)

- build(deps-dev): bump @types/marked from 1.2.1 to 1.2.2 [`#1285`](https://github.com/open-wa/wa-automate-nodejs/pull/1285)
- build(deps): bump update-notifier from 5.0.1 to 5.1.0 [`#1287`](https://github.com/open-wa/wa-automate-nodejs/pull/1287)
- Release 3.2.4 [`0fe1612`](https://github.com/open-wa/wa-automate-nodejs/commit/0fe1612bb452586046f7dceead4e88c86ac2805c)
- feat: (cli) swagger UI now has API docs built in (#918) [`0993537`](https://github.com/open-wa/wa-automate-nodejs/commit/099353720630d546cc0835a6c681a4f1a252578a)
- added twiter badge, updated wa version badge [`ae783a8`](https://github.com/open-wa/wa-automate-nodejs/commit/ae783a8eddd1d9e9f1a3ae4291dc748eb73e5b65)
