### ISSUE TITLE
src/controllers/initializer.ts

### ISSUE THREAD

**Issue by sr-marcos** [open-wa/wa-automate-nodejs#920]
![image](https://user-images.githubusercontent.com/38053209/95644167-b09c6d80-0a82-11eb-88c9-87302aee4df9.png)

**Describe the bug**
Error in line 231 change "eval" to "evaluate".

**Comment by dwikyrestu** [comment]
Yes, i change to evalute and its works (For me there's in line 332)

**Comment by smashah** [comment]
Merged + fixed thanks a lot @sr-marcos 

https://github.com/open-wa/wa-automate-nodejs/pull/919#issuecomment-706485624
