### ISSUE TITLE
client.sendRawWebpAsSticker() bug

### ISSUE THREAD

**Issue by Nurutomo** [open-wa/wa-automate-nodejs#921]
**Describe the bug**
`client.sendRawWebpAsSticker(message.from, base64webp, true)` work, but the animated webp is unknown.

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create('Imperial', {
        headless: false,
        qrRefreshS: 20,
        qrTimeout: 0,
        authTimeout: 0,
        autoRefresh: true,
        restartOnCrash: false,
        cacheEnabled: false,
        // executablePath: execPath,
        useChrome: true,
        killProcessOnBrowserClose: true,
        throwErrorOnTosBlock: false,
        chromiumArgs: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--aggressive-cache-discard',
            '--disable-cache',
            '--disable-application-cache',
            '--disable-offline-load-stale-cache',
            '--disk-cache-size=0'
        ]
    })
    .then((client) => start(client))
    .catch((err) => new Error(err))
function start(client) {
  client.onMessage((message) => {
    if (message.body !== '.sticker') return
    client.sendRawWebpAsSticker(message.from, base64webp, true) // the base64webp variable isn't dataUrl
  }
}
```

**Expected behavior**
The sticker is not blank and should be animated as it is

**DEBUG INFO**
```
Debug Info {
  WA_VERSION: '2.2041.6',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '2.0.29 UPDATE AVAILABLE: 2.0.31',
  BROWSER_VERSION: 'Chrome/85.0.4183.121'
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/18616827/95647426-85089a00-0af9-11eb-92f4-b72451536493.png)
expectation
![image](https://user-images.githubusercontent.com/18616827/95647417-699d8f00-0af9-11eb-9872-6d537396e7e1.png)

**Host (please complete the following information):**
 - OS: Windows 10 64 Bit

**Additional context**
nothing

**Comment by smashah** [comment]
There's so much information missing here. What is the raw webp. 

Are you getting the base64 from a message? If so you need to use this : https://open-wa.github.io/wa-automate-nodejs/classes/client.html#getstickerdecryptable

And why aren't you using the existing sendImageAsSticker?

https://open-wa.github.io/wa-automate-nodejs/classes/client.html#sendimageassticker

sendRawWebpAsSticker is a WIP and shouldn't be used yet.

**Comment by Nurutomo** [comment]
Yes, i get the base64 from message.

I didn't know ```sendImageAsSticker``` support animated stickers yet

but i know how to fix ```sendRawWebpAsSticker``` by adding this to ```dist/lib/wapi.js```
```js
/**
 * Send Raw Webp As Sticker
 * @param {*} webBase64 A valid webp image is required.
 * @param {*} chatId '000000000000@c.us'
 * @param metadata about the image. Based on [sharp metadata](https://sharp.pixelplumbing.com/api-input#metadata)
 */
window.WAPI.sendRawWebpAsSticker = async function (webpBase64,chatId,metadata) {
    let metatype = 'image/webp';
    if (metadata.animated) metatype = 'video/webp';
    let mediaBlob = await window.WAPI.base64ImageToFile(
        'data:'+metatype+';base64,'+webpBase64,
        'file.webp'
    );
    let encrypted = await window.WAPI.encryptAndUploadFile("sticker", mediaBlob);
    return await window.WAPI._sendSticker(encrypted, chatId, metadata);
};
```

and modifying this to ```dist/api/Client.js``` at line ```2012```
```js
return WAPI.sendRawWebpAsSticker(webpBase64, to, metadata);
```

i modify the metatype to ```video/webp``` because i reverse engineer the ```sendGiphyAsSticker``` and i found this ```base64Image.replace('data:image', 'data:video');```
```js
 try {
    const base64Image = await _0xa57c04(_0x3725ad);
    if ('GIF_NOT_FOUND' == base64Image) return base64Image;
    base64Image.replace('data:image', 'data:video');
    let file = await WAPI.base64ImageToFile(base64Image, 'sticker.webp'),
        encrypted = await WAPI.encryptAndUploadFile('sticker', file);
    return await WAPI._sendSticker(encrypted, from, {});
} catch (err) {
    return err;
}
```

**Comment by smashah** [comment]
@Nurutomo well obviously not enough has been done to 'fix' it. There is no support for issues based on mutated versions or forks of open-wa. My original comment has your answer.

To reiterate, just use https://open-wa.github.io/wa-automate-nodejs/classes/client.html#sendimageassticker

or if you want to decrypt the stickers then please use https://open-wa.github.io/wa-automate-nodejs/classes/client.html#getstickerdecryptable
