### ISSUE TITLE
Error when refocus

### ISSUE THREAD

**Issue by dhevanthareza** [open-wa/wa-automate-nodejs#923]
Hello i have some error, when doing client.forceRefocus() like this
![image](https://user-images.githubusercontent.com/31506778/95680580-eec19a80-0c04-11eb-8a35-739dfc378f64.png)
and i fixed this by edit your library code like this
![image](https://user-images.githubusercontent.com/31506778/95680586-026d0100-0c05-11eb-8249-50c112215b28.png)
can i PR this code, or i missing some configuration

**Comment by smashah** [comment]
@dhevanthareza thanks for reporting this issue but the proposed fix would break this functionality for people all over the world. I'll work on this asap and issue a patch.

**Comment by smashah** [comment]
@dhevanthareza fixed thanks
