### ISSUE TITLE
Implement a function that return the last message sent by the bot in a chat

### ISSUE THREAD

**Issue by pedrogrisolia** [open-wa/wa-automate-nodejs#924]
It would be nice if there was a function that would return the last message sent by the bot in a given chat. The currently method that I'm using is to call getAllMessagesInChat() and then loop it backwards until I find the last bot message. But, getAllMessagesInChat() takes a while to return the list of messages.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [2.0.32](https://github.com/open-wa/wa-automate-nodejs/compare/2.0.31...2.0.32) (2020-10-12)

- build(deps): bump uuid-apikey from 1.4.6 to 1.5.1 [`#928`](https://github.com/open-wa/wa-automate-nodejs/pull/928)
- build(deps-dev): bump release-it from 14.0.4 to 14.1.0 [`#929`](https://github.com/open-wa/wa-automate-nodejs/pull/929)
- build(deps): bump p-queue from 6.6.1 to 6.6.2 [`#930`](https://github.com/open-wa/wa-automate-nodejs/pull/930)
- build(deps): bump ts-json-schema-generator from 0.75.0 to 0.76.1 [`#922`](https://github.com/open-wa/wa-automate-nodejs/pull/922)
- Fix #927 [`#927`](https://github.com/open-wa/wa-automate-nodejs/issues/927)
- Release 2.0.32 [`46e1fd8`](https://github.com/open-wa/wa-automate-nodejs/commit/46e1fd82a086f5693d46dae550d7ede3d2dcf3fd)
- added `sendAudio` as alias for `sendPtt` and example in demo [`b8e4440`](https://github.com/open-wa/wa-automate-nodejs/commit/b8e44406eea77f05145ad105f5ab481b09206678)
- Feature: Implemented `getMyLastMessage` #924 [`b357b1e`](https://github.com/open-wa/wa-automate-nodejs/commit/b357b1eb1224b44e5dd2a7246e8a09d49d72e737)
- fix: patched #923 [`462fadb`](https://github.com/open-wa/wa-automate-nodejs/commit/462fadb59def59956095edda16785d6c6e2e7976)
- chore: bump wa version [`836b676`](https://github.com/open-wa/wa-automate-nodejs/commit/836b67649f40a512a907623ddadb5f1a824acfbd)

**Comment by smashah** [comment]
@pedrogrisolia https://open-wa.github.io/wa-automate-nodejs/classes/client.html#getmylastmessage

**Comment by pedrogrisolia** [comment]
> 
> 
> @pedrogrisolia https://open-wa.github.io/wa-automate-nodejs/classes/client.html#getmylastmessage

You are awesome, thanks!
