### ISSUE TITLE
Function getMe() return Unknown values

### ISSUE THREAD

**Issue by paulocorcino** [open-wa/wa-automate-nodejs#927]
**Describe the bug**
When use the function getMe return many objects with value '[Unknown]'

**create() code**
My code to get object.
```javascript
var me = await WA_CLIENT.CONNECTION.getMe();
```

**Expected behavior**
Return all information about connection

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2041.6',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '2.0.31',
  BROWSER_VERSION: 'Chrome/85.0.4183.121'
}
```

**Screenshots**
![Anotação 2020-10-12 061608](https://user-images.githubusercontent.com/7800501/95728901-77b2f300-0c52-11eb-96b1-9065723f8a73.png)

**Host (please complete the following information):**
 - OS: WINDOWS SERVER 2012 R2 and UBUNTU 18

**Comment by smashah** [comment]
@paulocorcino thanks for reporting. This should be fixed in the latest patch. Please restart your instances and report back if the patch works. thanks
