### ISSUE TITLE
Client.onAnyMessage didn't detect me (client) sending a image

### ISSUE THREAD

**Issue by Waxaranai** [open-wa/wa-automate-nodejs#935]
Hey i tried to test something with `<Client>.onAnyMessage`, im as the host client (bot) sending an `image`, but the event didn't receive it, is it should be like that? Because on `chat` type, it's working properly

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [2.1.1](https://github.com/open-wa/wa-automate-nodejs/compare/2.1.0...2.1.1) (2020-10-14)

- Fixed `getGroupAdmins` return type using proper alias. Closes #936 [`#936`](https://github.com/open-wa/wa-automate-nodejs/issues/936)
- Release 2.1.1 [`1a2d38c`](https://github.com/open-wa/wa-automate-nodejs/commit/1a2d38c14a60317dac82559e3476630bec37b4a6)
- fix `noCase` dynamic import [`b851acf`](https://github.com/open-wa/wa-automate-nodejs/commit/b851acf4cd63cbd039acd074ad33847cf2fac343)
-  #935 patched [`fe54261`](https://github.com/open-wa/wa-automate-nodejs/commit/fe5426154c4205561e56fa5cda6e4b6723d0d37d)
- Remove redundant logs when sending media [`999e0e3`](https://github.com/open-wa/wa-automate-nodejs/commit/999e0e3751360d7212b0d7f79ebd0144509e02a7)

**Comment by Waxaranai** [comment]
It's happened again in version 2.1.5

**Comment by smashah** [comment]
@Waxaranai what was the message type? Needs more info as it is working fine here.

**Comment by Waxaranai** [comment]
image

**Comment by Waxaranai** [comment]
It's my fault, my code is changed and i forgot about it

**Comment by fajarnurprasetyo** [comment]
@Waxaranai
I found that problem too, what caused it to happen?

**Comment by fajarnurprasetyo** [comment]
@smashah
please help me
why my code not catching message type image?

```
create({
    useChrome: true,
    executablePath: '/bin/google-chrome',
}).then(async (client: Client) => {
    // const me: any = await client.getMe();
    
    client.onAnyMessage((message: Message) => {
        console.log(message.type);
    });
});
```
