### ISSUE TITLE
how to get the status of qrcode read successfully? to close it on the frontend

### ISSUE THREAD

**Issue by matheusm821** [open-wa/wa-automate-nodejs#937]
What about the status if the bot is active or not?

**Comment by Waxaranai** [comment]
I've figured out how to solve this, but not yet tested.

```ts
import { ev } from "@open-wa/wa-automate";

ev.on("**", (data, sessionId, namespace) => {
    if (data === "SUCCESS" && namespace === "QR") {
        doSomething();
    }
})
```

**Comment by Waxaranai** [comment]
Or try change the `SUCCESS` to `successfulScan`

**Comment by matheusm821** [comment]
thank you!

**Comment by Waxaranai** [comment]
No problem!

**Comment by smashah** [comment]
@matheusm821 in next version https://github.com/open-wa/wa-automate-nodejs/blob/3958e86c9e08e593e2e20afde80c43c5571d5ecc/demo/index.ts#L36
