### ISSUE TITLE
Is there a way to resize the innerWidth & innerHeight for Non Headless Chrome?

### ISSUE THREAD

**Issue by Nurutomo** [open-wa/wa-automate-nodejs#943]
Currently the default innerSize is `1440 by 900`
With that size, my window cropping it (My screen resolution is `1366 by 768`)
![image](https://user-images.githubusercontent.com/18616827/96125661-1aeb5d00-0f1e-11eb-9924-c44f6c92a624.png)

Console Debugger:
![image](https://user-images.githubusercontent.com/18616827/96126925-74ec2280-0f1e-11eb-8186-5c6a3f3e8e56.png)

My expectation is the innerSize matching the windowSize

**Comment by smashah** [comment]
@Nurutomo 

You can change this in your create config

```javascript
create({
	puppeteerConfig: {
		width : 1366,
		height: 768	
	}
})
```

**Comment by Nurutomo** [comment]
similar issue https://github.com/puppeteer/puppeteer/issues/1183

**Comment by Nurutomo** [comment]
https://github.com/open-wa/wa-automate-nodejs/blob/1a2d38c14a60317dac82559e3476630bec37b4a6/src/config/puppeteer.config.ts#L1-L5

**Comment by smashah** [comment]
yep. on the todo list

**Comment by Nurutomo** [comment]
about right here needs change
https://github.com/open-wa/wa-automate-nodejs/blob/1a2d38c14a60317dac82559e3476630bec37b4a6/src/controllers/browser.ts#L15-L27

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by Nurutomo** [comment]
https://github.com/open-wa/wa-automate-nodejs/blob/dc7bcd012c6bd7d3270583aacc4c5e5513e32847/demo/index.ts#L235-L238

Uhmm...I tried the options/config above, it doesnt work. i renamed key from `viewport` to `window` and its working

**Working code**
```js
const { create, Client } = require('@open-wa/wa-automate')

create('nurutomo', {
    headless: false,
    useChrome: true,
//  viewport: {
    window: {
        width : 1280,
        height: 720
     }
}).then((client) => start(client))

function start(client = new Client()) {
    client.onAnyMessage(message => {
        let name = message.sender.pushname || message.sender.verifiedName || message.sender.formattedName
        let text = message.body || message.caption
        console.log(`(${name}) ${text}`)
    })
}
```
https://github.com/open-wa/wa-automate-nodejs/blob/dc7bcd012c6bd7d3270583aacc4c5e5513e32847/src/controllers/browser.ts#L23-L27

**Comment by smashah** [comment]
working as `viewport` in 2.1.4
