### ISSUE TITLE
Whatsapp detecting automated session?

### ISSUE THREAD

**Issue by Justice4Joffrey** [open-wa/wa-automate-nodejs#946]
**Describe the bug**

No logins I have will work headless or otherwise. Have tried personal Whatsapp in a wa-automate session vs regular browser. Automated session hangs indefinitely on 'Authenticating'. In the browser, this is the page:

Trying to reach phone
Retrying in Invalid date…

My guess is they're detecting automation - (maybe this is useful? https://infosimples.github.io/detect-headless/).

Does this warrant using puppeteer-stealth?

**Steps to Reproduce**

Try to log in any session.

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

Sessions should log in.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#usestealth

**Comment by smashah** [comment]
#942 

Please discuss further in discord

**Comment by Justice4Joffrey** [comment]
Thanks for the prompt reply. Could you please send an invite link? I don't think there's a link to the channel in the overview/docs.
