### ISSUE TITLE
Suggestion: Create a sendInstagramLink like as sendYoutubeLink

### ISSUE THREAD

**Issue by paulocorcino** [open-wa/wa-automate-nodejs#948]
@smashah I would like to do a suggestion of make an extension to function sendYoutubeLink for a new function with the name sendInstagramLink, when permitted show a link preview to Instagram video.

Sample video Instagram link how show on WhatsApp.

![image](https://user-images.githubusercontent.com/7800501/96322749-bbaa4d00-0ff0-11eb-8716-3d80d013fdbf.png)

Thank you!

**Comment by fdciabdul** [comment]
it's show automatically by whatsapp itself right ? 

you don't need any function for that

**Comment by smashah** [comment]
@paulocorcino @fdciabdul Please restart your session try again with:

https://open-wa.github.io/wa-automate-nodejs/classes/client.html#sendlinkwithautopreview

and report back if it's working for you

**Comment by smashah** [comment]
I've tested this thoroughly and it seems to be working on. Closing.
