### ISSUE TITLE
TIMEOUT problem.

### ISSUE THREAD

**Issue by realunreals** [open-wa/wa-automate-nodejs#949]
**Describe the bug**
When I create client everything is working but after 2 minutes I start getting TIMEOUT, CONNECTED again and again.... I keep getting this message for 4-5 minutes and then it stops automatically. This problem started 2 hours ago. Also I have checked on different computer, different internet and different phone but same problem. Please check screenshot.

Debug Info {
  WA_VERSION:2.2041.6,
  PAGE_UA: WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36,
  WA_AUTOMATE_VERSION: 2.1.6,
  BROWSER_VERSION: HeadlessChrome/85.0.4183.121
}
Create {
    sessionId:'test',
    useChrome: true,
    headless:true,
    throwErrorOnTosBlock:false,
    qrTimeout:40,
    authTimeout:40,
    killProcessOnBrowserClose: false,
    autoRefresh:true, 
    qrRefreshS:15, 
}
<img width="1104" alt="Screen Shot 2020-10-17 at 05 58 38" src="https://user-images.githubusercontent.com/13606459/96326978-e5d62c00-103d-11eb-8c06-e339e1ef55ee.png">

**Comment by smashah** [comment]
This is normal. It just means that the connection between your phone and the session goes on 'standby'
