### ISSUE TITLE
Feature: ID checking

### ISSUE THREAD

**Issue by smashah** [open-wa/wa-automate-nodejs#955]
Although `@c.us` and `@g.us` are well-known concepts for library users. It would be helpful if, where possible, users can add those suffixes optionally.

- [ ] All id parameters should be labelled with their corresponding type alias in camelCase.
- [x] Typescript literal types

**Comment by joedutra** [comment]
I come to apologize and say that we have nothing against this, only that they accuse us of copying and we never copied anything, if someone copied it was when someone changed our lib, I apologize and the intention was not to be slandered anymore of copying something we worked on every day. just like you, we will not do that anymore.

**Comment by smashah** [comment]
@joedutra 

> I come to apologize and say that we have nothing against this, only that they accuse us of copying and we never copied anything, if someone copied it was when someone changed our lib, I apologize and the intention was not to be slandered anymore of copying something we worked on every day. just like you, we will not do that anymore.


You're a lying plagiarizing degenerate. I can't believe you even copied the non-functional buttons code AGAIN WITH ZERO ATTRIBUTION.

https://github.com/orkestral/venom/blob/72e24d35cd8d5ff6472095b44fce79c3af0e32c6/src/lib/wapi/business/send-message-with-buttons.js#L55

Yes, a random third party named `orkestral` "changed" the lib - https://github.com/orkestral/venom/commits/91bcb297322b0ad30f14704393d7fd2b8eab1f41/src/lib/wapi/business/send-message-with-buttons.js

this third party random person somehow managed to copy code I wrote in February 2020 without your knowledge or permission: https://github.com/open-wa/wa-automate-nodejs/blob/82ee145b9d83222aa506ff3bfc72a9aacd9164da/src/lib/wapi.js#L1692

https://github.com/open-wa/wa-automate-nodejs/issues/98#issuecomment-583209949

You should be ashamed of yourself, scumbag.

**Comment by smashah** [comment]
Implemented in the latest version (3.5.0).

When `idCorrection : true` in the config, the library will automatically append `@c.us` or @g.us` to the relevant parameters. This may be helpful for js users that sometimes miss out the chat server suffixes.
