### ISSUE TITLE
typings: Client.getGroupMembers returning invalid type

### ISSUE THREAD

**Issue by Waxaranai** [open-wa/wa-automate-nodejs#959]
`Client.getGroupMembers` returning invalid type, i log the returned data are not same like the type (`Contact[]`)
 I want use `id` property from `Contact` but in the type it returning a `Object` and the real result are just a `string`

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️

**Comment by smashah** [comment]
I think you're using https://open-wa.github.io/wa-automate-nodejs/classes/client.html#getgroupmembersid

**Comment by Waxaranai** [comment]
> I think you're using https://open-wa.github.io/wa-automate-nodejs/classes/client.html#getgroupmembersid

Nope, just test it by yourself

**Comment by Waxaranai** [comment]
Here is the thing, when i do `client.getGroupMembers(groupId)` it returning a `Contact`. in the type of `Contact.Id` it return a object, but in here it returns a string

**Comment by smashah** [comment]
The types aren't fully consistent right now because things change all the time. I suggest just going with whatever is outputted. You just have to be a bit flexible.
