### ISSUE TITLE
Not a contact error after upgrade to v3

### ISSUE THREAD

**Issue by kodmanyagha** [open-wa/wa-automate-nodejs#960]
v3 wapi.js:

	window.WAPI.sendMessage = async function (id, message) {
	    if(id==='status@broadcast') return 'Not able to send message to broadcast';
	    let chat = WAPI.getChat(id);
	    if((!chat && !id.includes('g') || chat.msgs.models.length == 0)) {
	        var contact = WAPI.getContact(id)
	        if(!contact || !contact.isMyContact) return 'Not a contact';
	        await Store.Chat.find(Store.Contact.get(id).id)
	        chat = WAPI.getChat(id);
	    }
	    if (chat !== undefined) {
	            // return WAPI.sendMessageReturnId(chat,message).then(id=>{return id})
	            return await chat.sendMessage(message).then(_=>chat.lastReceivedKey._serialized);
	    } 
	    return false;
	    };

please remove that shit: !contact.isMyContact
why are you checking this contact is my or not? if someone from outside wrote me from whatsapp this stupid condition is blocking me. sendMessage method shoud be like that:

	window.WAPI.sendMessage = async function (id, message) {
	    if(id==='status@broadcast') return 'Not able to send message to broadcast';
	    let chat = WAPI.getChat(id);
	    if((!chat && !id.includes('g') || chat.msgs.models.length == 0)) {
	        var contact = WAPI.getContact(id)
	        if(!contact) return 'Not a contact'; // LOOK HERE
	        await Store.Chat.find(Store.Contact.get(id).id)
	        chat = WAPI.getChat(id);
	    }
	    if (chat !== undefined) {
	            // return WAPI.sendMessageReturnId(chat,message).then(id=>{return id})
	            return await chat.sendMessage(message).then(_=>chat.lastReceivedKey._serialized);
	    } 
	    return false;
	    };

**Comment by kodmanyagha** [comment]
I think you don't making good tests when releasing new versions. You're increasing version very day. This is not a good programming experience. Please make more tests.

**Comment by smashah** [comment]
Please downgrade to https://github.com/open-wa/wa-automate-nodejs/releases/tag/2.1.6

**Comment by kodmanyagha** [comment]
yes I downgraded. will you handle this issue for next versions?
