### ISSUE TITLE
Getting Group Info after the group is created

### ISSUE THREAD

**Issue by shubham0804** [open-wa/wa-automate-nodejs#962]
**Describe the bug**
I'm trying to get the group info (owner & invite link after I have created a group) but I'm getting an error wherein getting the group using getChatById returns false & getGroupInviteLink returns "TypeError: Cannot read property 'isGroup' of undefined". This is being done in a post request through Express. I get correct info returned from getChatById & getGroupInviteLink after the request is done but not during.

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
`function start(client) {
app.post('/testGroup', async (req, res, next) => {

        const createGroup = await client.createGroup(`Group No.${Math.random()}`, selfNo);
        console.log(createGroup)

        const group = await client.getChatById(createGroup.gid._serialized);
        console.log(group);

        const groupInviteLink = await client.getGroupInviteLink(createGroup.gid.user);
        console.log(groupInviteLink);
    })
}`

**Expected behavior**
The group should be created and groupInfro and invite link should be retrieved. Group is being created but the other two actions are not taking place.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '2.2041.6' 
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36'
  WA_AUTOMATE_VERSION: '2.1.1 UPDATE AVAILABLE: 3.0.0'
  BROWSER_VERSION: 'HeadlessChrome/86.0.4240.0'  
}
```

**Screenshots**
Result of the console.logs
![error console](https://user-images.githubusercontent.com/52071475/96368090-7b250d80-116f-11eb-9f15-bf7ee262955f.PNG)

**Host (please complete the following information):**
 - OS: [e.g. iOS] Android

**Additional context**
I'm stuck at this for quite a while. I'd really appreciate it if anybody could point out why this error is occuring.

**Comment by smashah** [comment]
@shubham0804 I think the issue is that you're creating a group with yourself. Please try this again with a different participant and see if that works.

**Comment by shubham0804** [comment]
@smashah It still gives the same error if I try with a different participant id and remove my id.

But adding about 3-5 sec delay after creating a group and before getting it's info and invite link works, though I'm not sure why, but I can make do with this solution.

`app.post('/testGroup', async (req, res, next) => {

        const createGroup = await client.createGroup(`Group No.${Math.random()}`, ['9876543211@c.us']);
        console.log(createGroup);

        **const wait = async(ms) => { return new Promise(resolve => setTimeout(resolve, ms)); }
        await wait(5000);**
        
        const group = await client.getChatById(createGroup.gid._serialized);
        console.log(group);
    
        const groupInviteLink = await client.getGroupInviteLink(createGroup.gid._serialized);
        console.log(groupInviteLink);
    })`

Credits: @Waxaranai

**Comment by smashah** [comment]
Maybe it's best if when you create a group it waits until the group is in the store before resolving (if it results in 200). This will result in a longer wait for createGroup but at least you won't have to manually wait in the code (which although it's a good workaround it's not really a solution to this problem)

**Comment by Waxaranai** [comment]
Using a `new Promise((resolve, reject) => doSomething())` something like this ?

**Comment by shubham0804** [comment]
> Maybe it's best if when you create a group it waits until the group is in the store before resolving (if it results in 200). This will result in a longer wait for createGroup but at least you won't have to manually wait in the code (which although it's a good workaround it's not really a solution to this problem)

@smashah I'm not sure what you mean by "until the group is in store" & "it results in 200". The getChatById always returns 200, even if it is not found. 

I edited the the createGroup function in wapi.js and added a wait of 3-5 sec to it, instead of my app,  before returning the group info and that works too. Is that what you meant?

**Comment by smashah** [comment]
@shubham0804 please try again in about 5 minutes. It should work as expected now

**Comment by shubham0804** [comment]
@smashah  It's working now. Thanks a lot! I really appreciate it.
