### ISSUE TITLE
Unable send video via URL on v3.0.0 and latest

### ISSUE THREAD

**Issue by aidilaryanto** [open-wa/wa-automate-nodejs#964]
**Describe the bug**

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
I'll put the same amount of effort into this issue. Thanks

**Comment by aidilaryanto** [comment]
Its already fixed?

**Comment by smashah** [comment]
@aidilaryanto  you didn't bother filling out the template which is actually the absolute minimum you could've done to help solve this issue. So I did less than minimum effort also and didn't bother looking into this issue.
