### ISSUE TITLE
Logout on Authenticating

### ISSUE THREAD

**Issue by Justice4Joffrey** [open-wa/wa-automate-nodejs#965]
**Describe the bug**

Whatsapp web sessions from this library are now getting redirected on login to a `/logout` endpoint on login which looks to me very much like bot prevention (I've been using this library fine for 6 months).

New tabs on that puppeteer browser work fine, simple puppeteer usage such as below works fine -
```
import puppeteer from "puppeteer";
const browser = await puppeteer.launch({headless: false})
const page = await browser.newPage()
await page.goto("https://web.whatsapp.com/")
```

I've tried the obvious things such as changing the userAgent, using stealth mode, removing all chromium arguments from the config and still seems to be triggering this issue. I'm going to keep going further through the code but would imagine you might have some good ideas what to try/where to look.

If you want to discuss further on discord could you please send me details to access the channel? I can't find them in the readmes/docs.

Previously #946 

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  WA_AUTOMATE_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

![Screenshot from 2020-10-19 14-47-40](https://user-images.githubusercontent.com/16974025/96459796-71a4af80-121a-11eb-9a6a-f91d10642265.png)

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
Click on the discord badge I'm the reader please thanks
