### ISSUE TITLE
Feature: ui improvements for non headless puppeteer

### ISSUE THREAD

**Issue by Nurutomo** [open-wa/wa-automate-nodejs#967]
# Feature Suggestions
This is my suggestion for non headless puppeteer

## Dark Mode Session
Allow `localStorage.theme` to be saved on the session 
I always turning on Dark Mode manually everytime i continue my session.

## Auto Resize InnerWindow
The puppeteer `innerWindow` seems to have fixed `innerWindow` size (similar issue https://github.com/puppeteer/puppeteer/issues/3688)

**Comment by smashah** [comment]
regarding the second point can you add this to your config:

```javascript
{
	...
    defaultViewport: null,
	...
}
```

as you can see here: https://github.com/open-wa/wa-automate-nodejs/blob/f53e6ae7c92fe5a95b574bb7362eb0d508bd6b41/src/controllers/browser.ts#L160

config is spread into the puppeteer launch options

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.0.3](https://github.com/open-wa/wa-automate-nodejs/compare/3.0.2...3.0.3) (2020-10-20)

- Release 3.0.3 [`5ea83ee`](https://github.com/open-wa/wa-automate-nodejs/commit/5ea83eefd470081af33259833245f2126c54cf70)
- `darkMode` is now GA #967 [`32c8fcf`](https://github.com/open-wa/wa-automate-nodejs/commit/32c8fcf979f94bcde335afa5e4f9def6b878e845)
- `deleteSessionDataOnLogout` set to false by default. onStateChanged no longer detects logout [`b68b20c`](https://github.com/open-wa/wa-automate-nodejs/commit/b68b20cb0ee6de67be6d2728c0bf295a9629d3cf)
- possible fix for #968 [`1a3b374`](https://github.com/open-wa/wa-automate-nodejs/commit/1a3b3740040bbfd2f3e03d9d1735185fcb473cc9)
- possible fix for #962 [`7612d20`](https://github.com/open-wa/wa-automate-nodejs/commit/7612d2033ecd7ce9a9dcea7c4bbc6228b7828719)

**Comment by smashah** [comment]
Regarding dark mode, you can just use this now: https://open-wa.github.io/wa-automate-nodejs/classes/client.html#darkmode

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [3.0.4](https://github.com/open-wa/wa-automate-nodejs/compare/3.0.3...3.0.4) (2020-10-20)

- Release 3.0.4 [`76593e4`](https://github.com/open-wa/wa-automate-nodejs/commit/76593e465d56428fe5185867a855772f0f425c46)
- config: allow setting `defaultViewport` to null for a resizable window #967 [`7e81752`](https://github.com/open-wa/wa-automate-nodejs/commit/7e81752e0a1d96dec45ba48cecd4eef2cd68d3c6)

**Comment by smashah** [comment]
> regarding the second point can you add this to your config:
> 
> ```js
> {
> 	...
>     defaultViewport: null,
> 	...
> }
> ```
> 
> as you can see here:
> 
> https://github.com/open-wa/wa-automate-nodejs/blob/f53e6ae7c92fe5a95b574bb7362eb0d508bd6b41/src/controllers/browser.ts#L160
> 
> config is spread into the puppeteer launch options
> 
> Edit: nvm that doesn't work. Can you try to figure out which pptr configs work please.

This should work now. Report back if working for you thanks

**Comment by Nurutomo** [comment]
> > regarding the second point can you add this to your config:
> > ```js
> > {
> > 	...
> >     defaultViewport: null,
> > 	...
> > }
> > ```
> > 
> > 
> > as you can see here:
> > https://github.com/open-wa/wa-automate-nodejs/blob/f53e6ae7c92fe5a95b574bb7362eb0d508bd6b41/src/controllers/browser.ts#L160
> > 
> > config is spread into the puppeteer launch options
> > Edit: nvm that doesn't work. Can you try to figure out which pptr configs work please.
> 
> @Nurutomo This should work now. Report back if working for you thanks

It works. but, the dark mode Wallpaper doesn't load. Just plain dark-gray color
![image](https://user-images.githubusercontent.com/18616827/96615077-08f92800-132b-11eb-94f3-cae55e3fe4a6.png)

**Comment by smashah** [comment]
@Nurutomo it's not only dark gray, I can see the doodles there. If you want to change the background colour you can use this https://open-wa.github.io/wa-automate-nodejs/classes/client.html#setchatbackgroundcolourhex

**Comment by Nurutomo** [comment]
That feature requires *INSIDERS LICENSE KEY* , which is i doesn't have one.
nvm 'bout the wallpaper
