### ISSUE TITLE
Feature: get group info from invite link

### ISSUE THREAD

**Issue by Waxaranai** [open-wa/wa-automate-nodejs#969]
Return the group status, gid, description from the valid invite link

**Comment by AlenSaito1** [comment]
[https://open-wa.github.io/wa-automate-nodejs/classes/client.html#inviteinfo](https://open-wa.github.io/wa-automate-nodejs/classes/client.html#inviteinfo)

**Comment by smashah** [comment]
thanks @AlenSaito1 closing
