### ISSUE TITLE
Feature Proposal: make setGroupToAdminOnly and setGroupEditToAdminOnly feature Generaly Available

### ISSUE THREAD

**Issue by Waxaranai** [open-wa/wa-automate-nodejs#970]
Another open source project have this features

**Comment by joedutra** [comment]
<img src="https://media.giphy.com/media/sNZddQMtrqpS0HEEMC/giphy.gif"></img>
Man, you know it sucks, how we copy your repo, if we have functions that you don’t even have, all for free, we perform almost every day, I came from Sulla and you too, but if you look at following the week, we redid it all lib again, now you will no longer be able to copy us, you copy and keep saying that we copy, nor compete with you ours and for free and your payment
