### ISSUE TITLE
Feature Proposal: make setProfilePic to Generaly Available

### ISSUE THREAD

**Issue by Waxaranai** [open-wa/wa-automate-nodejs#971]
Another open source project have this features

**Comment by joedutra** [comment]
<img src="https://media.giphy.com/media/sNZddQMtrqpS0HEEMC/giphy.gif"></img>
Man, you know it sucks, how we copy your repo, if we have functions that you don’t even have, all for free, we perform almost every day, I came from Sulla and you too, but if you look at following the week, we redid it all lib again, now you will no longer be able to copy us, you copy and keep saying that we copy, nor compete with you ours and for free and your payment

**Comment by Waxaranai** [comment]
> ![](https://camo.githubusercontent.com/630e8919e368dd2f0865e9e3b8ae6c24c9bd6d0e9ea0457b21b6e8a1afce8327/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f734e5a6464514d7472717053304845454d432f67697068792e676966)
> Man, you know it sucks, how we copy your repo, if we have functions that you don’t even have, all for free, we perform almost every day, I came from Sulla and you too, but if you look at following the week, we redid it all lib again, now you will no longer be able to copy us, you copy and keep saying that we copy, nor compete with you ours and for free and your payment

You know why u opened this issue? @smashah told me to do it on discord

**Comment by smashah** [comment]
04c2e36
