### ISSUE TITLE
A way to test beta builds of WhatsApp Web?

### ISSUE THREAD

**Issue by tinyCoder32** [open-wa/wa-automate-nodejs#974]
Hi, thank you for your great efforts in this project.
Is there a way to try the early beta features of WhatsApp Web? For example, wabetainfo website is always releasing screenshots of features, although they are not an official party related to WhatsApp.

How are they doing it?
Example:
https://wabetainfo.com/whatsapp-web-2-2043-7-whats-new/

**Comment by smashah** [comment]
@tinyCoder32 A lot of feature flags are connected to your phone app. So if you have the beta app on your phone, it will unlock some features on the web app. There is another level which only WA devs have access to.
