### ISSUE TITLE
#ASK

### ISSUE THREAD

**Issue by dhevanthareza** [open-wa/wa-automate-nodejs#977]
hello, i want to ask, can i get the whatsapp qrcode as text so i can show in my webpage

**Comment by rzkytmgr** [comment]
did you mean, open web whatsapp with chrome/chromium ? if yes,

You can use `configObject` instead,
`const configObject = { headless: false }`

**Comment by dhevanthareza** [comment]
no, in this version of plugin we can scan the qr code from terminal, what i want is gettin the qrcode text show i can show it on my own webpage app

**Comment by smashah** [comment]
@dhevanthareza you can get the qr code png using the `ev`

https://open-wa.github.io/wa-automate-nodejs/pages/The%20Client/launch-events/capture-qr.html
