### ISSUE TITLE
How do I prevent message content from being written to the console when using the SendText method?

### ISSUE THREAD

**Issue by can1871** [open-wa/wa-automate-nodejs#988]
How do I prevent message content from being written to the console when using the SendText method?

**Comment by kmirea** [comment]
find and comment out or delete the Console.Log  command

**Comment by can1871** [comment]
> Console.Log komutunu bulun ve yorumlayın veya silin

I searched but couldn't find it so I wrote it here.

**Comment by kmirea** [comment]
Yeah i too couldnt find in a quick search, but it would be part of the API code.

Do you use any other projects with this ? or WA-AUTOMATE alone.  In my case the logging happens in third party code

**Comment by smashah** [comment]
This really shouldn't be happening. What is your config?

**Comment by smashah** [comment]
Actually, please fill in the issue template

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️

**Comment by can1871** [comment]
I apologize I could not look for the notification. My problem still persists. When the message comes, it writes the message content on the screen and I do not do this. Can anyone inform which piece of code the module is in?

**Comment by smashah** [comment]
@can1871 please fill in the issue template
