### ISSUE TITLE
getConnectionState often returning CONNECTED

### ISSUE THREAD

**Issue by lbertoncello** [open-wa/wa-automate-nodejs#989]
I'm trying to detect when WhatsApp Web is disconnected using the method getConnectionState(), so I can connect again. 

The problem is that often the getConnectionState method is returning 'CONNECTED', even after I manually disconnect using WA Business on smartphone.

After setting headless to false I've realized that WhatsApp Web keeps endlessly loading when I disconnect.

```
Debug Info {
  WA_VERSION: '2.2043.8',
  PAGE_UA: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
  WA_AUTOMATE_VERSION: '3.0.6 UPDATE AVAILABLE: 3.0.6',
  BROWSER_VERSION: 'Chrome/86.0.4240.111'
}
```

**Screenshots**

[The screen when I disconnect on smartphone](https://i.imgur.com/TknXWWO.png)

**Comment by smashah** [comment]
@lbertoncello this is a bug from WA's end. A fix was attempted in V3.0.0 but it prematurely detected a logout event. More work needs to be done to detect a logout properly. I've got a few ideas.

**Comment by lbertoncello** [comment]
> @lbertoncello this is a bug from WA's end. A fix was attempted in V3.0.0 but it prematurely detected a logout event. More work needs to be done to detect a logout properly. I've got a few ideas.

@smashah In the current version (3.0.6) there is someway you recommend me to handle the problem of users getting disconected?

**Comment by smashah** [comment]
@lbertoncello Are you completely sure this is happening in v3.0.6?

The premature logout (and session delete) regression was fixed here: https://github.com/open-wa/wa-automate-nodejs/commit/b68b20cb0ee6de67be6d2728c0bf295a9629d3cf and released in https://github.com/open-wa/wa-automate-nodejs/releases/tag/3.0.3

**Comment by lbertoncello** [comment]
> @lbertoncello Are you completely sure this is happening in v3.0.6?
> 
> The premature logout (and session delete) regression was fixed here: [b68b20c](https://github.com/open-wa/wa-automate-nodejs/commit/b68b20cb0ee6de67be6d2728c0bf295a9629d3cf) and released in https://github.com/open-wa/wa-automate-nodejs/releases/tag/3.0.3

@smashah Yes, I do. You can check in the screenshot bellow. But, after a few tests, I realized that in v3.0.6 this only happens when headless is set to false.

**Screenshots**

[wa-automate version](https://i.imgur.com/6wCL0CG.png)

**Comment by smashah** [comment]
For future reference please just upload screenshots into GitHub itself.

This (https://github.com/open-wa/wa-automate-nodejs/issues/989#issuecomment-717203091) seems like an entirely separate problem and is causing confusion in this issue ticket.

As far as detecting a logout, previously you would be able to tell when UNPAIRED is fired but recently some people experience UNPAIRED randomly. Best to let this issue sit for a while till it's clearer what is going on in your end and what can be done. As for definitively determining when the user has logged out, there will be a few possible fixes to that which I will work on by the end of this week.

**Comment by lbertoncello** [comment]
> For future reference please just upload screenshots into GitHub itself.
> 
> This ([#989 (comment)](https://github.com/open-wa/wa-automate-nodejs/issues/989#issuecomment-717203091)) seems like an entirely separate problem and is causing confusion in this issue ticket.
> 
> As far as detecting a logout, previously you would be able to tell when UNPAIRED is fired but recently some people experience UNPAIRED randomly. Best to let this issue sit for a while till it's clearer what is going on in your end and what can be done. As for definitively determining when the user has logged out, there will be a few possible fixes to that which I will work on by the end of this week.

OK, I will wait until the next version and try again. Thanks for your attention.

**Comment by smashah** [comment]
Closing thanks
